import type { Level } from '../engine'

/**
 * Action ou Vérité — défis « Action ». Ceux qui impliquent quelqu’un d’autre
 * supposent toujours son accord : chacun peut refuser ou passer son tour.
 */
export const dares: Record<Level, string[]> = {
  soft: [
    // Existants
    'Imite quelqu’un de la pièce jusqu’à ce qu’on devine qui c’est.',
    'Parle avec un accent pendant les trois prochains tours.',
    'Fais ta meilleure danse pendant 30 secondes.',
    'Chante le refrain de la dernière chanson que tu as écoutée.',
    'Laisse le groupe écrire ta prochaine story.',
    'Fais 15 squats en racontant ta journée.',
    'Raconte une blague. Si personne ne rit, recommence.',
    'Fais une déclaration d’amour dramatique à un objet de la pièce.',
    'Montre la dernière photo de ta galerie.',
    'Mime un film jusqu’à ce que quelqu’un trouve.',
    'Parle uniquement en chantant jusqu’à ton prochain tour.',
    'Fais un compliment sincère à chaque personne présente.',
    'Fais le cri de ton animal préféré.',
    'Garde une grimace pendant une minute.',
    'Appelle un ami et chante-lui joyeux anniversaire.',
    'Commente ta propre vie comme un match de foot pendant 30 secondes.',
    'Fais un défilé de mannequin d’un bout à l’autre de la pièce.',
    'Laisse quelqu’un te coiffer comme il veut.',
    'Écris un poème de quatre vers sur la personne à ta gauche.',
    'Échange un vêtement avec la personne à ta droite jusqu’au prochain tour.',
    // Imitations et voix
    'Imite un dessin animé de ton enfance jusqu’à ce que le groupe trouve lequel.',
    'Parle comme un robot pendant les deux prochains tours.',
    'Présente ta journée comme un présentateur de journal télévisé, pendant une minute.',
    'Imite un bébé qui goûte un citron pour la première fois.',
    'Imite un dragon enrhumé qui essaie de cracher du feu.',
    'Raconte ta matinée avec la voix d’un narrateur de documentaire animalier.',
    'Parle comme un pirate pendant les trois prochains tours.',
    'Imite un chat qui veut absolument sortir de la maison.',
    'Commente chaque geste de la personne à ta droite comme un reporter sportif, si elle accepte.',
    'Lis ta dernière notification avec la voix d’un méchant de dessin animé.',
    'Pousse ton meilleur cri de Tarzan.',
    'Imite le bruit d’une vieille voiture qui refuse de démarrer.',
    'Parle avec une voix très aiguë jusqu’à ton prochain tour.',
    'Parle avec une voix très grave jusqu’à ton prochain tour.',
    'Chuchote tout ce que tu dis pendant les deux prochains tours.',
    'Parle en verlan pendant une minute.',
    'Parle avec l’accent anglais pendant deux tours.',
    'Imite un perroquet qui répète tout ce que dit la personne à ta gauche, pendant deux tours.',
    'Fais l’annonce d’un haut-parleur de gare, avec un retard complètement absurde.',
    'Imite la façon de rire de chaque personne de la pièce.',
    'Fais la voix d’un guide de musée pour présenter un objet banal de la pièce.',
    // Chant
    'Chante l’hymne de ton pays comme si tu étais à l’opéra.',
    'Chante le générique d’un dessin animé, avec les gestes.',
    'Chante « Joyeux anniversaire » en voix d’opéra à la personne de ton choix.',
    'Chante un tube en remplaçant toutes les paroles par « miaou ».',
    'Chante un refrain la bouche fermée : le groupe doit deviner le titre.',
    'Invente une chanson de 20 secondes sur la personne à ta gauche.',
    'Rappe le contenu de ton sac ou de tes poches.',
    'Fais du beatbox pendant 20 secondes.',
    'Chante un tube comme si tu étais sous la douche, avec la brosse à cheveux en micro.',
    'Chante une chanson de Noël avec une voix de rockstar.',
    'Fais un duo chanté avec la personne de ton choix, si elle est partante.',
    'Chante une berceuse à un coussin pour l’endormir.',
    'Chante la chanson de ton choix en changeant de voix à chaque phrase.',
    // Danse
    'Danse comme un robot cassé pendant 20 secondes.',
    'Danse sans musique pendant 30 secondes, avec la plus grande conviction.',
    'Danse comme si tu avais des fourmis dans les vêtements.',
    'Improvise une chorégraphie sur la chanson choisie par le groupe.',
    'Danse au ralenti, comme dans un film, pendant 20 secondes.',
    'Fais un moonwalk d’un bout à l’autre de la pièce.',
    'Danse en gardant les pieds collés au sol.',
    'Fais le twist pendant 20 secondes, sans t’arrêter.',
    'Danse comme un pingouin qui a trop chaud.',
    'Invente une danse et donne-lui un nom. Le groupe doit ensuite la refaire.',
    // Mime
    'Mime une action du quotidien de façon exagérée jusqu’à ce qu’on devine laquelle.',
    'Mime un métier jusqu’à ce que le groupe le trouve.',
    'Mime un animal du zoo sans faire de bruit.',
    'Mime une chanson, le groupe doit retrouver le titre.',
    'Mime une scène de film d’action au ralenti.',
    'Mime un sport bizarre que tu viens d’inventer et explique-nous les règles.',
    'Mime quelqu’un qui prépare un plat compliqué, sans dire un mot.',
    'Joue une dispute avec toi-même en changeant de voix à chaque réplique.',
    'Mime un dessin animé, le groupe a 30 secondes pour le trouver.',
    'Mime quelqu’un qui est coincé dans une boîte invisible.',
    // Impro
    'Invente une excuse absurde pour un retard à un rendez-vous imaginaire.',
    'Vends un stylo au groupe comme dans une publicité télé.',
    'Invente un slogan pour chaque personne de la pièce.',
    'Invente une légende sur l’origine du canapé.',
    'Raconte la fin d’un film célèbre en la changeant complètement.',
    'Fais un discours de remerciement comme si tu venais de gagner un Oscar.',
    'Fais un discours de campagne pour devenir roi ou reine de la soirée.',
    'Annonce la météo de demain sur le ton le plus dramatique possible.',
    'Fais une visite guidée de la pièce comme si c’était un musée.',
    'Défends pendant 30 secondes l’idée que les chaussettes sont inutiles.',
    'Joue l’interview d’un pingouin qui rêve de devenir acteur.',
    'Invente un nouveau sport et explique ses règles en 30 secondes.',
    'Raconte une histoire de 30 secondes avec trois objets pris dans la pièce.',
    'Invente une recette absurde et présente-la comme un chef étoilé.',
    'Fais une publicité pour la ville où tu habites.',
    'Raconte le début d’un conte de fées en le situant dans un supermarché.',
    'Donne un nom et une histoire à un objet de la pièce.',
    'Fais semblant d’être un serveur de restaurant chic et prends la commande du groupe.',
    'Présente-toi comme si tu postulais pour devenir super-héros ou super-héroïne.',
    'Joue un entretien d’embauche pour devenir meilleur ami ou meilleure amie du groupe.',
    'Fais semblant d’être une statue de musée jusqu’à ton prochain tour.',
    // Téléphone
    'Montre ton fond d’écran et explique pourquoi tu l’as choisi.',
    'Prends une photo de groupe avec le filtre le plus ridicule possible.',
    'Montre la photo la plus drôle de ta galerie.',
    'Lis à voix haute la dernière note enregistrée dans ton téléphone.',
    'Envoie un message d’amour à un membre de ta famille.',
    'Envoie un selfie grimaçant à un ami proche, sans explication.',
    'Mets la chanson de ton choix : le groupe doit en deviner le titre en moins de 10 secondes.',
    'Change ton fond d’écran pour une photo d’animal choisie par le groupe, jusqu’à demain.',
    'Poste une story du groupe qui fait des grimaces, si tout le monde est d’accord.',
    'Envoie à un ami un vocal de dix secondes où tu miaules.',
    'Montre les trois derniers emojis que tu as utilisés et invente une histoire avec.',
    'Prends une photo de toi dans le style d’une pochette d’album.',
    'Ouvre ta galerie au hasard et raconte l’histoire de la cinquième photo.',
    'Fais un selfie avec chaque personne de la pièce, si elle accepte.',
    'Montre la dernière application que tu as téléchargée et défends ce choix.',
    'Enregistre un message vocal d’annonce de ton prochain exploit sportif imaginaire.',
    // Compliments
    'Fais un compliment à la personne à ta gauche sans utiliser les mots « super » ni « gentil ».',
    'Dis ce que tu admires chez la personne en face de toi.',
    'Remercie une personne présente pour un souvenir précis.',
    'Trouve un surnom affectueux pour chaque personne de la pièce.',
    'Décris la personne à ta droite avec trois adjectifs positifs.',
    'Écris un petit mot gentil pour la personne de ton choix et lis-le à voix haute.',
    'Raconte un souvenir drôle que tu as vécu avec la personne en face de toi.',
    'Dis quel super-pouvoir tu offrirais à chaque personne de la pièce, et pourquoi.',
    // Sport léger
    'Fais la planche pendant 30 secondes.',
    'Fais 10 pompes, ou 10 abdos au choix.',
    'Fais la chaise contre le mur pendant 30 secondes en récitant ta poésie préférée.',
    'Fais 10 sauts sur place en comptant à l’envers.',
    'Fais le tour de la pièce sur la pointe des pieds sans te faire entendre.',
    'Fais cinq pas les yeux fermés en ligne droite, le groupe juge ta trajectoire.',
    'Essaie de te toucher le nez avec la langue.',
    'Fais le tour de la pièce avec un livre en équilibre sur la tête.',
    'Fais un bras de fer avec la personne de ton choix, si elle accepte.',
    'Fais un concours de regards sans rire avec la personne en face de toi, si elle accepte.',
    'Joue à pierre-feuille-ciseaux contre la personne de ton choix : le perdant fait 5 squats.',
    'Fais le plus de jumping jacks possible en 20 secondes.',
    'Tiens en équilibre sur un pied pendant 30 secondes.',
    'Fais le plus de grimaces différentes en 20 secondes.',
    'Garde une cuillère en équilibre sur le nez pendant 10 secondes.',
    'Touche tes orteils puis lève les bras vers le plafond dix fois, en chantant.',
    // Défis entre joueurs
    'Fais deviner un mot à la personne de ton choix en le mimant, si elle accepte.',
    'Lance un défi d’imitation à la personne à ta droite : le groupe vote pour le meilleur.',
    'Joue une scène de théâtre de 30 secondes avec la personne de ton choix, avec son accord.',
    'Invente une poignée de main secrète avec la personne de ton choix, avec son accord.',
    'Fais un high five créatif avec chaque joueur, avec son accord.',
    'Dessine le portrait de la personne en face de toi en 30 secondes, avec son accord.',
    'Défie quelqu’un à un concours de grimaces : le groupe désigne le gagnant.',
    'Fais une course de marche arrière avec la personne de ton choix, si elle accepte.',
    'Joue avec la personne de ton choix au jeu du miroir pendant 20 secondes, si elle accepte.',
    'Fais un duel de poésie avec la personne à ta gauche : trois vers chacun, si elle accepte.',
    // Contraintes
    'Parle sans dire « oui », « non » ni « euh » jusqu’à ton prochain tour.',
    'Parle de toi à la troisième personne jusqu’à ton prochain tour.',
    'Termine chaque phrase par « Majesté » pendant les deux prochains tours.',
    'Réponds à toutes les questions par une question jusqu’à ton prochain tour.',
    'Tiens bon une minute sans rire pendant que le groupe essaie de te faire craquer.',
    'Dessine un chat les yeux fermés et montre ton œuvre au groupe.',
    'Dessine ton animal préféré avec ta main non dominante.',
    'Écris ton prénom dans les airs avec ton coude.',
    'Dis un virelangue choisi par le groupe trois fois de suite, sans te tromper.',
    'Épelle ton prénom à l’envers.',
    'Cite dix animaux en dix secondes.',
    'Compte jusqu’à vingt en alternant le français et une autre langue.',
    'Construis la tour la plus haute possible avec les objets autour de toi en 30 secondes.',
    'Mets ta veste ou ton pull à l’envers jusqu’à la fin de la partie.',
    'Mets des chaussettes sur tes mains jusqu’à ton prochain tour.',
    'Berce un coussin comme un bébé et chante-lui une berceuse.',
    'Parle à ta main comme à une marionnette pendant une minute.',
    'Fais un clin d’œil à chaque personne de la pièce sans éclater de rire.',
    'Fais un tour de magie improvisé, même complètement raté.',
    'Récite l’alphabet à l’envers le plus vite possible.',
    'Parle sans bouger les lèvres pendant 30 secondes.',
    'Marche comme un crabe d’un bout à l’autre de la pièce.',
    'Raconte une histoire de 30 secondes où tous les mots commencent par la même lettre.',
    'Fais un discours d’adieu à ton plat préféré.',
    'Nomme dix fruits sans reprendre deux fois la même première lettre.',
    'Fais un rire de sorcière pendant dix secondes.',
    'Salue chaque personne de la pièce d’une façon différente.',
    'Mets-toi dans la peau d’un acteur de théâtre qui a oublié son texte, pendant 30 secondes.',
    'Garde les yeux fermés jusqu’à ton prochain tour.',
    'Fais un selfie avec un objet de la pièce comme si c’était ton meilleur ami.',
    'Fais un discours de deux minutes sur ton animal préféré, sans jamais le nommer.',
  ],
  spicy: [
    // Existants
    'Lis à voix haute ton dernier message envoyé.',
    'Laisse la personne à ta gauche envoyer un emoji à un contact de son choix.',
    'Fais ta meilleure technique de drague à quelqu’un ici.',
    'Montre ton historique de recherche des dernières 24 h.',
    'Envoie « tu me manques » à la troisième conversation de ta messagerie.',
    'Fais un slow de 30 secondes avec la personne de ton choix.',
    'Raconte ton pire date en le mimant.',
    'Fais un bisou sur la joue de la personne de ton choix.',
    'Laisse le groupe regarder tes dernières recherches Instagram.',
    'Imite ton ex pendant 30 secondes.',
    'Dis à quelqu’un ici ce que tu as pensé la première fois que tu l’as vu.',
    'Danse de façon sexy pendant 20 secondes.',
    'Masse les épaules de la personne à ta droite pendant une minute.',
    'Laisse quelqu’un poster une story depuis ton téléphone.',
    'Fais une déclaration à la personne en face de toi, un genou à terre.',
    'Montre ta dernière conversation avec ta mère.',
    'Échange ton haut avec quelqu’un jusqu’à la fin de la partie.',
    'Fais un câlin de 10 secondes à la personne de ton choix.',
    'Lis avec conviction une bio d’appli de rencontre choisie par le groupe.',
    'Choisis quelqu’un : il te pose une question, tu dois répondre honnêtement.',
    // Drague
    'Lance la pire phrase d’accroche que tu connaisses à la personne de ton choix.',
    'Fais un compliment de drague à la personne en face de toi, sans rire.',
    'Fais ton regard le plus séducteur à la personne de ton choix pendant 10 secondes, si elle accepte.',
    'Fais la cour à la personne de ton choix pendant 30 secondes, avec son accord.',
    'Chante une chanson d’amour à quelqu’un ici en le regardant dans les yeux, si il ou elle accepte.',
    'Écris un mot doux sur un papier et donne-le à la personne de ton choix.',
    'Écris la bio d’appli de rencontre de la personne de ton choix : le groupe valide ou corrige.',
    'Joue un premier rendez-vous raté avec la personne de ton choix, avec son accord.',
    'Joue une demande en mariage théâtrale à la personne de ton choix, si elle est partante.',
    'Joue une scène de rupture dramatique avec la personne de ton choix, avec son accord.',
    'Joue la scène de rencontre d’une comédie romantique avec la personne de ton choix, si elle accepte.',
    'Joue une scène de jalousie exagérée avec la personne à ta droite, si elle accepte.',
    'Présente-toi comme si tu étais sur une appli de rencontre, en cinq phrases maximum.',
    'Fais un clin d’œil séducteur à chaque personne de la pièce, sans rougir.',
    'Joue le rôle d’un prétendant timide qui n’ose pas parler à la personne de ton choix, avec son accord.',
    'Dis « je t’aime » de dix façons différentes à la personne en face de toi.',
    'Dis « je t’aime » dans trois langues, avec les gestes qui vont avec.',
    'Fais un selfie de couple avec la personne de ton choix, avec son accord, sans le poster.',
    'Fais un baisemain à la personne de ton choix, avec son accord.',
    'Fais la bise à chaque personne de la pièce, avec leur accord.',
    'Imite ta façon de draguer en soirée, sans te ménager.',
    'Choisis une chanson d’amour et dédie-la à quelqu’un d’ici.',
    'Fais une déclaration d’amour en chantant à la personne de ton choix, si elle accepte.',
    'Fais une tirade romantique de 20 secondes à un coussin comme s’il s’agissait de ton ou ta partenaire.',
    'Invente une phrase d’accroche personnalisée pour chaque personne de la pièce.',
    'Fais une demande de rendez-vous poétique à la personne de ton choix, qui peut refuser.',
    'Écris un poème d’amour de quatre vers sur la personne à ta gauche et lis-le avec émotion.',
    'Dédicace une chanson à l’amour de ta vie imaginaire, avec le décor qui va avec.',
    // Câlins, slows et contacts doux
    'Danse un slow avec la personne de ton choix, avec son accord, en gardant une feuille de papier entre vous.',
    'Danse un slow avec une chaise comme si c’était l’amour de ta vie.',
    'Donne un câlin de 15 secondes à la personne de ton choix, avec son accord.',
    'Fais un câlin de groupe, pour ceux qui acceptent.',
    'Tiens la main de la personne à ta gauche jusqu’à ton prochain tour, avec son accord.',
    'Masse les mains de la personne de ton choix pendant 30 secondes, avec son accord.',
    'Laisse la personne de ton choix te masser les épaules pendant 30 secondes, si elle accepte.',
    'Pose ta tête sur l’épaule de la personne à ta gauche pendant 20 secondes, avec son accord.',
    'Fais un câlin à la personne qui te réconforterait le mieux en cas de coup dur, avec son accord.',
    'Reste dos à dos avec la personne de ton choix pendant 20 secondes, avec son accord.',
    'Fais un massage du cuir chevelu à la personne de ton choix pendant 20 secondes, si elle accepte.',
    'Fais un câlin de retrouvailles ultra dramatique avec la personne de ton choix, si elle est d’accord.',
    'Danse une valse avec la personne de ton choix, avec son accord.',
    'Danse un tango de 20 secondes avec la personne de ton choix, si elle accepte.',
    'Porte la personne de ton choix sur ton dos jusqu’à l’autre bout de la pièce, avec son accord et sans te faire mal.',
    'Passe un bras autour des épaules de la personne de ton choix pendant ton prochain tour, avec son accord.',
    'Fais une photo romantique à la personne de ton choix, dans une pose de cinéma, avec son accord.',
    // Gêne et honte
    'Raconte ton premier baiser avec tous les détails gênants.',
    'Raconte ta pire honte en soirée.',
    'Raconte ton pire râteau en le jouant.',
    'Montre ta playlist la plus honteuse et chante un titre.',
    'Montre ton dernier selfie sauvegardé et justifie-le.',
    'Raconte le message que tu regrettes le plus d’avoir envoyé.',
    'Imite ta façon de réagir quand tu es amoureux ou amoureuse.',
    'Raconte ton rêve le plus étrange impliquant quelqu’un de la pièce, sans citer de nom si tu préfères.',
    'Fais ton plus beau sourire charmeur sans cligner des yeux pendant 10 secondes.',
    'Prends un selfie avec ta meilleure tête de séducteur et montre-le au groupe.',
    'Révèle un truc que tu as fait uniquement pour impressionner quelqu’un.',
    'Avoue ton plus gros mensonge à un rendez-vous galant.',
    'Raconte ton pire cadeau offert ou reçu pour la Saint-Valentin.',
    'Raconte un moment où tu as été jaloux ou jalouse sans l’avouer.',
    'Avoue la chose la plus bizarre que tu aies faite pour attirer l’attention de quelqu’un.',
    'Raconte ton premier amour en le mimant.',
    'Avoue ce que tu as fait la dernière fois que tu t’es senti ridicule devant quelqu’un qui te plaisait.',
    'Lis à voix haute le plus vieux message que tu as dans une conversation avec un ami proche.',
    'Fais un compte rendu honnête de ta dernière tentative de séduction.',
    'Révèle ton plus gros fou rire gênant avec quelqu’un qui te plaisait.',
    // Révélations
    'Désigne la personne de la pièce avec qui tu t’entendrais le mieux en couple, et dis pourquoi.',
    'Dis ce que tu trouves le plus craquant chez la personne en face de toi, avec son accord.',
    'Décris ton type de personne idéale en détail, sans rien oublier.',
    'Dis la phrase la plus romantique que tu aies jamais entendue.',
    'Donne ton meilleur conseil de séduction, avec démonstration.',
    'Dis un truc que tu n’as jamais osé dire à quelqu’un d’ici.',
    'Dis quelle célébrité tu trouves la plus charmante et fais-nous son imitation.',
    'Décris ton rendez-vous romantique idéal comme si tu étais agent immobilier.',
    'Révèle la chose qui te fait craquer en premier chez quelqu’un.',
    'Dis ce qui te fait le plus fondre dans un message de quelqu’un qui te plaît.',
    'Dis quelle chanson d’amour résume le mieux ta vie amoureuse, et chante-la.',
    'Cite trois qualités chez quelqu’un qui te font craquer à tous les coups.',
    'Cite trois « red flags » qui te font fuir immédiatement, en les mimant.',
    'Dis quelle est la plus belle déclaration d’amour que tu aies lue ou vue dans un film.',
    'Dis quel détail d’une personne te fait sourire sans que tu saches pourquoi.',
    'Révèle ton premier crush de collège, sans le nommer, mais avec les détails.',
    'Dis ce que tu espères trouver chez ton ou ta futur(e) partenaire, en trois mots.',
    // Téléphone et messages
    'Envoie « J’ai pensé à toi aujourd’hui » à un ami proche, sans explication.',
    'Envoie un emoji cœur à la personne avec qui tu parles le plus ces temps-ci.',
    'Envoie un vocal de dix secondes à un ami proche où tu lui dis à quel point il ou elle compte.',
    'Renomme un contact en « Mon amour » jusqu’à la fin de la soirée.',
    'Montre le dernier selfie que tu as pris et raconte pourquoi tu l’as fait.',
    'Montre la dernière photo que tu as likée sur un réseau social.',
    'Lis à voix haute un statut ou une légende de photo que tu regrettes aujourd’hui.',
    'Montre les noms des personnes avec qui tu as échangé le plus de messages cette semaine.',
    'Poste une story où tu fais une déclaration d’amour à ta pizza ou à ton plat préféré.',
    'Envoie « On se voit bientôt ? » à un ami que tu n’as pas vu depuis longtemps.',
    'Lis à voix haute la dernière note vocale que tu as envoyée à quelqu’un de proche.',
    'Écris un message de drague pour la personne à ta gauche et laisse-la décider si elle l’envoie à quelqu’un.',
    'Montre la dernière conversation que tu as eue avec un ami proche, sans rien cacher.',
    'Laisse la personne à ta droite choisir une photo de ta galerie qu’elle montrera à tout le monde.',
    'Montre l’application que tu consultes le plus quand tu es seul ou seule.',
    'Montre la dernière personne que tu as cherchée sur un réseau social, sans commenter.',
    'Appelle un ami proche et dis-lui que tu l’adores, sans explication.',
    // Jeux de regard et de rôle
    'Regarde la personne en face de toi dans les yeux pendant 30 secondes sans rire, si elle accepte.',
    'Joue un coup de foudre au premier regard avec la personne de ton choix, avec son accord.',
    'Joue le rôle d’un ou d’une prétendant(e) très maladroit(e) devant la personne de ton choix, avec son accord.',
    'Mime un baiser langoureux avec ta main, avec le sérieux d’un acteur.',
    'Récite une réplique de film romantique avec toute l’émotion possible.',
    'Fais une scène de ménage jouée avec la personne de ton choix, avec son accord.',
    'Fais semblant d’être un couple qui se retrouve après dix ans avec la personne de ton choix, avec son accord.',
    'Joue une scène de balcon de Roméo et Juliette avec la personne de ton choix, si elle accepte.',
    'Joue une scène de film romantique sous la pluie, avec bruitages, avec la personne de ton choix si elle accepte.',
    'Joue une rencontre dans un ascenseur coincé avec la personne de ton choix, avec son accord.',
    'Fais un compliment de quelqu’un qui te voit pour la première fois, à la personne de ton choix.',
    'Dis à la personne en face de toi ce que tu lui offrirais pour un premier rendez-vous idéal.',
    'Fais la pose la plus romantique possible pour un portrait d’amoureux, avec la personne de ton choix si elle accepte.',
    'Chuchote un compliment dans l’oreille de la personne de ton choix, avec son accord.',
    'Fais le portrait chinois de la personne en face de toi, en trois comparaisons.',
    'Fais passer un message de drague de main en main jusqu’à la personne de ton choix.',
    'Dis à la personne de ton choix le plus beau souvenir que tu as d’elle.',
    'Donne un surnom tendre à la personne de ton choix et garde-le toute la soirée.',
    'Fais un compliment sincère à la personne la plus timide de la pièce, avec douceur.',
    'Décris le style de la personne à ta droite comme le ferait un styliste enthousiaste.',
    'Fais une photo de toi avec le regard le plus séducteur possible et montre-la au groupe.',
    'Prends la main de la personne de ton choix et fais une lecture des lignes de la main romantique, avec son accord.',
    'Fais une déclaration à la personne de ton choix en utilisant uniquement des noms d’aliments.',
    'Fais la bise à la personne la plus éloignée de toi en traversant la pièce, avec son accord.',
    'Joue la scène du premier baiser d’un film, mais en t’arrêtant à un mètre de distance, avec accord.',
    'Prépare un petit discours de demande en mariage pour la personne de ton choix, si elle accepte, sans exagération.',
    'Tente de faire rire la personne de ton choix en moins de 30 secondes avec ta meilleure blague de drague.',
    'Écris ton prénom sur la main de la personne de ton choix avec ton doigt, avec son accord.',
    'Danse une danse du ventre de 15 secondes pour faire rire le groupe.',
    'Fais un coup de foudre mimé avec un objet de la pièce.',
    'Récite les paroles d’une chanson d’amour comme un poème, sans musique.',
    'Fais un massage de dix secondes aux épaules à chaque personne de la pièce qui accepte.',
    // Compléments
    'Fais semblant de te réveiller à côté de la personne de ton choix dans une comédie romantique, avec son accord.',
    'Raconte comment tu aimerais être demandé en rendez-vous, avec la mise en scène.',
    'Fais un compliment à chaque personne en commençant par « Ce qui me plaît chez toi, c’est… ».',
    'Mime la scène d’un baiser sous la neige, avec bruitages, devant le groupe.',
    'Dis quel prénom tu donnerais à un chien si tu devais le choisir avec la personne de ton choix, avec son accord.',
    'Décris le plus beau texto que tu aies reçu, en le jouant avec émotion.',
    'Rejoue l’instant où tu as compris que tu étais amoureux ou amoureuse pour la première fois.',
    'Fais une déclaration d’amour à la lune, avec lyrisme, en regardant par la fenêtre.',
    'Dis ce que tu penses du fait de faire le premier pas, puis fais-le : lance une discussion avec la personne de ton choix.',
    'Dédie un haïku romantique à la personne à ta droite et lis-le avec sérieux.',
    'Fais ton plus beau numéro de charme à un objet de la pièce.',
  ],
  hot: [
    // Existants (consentement précisé)
    'Embrasse la personne de ton choix, si elle est d’accord, là où elle le veut.',
    'Retire un vêtement, en musique.',
    'Murmure quelque chose de coquin à l’oreille de la personne à ta gauche, si elle accepte.',
    'Masse le cou de la personne de ton choix pendant une minute, si elle accepte.',
    'Mime ta position préférée, habillé.',
    'Laisse quelqu’un t’écrire un mot sur le bras au feutre.',
    'Fais une danse lascive de 20 secondes pour la personne de ton choix, si elle accepte.',
    'Décris ton fantasme à la personne en face de toi, si elle est d’accord.',
    'Retire un vêtement de ton choix jusqu’à la fin de la partie.',
    'Fais un suçon à la personne de ton choix, si elle est d’accord.',
    'Embrasse le cou de quelqu’un ici, avec son accord.',
    'Mange un fruit de la façon la plus sensuelle possible.',
    'Fais un baiser de cinéma de 10 secondes à la personne de ton choix, si elle accepte.',
    'Les yeux bandés, devine qui te prend la main, avec l’accord de chacun.',
    'Fais ton meilleur gémissement.',
    'Assieds-toi sur les genoux de quelqu’un jusqu’à ton prochain tour, s’il ou elle accepte.',
    'Envoie un message coquin à ton ou ta partenaire, ou passe ton tour.',
    'Embrasse le doigt de la personne de ton choix, le plus lentement possible, si elle accepte.',
    'Décris ta dernière fois en trois mots.',
    'Donne une petite fessée à la personne de ton choix, si elle est d’accord.',
    // Baisers
    'Embrasse la main de la personne de ton choix, avec son accord, comme dans un film d’époque.',
    'Embrasse le creux du poignet de la personne de ton choix, si elle accepte.',
    'Fais un bisou sur le lobe de l’oreille de la personne de ton choix, avec son accord.',
    'Embrasse la personne de ton choix sur la bouche pendant 5 secondes, uniquement si elle est d’accord.',
    'Fais un baiser sur le front de la personne de ton choix, avec une tendresse appuyée, si elle accepte.',
    'Embrasse l’avant-bras de la personne de ton choix en remontant lentement, avec son accord.',
    'Fais un bisou dans la nuque de la personne de ton choix, si elle accepte.',
    'Envoie un baiser volant à chaque personne de la pièce, avec ton regard le plus intense.',
    'Fais un baiser d’adieu de fin de film à la personne de ton choix, avec son accord.',
    'Embrasse la joue de la personne à ta droite très, très lentement, avec son accord.',
    'Joue à pierre-feuille-ciseaux : le perdant embrasse la main du gagnant, si les deux acceptent.',
    'Fais un baiser sur la paume de la main de la personne de ton choix, avec son accord.',
    'Fais un bisou dans le creux du cou de la personne de ton choix, si elle est d’accord.',
    'Embrasse l’épaule de la personne de ton choix, par-dessus ses vêtements, avec son accord.',
    'Embrasse la personne de ton choix dans les cheveux, doucement, avec son accord.',
    'Embrasse un coussin comme si c’était l’être aimé, puis passe-le à ton voisin.',
    // Souffles et murmures
    'Souffle doucement dans le cou de la personne de ton choix, avec son accord.',
    'Murmure ce que tu aimes chez la personne de ton choix à son oreille, avec son accord.',
    'Chuchote un compliment sensuel à l’oreille de chaque personne de la pièce, avec leur accord.',
    'Murmure ton prénom à l’oreille de la personne de ton choix d’une voix très sensuelle, avec son accord.',
    'Murmure la phrase la plus séduisante que tu connaisses à l’oreille de la personne à ta droite, si elle accepte.',
    'Dis « bonsoir » à la personne de ton choix de la voix la plus suave possible.',
    'Lis la météo de demain d’une voix très sensuelle.',
    'Lis une liste de courses comme si c’était un poème érotique.',
    'Lis une réplique de film romantique d’une voix grave et sensuelle.',
    'Demande l’heure à la personne de ton choix de la façon la plus séduisante possible.',
    'Dis « passe-moi le sel » de la manière la plus sensuelle possible.',
    'Murmure un secret coquin à l’oreille de la personne de ton choix, avec son accord.',
    'Chuchote ta plus belle promesse de soirée à la personne en face de toi, avec son accord.',
    'Joue un animateur de radio de nuit à la voix très suave, en annonçant la prochaine chanson.',
    'Dis une phrase d’accroche coquine à la personne de ton choix, en la regardant dans les yeux, si elle accepte.',
    // Massages
    'Masse les épaules de la personne de ton choix pendant une minute, avec son accord.',
    'Masse le dos de la personne de ton choix, par-dessus ses vêtements, pendant une minute, avec son accord.',
    'Masse les mains de la personne de ton choix pendant deux minutes, avec son accord.',
    'Masse les pieds de la personne de ton choix pendant une minute, si elle est d’accord.',
    'Masse le cuir chevelu de la personne de ton choix pendant 30 secondes, avec son accord.',
    'Masse les tempes de la personne de ton choix en la regardant dans les yeux, si elle accepte.',
    'Fais-toi masser le dos par la personne de ton choix, par-dessus tes vêtements, si elle accepte.',
    'Laisse la personne à ta gauche te masser la nuque pendant une minute, si elle accepte.',
    'Fais un massage des avant-bras à la personne de ton choix, avec son accord.',
    'Masse doucement les mains de ton ou ta partenaire pendant une minute, ou passe ton tour.',
    'Masse les épaules de deux personnes différentes pendant 30 secondes chacune, avec leur accord.',
    'Masse la nuque de la personne en face de toi lentement, avec son accord.',
    // Danses
    'Fais une danse sensuelle de 30 secondes sur la musique choisie par le groupe.',
    'Danse collé-serré avec la personne de ton choix pendant 30 secondes, uniquement si elle est d’accord.',
    'Danse un tango sensuel avec la personne de ton choix, avec son accord.',
    'Fais une danse lascive en tournant autour de la personne de ton choix, tout habillé, avec son accord.',
    'Fais une vague avec ton corps pendant 15 secondes, avec sérieux.',
    'Fais un déhanché de 20 secondes, sans rire.',
    'Danse sur les genoux de la personne de ton choix pendant 10 secondes, avec son accord.',
    'Fais une danse du ventre sensuelle de 20 secondes pour le groupe.',
    'Danse avec une chaise comme si c’était ton ou ta partenaire.',
    'Fais un slow collé-serré de 30 secondes avec la personne de ton choix, avec son accord.',
    'Fais un effeuillage d’un seul vêtement, sur la musique du groupe.',
    'Fais un défilé de mannequin sensuel dans la pièce, avec un regard de braise.',
    'Danse avec la personne de ton choix en imitant un couple de danseurs de salsa, si elle est d’accord.',
    'Danse comme dans un clip de R’n’B, avec la voix et le regard qui vont avec.',
    'Fais une danse lente, yeux dans les yeux, avec la personne de ton choix, avec son accord.',
    // Vêtements (jamais de nudité)
    'Retire tes chaussettes de la façon la plus sensuelle possible.',
    'Retire ta veste ou ton pull de la façon la plus sexy possible.',
    'Enlève un accessoire (montre, bague, ceinture, écharpe) avec une lenteur très sensuelle.',
    'Défais ta coiffure de la façon la plus sensuelle possible.',
    'Aide la personne de ton choix à retirer sa veste, avec son accord.',
    'Mets ta chemise ou ton haut à l’envers, puis remets-le le plus sensuellement possible.',
    'Retire un vêtement de ton choix, puis remets-le dans la même minute avec le même style.',
    'Enlève tes chaussures en prenant la pose d’un mannequin de couverture de magazine glamour.',
    'Garde ta veste sur une seule épaule jusqu’à ton prochain tour.',
    'Retire ta chaussure et ta chaussette et fais un défilé pied nu, avec le plus de sensualité possible.',
    'Échange un vêtement avec la personne de ton choix pendant 10 minutes, avec son accord.',
    'Ôte ta montre ou un bijou en regardant la personne en face de toi dans les yeux.',
    // Caresses et gestes
    'Caresse doucement la joue de la personne de ton choix, avec son accord.',
    'Passe doucement tes doigts dans les cheveux de la personne de ton choix, avec son accord.',
    'Dessine du doigt une lettre dans le dos de la personne de ton choix, avec son accord. Elle doit la deviner.',
    'Écris un mot coquin dans le dos de la personne de ton choix avec ton doigt, avec son accord. Elle doit le deviner.',
    'Caresse l’avant-bras de la personne à ta gauche pendant 20 secondes, avec son accord.',
    'Prends la personne de ton choix dans tes bras pendant 20 secondes, avec son accord.',
    'Prends la main de la personne de ton choix et fais-lui un baiser, avec son accord.',
    'Pose la main sur la joue de la personne de ton choix et regarde-la dans les yeux sans rire, avec son accord.',
    'Danse un slow avec la personne de ton choix, avec son accord, en gardant les yeux fermés.',
    'Fais un câlin très long de 30 secondes à la personne de ton choix, avec son accord.',
    'Joue avec les cheveux de la personne de ton choix pendant 20 secondes, avec son accord.',
    'Prends la personne de ton choix par la taille et fais un tour de danse, avec son accord.',
    'Fais passer un bisou de main en main jusqu’à la personne de ton choix, avec l’accord de tous.',
    'Appuie ton front contre celui de la personne de ton choix pendant 10 secondes, avec son accord.',
    'Prends place à côté de la personne de ton choix, tête sur son épaule, jusqu’à ton prochain tour, avec son accord.',
    // Regards et ambiance
    'Regarde la personne de ton choix dans les yeux pendant 30 secondes sans rire, avec son accord.',
    'Fais ton regard le plus sensuel à chaque personne de la pièce, avec ton plus beau sourire en coin.',
    'Prends la pose d’un mannequin de parfum en regardant le groupe, avec la voix off qui va avec.',
    'Fais un clin d’œil appuyé à la personne que tu trouves la plus séduisante ici, si elle est d’accord.',
    'Souris de façon espiègle à la personne de ton choix, sans rien dire, pendant 20 secondes.',
    'Mime un baiser langoureux avec un oreiller, avec toute la passion possible.',
    'Joue une scène de coup de foudre avec la personne de ton choix, avec son accord, qui finit par un baiser sur la joue.',
    'Fais-toi photographier dans la pose la plus sexy possible, habillé, sans poster la photo.',
    'Joue la scène où deux personnes se rapprochent pour s’embrasser, avec la personne de ton choix, si elle accepte.',
    'Prépare une scène de séduction de 20 secondes avec la personne de ton choix, avec son accord, qui reste respectueuse.',
    'Prends un selfie dans une pose sensuelle, habillé, et montre-le au groupe.',
    'Mime un glaçon qui glisse dans le cou de la personne de ton choix, avec son accord. Bruitages obligatoires.',
    // Confidences
    'Raconte ton meilleur baiser et ce qui l’a rendu inoubliable.',
    'Raconte l’endroit le plus insolite où tu as embrassé quelqu’un.',
    'Dis quelle partie du corps tu remarques en premier chez quelqu’un.',
    'Décris le baiser idéal, avec les gestes.',
    'Dis ce qui te fait craquer physiquement chez quelqu’un, avec franchise.',
    'Décris ton rendez-vous romantique idéal d’une voix sensuelle.',
    'Dis la phrase la plus coquine que tu connaisses, sans rougir.',
    'Dis ce que tu trouves le plus séduisant chez la personne en face de toi, avec son accord.',
    'Raconte ton fantasme le plus romantique, sans détails explicites.',
    'Raconte ta soirée la plus torride, sans entrer dans les détails.',
    'Décris le moment où tu as su que tu étais attiré ou attirée par quelqu’un.',
    'Dis quel est le geste le plus sensuel selon toi, et fais-le.',
    'Dis quelle chanson te met dans l’ambiance, et fais-la écouter au groupe.',
    'Avoue ta plus grande tentation lors d’une soirée, sans citer de nom.',
    'Avoue ton plus gros coup de cœur physique, sans citer de nom.',
    'Révèle quelle tenue te rend irrésistible selon toi.',
    'Avoue quel genre de baiser tu préfères : doux, passionné, volé ?',
    'Raconte ta première nuit blanche à discuter avec quelqu’un qui te plaisait.',
    'Dis ce que tu ferais pour surprendre ton ou ta partenaire un soir de Saint-Valentin.',
    'Raconte comment tu as fait ou raté ta première approche avec quelqu’un qui te plaisait.',
    // Messages au partenaire (jamais à quelqu’un d’autre)
    'Envoie « Je pense à ce soir » à ton ou ta partenaire, ou passe ton tour.',
    'Envoie un vocal sensuel de 5 secondes à ton ou ta partenaire, ou passe ton tour.',
    'Envoie un emoji coquin à ton ou ta partenaire, ou passe ton tour.',
    'Envoie un message qui commence par « J’ai très envie de… » à ton ou ta partenaire, ou passe ton tour.',
    'Écris à ton ou ta partenaire ce que tu aimerais faire avec lui ou elle ce week-end, ou passe ton tour.',
    'Envoie un selfie séducteur, habillé, à ton ou ta partenaire, ou passe ton tour.',
    'Envoie « Tu me manques, rentre vite » à ton ou ta partenaire, ou passe ton tour.',
    // Jeux entre joueurs
    'Joue au jeu du miroir sensuel avec la personne de ton choix pendant 20 secondes, avec son accord.',
    'Fais un duel de séduction avec la personne de ton choix, avec son accord : le groupe vote.',
    'Fais deviner une chanson sensuelle à la personne de ton choix en la fredonnant à l’oreille, avec son accord.',
    'Fais un défi du premier qui rit : regards intenses avec la personne de ton choix, avec son accord.',
    'Choisis une personne qui te lit une phrase coquine de son choix sur son téléphone, uniquement si elle accepte.',
    'Fais un concours de la plus belle voix sensuelle avec la personne de ton choix, avec son accord.',
    'Fais un bisou à chaque joueur sur la joue, avec leur accord.',
    'Donne un bisou sur la joue à la personne de ton choix en prenant la pose d’un acteur de série.',
    'Fais danser deux personnes qui acceptent, un slow collé-serré de 20 secondes.',
    'Joue le jeu de la bouteille avec un seul bisou sur la joue, avec l’accord des deux personnes.',
    'Joue une scène de séduction dans un ascenseur avec la personne de ton choix, avec son accord.',
    'Invente un cocktail sans alcool très sensuel et présente-le d’une voix charmeuse.',
    'Fais un compliment sensuel à chaque personne qui accepte d’en recevoir un.',
    'Attribue à chaque personne un titre de film romantique qui lui va bien, avec le sourire.',
    'Choisis quelqu’un qui te donne un bisou sur la main, si les deux acceptent.',
    'Donne à la personne de ton choix un surnom très coquin mais gentil, avec son accord.',
    'Ferme les yeux et laisse la personne de ton choix te toucher le bout du doigt, avec ton accord, puis devine qui c’est.',
    'Fais un bisou volant à la personne de ton choix en lui disant « On se reverra ».',
    'Laisse la personne de ton choix te choisir une pose de séducteur à tenir 15 secondes, avec ton accord.',
    'Fais semblant de séduire un fruit devant tout le monde, et mange-le avec élégance.',
    'Lis à voix haute une phrase d’amour au hasard sur ton téléphone, comme si c’était un poème sensuel.',
    'Chuchote un compliment à chaque personne, de ta gauche à ta droite, avec leur accord.',
  ],
}
