import type { Level } from '../engine'

/** Questions profondes — de quoi lancer de vraies conversations. */
export const deepTalk: Record<Level, string[]> = {
  soft: [
    'Quel souvenir d’enfance te fait encore sourire aujourd’hui ?',
    'Quelle est la chose dont tu es le plus fier·e, et que personne ne remarque ?',
    'Si tu pouvais dîner avec ta version de dix ans, que lui dirais-tu ?',
    'Quel conseil aimerais-tu avoir reçu plus tôt dans ta vie ?',
    'Quelle petite habitude te rend vraiment heureux·se au quotidien ?',
    'Quel endroit te donne le sentiment d’être exactement à ta place ?',
    'Quelle qualité chez toi aimerais-tu que les autres voient davantage ?',
    'Quel défaut as-tu fini par apprécier chez toi ?',
    'Quelle journée de ta vie rejouerais-tu sans hésiter ?',
    'Qu’est-ce qui te donne de l’énergie quand tout va mal ?',
    'Quelle décision, petite ou grande, a le plus changé ta vie ?',
    'Si l’argent n’existait pas, que ferais-tu de tes journées ?',
    'Quelle chose rêves-tu d’apprendre un jour, juste par plaisir ?',
    'Quel est le plus beau compliment qu’on t’ait jamais fait ?',
    'Qu’est-ce qui te fait perdre la notion du temps ?',
    'Quel est le moment où tu t’es senti·e le plus libre ?',
    'Quelle personne a eu la plus grande influence sur ta façon de penser ?',
    'Qu’est-ce que tes parents t’ont transmis sans le vouloir ?',
    'Quelle valeur te semble non négociable dans ta vie ?',
    'Quel risque as-tu pris dont tu es heureux·se aujourd’hui ?',
    'Quelle peur aimerais-tu enfin laisser derrière toi ?',
    'Qu’est-ce qui te rend nostalgique rien qu’en y repensant ?',
    'Quelle chanson résume le mieux la personne que tu es ?',
    'Quel livre ou quel film a vraiment changé ta façon de voir les choses ?',
    'Si tu écrivais un livre sur ta vie, quel en serait le titre ?',
    'Quel est ton plus beau souvenir de vacances, et pourquoi celui-là ?',
    'Quelle tradition familiale aimerais-tu transmettre un jour ?',
    'Qu’est-ce que tu aimerais qu’on dise de toi à la fin de ta vie ?',
    'Quelle est la plus belle surprise que la vie t’ait réservée ?',
    'Quel talent caché possèdes-tu que peu de gens connaissent ?',
    'Dans quelle ville du monde pourrais-tu vivre sans jamais te lasser ?',
    'Quel métier aurais-tu fait si tu n’avais eu aucune contrainte ?',
    'Quel est le meilleur cadeau que tu aies jamais reçu, et pourquoi ?',
    'Qu’est-ce qui te fait te sentir vraiment écouté·e par quelqu’un ?',
    'Quelle est la leçon la plus importante que tu aies apprise à tes dépens ?',
    'Quelle version de toi-même aimerais-tu être dans cinq ans ?',
    'Qu’est-ce que tu fais pour te ressourcer quand tu es à bout ?',
    'Quel moment tout simple a pourtant marqué ta mémoire pour toujours ?',
    'Quelle est la chose la plus courageuse que tu aies faite ?',
    'Quel regret aimerais-tu transformer en leçon plutôt qu’en poids ?',
    'Si tu pouvais maîtriser instantanément une langue, laquelle choisirais-tu ?',
    'Quelle est ta définition personnelle d’une vie réussie ?',
    'Qu’est-ce qui te touche le plus chez les gens que tu admires ?',
    'Quel souvenir de classe ou d’école te revient le plus souvent ?',
    'Quelle odeur te ramène immédiatement à un moment précis de ta vie ?',
    'Quel est ton rituel du matin idéal, celui dont tu rêves ?',
    'Quelle rencontre a changé le cours de ta vie, même un tout petit peu ?',
    'Quel est l’endroit le plus calme où tu te sois jamais senti·e bien ?',
    'Quelle est la chose la plus folle que tu aies faite par curiosité ?',
    'Qu’est-ce que tu voudrais dire plus souvent aux gens que tu aimes ?',
    'Quel est le plus beau paysage que tu aies vu de tes propres yeux ?',
    'Si tu pouvais remonter le temps d’une journée, où irais-tu ?',
    'Quelle qualité cherches-tu en priorité chez un·e ami·e ?',
    'Qu’est-ce qui te fait rire de manière incontrôlable ?',
    'Quelle est la plus grande leçon que t’ont donnée tes grands-parents ?',
    'Quel compliment aimerais-tu entendre plus souvent ?',
    'Quelle passion de ton enfance as-tu abandonnée, et te manque-t-elle ?',
    'Quel est ton plus grand rêve, celui que tu n’oses pas trop dire ?',
    'Qu’est-ce que tu ferais différemment si personne ne te jugeait ?',
    'Quelle est la plus belle preuve d’amitié que tu aies reçue ?',
    'Qu’est-ce qui te donne le sentiment d’avoir bien rempli ta journée ?',
    'Quelle est la chose la plus utile que tu aies apprise hors de l’école ?',
    'Quel objet de ta vie a une valeur sentimentale énorme pour toi ?',
    'Si tu devais choisir un seul mot pour décrire cette année, ce serait lequel ?',
    'Quel moment de ta vie te semble avoir été un vrai tournant ?',
    'Quelle est la plus belle chose que quelqu’un ait faite pour toi ?',
    'Qu’est-ce qui, chez toi, a le plus changé depuis tes vingt ans ?',
    'Quelle est ta plus grande source d’inspiration en ce moment ?',
    'Quel genre de parent, d’oncle ou de tante rêves-tu d’être ?',
    'Quel endroit de ton enfance aimerais-tu revoir une dernière fois ?',
    'Quelle règle de vie t’es-tu fixée et que tu essaies de respecter ?',
    'Quel est ton plus grand talent de survie en société ?',
    'Quelle activité te fait te sentir pleinement vivant·e ?',
    'Quel est le plus beau jour de ta vie jusqu’ici, et que s’est-il passé ?',
    'Qu’est-ce qu’un bon week-end représente pour toi, dans les détails ?',
    'Comment aimerais-tu que tes proches te décrivent à un inconnu ?',
    'Quelle petite victoire de cette année te rend fier·e ?',
    'Qu’est-ce qui te surprend le plus chez les gens ?',
    'Quelle est la meilleure décision que tu aies prise sur un coup de tête ?',
    'Quel est le plus long voyage que tu rêves de faire ?',
    'Quelle erreur t’a finalement apporté quelque chose de positif ?',
    'Quel moment de calme te fait le plus de bien dans une semaine ?',
    'À quel âge as-tu eu l’impression de devenir vraiment adulte ?',
    'Quelle est la chose la plus gentille que tu aies faite pour un inconnu ?',
    'Qu’est-ce que tu détestais enfant et que tu adores aujourd’hui ?',
    'Quelle phrase t’a marqué·e au point de t’accompagner encore ?',
    'Quelle différence vois-tu entre la personne que tu es et celle que tu montres ?',
    'Qu’est-ce qui te rassure quand tu doutes de toi ?',
    'Quel talent d’un·e ami·e présent ici t’impressionne le plus ?',
    'Si tu pouvais changer une seule chose dans le monde, laquelle serait-ce ?',
    'Quelle question aimerais-tu qu’on te pose plus souvent ?',
    'Quel est le meilleur souvenir que tu aies avec ta famille ?',
    'Quelle est la chose que tu aimerais avoir plus de temps pour faire ?',
    'Qu’est-ce qui rend un moment inoubliable selon toi ?',
    'Quelle est ta façon préférée de dire à quelqu’un que tu tiens à lui ?',
    'Quel est le souvenir le plus drôle que tu partages avec un·e ami·e ?',
    'Quel âge rêverais-tu d’avoir pour toujours, et pourquoi ?',
    'Si tu pouvais vivre une journée dans la peau de quelqu’un d’autre, qui choisirais-tu ?',
    'Qu’est-ce qui te donne confiance en l’avenir ?',
    'Quelle est la dernière fois que tu as été ému·e aux larmes de joie ?',
    'Quel conseil donnerais-tu à quelqu’un qui doute de son chemin ?',
    'Quelle est la plus grande aventure que tu aies vécue ?',
    'Quel lieu secret ou préféré aimerais-tu faire découvrir à quelqu’un ?',
    'Qu’est-ce que tu n’as jamais osé demander à tes parents ?',
    'Quelle chose banale te rend étrangement heureux·se ?',
    'Quel moment de solitude as-tu fini par apprécier ?',
    'Quel superpouvoir très modeste aimerais-tu avoir au quotidien ?',
    'Quelle est la meilleure surprise que tu aies organisée pour quelqu’un ?',
    'Quelle est la chose que tu fais mieux que presque tout le monde ?',
    'Quelle idée reçue sur toi te fait le plus sourire ?',
    'Quel mot ou quelle expression utilises-tu tout le temps sans t’en rendre compte ?',
    'Quelle est la plus belle conversation que tu aies jamais eue ?',
    'Qu’est-ce que tu aimerais que ton futur toi te remercie d’avoir fait ?',
    'Quel changement récent dans ta vie te rend le plus heureux·se ?',
    'Quelle est la plus grande source de fierté de ta famille, selon toi ?',
    'Quel moment de ta vie voudrais-tu revivre en entier, sans rien changer ?',
    'Quelle personne aimerais-tu remercier, sans l’avoir jamais vraiment fait ?',
    'Si tu pouvais offrir une seule chose à tous les gens que tu aimes, ce serait quoi ?',
    'Qu’est-ce qui t’a le plus appris sur toi-même ces dernières années ?',
    'Quelle est la chose la plus importante que tu n’aies pas encore faite ?',
    'Quel genre de souvenirs veux-tu collectionner dans les dix prochaines années ?',
    'Qu’est-ce qui te fait dire « là, je suis bien » ?',
    'Quelle est ta plus belle réussite, même si personne ne l’a célébrée ?',
    'Qu’as-tu appris d’un échec qui t’a vraiment aidé·e ensuite ?',
    'Quelle qualité de tes parents espères-tu avoir héritée ?',
    'Qu’est-ce que tu ferais si tu savais que tu ne pouvais pas échouer ?',
    'Quel est le plus beau message ou la plus belle lettre que tu aies reçu ?',
    'Quelle personne te fait te sentir le plus compris·e, et pourquoi ?',
    'Quel détail du quotidien aimerais-tu savourer davantage ?',
    'Quelle est la différence entre ce que tu veux et ce dont tu as besoin en ce moment ?',
    'Quel moment de l’année est ton préféré, et que ressens-tu à ce moment-là ?',
    'Quelle est l’idée la plus folle que tu aimerais réaliser un jour ?',
    'Quel est le meilleur endroit où tu aies mangé, et avec qui ?',
    'Qu’est-ce qui te fait te sentir chez toi, au-delà d’un simple lieu ?',
    'Quelle est ta plus grande force quand les choses se compliquent ?',
    'Quel talent offert à quelqu’un d’autre te rendrait heureux·se ?',
    'Qu’est-ce que la réussite des autres t’apprend sur toi-même ?',
    'Quelle est la plus belle chose que tu aies apprise en voyageant ?',
    'Quelle habitude de ton enfance aimerais-tu retrouver ?',
    'Quel rôle l’humour joue-t-il dans ta façon de traverser les moments difficiles ?',
    'Quelle est ta plus grande peur quand tu penses à l’avenir ?',
    'Qu’est-ce qui t’a fait changer d’avis sur un sujet important ?',
    'Quelle est la personne que tu admires le plus dans ton entourage ?',
    'Quel talent ou quelle passion partages-tu avec un membre de ta famille ?',
    'Quelle aventure imaginaire aimerais-tu vivre avec toute cette bande ?',
    'Qu’est-ce que tu aimerais comprendre de toi-même d’ici un an ?',
    'Qu’est-ce qui te fait te sentir en sécurité ?',
    'Quelle est la chose la plus étonnante que tu aies apprise récemment ?',
    'Quelle est ta façon de gérer le stress, la plus étrange mais efficace ?',
    'Quel rêve de gosse as-tu déjà réalisé sans même t’en rendre compte ?',
    'Qu’est-ce qui, selon toi, rend une amitié durable ?',
    'Quelle est ta plus grande fierté liée à ton travail ou à tes études ?',
    'Quel défi aimerais-tu relever avant tes quarante ans ?',
    'Quelle est la plus belle façon de passer un dimanche pluvieux ?',
    'Quel souvenir d’une fête de famille te revient toujours en tête ?',
    'Qu’est-ce que tu aimerais que les gens comprennent mieux sur toi ?',
    'Quelle personnalité de fiction te ressemble le plus, et pourquoi ?',
    'Si ta vie était un film, quel genre serait-il et qui jouerait ton rôle ?',
    'Quelle chose t’a rendu·e plus patient·e avec le temps ?',
    'Quel est le moment de la journée où tu te sens le plus toi-même ?',
    'Quel geste d’un proche t’a le plus touché·e récemment ?',
    'Qu’est-ce qui te motive à te lever le matin, au fond ?',
    'Quelle erreur de jeunesse te fait aujourd’hui éclater de rire ?',
    'Qu’est-ce qui rend un groupe d’amis vraiment soudé selon toi ?',
    'Quelle est la décision la plus difficile que tu aies eue à prendre ?',
    'Quel genre de souvenir aimerais-tu créer ce soir même ?',
    'Quel proverbe ou quelle citation te guide, consciemment ou non ?',
    'Quel est le meilleur conseil de vie que quelqu’un t’ait donné ?',
    'Quelle part de ton enfance as-tu gardée intacte en toi ?',
    'Quelle est la première chose que tu ferais si tu gagnais une année de liberté totale ?',
    'Quelle est la plus belle marque d’attention qu’on puisse te faire ?',
    'Qu’est-ce que tu préfères chez toi quand tu es entouré·e de gens que tu aimes ?',
    'Quel sujet pourrais-tu raconter pendant des heures sans t’ennuyer ?',
    'Quelle activité aimerais-tu partager avec les gens présents ce soir ?',
    'Qu’est-ce qui fait que tu te sens fier·e d’appartenir à ta famille ?',
    'Quel monument ou quel lieu a dépassé tes attentes quand tu l’as découvert ?',
    'Quelle chose bien précise te met immédiatement de bonne humeur ?',
    'Quelle est la plus belle histoire de hasard que tu aies vécue ?',
    'Quel moment de grande joie as-tu eu du mal à décrire avec des mots ?',
    'Quelle personne que tu as perdue de vue aimerais-tu retrouver ?',
    'Quel talent des autres aimerais-tu pouvoir t’approprier du jour au lendemain ?',
    'Qu’est-ce que la gentillesse veut dire pour toi, concrètement ?',
    'Quel est ton plus beau souvenir d’une soirée entre amis ?',
    'Quelle chose, aujourd’hui évidente, te semblait impossible il y a cinq ans ?',
    'Quel est le meilleur moment de ta semaine, celui que tu attends vraiment ?',
    'Quel bonheur simple te suffirait pour que ta journée soit réussie ?',
  ],
  spicy: [
    'Quelle est la vérité sur toi que tu as le plus de mal à admettre ?',
    'Quel ex te manque encore un peu, et pourquoi ?',
    'Quelle est la pire chose que tu aies faite par jalousie ?',
    'Quelle amitié t’a le plus déçu·e, et que s’est-il passé ?',
    'Qui, dans ce groupe, te surprend le plus par sa façon de vivre ?',
    'Quel défaut chez les gens ici as-tu appris à tolérer ?',
    'Quelle qualité d’une personne présente ici aimerais-tu lui voir plus utiliser ?',
    'Quelle est la plus grosse erreur que tu aies faite en amour ?',
    'Qu’est-ce que tu n’as jamais pardonné à un·e ami·e ?',
    'Quelle est la chose la plus égoïste que tu aies faite en couple ?',
    'À quel moment as-tu su que ta dernière relation était finie ?',
    'Quelle vérité difficile aimerais-tu dire à quelqu’un d’ici ?',
    'Qui, dans ce groupe, a le plus changé selon toi depuis qu’on se connaît ?',
    'Quelle est la jalousie que tu ressens le plus souvent, et envers qui ?',
    'Quel mensonge dis-tu régulièrement pour éviter un conflit ?',
    'Qu’est-ce qui t’agace le plus chez les gens que tu aimes ?',
    'Quelle est la plus belle déclaration d’amour que tu aies reçue ?',
    'Quelle est la chose qui te fait immédiatement fuir en amour ?',
    'Qu’est-ce que tu as longtemps cru être de l’amour, alors que non ?',
    'Quel ex referait un pas vers toi, selon toi, et que ferais-tu ?',
    'Quel secret as-tu gardé trop longtemps pour protéger quelqu’un ?',
    'Quelle personne ici pourrait te faire changer d’avis sur un sujet ?',
    'Quelle est la chose la plus dure que tu aies entendue sur toi-même ?',
    'Quel conseil que tu donnes aux autres n’appliques-tu pas toi-même ?',
    'Quel rôle joues-tu dans ce groupe, et est-ce que ça te convient ?',
    'Qu’est-ce que tu faisais semblant d’aimer pour plaire à quelqu’un ?',
    'Quelle est ta plus grande insécurité dans une relation amoureuse ?',
    'Qu’attends-tu vraiment d’un·e partenaire, sans te censurer ?',
    'Quelle est la plus grosse dispute que tu aies eue avec un·e ami·e ?',
    'Quelle amitié du passé regrettes-tu d’avoir laissée mourir ?',
    'Qu’est-ce que tu attends encore de quelqu’un qui ne te l’a jamais donné ?',
    'Quelle est ta plus grande peur quand tu tombes amoureux·se ?',
    'Quelle personne dans ce groupe fais-tu le plus facilement rire, et pourquoi ?',
    'Quel trait de ton caractère a déjà fait fuir quelqu’un ?',
    'Qu’est-ce que tu ne supportes pas qu’on te dise sur ta vie amoureuse ?',
    'Quel talent d’un·e ami·e ici te rend un peu jaloux·se ?',
    'Quelle est la phrase que tu regrettes le plus d’avoir dite à un·e ex ?',
    'Quel compliment est trop rare dans ta vie amoureuse ?',
    'Qu’est-ce qui t’a fait le plus mal dans une rupture ?',
    'Quelle est la personne ici que tu as mal jugée au départ ?',
    'Quelle première impression as-tu eue de chacun·e dans ce groupe ?',
    'Quelle limite as-tu eu du mal à poser dans une relation ?',
    'Quel est le plus gros red flag que tu aies ignoré en amour ?',
    'Quelle relation toxique as-tu mis du temps à quitter ?',
    'Qu’est-ce que tu penses vraiment des gens qui restent amis avec leurs ex ?',
    'Quel est le plus gros mensonge que tu aies avoué après coup ?',
    'Qu’est-ce que tu aurais aimé que ton ex comprenne de toi ?',
    'Quel rôle l’orgueil a-t-il joué dans l’une de tes ruptures ?',
    'Quelle est la chose la plus difficile à pardonner chez un·e partenaire ?',
    'Pour quelle raison as-tu déjà quitté quelqu’un alors que tu l’aimais encore ?',
    'Dans quelle relation as-tu été le·la plus amoureux·se, et pourquoi ça a fini ?',
    'Quel ami ou amie envierais-tu pour sa vie de couple ?',
    'Quel est le défaut d’un·e ex que tu retrouves chez les autres ?',
    'Quelle différence y a-t-il entre l’amour que tu donnes et celui que tu reçois ?',
    'Quel ami ou amie te dirait la vérité même si elle te fait mal ?',
    'Quelle vérité sur ton couple ou tes amours cachez-tu à tes proches ?',
    'Quel défaut de ton caractère rend la vie difficile à ceux qui t’aiment ?',
    'À qui as-tu déjà menti pour ne pas lui faire de peine ?',
    'Quelle est la pire façon de se faire larguer, selon ton expérience ?',
    'Qu’est-ce qui te fait te sentir en danger dans une relation ?',
    'Quelle est la décision amoureuse que tu referais exactement pareil ?',
    'Quelle est la chose que tu aurais aimé que quelqu’un ici te dise plus tôt ?',
    'Quel conflit non résolu avec un·e ami·e te pèse encore ?',
    'À quel moment t’es-tu senti·e le plus seul·e malgré des gens autour de toi ?',
    'Quelle personne du groupe ferais-tu appeler en premier en cas de gros souci ?',
    'Quel trait de ta personnalité te fait trop souvent perdre tes amis ?',
    'Qui, ici, sait le mieux te réconforter, et comment ?',
    'Quel est ton plus grand paradoxe en amour ?',
    'Quelle excuse as-tu déjà inventée pour esquiver un rendez-vous ?',
    'Qu’est-ce que tu penses vraiment des histoires à distance ?',
    'Qu’est-ce qui te donne envie de partir à la première dispute ?',
    'Quelle est la plus belle chose que tu aies faite pour reconquérir quelqu’un ?',
    'Quel âge avais-tu quand tu as vraiment compris ce que voulait dire aimer ?',
    'Quel ex garde une place à part dans ton cœur, et laquelle ?',
    'Qu’est-ce que tu as pris pour de l’indifférence alors que c’était de la timidité ?',
    'Quel sentiment as-tu le plus de mal à exprimer à ceux que tu aimes ?',
    'Quelle est la différence entre ce que tu dis chercher et ce que tu cherches vraiment en amour ?',
    'Qu’est-ce que tu ne dirais jamais à ta meilleure amie ou à ton meilleur ami ?',
    'Quelle personne du groupe te semble la plus difficile à cerner ?',
    'Quelle est ta plus grande hypocrisie, celle que tu assumes à moitié ?',
    'Quel jugement hâtif sur quelqu’un ici s’est révélé complètement faux ?',
    'Quelle est la dernière fois où tu as pleuré à cause de quelqu’un ?',
    'Quelle chose chez ton ex ne te manque absolument pas ?',
    'Qu’est-ce qui a signé la fin de ton amitié la plus douloureuse ?',
    'Quel rôle tes parents ont-ils joué dans ta façon d’aimer ?',
    'Quelle question n’oses-tu pas poser à la personne que tu fréquentes ?',
    'Quelle est la preuve d’amour que tu trouves la plus surcotée ?',
    'Quelle est la preuve d’amour qui te toucherait au plus profond ?',
    'Que ferais-tu si ton meilleur ami ou ta meilleure amie sortait avec ton ex ?',
    'Quelle est la raison la plus absurde pour laquelle tu aies déjà rompu ?',
    'Quel est ton avis honnête sur la vie de couple de tes amis les plus proches ?',
    'Quel sacrifice as-tu déjà fait par amour que tu regrettes aujourd’hui ?',
    'Quelle est ta plus belle erreur de casting en amour ?',
    'Quelle chose que tu as dite à voix haute une fois, tu aimerais la reprendre ?',
    'Quelle est la plus grosse déception que t’a causée un·e ami·e ?',
    'Quel type de personne attire toujours les mauvaises relations chez toi ?',
    'Qui dans ce groupe sera, selon toi, le premier à se marier, et pourquoi ?',
    'Quelle est la preuve que tu as grandi après une rupture ?',
    'Quelle amitié a le plus changé en devenant adulte ?',
    'Qu’est-ce qui te rend le plus jaloux·se chez les autres : leur vie, leur succès ou leur couple ?',
    'Quelle est la chose la plus honnête que tu aies dite à quelqu’un que tu aimais ?',
    'Quel type de relation te fait te sentir le plus vulnérable ?',
    'Qui ici te connaît le mieux, et que ne sait-il pas encore sur toi ?',
    'Quel regard portes-tu sur les gens qui ne veulent jamais s’engager ?',
    'Quel rendez-vous raté t’a le plus marqué·e ?',
    'Quelle est la chose que tu changerais immédiatement dans ton rapport à l’amour ?',
    'Quel secret ton regard trahit-il le plus facilement ?',
    'Quelle amitié penses-tu ne pas pouvoir survivre à un désaccord sur le couple ?',
    'Quelle question sur ton passé amoureux hésites-tu à raconter à un·e nouveau·elle partenaire ?',
    'Quelle est la dernière fois où tu t’es senti·e très blessé·e par une remarque ?',
    'Quelle comparaison avec les autres te fait le plus mal ?',
    'Dans quel domaine de ta vie te mens-tu encore un peu à toi-même ?',
    'Quel sentiment t’envahit quand tu vois un·e ex heureux·se avec quelqu’un d’autre ?',
    'Qu’est-ce que tu as le plus de mal à demander à ton·ta partenaire ?',
    'Quelle personne du groupe a le meilleur flair pour les gens, selon toi ?',
    'Qu’est-ce qui t’a fait te dire « plus jamais ça » en amour ?',
    'Quelle est la différence entre aimer quelqu’un et être bien avec lui ?',
    'Quelle part de toi n’as-tu jamais montrée à un·e partenaire ?',
    'Quel ami ou amie t’a déjà dit une vérité qui t’a vexé·e sur le moment ?',
    'Quelle qualité d’un·e ex voudrais-tu retrouver chez quelqu’un d’autre ?',
    'Quel mot résume le mieux ton histoire d’amour la plus marquante ?',
    'Quel défaut d’un·e partenaire serait pour toi un point de rupture ?',
    'Quelle est ta plus grande peur dans l’amitié ?',
    'Quel est le moment où tu as le plus douté de ton couple ou de ta relation ?',
    'Quelle est la chose que les autres ont mal compris sur ton comportement amoureux ?',
    'Quelle personne ici pourrais-tu imaginer comme colocataire, et laquelle jamais ?',
    'Quelle est la jalousie que tu trouves la plus saine dans un couple ?',
    'À qui as-tu déjà caché que tu étais jaloux·se ?',
    'Quelle est la plus grosse prise de tête que tu aies eue pour un détail ridicule ?',
    'Qu’est-ce que tu aurais envie de dire à ton ex si tu étais sûr·e qu’il ne le répéterait pas ?',
    'Quelle chose faut-il savoir pour te rendre vraiment heureux·se en amour ?',
    'Quelle relation du passé te montre le mieux qui tu es devenu·e ?',
    'Quel est le cadeau le plus raté que tu aies offert à quelqu’un que tu aimais ?',
    'Quelle est ta réaction type quand tu te sens trahi·e ?',
    'Quelle est la chose que tu espères que ton futur partenaire ne découvre jamais sur toi ?',
    'Dans quel domaine es-tu injuste avec les autres sans le vouloir ?',
    'Quelle est la différence entre une vraie amitié et une simple habitude ?',
    'Quelle remarque sur ta vie sentimentale te fait lever les yeux au ciel ?',
    'Quel ami ou amie t’a le plus appris sur l’amour, et comment ?',
    'À quel moment as-tu eu le plus peur de perdre quelqu’un ?',
    'Quelle est la question qui te met le plus mal à l’aise en soirée ?',
    'Quelle est la plus grande preuve de confiance que tu aies faite à quelqu’un ?',
    'Quel type de personne te rend irrationnel·le dès que tu la croises ?',
    'Quel clash a transformé une de tes amitiés en meilleure version d’elle-même ?',
    'Que penses-tu vraiment des coups de foudre ?',
    'Quelle erreur as-tu faite en amour qu’aucun conseil n’aurait pu t’éviter ?',
    'Quelle réputation as-tu dans ton groupe d’amis, et la mérites-tu ?',
    'Si tu devais décrire chaque personne ici en un mot, lequel choisirais-tu pour la plus proche de toi ?',
    'Quelle est la chose la plus romantique que quelqu’un ait faite pour toi ?',
    'Quelle est la chose la moins romantique que tu aies faite en pensant bien faire ?',
    'Quelle excuse te sers-tu le plus souvent pour ne pas t’engager ?',
    'Quelle confidence faite par un·e ami·e t’a le plus surpris·e ?',
    'Qu’est-ce qui t’aide à tourner la page quand une relation prend fin ?',
    'Quelle est la jalousie amicale la plus bête que tu aies ressentie ?',
    'Quelle sorte de compliment sonne faux à tes oreilles ?',
    'Qu’est-ce qui te donne envie de dire « je t’aime » à quelqu’un ?',
    'Quelle personne du groupe aimerais-tu mieux connaître, et pourquoi ?',
    'Qu’est-ce qui t’a fait le plus grandir dans une relation difficile ?',
    'Quelle est la phrase que tu rêves d’entendre de la part de la personne que tu aimes ?',
    'Quel est le comportement d’un·e partenaire que tu n’as jamais osé critiquer ?',
    'Qu’est-ce qui, dans ton passé amoureux, t’empêche encore d’avancer ?',
    'Quel scénario amoureux de film te fait rêver mais n’arrivera jamais ?',
    'Si tu pouvais effacer une seule dispute de ta vie, laquelle choisirais-tu ?',
    'Quel regret en amitié reviendra sans doute dans dix ans ?',
    'Quel verdict ton meilleur ami ou ta meilleure amie donnerait-il sur ta vie amoureuse ?',
    'Quelle étiquette t’a-t-on collée dans ce groupe sans que tu l’aies choisie ?',
    'Quelle est la leçon que ta pire rupture t’a apprise ?',
    'Quelle est l’attitude d’un proche qui te blesse sans qu’il s’en rende compte ?',
    'Quel genre de jalousie as-tu appris à contrôler avec le temps ?',
    'Quel critère éliminatoire en amour trouves-tu injuste mais indispensable ?',
    'Quelle est la différence entre ta vie amoureuse rêvée et celle que tu vis ?',
    'Quelle est la dernière chose pour laquelle tu t’es excusé·e sincèrement ?',
    'Quelle franchise gratuite d’un·e ami·e t’a le plus fait réfléchir ?',
    'Quel détail de ta vie sentimentale aimerais-tu raconter à tout le monde, mais tu n’oses pas ?',
  ],
  hot: [
    'Qu’est-ce qui te donne immédiatement envie de séduire quelqu’un ?',
    'Quelle est la qualité physique que tu remarques en premier chez quelqu’un ?',
    'Quel est ton plus beau souvenir de premier baiser ?',
    'Quel geste, tout simple, te fait fondre instantanément ?',
    'Quelle partie de ton corps as-tu appris à aimer avec le temps ?',
    'Quelle est la chose la plus sexy que quelqu’un ait jamais murmurée à ton oreille ?',
    'Qu’est-ce qui rend un baiser inoubliable selon toi ?',
    'Quel est ton rapport à ton corps aujourd’hui, comparé à tes vingt ans ?',
    'Quelle est la chose la plus audacieuse que tu aies osée pour séduire ?',
    'Qu’est-ce qui te met le plus à l’aise dans l’intimité avec quelqu’un ?',
    'Quel genre de regard te fait perdre tous tes moyens ?',
    'Quel est ton plus grand complexe, et comment vis-tu avec ?',
    'Qu’est-ce qui t’attire en premier chez quelqu’un : la voix, le regard, l’humour ?',
    'Quelle est la plus belle façon de faire comprendre à quelqu’un qu’il te plaît ?',
    'Quelle ambiance rend une soirée à deux irrésistible pour toi ?',
    'Quel est ton rituel de séduction préféré, celui qui marche presque toujours ?',
    'Quel talent de séducteur ou séductrice possèdes-tu sans le vouloir ?',
    'Quel est le moment où tu t’es senti·e le plus désirable ?',
    'Quelle tenue te fait te sentir au summum de ta confiance ?',
    'Quel est le plus beau compliment sur ton physique que tu aies reçu ?',
    'Qu’est-ce que tu trouves terriblement attirant mais que tu n’avoues jamais ?',
    'Quelle est ta plus grande peur dans l’intimité avec quelqu’un de nouveau ?',
    'Quel est le geste de tendresse que tu préfères donner ?',
    'Quel est le geste de tendresse que tu aimerais recevoir plus souvent ?',
    'Quelle est la différence pour toi entre désir et amour ?',
    'Qu’est-ce qui te fait te sentir en sécurité pour te laisser aller avec quelqu’un ?',
    'Quelle est la chose la plus romantique que tu rêves de vivre dans un lit ou hors du lit ?',
    'Quelle est la chose la plus coquine que tu aies faite en voyage ?',
    'Quel lieu insolite te semble le plus romantique pour une nuit à deux ?',
    'Qu’est-ce qui t’a le plus surpris·e dans la découverte de ta propre sexualité ?',
    'Qu’est-ce que tu aurais aimé savoir sur l’intimité à dix-huit ans ?',
    'Quelle est la qualité d’un·e amant·e qui compte le plus pour toi ?',
    'Qu’est-ce qui t’éteint complètement au moment de séduire ?',
    'Quelle est la chose qui t’excite mentalement plus que physiquement ?',
    'Quelle est ta définition d’une soirée parfaite à deux, sans filtre ?',
    'Quel parfum te donne envie de te rapprocher de quelqu’un ?',
    'Quelle est la phrase d’accroche la plus ridicule qu’on t’ait lancée ?',
    'Quelle est la pire technique de drague que tu aies essayée ?',
    'Quelle chanson te met immédiatement dans l’ambiance séduction ?',
    'Quelle est la dernière fois où tu as rougi de désir ou de gêne ?',
    'Que préfères-tu dans les préliminaires : l’attente, les mots ou les gestes ?',
    'Quel sens est le plus important pour toi dans l’intimité : toucher, vue, odorat ou ouïe ?',
    'Quelle chose banale te trouble étrangement chez une personne ?',
    'Quel est le détail physique que tu trouves le plus craquant chez quelqu’un ?',
    'Quelle est ta zone de confort en séduction, et ta zone d’aventure ?',
    'Quelle est la chose la plus excitante qu’on t’ait dite sans te toucher ?',
    'Quel scénario romantique te ferait complètement craquer ?',
    'Qu’est-ce qui, dans une première nuit, compte vraiment le plus pour toi ?',
    'Quel souvenir intime te fait encore un peu sourire en y repensant ?',
    'Quelle est la plus grande preuve de complicité dans l’intimité à tes yeux ?',
    'Quelle est la chose que tu rêves d’oser dire à la personne qui te plaît ?',
    'Quel rôle joue l’humour dans ta façon de séduire ou d’être séduit·e ?',
    'Quel est ton avis honnête sur l’idée du « premier soir » ?',
    'Quelle différence fais-tu entre un flirt innocent et un flirt qui va trop loin ?',
    'Qu’est-ce qui te rend irrésistible, selon tes ex ?',
    'Quelle a été ta plus belle nuit blanche à deux, et pourquoi ?',
    'Quelle part de ton corps ressent le plus les frissons quand on te touche ?',
    'Quelle est la chose la plus sensuelle qui ne soit pas du tout sexuelle ?',
    'Quelle est ta plus grande envie dont tu n’as jamais parlé à personne ?',
    'Quel fantasme de voyage ou de lieu aimerais-tu vivre avec quelqu’un ?',
    'Quelle est la chose que tu voudrais qu’un·e partenaire devine sans que tu aies à la dire ?',
    'Qu’est-ce qu’un bon massage a de plus séduisant qu’on ne le croit ?',
    'Dans quel cadre te sens-tu le plus sexy : lumière tamisée, plage, soirée dansante ?',
    'Quel est ton plus grand tabou en matière d’intimité, celui qu’on évite d’aborder ?',
    'Quelle est la différence entre la séduction que tu montres et celle que tu ressens ?',
    'Quelle étrange habitude de séduction as-tu déjà eue sans t’en apercevoir ?',
    'Quelle est la plus grande preuve de confiance qu’on puisse donner dans l’intimité ?',
    'Quelle est la chose la plus osée que tu aies portée un soir pour séduire ?',
    'Quel souvenir de danse sensuelle te revient en tête ?',
    'Qu’est-ce qui rend un message du soir plus séduisant qu’un appel ?',
    'Quelle est la chose qui te rend le plus vulnérable dans un moment d’intimité ?',
    'Quel est ton avis sur les relations purement physiques entre adultes consentants ?',
    'Comment aimes-tu être séduit·e : par les mots, les attentions ou l’audace ?',
    'Quelle est la plus belle manière de dire non à un rapprochement sans blesser ?',
    'Quelle est l’habitude d’un·e partenaire qui entretient le mieux le désir ?',
    'Quel est le moment où tu te sens le plus sexy dans une journée ordinaire ?',
    'Qu’est-ce que tu as appris sur toi en explorant ton désir ?',
    'Quelle limite as-tu appris à poser dans l’intimité, et pourquoi ?',
    'Quel conseil donnerais-tu à quelqu’un qui manque de confiance pour séduire ?',
    'Quelle est la différence entre un câlin tendre et un câlin qui annonce autre chose ?',
    'Quel mot doux t’a le plus marqué·e dans l’intimité ?',
    'Quelle est la chose que tu aimerais essayer, juste une fois, avec la bonne personne ?',
    'Quel mélange de timidité et d’audace décrit le mieux ta façon de séduire ?',
    'Qu’est-ce qu’une soirée romantique réussie pour toi, étape par étape ?',
    'Quelle est la chose la plus charmante qu’un·e inconnu·e t’ait dite dans la rue ou en soirée ?',
    'Quel regard sur ton corps as-tu quand tu te trouves devant le miroir le matin ?',
    'Quelle est ta plus grande peur concernant l’image que les autres ont de ton physique ?',
    'Quel est le rôle de la confiance en soi dans ta vie intime ?',
    'Qu’est-ce que tu trouves excitant dans une conversation, même sans contact ?',
    'Quelle célébrité imaginaire ou personnage de fiction t’a longtemps troublé·e ?',
    'Quelle est l’astuce de séduction la plus efficace que tu connaisses ?',
    'Quelle chose peut transformer une soirée banale en soirée torride ?',
    'Quelle est la rencontre la plus électrique que tu aies faite ?',
    'Dans quel moment de la séduction te sens-tu le plus vivant·e : l’approche, l’attente ou la conclusion ?',
    'Quelle différence vois-tu entre être attiré·e et être amoureux·se ?',
    'Quelle est la façon dont tu aimes qu’on te regarde dans une pièce pleine de monde ?',
    'Quelle est la plus grande source de désir pour toi : le mystère ou la complicité ?',
    'Quel aspect de ton corps trouves-tu injustement sous-estimé ?',
    'Quelle phrase te fait fondre quand elle est dite avec la bonne voix ?',
    'Quelle chose les gens pensent à tort de toi en matière de séduction ?',
    'Quel genre de surprise intime te ferait vraiment plaisir ?',
    'Qu’est-ce que tu aimerais qu’on te dise le matin après une belle nuit ?',
    'Quelle ambiance sonore ou musicale accompagne le mieux une nuit à deux ?',
    'Quelle est ta plus belle histoire de séduction, celle qui a failli rater ?',
    'Quelle tension entre deux personnes trouves-tu la plus délicieuse ?',
    'Quelle est la place du jeu dans l’intimité selon toi ?',
    'Quel point de ta vie intime aimerais-tu pouvoir améliorer ?',
    'Qu’est-ce que tu as appris de ton ex dans l’intimité qui t’a servi ensuite ?',
    'Quelle est la plus belle preuve d’attention qu’un·e partenaire puisse te donner au lit ?',
    'Quel genre de proposition te ferait rire autant que rougir ?',
    'Quelle petite audace te manque pour oser davantage en séduction ?',
    'Quelle est la chose la plus sensuelle que tu puisses cuisiner pour quelqu’un ?',
    'Quelle est la différence entre séduire et vouloir plaire à tout prix ?',
    'Quel mot résume le mieux ton énergie quand tu es amoureux·se ?',
    'Quelle est la dernière fois où tu t’es senti·e sincèrement séduisant·e ?',
    'Qu’est-ce qui te fait te sentir désiré·e plus qu’un compliment ne le pourrait ?',
    'Quelle est la plus belle chose que tu aies ressentie en tenant la main de quelqu’un ?',
    'Quelle est ta réaction quand quelqu’un te drague de manière maladroite ?',
    'Quelle est la chose qui doit être claire avant toute intimité, selon toi ?',
    'Quelle importance accordes-tu au consentement enthousiaste, au-delà du simple oui ?',
    'Quelle est la chose qui rend la communication dans l’intimité plus facile ?',
    'Quel est ton plus grand fantasme romantique, sans entrer dans les détails ?',
    'Quelle ambiance de rêve te donnerait envie d’un week-end loin de tout à deux ?',
    'Quelle sorte de baiser préfères-tu : lent, fougueux, volé ou inattendu ?',
    'Quelle est la chose la plus intime que tu aies confiée à quelqu’un ?',
    'Quel est le mot qui te fait le plus rougir quand on te le dit ?',
    'Quel équilibre cherches-tu entre tendresse et passion ?',
    'Qu’est-ce qui t’aide à te sentir bien dans ta peau avant une soirée importante ?',
    'Quelle est la plus belle surprise que tu aies faite à quelqu’un pour le séduire ?',
    'Quel est le défaut de séduction que tu avoues sans honte ?',
    'Quelle chose rend un début d’histoire excitant et un peu effrayant à la fois ?',
    'Quelle différence vois-tu entre séduire en vrai et séduire par messages ?',
    'Quelle est la plus grande erreur à éviter lors d’un premier rendez-vous ?',
    'Quelle est la chose que tu trouves sexy chez toi qu’on ne remarque pas ?',
    'Quelle partie du corps d’un·e partenaire embrasses-tu avec le plus de plaisir ?',
    'Quelle petite attention au quotidien entretient le feu dans un couple ?',
    'Quel regard portes-tu sur la routine dans la vie intime d’un couple ?',
    'Qu’est-ce qui t’attire chez quelqu’un qui te semble inaccessible ?',
    'Quel genre de tension ou de jeu de regards aimerais-tu vivre ce soir ?',
    'Quelle est la chose que tu n’as jamais osé demander à quelqu’un dans l’intimité ?',
    'Quelle ambiance lumineuse te fait te sentir le plus séduisant·e : bougies, nuit, plein soleil ?',
    'Quelle est la façon la plus élégante d’avouer son attirance à quelqu’un ?',
    'Quel rôle jouent les silences dans une belle soirée à deux ?',
    'Quelle est ta plus grande frustration dans la manière dont on parle de désir aujourd’hui ?',
    'Quel est le meilleur conseil intime que tu aies reçu d’un·e ami·e ?',
    'Quelle est la différence entre une nuit réussie et une nuit inoubliable ?',
    'Quel est ton point faible en séduction, celui qui te trahit à chaque fois ?',
    'Quelle est la plus grande source d’excitation que tu connaisses sans contact physique ?',
    'Quelle chose te fait sentir irrésistible sans que tu n’aies rien à faire ?',
    'Quel tabou sur le corps aimerais-tu voir disparaître ?',
    'Qu’aimerais-tu que les gens comprennent mieux sur la façon dont tu vis ton désir ?',
    'Qu’est-ce qui rend la tendresse plus érotique qu’on ne l’imagine ?',
    'Quelle sorte de complicité souhaiterais-tu retrouver avec quelqu’un dans l’intimité ?',
    'Quel est le moment où tu t’es senti·e le plus proche de quelqu’un physiquement ?',
    'Quelle est la chose qui te rend le plus audacieux·se une fois la confiance installée ?',
    'Quelle est ta façon de te reconnecter à ton corps quand tu t’en sens loin ?',
    'Quelle est la plus belle promesse qu’on t’ait faite dans un moment de proximité ?',
    'Qu’est-ce qui te fait dire « cette personne me plaît vraiment » dès les premières minutes ?',
    'Quelle est la plus grande différence entre le désir à vingt ans et aujourd’hui ?',
    'Quelle est ta plus belle histoire de crush secret, avoué ou non ?',
    'Quelle chose chez toi te rend plus attirant·e quand tu es heureux·se ?',
    'Quel est ton plus beau souvenir de soirée où tout aurait pu arriver ?',
    'Qu’est-ce qui, dans le jeu de la séduction, te fait le plus rire ?',
    'Quelle part de mystère aimes-tu conserver dans une relation ?',
    'Quelle est la chose que tu retiens toujours de ta toute première fois, sans entrer dans les détails ?',
    'Qu’est-ce que la sensualité veut dire pour toi, concrètement ?',
    'Quelle audace aimerais-tu qu’on ait avec toi, au moins une fois dans ta vie ?',
    'Quelle est la plus belle chose que l’on puisse dire à quelqu’un après une première nuit ?',
    'Quelle est ta plus belle excuse inventée pour prolonger une soirée avec quelqu’un ?',
  ],
}
