import type { Level } from '../engine'

/** Le jeu des 5 secondes — chaque entrée complète « Cite 3… ». */
export const fiveSeconds: Record<Level, string[]> = {
  soft: [
    'marques de voiture',
    'choses qu’on trouve dans un frigo',
    'excuses pour arriver en retard',
    'fruits rouges',
    'capitales européennes',
    'animaux de la ferme',
    'langues parlées en Europe',
    'sports d’équipe',
    'sports d’hiver',
    'instruments de musique',
    'pays d’Afrique',
    'pays d’Asie',
    'pays d’Amérique du Sud',
    'légumes verts',
    'fromages français',
    'marques de chaussures',
    'marques de céréales',
    'personnages de dessin animé',
    'héros de films d’animation',
    'princesses de dessin animé',
    'super-héros',
    'méchants de films',
    'choses qu’on trouve dans une trousse',
    'choses qu’on trouve dans un sac à dos',
    'choses qu’on trouve dans une salle de bain',
    'choses qu’on trouve dans une cuisine',
    'choses qu’on trouve dans un garage',
    'choses qu’on trouve dans un jardin',
    'choses qu’on trouve à la plage',
    'choses qu’on trouve dans une valise',
    'choses qu’on trouve dans une cour d’école',
    'choses qu’on trouve dans un supermarché',
    'choses qu’on trouve dans une boîte à outils',
    'choses qu’on trouve dans une forêt',
    'choses qu’on trouve au fond d’un tiroir',
    'choses qu’on trouve dans une trousse de secours',
    'choses qu’on trouve dans un bureau',
    'choses qu’on trouve dans une chambre d’enfant',
    'choses qu’on trouve dans un parc',
    'choses qu’on trouve dans une gare',
    'choses qu’on trouve dans un aéroport',
    'choses qu’on trouve dans une bibliothèque',
    'choses qu’on trouve dans un zoo',
    'choses qu’on trouve dans une piscine',
    'choses qu’on trouve dans une ferme',
    'choses qu’on trouve sur une pizza',
    'choses qu’on trouve dans un sandwich',
    'choses qu’on trouve dans un salon',
    'choses qu’on trouve dans une cave',
    'choses qu’on trouve au grenier',
    'choses qui sont rondes',
    'choses qui sont jaunes',
    'choses qui sont rouges',
    'choses qui sont vertes',
    'choses qui sont bleues',
    'choses qui sont noires et blanches',
    'choses qui sont rondes et comestibles',
    'choses qui sont collantes',
    'choses qui sont pointues',
    'choses qui sont gluantes',
    'choses qui sont brillantes',
    'choses qui sont poilues',
    'choses qui font du bruit',
    'choses qui font peur aux enfants',
    'choses qui volent',
    'choses qui roulent',
    'choses qui flottent',
    'choses qui coulent',
    'choses qui piquent',
    'choses qui puent',
    'choses qui sentent bon',
    'choses qui se plient',
    'choses qui se cassent facilement',
    'choses qui se mangent froides',
    'choses qui se mangent chaudes',
    'choses qui se boivent',
    'choses qui se collectionnent',
    'choses qui font pleurer',
    'choses qui font rire',
    'choses qui font sursauter',
    'choses qui brillent dans le noir',
    'choses qui se vendent en lot de six',
    'choses qui ont des ailes',
    'choses qui ont des roues',
    'choses qui ont des dents',
    'choses qui ont une queue',
    'choses qui ont des boutons',
    'choses qui ont un écran',
    'choses qui ont une clé',
    'choses qui ont un manche',
    'choses qui ont des pages',
    'choses qui ont des touches',
    'choses qui ont une porte',
    'choses qui ont des pieds mais pas de jambes',
    'choses qui ont une tête mais pas de cerveau',
    'choses qu’on pèle',
    'choses qu’on épluche',
    'choses qu’on plie avant de ranger',
    'choses qu’on remonte',
    'choses qu’on range dans un tiroir',
    'choses qu’on accroche à un mur',
    'choses qu’on ouvre',
    'choses qu’on lance',
    'choses qu’on attrape',
    'choses qu’on casse en cuisinant',
    'choses qu’on recharge',
    'choses qu’on perd tout le temps',
    'choses qu’on oublie en partant en vacances',
    'choses qu’on emporte en randonnée',
    'choses qu’on emporte à un pique-nique',
    'choses qu’on met dans une salade',
    'choses qu’on met dans un sandwich',
    'choses qu’on met sur des frites',
    'choses qu’on met dans un gâteau',
    'choses qu’on met dans une soupe',
    'choses qu’on met dans un café',
    'choses qu’on met sur du pain',
    'choses qu’on met dans une omelette',
    'choses qu’on met dans un cartable',
    'choses qu’on met dans une machine à laver',
    'choses qu’on peut faire sans sortir de chez soi',
    'choses qu’on fait sous la douche',
    'choses qu’on fait en voiture',
    'choses qu’on fait dans un train',
    'choses qu’on fait quand on s’ennuie',
    'choses qu’on fait le dimanche',
    'choses qu’on fait avant de dormir',
    'choses qu’on fait au réveil',
    'choses qu’on fait en attendant le bus',
    'choses qu’on fait quand il pleut',
    'choses qu’on fait quand il neige',
    'choses qu’on fait à Noël',
    'choses qu’on fait pendant un anniversaire',
    'choses qu’on fait chez le dentiste',
    'choses qu’on fait à la plage',
    'choses qu’on fait à la montagne',
    'choses qu’on fait au bureau pour avoir l’air occupé',
    'choses qu’on fait en cachette quand on est petit',
    'choses qu’on fait en vacances',
    'choses qu’on fait quand on n’a pas de réseau',
    'choses qu’on fait pour se réveiller',
    'choses qu’on fait pour se détendre',
    'choses qu’on fait quand on a le hoquet',
    'jeux de société',
    'jeux de cartes',
    'jeux vidéo',
    'jeux de cour de récréation',
    'jeux d’extérieur',
    'jeux télévisés',
    'séries télé',
    'films d’horreur',
    'comédies françaises',
    'films de Noël',
    'dessins animés des années 90',
    'émissions de télé-réalité',
    'chaînes de télévision',
    'applis de smartphone',
    'réseaux sociaux',
    'sites web qu’on visite tous les jours',
    'marques de téléphone',
    'marques d’ordinateur',
    'marques de vêtements de sport',
    'marques de jean',
    'marques de chocolat',
    'marques de glace',
    'marques de biscuits',
    'marques de bonbons',
    'marques de chips',
    'marques de boissons sans alcool',
    'marques de dentifrice',
    'marques de lessive',
    'marques de céréales du petit-déjeuner',
    'chaînes de fast-food',
    'chaînes de magasins de vêtements',
    'enseignes de supermarché',
    'compagnies aériennes',
    'parfums de glace',
    'parfums de chips',
    'parfums de yaourt',
    'parfums de bonbons',
    'parfums de sirop',
    'types de pâtes',
    'types de pain',
    'types de gâteaux',
    'types de tartes',
    'types de salades',
    'types de soupes',
    'types de sauces',
    'types de chaussures',
    'types de chapeaux',
    'types de manteaux',
    'types de sacs',
    'types de lunettes',
    'types de nuages',
    'types de météo',
    'types de fleurs',
    'types d’arbres',
    'types de poissons',
    'types d’oiseaux',
    'types de chiens',
    'types de chats',
    'types de dinosaures',
    'animaux qui vivent dans l’eau',
    'animaux qu’on trouve en Afrique',
    'animaux qui hibernent',
    'animaux qui pondent des œufs',
    'animaux qui ont quatre pattes',
    'animaux qui ont des rayures',
    'animaux qui ont des taches',
    'animaux nocturnes',
    'animaux de compagnie',
    'animaux de la forêt',
    'animaux du pôle Nord',
    'animaux qui font du bruit',
    'animaux rapides',
    'animaux lents',
    'animaux dangereux',
    'animaux roses',
    'insectes',
    'oiseaux',
    'poissons de mer',
    'fleurs',
    'épices',
    'herbes aromatiques',
    'noix et graines',
    'fruits qui ont un noyau',
    'fruits exotiques',
    'fruits d’été',
    'légumes racines',
    'légumes qu’on déteste',
    'légumes qu’on cuit à la vapeur',
    'plats qu’on mange avec les doigts',
    'plats de fête',
    'plats qu’on mange en hiver',
    'plats qu’on mange à la plage',
    'desserts',
    'boissons chaudes',
    'boissons gazeuses',
    'jus de fruits',
    'céréales du petit-déjeuner',
    'plats italiens',
    'plats asiatiques',
    'plats mexicains',
    'plats français',
    'plats qu’on mange avec du riz',
    'plats qu’on mange avec une fourchette',
    'plats qu’on mange avec une cuillère',
    'plats au four',
    'plats de grand-mère',
    'spécialités régionales françaises',
    'villes de France',
    'villes d’Italie',
    'villes d’Espagne',
    'villes d’Allemagne',
    'villes des États-Unis',
    'îles où partir en vacances',
    'fleuves du monde',
    'montagnes célèbres',
    'monuments célèbres',
    'musées célèbres',
    'merveilles du monde',
    'départements français',
    'régions françaises',
    'pays où il fait chaud',
    'pays où il fait froid',
    'pays qui commencent par la lettre A',
    'pays qui commencent par la lettre S',
    'prénoms de filles qui commencent par M',
    'prénoms de garçons qui commencent par T',
    'prénoms de garçons qui commencent par L',
    'prénoms de filles qui commencent par C',
    'mots qui commencent par la lettre B',
    'mots qui riment avec « chat »',
    'mots qui riment avec « maison »',
    'mots qui riment avec « bateau »',
    'mots de cinq lettres',
    'mots qui commencent par « pro »',
    'métiers qui commencent par la lettre C',
    'mots qu’on dit en rigolant',
    'mots qui font plaisir à entendre',
    'mots difficiles à prononcer',
    'mots d’argot qu’on utilise tous les jours',
    'mots anglais qu’on utilise en français',
    'mots qui commencent et finissent par la même lettre',
    'métiers qui se font dehors',
    'métiers qui se font de nuit',
    'métiers qui font peur aux enfants',
    'métiers qu’on rêvait de faire petit',
    'métiers dangereux',
    'métiers de la santé',
    'métiers qui demandent un uniforme',
    'métiers créatifs',
    'métiers avec un costume',
    'métiers où l’on porte un casque',
    'métiers où l’on porte une blouse',
    'métiers où l’on conduit',
    'métiers de l’école',
    'métiers de la mer',
    'métiers du cinéma',
    'métiers de la cuisine',
    'matières qu’on étudie à l’école',
    'moyens de transport',
    'moyens de transport en commun',
    'véhicules à deux roues',
    'véhicules d’urgence',
    'véhicules de chantier',
    'pièces d’une maison',
    'meubles',
    'appareils électroménagers',
    'objets qu’on branche',
    'objets qui fonctionnent avec des piles',
    'objets qu’on trouve dans une voiture',
    'objets qu’on trouve dans un avion',
    'objets qui servent à écrire',
    'objets qui servent à couper',
    'objets qui servent à nettoyer',
    'objets qui servent à mesurer',
    'objets qui servent à voir',
    'objets qui servent à attacher',
    'objets qui servent à ouvrir',
    'ustensiles de cuisine',
    'outils de bricolage',
    'accessoires de plage',
    'accessoires de ski',
    'accessoires de camping',
    'vêtements d’hiver',
    'vêtements d’été',
    'vêtements qu’on porte à la maison',
    'vêtements qui se portent au cou',
    'vêtements qui se portent aux pieds',
    'bijoux',
    'parties du corps qui commencent par la lettre C',
    'parties du visage',
    'os du corps humain',
    'organes du corps',
    'sens qu’on possède',
    'émotions',
    'qualités qu’on apprécie chez un ami',
    'défauts qui agacent chez un colocataire',
    'peurs communes',
    'phobies',
    'rêves d’enfant',
    'souvenirs d’enfance',
    'cadeaux de Noël',
    'cadeaux d’anniversaire',
    'cadeaux qu’on offre à une mamie',
    'décorations de Noël',
    'traditions de Noël',
    'fêtes de l’année',
    'jours fériés',
    'mois de l’année',
    'jours de la semaine',
    'saisons',
    'signes du zodiaque',
    'planètes',
    'constellations',
    'couleurs de l’arc-en-ciel',
    'formes géométriques',
    'chiffres romains',
    'unités de mesure',
    'monnaies du monde',
    'drapeaux avec du rouge',
    'drapeaux avec une étoile',
    'drapeaux tricolores',
    'sports de balle',
    'sports de raquette',
    'sports aquatiques',
    'sports de combat',
    'sports d’été',
    'sports qui se jouent à cheval',
    'sports olympiques',
    'sports qu’on pratique en solo',
    'sports extrêmes',
    'sports qui se jouent avec un ballon rond',
    'disciplines d’athlétisme',
    'clubs de football français',
    'équipes nationales de football',
    'accessoires de sport',
    'chansons de Noël',
    'chansons d’enfance',
    'chansons qu’on chante sous la douche',
    'chansons qu’on connaît par cœur',
    'chansons d’été',
    'chansons de dessin animé',
    'chansons de film Disney',
    'comptines',
    'genres de musique',
    'instruments à cordes',
    'instruments à vent',
    'instruments à percussion',
    'groupes de musique des années 80',
    'danses',
    'styles de danse',
    'pas de danse connus',
    'films d’aventure',
    'films de science-fiction',
    'films qui font pleurer',
    'films qu’on a vus plus de trois fois',
    'films d’animation',
    'films de super-héros',
    'films de pirates',
    'films qui se passent dans l’espace',
    'films avec des animaux',
    'films qui se passent à Noël',
    'films qui font rire',
    'sagas de films',
    'livres pour enfants',
    'bandes dessinées',
    'personnages de contes',
    'personnages de conte de fées',
    'créatures fantastiques',
    'monstres',
    'personnages de jeux vidéo',
    'personnages de la mythologie grecque',
    'dieux et déesses antiques',
    'personnages qui portent un chapeau',
    'personnages qui portent des lunettes',
    'personnages jaunes',
    'personnages bleus',
    'personnages verts',
    'aliments qu’on mange au petit-déjeuner',
    'aliments qu’on mange au goûter',
    'aliments qu’on mange pour Noël',
    'aliments qu’on mange avec du fromage',
    'aliments qu’on mange crus',
    'aliments en conserve',
    'aliments surgelés',
    'aliments qui piquent',
    'aliments sucrés',
    'aliments salés',
    'aliments acides',
    'aliments amers',
    'aliments croquants',
    'aliments mous',
    'aliments orange',
    'aliments jaunes',
    'aliments rouges',
    'aliments blancs',
    'aliments qui viennent de la mer',
    'aliments qui viennent d’une vache',
    'aliments qui viennent de la ruche',
    'aliments qu’on mange à la cuillère',
    'aliments qui ont une peau',
    'aliments qui ont un noyau',
    'aliments qui font pleurer en les coupant',
    'aliments qu’on trouve dans un burger',
    'aliments qu’on trouve dans un kebab',
    'aliments qu’on trouve dans une crêpe',
    'ingrédients d’une crêpe',
    'ingrédients d’une pizza',
    'ingrédients d’un gâteau au chocolat',
    'ingrédients d’une salade composée',
    'ingrédients d’un petit-déjeuner complet',
    'ingrédients d’un cocktail de fruits sans alcool',
    'ingrédients d’une soupe de légumes',
    'ingrédients d’un hamburger',
    'excuses pour ne pas faire ses devoirs',
    'excuses pour ne pas ranger sa chambre',
    'excuses pour ne pas sortir le chien',
    'excuses pour ne pas faire la vaisselle',
    'excuses pour sauter le sport',
    'excuses pour rester au lit',
    'excuses pour ne pas répondre à un message',
    'excuses pour rester sous la couette',
    'raisons de se lever tôt',
    'raisons de se coucher tard',
    'raisons de partir en vacances',
    'raisons de rire aux éclats',
    'raisons d’adopter un chien',
    'raisons de pleurer devant un film',
    'raisons d’être en retard',
    'raisons de faire une fête',
    'bruits d’animaux',
    'bruits de la maison la nuit',
    'bruits qu’on déteste',
    'bruits qui font peur',
    'bruits qu’on fait avec la bouche',
    'cris qu’on pousse quand on a peur',
    'sons relaxants',
    'odeurs de l’enfance',
    'odeurs qu’on adore',
    'odeurs qu’on déteste',
    'odeurs de la cuisine de grand-mère',
    'goûts de bonbons',
    'goûts de glace',
    'textures désagréables',
    'sensations agréables',
    'choses douces au toucher',
    'choses froides',
    'choses chaudes',
    'choses lourdes',
    'choses légères',
    'choses grandes',
    'choses minuscules',
    'choses très rapides',
    'choses très lentes',
    'choses très chères',
    'choses qu’on achète en soldes',
    'choses qu’on achète à la boulangerie',
    'choses qu’on achète au marché',
    'choses qu’on achète à la pharmacie',
    'choses qu’on achète en papeterie',
    'choses qu’on achète en jardinerie',
    'choses qu’on achète au tabac-presse',
    'choses qu’on achète sur internet',
    'choses qu’on offre à un nouveau-né',
    'choses qu’on offre pour un mariage',
    'choses qu’on offre pour une pendaison de crémaillère',
    'choses qu’on garde dans sa poche',
    'choses qu’on garde dans sa boîte à gants',
    'choses qu’on garde dans son portefeuille',
    'choses qu’on garde dans son sac à main',
    'choses qu’on garde dans un tiroir de cuisine',
    'choses qu’on garde sur sa table de nuit',
    'choses qu’on garde sur son bureau',
    'choses qu’on voit depuis une fenêtre de train',
    'choses qu’on voit dans le ciel',
    'choses qu’on voit dans la rue',
    'choses qu’on voit à la campagne',
    'choses qu’on voit à la mer',
    'choses qu’on voit au cirque',
    'choses qu’on voit dans un parc d’attractions',
    'choses qu’on voit dans une salle de classe',
    'choses qu’on voit dans un aquarium',
    'choses qu’on voit dans un champ',
    'choses qu’on voit en montagne',
    'choses qu’on entend dans un stade',
    'choses qu’on entend dans une gare',
    'choses qu’on entend à la campagne',
    'choses qu’on entend dans une cuisine',
    'choses qu’on entend en forêt',
    'choses qu’on entend à l’aéroport',
    'choses qu’on entend dans un cinéma',
    'choses qu’on dit à un bébé',
    'choses qu’on dit à son chien',
    'choses qu’on dit en cuisinant',
    'choses qu’on dit quand on gagne',
    'choses qu’on dit quand on perd',
    'choses qu’on dit en trinquant à un anniversaire',
    'choses qu’on dit quand on se fait mal',
    'choses qu’on dit en voyant une araignée',
    'choses qu’on crie dans un stade',
    'phrases que disent tous les parents',
    'phrases que disent tous les profs',
    'phrases qu’on dit au restaurant',
    'phrases qu’on dit en voiture',
    'phrases qu’on dit à la caisse',
    'phrases qu’on dit au téléphone',
    'phrases qu’on dit à la fin d’une réunion',
    'phrases qu’on entend dans un magasin',
    'proverbes français',
    'expressions avec un animal',
    'expressions avec une couleur',
    'expressions avec une partie du corps',
    'expressions avec de la nourriture',
    'expressions pour dire qu’on est fatigué',
    'expressions pour dire qu’il pleut beaucoup',
    'expressions pour dire qu’on est content',
    'expressions pour dire qu’on est surpris',
    'synonymes de « bizarre »',
    'synonymes de « très beau »',
    'synonymes de « fatigué »',
    'synonymes de « content »',
    'synonymes de « voiture »',
    'mots pour dire bonjour dans une autre langue',
    'mots pour dire merci dans une autre langue',
    'langues parlées en Asie',
    'langues parlées en Afrique',
    'langues romanes',
    'alphabets du monde',
    'inventions qui ont changé le monde',
    'inventions françaises',
    'inventions utiles à la maison',
    'inventions de cuisine',
    'inventions qui ne servent à rien',
    'inventions qu’on rêve de voir exister',
    'superpouvoirs qu’on aimerait avoir',
    'objets magiques de contes',
    'destinations de voyage rêvées',
    'souvenirs qu’on rapporte de vacances',
    'activités de vacances',
    'activités de week-end',
    'activités de printemps',
    'activités d’automne',
    'activités en famille',
    'activités à faire sous la pluie',
    'activités à faire avec des enfants',
    'activités à faire en voiture',
    'activités pour un anniversaire d’enfant',
    'activités qu’on peut faire au bord d’un lac',
    'passe-temps',
    'loisirs créatifs',
    'collections qu’on peut commencer',
    'résolutions de nouvelle année',
    'vœux pour la nouvelle année',
    'cadeaux de fête des mères',
    'excuses pour manger un dessert en plus',
    'astuces pour s’endormir',
    'astuces pour se réveiller',
    'astuces pour retenir un mot',
    'astuces pour faire des économies',
    'astuces de grand-mère',
    'astuces pour gagner du temps le matin',
    'astuces pour ne pas avoir le hoquet',
    'astuces pour ne pas avoir froid',
    'astuces pour ne pas avoir chaud',
    'bonnes résolutions',
    'petits bonheurs du quotidien',
    'choses agaçantes dans les transports en commun',
    'choses agaçantes en voiture',
    'choses agaçantes au cinéma',
    'choses agaçantes en vacances',
    'choses agaçantes au supermarché',
    'choses agaçantes en réunion',
    'choses agaçantes dans un avion',
    'choses agaçantes chez soi',
    'choses qui arrivent toujours au pire moment',
    'choses qu’on regrette d’avoir mangées',
    'choses qu’on mange sans faim',
    'choses qu’on mange devant un film',
    'choses qu’on mange à la fête foraine',
    'choses qu’on mange au cinéma',
    'choses qu’on mange au stade',
    'choses qu’on mange debout',
    'choses qu’on mange en marchant',
    'choses qu’on mange sur le pouce',
    'choses qu’on grignote',
    'choses qu’on trempe dans une sauce',
    'choses qu’on trempe dans le café',
    'choses qu’on trempe dans du chocolat',
    'choses qu’on peut griller',
    'choses qu’on peut faire sauter',
    'choses qu’on peut faire fondre',
    'choses qu’on peut faire bouillir',
    'choses qu’on peut congeler',
    'choses qu’on peut recycler',
    'choses qu’on peut réparer soi-même',
    'choses qu’on peut fabriquer avec du papier',
    'choses qu’on peut construire avec des cubes',
    'choses qu’on peut dessiner facilement',
    'choses qu’on peut faire avec une ficelle',
    'choses qu’on peut faire avec un ballon',
    'choses qu’on peut faire avec une boîte en carton',
    'choses qu’on peut faire avec une feuille',
    'choses qu’on peut faire avec un bâton',
    'choses qu’on peut faire avec une corde',
    'choses qu’on peut faire avec un drap',
    'choses qu’on peut faire avec un seul doigt',
    'choses qu’on peut faire avec les yeux fermés',
    'choses qu’on peut faire en une minute',
    'choses qu’on peut faire en une heure',
    'choses qu’on peut faire en un week-end',
  ],
  spicy: [
    'cocktails',
    'cocktails à base de rhum',
    'cocktails à base de vodka',
    'cocktails à base de gin',
    'cocktails à base de tequila',
    'cocktails à base de whisky',
    'cocktails avec des fruits',
    'cocktails sans alcool',
    'cocktails qui se boivent en été',
    'cocktails qui se servent dans un verre à pied',
    'cocktails qui se servent avec une paille',
    'cocktails qu’on commande en terrasse',
    'cocktails qu’on boit en vacances',
    'cocktails à bulles',
    'cocktails avec de la menthe',
    'cocktails avec du citron',
    'cocktails avec du sirop',
    'cocktails qui rendent malade le lendemain',
    'bières',
    'marques de bière',
    'types de bière',
    'marques de vodka',
    'marques de whisky',
    'marques de champagne',
    'marques de rhum',
    'marques de vin',
    'marques d’apéritifs',
    'apéritifs',
    'alcools forts',
    'alcools qu’on boit en digestif',
    'alcools de fête',
    'alcools qu’on a déjà regretté d’avoir bus',
    'alcools qui piquent la gorge',
    'vins rouges',
    'vins blancs',
    'régions viticoles',
    'cépages',
    'jeux à boire',
    'jeux de soirée',
    'jeux d’apéro',
    'jeux de cartes à boire',
    'défis de soirée',
    'gages de soirée',
    'règles d’un jeu à boire',
    'choses qu’on dit en trinquant',
    'façons de trinquer dans d’autres langues',
    'façons de dire qu’on a trop bu',
    'façons de dire qu’on est ivre',
    'excuses pour ne pas boire',
    'excuses pour partir d’une soirée',
    'excuses bidon pour annuler un rendez-vous',
    'excuses bidon pour ne pas aller au travail',
    'excuses bidon pour quitter une soirée ennuyeuse',
    'excuses bidon pour éviter un repas de famille',
    'excuses bidon pour ne pas rappeler quelqu’un',
    'excuses bidon pour un retard de deux heures',
    'excuses bidon pour un devoir pas rendu',
    'excuses bidon pour ne pas aider à déménager',
    'excuses bidon pour oublier un anniversaire',
    'excuses bidon pour ne pas répondre à un message',
    'excuses qu’on donne quand on arrive en retard à une soirée',
    'excuses qu’on donne à son patron',
    'excuses qu’on donne à son ex',
    'excuses qu’on donne pour ne pas sortir ce soir',
    'excuses qu’on donne quand on est démasqué',
    'excuses pour une grosse addition',
    'mensonges qu’on dit pour se faire bien voir',
    'mensonges qu’on dit à ses parents',
    'mensonges qu’on dit sur son CV',
    'mensonges qu’on dit en soirée',
    'mensonges qu’on dit à un rendez-vous',
    'petits mensonges du quotidien',
    'mensonges qu’on dit sur son âge',
    'mensonges qu’on dit sur son poids',
    'mensonges qu’on dit sur son travail',
    'mensonges qu’on dit pour avoir un jour de congé',
    'mensonges qu’on dit au médecin',
    'mensonges qu’on dit à son banquier',
    'applis de rencontre',
    'phrases d’accroche pour un premier message',
    'premiers messages nuls sur une appli de rencontre',
    'choses qu’on met dans sa bio d’appli de rencontre',
    'photos de profil qu’on voit trop souvent',
    'défauts qu’on cache à un premier rendez-vous',
    'sujets à éviter à un premier rendez-vous',
    'endroits pour un premier rendez-vous',
    'activités pour un premier rendez-vous',
    'restaurants pour un premier rendez-vous',
    'choses à ne pas dire à un premier rendez-vous',
    'questions à poser à un premier rendez-vous',
    'tenues pour un premier rendez-vous',
    'signes qu’on n’a pas de chance en amour',
    'signes qu’un rendez-vous se passe mal',
    'signes qu’un rendez-vous se passe très bien',
    'signes qu’on plaît à quelqu’un',
    'signes qu’on a un ticket avec quelqu’un',
    'signes qu’on est amoureux',
    'signes qu’on est jaloux',
    'signes qu’on est ghosté',
    'signes qu’une relation touche à sa fin',
    'signes qu’on a trop bu',
    'signes qu’il est temps de rentrer',
    'raisons de quitter quelqu’un',
    'raisons de se disputer en couple',
    'raisons de se réconcilier',
    'raisons de bloquer un ex',
    'raisons de ne pas répondre à un ex',
    'raisons de garder un ex en contact',
    'raisons de ne pas retourner avec son ex',
    'choses qu’on garde d’un ex',
    'choses qu’on regrette avec un ex',
    'choses qui agacent chez un ex',
    'cadeaux qu’on peut offrir à son ex',
    'prénoms d’ex qu’on ne veut plus entendre',
    'chansons qu’on écoute après une rupture',
    'chansons qu’on dédie à son ex',
    'chansons qu’on chante en soirée en hurlant',
    'chansons de karaoké',
    'chansons qu’on danse en soirée',
    'chansons de slow',
    'chansons romantiques',
    'chansons qui sont dans toutes les soirées',
    'chansons qu’on connaît tous par cœur à l’apéro',
    'chansons que tout le monde chante quand il a bu',
    'chansons de rupture',
    'chansons qu’on met pour se motiver avant de sortir',
    'chansons qu’on met au réveil le dimanche',
    'phrases de rupture',
    'phrases qu’on dit pour quitter quelqu’un gentiment',
    'phrases qu’on dit quand on est jaloux',
    'phrases qui énervent en couple',
    'phrases qu’on dit après une dispute',
    'phrases qu’on dit pour se faire pardonner',
    'phrases de drague nulles',
    'phrases de drague qui marchent',
    'phrases de drague qui ne marchent jamais',
    'phrases qu’on dit pour draguer au bar',
    'phrases qu’on dit pour refuser poliment un verre',
    'phrases qu’on dit pour décliner un numéro de téléphone',
    'phrases d’amour clichés',
    'prénoms qu’on ne donnera jamais à un enfant',
    'surnoms qu’on donne à son chéri ou sa chérie',
    'surnoms mignons pour un couple',
    'surnoms ridicules qu’on a eus',
    'surnoms qu’on a eus à l’école',
    'surnoms qu’on donne à ses amis',
    'surnoms de collègues',
    'surnoms de profs',
    'surnoms pour un bébé',
    'surnoms d’animaux de compagnie',
    'cadeaux romantiques',
    'cadeaux de Saint-Valentin',
    'cadeaux de dernière minute',
    'cadeaux nuls',
    'cadeaux qu’on revend après Noël',
    'cadeaux qu’on regifte',
    'cadeaux de mariage',
    'cadeaux qu’on offre à un couple',
    'cadeaux qu’on offre à un patron',
    'cadeaux qui font l’effet inverse de celui voulu',
    'endroits où faire une demande en mariage',
    'endroits où se disputer en public',
    'endroits où on a pleuré en public',
    'endroits où on s’est endormi en soirée',
    'endroits où on a perdu ses clés',
    'endroits où on a vomi au moins une fois',
    'endroits où on a honte d’être allé',
    'endroits où on a fini une soirée',
    'endroits où on peut dormir quand on rate le dernier métro',
    'endroits où on peut s’isoler en soirée',
    'endroits où on peut faire un selfie ridicule',
    'endroits où on se perd en soirée',
    'endroits où on se retrouve à 4 heures du matin',
    'endroits où manger après une soirée',
    'endroits où danser',
    'types de soirée',
    'types de boîtes de nuit',
    'types de personnes qu’on croise en soirée',
    'types de gens qui gâchent une soirée',
    'types d’invités en soirée',
    'types de collègues',
    'types d’ex',
    'types de voisins',
    'types de colocataires',
    'types d’amis qu’on a tous',
    'types de potes qui trahissent en soirée',
    'types de beaux-parents',
    'types de patrons',
    'types de dragueurs',
    'types de rendez-vous ratés',
    'types de réveils après une soirée',
    'types de gueules de bois',
    'remèdes contre la gueule de bois',
    'remèdes de grand-mère contre la gueule de bois',
    'choses qu’on mange après une soirée',
    'choses qu’on mange à 3 heures du matin',
    'choses qu’on boit après une soirée',
    'choses qu’on fait au lendemain d’une soirée',
    'choses qu’on regrette le lendemain d’une soirée',
    'choses qu’on découvre dans sa poche le lendemain',
    'choses qu’on retrouve dans son téléphone après une soirée',
    'choses qu’on poste en soirée et qu’on regrette',
    'choses qu’on envoie par message après minuit',
    'choses qu’on envoie à son ex quand on a bu',
    'choses qu’on dit quand on est ivre',
    'choses qu’on fait quand on est ivre',
    'choses qu’on ne dit jamais à son patron',
    'choses qu’on ne dit jamais à sa belle-mère',
    'choses qu’on ne dit jamais à un premier rendez-vous',
    'choses qu’on ne dit jamais en soirée',
    'choses qu’on ne dit jamais à son ex',
    'choses qu’on ne dit jamais à un inconnu',
    'choses qu’on ne dit jamais à un policier',
    'choses qu’on ne dit jamais à un vigile',
    'choses qu’on ne dit jamais à son médecin',
    'choses qu’on ne dit jamais à un serveur',
    'choses qu’on ne dit jamais à un chauffeur de taxi',
    'choses qu’on cache à ses parents',
    'choses qu’on cache à son conjoint',
    'choses qu’on cache à ses collègues',
    'choses qu’on cache à ses amis',
    'choses qu’on cache à ses voisins',
    'choses qu’on cache à son patron',
    'choses qu’on cache dans son téléphone',
    'choses qu’on cache sous son lit',
    'choses qu’on cache dans un placard',
    'choses qui gênent en public',
    'choses embarrassantes en public',
    'choses embarrassantes en soirée',
    'choses embarrassantes en réunion',
    'choses embarrassantes en couple',
    'choses embarrassantes au restaurant',
    'choses embarrassantes à la plage',
    'choses embarrassantes sur les réseaux sociaux',
    'choses embarrassantes qui arrivent en vacances',
    'choses embarrassantes qui arrivent chez les beaux-parents',
    'choses embarrassantes qui arrivent en avion',
    'choses embarrassantes qui arrivent à l’école',
    'choses embarrassantes qui arrivent au travail',
    'choses embarrassantes qui arrivent en rendez-vous',
    'choses embarrassantes que fait un parent',
    'moments gênants',
    'moments gênants en visioconférence',
    'moments gênants avec un voisin',
    'moments gênants avec un collègue',
    'moments gênants avec un ex',
    'moments gênants chez le médecin',
    'moments gênants dans un ascenseur',
    'moments gênants dans les transports',
    'moments gênants au cinéma',
    'moments gênants chez le coiffeur',
    'moments gênants en famille',
    'moments gênants en cours',
    'moments gênants en vestiaire',
    'moments gênants en soirée',
    'moments gênants qu’on a tous vécus',
    'moments où on aimerait disparaître',
    'moments où on a eu un fou rire interdit',
    'moments où on a fait semblant de comprendre',
    'moments où on a fait semblant de ne pas voir quelqu’un',
    'moments où on a fait semblant d’être malade',
    'moments où on a menti pour se sortir d’un mauvais pas',
    'moments où on a dit « je t’aime » trop vite',
    'moments où on a envoyé un message à la mauvaise personne',
    'moments où on a appelé quelqu’un par le mauvais prénom',
    'moments où on a ri au mauvais moment',
    'moments où on est tombé en public',
    'moments où on a oublié le nom de quelqu’un',
    'moments où on a répondu « toi aussi » au mauvais moment',
    'moments où on a pris un râteau',
    'moments où on a pris un vent',
    'moments où on a été ghosté',
    'moments où on a ghosté quelqu’un',
    'moments où on a stalké quelqu’un',
    'moments où on a liké une vieille photo par erreur',
    'moments où on a dit une bêtise devant tout le monde',
    'moments où on s’est trompé de porte',
    'moments où on a perdu quelqu’un en soirée',
    'moments où on a perdu son téléphone en soirée',
    'moments où on a oublié ses clés dehors',
    'moments où on a raté le dernier métro',
    'moments où on a dansé sur une table',
    'moments où on a chanté trop fort',
    'moments où on a pleuré devant tout le monde',
    'moments où on a mis la honte à ses amis',
    'moments où on a été mis à la porte',
    'moments où on s’est fait repérer en train de mentir',
    'moments où on a trop parlé',
    'moments où on a posté la mauvaise story',
    'moments où on a répondu à tous au lieu de répondre à un seul',
    'moments où on a eu un fou rire en réunion',
    'moments où on s’est endormi en public',
    'applications qu’on a honte d’avoir sur son téléphone',
    'applications qu’on ouvre sans y penser',
    'applications qu’on ouvre aux toilettes',
    'applications de livraison de repas',
    'applications de transport',
    'applications pour se faire des amis',
    'applications qui espionnent',
    'applications de photo',
    'applications de messagerie',
    'applications de musique',
    'applications de fitness qu’on n’utilise jamais',
    'applications qu’on supprime après une rupture',
    'comptes qu’on stalke sur Instagram',
    'hashtags qu’on utilise',
    'filtres de photo',
    'types de stories',
    'types de publications agaçantes',
    'types d’influenceurs',
    'types de selfies',
    'types de statuts sur les réseaux',
    'types de photos de vacances',
    'types de messages vocaux',
    'types de SMS qu’on ne veut pas recevoir',
    'types de SMS qu’on veut recevoir',
    'types d’emojis qu’on utilise trop',
    'emojis qui ont un double sens',
    'emojis qui sèment la confusion',
    'emojis qu’on envoie à ses amis',
    'emojis qu’on envoie à la personne qu’on aime bien',
    'emojis qu’on envoie à son patron',
    'emojis qu’on n’ose pas envoyer',
    'emojis de visage',
    'emojis de nourriture',
    'emojis d’animaux',
    'séries qu’on binge-watche',
    'séries qu’on regarde en cachette',
    'séries qu’on regarde en couple',
    'séries romantiques',
    'séries sur un lycée',
    'séries policières',
    'séries d’horreur',
    'séries d’animation pour adultes',
    'séries avec des vampires',
    'séries qui se passent dans un hôpital',
    'séries qui se passent dans un bar',
    'séries françaises',
    'séries cultes',
    'séries à la télé-réalité',
    'émissions de dating',
    'émissions de cuisine',
    'émissions de téléréalité qu’on regarde en cachette',
    'émissions de télé du dimanche soir',
    'émissions qui passent en boucle l’après-midi',
    'émissions de talent',
    'émissions de chant',
    'émissions de voyance',
    'films romantiques',
    'films de braquage',
    'films d’espionnage',
    'films de vampires',
    'films de zombies',
    'films de mafia',
    'films de guerre',
    'films de western',
    'films qui se passent à Paris',
    'films qui se passent à New York',
    'films qui se passent en Italie',
    'films qu’on regarde quand on est triste',
    'films qu’on regarde pour pleurer',
    'films qu’on regarde pour rire',
    'films qu’on regarde pour avoir peur',
    'films qu’on regarde en couple',
    'films qu’on regarde entre amis',
    'films qu’on regarde le dimanche soir',
    'films qu’on regarde pendant les vacances',
    'films qui ont fait pleurer tout le monde',
    'films où tout le monde meurt à la fin',
    'films dont tout le monde cite les répliques',
    'films dont on connaît tous la fin',
    'films cultes des années 90',
    'films cultes des années 2000',
    'suites de films qui sont nulles',
    'répliques cultes de films',
    'répliques cultes de séries',
    'répliques de films qu’on peut dire en soirée',
    'comédies romantiques',
    'comédies musicales',
    'duos célèbres de fiction',
    'couples célèbres de fiction',
    'couples célèbres de films',
    'couples célèbres de séries',
    'couples de dessins animés',
    'couples mythiques',
    'couples mal assortis',
    'couples qui se séparent à la fin du film',
    'vilains de films',
    'personnages de séries qu’on aime détester',
    'personnages de séries qu’on voudrait pour ami',
    'personnages de séries qu’on voudrait pour collègue',
    'personnages de séries qu’on voudrait pour colocataire',
    'personnages de séries qu’on voudrait comme voisin',
    'personnages de séries qui sont bien habillés',
    'personnages de fiction qu’on aimerait inviter en soirée',
    'métiers où on boit beaucoup',
    'métiers de la nuit',
    'métiers de la fête',
    'métiers de bar',
    'métiers où on est bien payé',
    'métiers où on voyage beaucoup',
    'métiers où on rencontre des célébrités',
    'métiers où on porte un costume',
    'métiers où on parle à des gens toute la journée',
    'métiers où on ne voit jamais la lumière du jour',
    'métiers qu’on ferait pour rire',
    'métiers qui font rêver',
    'métiers qu’on ne ferait pour rien au monde',
    'métiers qu’on ferait si on gagnait au loto',
    'métiers qu’on cite pour impressionner en soirée',
    'métiers qui font de bons rendez-vous',
    'objets qu’on perd en soirée',
    'objets qu’on trouve dans un bar',
    'objets qu’on trouve dans une boîte de nuit',
    'objets qu’on trouve dans un sac de soirée',
    'objets qu’on trouve dans la poche d’un fêtard',
    'objets qu’on trouve dans une voiture après une soirée',
    'objets qu’on emprunte à un ami et qu’on ne rend jamais',
    'objets qu’on vole dans les hôtels',
    'objets qu’on a déjà volés en soirée',
    'objets qu’on a déjà perdus en soirée',
    'objets qui servent à cacher un secret',
    'objets qu’on trouve dans un sac de voyage',
    'objets qu’on emporte en week-end en amoureux',
    'objets qu’on emporte en soirée pyjama',
    'objets qu’on emporte en festival',
    'objets qu’on emporte en voyage entre amis',
    'objets qu’on emporte chez les parents d’un ami',
    'tenues de soirée',
    'tenues déguisées',
    'tenues pour une soirée à thème',
    'thèmes de soirée déguisée',
    'déguisements faciles à faire',
    'déguisements qu’on voit à chaque fête',
    'déguisements qu’on met pour Halloween',
    'déguisements de couple',
    'déguisements qui font rire',
    'accessoires de soirée',
    'accessoires de festival',
    'accessoires de karaoké',
    'accessoires de mariage',
    'accessoires d’enterrement de vie de garçon',
    'accessoires d’enterrement de vie de jeune fille',
    'activités d’enterrement de vie de garçon',
    'activités d’enterrement de vie de jeune fille',
    'idées de gages pour un enterrement de vie de jeune fille',
    'idées de gages pour un enterrement de vie de garçon',
    'idées de gages pour une soirée entre amis',
    'idées de soirée à la maison',
    'idées de soirée à thème',
    'idées de soirée à deux',
    'idées de week-end entre amis',
    'idées de week-end en couple',
    'idées de sorties du samedi soir',
    'idées pour fêter un anniversaire',
    'idées pour fêter un diplôme',
    'idées pour fêter une promotion',
    'idées pour rendre une soirée mémorable',
    'idées pour pimenter un dimanche pluvieux',
    'idées de surprise pour un anniversaire',
    'idées de cadeaux pour un pot de départ',
    'idées de toasts',
    'idées de jeux à faire en voiture',
    'idées de jeux pour un apéro',
    'idées de défis entre amis',
    'idées pour animer un repas de famille',
    'idées pour calmer une dispute',
    'idées pour s’excuser',
    'idées pour impressionner un invité',
    'idées pour faire rire sa moitié',
    'idées de recette à faire avec de l’alcool',
    'idées d’apéro dînatoire',
    'idées de plats à partager',
    'idées de plats à préparer quand on invite',
    'idées de plats pour impressionner',
    'idées de desserts rapides',
    'choses qu’on dit à un barman',
    'choses qu’on commande en boîte',
    'choses qu’on commande au bar',
    'choses qu’on commande en terrasse',
    'choses qu’on commande au restaurant pour impressionner',
    'choses qu’on commande quand on a un petit budget',
    'choses qu’on commande à 3 heures du matin',
    'choses qu’on commande pour se faire pardonner',
    'choses qu’on offre à un verre',
    'choses qu’on offre à un premier rendez-vous',
    'choses qu’on offre pour un anniversaire de rencontre',
    'plats de rendez-vous',
    'plats qui font tache sur une chemise blanche',
    'plats qui sentent fort',
    'plats qu’on évite à un premier rendez-vous',
    'plats qu’on partage en amoureux',
    'plats qu’on mange avec des baguettes',
    'plats qu’on mange avec les mains',
    'plats qui donnent mauvaise haleine',
    'plats qui rendent amoureux',
    'ingrédients d’un bon apéro',
    'ingrédients d’un mojito',
    'ingrédients d’un cocktail maison',
    'ingrédients d’un plateau de fromages',
    'ingrédients d’une planche apéro',
    'ingrédients d’une tarte flambée',
    'ingrédients d’une raclette',
    'ingrédients d’une fondue',
    'ingrédients d’un burger de fête',
    'ingrédients d’une sangria',
    'ingrédients d’un punch',
    'ingrédients d’un vin chaud',
    'ingrédients d’un petit-déjeuner de lendemain de soirée',
    'ingrédients d’un repas de réconciliation',
    'ingrédients d’un dîner aux chandelles',
    'ingrédients d’une soirée parfaite',
    'ingrédients d’une soirée réussie',
    'ingrédients d’un week-end réussi',
    'ingrédients d’un bon couple',
    'ingrédients d’une bonne amitié',
    'ingrédients d’un bon rendez-vous',
    'ingrédients d’un mariage réussi',
    'ingrédients d’un fou rire',
  ],
  hot: [
    'surnoms coquins',
    'endroits où s’embrasser en cachette',
    'accessoires de séduction',
    'endroits insolites où s’embrasser',
    'endroits romantiques pour un premier baiser',
    'endroits où on a déjà roulé une pelle',
    'endroits où on a envie de s’embrasser passionnément',
    'endroits où on a déjà flirté',
    'endroits où on peut se faire des câlins à deux',
    'endroits où on peut s’isoler à deux',
    'endroits où on peut se retrouver en cachette',
    'endroits pour un week-end coquin',
    'endroits où on peut se faire un bisou discret',
    'endroits où s’embrasser sous la pluie',
    'endroits où s’embrasser pendant un voyage',
    'endroits où on a déjà eu un coup de foudre',
    'endroits où on rencontre des gens',
    'endroits où on peut passer une nuit à deux',
    'endroits où on se fait des mots doux',
    'hôtels où passer une nuit en amoureux',
    'lieux de vacances romantiques',
    'villes romantiques',
    'destinations pour une escapade amoureuse',
    'décors pour un rendez-vous romantique',
    'ambiances pour une soirée romantique',
    'musiques pour une soirée romantique',
    'chansons sensuelles',
    'chansons pour séduire',
    'chansons de slow langoureux',
    'chansons à mettre pour un dîner aux chandelles',
    'chansons qui parlent de désir',
    'chansons qu’on dédie à quelqu’un qu’on aime',
    'chansons à écouter à deux',
    'films sexy',
    'films qui donnent envie de s’embrasser',
    'films à regarder en amoureux sous la couette',
    'séries qui font monter la température',
    'scènes de films romantiques cultes',
    'scènes de baisers cultes',
    'baisers célèbres de films',
    'comédies romantiques à voir en couple',
    'accessoires de lingerie',
    'pièces de lingerie',
    'tenues sexy',
    'tenues qui font de l’effet',
    'tenues qui font craquer',
    'tenues pour séduire',
    'tenues de soirée qui font tourner les têtes',
    'tenues de déguisement coquines',
    'tenues de soirée d’été qui font de l’effet',
    'tenues qu’on porte pour un rendez-vous',
    'tenues qu’on enlève en premier',
    'vêtements qui moulent',
    'vêtements qu’on aime voir sur son partenaire',
    'vêtements qu’on emprunte à son partenaire',
    'chaussures qui font de l’effet',
    'parfums qui font tourner la tête',
    'parfums qui sentent bon sur la peau',
    'odeurs qui donnent envie',
    'odeurs qui plaisent chez son partenaire',
    'odeurs d’une peau qui plaît',
    'huiles de massage',
    'huiles parfumées',
    'parfums de bougie sensuelle',
    'bougies de soirée',
    'bougies parfumées',
    'idées de massage',
    'types de massage',
    'zones du corps où on aime être massé',
    'zones du corps où on aime être embrassé',
    'zones du corps où on a des chatouilles',
    'zones du corps qui sont sensibles aux caresses',
    'parties du corps qui plaisent chez l’autre',
    'parties du corps qu’on regarde en premier',
    'parties du corps qu’on trouve sexy',
    'parties du corps qu’on aime caresser',
    'parties du corps où on aime recevoir un bisou',
    'parties du corps où on met du parfum',
    'parties du corps qu’on rase pour l’été',
    'parties du corps qu’on aime bronzer',
    'choses qui font fondre quand on est amoureux',
    'choses qui font craquer chez quelqu’un',
    'choses qui plaisent chez un partenaire',
    'choses qui plaisent chez un homme',
    'choses qui plaisent chez une femme',
    'choses qui font de l’effet chez un partenaire',
    'choses qui rendent quelqu’un séduisant',
    'choses qui rendent quelqu’un irrésistible',
    'choses qui donnent confiance en séduction',
    'choses qui donnent des papillons dans le ventre',
    'choses qui font rougir',
    'choses qui font battre le cœur plus vite',
    'choses qui font monter la température',
    'choses qui mettent dans l’ambiance',
    'choses qui mettent de bonne humeur au réveil à deux',
    'choses qui détendent avant un câlin',
    'choses qu’on fait pour séduire',
    'choses qu’on fait pour faire craquer quelqu’un',
    'choses qu’on fait pour attirer l’attention de quelqu’un',
    'choses qu’on fait pour mettre à l’aise un rendez-vous',
    'choses qu’on fait pour se rapprocher de quelqu’un en soirée',
    'choses qu’on fait pour flirter',
    'choses qu’on fait pour passer à l’étape suivante',
    'choses qu’on fait pour se réconcilier sur l’oreiller',
    'choses qu’on fait au lit à part dormir',
    'choses qu’on fait en amoureux sous la couette',
    'choses qu’on fait à deux dans un bain',
    'choses qu’on fait à deux sous la douche',
    'choses qu’on fait à deux dans un hamac',
    'choses qu’on fait à deux sur la plage',
    'choses qu’on fait à deux au clair de lune',
    'choses qu’on fait à deux pour s’amuser',
    'choses qu’on fait à deux le dimanche matin',
    'choses qu’on fait après un baiser',
    'choses qu’on fait avant un baiser',
    'choses qu’on fait pendant un baiser',
    'choses qu’on dit à l’oreille de son partenaire',
    'choses qu’on chuchote à l’oreille',
    'choses qu’on murmure dans le noir',
    'choses qu’on dit pour dire à quelqu’un qu’il plaît',
    'choses qu’on dit pour faire un compliment coquin',
    'choses qu’on dit pour draguer au bar',
    'choses qu’on dit pour inviter quelqu’un chez soi',
    'choses qu’on dit pour finir la soirée à deux',
    'choses qu’on dit après un baiser',
    'choses qu’on dit à quelqu’un pour le faire rougir',
    'choses qu’on dit en couple dans l’intimité',
    'choses qu’on dit à son chéri ou sa chérie au réveil',
    'choses qu’on écrit dans un message coquin',
    'choses qu’on écrit dans un mot doux',
    'choses qu’on écrit sur une carte de Saint-Valentin',
    'choses qu’on envoie à quelqu’un qui plaît',
    'choses qu’on envoie à son chéri ou sa chérie en journée',
    'messages qu’on envoie à quelqu’un qui plaît',
    'messages qu’on envoie après un premier rendez-vous réussi',
    'messages qu’on envoie à son crush à minuit',
    'messages qu’on envoie à son partenaire pour le taquiner',
    'messages doux qu’on envoie le matin',
    'messages qui font sourire un partenaire',
    'messages qu’on regrette d’avoir envoyés à un crush',
    'compliments qu’on fait à un partenaire',
    'compliments qui font fondre',
    'compliments sur un physique',
    'compliments sur un sourire',
    'compliments sur un regard',
    'compliments sur des mains',
    'compliments sur une voix',
    'compliments qu’on reçoit avec plaisir',
    'compliments pour séduire en soirée',
    'compliments gênants',
    'compliments bien maladroits',
    'compliments originaux',
    'phrases d’accroche coquines',
    'phrases d’accroche qui font sourire',
    'phrases d’accroche pour aborder quelqu’un',
    'phrases d’accroche à ne jamais utiliser',
    'phrases de séduction',
    'phrases pour inviter quelqu’un à danser',
    'phrases pour proposer un verre',
    'phrases pour proposer un deuxième rendez-vous',
    'phrases d’amour',
    'phrases à dire les yeux dans les yeux',
    'phrases qui font tomber amoureux',
    'phrases qui font fondre',
    'phrases qui rendent tout rouge',
    'phrases qu’on rêve d’entendre',
    'phrases qui donnent des frissons',
    'phrases qu’on murmure au creux de l’oreille',
    'mots doux',
    'mots d’amour',
    'mots coquins',
    'mots qui font rougir',
    'mots qui rendent amoureux',
    'mots qui donnent envie d’embrasser',
    'mots qui parlent d’amour',
    'mots qui font sourire à deux',
    'mots à double sens',
    'mots qui ont un double sens coquin',
    'expressions à double sens',
    'expressions qui parlent d’amour',
    'expressions coquines',
    'expressions pour dire « embrasser »',
    'expressions pour dire qu’on est amoureux',
    'expressions pour dire qu’on a un faible pour quelqu’un',
    'expressions pour dire qu’on a flashé sur quelqu’un',
    'expressions pour dire qu’on a envie de quelqu’un',
    'expressions pour dire qu’on est attiré par quelqu’un',
    'façons de dire « embrasser »',
    'façons de dire « je t’aime »',
    'façons d’embrasser',
    'façons de séduire',
    'façons de séduire sans parler',
    'façons de séduire au bar',
    'façons de séduire quelqu’un de timide',
    'façons de flirter en public',
    'façons de flirter sans se faire repérer',
    'façons de se faire remarquer',
    'façons de faire un premier pas',
    'façons de prendre la main de quelqu’un',
    'façons de se rapprocher de quelqu’un',
    'façons de se faire désirer',
    'façons de faire un clin d’œil',
    'façons de dire à quelqu’un qu’il nous plaît',
    'façons de proposer un baiser',
    'façons de commencer une soirée à deux',
    'façons de finir une soirée en beauté à deux',
    'façons de raviver la flamme dans un couple',
    'façons de surprendre son partenaire',
    'façons de pimenter une relation',
    'façons de se réconcilier avec un baiser',
    'façons de réveiller son partenaire en douceur',
    'façons de dire bonne nuit à son partenaire',
    'façons de faire craquer son crush',
    'façons de se faire pardonner un oubli',
    'idées de rendez-vous coquins',
    'idées de rendez-vous romantiques',
    'idées de soirée en amoureux',
    'idées pour surprendre son partenaire',
    'idées pour pimenter une soirée à deux',
    'idées de cadeaux coquins',
    'idées de cadeaux sensuels',
    'idées de cadeaux pour la Saint-Valentin',
    'idées de dîner aux chandelles',
    'idées de week-end en amoureux',
    'idées de jeux à faire à deux',
    'idées de jeux coquins entre adultes',
    'idées de défis à deux',
    'idées de gages doux pour un couple',
    'idées de petits mots à laisser',
    'idées pour séduire quelqu’un',
    'idées pour un premier baiser',
    'idées pour demander à quelqu’un de sortir avec nous',
    'idées pour attirer le regard d’un crush',
    'idées pour faire monter la tension à deux',
    'idées pour que son partenaire se sente désiré',
    'idées de câlins à deux',
    'idées pour un câlin parfait',
    'idées de petits-déjeuners au lit',
    'idées de plats aphrodisiaques',
    'aliments aphrodisiaques',
    'aliments qui se mangent de façon sensuelle',
    'aliments qu’on partage en amoureux',
    'aliments qu’on s’offre à la becquée',
    'aliments qu’on mange à deux au lit',
    'boissons de séduction',
    'boissons qu’on offre pour séduire',
    'boissons romantiques',
    'boissons pour une soirée à deux',
    'cocktails qu’on sirote à deux',
    'cocktails qu’on offre à quelqu’un qui nous plaît',
    'cocktails qui mettent d’humeur coquine',
    'cocktails sexy',
    'cocktails au nom osé',
    'cocktails qui ont un nom coquin',
    'cocktails romantiques',
    'desserts sensuels',
    'desserts à partager à deux',
    'desserts qui se mangent avec les doigts',
    'desserts au chocolat',
    'fruits sensuels',
    'fruits qui se mangent de façon sensuelle',
    'fruits qu’on aime croquer à deux',
    'chocolats de Saint-Valentin',
    'sucreries qu’on s’offre en amoureux',
    'jeux de séduction',
    'jeux de rôle entre adultes consentants',
    'jeux de rôle de couple',
    'jeux qui rapprochent à deux',
    'jeux de cartes à deux',
    'jeux à faire sous la couette',
    'jeux à faire dans un bain',
    'jeux d’obscurité',
    'jeux qui font monter la température',
    'jeux à boire pour couples',
    'jeux à boire coquins entre adultes',
    'défis de séduction',
    'défis entre amoureux',
    'défis qui font rougir',
    'défis pour faire rougir son partenaire',
    'défis de Saint-Valentin',
    'gages doux entre amoureux',
    'gages coquins entre adultes consentants',
    'gages qui font rougir',
    'gages à faire à son partenaire',
    'gages à faire pendant un slow',
    'gages qui amusent un couple',
    'gages à faire devant son crush',
    'gages de soirée un peu osés',
    'gestes de tendresse',
    'gestes doux entre amoureux',
    'gestes qui font fondre',
    'gestes qui montrent qu’on est attiré',
    'gestes qui trahissent un crush',
    'gestes de séduction',
    'gestes qu’on fait quand on flirte',
    'gestes qui donnent des frissons',
    'gestes coquins qu’on peut faire en public',
    'gestes qui font comprendre qu’on a envie d’un baiser',
    'gestes qui font comprendre qu’on veut rester seul avec quelqu’un',
    'gestes romantiques',
    'gestes tendres le matin',
    'gestes qu’on fait pour se réchauffer à deux',
    'gestes qu’on fait pour faire un clin d’œil à son partenaire',
    'gestes qu’on fait quand on est amoureux',
    'regards qui en disent long',
    'regards qui font fondre',
    'regards qui disent « viens »',
    'regards qu’on lance en soirée',
    'regards qu’on échange sans parler',
    'regards complices entre amoureux',
    'sourires qui font craquer',
    'sourires de séducteur',
    'sourires en coin',
    'voix qui font fondre',
    'voix sensuelles',
    'voix de radio qui font rêver',
    'prénoms sexy',
    'prénoms romantiques',
    'prénoms qui font rêver',
    'prénoms de crushs',
    'prénoms de filles qui font craquer',
    'prénoms de garçons qui font craquer',
    'personnages de fiction séduisants',
    'personnages de fiction qui font craquer',
    'personnages de séries qu’on trouve sexy',
    'personnages de séries qui sont des séducteurs',
    'personnages de films qui sont des séducteurs',
    'personnages de dessin animé qui nous ont fait craquer étant enfants',
    'personnages de films dont on a été amoureux',
    'personnages de livres dont on est tombé amoureux',
    'séducteurs de fiction',
    'séductrices de fiction',
    'couples de fiction qu’on adore',
    'couples de fiction qui ont une belle alchimie',
    'couples de fiction qui s’embrassent sous la pluie',
    'couples de fiction qui ont une relation compliquée',
    'duos de fiction qui ont une tension romantique',
    'tensions romantiques de séries',
    'histoires d’amour de séries',
    'histoires d’amour de films',
    'histoires d’amour de dessins animés',
    'histoires d’amour de contes',
    'histoires d’amour de livres',
    'histoires d’amour impossibles',
    'histoires d’amour de vacances',
    'histoires d’amour qui commencent en soirée',
    'histoires d’amour qui commencent au travail',
    'histoires d’amour qui commencent par une dispute',
    'histoires d’amour qui commencent entre amis',
    'histoires d’amour qui commencent sur une appli',
    'histoires d’amour qui commencent dans un train',
    'histoires d’amour qui commencent par un coup de foudre',
    'moments où on a eu un coup de foudre',
    'moments où on a rougi devant son crush',
    'moments où on a flirté sans le vouloir',
    'moments où on a failli embrasser quelqu’un',
    'moments où on a roulé une pelle à quelqu’un',
    'moments où on a embrassé quelqu’un en soirée',
    'moments où on a embrassé quelqu’un sur un coup de tête',
    'moments où on a embrassé quelqu’un devant tout le monde',
    'moments où on a pris la main de quelqu’un',
    'moments où on s’est retrouvé trop près de son crush',
    'moments où on a dansé collé-serré',
    'moments où on a dansé un slow',
    'moments où on a dormi chez quelqu’un',
    'moments où on a dit « je t’aime » trop tôt',
    'moments où on a fait un compliment osé',
    'moments où on a envoyé un message coquin',
    'moments où on a reçu un message coquin',
    'moments où on s’est fait surprendre en train de s’embrasser',
    'moments où on s’est caché pour s’embrasser',
    'moments où on a eu des papillons dans le ventre',
    'moments où on a rendu quelqu’un jaloux volontairement',
    'moments où on a eu un fou rire pendant un baiser',
    'moments où on s’est embrassé sous la pluie',
    'moments où on s’est embrassé à minuit pour le nouvel an',
    'moments où on s’est embrassé dans un lieu insolite',
    'moments où on a fait le premier pas',
    'moments où on a attendu un message toute la nuit',
    'moments où on a rêvé de quelqu’un qu’on connaît',
    'moments où on a eu des pensées coquines en public',
    'moments où on a eu un crush sur un ami',
    'moments où on a eu un crush sur un collègue',
    'moments où on a eu un crush sur un voisin',
    'moments où on a eu un crush sur un serveur ou une serveuse',
    'moments où on a eu un crush sur un inconnu dans le métro',
    'raisons de craquer pour quelqu’un',
    'raisons de ne pas craquer pour quelqu’un',
    'raisons de dire non à un verre',
    'raisons de dire oui à un deuxième rendez-vous',
    'raisons de ne pas donner son numéro',
    'raisons de donner son numéro',
    'raisons de s’embrasser',
    'raisons de s’embrasser en cachette',
    'raisons de rougir',
    'raisons de ne pas oser faire le premier pas',
    'raisons de dire « je t’aime »',
    'raisons de bouder après un baiser',
    'raisons qui font qu’un couple s’éloigne',
    'raisons de rester au lit le dimanche',
    'raisons de rester chez soi avec quelqu’un',
    'raisons de garder quelqu’un dans ses bras',
    'raisons d’être jaloux',
    'raisons de ne pas être jaloux',
    'raisons de sourire en pensant à quelqu’un',
    'raisons de se rapprocher de quelqu’un',
    'raisons de faire un câlin',
    'raisons de donner rendez-vous à quelqu’un',
    'signes de désir',
    'signes d’attirance',
    'signes de séduction',
    'signes qu’on est attiré par quelqu’un',
    'signes qu’on a envie d’un baiser',
    'signes qu’on est sous le charme',
    'signes qu’on veut rester dormir chez quelqu’un',
    'signes qu’on a un faible pour quelqu’un',
    'signes qu’on est en train de flirter',
    'signes que quelqu’un nous drague',
    'signes que quelqu’un nous fait de l’effet',
    'signes qu’un premier baiser arrive',
    'signes qu’une soirée tourne à la séduction',
    'signes qu’un rendez-vous va finir à deux',
    'signes qu’on a le cœur qui s’emballe',
    'signes d’un coup de foudre',
    'signes d’un couple amoureux',
    'signes d’un couple en pleine lune de miel',
    'signes que la flamme s’éteint',
    'signes que la flamme est toujours là',
    'signes que quelqu’un est timide en amour',
    'signes qu’on veut un deuxième rendez-vous',
    'signes qu’on est amoureux sans le savoir',
    'signes qu’on est fait l’un pour l’autre',
    'signes qu’on veut embrasser quelqu’un',
    'types de baisers',
    'types de câlins',
    'types de séducteurs',
    'types de séductrices',
    'types de dragueurs en soirée',
    'types de dragueurs sur les applis',
    'types de dragueurs lourds',
    'types de rendez-vous romantiques',
    'types de crushs',
    'types d’amoureux',
    'types de relations',
    'types de flirts',
    'types de premiers rendez-vous',
    'types de soirées à deux',
    'types de week-ends en amoureux',
    'types de cadeaux romantiques',
    'types de lettres d’amour',
    'types de mots doux',
    'types de regards en soirée',
    'types de danseurs en soirée',
    'types de slows',
    'types de baisers dans les films',
    'types de caresses',
    'surnoms qu’on donne à son crush dans sa tête',
    'surnoms mignons pour son chéri',
    'surnoms mignons pour sa chérie',
    'surnoms de couple qui font rougir',
    'surnoms de couple qui font rire',
    'surnoms de couple qu’on trouve ridicules',
    'surnoms qu’on donne en privé',
    'surnoms qu’on murmure',
    'surnoms qu’on n’ose pas dire en public',
    'surnoms qu’on donne à un amoureux timide',
    'surnoms avec des animaux',
    'surnoms avec de la nourriture',
    'surnoms avec des fruits',
    'surnoms avec des bonbons',
    'cadeaux qui disent « je pense à toi »',
    'cadeaux qui disent « tu me plais »',
    'cadeaux romantiques à faire à son crush',
    'cadeaux sensuels pour un anniversaire de couple',
    'cadeaux osés pour un anniversaire de couple',
    'cadeaux qui font rougir',
    'cadeaux de lune de miel',
    'cadeaux pour une nuit en amoureux',
    'cadeaux pour un week-end en amoureux',
    'cadeaux qu’on offre pour un premier anniversaire de couple',
    'cadeaux qu’on offre pour séduire',
    'cadeaux de Saint-Valentin ratés',
    'cadeaux de Saint-Valentin originaux',
    'fleurs romantiques',
    'fleurs qu’on offre pour séduire',
    'bouquets de fleurs pour s’excuser',
    'bijoux qu’on offre à une amoureuse',
    'bijoux qu’on offre à un amoureux',
    'bijoux qui font de l’effet',
    'bijoux sexy',
    'accessoires coquins pour une soirée déguisée',
    'accessoires pour une soirée à deux',
    'accessoires pour un dîner aux chandelles',
    'accessoires pour un bain à deux',
    'accessoires pour une soirée romantique',
    'accessoires pour séduire en soirée',
    'accessoires pour séduire quelqu’un',
    'accessoires pour un pique-nique romantique',
    'accessoires pour un week-end en amoureux',
    'accessoires de plage romantiques',
    'accessoires de salle de bain pour un bain à deux',
    'accessoires de chambre romantique',
    'accessoires d’un lit douillet',
    'accessoires pour pimenter une soirée',
    'accessoires de déguisement sexy',
    'accessoires de déguisement d’infirmière',
    'accessoires de déguisement d’ange',
  ],
}
