import type { Level } from '../engine'

export interface Suspect {
  name: string
  emoji: string
  /** Pays auquel on associe la personnalité. */
  flag: string
  /** Décédé à la rédaction (2026). */
  dead?: boolean
  /** Condamné au moins une fois par la justice. */
  convicted?: boolean
  /** Le casier, en une phrase d'humour noir. */
  record: string
  /** Titre de l'article Wikipédia (FR) quand il diffère du nom, pour la photo. */
  wiki?: string
}

/**
 * Qui est-ce ? version casier judiciaire. Les fiches s'en tiennent à des faits
 * publics établis : pour les vivants, uniquement des condamnations, des aveux
 * ou des faits incontestés, jamais de simples accusations.
 * Soft : escrocs et vauriens célèbres, Épicé : dictateurs, terroristes et
 * parrains, Hot : le pire de l'humour noir.
 */
export const suspects: Record<Level, Suspect[]> = {
  soft: [
    { name: 'Al Capone', emoji: '🎩', flag: '🇺🇸', dead: true, convicted: true, record: 'Roi de la pègre de Chicago, tombé pour… sa déclaration d’impôts.' },
    { name: 'Raspoutine', wiki: "Grigori Raspoutine", emoji: '🧔', flag: '🇷🇺', dead: true, record: 'Empoisonné, abattu, jeté dans la Neva : il a fallu insister.' },
    { name: 'Bernard Madoff', emoji: '💸', flag: '🇺🇸', dead: true, convicted: true, record: 'A fait disparaître des dizaines de milliards. Pyramide de Ponzi, 150 ans de prison.' },
    { name: 'Jérôme Kerviel', emoji: '📉', flag: '🇫🇷', convicted: true, record: 'A fait perdre 4,9 milliards à la Société Générale. Trader du mois.' },
    { name: 'Jérôme Cahuzac', emoji: '🧾', flag: '🇫🇷', convicted: true, record: 'Ministre du Budget chargé de traquer la fraude fiscale. Compte caché en Suisse.' },
    { name: 'Bernard Tapie', emoji: '⚽', flag: '🇫🇷', dead: true, convicted: true, record: 'Champion d’Europe avec l’OM, puis prison pour le match truqué VA-OM.' },
    { name: 'Lance Armstrong', emoji: '🚴', flag: '🇺🇸', record: 'Sept Tours de France gagnés, sept Tours de France rendus.' },
    { name: 'Elizabeth Holmes', emoji: '🩸', flag: '🇺🇸', convicted: true, record: 'Promettait des analyses avec une goutte de sang. Il restait surtout la fraude.' },
    { name: 'Sam Bankman-Fried', emoji: '🪙', flag: '🇺🇸', convicted: true, record: 'Prodige de la crypto, a confondu l’argent des clients avec le sien. 25 ans.' },
    { name: 'Martin Shkreli', emoji: '💊', flag: '🇺🇸', convicted: true, record: 'A multiplié par plus de 50 le prix d’un médicament. Condamné pour fraude, pas pour ça.' },
    { name: 'Carlos Ghosn', emoji: '🎸', flag: '🇫🇷', record: 'Ex-patron de Renault, évadé du Japon caché dans une caisse de matériel audio.' },
    { name: 'Jacques Mesrine', emoji: '🥸', flag: '🇫🇷', dead: true, convicted: true, record: 'Ennemi public n° 1, roi de l’évasion et des déguisements.' },
    { name: 'Bonnie Parker', emoji: '💋', flag: '🇺🇸', dead: true, record: 'Braqueuse et poétesse, en cavale avec Clyde jusqu’à la dernière rafale.' },
    { name: 'Clyde Barrow', emoji: '🚗', flag: '🇺🇸', dead: true, convicted: true, record: 'Braquait des banques, mais surtout des stations-service et des épiceries.' },
    { name: 'Barbe Noire', emoji: '🏴‍☠️', flag: '🇬🇧', dead: true, record: 'Pirate qui glissait des mèches allumées dans sa barbe pour faire peur.' },
    { name: 'Néron', wiki: "Néron", emoji: '🔥', flag: '🇮🇹', dead: true, record: 'Accusé d’avoir joué de la lyre pendant que Rome brûlait.' },
    { name: 'Caligula', emoji: '🐎', flag: '🇮🇹', dead: true, record: 'Aurait voulu nommer son cheval consul. Le Sénat a apprécié.' },
    { name: 'Marie-Antoinette', wiki: "Marie-Antoinette d'Autriche", emoji: '🍰', flag: '🇫🇷', dead: true, convicted: true, record: 'N’a jamais parlé de brioche. A quand même perdu la tête.' },
    { name: 'Henri VIII', wiki: "Henri VIII", emoji: '💍', flag: '🇬🇧', dead: true, record: 'Six épouses, dont deux répudiées et deux décapitées. Le mariage, version sport extrême.' },
    { name: 'Vlad l’Empaleur', wiki: "Vlad III l'Empaleur", emoji: '🧛', flag: '🇷🇴', dead: true, record: 'A inspiré Dracula. Le surnom résume sa politique étrangère.' },
    { name: 'Charles Ponzi', emoji: '🔺', flag: '🇮🇹', dead: true, convicted: true, record: 'A donné son nom à l’arnaque. Plus célèbre qu’un prix Nobel.' },
    { name: 'Diego Maradona', emoji: '✋', flag: '🇦🇷', dead: true, record: 'Le but de la « main de Dieu » : tricheur, mais avec talent.' },
    { name: 'Ben Johnson', wiki: "Ben Johnson (athlétisme)", emoji: '🏃', flag: '🇨🇦', record: '9 s 79 à Séoul en 1988, médaille d’or rendue trois jours plus tard.' },
    { name: 'Tonya Harding', emoji: '⛸️', flag: '🇺🇸', convicted: true, record: 'Une rivale frappée au genou, une carrière qui finit à terre.' },
    { name: 'Patrick Balkany', emoji: '🏝️', flag: '🇫🇷', convicted: true, record: 'Fraude fiscale, prison à 72 ans, puis bracelet électronique.' },
    { name: 'Nicolas Sarkozy', emoji: '📿', flag: '🇫🇷', convicted: true, record: 'Premier ancien président de la Ve République à porter le bracelet électronique.' },
    { name: 'Mata Hari', emoji: '💃', flag: '🇳🇱', dead: true, convicted: true, record: 'Danseuse exotique, espionne, fusillée en 1917.' },
    { name: 'Lucky Luciano', emoji: '🍀', flag: '🇮🇹', dead: true, convicted: true, record: 'A organisé le crime en syndicat, avec sa commission, comme une vraie entreprise.' },
    { name: 'Jordan Belfort', emoji: '🐺', flag: '🇺🇸', convicted: true, record: 'Le vrai loup de Wall Street : 22 mois de prison et un film avec DiCaprio.' },
    { name: 'Frank Abagnale', emoji: '✈️', flag: '🇺🇸', convicted: true, record: 'Faux pilote, faux médecin, faux avocat : le vrai « Arrête-moi si tu peux ».' },
    { name: 'Anna Delvey', emoji: '🥂', flag: '🇩🇪', convicted: true, wiki: 'Anna Sorokin', record: 'Fausse héritière, vraies notes d’hôtel impayées à New York.' },
    { name: 'Jacques Chirac', emoji: '🍎', flag: '🇫🇷', dead: true, convicted: true, record: 'Deux ans avec sursis pour les emplois fictifs de la mairie de Paris.' },
    { name: 'Alain Juppé', emoji: '📎', flag: '🇫🇷', convicted: true, record: 'Condamné pour les emplois fictifs du RPR, « droit dans ses bottes ».' },
    { name: 'François Fillon', emoji: '👔', flag: '🇫🇷', convicted: true, record: 'Emplois fictifs pour Penelope, costumes offerts en prime.' },
    { name: 'Richard Nixon', emoji: '📼', flag: '🇺🇸', dead: true, record: 'Watergate, cassettes effacées et « I’m not a crook ». Démission avant destitution.' },
    { name: 'Bill Clinton', emoji: '🎷', flag: '🇺🇸', record: '« Je n’ai pas eu de relations sexuelles avec cette femme. » Spoiler : si.' },
    { name: 'Judas', emoji: '🪙', flag: '🇮🇱', dead: true, wiki: 'Judas Iscariote', record: 'A vendu son meilleur pote pour trente pièces d’argent.' },
    { name: 'Brutus', emoji: '🗡️', flag: '🇮🇹', dead: true, wiki: 'Marcus Junius Brutus', record: '« Toi aussi, mon fils ? » Oui, lui aussi, avec vingt-deux copains.' },
    { name: 'Napoléon', emoji: '🎩', flag: '🇫🇷', dead: true, wiki: 'Napoléon Ier', record: 'A mis l’Europe à feu et à sang. Deux exils, dont un très loin.' },
    { name: 'Robespierre', emoji: '✂️', flag: '🇫🇷', dead: true, wiki: 'Maximilien de Robespierre', record: 'A lancé la Terreur, a fini sous la guillotine qu’il aimait tant.' },
    { name: 'Ravaillac', emoji: '🔪', flag: '🇫🇷', dead: true, convicted: true, wiki: 'François Ravaillac', record: 'A poignardé Henri IV, coincé dans un embouteillage parisien.' },
    { name: 'Cartouche', emoji: '🎯', flag: '🇫🇷', dead: true, convicted: true, wiki: 'Louis Dominique Cartouche', record: 'Chef de bande star du Paris de la Régence, roué en place de Grève.' },
    { name: 'Louis Mandrin', emoji: '🧂', flag: '🇫🇷', dead: true, convicted: true, record: 'Contrebandier adoré, revendait aux paysans ce que le fisc taxait.' },
    { name: 'Rédoine Faïd', emoji: '🚁', flag: '🇫🇷', convicted: true, record: 'S’est évadé de prison en hélicoptère. Zéro discrétion.' },
    { name: 'Marion Jones', wiki: "Marion Jones (athlétisme)", emoji: '🥇', flag: '🇺🇸', convicted: true, record: 'Cinq médailles à Sydney, toutes rendues, et six mois de prison pour mensonge.' },
    { name: 'Luis Suárez', wiki: "Luis Suárez (football, 1987)", emoji: '🦷', flag: '🇺🇾', record: 'Trois adversaires mordus en match. Le seul attaquant qui mord vraiment.' },
    { name: 'Éric Cantona', emoji: '🥋', flag: '🇫🇷', convicted: true, record: 'Coup de pied kung-fu dans un supporter, travaux d’intérêt général.' },
    { name: 'Martha Stewart', emoji: '🧁', flag: '🇺🇸', convicted: true, record: 'Reine des arts ménagers, cinq mois de prison dans une affaire de délit d’initié.' },
    { name: 'Paris Hilton', emoji: '👛', flag: '🇺🇸', convicted: true, record: 'Héritière, quelques semaines de prison en 2007 pour conduite sans permis.' },
    { name: 'Winona Ryder', emoji: '🛍️', flag: '🇺🇸', convicted: true, record: 'Star d’Hollywood, condamnée pour vol à l’étalage chez Saks.' },
    { name: 'Justin Bieber', emoji: '🥚', flag: '🇨🇦', convicted: true, record: 'A bombardé la maison du voisin d’œufs. Condamné pour vandalisme.' },
    { name: 'Kenneth Lay', emoji: '⚡', flag: '🇺🇸', dead: true, convicted: true, record: 'Patron d’Enron, comptabilité créative jusqu’à la faillite.' },
    { name: 'Victor Lustig', emoji: '🗼', flag: '🇨🇿', dead: true, convicted: true, record: 'A vendu la tour Eiffel à un ferrailleur. Elle est toujours là.' },
    { name: 'Billy the Kid', emoji: '🤠', flag: '🇺🇸', dead: true, convicted: true, record: 'Pistolero mort à 21 ans, légende du Far West.' },
    { name: 'Jesse James', emoji: '🚂', flag: '🇺🇸', dead: true, record: 'Braqueur de trains, abattu dans le dos par un de ses hommes.' },
    { name: 'Ned Kelly', emoji: '🛡️', flag: '🇦🇺', dead: true, convicted: true, record: 'Bandit australien en armure de fer bricolée maison.' },
    { name: 'Marquis de Sade', emoji: '⛓️', flag: '🇫🇷', dead: true, convicted: true, wiki: 'Donatien Alphonse François de Sade', record: 'A donné son nom au sadisme, en écrivant surtout depuis sa cellule.' },
    { name: 'Casanova', emoji: '💌', flag: '🇮🇹', dead: true, convicted: true, wiki: 'Giacomo Casanova', record: 'Séducteur en série, évadé des prisons de Venise par le toit.' },
    { name: 'Lucrèce Borgia', emoji: '🍷', flag: '🇮🇹', dead: true, record: 'Réputation d’empoisonneuse, sans doute imméritée. Sa famille, par contre…' },
    { name: 'Catherine de Médicis', emoji: '👑', flag: '🇫🇷', dead: true, record: 'Reine mère au moment de la Saint-Barthélemy. Ambiance mariage raté.' },
  ],
  spicy: [
    { name: 'Oussama Ben Laden', emoji: '🕳️', flag: '🇸🇦', dead: true, record: 'Cherché dix ans dans les grottes, retrouvé dans une villa au Pakistan.' },
    { name: 'Joseph Staline', emoji: '🥶', flag: '🇷🇺', dead: true, record: 'Moustache iconique, goulag XXL, photos retouchées bien avant Photoshop.' },
    { name: 'Saddam Hussein', emoji: '🪤', flag: '🇮🇶', dead: true, convicted: true, record: 'Des palais à la pelle, retrouvé caché dans un trou près d’une ferme.' },
    { name: 'Mouammar Kadhafi', emoji: '⛺', flag: '🇱🇾', dead: true, record: 'A planté sa tente bédouine en plein Paris, à deux pas de l’Élysée.' },
    { name: 'Kim Jong-un', emoji: '🚀', flag: '🇰🇵', record: 'Lance des missiles comme d’autres des feux d’artifice. Coiffeur sous pression.' },
    { name: 'Kim Jong-il', emoji: '⛳', flag: '🇰🇵', dead: true, record: 'Selon la propagande, onze trous en un dès sa première partie de golf.' },
    { name: 'Vladimir Poutine', emoji: '🐻', flag: '🇷🇺', record: 'Torse nu à cheval, mandat d’arrêt de la Cour pénale internationale.' },
    { name: 'Bachar al-Assad', emoji: '👁️', flag: '🇸🇾', record: 'Ophtalmologue de formation, aveugle à tout le reste. Fuite express à Moscou en 2024.' },
    { name: 'Benito Mussolini', emoji: '🚂', flag: '🇮🇹', dead: true, record: 'Les trains arrivaient à l’heure. Lui a fini pendu par les pieds.' },
    { name: 'Francisco Franco', emoji: '🪖', flag: '🇪🇸', dead: true, record: 'Trente-six ans de dictature, mort tranquillement dans son lit.' },
    { name: 'Augusto Pinochet', emoji: '🕶️', flag: '🇨🇱', dead: true, record: 'Coup d’État, disparus par milliers et comptes secrets à l’étranger.' },
    { name: 'Idi Amin Dada', emoji: '🎖️', flag: '🇺🇬', dead: true, record: 'S’était proclamé « dernier roi d’Écosse ». Rien que ça.' },
    { name: 'Pol Pot', emoji: '🌾', flag: '🇰🇭', dead: true, record: 'Ancien professeur, a vidé les villes et fermé toutes les écoles.' },
    { name: 'Nicolae Ceaușescu', emoji: '🏛️', flag: '🇷🇴', dead: true, convicted: true, record: 'Un palais démesuré, un procès express un jour de Noël.' },
    { name: 'Mao Zedong', emoji: '📕', flag: '🇨🇳', dead: true, record: 'Petit Livre rouge et Grand Bond en avant… droit dans le mur.' },
    { name: 'Pablo Escobar', emoji: '🦛', flag: '🇨🇴', dead: true, record: 'Narco le plus riche du monde, zoo d’hippopotames inclus.' },
    { name: 'El Chapo', wiki: "Joaquín Guzmán", emoji: '🚿', flag: '🇲🇽', convicted: true, record: 'Évadé par un tunnel creusé sous sa douche. Perpétuité aux États-Unis.' },
    { name: 'Carlos le Chacal', wiki: "Ilich Ramírez Sánchez", emoji: '🦊', flag: '🇻🇪', convicted: true, record: 'Terroriste vedette des années 70, perpétuité en France.' },
    { name: 'Robert Mugabe', emoji: '👴', flag: '🇿🇼', dead: true, record: 'Encore président à 93 ans, renversé par un coup d’État « en douceur ».' },
    { name: 'Jean-Bedel Bokassa', emoji: '💎', flag: '🇨🇫', dead: true, convicted: true, record: 'Sacré empereur avec une couronne en diamants, en offrait aussi aux amis.' },
    { name: 'Manuel Noriega', emoji: '🔊', flag: '🇵🇦', dead: true, convicted: true, record: 'Délogé par l’armée américaine à coups de hard rock à plein volume.' },
    { name: 'Abou Bakr al-Baghdadi', emoji: '🏴', flag: '🇮🇶', dead: true, record: 'Calife autoproclamé, fin de règne au fond d’un tunnel.' },
    { name: 'Zine el-Abidine Ben Ali', emoji: '✈️', flag: '🇹🇳', dead: true, convicted: true, record: '23 ans au pouvoir, chassé en un mois par le Printemps arabe.' },
    { name: 'Silvio Berlusconi', emoji: '🥂', flag: '🇮🇹', dead: true, convicted: true, record: 'Soirées « bunga-bunga », fraude fiscale et quatre fois chef du gouvernement.' },
    { name: 'Fidel Castro', emoji: '🚬', flag: '🇨🇺', dead: true, record: 'Selon La Havane, plus de 600 tentatives d’assassinat, cigares piégés compris.' },
    { name: 'Che Guevara', emoji: '👕', flag: '🇦🇷', dead: true, record: 'Révolutionnaire devenu motif de t-shirt. Le capitalisme a gagné.' },
    { name: 'Alexandre Loukachenko', emoji: '🥔', flag: '🇧🇾', record: 'Réélu à chaque fois avec plus de 80 % des voix. Quelle surprise.' },
    { name: 'John Gotti', emoji: '🍝', flag: '🇺🇸', dead: true, convicted: true, record: 'Le « parrain en téflon » : rien ne collait… jusqu’à la perpétuité.' },
    { name: 'Totò Riina', emoji: '🍋', flag: '🇮🇹', dead: true, convicted: true, record: 'Le « chef des chefs » de la Mafia, 24 ans de cavale en Sicile.' },
    { name: 'Erich Honecker', emoji: '🧱', flag: '🇩🇪', dead: true, record: 'A gardé un mur debout pour le bien de tous, évidemment.' },
    { name: 'Donald Trump', emoji: '🍊', flag: '🇺🇸', convicted: true, record: 'Premier président américain condamné au pénal, sur 34 chefs d’accusation.' },
    { name: 'Gengis Khan', emoji: '🏹', flag: '🇲🇳', dead: true, record: 'A conquis un empire de Pékin à la mer Caspienne. Des millions de descendants.' },
    { name: 'Attila', emoji: '🐴', flag: '🇭🇺', dead: true, record: 'Là où passait son cheval, l’herbe ne repoussait plus.' },
    { name: 'Ivan le Terrible', emoji: '🦯', flag: '🇷🇺', dead: true, record: 'Aurait tué son propre fils d’un coup de sceptre. Le surnom est mérité.' },
    { name: 'Léopold II', emoji: '🌴', flag: '🇧🇪', dead: true, wiki: 'Léopold II (roi des Belges)', record: 'S’était offert le Congo comme propriété privée. Le pire des proprios.' },
    { name: 'Lavrenti Beria', emoji: '🔎', flag: '🇷🇺', dead: true, convicted: true, record: 'Chef de la police secrète de Staline, fusillé par ses propres camarades.' },
    { name: 'Lénine', emoji: '🪦', flag: '🇷🇺', dead: true, wiki: 'Lénine', record: 'Embaumé depuis 1924, toujours exposé sur la place Rouge.' },
    { name: 'Enver Hoxha', emoji: '🛖', flag: '🇦🇱', dead: true, record: 'A couvert l’Albanie de bunkers par centaines de milliers. Au cas où.' },
    { name: 'Saparmyrat Nyýazow', emoji: '📅', flag: '🇹🇲', dead: true, record: 'A rebaptisé les mois de l’année, dont un à son nom et un au nom de sa mère.' },
    { name: 'Berdimuhamedow', wiki: 'Gurbanguly Berdimuhamedow', emoji: '🏇', flag: '🇹🇲', record: 'Statue en or de lui à cheval, rappeur à ses heures perdues.' },
    { name: 'Kim Il-sung', emoji: '🌟', flag: '🇰🇵', dead: true, record: 'Mort en 1994, toujours « président éternel » de la Corée du Nord.' },
    { name: 'Mobutu Sese Seko', emoji: '🐆', flag: '🇨🇩', dead: true, record: 'Toque en léopard et Concorde affrété pour faire ses courses.' },
    { name: 'Slobodan Milošević', emoji: '🏚️', flag: '🇷🇸', dead: true, record: 'Mort dans sa cellule de La Haye avant la fin de son procès.' },
    { name: 'Radovan Karadžić', emoji: '🧙', flag: '🇧🇦', convicted: true, record: 'Caché des années en guérisseur barbu sous un faux nom. Perpétuité.' },
    { name: 'Ratko Mladić', emoji: '🎖️', flag: '🇷🇸', convicted: true, record: 'Le « boucher des Balkans », condamné à perpétuité à La Haye.' },
    { name: 'Omar el-Béchir', emoji: '📜', flag: '🇸🇩', convicted: true, record: 'Premier chef d’État en exercice visé par un mandat d’arrêt de la CPI.' },
    { name: 'Hissène Habré', emoji: '🏜️', flag: '🇹🇩', dead: true, convicted: true, record: 'Ex-président tchadien, condamné à perpétuité au Sénégal.' },
    { name: 'Joseph Kony', emoji: '🌿', flag: '🇺🇬', record: 'Chef de l’Armée de résistance du Seigneur, recherché par la CPI depuis 2005.' },
    { name: 'Ayman al-Zawahiri', emoji: '🛩️', flag: '🇪🇬', dead: true, record: 'Successeur de Ben Laden, tué par un drone sur son balcon à Kaboul.' },
    { name: 'Khalid Cheikh Mohammed', emoji: '🗽', flag: '🇵🇰', record: 'Cerveau revendiqué du 11-Septembre, détenu à Guantánamo.' },
    { name: 'Hugo Chávez', emoji: '📺', flag: '🇻🇪', dead: true, record: 'Animait son propre talk-show de plusieurs heures chaque dimanche.' },
    { name: 'Nicolás Maduro', emoji: '🐦', flag: '🇻🇪', record: 'Ancien chauffeur de bus, dit avoir reçu la visite de Chávez en petit oiseau.' },
    { name: 'Daniel Ortega', emoji: '🔁', flag: '🇳🇮', record: 'Révolutionnaire devenu ce qu’il combattait, coprésident avec sa femme.' },
    { name: 'Fulgencio Batista', emoji: '🎆', flag: '🇨🇺', dead: true, record: 'A fui Cuba en pleine nuit du réveillon 1958.' },
    { name: 'Rafael Trujillo', emoji: '🏙️', flag: '🇩🇴', dead: true, record: 'Avait rebaptisé la capitale à son nom : Ciudad Trujillo.' },
    { name: 'Papa Doc', emoji: '💀', flag: '🇭🇹', dead: true, wiki: 'François Duvalier', record: 'Médecin devenu dictateur, cultivait son image de baron Samedi.' },
    { name: 'Ferdinand Marcos', emoji: '👞', flag: '🇵🇭', dead: true, record: 'A pillé les Philippines pendant vingt ans. Sa femme a gardé les chaussures.' },
    { name: 'Imelda Marcos', emoji: '👠', flag: '🇵🇭', convicted: true, record: 'Plus de mille paires de chaussures, condamnée pour corruption à 89 ans.' },
    { name: 'Elena Ceaușescu', emoji: '🧪', flag: '🇷🇴', dead: true, convicted: true, record: '« Savante de renommée mondiale » autoproclamée, exécutée avec son mari.' },
    { name: 'Jiang Qing', emoji: '🎎', flag: '🇨🇳', dead: true, convicted: true, record: 'Veuve de Mao et cheffe de la « bande des Quatre ».' },
    { name: 'Philippe Pétain', emoji: '🥖', flag: '🇫🇷', dead: true, convicted: true, record: 'Héros de Verdun puis chef de la collaboration. Condamné à mort, gracié.' },
    { name: 'Pierre Laval', emoji: '📻', flag: '🇫🇷', dead: true, convicted: true, record: 'A souhaité à la radio « la victoire de l’Allemagne ». Fusillé en 1945.' },
    { name: 'Bugsy Siegel', emoji: '🎰', flag: '🇺🇸', dead: true, record: 'Gangster pionnier de Las Vegas, abattu dans son salon.' },
    { name: 'Griselda Blanco', emoji: '❄️', flag: '🇨🇴', dead: true, convicted: true, record: 'La « reine de la cocaïne », pionnière des règlements de comptes à moto.' },
    { name: 'Carlos Lehder', emoji: '🏝️', flag: '🇨🇴', convicted: true, record: 'Cofondateur du cartel de Medellín, avait son île privée aux Bahamas.' },
    { name: 'Bernardo Provenzano', emoji: '📝', flag: '🇮🇹', dead: true, convicted: true, record: '43 ans de cavale, dirigeait la Mafia par petits billets.' },
    { name: 'Hassan Nasrallah', emoji: '🎙️', flag: '🇱🇧', dead: true, record: 'Chef du Hezbollah, trente ans de discours enregistrés depuis des bunkers.' },
    { name: 'Rouhollah Khomeini', emoji: '📖', flag: '🇮🇷', dead: true, record: 'A lancé une fatwa contre un romancier. La critique littéraire version extrême.' },
  ],
  hot: [
    { name: 'Adolf Hitler', emoji: '🎨', flag: '🇩🇪', dead: true, convicted: true, record: 'Recalé deux fois aux Beaux-Arts de Vienne. On aurait dû le prendre.' },
    { name: 'Jeffrey Epstein', emoji: '🏝️', flag: '🇺🇸', dead: true, convicted: true, record: 'Île privée, carnet d’adresses en or et caméras en panne la nuit de sa mort.' },
    { name: 'Ghislaine Maxwell', emoji: '📒', flag: '🇬🇧', convicted: true, record: 'Bras droit d’Epstein, 20 ans de prison pour trafic sexuel de mineures.' },
    { name: 'Harvey Weinstein', emoji: '🎬', flag: '🇺🇸', convicted: true, record: 'Producteur oscarisé, détonateur de #MeToo, condamné pour viol.' },
    { name: 'R. Kelly', emoji: '🕊️', flag: '🇺🇸', convicted: true, record: '« I Believe I Can Fly » : finalement non. 30 ans de prison.' },
    { name: 'Sean « Diddy » Combs', wiki: "Sean Combs", emoji: '🧴', flag: '🇺🇸', convicted: true, record: 'Roi du hip-hop, 50 mois de prison en 2025 pour transport à des fins de prostitution.' },
    { name: 'Charles Manson', emoji: '🪕', flag: '🇺🇸', dead: true, convicted: true, record: 'Musicien raté devenu gourou, a fait tuer par ses disciples.' },
    { name: 'Ted Bundy', emoji: '⚖️', flag: '🇺🇸', dead: true, convicted: true, record: 'Étudiant en droit, s’est défendu lui-même au procès. Très mauvais avocat.' },
    { name: 'Jeffrey Dahmer', emoji: '🧊', flag: '🇺🇸', dead: true, convicted: true, record: 'Le frigo le plus inquiétant de Milwaukee.' },
    { name: 'Anders Breivik', emoji: '🎮', flag: '🇳🇴', convicted: true, record: 'Auteur du massacre d’Utøya, a porté plainte en prison… pour sa console de jeux.' },
    { name: 'Ted Kaczynski', emoji: '📦', flag: '🇺🇸', dead: true, convicted: true, record: 'Génie des maths, cabane au fond des bois, colis piégés par la poste.' },
    { name: 'Henri Désiré Landru', emoji: '💌', flag: '🇫🇷', dead: true, convicted: true, record: 'Petites annonces matrimoniales, fiancées disparues, cuisinière très utilisée.' },
    { name: 'Marcel Petiot', emoji: '🩺', flag: '🇫🇷', dead: true, convicted: true, record: 'Médecin sous l’Occupation, faux passeur vers l’Argentine, vrai tueur en série.' },
    { name: 'Josef Mengele', emoji: '💉', flag: '🇩🇪', dead: true, record: 'L’« ange de la mort » d’Auschwitz, noyé à la plage au Brésil sans jamais être jugé.' },
    { name: 'Heinrich Himmler', emoji: '🐔', flag: '🇩🇪', dead: true, record: 'Éleveur de poulets devenu chef de la SS. Cyanure à l’arrestation.' },
    { name: 'Joseph Goebbels', emoji: '📢', flag: '🇩🇪', dead: true, record: 'Ministre de la Propagande : les fake news avant Internet.' },
    { name: 'Jim Jones', wiki: "Jim Jones (pasteur)", emoji: '🥤', flag: '🇺🇸', dead: true, record: 'Gourou du Temple du Peuple. Le punch qu’il servait, personne n’en a redemandé.' },
    { name: 'Andreï Tchikatilo', emoji: '🌲', flag: '🇷🇺', dead: true, convicted: true, record: 'L’« ogre de Rostov », plus de 50 victimes, fusillé en 1994.' },
    { name: 'Élisabeth Báthory', emoji: '🛁', flag: '🇭🇺', dead: true, record: 'Comtesse soupçonnée de bains de sang de jeunes filles. Routine beauté discutable.' },
    { name: 'O. J. Simpson', emoji: '🧤', flag: '🇺🇸', dead: true, convicted: true, record: 'Acquitté du double meurtre, a écrit « If I Did It », puis prison pour vol à main armée.' },
    { name: 'Oscar Pistorius', emoji: '🚪', flag: '🇿🇦', convicted: true, record: 'Champion paralympique, a tiré à travers la porte des toilettes sur sa compagne.' },
    { name: 'Bertrand Cantat', emoji: '🎤', flag: '🇫🇷', convicted: true, record: 'Chanteur de Noir Désir, condamné pour avoir tué sa compagne, Marie Trintignant.' },
    { name: 'Guy Georges', emoji: '🌃', flag: '🇫🇷', convicted: true, record: 'Le « tueur de l’Est parisien », condamné à perpétuité.' },
    { name: 'Roman Polanski', emoji: '🎥', flag: '🇵🇱', convicted: true, record: 'Oscarisé, en fuite de la justice américaine depuis 1978.' },
    { name: 'Chris Brown', emoji: '👊', flag: '🇺🇸', convicted: true, record: 'Chanteur à succès, condamné pour avoir frappé Rihanna en 2009.' },
    { name: 'Mike Tyson', emoji: '👂', flag: '🇺🇸', convicted: true, record: 'Trois ans de prison pour viol, puis a mordu l’oreille d’Holyfield.' },
    { name: 'Phil Spector', emoji: '🎚️', flag: '🇺🇸', dead: true, convicted: true, record: 'Génie du « Wall of Sound », mort en prison pour meurtre.' },
    { name: 'Lizzie Borden', emoji: '🪓', flag: '🇺🇸', dead: true, record: 'Acquittée, mais la comptine lui compte quarante coups de hache.' },
    { name: 'Aileen Wuornos', emoji: '🛣️', flag: '🇺🇸', dead: true, convicted: true, record: 'Tueuse en série des autoroutes de Floride, exécutée en 2002.' },
    { name: 'Adolf Eichmann', emoji: '🗃️', flag: '🇩🇪', dead: true, convicted: true, record: 'Bureaucrate de la Shoah, retrouvé en Argentine, pendu en Israël.' },
    { name: 'Hermann Göring', emoji: '🖼️', flag: '🇩🇪', dead: true, convicted: true, record: 'Collectionneur d’œuvres volées, cyanure la veille de sa pendaison.' },
    { name: 'Klaus Barbie', emoji: '🦂', flag: '🇩🇪', dead: true, convicted: true, record: 'Le « boucher de Lyon », rattrapé en Bolivie, mort en prison.' },
    { name: 'Reinhard Heydrich', emoji: '🚘', flag: '🇩🇪', dead: true, record: 'Architecte de la « solution finale », abattu à Prague par la Résistance.' },
    { name: 'Rudolf Hess', emoji: '🪂', flag: '🇩🇪', dead: true, convicted: true, record: 'S’est envolé seul vers l’Écosse en 1941 pour négocier la paix. Raté.' },
    { name: 'Eva Braun', emoji: '💒', flag: '🇩🇪', dead: true, record: 'Mariée à Hitler moins de deux jours avant leur suicide. Lune de miel au bunker.' },
    { name: 'John Wayne Gacy', emoji: '🤡', flag: '🇺🇸', dead: true, convicted: true, record: 'Clown d’anniversaire le week-end, 33 meurtres sous le plancher.' },
    { name: 'Richard Ramirez', emoji: '🌙', flag: '🇺🇸', dead: true, convicted: true, record: 'Le « Night Stalker » de Los Angeles, fan déclaré de Satan.' },
    { name: 'David Berkowitz', emoji: '🐕', flag: '🇺🇸', convicted: true, record: 'Le « fils de Sam » disait obéir au chien du voisin.' },
    { name: 'Ed Gein', emoji: '🪚', flag: '🇺🇸', dead: true, convicted: true, record: 'A inspiré Psychose et Massacre à la tronçonneuse. Déco très personnelle.' },
    { name: 'Harold Shipman', emoji: '💊', flag: '🇬🇧', dead: true, convicted: true, record: 'Médecin de famille, des centaines de patients tués. Pire généraliste du monde.' },
    { name: 'Gary Ridgway', emoji: '🏞️', flag: '🇺🇸', convicted: true, record: 'Le « tueur de la Green River », 49 meurtres reconnus.' },
    { name: 'Dennis Rader', emoji: '💾', flag: '🇺🇸', convicted: true, record: 'BTK, piégé par une disquette qu’il a lui-même envoyée à la police.' },
    { name: 'Charles Sobhraj', emoji: '🐍', flag: '🇫🇷', convicted: true, record: 'Le « Serpent », tueur de routards en Asie, libéré au Népal en 2022.' },
    { name: 'Andrew Cunanan', emoji: '🕶️', flag: '🇺🇸', dead: true, record: 'A tué Gianni Versace devant sa villa de Miami.' },
    { name: 'Mark David Chapman', emoji: '📗', flag: '🇺🇸', convicted: true, record: 'A tué John Lennon, puis s’est assis pour lire L’Attrape-cœurs.' },
    { name: 'Lee Harvey Oswald', emoji: '🔭', flag: '🇺🇸', dead: true, record: 'A tué Kennedy, abattu deux jours plus tard en direct à la télé.' },
    { name: 'John Wilkes Booth', emoji: '🎭', flag: '🇺🇸', dead: true, record: 'Acteur, a tué Lincoln au théâtre, en pleine représentation.' },
    { name: 'Gavrilo Princip', emoji: '🔫', flag: '🇷🇸', dead: true, convicted: true, record: 'Deux balles à Sarajevo, une guerre mondiale.' },
    { name: 'Timothy McVeigh', emoji: '🚚', flag: '🇺🇸', dead: true, convicted: true, record: 'Camion piégé à Oklahoma City, exécuté en 2001.' },
    { name: 'Mehmet Ali Ağca', emoji: '⛪', flag: '🇹🇷', convicted: true, record: 'A tiré sur Jean-Paul II, qui est venu lui pardonner en prison.' },
    { name: 'Ilse Koch', emoji: '🏮', flag: '🇩🇪', dead: true, convicted: true, record: 'Épouse du commandant de Buchenwald, condamnée à perpétuité.' },
    { name: 'Irma Grese', emoji: '🥾', flag: '🇩🇪', dead: true, convicted: true, record: 'Gardienne SS à 19 ans, pendue à 22.' },
    { name: 'Marie Besnard', emoji: '🫖', flag: '🇫🇷', dead: true, record: 'La « bonne dame de Loudun », accusée d’empoisonnements, acquittée.' },
    { name: 'Violette Nozière', emoji: '🧪', flag: '🇫🇷', dead: true, convicted: true, record: 'A empoisonné ses parents à 18 ans, condamnée puis réhabilitée.' },
    { name: 'David Koresh', emoji: '🔥', flag: '🇺🇸', dead: true, record: 'Gourou de Waco, 51 jours de siège face au FBI.' },
    { name: 'Keith Raniere', emoji: '🔥', flag: '🇺🇸', convicted: true, record: 'Gourou de NXIVM, marquait ses adeptes au fer. 120 ans de prison.' },
    { name: 'H. H. Holmes', emoji: '🏨', flag: '🇺🇸', dead: true, convicted: true, record: 'Tueur en série, son hôtel de Chicago est devenu le « château du meurtre ».' },
    { name: 'Ernst Röhm', emoji: '🔪', flag: '🇩🇪', dead: true, convicted: true, record: 'Chef des SA, liquidé par Hitler lui-même lors de la Nuit des longs couteaux.' },
    { name: 'Robert Durst', emoji: '🎙️', flag: '🇺🇸', dead: true, convicted: true, record: 'Héritier new-yorkais, s’est trahi au micro d’un documentaire resté allumé.' },
    { name: 'Albert DeSalvo', emoji: '🧣', flag: '🇺🇸', dead: true, convicted: true, record: 'S’est accusé d’être l’« étrangleur de Boston », mort poignardé en prison.' },
    { name: 'Ulrike Meinhof', emoji: '📰', flag: '🇩🇪', dead: true, convicted: true, record: 'Journaliste vedette devenue terroriste de la Fraction armée rouge.' },
  ],
}
