import type { Level } from '../engine'

/** Mimes — à faire deviner sans un mot. */
export const mimes: Record<Level, string[]> = {
  soft: [
    // Actions du quotidien
    'Se brosser les dents',
    'Prendre une douche',
    'Se coiffer',
    'Se maquiller',
    'Se raser',
    'Se couper les ongles',
    'Mettre ses lunettes',
    'Nouer sa cravate',
    'Lacer ses chaussures',
    'Enfiler un pull trop petit',
    'Chercher ses clés',
    'Faire la vaisselle',
    'Passer l’aspirateur',
    'Laver les vitres',
    'Étendre le linge',
    'Repasser une chemise',
    'Faire son lit',
    'Mettre la table',
    'Coudre un bouton',
    'Tricoter un pull',
    'Taper sur un clavier',
    'Téléphoner',
    'Prendre un selfie',
    'Ouvrir un parapluie',
    'Tourner une clé dans une serrure',
    'Déboucher un évier',
    'Boire avec une paille',
    'Manger des spaghettis',
    'Manger une glace qui fond',
    'Croquer dans une pomme',
    // Cuisine
    'Retourner une crêpe',
    'Éplucher des pommes de terre',
    'Couper des oignons',
    'Casser un œuf',
    'Pétrir la pâte',
    'Faire un gâteau',
    'Faire griller des chamallows',
    'Servir la soupe',
    'Mélanger une salade',
    'Ouvrir une boîte de conserve',
    // Bricolage et jardin
    'Tondre la pelouse',
    'Planter un arbre',
    'Arroser les plantes',
    'Cueillir des pommes',
    'Planter un clou',
    'Scier une planche',
    'Percer un mur',
    'Peindre un mur',
    'Changer une ampoule',
    'Monter un meuble',
    'Planter une tente',
    'Faire un feu de camp',
    'Utiliser une tronçonneuse',
    'Ramasser les feuilles mortes',
    // Sports et loisirs
    'Faire du ski',
    'Faire du surf',
    'Nager le crawl',
    'Jouer au tennis',
    'Jouer au golf',
    'Jouer au bowling',
    'Faire du vélo',
    'Faire du cheval',
    'Pêcher à la ligne',
    'Faire du patin à glace',
    'Faire de la plongée',
    'Faire du yoga',
    'Faire de la boxe',
    'Tirer à l’arc',
    'Escalader un mur',
    'Faire du kayak',
    'Ramer en barque',
    'Faire du trampoline',
    'Sauter à la corde',
    'Faire du hula hoop',
    'Jongler avec trois balles',
    'Lancer un boomerang',
    'Jouer aux échecs',
    'Faire un puzzle',
    'Faire du skateboard',
    'Faire de la trottinette',
    'Faire du roller',
    'Faire du stop',
    // Musique
    'Jouer du violon',
    'Jouer de la guitare',
    'Jouer de la batterie',
    'Jouer du piano',
    'Jouer de la trompette',
    'Chanter à l’opéra',
    'Diriger un orchestre',
    'Jouer de la flûte',
    'Danser le tango',
    'Danser le rock',
    // Transports
    'Conduire une voiture',
    'Changer une roue',
    'Pousser une voiture en panne',
    'Piloter un avion',
    'Conduire un camion',
    'Prendre le métro bondé',
    // Métiers
    'Dentiste',
    'Pompier',
    'Facteur',
    'Boulanger',
    'Coiffeur',
    'Chef d’orchestre',
    'Policier',
    'Astronaute',
    'Plombier',
    'Photographe',
    'Pêcheur',
    'Serveur',
    'Médecin',
    'Infirmière',
    'Chirurgien',
    'Peintre',
    'Sculpteur',
    'Magicien',
    'Clown',
    'Funambule',
    'Dompteur de lions',
    'Jardinier',
    'Bûcheron',
    'Apiculteur',
    'Boucher',
    'Maçon',
    'Éboueur',
    'Pilote de course',
    'Arbitre de football',
    'Contrôleur de train',
    'Professeur',
    'Danseuse classique',
    'Cowboy',
    'Pirate',
    'Chevalier',
    'Roi',
    'Sorcière',
    'Vétérinaire',
    'Mécanicien',
    'Vendeur de glaces',
    'Marin',
    'Cuisinier',
    'Mime',
    // Animaux
    'Un kangourou',
    'Un éléphant',
    'Un singe',
    'Une girafe',
    'Un pingouin',
    'Un serpent',
    'Une grenouille',
    'Un lapin',
    'Un crabe',
    'Un chat qui fait sa toilette',
    'Un chien qui se secoue',
    'Un oiseau qui s’envole',
    'Un cheval au galop',
    'Une araignée',
    'Un requin',
    'Un ours',
    'Un paresseux',
    'Un gorille',
    'Un flamant rose',
    'Un escargot',
    'Une poule',
    'Un coq',
    'Un canard',
    'Un dauphin',
    'Un lion qui rugit',
    'Une chauve-souris',
    'Un dinosaure',
    'Une tortue',
    'Un papillon',
    'Une vache',
    // Situations
    'Rater son bus',
    'Courir sous la pluie',
    'Glisser sur une peau de banane',
    'Avoir très froid',
    'Avoir très chaud',
    'Éternuer',
    'Bâiller',
    'Avoir le hoquet',
    'Se faire piquer par une guêpe',
    'Marcher dans une flaque',
    'Marcher dans du chewing-gum',
    'Être coincé dans l’ascenseur',
    'Se perdre en forêt',
    'Faire la queue',
    'Trouver un trésor',
    'Gagner au loto',
    'Se réveiller en retard',
    'Marcher sur la Lune',
    'Traverser un désert',
    'Marcher dans la neige',
    'Respirer sous l’eau',
    'Voler comme un oiseau',
    'Attendre un train',
    // Films et contes
    'Le Petit Chaperon rouge',
    'Cendrillon',
    'Blanche-Neige',
    'Pinocchio',
    'Le Roi Lion',
    'Titanic',
    'La Reine des neiges',
    'Harry Potter',
    'Spider-Man',
    'Batman',
    'Superman',
    'Les Trois Petits Cochons',
    'Le Chat botté',
    'Aladdin',
    'La Belle au bois dormant',
    'Peter Pan',
    'Indiana Jones',
    'Jurassic Park',
    'King Kong',
    'Shrek',
    'Raiponce',
    'Mary Poppins',
    'Les Dents de la mer',
    'Tarzan',
    'Robin des Bois',
    'Alice au pays des merveilles',
    'Le Livre de la jungle',
    'Le Monde de Nemo',
    // Sports
    'Le basket',
    'Le rugby',
    'Le handball',
    'Le judo',
    'L’escrime',
    'Le ping-pong',
    'Le badminton',
    'Le volley',
    'Le curling',
    'Le saut à la perche',
    'Le lancer de poids',
    'Le saut en longueur',
    'Le marathon',
    'Le water-polo',
    'La natation synchronisée',
    'Le hockey sur glace',
    'Le baseball',
    'Le sumo',
    'Le bobsleigh',
    'Le saut à ski',
    'Le parapente',
    'L’haltérophilie',
    'La course de haies',
    'Le lancer de javelot',
    // Émotions
    'Être surpris',
    'Avoir peur',
    'Être très en colère',
    'Être jaloux',
    'Être fier',
    'Être épuisé',
    'Avoir honte',
    'Pleurer de joie',
    'Être dégoûté',
    'Être impatient',
    'S’ennuyer',
    'Être timide',
  ],

  spicy: [
    // Alcool et soirée
    'Trinquer',
    'Faire cul sec',
    'Servir un cocktail',
    'Secouer un shaker',
    'Déboucher du champagne',
    'Boire à la bouteille',
    'Jouer au beer-pong',
    'Commander un dernier verre',
    'Siroter un vin chaud',
    'Verser une pinte',
    'Faire un shot de tequila',
    'Faire tourner son vin dans le verre',
    'Boire un verre de trop',
    'Faire un toast raté',
    'Danser sur une table',
    'Chanter faux au karaoké',
    'Faire la conga',
    'Danser la Macarena',
    'Faire la danse du canard',
    'Faire le DJ complètement saoul',
    'Fumer une cigarette sur le balcon',
    'Fumer la chicha',
    'Faire la queue devant la boîte de nuit',
    'Se faire refuser à l’entrée',
    'Faire la queue au vestiaire',
    'Perdre son téléphone en soirée',
    'Retrouver son manteau sous un tas',
    'Rentrer à pied à 5 h du matin',
    'Marcher en zigzag',
    'Tenir debout après dix verres',
    'Parler la bouche pâteuse',
    'Jouer à action ou vérité',
    'Jouer à la bouteille',
    'Faire un discours bourré',
    'Faire du karaoké en duo',
    'Manquer de s’endormir en soirée',
    'S’endormir sur le canapé de l’hôte',
    // Lendemain de fête
    'Se réveiller avec la gueule de bois',
    'Chercher de l’eau à 4 h du matin',
    'Vomir dans les toilettes',
    'Avoir mal au crâne',
    'Prendre un cachet d’aspirine',
    'Se cacher du soleil',
    'Ne plus se souvenir de la soirée',
    'Retrouver un cône sur sa tête',
    'Découvrir des photos honteuses',
    'Commander un burger à 3 h du matin',
    'Manger un kebab à la sortie du bar',
    'Dormir tout habillé',
    'Se réveiller dans la baignoire',
    'Lire ses messages de la veille',
    'Regretter un message envoyé',
    // Drague
    'Draguer au bar',
    'Lancer une phrase d’accroche ratée',
    'Faire un clin d’œil',
    'Envoyer un baiser',
    'Offrir un verre à un inconnu',
    'Demander un numéro de téléphone',
    'Se prendre un râteau',
    'Faire un compliment gênant',
    'Faire le beau',
    'Jouer les séducteurs',
    'Séduire en dansant',
    'Faire un slow',
    'Danser collé-serré',
    'Faire les yeux de biche',
    'Se recoiffer devant son crush',
    'Rougir devant son crush',
    'Stalker un profil',
    'Liker une vieille photo par erreur',
    'Swiper sur une appli de rencontres',
    'Matcher avec son ex',
    'Faire un date raté',
    'Arriver en retard au rendez-vous',
    'Poser un lapin',
    'Se faire poser un lapin',
    'Découvrir que son date ne ressemble pas aux photos',
    'Payer l’addition au premier rendez-vous',
    'Se disputer pour l’addition',
    'Oublier le prénom de son rencard',
    'Tomber sur son ex au restaurant',
    'Faire semblant de rire à une blague nulle',
    'Se cacher derrière la carte du restaurant',
    'Ne pas savoir quoi dire au premier rendez-vous',
    'Faire un bisou sur la joue qui rate',
    'Se tromper entre une bise et une poignée de main',
    'Réciter un poème à son crush',
    'Chanter sous le balcon',
    'Offrir un bouquet de fleurs',
    'Offrir un ours en peluche',
    'Apporter des chocolats',
    'Attendre une réponse à son SMS',
    'Relire dix fois son message avant de l’envoyer',
    'Regarder son téléphone toutes les trois secondes',
    'Se faire ghoster',
    'Se retourner sur un beau gosse',
    'S’éventer devant quelqu’un de beau',
    // Couple
    'Se disputer pour la télécommande',
    'Dormir dos à dos',
    'Voler la couette',
    'Ronfler à côté de son conjoint',
    'Oublier l’anniversaire de sa moitié',
    'Faire une scène de jalousie',
    'Bouder en disant « j’ai rien »',
    'Choisir le film du soir',
    'Faire la paix après une dispute',
    'Faire sa demande en mariage',
    'Dire oui devant le maire',
    'Lancer le bouquet de la mariée',
    'Ouvrir le bal en tant que mariés',
    'Rencontrer les beaux-parents',
    'Se faire larguer par SMS',
    'Rompre dans un café',
    'Pleurer devant une comédie romantique',
    'Jeter les affaires de son ex',
    'Brûler les photos de son ex',
    'Espionner son ex sur les réseaux',
    'Emménager ensemble',
    'Se disputer à cause du GPS',
    'Monter un meuble en couple',
    'Se disputer pour le thermostat',
    'Rapporter les clés à son ex',
    'Manger un pot de glace après une rupture',
    'Rejouer la scène de rupture d’un film',
    'Remettre son alliance',
    'Enlever son alliance',
    'Se réconcilier sur l’oreiller',
    'Demander une pause dans le couple',
    'Faire un câlin de réconciliation',
    'Dire « je t’aime » pour la première fois',
    'Découvrir un message suspect sur un téléphone',
    'Cacher son téléphone à son conjoint',
    'Se faire demander « tu penses à quoi ? »',
    // Gênes sociales
    'Faire un rot en public',
    'Lâcher un pet discret',
    'Se faire prendre en train de mentir',
    'Oublier le nom d’un invité',
    'Renverser son verre sur quelqu’un',
    'Tomber en talons',
    'Déchirer son pantalon',
    'Croiser son patron en boîte',
    'Croiser son ex en soirée',
    'Avoir sa braguette ouverte',
    'Avoir du persil dans les dents',
    'Parler la bouche pleine',
    'Envoyer un vocal gênant',
    'Raconter une blague nulle',
    'Danser comme un robot',
    'Se faire surprendre en train de chanter sous la douche',
    'Se tromper de groupe WhatsApp',
    'Répondre « à toi aussi » à un serveur',
    'Saluer quelqu’un qui ne nous salue pas',
    'Tomber sur un faux numéro',
    'Faire la bise à la mauvaise personne',
    'Faire semblant de dormir devant un importun',
    'Faire semblant de téléphoner pour éviter quelqu’un',
    'Se cacher derrière un pot de fleurs',
    'Se prendre une porte vitrée',
    'Éclater de rire à un enterrement',
    'Avoir un fou rire en réunion',
    'Se faire griller en train de zoner au bureau',
    'S’endormir à une réunion',
    'Découvrir qu’on a pris le mauvais manteau',
    'Se faire apostropher par un videur',
    'Rentrer en taxi sans son portefeuille',
    'Faire un selfie raté avec le flash',
    'Pousser la chansonnette dans un bar à karaoké',
    'Enchaîner les verres de sangria',
    'Perdre un pari et payer sa tournée',
    'Pleurer sur l’épaule d’un inconnu au bar',
    'Faire une déclaration d’amour à un ami complètement saoul',
    'Tomber de sa chaise après quelques verres',
    'Se faire servir un café à la place d’un cocktail',
    'Se tromper de cadeau pour l’anniversaire de son crush',
    'Danser le slow avec le mauvais cavalier',
    'Faire la cuisine pour impressionner son rencard',
  ],

  hot: [
    // Regards et séduction
    'Lancer un regard de braise',
    'Faire les yeux doux',
    'Murmurer à l’oreille',
    'Souffler dans le cou',
    'Passer sa main dans ses cheveux',
    'Se mordre la lèvre',
    'Faire un clin d’œil appuyé',
    'Faire du charme à un serveur',
    'Faire du charme à son voisin',
    'Allumer quelqu’un du regard',
    'Faire du pied sous la table',
    'Faire le paon devant son crush',
    'Avoir des papillons dans le ventre',
    'Avoir des bouffées de chaleur',
    'Être hypnotisé par un beau gosse',
    'Se retourner sur un beau maître-nageur',
    'Frôler quelqu’un dans un couloir étroit',
    'Rester coincé dans un placard avec son crush',
    'Retenir son souffle près de son crush',
    'Jouer avec son collier en séduisant',
    'Rouler des hanches en marchant',
    'Faire un compliment très coquin',
    'Proposer un dernier verre chez soi',
    'Chuchoter un secret coquin',
    // Danse sensuelle
    'Danser de façon très sensuelle',
    'Se déhancher sur la piste',
    'Danser autour d’une barre',
    'Faire du pole dance',
    'Danser le tango torride',
    'Danser la salsa collée-serrée',
    'Danser la bachata',
    'Danser le zouk',
    'Faire un slow langoureux',
    'Faire une danse du ventre',
    'Danser le flamenco passionné',
    'Danser le French cancan',
    'Faire un numéro de cabaret',
    'Danser avec une écharpe en soie',
    'Danser comme dans Dirty Dancing',
    'Danser langoureusement sous la lune',
    'Chanter sensuellement au micro',
    'Faire un défilé de lingerie',
    'Défiler sur un podium en talons',
    // Déshabillage et tenues
    'Faire un strip-tease',
    'Enlever lentement sa chemise',
    'Enlever lentement ses gants',
    'Retirer ses bas',
    'Déboutonner sa chemise',
    'Défaire sa cravate lentement',
    'Enlever sa ceinture',
    'Dégrafer sa robe',
    'Défaire un soutien-gorge',
    'Se déshabiller dans le noir',
    'Enfiler des bas résille',
    'Essayer de la lingerie en cabine',
    'Enfiler des talons hauts',
    'Enfiler un peignoir en soie',
    'Se promener en peignoir',
    'Sortir de la douche en serviette',
    'Laisser tomber sa serviette de bain',
    'Mettre du rouge à lèvres',
    'Laisser une trace de rouge à lèvres',
    'Mettre du parfum sur sa nuque',
    'Sortir en petite robe noire',
    'S’habiller sexy pour sortir',
    'Poser pour un peintre',
    'Poser en pin-up',
    'Poser pour un calendrier de pompiers',
    'Faire un shooting boudoir',
    'Se faire prendre en photo en maillot',
    'Jouer au strip-poker',
    // Baisers
    'Donner un premier baiser',
    'Embrasser langoureusement',
    'Faire un baiser fougueux',
    'Voler un baiser',
    'Faire un baiser dans le cou',
    'Embrasser sa main en la tenant',
    'Faire un bisou esquimau',
    'Rejouer le baiser à l’envers de Spider-Man',
    'S’embrasser sous la pluie',
    'S’embrasser sous le gui',
    'S’embrasser dans l’ascenseur',
    'S’embrasser sur la plage',
    'Se bécoter sur un banc',
    'Se bécoter au cinéma',
    'Se faire un suçon',
    'Cacher un suçon avec un foulard',
    'Rejouer la scène de poterie de Ghost',
    'Rejouer une scène de baiser sous la pluie',
    'Se faire embrasser à l’improviste',
    'Rater un baiser et se cogner le nez',
    'Retenir un baiser par timidité',
    'Souffler un baiser du bout des doigts',
    // Massage et bain
    'Faire un massage sensuel',
    'Masser le dos de quelqu’un à l’huile',
    'Mettre de la crème solaire dans le dos de quelqu’un',
    'Faire un massage à la bougie',
    'Se faire masser avec des pierres chaudes',
    'Masser les pieds de quelqu’un',
    'Se faire masser les épaules',
    'Faire un massage du cuir chevelu',
    'Prendre un bain à deux',
    'Prendre une douche à deux',
    'Se savonner sensuellement',
    'Se faire couler un bain moussant',
    'Boire du champagne dans le bain',
    'Prendre un bain de minuit',
    'Se faire peindre le dos',
    // Gourmandise suggestive
    'Manger une fraise sensuellement',
    'Lécher une glace de façon suggestive',
    'Manger une banane de façon suggestive',
    'Lécher la crème d’un éclair avec un air coquin',
    'Boire du champagne dans une flûte en regardant quelqu’un',
    'Déguster un chocolat fondant avec plaisir',
    'Faire couler du miel sur ses doigts',
    'Nourrir quelqu’un du bout des doigts',
    'Partager un spaghetti comme dans La Belle et le Clochard',
    // Soirée romantique
    'Dîner aux chandelles',
    'Allumer des bougies parfumées',
    'Préparer une soirée romantique',
    'Mettre une musique romantique',
    'Offrir une rose entre ses dents',
    'Offrir un bouquet de roses',
    'Porter quelqu’un dans ses bras',
    'Porter sa mariée',
    'Proposer un week-end romantique',
    'Se tenir la main sous la table',
    'Compter les étoiles en amoureux',
    'Se glisser sous la couette',
    'Se coucher sur le lit en pose sexy',
    'Faire un câlin très long',
    'Se faire des câlins sur le canapé',
    'Se réveiller dans les bras de quelqu’un',
    'Regarder un film coquin avec des amis par erreur',
    'Écrire un message coquin',
    'Envoyer un SMS coquin',
    'Recevoir un message coquin en réunion',
    'Se faire bander les yeux',
    // Jeux de rôle et déguisements
    'Se déguiser en infirmière sexy',
    'Se déguiser en policière sexy',
    'Se déguiser en diable séducteur',
    'Se déguiser en ange coquin',
    'Se déguiser en chat sexy',
    'Se déguiser en lapine sexy',
    'Jouer la secrétaire sexy',
    'Jouer la prof sexy',
    'Jouer le pompier sexy',
    'Jouer le plombier sexy',
    'Jouer le pirate séducteur',
    'Jouer le cowboy séducteur',
    'Jouer la sirène séductrice',
    'Jouer le vampire séducteur',
    'Jouer la femme fatale',
    'Jouer le play-boy',
    'Jouer le Casanova',
    'Jouer la vamp',
    'Imiter un James Bond séducteur',
    'Rejouer une scène à la Basic Instinct',
    'Jouer un agent secret séducteur',
    'Jouer à cache-cache amoureux',
    // Surprises et lendemains
    'Se faire surprendre en pleins bisous',
    'Se faire surprendre par son colocataire',
    'Se faire surprendre par ses voisins',
    'Cacher son amant dans le placard',
    'Entendre les voisins à travers le mur',
    'Se réveiller à côté d’un inconnu',
    'Faire la marche de la honte le matin',
    'Se rhabiller en cachette',
    'Sortir à pas de loup au petit matin',
    'Chercher ses chaussettes en silence',
    'Se rhabiller à toute vitesse',
    'Se faire griller en sortant de chez quelqu’un',
    'Prendre un air innocent après un baiser',
    'Réajuster ses vêtements en sortant d’un placard',
    'Se lisser les cheveux après une folle nuit',
    'Dormir avec le maquillage de la veille',
  ],
}
