import type { Level } from '../engine'

/** « Je n'ai jamais… » — chaque entrée complète la phrase. */
export const neverHaveI: Record<Level, string[]> = {
  soft: [
    'mangé un plat tombé par terre',
    'fait semblant de connaître une chanson en soirée',
    'oublié le prénom de quelqu’un juste après les présentations',
    'parlé tout seul dans la rue',
    'pleuré devant un dessin animé',
    'raté un train ou un avion',
    'menti sur mon âge',
    'stalké l’ex de quelqu’un sur les réseaux',
    'fait une sieste de plus de trois heures',
    'envoyé un message à la mauvaise personne',
    'chanté sous la douche à pleine voix',
    'acheté un truc inutile à 3 h du matin',
    'fait semblant d’être malade pour éviter quelqu’un',
    'mangé un pot de glace entier d’un coup',
    'regardé une série entière en un week-end',
    'eu peur du noir après un film d’horreur',
    'été viré d’un cours',
    'liké une vieille photo par accident',
    'fait un selfie avec un inconnu',
    'perdu mes clés plus de trois fois dans le même mois',
    'dormi dans un endroit public',
    'eu un fou rire à un moment où il ne fallait surtout pas',
    'raconté une blague que personne n’a comprise',
    'appelé un prof « maman » ou « papa »',
    'mangé quelque chose de périmé sans le savoir',
    'fait un vœu sur une étoile filante',
    'menti dans une partie de Je n’ai jamais',
    'tenté une recette vue sur TikTok',
    // Enfance
    'caché un légume sous la table pour ne pas le manger',
    'cassé quelque chose et accusé le chat ou le chien',
    'dormi avec un doudou après mes dix ans',
    'cru au père Noël bien plus longtemps que je ne veux l’avouer',
    'triché à un jeu de société',
    'laissé un frère ou une sœur se faire punir à ma place',
    'eu un ami imaginaire',
    'mangé de la pâte à gâteau crue',
    'sauté dans une flaque d’eau exprès',
    'fait du vélo sans les mains et fini par tomber',
    'construit une cabane dans le salon',
    'fait semblant de dormir pour qu’on me porte jusqu’au lit',
    'collé un chewing-gum sous une table',
    'été oublié par les autres pendant une partie de cache-cache',
    'dessiné sur un mur de la maison',
    'mangé des bonbons en cachette avant le repas',
    'cru qu’un monstre vivait sous mon lit',
    'écrit sur ma main pour ne pas oublier quelque chose',
    // École
    'copié sur mon voisin ou ma voisine pendant un contrôle',
    'prétendu que le chien avait mangé mon devoir',
    'dormi en plein cours',
    'raté un examen parce que j’avais mal lu l’énoncé',
    'fait un exposé sans l’avoir préparé',
    'passé une nuit blanche à réviser',
    'imité la signature de mes parents',
    'appris une leçon par cœur sans rien y comprendre',
    'séché un cours',
    'passé une nuit entière sur un devoir à rendre le lendemain',
    // Travail
    'fait semblant de travailler quand mon chef passait',
    'été en retard à un entretien d’embauche',
    'menti sur mon CV',
    'oublié de couper mon micro en visio',
    'gardé un pyjama sous ma chemise en visio',
    'dormi pendant une réunion',
    'pleuré au travail',
    'prétendu que ma connexion coupait pendant une visio',
    'rédigé un mail de démission que je n’ai jamais envoyé',
    'écrit « je vous appelle » dans un mail sans jamais appeler',
    'mangé le déjeuner de quelqu’un d’autre au frigo du bureau',
    'imprimé quelque chose de personnel au travail',
    'fait semblant de comprendre un mot compliqué en réunion',
    // Voyages et transports
    'raté ma sortie sur l’autoroute et fait trois demi-tours',
    'dormi dans un aéroport',
    'pris le mauvais train',
    'voyagé dans un pays sans parler un mot de la langue',
    'perdu ma valise',
    'oublié mon passeport ou ma carte d’identité avant de partir',
    'ramené un souvenir hideux de vacances',
    'squatté la place de quelqu’un dans le train',
    'fait du stop',
    'dormi dans une tente sous la pluie',
    'passé une nuit à la belle étoile',
    'été perdu dans une ville inconnue sans batterie',
    'trouvé un billet par terre',
    'couru derrière un bus qui est parti quand même',
    'fait semblant de dormir dans le métro pour ne pas céder ma place',
    'pris une photo de moi dans une pose ridicule devant un monument',
    'dormi jusqu’au terminus d’un trajet',
    // Famille
    'appelé mes parents pour une question de cuisine toute bête',
    'offert deux fois le même cadeau à la même personne',
    'fait semblant d’aimer un cadeau',
    'redonné un cadeau reçu',
    'oublié l’anniversaire d’un proche',
    'gardé un secret de famille pendant des années',
    'chanté au karaoké avec ma famille',
    'piqué un pull à un proche sans jamais le rendre',
    'appelé ma grand-mère pour qu’elle me donne une recette',
    // Technologie
    'laissé tomber mon téléphone sur mon visage en étant allongé',
    'tapé un mot de passe vingt fois de suite',
    'cherché mon téléphone alors que je l’avais à la main',
    'laissé un message « vu » sans répondre pendant des jours',
    'envoyé un vocal de plus de cinq minutes',
    'continué à utiliser un téléphone à l’écran cassé',
    'cherché mes symptômes sur internet et paniqué',
    'créé une playlist pour un moment précis',
    'tapé mon propre nom sur un moteur de recherche',
    'enregistré une vidéo TikTok que je n’ai jamais postée',
    'payé un abonnement oublié pendant des mois',
    'parlé à un assistant vocal comme à un ami',
    'joué à un jeu vidéo toute la nuit',
    'pris une photo avec un filtre ridicule',
    // Nourriture
    'mangé des céréales au dîner',
    'mangé des pâtes tous les jours pendant une semaine',
    'mangé des chips en guise de repas',
    'raté une recette pourtant très simple',
    'mis du sel à la place du sucre',
    'goûté un plat sans savoir ce que c’était',
    'mangé seul au restaurant',
    'léché mon assiette',
    'grignoté le contenu du frigo à minuit',
    'caché des gâteaux pour ne pas les partager',
    'piqué des frites dans l’assiette de quelqu’un',
    'commandé le même plat à chaque fois dans un restaurant',
    'fait semblant d’aimer un plat chez des amis',
    'mélangé deux aliments bizarres et adoré ça',
    'servi le petit-déjeuner au lit à quelqu’un',
    'mangé une pizza à l’ananas et aimé ça',
    // Argent
    'payé en pièces de un centime à la caisse',
    'oublié le code de ma carte bancaire',
    'trouvé un billet oublié dans un manteau et sauté de joie',
    'acheté un truc en solde dont je n’avais pas besoin',
    'fait semblant d’oublier mon portefeuille pour ne pas payer',
    'mis des mois à rendre de l’argent emprunté',
    'dépensé tout mon argent de poche le premier jour',
    'gagné à un jeu à gratter',
    'rêvé de ce que je ferais en gagnant au loto',
    'vendu mes affaires sur Vinted ou Leboncoin',
    // Sport
    'abandonné une salle de sport après une seule séance',
    'acheté une tenue de sport sans jamais m’en servir',
    'trébuché devant tout le monde en courant',
    'fait semblant de savoir jouer à un sport',
    'pleuré après un match perdu',
    'regardé un match en prétendant m’y connaître',
    'pris un ballon en pleine figure',
    'juré de me remettre au sport le 1er janvier',
    'eu des courbatures pendant une semaine',
    'plus tombé que glissé en faisant du ski ou du snowboard',
    'dansé seul dans mon salon comme si personne ne me voyait',
    // Réseaux sociaux
    'supprimé une publication parce qu’elle n’avait pas assez de likes',
    'posté une story en espérant qu’une seule personne la voie',
    'regardé des stories avec un faux compte',
    'ignoré une demande d’ami exprès',
    'passé une heure à choisir la photo à poster',
    'retouché une photo avant de la publier',
    'partagé un article sans l’avoir lu',
    'cru à une fausse information et l’avoir partagée',
    'écrit un message en colère puis tout effacé',
    'regardé des vidéos de chats pendant des heures',
    // Animaux et plantes
    'parlé à un animal comme à un humain',
    'eu peur d’un pigeon',
    'été poursuivi par un oiseau ou un chien',
    'adopté un animal sur un coup de tête',
    'tué une plante pourtant réputée indestructible',
    'donné un prénom à ma voiture ou à un objet',
    'tenu une araignée dans la main',
    'couru après un animal pour le prendre en photo',
    // Mensonges et petites hontes
    'dit « j’arrive » alors que je n’étais pas encore parti',
    'fait semblant d’avoir lu un livre',
    'dit « je n’ai rien entendu » alors que si',
    'prétendu être au téléphone pour éviter quelqu’un',
    'ri à une blague que je n’avais pas comprise',
    'hoché la tête sans rien comprendre à la conversation',
    'dit « enchanté » à quelqu’un que je connaissais déjà',
    'poussé une porte sur laquelle il y avait écrit « tirez »',
    'salué quelqu’un qui ne me saluait pas, mais saluait la personne derrière moi',
    'marché dans une porte vitrée',
    'tombé en public et fait semblant que c’était voulu',
    'porté mon pull à l’envers toute la journée',
    'porté deux chaussettes dépareillées sans le savoir',
    'chanté faux en public',
    'prétendu être allergique pour éviter un plat',
    'rougi en public sans raison',
    'parlé trop fort dans un endroit calme',
    'oublié ce que j’allais dire en plein milieu d’une phrase',
    'appelé quelqu’un par le mauvais prénom',
    'raté une bise et heurté le nez de la personne',
    // Fêtes
    'détesté un cadeau de Noël',
    'fait semblant d’être surpris à une fête surprise',
    'pleuré à un mariage',
    'chanté « joyeux anniversaire » complètement faux',
    'mangé de la galette jusqu’à en être malade',
    'été la dernière personne à partir d’une fête',
    'dormi pendant un feu d’artifice',
    'passé le réveillon tout seul',
    // Amour (version sage)
    'écrit un mot doux en cachette',
    'eu un coup de foudre',
    'eu le béguin pour un personnage de film ou de dessin animé',
    'pleuré devant une comédie romantique',
    'offert des fleurs à quelqu’un',
    'rougi devant quelqu’un qui me plaisait',
    'gribouillé le prénom de quelqu’un sur mon cahier',
    // Divers du quotidien
    'parlé à mon reflet',
    'ronflé si fort que je me suis réveillé',
    'parlé en dormant',
    'raté une marche d’escalier',
    'lu la fin d’un livre avant de le terminer',
    'spoilé une série à quelqu’un',
    'fait passer un mouchoir en papier dans la machine à laver',
    'gardé des vêtements trop petits en espérant les remettre',
    'appuyé plus de cinq fois sur « rappel » le matin',
    'été enfermé dehors en pyjama',
    'été coincé dans un ascenseur',
    'eu le hoquet pendant une heure',
    'gagné à une tombola',
    'cassé mes lunettes en m’asseyant dessus',
    'cherché mes lunettes alors qu’elles étaient sur ma tête',
    'regardé le même film plus de dix fois',
    'pleuré en lisant un livre',
    'pleuré de rire',
    'cru voir un fantôme',
    'chanté à tue-tête en voiture en croisant le regard d’un autre conducteur',
    'confondu la gauche et la droite en donnant une direction',
    'cherché pendant dix minutes un objet que j’avais dans la main',
  ],
  spicy: [
    'envoyé un message bourré que j’ai regretté le lendemain',
    'embrassé quelqu’un dans cette pièce',
    'ghosté quelqu’un',
    'été ghosté',
    'menti pour sortir d’un date',
    'dragué quelqu’un juste pour un verre gratuit',
    'fait le mur',
    'fini une soirée sans aucun souvenir',
    'eu un crush sur le ou la partenaire d’un pote',
    'fouillé le téléphone de mon ou ma partenaire',
    'utilisé une appli de rencontre',
    'eu un date catastrophique',
    'embrassé un inconnu en soirée',
    'menti sur mon nombre d’ex',
    'pleuré à cause d’une rupture en pleine soirée',
    'écrit à un ex à 2 h du matin',
    'été recalé à l’entrée d’une boîte',
    'été malade dans un taxi ou un VTC',
    'dormi chez quelqu’un dont je ne connaissais pas le nom de famille',
    'eu un crush sur un prof',
    'fait une déclaration que j’ai regrettée',
    'fréquenté deux personnes en même temps',
    'remis le couvert avec un ex juste parce que je m’ennuyais',
    'inventé un copain ou une copine',
    'refusé un bisou puis regretté',
    'eu une photo gênante de moi qui a circulé',
    'eu une histoire avec un ou une collègue',
    'été surpris en train d’embrasser quelqu’un',
    // Alcool et soirées
    'vomi après une soirée trop arrosée',
    'perdu à un jeu à boire et fini mon verre cul sec',
    'dansé sur une table en soirée',
    'perdu un vêtement pendant une soirée',
    'oublié où j’avais laissé ma voiture ou mon vélo après une soirée',
    'dormi sur un canapé qui n’était pas le mien après une soirée',
    'chanté au karaoké en étant très éméché',
    'pris un shot en croyant que c’était de l’eau',
    'bu dans le verre de quelqu’un par erreur',
    'perdu mon téléphone en soirée',
    'pleuré dans la salle de bains d’une soirée',
    'confié ma vie à un inconnu à 4 h du matin',
    'fait un discours enflammé en étant éméché',
    'eu une gueule de bois qui a duré deux jours',
    'juré de ne plus jamais boire puis recommencé la semaine suivante',
    'été la dernière personne debout en soirée',
    'dormi par terre pendant une soirée',
    'posté une story en soirée que j’ai supprimée le lendemain',
    'fini une soirée à 6 h du matin',
    'fait l’after chez quelqu’un que je connaissais à peine',
    'fait semblant d’être plus ivre que je ne l’étais',
    'dormi dans un taxi après une soirée',
    'relevé un défi alcoolisé que j’ai regretté',
    'joué à action ou vérité jusqu’à le regretter',
    'joué à la bouteille',
    'été le seul sobre d’une soirée très arrosée',
    'fait un faux pas en soirée devant la personne qui me plaisait',
    // Drague
    'dragué un serveur ou une serveuse',
    'demandé le numéro de quelqu’un en soirée',
    'donné un faux numéro de téléphone',
    'reçu un râteau devant tout le monde',
    'posé un lapin à un rendez-vous',
    'attendu quelqu’un qui n’est jamais venu à un rendez-vous',
    'tenté un « tu viens souvent ici ? »',
    'relu dix fois un message avant de l’envoyer à mon crush',
    'demandé à un ami de relire mon message à un crush',
    'attendu exprès avant de répondre pour paraître occupé',
    'ignoré un message pour jouer la difficulté',
    'proposé un verre à un ou une collègue avec une arrière-pensée',
    'été « juste ami » avec quelqu’un en espérant bien plus',
    'invité quelqu’un à danser sans le ou la connaître',
    'reçu un verre offert par un ou une inconnue',
    'offert un verre à quelqu’un pour lui plaire',
    'dansé un slow avec un ou une inconnue',
    'laissé mon numéro sur une serviette',
    'fait un clin d’œil à quelqu’un et regretté aussitôt',
    'été surpris en train de regarder quelqu’un trop longtemps',
    'espéré une réponse à cause d’un simple émoji',
    'passé un week-end entier à attendre une réponse',
    'changé de trajet pour croiser quelqu’un',
    'organisé un faux hasard pour croiser quelqu’un',
    'envoyé un « Salut, ça va ? » à un crush après des mois de silence',
    'liké une vieille photo de mon crush exprès',
    'craqué pour quelqu’un uniquement à cause de sa voix',
    'eu un coup de cœur pour un voisin ou une voisine',
    'laissé quelqu’un de côté pour sortir avec mieux',
    'fait l’entremetteur ou l’entremetteuse pour deux amis',
    'surpris deux amis en train de s’embrasser',
    // Applis de rencontre et dates
    'eu un date avec quelqu’un qui ne ressemblait pas à sa photo',
    'retouché mes photos sur une appli de rencontre',
    'menti sur ma taille ou mon métier sur une appli de rencontre',
    'swipé à gauche sur quelqu’un que je connaissais',
    'matché avec un ou une collègue sur une appli',
    'matché avec un ex',
    'annulé un date à la dernière minute',
    'annulé un date pour un meilleur plan',
    'parlé de mon ex pendant tout un date',
    'fait semblant d’aller aux toilettes pour fuir un date',
    'envoyé un SOS à un ami pendant un date',
    'payé l’addition d’un date pour paraître généreux',
    'laissé la personne payer l’addition au premier rendez-vous',
    'fait croire à ma famille que j’étais en couple',
    'présenté un ami ou une amie comme mon ou ma partenaire',
    'fait semblant d’être célibataire',
    'eu une relation à distance',
    'passé la nuit entière à discuter avec quelqu’un sans dormir',
    'dormi dans le même lit que quelqu’un sans que rien se passe',
    'partagé un lit avec un ou une ami(e)',
    // Ex et ruptures
    'gardé des affaires d’un ex',
    'supprimé toutes les photos d’un ex en pleine nuit',
    'écouté la même chanson triste en boucle après une rupture',
    'rompu par message',
    'été largué par message',
    'quitté quelqu’un sans lui dire pourquoi',
    'été largué un jour de fête',
    'supplié un ex de revenir',
    'croisé un ex en soirée et fait semblant de ne pas le voir',
    'croisé mon ex avec quelqu’un d’autre en pleine rue',
    'stalké le nouveau ou la nouvelle partenaire de mon ex',
    'retrouvé un ex à un mariage',
    'appelé mon ou ma partenaire par le prénom d’un ex',
    'gardé un ex comme plan B',
    'été le plan B de quelqu’un',
    'pris des nouvelles d’un ex juste pour savoir',
    'été en couple juste pour ne pas être seul ou seule',
    'gardé une relation par simple habitude',
    // Couple et sentiments
    'rencontré les parents de mon ou ma partenaire et dit une bêtise',
    'été jaloux d’un ami ou d’une amie de mon ou ma partenaire',
    'fait une scène de jalousie en public',
    'dit « je t’aime » trop tôt',
    'dit « je t’aime » sans le penser',
    'embrassé quelqu’un pour rendre une autre personne jalouse',
    'fait exprès de rendre quelqu’un jaloux',
    'été témoin d’une dispute de couple très gênante',
    'mal embrassé et regretté',
    'embrassé quelqu’un dont je ne connaissais pas le prénom',
    'menti à ma famille sur ma vie amoureuse',
    'été amoureux ou amoureuse en secret pendant plus d’un an',
    // Encore des soirées et des sentiments
    'été séparé de mes amis en boîte et rentré seul',
    'oublié le prénom de quelqu’un juste après l’avoir embrassé',
    'envoyé un vocal bourré à mon crush',
    'mis une chanson en soirée pour draguer quelqu’un',
    'été pris en photo dans un moment gênant en soirée',
    'vérifié la dernière connexion d’un ex ou d’un crush',
    'répondu à une story pour lancer la conversation avec mon crush',
    'rédigé un long message de rupture sans jamais l’envoyer',
    'juré à un ex que j’étais passé à autre chose alors que non',
    'flirté pour obtenir un service ou une réduction',
    'inventé un rencard pour éviter une soirée',
    'croisé quelqu’un que je connaissais pendant un rendez-vous',
    'vu mon crush avec quelqu’un d’autre en faisant semblant que ça m’était égal',
    'été en couple avec quelqu’un que mes amis détestaient',
    'été amoureux ou amoureuse de mon meilleur ami ou de ma meilleure amie',
    'dansé collé-serré avec quelqu’un sans oser l’embrasser',
    'fait un toast ridicule en soirée',
    'cherché mon ex dans la foule en boîte',
    'demandé à un DJ de passer une chanson pour quelqu’un',
    'embrassé quelqu’un sur un dancefloor',
    'proposé à quelqu’un de rentrer ensemble en fin de soirée',
    'bu un verre en cachette avec quelqu’un dont mes amis ne savaient rien',
    'menti à mes amis pour retrouver quelqu’un en secret',
    'prétendu être sobre devant mes parents après une soirée',
    'changé mon statut sur les réseaux trop vite après une rencontre',
  ],
  hot: [
    'couché le premier soir',
    'envoyé une photo coquine',
    'fait l’amour dans un lieu public',
    'eu un plan à trois',
    'simulé',
    'couché avec un ou une ex après la rupture',
    'eu un sex friend',
    'fait l’amour dans une voiture',
    'été surpris en plein acte',
    'utilisé des menottes',
    'fait un strip-tease',
    'couché avec quelqu’un rencontré le soir même',
    'fantasmé sur quelqu’un de cette pièce',
    'regardé un film X avec quelqu’un',
    'couché avec quelqu’un de plus de dix ans mon aîné',
    'fait l’amour à la plage',
    'acheté un sextoy',
    'joué à un jeu de rôle au lit',
    'eu une aventure d’un soir en vacances',
    'fait l’amour chez mes parents',
    'été attiré par quelqu’un du même sexe',
    'envoyé un message coquin à la mauvaise personne',
    'couché avec deux personnes différentes le même week-end',
    'fait l’amour au travail',
    'eu un rendez-vous coquin via une appli',
    'fait l’amour plus de cinq fois dans la même journée',
    'été nu dans un lieu public',
    'fait un rêve érotique sur un ou une amie',
    // Lieux insolites
    'fait l’amour sous la douche',
    'fait l’amour dans la cuisine',
    'fait l’amour dans un ascenseur',
    'fait l’amour dans une tente de camping',
    'fait l’amour dans une chambre d’hôtel',
    'fait l’amour devant un miroir',
    'fait l’amour avec la lumière allumée',
    'fait l’amour dans un jacuzzi ou un spa',
    'fait l’amour sous les étoiles',
    'fait l’amour en pleine forêt',
    'fait l’amour chez des amis pendant qu’ils dormaient à côté',
    'fait l’amour dans un train de nuit',
    'fait l’amour sur un balcon ou une terrasse',
    'fait l’amour dans un escalier',
    'fait l’amour dans une piscine',
    'fait l’amour sur un bateau',
    'fait l’amour dans les toilettes d’un bar ou d’une boîte',
    'fait l’amour par terre faute d’avoir pu atteindre le lit',
    'fait l’amour pendant un orage',
    'fait l’amour la nuit du 31 décembre',
    'fait l’amour sur une table',
    'fait l’amour dans la salle de bains pendant une soirée',
    'fait l’amour au réveil',
    'fait l’amour avant un entretien ou un examen',
    // Lendemains et situations gênantes
    'oublié le prénom de la personne avec qui j’avais passé la nuit',
    'filé avant le petit-déjeuner après une nuit chez quelqu’un',
    'fait la marche de la honte au petit matin',
    'remis mes vêtements dans le noir en cherchant ma chaussette',
    'fait entrer quelqu’un en cachette chez moi',
    'fait sortir quelqu’un en cachette au petit matin',
    'entendu mes voisins faire l’amour',
    'été entendu par mes voisins',
    'mis la musique à fond pour couvrir le bruit',
    'eu un fou rire en plein moment intime',
    'chuté du lit au pire moment',
    'eu une crampe au mauvais moment',
    'été interrompu par un animal de compagnie',
    'été interrompu par un appel de mes parents',
    'été interrompu par quelqu’un qui est entré dans la pièce',
    'dit le mauvais prénom au mauvais moment',
    'oublié le dîner sur le feu à cause d’un câlin',
    'été en retard au travail à cause d’un câlin matinal',
    'eu un suçon que j’ai dû cacher',
    'eu des courbatures après une nuit mouvementée',
    'acheté des préservatifs en rougissant',
    'rougi en lisant un message coquin',
    'raconté mes ébats à mes amis',
    'tenu une liste de mes partenaires',
    // Messages, photos et vidéo
    'envoyé un nude',
    'reçu un nude',
    'fait un sexto',
    'fait un appel vidéo coquin',
    'eu une relation coquine à distance',
    'écrit un message érotique',
    'écrit une histoire érotique',
    'lu un roman érotique',
    'regardé un film érotique',
    'écouté un audio érotique',
    'pris une photo sexy de moi dans un miroir',
    'pris des photos de moi en sous-vêtements',
    'fait une séance photo sensuelle',
    'laissé un mot coquin dans la poche de quelqu’un',
    'chuchoté des mots coquins à l’oreille de quelqu’un en public',
    // Fantasmes
    'eu un fantasme que je n’ai jamais avoué',
    'avoué un fantasme à mon ou ma partenaire',
    'réalisé un fantasme',
    'fantasmé sur un ou une célébrité',
    'fantasmé sur un ou une collègue',
    'fantasmé sur le ou la partenaire d’un ami',
    'eu un fantasme pour quelqu’un en uniforme',
    'regardé quelqu’un à la salle de sport avec des idées coquines',
    'eu un coup de chaud devant une scène de film',
    'eu des frissons à cause d’un baiser dans le cou',
    'regardé le corps de quelqu’un sans pouvoir m’en empêcher',
    'rêvé d’un ou d’une ex en pleine nuit',
    // Jeux et accessoires
    'fait un massage sensuel',
    'fini au lit après un massage',
    'pris un bain à deux aux chandelles',
    'joué avec de la cire ou des glaçons',
    'mis un bandeau sur les yeux',
    'porté de la lingerie pour quelqu’un',
    'porté un déguisement coquin',
    'acheté de la lingerie pour une occasion',
    'dansé de façon sensuelle pour quelqu’un',
    'joué au strip-poker',
    'joué à action ou vérité avec des gages coquins',
    'acheté un jeu coquin',
    'offert un cadeau coquin à quelqu’un',
    'reçu un cadeau coquin',
    'joué à un jeu de cartes coquin en couple',
    'organisé une surprise coquine pour mon ou ma partenaire',
    'proposé « Netflix and chill » avec une idée derrière la tête',
    'arrêté un film au bout de dix minutes pour finir au lit',
    'passé un week-end entier au lit',
    'fait du pied sous la table à quelqu’un',
    'caressé le genou de quelqu’un sous la table',
    'dormi nu ou nue',
    'fait du naturisme',
    'bronzé en topless ou nu',
    'pris un bain de minuit tout nu',
    'pris un bain de minuit en sous-vêtements',
    // Rencontres
    'accepté un « dernier verre » en sachant très bien ce que ça voulait dire',
    'couché avec un ou une ami(e) et abîmé l’amitié',
    'couché avec un ou une voisine',
    'couché avec un ou une camarade de fac',
    'couché avec quelqu’un qui ne parlait pas ma langue',
    'couché avec quelqu’un dont j’avais honte devant mes amis',
    'eu un coup d’un soir que j’ai revu ensuite',
    'eu un coup de foudre purement physique',
    'embrassé quelqu’un langoureusement en public',
    'embrassé plusieurs personnes dans la même soirée',
    'embrassé une personne du même sexe',
    'eu un câlin coquin dans un cinéma',
    'gardé secrète une relation coquine pendant des mois',
    'parlé de mes préférences intimes avec un ou une ami(e)',
    // Encore plus coquin
    'pris une douche à deux',
    'joué avec de la chantilly ou du chocolat',
    'pris un petit-déjeuner au lit après une nuit torride',
    'porté la chemise de quelqu’un le lendemain matin',
    'gardé un vêtement oublié par un coup d’un soir',
    'écrit un poème coquin',
    'murmuré des mots crus à l’oreille de quelqu’un',
    'fait l’amour en cinq minutes chrono faute de temps',
    'fait l’amour sur un lave-linge en marche',
    'mis de la musique pour l’ambiance avant un moment intime',
    'préparé une chambre avec bougies et pétales pour un moment intime',
    'eu des pensées coquines pendant une réunion de travail',
    'eu des pensées coquines pendant un repas de famille',
    'réservé un hôtel juste pour une nuit coquine',
    'fait l’amour dans toutes les pièces de la maison',
    'passé une nuit blanche pour des raisons très coquines',
    'dit à quelqu’un ce que j’aime au lit',
    'poussé la porte d’un sex-shop',
    'touché quelqu’un « accidentellement exprès »',
    'fait un câlin amical qui a duré trop longtemps',
    'lu un message coquin à voix haute',
  ],
}
