import type { Level } from '../engine'

/** « Je n'ai jamais… » — chaque entrée complète la phrase. */
export const neverHaveI: Record<Level, string[]> = {
  soft: [
    'mangé un plat tombé par terre',
    'fait semblant de connaître une chanson en soirée',
    'oublié le prénom de quelqu’un juste après les présentations',
    'parlé tout seul dans la rue',
    'pleuré devant un dessin animé',
    'raté un train ou un avion',
    'menti sur mon âge',
    'stalké l’ex de quelqu’un sur les réseaux',
    'fait une sieste de plus de trois heures',
    'envoyé un message à la mauvaise personne',
    'chanté sous la douche à pleine voix',
    'acheté un truc inutile à 3 h du matin',
    'fait semblant d’être malade pour éviter quelqu’un',
    'mangé un pot de glace entier d’un coup',
    'regardé une série entière en un week-end',
    'eu peur du noir après un film d’horreur',
    'été viré d’un cours',
    'liké une vieille photo par accident',
    'fait un selfie avec un inconnu',
    'perdu mes clés plus de trois fois dans le même mois',
    'dormi dans un endroit public',
    'eu un fou rire à un moment où il ne fallait surtout pas',
    'raconté une blague que personne n’a comprise',
    'appelé un prof « maman » ou « papa »',
    'mangé quelque chose de périmé sans le savoir',
    'fait un vœu sur une étoile filante',
    'menti dans une partie de Je n’ai jamais',
    'tenté une recette vue sur TikTok',
  ],
  spicy: [
    'envoyé un message bourré que j’ai regretté le lendemain',
    'embrassé quelqu’un dans cette pièce',
    'ghosté quelqu’un',
    'été ghosté',
    'menti pour sortir d’un date',
    'dragué quelqu’un juste pour un verre gratuit',
    'fait le mur',
    'fini une soirée sans aucun souvenir',
    'eu un crush sur le ou la partenaire d’un pote',
    'fouillé le téléphone de mon ou ma partenaire',
    'utilisé une appli de rencontre',
    'eu un date catastrophique',
    'embrassé un inconnu en soirée',
    'menti sur mon nombre d’ex',
    'pleuré à cause d’une rupture en pleine soirée',
    'écrit à un ex à 2 h du matin',
    'été recalé à l’entrée d’une boîte',
    'été malade dans un taxi ou un VTC',
    'dormi chez quelqu’un dont je ne connaissais pas le nom de famille',
    'eu un crush sur un prof',
    'fait une déclaration que j’ai regrettée',
    'fréquenté deux personnes en même temps',
    'remis le couvert avec un ex juste parce que je m’ennuyais',
    'inventé un copain ou une copine',
    'refusé un bisou puis regretté',
    'eu une photo gênante de moi qui a circulé',
    'eu une histoire avec un ou une collègue',
    'été surpris en train d’embrasser quelqu’un',
  ],
  hot: [
    'couché le premier soir',
    'envoyé une photo coquine',
    'fait l’amour dans un lieu public',
    'eu un plan à trois',
    'simulé',
    'couché avec un ou une ex après la rupture',
    'eu un sex friend',
    'fait l’amour dans une voiture',
    'été surpris en plein acte',
    'utilisé des menottes',
    'fait un strip-tease',
    'couché avec quelqu’un rencontré le soir même',
    'fantasmé sur quelqu’un de cette pièce',
    'regardé un film X avec quelqu’un',
    'couché avec quelqu’un de plus de dix ans mon aîné',
    'fait l’amour à la plage',
    'acheté un sextoy',
    'joué à un jeu de rôle au lit',
    'eu une aventure d’un soir en vacances',
    'fait l’amour chez mes parents',
    'été attiré par quelqu’un du même sexe',
    'envoyé un message coquin à la mauvaise personne',
    'couché avec deux personnes différentes le même week-end',
    'fait l’amour au travail',
    'eu un rendez-vous coquin via une appli',
    'fait l’amour plus de cinq fois dans la même journée',
    'été nu dans un lieu public',
    'fait un rêve érotique sur un ou une amie',
  ],
}
