import type { Level } from '../engine'

/** Paranoïa — chaque entrée complète « Qui ici… », chuchotée à l’oreille du voisin. */
export const paranoia: Record<Level, string[]> = {
  soft: [
    'serait le pire colocataire',
    'a le plus de chances de finir célèbre',
    'ment le plus souvent à ses parents',
    'se perdrait même avec un GPS',
    'oublie tout le temps où il a posé ses clés',
    'arrive en retard même à son propre anniversaire',
    'a déjà ri à une blague sans la comprendre',
    'cache un talent inutile mais impressionnant',
    'pense secrètement être le meilleur cuisinier du groupe',
    'a déjà pleuré devant un dessin animé',
    'survivrait le plus longtemps sur une île déserte',
    'serait le premier éliminé dans un film d’horreur',
    'a la playlist la plus honteuse',
    'chante faux mais avec une confiance totale',
    'a déjà regardé une série entière en une seule nuit',
    'est le plus susceptible de gagner au loto et de tout perdre',
    'a le fou rire le plus contagieux',
    'dirait oui à n’importe quel projet complètement fou',
    'garde une vieille photo de lui qu’il n’oserait jamais montrer',
    'a déjà fait semblant d’être malade pour éviter une sortie',
    'parle tout seul quand il se croit seul',
    'a la pire écriture du groupe',
    'serait le meilleur chef d’une expédition en montagne',
    'passe sa vie à répondre aux messages avec trois jours de retard',
    'a déjà dansé tout seul devant son miroir',
    'serait le plus convaincant en faux médecin dans une pièce de théâtre',
    'collectionne quelque chose de très bizarre',
    'a déjà été recalé à un examen très facile',
    'pense être plus drôle qu’il ne l’est vraiment',
    'serait le meilleur garde du corps du groupe',
    'garde en secret un doudou ou une peluche',
    'a déjà inventé une excuse absurde pour annuler une soirée',
    'rêve de tout plaquer pour ouvrir un café au bout du monde',
    'est le plus doué pour faire rire les enfants',
    'a déjà confondu le prénom de quelqu’un pendant des mois',
    'dort le plus longtemps le week-end',
    'serait le meilleur dans une émission de télé-réalité',
    'a déjà fait une grosse bêtise à l’école sans jamais se faire prendre',
    'passe son temps à consulter la météo',
    'a le plus de chances de rater son train',
    'tient un journal intime ou l’a déjà fait',
    'a déjà fait croire qu’il savait faire quelque chose qu’il ne savait pas faire',
    'est le plus soupe au lait du groupe',
    'cache des bonbons quelque part chez lui',
    'a déjà pleuré à un mariage sans connaître les mariés',
    'est le plus susceptible de devenir un grand-père ou une grand-mère adoré',
    'dirait des horreurs sur le groupe si on lui offrait mille euros',
    'a déjà parlé à un animal comme à un humain',
    'serait le plus mauvais perdant à un jeu de société',
    'a un vieux surnom ridicule qu’il déteste',
    'prépare trop à manger quand il reçoit',
    'a déjà fait semblant de dormir pour éviter une conversation',
    'ferait le meilleur président de classe',
    'trouve que tout le monde conduit mal sauf lui',
    'a déjà envoyé un message à la mauvaise personne',
    'serait le plus à l’aise pour parler devant mille personnes',
    'connaît par cœur une réplique de film qu’il récite à tout bout de champ',
    'se prend pour un grand sportif sans l’être',
    'a la bibliothèque musicale la plus étrange',
    'ne supporte pas qu’on lui dise qu’il a tort',
    'pense être le plus intelligent de la pièce',
    'a déjà pris un fou rire pendant un moment très sérieux',
    'est le plus doué pour trouver des excuses',
    'a déjà fait une sieste en pleine réunion ou en plein cours',
    'passe plus de temps sur son téléphone qu’il ne veut l’admettre',
    'serait le meilleur détective du groupe',
    'garde une rancune bien trop longue pour une broutille',
    'rêve en secret de devenir une star de la chanson',
    'a déjà perdu quelque chose d’important le jour le plus important',
    'serait le meilleur partenaire pour un tour du monde',
    'a déjà adopté un accent étranger pour s’amuser',
    'est le plus généreux avec les cadeaux',
    'n’a jamais vraiment su faire un nœud de cravate ou de lacets',
    'a le plus de chances de gagner un concours de grimaces',
    'cache un gros défaut derrière un grand sourire',
    'est plus sensible qu’il ne veut le montrer',
    'a déjà pleuré de rire devant une vidéo de chats',
    'est le plus doué pour raconter des histoires',
    'ferait un excellent professeur',
    'a menti sur son âge ou sa taille une fois dans sa vie',
    'a le plus de chances de se faire tatouer un truc nul',
    'trouve toujours le bon cadeau pour les autres',
    'a déjà oublié l’anniversaire d’un ami proche',
    'regarde en cachette des émissions que personne ne devine',
    'est le plus maniaque du groupe',
    'est le plus bordélique du groupe',
    'a un rituel bizarre avant de s’endormir',
    'a le plus de chances de se marier en premier',
    'a déjà fait une blague qui a mal tourné',
    'serait le plus mauvais passager pendant un long voyage',
    'aurait été le chouchou de la maîtresse',
    'a déjà copié sur son voisin en classe',
    'garde tout et ne jette rien',
    'est le meilleur public pour une mauvaise blague',
    'a déjà dit je suis bientôt là alors qu’il était encore chez lui',
    'est le plus dépensier du groupe',
    'est le plus radin du groupe',
    'serait capable de pleurer pour obtenir une réduction',
    'a déjà ressenti de la jalousie pour un ami sans le dire',
    'a un côté très sérieux que personne ne soupçonne',
    'pourrait vivre uniquement de pizzas',
    'a déjà fait croire à ses amis qu’il partait en voyage alors qu’il restait chez lui',
    'est le plus nul pour garder un secret',
    'a déjà raconté un secret qu’on lui avait confié',
    'a la voix la plus étrange au téléphone',
    'serait le meilleur imitateur du groupe',
    'est le plus susceptible d’avoir un chat ou un chien ridiculement gâté',
    'a déjà rêvé de quelqu’un dans cette pièce',
    'a le plus de chances de réussir à tout casser en un seul geste',
    'a déjà trouvé un faux prétexte pour quitter une fête plus tôt',
    'est celui qui a le plus changé depuis l’adolescence',
    'se couche toujours trop tard',
    'est un grand enfant dans l’âme',
    'a déjà fait semblant d’aimer un cadeau qu’il détestait',
    'cache un grand secret derrière son air tranquille',
    'a le plus peur du noir',
    'a le plus peur des araignées',
    'est le plus téméraire sur un manège à sensations',
    'a déjà pris le mauvais bus ou le mauvais train à cause de sa distraction',
    'est capable de manger la même chose tous les jours',
    'a le plus de chances de survivre à une apocalypse zombie',
    'a déjà fait semblant de comprendre une conversation de vacances ou de sport',
    'est le plus nul en bricolage',
    'est le plus fort en bricolage',
    'cuisine mieux que ce qu’il laisse croire',
    'a déjà pleuré en regardant un film de sport',
    'est un vrai fan de quelque chose de très niche',
    'ne sait pas dire non à ses amis',
    'pense déjà à ses prochaines vacances alors qu’il vient de rentrer',
    'est la personne la plus têtue du groupe',
    'a déjà évité quelqu’un dans la rue pour ne pas lui parler',
    'a le meilleur sens de la répartie',
    'est le plus fort pour négocier un prix',
    'a déjà fait une très mauvaise coupe de cheveux par choix',
    'a le plus de chances d’être un jour dans le journal',
    'n’a pas encore vu un film culte que tout le monde adore',
    'ferait le meilleur animateur de soirée',
    'a déjà trouvé un objet de valeur dans la rue',
    'est le plus doué pour faire des câlins',
    'a une peur ridicule de quelque chose de banal',
    'est secrètement le plus romantique du groupe',
    'a déjà regardé un film d’horreur avec les yeux fermés',
    'est celui sur qui on peut toujours compter',
    'est le plus agaçant quand il perd',
    'a déjà fait une farce à un inconnu',
    'est le plus fort aux jeux vidéo',
    'a déjà fait une partie de cache-cache ou de jeu d’enfant en tant qu’adulte',
    'pense que sa vie ferait un excellent film',
    'garde en tête une conversation embarrassante depuis des années',
    'est le plus honnête, même quand ça fait mal',
    'a le plus de chances d’oublier son propre numéro de téléphone',
    'dort avec une lumière ou un bruit de fond',
    'est le plus paresseux du groupe',
    'est le plus actif du groupe',
    'a déjà inventé un mot qu’il utilise comme s’il existait',
    'est le plus susceptible de rater un vol',
    'a déjà fait un faux numéro exprès pour rire',
    'sait faire un tour de magie qu’il cache',
    'a déjà été témoin d’un moment très gênant pour quelqu’un d’ici',
    'est un peu trop dramatique pour un petit rhume',
    'a déjà fait le mort pour éviter une dispute',
    'sait toujours remonter le moral des autres',
    'a le plus de chances de devenir riche en vendant une idée absurde',
    'est un expert en excuses pour ne pas faire la vaisselle',
    'est le plus nostalgique de son enfance',
    'se vante parfois de choses qui ne sont pas tout à fait vraies',
    'aimerait changer de métier en secret',
    'a déjà écrit un poème ou une chanson en cachette',
    'a le plus de chances de devenir un excellent parent',
    'aurait fait un bon espion',
    'a déjà regardé quelqu’un d’ici en se disant qu’il le ou la connaissait mal',
    'connaît l’ensemble des paroles d’un tube qu’il prétend détester',
    'donne les meilleurs conseils mais ne les applique jamais',
    'a déjà été surpris en train de chanter sous la douche',
    'est le plus enclin à raconter sa vie à un inconnu dans le train',
    'a un côté secrètement très compétitif',
    'a déjà fait croire à quelqu’un d’ici qu’il le ou la détestait pour rire',
    'passe pour le plus calme mais cache une vraie folie',
    'est celui dont on se souviendra le plus longtemps dans cette soirée',
  ],
  spicy: [
    'a déjà eu un crush sur un ami de cette pièce',
    'est le plus susceptible de s’être déjà fait recaler en soirée',
    'a déjà stalké l’ex de quelqu’un',
    'a déjà envoyé un message à son ex à 3 heures du matin',
    'est le plus jaloux en couple',
    'se ferait le plus facilement draguer par un inconnu',
    'drague le plus maladroitement',
    'a déjà fait semblant d’avoir un copain ou une copine pour se débarrasser de quelqu’un',
    'a le plus de chances de finir la soirée dans les bras de quelqu’un',
    'a déjà embrassé quelqu’un dont il ne connaissait pas le prénom',
    'cache un crush depuis des mois',
    'a déjà été amoureux de quelqu’un qui sortait avec son ami',
    'est le plus doué pour séduire d’un seul regard',
    'a déjà pleuré à cause d’une rupture et ne l’a avoué à personne',
    'a déjà mis une cuite mémorable',
    'a le plus de chances de se réveiller sans savoir comment il est rentré',
    'a déjà fouillé le téléphone de son partenaire',
    'a déjà passé la nuit chez quelqu’un en prétendant dormir chez un ami',
    'ment le plus sur son nombre de conquêtes',
    'garde des photos de son ex dans son téléphone',
    'a déjà été largué par message',
    'a déjà largué quelqu’un par message',
    'est resté bien trop longtemps avec quelqu’un par peur d’être seul',
    'a déjà fait du charme pour obtenir un verre gratuit',
    'a déjà dragué un serveur ou une serveuse',
    'est le plus susceptible d’avoir déjà couru après quelqu’un qui ne voulait pas de lui',
    'est l’ami le plus enclin à se mêler des histoires de cœur des autres',
    'est le plus en mode célibataire endurci',
    'aurait pu sortir avec la moitié de cette pièce',
    'est secrètement amoureux de quelqu’un d’ici',
    'a déjà trouvé un ami de ses amis très attirant',
    'est le plus mauvais pour écrire un message de séduction',
    'a déjà fait le premier pas dans un bar',
    'a déjà vomi en soirée devant tout le monde',
    'a le plus de chances de tomber amoureux ce mois-ci',
    'a déjà fait croire qu’il était très occupé pour éviter un rendez-vous',
    'a déjà posé un lapin à un rendez-vous',
    'a déjà été plaqué sur la piste de danse',
    'est le plus nul en danse mais le plus motivé',
    'a le plus de chances de se mettre en couple avec un ami',
    'a déjà aimé une photo vieille de trois ans sur le profil de quelqu’un par erreur',
    'est le plus susceptible d’avoir une relation compliquée en ce moment',
    'drague quand il a bu',
    'raconte des choses qu’il regrette quand il a trop bu',
    'a déjà dit je t’aime sans le penser',
    'a déjà été amoureux sans oser le dire',
    'a le plus de mal à tourner la page',
    'a déjà fait croire à quelqu’un qu’il n’était pas disponible alors qu’il l’était',
    'a un profil de rencontre dont il a honte',
    'est le plus susceptible d’avoir déjà dragué sur une appli de rencontre',
    'passe pour le plus sérieux mais cache un passé de fêtard',
    'a déjà fini sur un canapé d’inconnu après une soirée',
    'a déjà laissé quelqu’un en vu après un message important',
    'est le plus fort pour inventer un mensonge sur une soirée',
    'a déjà dû fuir une soirée à cause d’un ex',
    'a déjà reçu un message d’un ex et fait semblant de ne pas l’avoir lu',
    'se fait toujours draguer sans le remarquer',
    'est le plus doué pour flirter avec tout le monde sans arrière-pensée',
    'a déjà gardé un ex en contact juste pour le plaisir',
    'est le plus nostalgique d’une ancienne histoire',
    'a déjà fait une scène de jalousie en public',
    'est le plus sûr de son pouvoir de séduction',
    'se trompe sur son pouvoir de séduction',
    'a déjà embrassé quelqu’un sur un coup de tête dans cette soirée ou une précédente',
    'aurait pu avoir un coup de cœur pour un prof',
    'a déjà fait un faux pas en soirée dont il se souvient encore',
    'a déjà été surpris en train d’espionner un profil',
    'est le plus fort pour retomber sur ses pattes après une rupture',
    'ne répond jamais aux messages d’un prétendant',
    'pense que c’est toujours l’autre qui a tort après une dispute',
    'a un type très précis et très étrange',
    'a déjà dit à quelqu’un qu’il l’appellerait sans jamais le faire',
    'a déjà fait croire à une rencontre fortuite alors que tout était calculé',
    'a déjà passé un temps fou à choisir une tenue pour un rendez-vous',
    'a déjà demandé conseil à tout le groupe sur un message de séduction',
    'est le plus susceptible d’avoir couru après un ex',
    'aurait déjà dû se remettre avec son ex',
    'aurait dû rester avec son ex',
    'a déjà été le troisième sur un rendez-vous',
    'est le plus protecteur envers ses amis en soirée',
    'a déjà fait du charme à quelqu’un pour obtenir un service',
    'a déjà cherché à rendre quelqu’un jaloux',
    'a déjà eu un coup de cœur pour un inconnu dans les transports',
    'a déjà mis un pas dans la zone ami et n’en est jamais sorti',
    'a déjà été ami avec un ex après une rupture compliquée',
    'est le plus doué pour pleurer sur commande',
    'est le plus doué pour s’inviter dans une soirée',
    'est le plus enclin à tout raconter après trois verres',
    'a déjà gardé un secret énorme pendant des années',
    'a déjà gâché une soirée par jalousie',
    'est le premier à lancer un jeu à boire',
    'est celui qui tient le moins bien l’alcool',
    'est celui qui tient le mieux l’alcool',
    'a déjà fini la soirée dans la salle de bains avec un ami',
    'a déjà fait un discours embarrassant à une fête',
    'a déjà raconté la vie intime d’un ami à un autre',
    'est le plus susceptible d’avoir un secret qu’on découvrirait par hasard',
    'est le plus susceptible de rester jusqu’au bout de la soirée',
    'est le plus susceptible de partir sans dire au revoir',
    'a déjà fait un appel manqué à quelqu’un en pensant à lui',
    'est le plus susceptible de rougir à une question gênante',
    'a déjà fait semblant de ne pas connaître quelqu’un en soirée',
    'a déjà été pris en flagrant délit en train de regarder le téléphone de quelqu’un',
    'a déjà eu de gros regrets amoureux',
    'garde la lettre ou le message d’un amour passé',
    'est le plus doué pour jouer l’indifférent',
    'a le plus de chances de se marier à Las Vegas sur un coup de tête',
    'a déjà fait quelque chose de fou par amour',
    'dort le plus souvent chez quelqu’un d’autre',
    'a déjà croisé quelqu’un d’ici dans une situation très gênante',
    'a déjà trouvé quelqu’un d’ici très séduisant sans jamais le dire',
    'est le meilleur pour séduire avec une bonne blague',
    'a le plus de chances d’avoir un amour caché',
    'est le plus susceptible de tomber amoureux lors d’un voyage',
    'aurait pu sortir avec l’ex de quelqu’un d’ici',
    'est le plus nul pour dire non à un verre de plus',
    'aime secrètement être le centre de l’attention',
    'est le plus susceptible d’avoir dansé sur une table',
    'a déjà fait un karaoké en solo devant tout un bar',
    'a déjà pleuré sur l’épaule d’un inconnu',
    'est celui qui connaît le plus de ragots',
    'est le premier à relayer un ragot',
    'a déjà dit du mal d’un ami et s’est fait prendre',
    'a déjà lu un message qui ne lui était pas destiné',
    'est le plus doué pour mentir sans rougir',
    'est le plus nul pour mentir',
    'a déjà fait croire à un amour d’un soir qu’il s’appelait autrement',
    'a déjà fait le premier pas sur une appli de rencontre',
    'est le plus susceptible d’avoir déjà posté une photo pour rendre son ex jaloux',
    'est le plus susceptible d’avoir bloqué quelqu’un sur les réseaux',
    'a déjà débloqué quelqu’un sur les réseaux sociaux en cachette',
    'regarde le plus souvent les stories de son ex',
    'est celui dont l’ex pense encore à lui',
    'a déjà fait croire à une panne de téléphone pour éviter un message',
    'est le plus enclin à pardonner un mensonge amoureux',
    'garde en mémoire tous les détails d’un premier rendez-vous',
    'a déjà été reconnu en soirée par un ancien flirt',
    'a déjà eu un flirt avec un collègue',
    'est le plus doué pour improviser une excuse après une nuit blanche',
    'a déjà fait un petit mensonge pour avoir une deuxième chance',
    'a des amis qui pensent tout savoir de sa vie amoureuse alors que non',
    'a déjà vécu un très gros râteau',
    'a le plus gros râteau à son actif',
    'a déjà été attiré par quelqu’un d’interdit',
    'a déjà eu une histoire dont personne ici n’est au courant',
    'ferait le meilleur entremetteur du groupe',
    'est le plus doué pour jouer au chat et à la souris en amour',
    'a déjà menti sur sa présence à une soirée pour éviter un ex',
    'a déjà dragué quelqu’un juste pour se prouver quelque chose',
    'a déjà dit à un ami que son ex ne le méritait pas, puis l’a regretté',
    'a déjà annulé un plan entre amis pour un rendez-vous galant',
    'a déjà fait semblant de s’intéresser à quelqu’un pour ses amis',
    'a déjà gardé le numéro d’un inconnu rencontré en soirée sans jamais l’appeler',
    'a déjà sauté dans un taxi avec quelqu’un après la fermeture du bar',
    'a déjà prétendu être célibataire alors que la situation était floue',
    'est le plus susceptible de demander l’avis de tous sur sa relation',
    'a déjà pris la défense d’un ex que tout le monde détestait',
    'a déjà été le plus ému par une chanson qui parlait d’une rupture',
    'a déjà passé une soirée à éviter quelqu’un du regard',
    'est le plus enclin à tomber dans le piège des beaux parleurs',
    'a déjà fait un tour de piste avec un inconnu pour échapper à un casse-pieds',
    'a déjà trinqué à la santé d’un amour impossible',
    'est le plus susceptible d’avoir un ex qui le suit encore en ligne',
    'a déjà ressenti un pincement au cœur en voyant un ex heureux',
    'a déjà dit non à une demande en couple par peur de s’engager',
    'est le plus doué pour consoler un ami après une rupture',
    'a déjà vu un ami d’ici sous un jour très différent après quelques verres',
  ],
  hot: [
    'est le plus doué pour les baisers',
    'a déjà échangé des messages très osés',
    'envoie les messages les plus coquins',
    'a déjà fait quelque chose de très osé dans un lieu public',
    'serait le plus endiablé sous la couette',
    'a déjà eu un plan d’un soir dont il se souvient encore',
    'a déjà fantasmé sur quelqu’un d’ici',
    'a le fantasme le plus étonnant',
    'est le plus entreprenant au premier rendez-vous',
    'a déjà pensé à quelqu’un d’autre pendant un baiser',
    'a déjà dormi avec quelqu’un le soir même de leur rencontre',
    'est le plus pudique quand on parle de sexe',
    'est le moins pudique quand on parle de sexe',
    'a déjà été surpris dans une situation intime',
    'a déjà fait croire à une panne pour rester dormir chez quelqu’un',
    'porte la lingerie ou les sous-vêtements les plus audacieux',
    'a déjà envoyé une photo un peu trop dénudée à la mauvaise personne',
    'a déjà été attiré par un ami proche',
    'a déjà eu une attirance pour un collègue de travail',
    'a déjà fait un massage qui a pris une tournure inattendue',
    'aurait pu avoir une aventure avec quelqu’un de cette pièce',
    'a le plus de chances d’avoir déjà dragué un barman ou une barmaid pour une nuit',
    'est le plus doué pour les mots doux à l’oreille',
    'est le plus doué pour susciter le désir d’un simple regard',
    'a déjà embrassé quelqu’un d’ici',
    'a déjà failli embrasser quelqu’un d’ici',
    'est le plus joueur au lit',
    'aime le plus prendre les commandes',
    'aime le plus se laisser faire',
    'a déjà eu une relation purement physique',
    'a déjà eu une histoire avec une personne de son entourage et l’a cachée',
    'a déjà regretté une nuit avec quelqu’un',
    'a déjà passé un week-end entier à ne sortir que pour manger',
    'a déjà rougi en repensant à une nuit passée',
    'garde un secret très coquin',
    'a déjà fait un jeu de rôle',
    'a déjà essayé un jeu coquin avec son partenaire',
    'a déjà lu un livre érotique en cachette',
    'regarde les films les plus osés dans son historique',
    'a déjà fait croire qu’il avait une grande expérience',
    'a déjà été plus intimidé qu’il ne le dit lors d’une première nuit',
    'a déjà fait une soirée à deux qui a duré jusqu’au petit matin',
    'serait le plus romantique pour une nuit en amoureux',
    'ferait la meilleure surprise pour une soirée à deux',
    'a déjà dansé de façon très sensuelle devant tout le monde',
    'a déjà fait une danse sensuelle pour quelqu’un',
    'a déjà fait un strip-tease, même pour rire',
    'a déjà fait du charme à plusieurs personnes à la fois',
    'a déjà été attiré par quelqu’un à cause de son odeur',
    'est le plus tactile du groupe',
    'est le plus câlin avec son partenaire',
    'dort le plus souvent avec quelqu’un',
    'a déjà passé une nuit torride et n’a jamais rappelé',
    'est le plus doué pour la séduction à voix basse',
    'a déjà fait le plus long baiser de sa vie sur un coup de tête',
    'a déjà ressenti un frisson à cause d’un simple effleurement',
    'a déjà été séduit par un message écrit',
    'écrit les messages les plus enflammés',
    'a déjà fait une déclaration passionnée au mauvais moment',
    'a déjà eu un rendez-vous qui s’est terminé de façon inattendue',
    'est le plus joueur lors des soirées entre adultes',
    'a déjà été le plus embarrassé après une nuit un peu trop arrosée',
    'a déjà fait une folie le soir d’un anniversaire',
    'serait le plus déchaîné à un enterrement de vie de garçon ou de jeune fille',
    'a déjà rêvé d’une nuit avec quelqu’un d’ici',
    'a déjà découvert un nouveau côté de lui lors d’une nuit',
    'aime que son partenaire lui murmure des mots coquins',
    'aime murmurer des mots coquins',
    'a déjà été surpris par une attirance soudaine',
    'est le plus enclin à tenter une expérience nouvelle',
    'a déjà été très gêné par un message trop osé reçu par erreur',
    'a déjà fait croire qu’il dormait pour éviter une situation intime',
    'a déjà été arrêté net par un ami au moment d’un baiser',
    'a déjà fait un câlin qui a duré beaucoup plus longtemps que prévu',
    'serait le plus imaginatif pour un rendez-vous romantique',
    'a le plus de chances d’avoir déjà essayé l’amour dans un lieu insolite',
    'a déjà été séduit par une voix',
    'aimerait avoir une aventure de vacances',
    'a déjà eu une aventure de vacances',
    'a déjà ramené quelqu’un chez lui sans prévenir son colocataire',
    'a déjà été réveillé par un message coquin',
    'a déjà envoyé un message coquin au mauvais moment',
    'est le plus naturel avec son propre corps',
    'est le plus complexé par son image sous la couette mais ne le dit pas',
    'a un passé plus aventurier que ce qu’il dit',
    'a déjà été intrigué par la vie intime d’un ami',
    'est le plus curieux de la vie intime des autres',
    'est le plus bavard sur sa vie intime',
    'a déjà été le sujet d’une rumeur coquine',
    'est le plus doué pour garder les secrets de chambre',
    'a déjà fait semblant d’être plus expérimenté qu’il ne l’est',
    'aurait pu être un grand séducteur dans une autre vie',
    'a déjà été surpris à regarder quelqu’un avec insistance',
    'est celui dont le sourire fait le plus d’effet',
    'a déjà fait rougir quelqu’un avec un compliment',
    'est le plus enclin à faire un compliment audacieux',
    'a déjà passé une nuit entière à discuter qui s’est terminée par un baiser',
    'a déjà été séduit par quelqu’un d’un tout autre milieu',
    'a déjà eu un moment gênant avec un voisin ou une voisine',
    'a déjà été attiré par une personne plus âgée que lui',
    'a déjà été attiré par une personne plus jeune que lui, majeure bien sûr',
    'est le plus susceptible de faire une demande en mariage après une nuit',
    'a déjà cédé après avoir dit que non',
    'a déjà repoussé un rendez-vous par peur de ses sentiments',
    'a déjà fait de la danse très rapprochée au milieu d’une foule',
    'a déjà gardé un souvenir précieux d’une nuit',
    'a déjà été accusé de faire du charme alors qu’il ne faisait rien',
    'a déjà vu quelqu’un d’ici dans une tenue plus légère que prévu',
    'est le plus enclin à faire le premier pas sous la couette',
    'a déjà été interrompu par quelqu’un dans un moment intime',
    'a déjà fait croire qu’il était fatigué pour éviter une nuit',
    'a déjà été frustré par une première nuit décevante',
    'a déjà eu une première fois dont il rit encore',
    'a déjà fait un fou rire en pleine intimité',
    'a le plus de chances de tomber dans les bras d’un ami en soirée',
    'a déjà été tenté par quelqu’un qui était en couple',
    'a déjà été tenté d’envoyer un message très osé à quelqu’un d’ici',
    'a déjà gardé une photo coquine de quelqu’un',
    'a déjà demandé à quelqu’un de supprimer une photo osée',
    'a déjà eu une idylle secrète avec quelqu’un de son travail',
    'est le plus charmeur après minuit',
    'est le plus chaud lapin du groupe',
    'est le plus coquin sous ses airs sages',
    'a déjà dit un mot doux à voix haute dans son sommeil',
    'serait le plus doué pour un slow collé-serré',
    'a déjà fait un baiser volé dans l’obscurité',
    'a déjà été séduit par un regard dans le métro',
    'a déjà passé une nuit blanche avec quelqu’un sans dormir une seule minute',
    'a déjà embrassé un ami pour un pari',
    'a déjà été embrassé par surprise',
    'est le plus chanceux en amour',
    'est le plus malchanceux en amour',
    'a déjà regretté de ne pas avoir osé un baiser',
    'a déjà craqué pour un ami d’un ami après une soirée',
    'a déjà passé une soirée entière à échanger des regards avec quelqu’un',
    'a déjà été troublé par un contact de main',
    'a déjà été ébloui par la tenue de quelqu’un d’ici',
    'a déjà ressenti de l’attirance pour une personne dont il ne connaissait pas le prénom',
    'dirait oui à une nuit avec une star du cinéma',
    'a déjà fait un rêve qu’il n’oserait jamais raconter',
    'a déjà trouvé quelqu’un d’ici irrésistible en maillot de bain',
    'a déjà fait du charme à quelqu’un d’ici lors d’un voyage',
    'a déjà failli être surpris pendant un baiser enflammé',
    'aime le plus les surprises coquines',
    'aime le plus les longs préliminaires',
    'est le plus pressé en amour',
    'est le plus patient en amour',
    'a déjà essayé un déguisement coquin',
    'a déjà offert un cadeau très osé',
    'a déjà reçu un cadeau coquin et ne l’a dit à personne',
    'est le plus tenté par un bain à deux',
    'est le plus tenté par une nuit improvisée sur un coup de tête',
    'a déjà mis de la musique pour séduire',
    'a déjà fait un massage à un ami',
    'a déjà rêvé d’un week-end romantique avec quelqu’un d’ici',
    'a déjà été complice d’un jeu de séduction entre deux amis',
    'est le plus doué pour deviner qui plaît à qui',
    'a déjà passé un temps fou à lire un message de séduction avant de l’envoyer',
    'est le plus enclin à avouer son attirance à quelqu’un',
    'a déjà été sujet de convoitise dans une soirée',
    'a déjà fait languir quelqu’un volontairement',
    'a déjà été dans une situation compromettante sans que personne ne le sache',
    'a un petit secret coquin que personne n’a jamais deviné',
    'est celui dont le charme est le plus dangereux',
    'est le plus tenté par le fruit défendu',
    'a déjà été surpris en train de sourire en lisant un message coquin',
    'a déjà fait une nuit que personne n’a jamais soupçonnée',
    'a déjà gardé la nuit d’avant secrète à son meilleur ami',
    'est le plus mauvais pour cacher son attirance',
    'a déjà envoyé un message très enflammé en pleine nuit',
    'est celui dont on parle le plus à voix basse en soirée',
  ],
}
