import type { Level } from '../engine'

/** Petit Bac — catégories tirées au hasard à chaque manche. */
export const petitBacCategories: Record<Level, string[]> = {
  soft: [
    // Classiques
    'Pays',
    'Prénom féminin',
    'Prénom masculin',
    'Animal',
    'Fruit ou légume',
    'Métier',
    'Marque',
    'Ville',
    'Capitale',
    'Fleuve ou rivière',
    'Sport',
    'Instrument de musique',
    'Couleur ou nuance',
    'Vêtement',
    'Meuble',
    'Nom de famille',
    'Célébrité',
    'Partie du corps',
    'Moyen de transport',
    'Matière scolaire',
    'Langue ou dialecte',
    'Monnaie',
    'Montagne ou massif',
    'Île',
    'Planète, étoile ou astre',
    'Phénomène météo',
    'Département ou région française',
    'Ville du monde',
    'Monument ou lieu touristique',
    'Pièce d’une maison',
    'Magasin ou commerce',
    'Bâtiment',
    // Cuisine
    'Objet qu’on trouve dans une cuisine',
    'Plat cuisiné',
    'Dessert',
    'Fromage',
    'Boisson sans alcool',
    'Boisson chaude',
    'Pâtisserie',
    'Bonbon ou friandise',
    'Épice ou herbe aromatique',
    'Sauce ou condiment',
    'Viande ou poisson',
    'Céréale ou féculent',
    'Entrée',
    'Sandwich ou fast-food',
    'Plat du monde',
    'Plat d’hiver',
    'Plat d’été',
    'Parfum de glace ou de sorbet',
    'Aliment du petit-déjeuner',
    'Ustensile de cuisine',
    'Appareil électroménager',
    'Marque de nourriture ou de boisson',
    // Culture et divertissement
    'Film',
    'Chanson',
    'Série télé',
    'Émission de télé',
    'Jeu vidéo',
    'Jeu de société',
    'Livre',
    'Écrivain',
    'Peintre ou artiste',
    'Chanteur ou chanteuse',
    'Acteur ou actrice',
    'Groupe de musique',
    'Style de musique',
    'Danse',
    'Application sur un téléphone',
    'Chaîne ou site internet',
    'Jouet',
    'Jeu de récré',
    'Hobby ou passe-temps',
    'Loisir créatif',
    // Personnages
    'Personnage de dessin animé',
    'Super-héros ou méchant',
    'Personnage de conte de fées',
    'Personnage de Disney',
    'Personnage historique',
    'Monstre ou créature imaginaire',
    'Personnage de film d’animation',
    'Sportif célèbre',
    'Équipe de sport',
    // Nature
    'Fleur',
    'Arbre ou plante',
    'Oiseau',
    'Poisson ou fruit de mer',
    'Insecte',
    'Animal de la ferme',
    'Animal sauvage',
    'Nom d’animal de compagnie',
    'Race de chien ou de chat',
    'Élément de la nature',
    // Les « choses qu’on trouve »
    'Chose qu’on trouve dans un sac à main',
    'Chose qu’on trouve dans une trousse',
    'Chose qu’on trouve dans une salle de bain',
    'Chose qu’on trouve dans une chambre',
    'Chose qu’on trouve à la plage',
    'Chose qu’on emporte en vacances',
    'Chose qu’on trouve dans un jardin',
    'Chose qu’on trouve dans une voiture',
    'Chose qu’on trouve à l’école',
    'Chose qu’on trouve dans un frigo',
    'Chose qu’on trouve dans une valise',
    'Chose qu’on trouve dans un placard',
    'Chose qu’on trouve dans un supermarché',
    'Chose qu’on trouve dans une ferme',
    'Chose qu’on trouve au bureau',
    'Chose qu’on trouve dans une forêt',
    'Chose qu’on trouve dans une boîte à outils',
    'Chose qu’on trouve dans un zoo',
    'Chose qu’on trouve à l’hôpital',
    'Chose qu’on trouve dans un salon',
    'Chose qu’on trouve dans un garage',
    'Chose qu’on trouve au cinéma',
    'Chose qu’on trouve dans un train',
    'Chose qu’on trouve dans un parc',
    'Chose qu’on garde dans un tiroir',
    'Chose qu’on voit dans le ciel',
    'Chose qu’on voit dans la rue',
    'Chose qu’on trouve dans l’eau',
    'Chose qu’on trouve en montagne',
    'Chose qu’on voit en été',
    'Chose qu’on voit en hiver',
    // Les « choses qui… »
    'Chose qui roule',
    'Chose ronde',
    'Chose qui fait du bruit',
    'Chose chaude',
    'Chose froide',
    'Chose collante',
    'Chose qui brille',
    'Chose qui se plie',
    'Chose qui vole',
    'Chose qui coupe',
    'Chose qui s’ouvre et se ferme',
    'Chose qui sent bon',
    'Chose qui sent mauvais',
    'Chose qui se mange avec les doigts',
    'Chose très grande',
    'Chose minuscule',
    'Chose rouge',
    'Chose verte',
    'Chose jaune',
    'Chose bleue',
    'Chose blanche',
    'Chose noire',
    'Chose en bois',
    'Chose en plastique',
    'Chose en verre',
    'Chose en papier',
    // Vie quotidienne
    'Chose qu’on peut perdre',
    'Chose qu’on peut casser',
    'Chose qu’on peut cacher',
    'Chose qu’on peut offrir',
    'Chose qu’on peut collectionner',
    'Chose qu’on porte sur la tête',
    'Chose qu’on porte aux pieds',
    'Chose qui énerve',
    'Chose qu’on adore',
    'Chose qu’on déteste',
    'Chose dont on a peur',
    'Cadeau d’anniversaire',
    'Cadeau de Noël',
    'Fête ou célébration',
    'Déguisement',
    'Activité de vacances',
    'Activité du dimanche',
    'Destination de rêve',
    'Lieu de vacances',
    'Outil',
    'Accessoire de mode',
    'Chaussure',
    'Tissu ou matière',
    'Objet décoratif',
    'Fournitures scolaires',
    'Objet high-tech',
    'Sport d’équipe',
    'Sport d’hiver',
    'Sport nautique',
    // Mots et expressions
    'Verbe d’action',
    'Adjectif positif',
    'Qualité',
    'Défaut',
    'Émotion ou sentiment',
    'Trait de caractère',
    'Onomatopée',
    'Expression française',
    'Mot qui fait rire',
    'Mot qui fait peur',
    'Mot en anglais',
    // Humour
    'Excuse pour être en retard',
    'Excuse pour ne pas faire ses devoirs',
    'Excuse pour ne pas faire le ménage',
    'Insulte gentille',
    'Surnom affectueux',
    'Surnom pour un ami',
    'Prénom de bébé original',
    'Prénom de grand-mère',
    'Nom de bateau',
    'Nom de restaurant rigolo',
    'Truc qu’on fait quand on s’ennuie',
  ],

  spicy: [
    // Alcool et apéro
    'Cocktail',
    'Marque de bière',
    'Vin ou cépage',
    'Alcool fort',
    'Marque d’alcool',
    'Marque de champagne',
    'Région viticole',
    'Apéritif',
    'Ingrédient de cocktail',
    'Fruit dans un cocktail',
    'Chose qu’on grignote à l’apéro',
    'Boisson de soirée',
    'Verre ou récipient pour boire',
    'Toast ou façon de trinquer',
    'Remède contre la gueule de bois',
    'Fast-food de fin de soirée',
    'Chose qu’on mange à 3 h du matin',
    'Chose qu’on dit en trinquant',
    // Soirée
    'Type de soirée',
    'Lieu de soirée',
    'Boîte de nuit ou bar',
    'Nom de bar rigolo',
    'Chanson de boîte de nuit',
    'Chanson qui fait danser',
    'Chanson à chanter au karaoké',
    'Danse de soirée',
    'Jeu à boire',
    'Jeu de soirée',
    'Défi ou gage',
    'Gage honteux',
    'Tenue de soirée',
    'Accessoire de soirée',
    'Chose qu’on trouve dans un sac de soirée',
    'Chose qu’on oublie en sortant',
    'Chose qu’on perd en soirée',
    'Invité pénible en soirée',
    'Type de personne en soirée',
    'Mauvaise décision de soirée',
    'Mauvaise idée à 3 h du matin',
    'Chose qu’on regrette le lendemain',
    'Chose qu’on fait trop saoul',
    'Chose qu’on dit quand on a trop bu',
    'Chose qu’on oublie après une soirée',
    'Chose qu’on retrouve dans sa poche le lendemain',
    'Endroit où on s’est réveillé sans savoir pourquoi',
    'Chose qu’on avoue après quelques verres',
    'Confidence entre amis',
    // Excuses et mensonges
    'Excuse bidon pour quitter une soirée',
    'Excuse pour ne pas répondre à un message',
    'Excuse pour poser un lapin',
    'Excuse pour rentrer tard',
    'Excuse pour ne pas aller au travail',
    'Excuse pour annuler un rendez-vous',
    'Excuse pour ne pas rester dormir chez quelqu’un',
    'Mensonge qu’on dit à ses parents',
    'Mensonge de drague',
    'Mensonge sur un profil de rencontre',
    'Chose qu’on dit pour se faire pardonner',
    'Façon de s’excuser',
    // Drague
    'Phrase d’accroche',
    'Réplique de drague',
    'Mauvaise phrase de drague',
    'Technique de drague',
    'Cliché de la drague',
    'Mot doux',
    'Lieu pour un premier rendez-vous',
    'Truc qui fait fuir en rendez-vous',
    'Signe qu’il faut partir d’un rendez-vous',
    'Qualité qu’on cherche chez un partenaire',
    'Défaut rédhibitoire',
    'Émoji qu’on envoie à son crush',
    'Message à envoyer à son crush',
    'Célébrité qu’on trouve canon',
    'Star de cinéma qu’on aimerait croiser',
    'Marque de parfum',
    'Chose qui rend jaloux',
    // Applis de rencontre
    'Appli de rencontre',
    'Prénom sur une appli de rencontre',
    'Phrase de profil de rencontre',
    'Hobby sur un profil de rencontre',
    // Couple
    'Activité en amoureux',
    'Cadeau de Saint-Valentin',
    'Film romantique',
    'Chanson d’amour',
    'Source de dispute dans un couple',
    'Dispute de couple absurde',
    'Mauvaise habitude de couple',
    'Chose qu’on partage en couple',
    'Chose qu’on ne partage jamais en couple',
    'Chose qui prouve qu’on est en couple',
    'Chose qu’on trouve chez un célibataire',
    'Plat romantique',
    'Fleur à offrir',
    'Destination romantique',
    'Lieu de lune de miel',
    'Cadeau de mariage',
    'Chanson de mariage',
    'Chose qu’on voit à un mariage',
    'Couple célèbre',
    'Couple de cinéma',
    // Ex
    'Prénom d’ex',
    'Défaut d’un ex',
    'Raison de rupture',
    'Chanson de rupture',
    'Phrase de rupture',
    'Chose qu’on garde d’un ex',
    'Cadeau nul d’un ex',
    // Gênes et secrets
    'Chose gênante',
    'Moment gênant',
    'Situation de honte',
    'Mot qu’on dit quand on est gêné',
    'Chose qui fait rougir',
    'Chose qu’on fait en cachette',
    'Petit secret inavouable',
    'Chose qu’on cache à ses parents',
    'Défaut qu’on cache',
    'Vice ou mauvaise habitude',
    'Péché mignon',
    'Plaisir coupable télé',
    'Mauvaise habitude à table',
    // Potins et télé
    'Émission de télé-réalité',
    'Candidat de télé-réalité',
    'Scandale de célébrité',
    'Ragot ou potin',
    'Sujet de commérage',
    'Sujet tabou au repas de famille',
    'Chose qu’on ne dit jamais à sa belle-mère',
    // Insultes
    'Gros mot ou juron',
    'Insulte rigolote',
    'Insulte originale',
    'Surnom moqueur',
    'Nom d’animal pour insulter quelqu’un',
    // Travail
    'Type de collègue pénible',
    'Chose qu’on fait en cachette au travail',
    'Chose qu’on rêve de dire à son patron',
    'Cadeau de pot de départ',
    'Excuse pour finir plus tôt',
    'Prétexte pour sortir d’une réunion',
    'Mensonge de CV',
    // Divers
    'Chose qu’on fait avant de sortir',
    'Chose qu’on fait après un verre',
    'Mot qui sonne comme un reproche',
    'Prénom de star',
    'Prénom mixte',
    'Pseudo ridicule',
    'Nom de groupe de potes',
    'Nom de groupe WhatsApp',
    'Phrase qui annonce une mauvaise nouvelle',
    'Chose qui fait fuir tout le monde',
    'Chose qu’on fait sans se faire voir',
    'Mauvaise surprise',
    'Raison de ne pas rentrer chez soi',
    'Défi qu’on relève pour une bière',
    'Mot qu’on dit au réveil après une grosse soirée',
    'Chose qu’on fait pour impressionner son crush',
    'Mauvais cadeau de la Saint-Valentin',
    'Chose qu’on fait en soirée pour se donner du courage',
    'Chose qu’on poste après une soirée',
    'Raison de bloquer quelqu’un',
    'Chose qu’on stalke sur un profil',
    'Sujet de conversation gênant',
    'Chose qui prouve qu’on a trop bu',
    'Chose qu’on dit à un inconnu en boîte',
  ],

  hot: [
    // Séduction
    'Surnom coquin',
    'Endroit insolite pour s’embrasser',
    'Accessoire de séduction',
    'Mot qu’on chuchote à l’oreille',
    'Cachette pour un baiser discret',
    'Lieu pour un rendez-vous secret',
    'Lieu d’un premier baiser',
    'Endroit où on a peur de se faire surprendre',
    'Excuse après avoir été surpris en train de s’embrasser',
    'Technique de séduction',
    'Façon de regarder quelqu’un pour le séduire',
    'Phrase d’accroche coquine',
    'Début de texto coquin',
    'Émoji coquin',
    'Compliment qui fait fondre',
    'Mot d’amour dans une autre langue',
    'Euphémisme pour parler de l’amour',
    'Adjectif pour décrire quelqu’un de séduisant',
    'Verbe de séduction',
    'Verbe qui se fait à deux',
    'Surnom pour un homme séduisant',
    'Surnom pour une femme séduisante',
    'Pseudo pour appli de rencontre coquine',
    'Chose qu’on fait pour séduire',
    'Chose qui rend irrésistible',
    'Préparatif avant un rendez-vous galant',
    // Physique
    'Partie du corps qui fait craquer',
    'Zone sensible',
    'Détail physique qui fait craquer',
    'Petit défaut qui rend irrésistible',
    'Qualité séduisante',
    'Accent qui fait fondre',
    'Langue qui fait craquer',
    'Voix qui fait craquer',
    'Prénom sensuel',
    'Prénom qui fait craquer',
    'Sport qui sculpte le corps',
    'Type de massage',
    'Produit de massage',
    'Chose qu’on trouve dans un spa',
    'Chose pour un bain à deux',
    // Tenues
    'Pièce de lingerie',
    'Sous-vêtement',
    'Vêtement qu’on enlève en premier',
    'Vêtement qui flatte',
    'Tissu sensuel',
    'Déguisement sexy',
    'Uniforme qui fait craquer',
    'Tenue qui fait craquer',
    'Détail de tenue qui fait craquer',
    'Chaussure qui fait de l’effet',
    'Bijou qui fait de l’effet',
    'Couleur de rouge à lèvres',
    'Marque de lingerie ou de maillot de bain',
    'Vêtement à perdre au strip-poker',
    // Ambiance
    'Parfum qui rend fou',
    'Parfum de bougie',
    'Chose qui crée l’ambiance',
    'Chanson sensuelle',
    'Chanson pour un slow',
    'Chanson qui donne envie de séduire',
    'Style de musique pour une soirée intime',
    'Instrument de musique sensuel',
    'Danse sensuelle',
    'Danse à deux',
    'Fleur qui évoque la passion',
    'Chose rouge et sensuelle',
    'Plat pour un dîner aux chandelles',
    'Boisson pour séduire',
    'Aliment aphrodisiaque',
    'Aliment sensuel',
    'Dessert à partager à deux',
    // Baisers et caresses
    'Type de baiser',
    'Façon d’embrasser',
    'Geste tendre',
    'Caresse',
    'Moment pour un câlin',
    'Façon de réveiller son partenaire',
    'Chose qu’on fait sous la couette',
    'Chose qu’on fait à deux sous la douche',
    'Chose qu’on trouve dans un lit',
    'Objet qui traîne sur une table de chevet',
    'Chose cachée dans un tiroir de chevet',
    'Chose qu’on cache sous son oreiller',
    // Jeux et défis
    'Jeu coquin',
    'Jeu à deux',
    'Jeu de cartes ou de société pour couples',
    'Défi coquin',
    'Gage coquin',
    'Question coquine pour Action ou Vérité',
    'Chose à faire avec du chocolat',
    'Chose à faire avec une plume',
    'Chose à faire les yeux bandés',
    'Cadeau coquin',
    'Cadeau pour pimenter la soirée',
    'Surprise pour son partenaire',
    'Idée pour pimenter un couple',
    // Fantasmes et pensées
    'Fantasme avouable',
    'Pensée qui fait rougir',
    'Pensée coquine',
    'Rêve qui ne se raconte pas',
    'Aveu sur l’oreiller',
    'Métier qui fait fantasmer',
    'Célébrité sur laquelle on fantasme',
    'Acteur ou actrice qui fait rêver',
    'Personnage de fiction séduisant',
    'Scène de film qui fait monter la température',
    'Film sensuel',
    'Série sexy',
    'Péché capital',
    'Personnage mythologique séduisant',
    'Histoire d’amour célèbre',
    'Poète ou écrivain romantique',
    'Chanteur ou chanteuse sexy',
    // Lieux
    'Lieu où on a envie de s’isoler à deux',
    'Endroit pour un câlin en vacances',
    'Type d’hébergement pour une nuit coquine',
    'Destination pour une escapade coquine',
    'Ville romantique',
    'Pays réputé pour ses amants',
    'Lieu romantique dans le monde',
    // Sensations
    'Chose douce au toucher',
    'Chose brûlante',
    'Chose qui chatouille',
    'Chose qui fait frissonner',
    'Chose qui fait battre le cœur plus vite',
    'Chose qui fait fondre',
    'Chose qu’on garde secrète',
    'Chose qu’on n’ose pas demander',
    'Chose qu’on rêve de se faire dire',
    'Mot qui sonne sensuel',
    'Chose qu’on fait au clair de lune',
    'Lieu pour un câlin sous les étoiles',
    'Moment de la journée pour un baiser',
    'Surnom pour son partenaire sous la couette',
    'Compliment sur le corps',
    'Tatouage sexy',
    'Parfum de gel douche',
    'Façon de dire « j’ai envie de toi » sans le dire',
    'Geste qui trahit l’attirance',
    'Signe qu’on plaît à quelqu’un',
    'Chose qu’on fait pour attirer l’attention de son crush',
    'Lieu pour un baiser volé au bureau',
    'Tenue de nuit',
    'Couleur de sous-vêtement',
    'Accessoire de couple',
    'Chose qu’on fait pendant un massage',
    'Parfum d’ambiance',
    'Personnage à incarner dans un jeu de rôle',
    'Prénom de premier amour',
    'Chose qu’on fait avant un baiser',
    'Chose qu’on fait après un baiser',
    'Réplique de film qui fait fondre',
    'Livre romantique ou sensuel',
    'Chose qu’on se dit à voix basse',
    'Chose qu’on fait en cachette à deux',
    'Chose dans un pique-nique romantique',
    'Activité à deux au bord de la mer',
    'Chose à faire sous la pluie à deux',
    'Erreur à éviter un soir de séduction',
    'Cadeau pour se faire pardonner',
    'Mot qui commence une déclaration',
    'Chose qui donne chaud aux joues',
    'Lieu pour un slow improvisé',
    'Chose qui donne envie de se rapprocher',
    'Boisson chaude à partager à deux',
    'Plaisir interdit',
  ],
}
