import type { Level } from '../engine'

/** Défis express — règles et mini-défis pour tout le groupe. */
export const quickDares: Record<Level, string[]> = {
  soft: [
    'Le dernier à toucher son nez choisit la prochaine musique.',
    'Tout le monde montre la dernière photo de sa galerie.',
    'Jusqu’à la prochaine carte, interdit de dire « oui ».',
    'Ceux qui portent du noir font 10 squats.',
    'Le plus jeune choisit la prochaine musique.',
    'Le dernier qui lève la main en l’air raconte une anecdote sur son enfance.',
    'Tout le monde imite un animal au choix. Le public vote pour le plus convaincant.',
    'Jusqu’à la prochaine carte, interdit de dire « non ».',
    'Ceux qui ont déjà cassé un téléphone font un tour d’applaudissements pour les autres.',
    'Chacun cite à son tour une marque de céréales. Le premier qui hésite perd.',
    'Le dernier à se lever fait un compliment sincère à la personne à sa droite.',
    'Tout le monde chante le refrain d’une chanson de son enfance, en même temps.',
    'Ceux qui ont des chaussettes dépareillées sont déclarés rois et reines de la soirée.',
    'Jusqu’à la prochaine carte, tout le monde parle avec l’accent de son choix.',
    'Le dernier qui touche une chaise donne un gage au groupe.',
    'Chacun cite à son tour un fruit exotique. Le premier qui répète ou hésite perd.',
    'Tout le monde pose son téléphone au centre. Le premier qui le reprend raconte une honte de collège.',
    'Ceux qui sont nés en été échangent leur place avec quelqu’un d’autre.',
    'Le dernier à faire un pouce en l’air choisit le prochain thème de conversation.',
    'Tout le monde mime son métier ou ses études. Les autres devinent.',
    'Jusqu’à la prochaine carte, il faut finir chaque phrase par « n’est-ce pas ».',
    'Ceux qui ont déjà raté un train ou un bus font un tour de salle en marche rapide.',
    'La personne la plus grande du groupe choisit un gage doux pour la plus petite.',
    'Chacun cite à son tour une capitale. Le premier qui hésite perd.',
    'Tout le monde montre son fond d’écran. Le plus original gagne un applaudissement.',
    'Le dernier qui touche ses oreilles raconte son plus beau souvenir de vacances.',
    'Ceux qui aiment les ananas sur la pizza se lèvent et défendent leur position en 10 secondes.',
    'Jusqu’à la prochaine carte, tout le monde se vouvoie.',
    'Tout le monde ferme les yeux et, à trois, montre du doigt la personne la plus drôle.',
    'Le premier qui rit dans les 30 prochaines secondes raconte une blague.',
    'Ceux qui ont un animal de compagnie montrent sa photo à tout le groupe.',
    'Chacun cite à son tour un dessin animé. Le premier qui hésite perd.',
    'Le dernier qui touche son genou choisit un jeu de mots à faire dire à quelqu’un.',
    'Tout le monde fait sa meilleure grimace en même temps. Le groupe élit la plus réussie.',
    'Jusqu’à la prochaine carte, interdit de montrer quelqu’un du doigt.',
    'Ceux qui sont gauchers lèvent le bras gauche et choisissent la prochaine carte.',
    'Chacun dit à son tour sa plus grande peur d’enfance, en une phrase.',
    'Le dernier à se tenir sur un pied donne un gage au groupe.',
    'Tout le monde échange son accessoire préféré avec son voisin pendant trois tours.',
    'Ceux qui ont déjà gagné un trophée ou une médaille le racontent en 10 secondes.',
    'Jusqu’à la prochaine carte, tout le monde parle en chuchotant.',
    'La personne à gauche du lecteur invente un surnom pour chaque joueur.',
    'Chacun cite à son tour un animal commençant par la même lettre que son prénom.',
    'Tout le monde danse 15 secondes sur une musique imaginaire.',
    'Le dernier qui croise les bras fait rire le groupe avec une imitation.',
    'Ceux qui ont déjà fait du théâtre jouent une courte scène de dispute à propos d’une chaussette.',
    'Jusqu’à la prochaine carte, il faut commencer chaque phrase par « Franchement ».',
    'Tout le monde montre son dernier emoji utilisé. Le plus étrange est élu.',
    'Chacun cite à son tour un film d’animation. Le premier qui répète perd.',
    'Le plus âgé du groupe choisit qui raconte la prochaine histoire drôle.',
    'Ceux qui ont déjà dormi sous une tente font un tour d’applaudissements.',
    'Tout le monde dit en même temps son plat préféré. Les points communs gagnent.',
    'Le dernier qui dit « moi » en premier donne un gage au groupe.',
    'Jusqu’à la prochaine carte, tout le monde doit marcher en petits pas.',
    'Chacun invente un slogan pour la personne à sa droite.',
    'Ceux qui ont déjà pleuré devant un dessin animé se lèvent et en citent un.',
    'Tout le monde fait semblant de jouer d’un instrument. Les autres devinent lequel.',
    'Le dernier qui montre trois doigts raconte son rêve le plus étrange.',
    'Chacun cite à son tour un sport. Le premier qui hésite ou répète perd.',
    'Jusqu’à la prochaine carte, interdit de dire le prénom de quelqu’un.',
    'Ceux qui aiment les films d’horreur poussent un cri de cinéma en même temps.',
    'Tout le monde doit trouver un objet de la pièce commençant par un « B ». Le dernier chante une comptine.',
    'La personne qui a le plus de batterie sur son téléphone choisit la prochaine carte.',
    'Chacun dit un mot gentil sur la personne en face de lui.',
    'Le dernier à poser la main sur la table doit raconter une manie bizarre.',
    'Ceux qui ont déjà oublié un anniversaire font un compliment à voix haute à quelqu’un.',
    'Jusqu’à la prochaine carte, tout le monde doit finir ses phrases en rimant si possible.',
    'Tout le monde dessine un chat dans l’air, les yeux fermés. On compare ensuite les talents.',
    'Chacun cite à son tour une série télé. Le premier qui hésite perd.',
    'Le dernier qui tape dans ses mains choisit une catégorie pour le prochain jeu de mémoire.',
    'Ceux qui ont une application de jeu sur leur téléphone montrent leur niveau.',
    'Tout le monde échange sa place avec la personne en face. Celui qui hésite fait un compliment.',
    'La personne la plus calme du groupe joue le rôle d’une présentatrice télé pendant 20 secondes.',
    'Jusqu’à la prochaine carte, interdit de dire « je » ou « moi ».',
    'Chacun cite à son tour une ville française. Le premier qui hésite perd.',
    'Le dernier qui fait une grimace raconte son meilleur souvenir d’école.',
    'Ceux qui sont déjà montés sur scène lèvent la main et saluent le public imaginaire.',
    'Tout le monde fait un selfie de groupe avec la grimace de son choix.',
    'Chacun invente un nom de super-héros pour la personne à sa gauche.',
    'Le dernier qui touche son coude avec sa main donne un gage au groupe.',
    'Ceux qui ont déjà mangé des escargots se lèvent et font semblant de ramper.',
    'Jusqu’à la prochaine carte, il faut ajouter « s’il vous plaît » à chaque demande.',
    'Tout le monde mime un sport en même temps. Les autres devinent les disciplines.',
    'La personne la plus récemment arrivée raconte comment elle a connu le groupe.',
    'Chacun cite à son tour un prénom d’animal de dessin animé. Le premier qui répète perd.',
    'Le dernier qui lève un genou choisit la prochaine musique.',
    'Ceux qui ont déjà gagné à un jeu de société citent leur victoire la plus fière.',
    'Tout le monde dit « bonjour » à la personne de son choix dans une langue différente.',
    'Jusqu’à la prochaine carte, tout le monde parle comme dans un documentaire animalier.',
    'Chacun montre l’application la plus utilisée de son téléphone.',
    'Le dernier qui touche un mur fait un tour d’applaudissements pour le groupe.',
    'Ceux qui ont déjà fait du vélo sans les mains lèvent les deux bras en l’air.',
    'Tout le monde choisit un mot interdit pour le voisin de droite, valable jusqu’à la prochaine carte.',
    'La personne qui a les cheveux les plus courts choisit qui raconte une histoire drôle.',
    'Chacun cite à son tour une couleur de la pièce. Le premier qui répète ou hésite perd.',
    'Le dernier qui dit « bravo » à voix haute doit faire rire le groupe avec une chanson.',
    'Ceux qui ont déjà raté un examen racontent comment ils ont rebondi, en une phrase.',
    'Jusqu’à la prochaine carte, interdit de dire « et ».',
    'Tout le monde mime un personnage de dessin animé. Les autres devinent à toute vitesse.',
    'Chacun dit à son tour sa saison préférée et une raison, en 5 secondes.',
    'Le dernier qui tire la langue choisit le thème de la prochaine blague.',
    'Ceux qui lisent des BD ou des mangas expliquent leur préférée en une phrase.',
    'Tout le monde échange son rôle de la soirée avec son voisin. Le plus drôle gagne.',
    'La personne à droite du lecteur choisit un mot que personne n’a le droit de dire.',
    'Jusqu’à la prochaine carte, il faut dire « chef » à la fin de chaque phrase.',
    'Chacun cite à son tour un objet qu’on trouve dans une cuisine. Le premier qui hésite perd.',
    'Le dernier qui montre ses deux mains vides raconte une peur ridicule.',
    'Ceux qui savent siffler sifflent la mélodie de leur choix. Les autres devinent.',
    'Tout le monde choisit un compliment bizarre à faire à son voisin, par exemple « tu as un excellent nom ».',
    'Chacun invente une phrase de pub pour un produit imaginaire.',
    'Le dernier qui touche ses chaussures donne un gage doux au groupe.',
    'Ceux qui ont déjà vu la mer cette année font un bruit de vague ensemble.',
    'Jusqu’à la prochaine carte, tout le monde salue d’un geste de la main avant de parler.',
    'La personne la plus bavarde du groupe se tait pendant deux tours.',
    'Chacun cite à son tour un animal de la ferme. Le premier qui répète perd.',
    'Tout le monde se met en cercle et applaudit en rythme. Celui qui se trompe chante.',
    'Le dernier qui touche le plafond du doigt, en pointant, raconte son meilleur cadeau.',
    'Ceux qui ont déjà adopté un nom d’emprunt sur internet le révèlent.',
    'Jusqu’à la prochaine carte, interdit de dire « merci », trouve d’autres façons.',
    'Tout le monde crée une poignée de main secrète avec son voisin de gauche.',
    'Chacun dit le premier mot qui lui vient en tête. Le plus original gagne.',
    'La personne la plus joyeuse du moment choisit la prochaine carte.',
    'Le dernier qui touche son menton choisit une personne qui doit faire une imitation.',
    'Ceux qui n’aiment pas les champignons s’affichent en levant le pouce vers le bas.',
    'Chacun cite à son tour un métier. Le premier qui hésite ou répète perd.',
    'Tout le monde mime la météo du jour. Les autres devinent le temps annoncé.',
    'Jusqu’à la prochaine carte, tout le monde se tient droit comme un robot.',
    'La personne qui a le plus de lettres dans son prénom raconte une anecdote sur celui-ci.',
    'Le dernier qui dit « stop » en premier choisit un thème de chanson.',
    'Ceux qui ont déjà gagné un concours de dessin dessinent un soleil avec le doigt dans l’air.',
    'Chacun cite à son tour une planète ou une étoile. Le premier qui répète perd.',
    'Tout le monde échange son verre ou son coussin avec celui d’une autre personne.',
    'Le plus calme du groupe raconte une anecdote en parlant très vite.',
    'Jusqu’à la prochaine carte, tout le monde doit parler en phrases de moins de six mots.',
    'Ceux qui ont déjà fait un feu de camp racontent leur meilleure histoire de camping.',
    'Chacun dit un compliment à la personne qui vient de parler.',
    'Le dernier qui touche sa montre ou son poignet donne un gage au groupe.',
    'Tout le monde dit à tour de rôle une qualité commençant par la première lettre de son prénom.',
    'Ceux qui sont déjà allés dans un parc d’attractions poussent un cri de montagnes russes.',
    'La personne qui a les plus grosses chaussures choisit un défi pour tout le groupe.',
    'Jusqu’à la prochaine carte, interdit de croiser les jambes.',
    'Chacun cite à son tour un jouet d’enfance. Le premier qui répète ou hésite perd.',
    'Le dernier qui fait un clin d’œil raconte son film préféré en trois mots.',
    'Tout le monde dessine un portrait de son voisin sur papier en 20 secondes. Le plus ressemblant gagne.',
    'Ceux qui ont déjà gagné une tombola lèvent la main et racontent leur lot.',
    'Chacun invente un proverbe absurde et le dit avec sérieux.',
    'Jusqu’à la prochaine carte, tout le monde parle comme un présentateur de journal télé.',
    'La personne la plus matinale du groupe donne une astuce pour se réveiller.',
    'Le dernier qui lève la jambe droite choisit la prochaine blague.',
    'Ceux qui ont déjà appris une langue étrangère disent « merci » dans cette langue.',
    'Tout le monde nomme son film de Noël préféré en même temps.',
    'Chacun cite à son tour un bruit de la nature. Le premier qui répète perd.',
    'Le dernier qui sourit à son voisin raconte son pire fou rire.',
    'Ceux qui ont déjà voyagé en avion lèvent les bras comme des ailes.',
    'Jusqu’à la prochaine carte, il faut chuchoter en finissant ses phrases.',
    'La personne qui a le prénom le plus long le dit à l’envers.',
    'Tout le monde choisit un mot inventé et l’utilise dans une phrase.',
    'Chacun cite à son tour un jour de la semaine et ce qu’il aime y faire.',
    'Le dernier qui touche ses cheveux donne un gage au groupe.',
    'Ceux qui ont déjà organisé un anniversaire surprise se lèvent et crient « surprise ! ».',
    'Jusqu’à la prochaine carte, tout le monde applaudit avant de parler.',
    'Chacun se coiffe d’un objet de la pièce et prend la pose. Le plus drôle gagne.',
    'La personne la plus petite du groupe choisit un fou rire à provoquer.',
    'Chacun montre son plus beau sourire de photo de classe.',
    'Le dernier qui touche son épaule donne un gage au groupe.',
    'Ceux qui aiment le chocolat chaud se lèvent et le crient en même temps.',
    'Tout le monde mime une scène de film d’aventure, les autres devinent laquelle.',
    'Chacun cite à son tour un animal marin. Le premier qui hésite perd.',
    'Jusqu’à la prochaine carte, interdit de dire « ah » ou « euh ».',
    'La personne à gauche du lecteur choisit qui doit se lever et saluer le groupe.',
    'Le dernier qui touche son téléphone raconte un souvenir marquant de cette année.',
    'Ceux qui ont déjà visité un château font une révérence royale aux autres.',
    'Tout le monde choisit un fruit et l’imite pendant 10 secondes, les autres devinent.',
    'Chacun cite à son tour un mot qui rime avec « soleil ». Le premier à sécher perd.',
    'Le plus jeune choisit un jeu de mots que le plus âgé doit prononcer.',
    'Jusqu’à la prochaine carte, tout le monde termine ses phrases par « et voilà ».',
    'Ceux qui ont déjà organisé une fête se lèvent et reçoivent un tonnerre d’applaudissements.',
    'Chacun dit sa chanson du moment en chantonnant 5 secondes.',
    'Tout le monde fait un high five avec trois personnes différentes en moins de 10 secondes.',
    'Le dernier qui croise les doigts raconte ce qu’il rêve de faire cet été.',
  ],
  spicy: [
    'Le dernier à toucher son nez boit une gorgée ou révèle son dernier crush.',
    'Tout le monde pose son téléphone au centre. Le premier qui le reprend lit son dernier message envoyé.',
    'Jusqu’à la prochaine carte, interdit de dire « je t’aime » même en plaisantant.',
    'Ceux qui ont déjà envoyé un message à leur ex à minuit boivent une gorgée.',
    'Chacun cite à son tour une marque de bière ou de cocktail. Le premier qui hésite boit ou fait un gage.',
    'Tout le monde vote à main levée pour la personne la plus susceptible de finir en after.',
    'Ceux qui ont déjà eu un crush sur un ami du groupe se lèvent sans dire de qui.',
    'Le dernier qui touche une bouteille raconte sa pire gueule de bois.',
    'Jusqu’à la prochaine carte, il faut finir chaque phrase par « si tu veux savoir ».',
    'Tout le monde montre la dernière personne à qui il a écrit. Les autres devinent le contexte.',
    'Ceux qui ont déjà ghosté quelqu’un lèvent la main et expliquent pourquoi.',
    'Chacun dit à son tour un défaut qu’il trouve charmant chez les autres.',
    'La personne qui a le plus d’ex dans ce groupe donne un conseil de rupture.',
    'Le dernier qui dit « moi » raconte son pire rendez-vous.',
    'Ceux qui ont déjà dragué dans un bar font le même regard de chasseur pendant 5 secondes.',
    'Tout le monde choisit qui serait le plus mauvais dragueur. Il fait une phrase d’accroche ratée.',
    'Jusqu’à la prochaine carte, tout le monde doit parler en demandant « tu viens souvent ici ? ».',
    'Chacun cite à son tour un lieu où il a déjà embrassé quelqu’un. Le premier qui répète boit ou passe.',
    'Le dernier qui touche son verre révèle son secret le plus anodin.',
    'Ceux qui ont déjà fait une soirée sans dormir lèvent la main et racontent le matin suivant.',
    'Tout le monde échange son téléphone avec son voisin pendant 30 secondes. Montrez seulement les photos autorisées.',
    'La personne à droite du lecteur choisit un secret léger à avouer à voix haute.',
    'Chacun lit son dernier SMS à voix haute, sauf si le contenu est privé, auquel cas il boit une gorgée.',
    'Ceux qui ont déjà menti pour éviter une sortie font semblant de tousser en chœur.',
    'Le dernier qui lève les deux mains raconte comment il a rencontré son dernier crush.',
    'Jusqu’à la prochaine carte, interdit de dire « ex » ou « crush ». Sinon, une gorgée.',
    'Tout le monde vote à main levée pour le meilleur danseur du groupe. Il fait une danse de 10 secondes.',
    'Chacun dit le prénom de l’ami avec qui il ferait le meilleur voyage. Sans justifier.',
    'Ceux qui ont déjà eu un coup de foudre au premier regard poussent un « ooh » collectif.',
    'Le dernier qui touche son cœur raconte son plus beau râteau.',
    'Tout le monde invente une chanson d’amour en dix secondes pour la personne à gauche.',
    'La personne la moins bavarde du groupe révèle un secret inoffensif.',
    'Jusqu’à la prochaine carte, il faut préciser « sans mauvaise intention » avant chaque phrase.',
    'Chacun cite à son tour un shot ou cocktail. Le premier qui hésite ou répète boit une gorgée ou donne un gage.',
    'Ceux qui ont déjà dansé sur une table se lèvent et font semblant de recommencer.',
    'Tout le monde montre son plus mauvais selfie de la semaine.',
    'Le dernier qui touche son téléphone avoue la dernière personne qu’il a stalkée.',
    'Ceux qui ont déjà fait semblant d’être occupé pour éviter quelqu’un lèvent la main.',
    'Chacun désigne celui qui a le plus de style. Les élus font un défilé de 10 secondes.',
    'La personne la plus romantique du groupe lit une phrase d’amour de son choix à voix haute.',
    'Jusqu’à la prochaine carte, tout le monde doit appeler les autres « mon chou ».',
    'Tout le monde vote : qui serait le plus susceptible d’oublier son téléphone en soirée ?',
    'Le dernier qui fait un clin d’œil à quelqu’un en face boit une gorgée ou chante une chanson d’amour.',
    'Ceux qui ont déjà dragué un serveur ou une serveuse boivent une gorgée.',
    'Chacun cite à son tour une raison de rupture absurde. Le premier qui répète perd.',
    'Tout le monde dit en même temps le prénom de la personne la plus fêtarde du groupe.',
    'La personne à gauche du lecteur doit avouer son plus gros mensonge de la semaine.',
    'Jusqu’à la prochaine carte, tout le monde doit faire un compliment avant de parler.',
    'Le dernier qui touche ses cheveux raconte son pire plan drague.',
    'Ceux qui ont déjà fait un « date » en secret se lèvent et font un clin d’œil à la salle.',
    'Chacun montre l’emoji qu’il envoie le plus à son crush ou à son ex.',
    'Tout le monde choisit un adjectif sympathique pour décrire la personne à sa droite.',
    'Ceux qui ont déjà rompu par message boivent une gorgée ou lèvent la main sans commenter.',
    'Le plus jeune choisit qui doit raconter son pire date.',
    'Jusqu’à la prochaine carte, tout le monde parle en chuchotant, comme dans un secret.',
    'Chacun cite à son tour une raison de swiper à gauche. Le premier qui hésite perd.',
    'Le dernier qui touche sa poche avoue ce qui s’y trouve en ce moment.',
    'Ceux qui ont déjà passé une nuit blanche en soirée lèvent la main et racontent le pire moment.',
    'Tout le monde vote à main levée pour le plus gros dormeur du groupe.',
    'La personne la plus timide du groupe choisit la prochaine question pour tous.',
    'Chacun fait son meilleur regard de séducteur pendant 5 secondes. Le groupe élit le plus convaincant.',
    'Jusqu’à la prochaine carte, interdit de rire. Celui qui rit boit une gorgée ou fait 5 sauts.',
    'Ceux qui ont déjà oublié le prénom d’un rendez-vous lèvent la main et grimacent.',
    'Le dernier qui touche son menton raconte une soirée où il a perdu quelque chose.',
    'Tout le monde dit une phrase d’accroche ridicule à la personne de son choix.',
    'Chacun désigne la personne qui a le plus de chance en amour. Les élus font une révérence.',
    'Ceux qui ont déjà fait un faux numéro à un inconnu lèvent la main.',
    'La personne qui est célibataire depuis le plus longtemps choisit un défi doux pour le groupe.',
    'Jusqu’à la prochaine carte, il faut commencer chaque phrase par « Entre nous… ».',
    'Chacun cite à son tour une chanson pour danser en slow. Le premier qui répète perd.',
    'Le dernier qui lève la main raconte son plus gros fou rire en soirée.',
    'Ceux qui ont déjà organisé une soirée qui a dégénéré lèvent la main et gardent le silence.',
    'Tout le monde choisit un nom de cocktail pour son voisin de gauche, avec une description.',
    'La personne la plus tardive à arriver aux soirées explique son excuse préférée.',
    'Chacun dit à son tour où il aimerait faire un premier rendez-vous idéal.',
    'Le dernier qui touche son verre trinque avec la personne de son choix et lui lance un compliment.',
    'Ceux qui ont déjà eu un ami qui a mal fini une soirée font un « oh non » de groupe.',
    'Jusqu’à la prochaine carte, tout le monde doit appeler son voisin de droite par un surnom mignon.',
    'Tout le monde échange un secret inoffensif avec la personne à sa droite, à voix basse.',
    'Chacun cite à son tour un truc qu’il ferait seulement quand il a un peu bu.',
    'Le dernier qui croise le regard de son voisin raconte ce qu’il pense en ce moment.',
    'Ceux qui ont déjà publié un story gênant lèvent la main et en citent le thème.',
    'La personne à gauche du lecteur choisit qui doit faire une déclaration d’amour à un objet.',
    'Tout le monde vote : qui serait le meilleur complice pour une bêtise ?',
    'Jusqu’à la prochaine carte, interdit de dire le prénom d’un ex.',
    'Chacun cite à son tour un défaut qu’il a en couple. Le premier qui hésite boit une gorgée.',
    'Le dernier qui touche le sol avec sa main raconte son pire message maladroit.',
    'Ceux qui ont déjà embrassé quelqu’un dans une soirée font un clin d’œil collectif.',
    'Tout le monde dit son pire défaut en une phrase, avec le sourire.',
    'La personne la plus jalouse du groupe choisit un secret que quelqu’un doit avouer.',
    'Chacun montre sa conversation la plus récente avec un ami, sans lire les messages. Les autres devinent le sujet.',
    'Jusqu’à la prochaine carte, il faut finir chaque phrase par « mais c’est un secret ».',
    'Le dernier qui lève son verre dit un vœu pour la soirée.',
    'Ceux qui ont déjà menti sur leur âge lèvent la main et sourient.',
    'Tout le monde fait semblant d’être au téléphone avec son crush pendant 15 secondes.',
    'Chacun cite à son tour une activité de premier rendez-vous. Le premier qui répète perd.',
    'La personne la plus sage du groupe raconte sa plus grosse folie.',
    'Le dernier qui touche son nez avoue ce qui lui a le plus plu chez la dernière personne rencontrée.',
    'Ceux qui ont déjà eu un faux départ en couple font un clap de fin.',
    'Jusqu’à la prochaine carte, tout le monde doit parler comme un héros de série romantique.',
    'Tout le monde vote pour la personne qui a le plus de succès. Elle partage son secret.',
    'Chacun lit à voix haute le dernier message envoyé à un proche. Les secrets passent leur tour en buvant une gorgée.',
    'Le dernier qui touche sa chaise doit se confesser sur une honte de soirée.',
    'Ceux qui ont déjà dit « je t’aime » trop vite lèvent la main et grimacent.',
    'Tout le monde échange un compliment à voix haute avec la personne de son choix.',
    'La personne qui a l’air le plus innocent du groupe avoue une petite bêtise.',
    'Jusqu’à la prochaine carte, interdit de dire « peut-être ».',
    'Chacun cite à son tour une règle de la drague. Le premier qui répète perd.',
    'Le dernier qui lève la main nomme la personne la plus mystérieuse du groupe.',
    'Ceux qui ont déjà passé un week-end entier sur un canapé boivent une gorgée ou lèvent la main.',
    'Tout le monde choisit un mot doux à dire à son voisin de droite, sans rougir.',
    'Chacun fait une déclaration d’amour dramatique à son plat préféré.',
    'La personne à droite du lecteur désigne qui doit raconter son pire silence gêné.',
    'Jusqu’à la prochaine carte, tout le monde doit finir ses phrases par un compliment.',
    'Le dernier qui touche son téléphone lit sa dernière recherche Internet à voix haute, ou boit une gorgée.',
    'Ceux qui ont déjà été jaloux d’un ami lèvent la main et se taisent.',
    'Tout le monde dit en même temps le nom de la chanson qui lui rappelle un ex.',
    'Chacun cite à son tour une série romantique. Le premier qui hésite perd.',
    'La personne qui a le moins de photos sur son téléphone choisit un thème de selfie.',
    'Le dernier qui touche ses joues raconte la fois où il a le plus rougi.',
    'Ceux qui ont déjà fait la bise à la mauvaise personne lèvent la main et font la bise à l’air.',
    'Jusqu’à la prochaine carte, tout le monde parle avec une voix de narrateur de film d’amour.',
    'Tout le monde échange un regard intense de 5 secondes avec la personne en face, sans rire.',
    'Chacun dit son signe astrologique et un défaut typique. Le groupe valide ou non.',
    'Le dernier qui croise les bras raconte sa pire excuse de retard.',
    'Ceux qui ont déjà dragué par message boivent une gorgée ou lèvent la main.',
    'La personne la plus âgée du groupe raconte un conseil de séduction d’un autre temps.',
    'Tout le monde vote à main levée pour qui serait le meilleur témoin de mariage.',
    'Chacun cite à son tour une chanson pour rompre. Le premier qui répète perd.',
    'Jusqu’à la prochaine carte, interdit de dire « mdr » ou « lol ».',
    'Le dernier qui touche son collier ou sa montre avoue un secret sans gravité.',
    'Ceux qui ont déjà écrit un poème d’amour lèvent la main et en récitent un vers.',
    'Tout le monde fait une imitation de son ex ou de son crush sans le nommer, les autres devinent.',
    'La personne la plus sociable du groupe présente la personne à sa gauche comme à une soirée de gala.',
    'Chacun montre son dernier selfie en groupe et raconte le contexte en une phrase.',
    'Le dernier qui lève la main nomme la personne qui l’a le plus fait rire.',
    'Ceux qui ont déjà dansé un slow sur du reggaeton se lèvent et recommencent.',
    'Jusqu’à la prochaine carte, il faut dire « chéri(e) » avant chaque prénom.',
    'Tout le monde fait un toast à la personne de son choix, avec une phrase originale.',
    'Chacun cite à son tour une qualité qu’il cherche chez quelqu’un. Pas de répétitions.',
    'Le dernier qui touche ses genoux avoue ce qu’il ferait s’il était invisible une soirée.',
    'Ceux qui ont déjà organisé une surprise romantique lèvent la main et la racontent.',
    'La personne qui a le plus de followers du groupe pose avec la pose de son choix.',
    'Tout le monde vote pour qui fait les meilleures déclarations enflammées. L’élu en improvise une.',
    'Jusqu’à la prochaine carte, tout le monde doit marcher comme sur un tapis rouge.',
    'Chacun dit à son tour son pire défaut en soirée, avec une grimace d’excuse.',
    'Le dernier qui touche son verre ou sa tasse boit une gorgée en regardant quelqu’un dans les yeux.',
    'Ceux qui ont déjà envoyé un message à la mauvaise personne se lèvent et font semblant de paniquer.',
    'Tout le monde échange son gage préféré avec celui du voisin.',
    'Chacun cite à son tour une tenue de soirée qu’il adore. Le premier qui hésite perd.',
    'La personne la plus chanceuse en amour du groupe distribue un compliment à chacun.',
    'Le dernier qui lève son pouce choisit un secret à partager à voix haute.',
    'Ceux qui ont déjà fait un premier pas lèvent la main et expliquent comment.',
    'Jusqu’à la prochaine carte, tout le monde doit finir sa phrase en soupirant d’admiration.',
    'Tout le monde dit son plus gros regret de soirée, en trois mots.',
    'Chacun fait son meilleur « bonsoir » de séducteur à la personne à sa droite.',
    'Le dernier qui touche son visage raconte son meilleur souvenir de soirée.',
    'Ceux qui ont déjà eu un coup de cœur pour un inconnu dans le métro lèvent la main.',
    'La personne qui a le plus voyagé raconte l’endroit le plus romantique qu’elle a vu.',
    'Tout le monde vote à main levée pour le meilleur compagnon de soirée.',
    'Jusqu’à la prochaine carte, interdit de dire « mais » sans boire une gorgée ou faire un gage.',
    'Chacun cite à son tour un prénom qui rend nostalgique. Le premier qui répète perd.',
    'Le dernier qui dit « ouais » à voix haute doit faire un compliment à quelqu’un en face.',
    'Ceux qui ont déjà regretté un tatouage ou une coupe lèvent la main en riant.',
    'Tout le monde échange son téléphone avec le voisin et lui fait écrire un compliment dans ses notes.',
    'La personne à gauche du lecteur invente une règle de soirée valable jusqu’à la fin du tour.',
    'Chacun montre la photo de son téléphone dont il est le plus fier, sans honte.',
    'Le dernier qui lève le bras raconte comment il a rencontré son meilleur ami.',
  ],
  hot: [
    'Le dernier à toucher son nez retire un accessoire ou boit une gorgée.',
    'Tout le monde chuchote à l’oreille de son voisin de droite un compliment sensuel, avec son accord.',
    'Jusqu’à la prochaine carte, tout le monde doit parler d’une voix basse et séductrice.',
    'Ceux qui ont déjà fait un rêve coquin sur quelqu’un de cette pièce boivent une gorgée, sans nommer.',
    'Chacun cite à son tour une zone du corps qu’il trouve sexy chez quelqu’un. Pas de répétitions.',
    'Le dernier qui touche son verre fait une danse sensuelle de 10 secondes.',
    'Tout le monde vote à main levée pour le meilleur embrasseur du groupe. L’élu remercie d’un baisemain.',
    'Ceux qui ont déjà envoyé un message coquin se lèvent et font un regard charmeur à la salle.',
    'Jusqu’à la prochaine carte, il faut finir chaque phrase par un clin d’œil.',
    'Chacun fait son meilleur regard de braise pendant 5 secondes. Le groupe élit le plus ravageur.',
    'Le dernier qui lève la main enlève une chaussette ou une bague.',
    'Tout le monde dit à voix basse son plus beau souvenir de baiser, sans donner le nom de la personne.',
    'Ceux qui aiment les massages lèvent la main. Les autres devinent qui donne le meilleur massage.',
    'La personne la plus séduisante selon le vote du groupe choisit un gage coquin et consenti.',
    'Chacun fait un baisemain à la personne de son choix, avec son accord.',
    'Jusqu’à la prochaine carte, tout le monde doit marcher comme sur un podium.',
    'Le dernier qui touche son cou raconte son premier émoi amoureux.',
    'Tout le monde vote à main levée pour le plus fort tempérament du groupe.',
    'Ceux qui ont déjà dansé très collé lèvent la main et font un mouvement de hanches.',
    'Chacun lit à voix haute un SMS imaginaire de séduction à son voisin de gauche.',
    'La personne à gauche du lecteur choisit qui doit retirer un accessoire.',
    'Jusqu’à la prochaine carte, interdit de dire « non » à une demande de compliment.',
    'Le dernier qui touche une bouteille ou un verre décrit sa soirée idéale à deux, version romantique.',
    'Tout le monde enlève un accessoire (montre, bracelet, bague, chaussure) en rythme.',
    'Ceux qui ont déjà fait semblant d’ignorer un flirt boivent une gorgée.',
    'Chacun cite à son tour une chanson sensuelle. Le premier qui hésite fait une petite danse.',
    'Le dernier qui touche ses lèvres raconte la plus belle approche qu’il ait reçue.',
    'Tout le monde fait un slow avec sa chaise, yeux dans les yeux avec une autre personne, sans contact.',
    'La personne la plus audacieuse du groupe lance une rumeur flatteuse sur quelqu’un.',
    'Jusqu’à la prochaine carte, tout le monde doit appeler son voisin de droite « beau gosse » ou « ma belle ».',
    'Chacun avoue à voix basse le lieu le plus insolite où il aimerait embrasser quelqu’un.',
    'Ceux qui ont déjà eu un crush interdit lèvent la main et se taisent.',
    'Le dernier qui touche sa nuque raconte son plus beau frisson.',
    'Tout le monde vote pour la personne dont le sourire est le plus ravageur.',
    'La personne la plus romantique du groupe lit une déclaration d’amour sensuelle improvisée.',
    'Chacun choisit une personne qu’il invite à danser un slow, avec son accord, pendant 15 secondes.',
    'Jusqu’à la prochaine carte, tout le monde murmure avant de dire un mot sur trois.',
    'Ceux qui ont déjà embrassé en public boivent une gorgée ou lèvent la main sans détails.',
    'Le dernier qui lève son verre retire une chaussette en prenant un air de star.',
    'Tout le monde cite à tour de rôle un parfum ou une odeur qui lui plaît chez quelqu’un.',
    'Chacun désigne à main levée la personne la plus charmeuse du groupe. L’élu fait une pose de mannequin.',
    'La personne à droite du lecteur choisit un aveu coquin et léger à faire à voix haute.',
    'Ceux qui ont déjà fait une soirée très osée lèvent la main et avouent un mot-clé, sans détails.',
    'Jusqu’à la prochaine carte, interdit de dire « merci » sans le dire d’une voix sensuelle.',
    'Le dernier qui touche son épaule fait un massage de cinq secondes à son voisin, avec son accord.',
    'Tout le monde dit à son voisin de gauche ce qui le rend irrésistible, sans vulgarité.',
    'Chacun cite à son tour une réplique de film romantique. Le premier qui hésite perd.',
    'Ceux qui sont déjà tombés amoureux d’un regard font un cœur avec leurs mains.',
    'La personne qui a le moins de vêtements en ce moment choisit le prochain gage.',
    'Le dernier qui touche sa ceinture ou son col retire un accessoire de son choix.',
    'Tout le monde fait un baiser dans le vide à la personne de son choix, avec le sourire.',
    'Jusqu’à la prochaine carte, tout le monde doit finir ses phrases par « mon cœur ».',
    'Chacun avoue à voix basse sa pire erreur de drague, avec une seule phrase.',
    'Ceux qui ont déjà passé une nuit de rêve avec quelqu’un lèvent la main, sans commentaire.',
    'Le dernier qui touche son visage raconte son meilleur compliment reçu.',
    'Tout le monde vote à main levée pour le plus beau regard du groupe.',
    'La personne la plus pudique du groupe désigne qui doit raconter un secret de séduction.',
    'Chacun fait une déclaration brûlante à un objet de la pièce, avec une voix tragique.',
    'Jusqu’à la prochaine carte, interdit de croiser les bras, il faut garder une posture de séducteur.',
    'Ceux qui ont déjà eu un coup de foudre en soirée boivent une gorgée ou font un clin d’œil.',
    'Le dernier qui touche son dos raconte la plus belle surprise qu’il ait reçue en amour.',
    'Tout le monde échange un regard appuyé de 5 secondes avec la personne en face, sans rire.',
    'Chacun dit à voix haute le mot qui le rend nostalgique d’un amour passé.',
    'La personne la plus joueuse du groupe choisit qui doit lancer un compliment sensuel à quelqu’un.',
    'Jusqu’à la prochaine carte, chaque phrase doit commencer par « Mmm… ».',
    'Ceux qui ont déjà écrit « tu me plais » à quelqu’un lèvent la main et se rasseyent avec élégance.',
    'Le dernier qui touche le bord de la table retire un accessoire visible.',
    'Tout le monde choisit un nom de parfum pour son voisin de droite, avec une description coquine.',
    'Chacun invente une phrase de séduction de film et la dit à la personne à sa gauche.',
    'Ceux qui ont déjà été draguée ou dragué par un inconnu lèvent la main et font un salut courtois.',
    'La personne à gauche du lecteur choisit un secret coquin que quelqu’un doit avouer sans détails.',
    'Jusqu’à la prochaine carte, interdit de dire « tu » sans un petit sourire séducteur.',
    'Le dernier qui touche son téléphone montre sa dernière photo de couple ou d’ami proche.',
    'Tout le monde fait un « vote de la nuit » : qui serait le meilleur partenaire de danse collée ?',
    'Chacun cite à son tour une partie du corps qu’il trouve élégante chez quelqu’un, avec respect.',
    'Ceux qui ont déjà échangé un baiser volé boivent une gorgée ou lèvent la main.',
    'Le dernier qui lève la main fait une danse lascive de 10 secondes, sans contact.',
    'La personne la plus entreprenante du groupe invite quelqu’un à danser, avec accord.',
    'Tout le monde dit à voix basse son prénom préféré chez une personne sexy.',
    'Jusqu’à la prochaine carte, interdit de rire, il faut garder un air de mystère.',
    'Chacun avoue à son voisin de gauche son plus beau fantasme de vacances, sans rien de sexuel.',
    'Ceux qui ont déjà fait un strip-tease de plaisanterie lèvent la main et enlèvent un accessoire.',
    'Le dernier qui touche sa nuque raconte la fois où il a eu le plus chaud en soirée.',
    'Tout le monde vote à main levée pour le meilleur conseil de séduction du groupe.',
    'Chacun fait la tête qu’il fait quand il est amoureux, pendant 5 secondes.',
    'La personne la plus coquine du groupe, selon un vote, chuchote un défi à l’oreille d’un joueur.',
    'Jusqu’à la prochaine carte, tout le monde doit parler comme dans un film des années 70.',
    'Ceux qui ont déjà dragué sous la pluie lèvent la main et miment un parapluie romantique.',
    'Le dernier qui touche sa bouche raconte son premier baiser en trois mots.',
    'Tout le monde échange un accessoire avec la personne de son choix, avec son accord, pour trois tours.',
    'Chacun cite à son tour un mot sensuel. Le premier qui répète ou hésite boit une gorgée.',
    'Ceux qui ont déjà passé une nuit entière à parler avec quelqu’un lèvent la main et sourient.',
    'La personne à droite du lecteur choisit un compliment audacieux à dire à voix haute.',
    'Jusqu’à la prochaine carte, il faut faire un clin d’œil à chaque fin de phrase.',
    'Le dernier qui touche son verre enlève un accessoire et le donne à quelqu’un.',
    'Tout le monde dit à son voisin de droite ce qui l’a le plus séduit chez lui, ou chez elle.',
    'Chacun invente un cocktail aphrodisiaque et le décrit avec un grand sérieux.',
    'Ceux qui ont déjà eu un rendez-vous romantique à la plage lèvent la main et font un bruit de vagues.',
    'La personne la plus élégante du groupe fait un défilé de 10 secondes.',
    'Le dernier qui touche son cœur confie un secret sentimental léger.',
    'Tout le monde vote à main levée : qui est le plus craquant du groupe ?',
    'Jusqu’à la prochaine carte, tout le monde doit chuchoter à l’oreille de son voisin pour demander quelque chose.',
    'Chacun cite à son tour une qualité sensuelle chez les autres. Le premier qui répète perd.',
    'Ceux qui ont déjà eu un rêve très étrange sur quelqu’un du groupe se lèvent sans parler.',
    'Le dernier qui lève la jambe retire une chaussure et la balance doucement vers un coussin.',
    'Tout le monde dit son plus grand talent de séducteur ou de séductrice.',
    'La personne à gauche du lecteur désigne qui doit faire une danse sensuelle avec un foulard imaginaire.',
    'Jusqu’à la prochaine carte, interdit de dire « je ne sais pas ». Il faut toujours répondre avec assurance.',
    'Chacun fait un compliment sur la voix de la personne en face.',
    'Ceux qui ont déjà eu un moment de tension avec un ami lèvent la main et gardent le suspense.',
    'Le dernier qui touche le sol avec sa main doit dire ce qui l’attire chez les autres, sans vulgarité.',
    'Tout le monde fait une pose sensuelle de calendrier pendant 5 secondes.',
    'Chacun cite à son tour un film ou une série sensuelle. Le premier qui hésite boit une gorgée.',
    'La personne la plus discrète du groupe avoue un petit secret de cœur.',
    'Jusqu’à la prochaine carte, chaque phrase doit se terminer par un murmure.',
    'Ceux qui ont déjà passé une soirée entière à flirter lèvent la main et soufflent un baiser.',
    'Le dernier qui touche sa chevelure fait un baisemain à la personne qu’il préfère ce soir.',
    'Tout le monde vote : qui serait le plus convaincant dans un rôle de séducteur ou séductrice ?',
    'Chacun décrit en un mot sa dernière nuit de rêve, sans entrer dans les détails.',
    'Ceux qui ont déjà embrassé quelqu’un sous les étoiles lèvent la main avec un sourire.',
    'La personne la plus joyeuse du groupe fait un compliment appuyé à celui qui l’aime le moins.',
    'Jusqu’à la prochaine carte, tout le monde doit saluer en faisant une révérence.',
    'Le dernier qui touche son nez avoue son plus grand frisson récent.',
    'Tout le monde partage une chanson à écouter pour un dîner aux chandelles.',
    'Chacun lance un regard de charme à la personne en face, qui doit répondre sans rire.',
    'Ceux qui ont déjà dragué un ami d’ami lèvent la main et font un clin d’œil à l’assemblée.',
    'La personne à droite du lecteur choisit un secret sensuel et léger à avouer.',
    'Jusqu’à la prochaine carte, interdit de dire « moi aussi » sans un soupir de plaisir.',
    'Le dernier qui touche sa chaise raconte la fois où il a été le plus charmé.',
    'Tout le monde enlève un accessoire et le pose devant soi, comme un trophée de séduction.',
    'Chacun cite à son tour un prénom romantique. Le premier qui répète ou hésite perd.',
    'Ceux qui ont déjà fait une danse avec un inconnu lèvent la main et refont un pas.',
    'La personne la plus assurée du groupe fait un compliment très osé mais élégant à quelqu’un.',
    'Jusqu’à la prochaine carte, tout le monde doit marcher comme un mannequin sur le podium.',
    'Le dernier qui lève la main raconte le moment où il a eu le plus de papillons dans le ventre.',
    'Tout le monde dit à voix basse un secret à son voisin de gauche, qui garde le mystère.',
    'Chacun invente un surnom coquin et chic pour la personne à sa droite.',
    'Ceux qui ont déjà passé une nuit en amoureux à la belle étoile lèvent la main et sourient.',
    'La personne la plus frileuse du groupe enfile un accessoire que le groupe choisit.',
    'Le dernier qui touche son visage soupire d’admiration en regardant quelqu’un.',
    'Tout le monde fait une déclaration passionnée à la personne de son choix, en trois mots.',
    'Chacun cite à son tour un lieu romantique. Le premier qui répète ou hésite boit une gorgée.',
    'Ceux qui ont déjà écrit une lettre d’amour lèvent la main et lisent une phrase de mémoire.',
    'Jusqu’à la prochaine carte, interdit de dire « bof ». Il faut tout dire avec passion.',
    'La personne à gauche du lecteur choisit qui doit faire un compliment à tout le monde.',
    'Le dernier qui touche son genou ôte un accessoire et le tend à quelqu’un.',
    'Tout le monde vote à main levée pour le meilleur danseur de salsa du groupe. L’élu fait trois pas.',
    'Chacun lance un baiser en l’air à la personne qu’il trouve la plus charmante.',
    'Ceux qui ont déjà été séduits par une voix lèvent la main et imitent un murmure.',
    'Jusqu’à la prochaine carte, tout le monde parle avec un accent romantique italien ou français.',
    'La personne la plus pudique du groupe choisit qui doit dire son plus grand charme.',
    'Le dernier qui touche sa bague ou son bracelet murmure un compliment à son voisin.',
    'Tout le monde dit à voix haute le mot qui lui donne le plus chaud, sans vulgarité.',
    'Chacun cite à son tour une phrase qui le fait craquer. Pas de répétitions.',
    'Ceux qui ont déjà eu un rendez-vous inoubliable lèvent la main et racontent le lieu.',
    'La personne qui a l’air le plus tranquille du groupe avoue un plaisir coupable avouable.',
    'Jusqu’à la prochaine carte, il faut faire un baisemain à chaque fois qu’on te parle.',
    'Le dernier qui lève la main raconte la meilleure phrase de drague qu’on lui ait dite.',
    'Tout le monde danse en rythme avec son voisin, sans contact, pendant dix secondes.',
    'Chacun choisit une personne et lui dit ce qui est charmant chez elle, sans parler du physique.',
    'Ceux qui ont déjà fait un câlin de plus de 10 secondes lèvent la main et se rasseyent doucement.',
    'La personne la plus douce du groupe chuchote un secret à celui qui le lui demande.',
    'Jusqu’à la prochaine carte, chaque prénom doit être prononcé avec un frisson dans la voix.',
    'Le dernier qui touche son verre doit dire ce qu’il ferait lors d’une nuit parfaite, version romantique.',
    'Tout le monde fait un compliment bien senti à la personne qui lui plaît le plus ce soir, sans la nommer.',
  ],
}
