import type { Level } from '../engine'

export interface QuizQuestion {
  question: string
  answer: string
}

/** Quiz — Soft : culture générale, Épicé : culture soirée et pop, Hot : culture coquine. */
export const quizQuestions: Record<Level, QuizQuestion[]> = {
  soft: [
    // Géographie
    { question: 'Quelle est la capitale de l’Australie ?', answer: 'Canberra' },
    { question: 'Quelle est la capitale du Canada ?', answer: 'Ottawa' },
    { question: 'Quel est le plus long fleuve de France ?', answer: 'La Loire' },
    { question: 'Combien de départements compte la France métropolitaine ?', answer: '96' },
    { question: 'Quel est le plus haut sommet des Alpes ?', answer: 'Le mont Blanc' },
    { question: 'Dans quel pays se trouve le Machu Picchu ?', answer: 'Le Pérou' },
    { question: 'Quelle est la capitale de la Turquie ?', answer: 'Ankara' },
    { question: 'Quel détroit sépare l’Espagne du Maroc ?', answer: 'Le détroit de Gibraltar' },
    { question: 'Quelle est la capitale du Brésil ?', answer: 'Brasília' },
    { question: 'Dans quel pays se trouve la ville de Marrakech ?', answer: 'Le Maroc' },
    { question: 'Quel pays européen a la forme d’une botte ?', answer: 'L’Italie' },
    { question: 'Quelle est la plus grande île de la Méditerranée ?', answer: 'La Sicile' },
    { question: 'Quelle est la capitale de la Nouvelle-Zélande ?', answer: 'Wellington' },
    { question: 'Sur quel continent se trouve le désert de Gobi ?', answer: 'L’Asie' },
    { question: 'Quel fleuve traverse Le Caire ?', answer: 'Le Nil' },
    { question: 'Quelle est la capitale de l’Écosse ?', answer: 'Édimbourg' },
    { question: 'Quel est le plus petit État du monde ?', answer: 'Le Vatican' },
    { question: 'Dans quelle ville se trouve la Sagrada Família ?', answer: 'Barcelone' },
    { question: 'Quelle chaîne de montagnes sépare la France de l’Espagne ?', answer: 'Les Pyrénées' },
    { question: 'Quelle est la capitale de la Norvège ?', answer: 'Oslo' },
    { question: 'Quel fleuve traverse Londres ?', answer: 'La Tamise' },
    { question: 'Dans quel pays se trouve la ville de Tombouctou ?', answer: 'Le Mali' },
    { question: 'Quelle est la capitale de l’Argentine ?', answer: 'Buenos Aires' },
    { question: 'Quel est le plus grand océan du monde ?', answer: 'L’océan Pacifique' },
    { question: 'Quelle est la monnaie du Japon ?', answer: 'Le yen' },
    { question: 'Quelle est la monnaie du Royaume-Uni ?', answer: 'La livre sterling' },
    { question: 'Dans quelle ville se dresse la statue du Christ Rédempteur ?', answer: 'Rio de Janeiro' },
    { question: 'Quelle île française de l’océan Indien a pour chef-lieu Saint-Denis ?', answer: 'La Réunion' },
    { question: 'Quelle est la capitale de la Suisse ?', answer: 'Berne' },
    { question: 'Quel pays a pour capitale Lisbonne ?', answer: 'Le Portugal' },
    { question: 'Quel fleuve traverse Bordeaux ?', answer: 'La Garonne' },
    { question: 'Dans quel pays se trouvent les pyramides de Gizeh ?', answer: 'L’Égypte' },
    { question: 'Quelle est la capitale de l’Islande ?', answer: 'Reykjavik' },
    // Histoire
    { question: 'En quelle année a eu lieu la prise de la Bastille ?', answer: '1789' },
    { question: 'Qui a été sacré empereur des Français en 1804 ?', answer: 'Napoléon Ier' },
    { question: 'En quelle année Christophe Colomb a-t-il atteint l’Amérique ?', answer: '1492' },
    { question: 'Quel roi de France était surnommé le Roi-Soleil ?', answer: 'Louis XIV' },
    { question: 'En quelle année est tombé le mur de Berlin ?', answer: '1989' },
    { question: 'Qui a été le premier président de la Ve République ?', answer: 'Charles de Gaulle' },
    { question: 'En quelle année a eu lieu le débarquement de Normandie ?', answer: '1944' },
    { question: 'Quelle bataille de 1815 marque la défaite finale de Napoléon ?', answer: 'Waterloo' },
    { question: 'Qui a été le premier homme à marcher sur la Lune ?', answer: 'Neil Armstrong' },
    { question: 'En quelle année l’homme a-t-il marché sur la Lune pour la première fois ?', answer: '1969' },
    { question: 'Quelle héroïne française a été brûlée à Rouen en 1431 ?', answer: 'Jeanne d’Arc' },
    { question: 'Quel général romain a conquis la Gaule ?', answer: 'Jules César' },
    { question: 'Quel chef gaulois s’est rendu à César après le siège d’Alésia ?', answer: 'Vercingétorix' },
    { question: 'En quelle année a débuté la Première Guerre mondiale ?', answer: '1914' },
    { question: 'En quelle année s’est terminée la Seconde Guerre mondiale ?', answer: '1945' },
    { question: 'Quel paquebot a coulé en 1912 après avoir heurté un iceberg ?', answer: 'Le Titanic' },
    { question: 'De quel pharaon Howard Carter a-t-il découvert le tombeau en 1922 ?', answer: 'Toutânkhamon' },
    { question: 'Quelle ville était la capitale de l’Empire byzantin ?', answer: 'Constantinople' },
    { question: 'Quel futur président américain est le principal rédacteur de la Déclaration d’indépendance ?', answer: 'Thomas Jefferson' },
    { question: 'Quel roi de France a été guillotiné en 1793 ?', answer: 'Louis XVI' },
    { question: 'Qui a été la première femme à recevoir un prix Nobel ?', answer: 'Marie Curie' },
    { question: 'Quel empereur romain a fait bâtir un mur défensif au nord de la Bretagne romaine ?', answer: 'Hadrien' },
    { question: 'En quelle année l’esclavage a-t-il été définitivement aboli en France ?', answer: '1848' },
    { question: 'Quel président américain a été assassiné à Dallas en 1963 ?', answer: 'John F. Kennedy' },
    { question: 'Quelle civilisation a bâti la cité de Chichén Itzá ?', answer: 'Les Mayas' },
    { question: 'Qui a mis au point l’imprimerie à caractères mobiles en Europe ?', answer: 'Johannes Gutenberg' },
    { question: 'Quelle reine de France était surnommée « l’Autrichienne » ?', answer: 'Marie-Antoinette' },
    { question: 'Sur quelle île Napoléon est-il mort en exil ?', answer: 'Sainte-Hélène' },
    { question: 'Quel roi franc a été baptisé à Reims vers 500 ?', answer: 'Clovis' },
    { question: 'Quel empereur a été couronné à Rome le jour de Noël de l’an 800 ?', answer: 'Charlemagne' },
    // Sciences
    { question: 'Quel est le symbole chimique de l’or ?', answer: 'Au' },
    { question: 'Quel est le symbole chimique du fer ?', answer: 'Fe' },
    { question: 'Quelle est la formule chimique de l’eau ?', answer: 'H2O' },
    { question: 'Quelle planète est la plus proche du Soleil ?', answer: 'Mercure' },
    { question: 'Quelle est la plus grande planète du Système solaire ?', answer: 'Jupiter' },
    { question: 'Quelle planète est surnommée la planète rouge ?', answer: 'Mars' },
    { question: 'Combien d’os compte le squelette d’un adulte ?', answer: '206' },
    { question: 'Quel gaz les plantes absorbent-elles pour la photosynthèse ?', answer: 'Le dioxyde de carbone' },
    { question: 'À quelle température l’eau bout-elle au niveau de la mer ?', answer: '100 °C' },
    { question: 'Quel est le plus grand organe du corps humain ?', answer: 'La peau' },
    { question: 'Qui a formulé la théorie de la relativité ?', answer: 'Albert Einstein' },
    { question: 'Combien de chromosomes compte une cellule humaine normale ?', answer: '46' },
    { question: 'Quel savant anglais a formulé la loi de la gravitation universelle ?', answer: 'Isaac Newton' },
    { question: 'Quel métal est liquide à température ambiante ?', answer: 'Le mercure' },
    { question: 'Quelle est, environ, la vitesse de la lumière dans le vide ?', answer: '300 000 km/s' },
    { question: 'Qui a découvert la pénicilline ?', answer: 'Alexander Fleming' },
    { question: 'Combien de cœurs possède une pieuvre ?', answer: 'Trois' },
    { question: 'Quel est le gaz le plus abondant dans l’atmosphère terrestre ?', answer: 'L’azote' },
    { question: 'Combien de temps met la lumière du Soleil pour atteindre la Terre, environ ?', answer: 'Environ 8 minutes' },
    { question: 'Quelle unité mesure l’intensité d’un courant électrique ?', answer: 'L’ampère' },
    { question: 'Quel savant français a mis au point le vaccin contre la rage ?', answer: 'Louis Pasteur' },
    { question: 'Combien de pattes a une araignée ?', answer: 'Huit' },
    { question: 'Combien de pattes a un insecte ?', answer: 'Six' },
    { question: 'Quel est l’os le plus long du corps humain ?', answer: 'Le fémur' },
    { question: 'Quelle planète est célèbre pour ses anneaux très visibles ?', answer: 'Saturne' },
    { question: 'Quel est le symbole chimique du sodium ?', answer: 'Na' },
    { question: 'Combien de minutes compte une journée ?', answer: '1 440' },
    { question: 'Quelle est la valeur de pi arrondie au centième ?', answer: '3,14' },
    { question: 'Combien de côtés a un hexagone ?', answer: 'Six' },
    { question: 'Comment appelle-t-on un polygone à huit côtés ?', answer: 'Un octogone' },
    { question: 'Quel est le plus petit nombre premier ?', answer: '2' },
    { question: 'Quel organe pompe le sang dans le corps ?', answer: 'Le cœur' },
    { question: 'Quel est le symbole chimique de l’oxygène ?', answer: 'O' },
    { question: 'Combien de degrés mesure un angle droit ?', answer: '90' },
    // Nature
    { question: 'Quel est le plus grand animal du monde ?', answer: 'La baleine bleue' },
    { question: 'Quel est l’animal terrestre le plus rapide ?', answer: 'Le guépard' },
    { question: 'Comment appelle-t-on le petit de la chèvre ?', answer: 'Le chevreau (ou cabri)' },
    { question: 'Comment s’appelle la femelle du sanglier ?', answer: 'La laie' },
    { question: 'Quel animal figure sur le logo du WWF ?', answer: 'Le panda géant' },
    { question: 'Quel oiseau est capable de voler en marche arrière ?', answer: 'Le colibri' },
    { question: 'De quelle plante se nourrit principalement le panda géant ?', answer: 'Le bambou' },
    { question: 'Comment appelle-t-on un animal qui mange de tout ?', answer: 'Omnivore' },
    { question: 'Combien de bosses a un dromadaire ?', answer: 'Une' },
    { question: 'Quel arbre produit les glands ?', answer: 'Le chêne' },
    { question: 'Comment appelle-t-on le cri du cerf ?', answer: 'Le brame' },
    { question: 'Quel est le seul mammifère capable de voler activement ?', answer: 'La chauve-souris' },
    { question: 'Comment appelle-t-on la larve aquatique de la grenouille ?', answer: 'Le têtard' },
    { question: 'Quel oiseau pond les plus gros œufs ?', answer: 'L’autruche' },
    { question: 'Quel est le plus grand félin du monde ?', answer: 'Le tigre' },
    { question: 'Quel insecte produit le miel ?', answer: 'L’abeille' },
    { question: 'Comment s’appelle la femelle du cheval ?', answer: 'La jument' },
    { question: 'Comment s’appelle l’abri creusé par le lapin de garenne ?', answer: 'Le terrier' },
    { question: 'Quelle fleur est l’emblème de la royauté française ?', answer: 'Le lys' },
    { question: 'Quel cétacé à longue défense est surnommé la licorne des mers ?', answer: 'Le narval' },
    { question: 'Combien de pattes a un crabe, pinces comprises ?', answer: 'Dix' },
    { question: 'Comment appelle-t-on les animaux qui ne mangent que des végétaux ?', answer: 'Herbivores' },
    // Langue française
    { question: 'Quel est le pluriel de « cheval » ?', answer: 'Chevaux' },
    { question: 'Quel est le féminin de « loup » ?', answer: 'Louve' },
    { question: 'Comment appelle-t-on un mot qui se lit dans les deux sens, comme « kayak » ?', answer: 'Un palindrome' },
    { question: 'Quel mot désigne la peur des araignées ?', answer: 'L’arachnophobie' },
    { question: 'Combien de lettres compte l’alphabet français ?', answer: '26' },
    { question: 'Comment appelle-t-on un mot de sens contraire à un autre ?', answer: 'Un antonyme' },
    { question: 'Comment appelle-t-on un texte qui s’interdit volontairement une lettre ?', answer: 'Un lipogramme' },
    { question: 'Qui a écrit « La Disparition », roman sans la lettre e ?', answer: 'Georges Perec' },
    { question: 'Quel est le participe passé du verbe « résoudre » ?', answer: 'Résolu' },
    { question: 'Que signifie l’expression « poser un lapin » ?', answer: 'Ne pas venir à un rendez-vous' },
    { question: 'Que signifie l’expression « avoir le cafard » ?', answer: 'Avoir des idées noires' },
    { question: 'Combien de membres compte l’Académie française ?', answer: '40' },
    { question: 'Comment surnomme-t-on les membres de l’Académie française ?', answer: 'Les Immortels' },
    { question: 'Comment s’appelle le petit signe placé sous le c de « ç » ?', answer: 'La cédille' },
    { question: 'Que signifie l’expression « avoir un poil dans la main » ?', answer: 'Être paresseux' },
    { question: 'Que signifie l’expression « tomber dans les pommes » ?', answer: 'S’évanouir' },
    // Arts et littérature
    { question: 'Qui a peint « La Joconde » ?', answer: 'Léonard de Vinci' },
    { question: 'Dans quel musée est exposée « La Joconde » ?', answer: 'Le Louvre' },
    { question: 'Qui a écrit « Les Misérables » ?', answer: 'Victor Hugo' },
    { question: 'Qui a peint « La Nuit étoilée » ?', answer: 'Vincent van Gogh' },
    { question: 'Quel peintre espagnol a réalisé « Guernica » ?', answer: 'Pablo Picasso' },
    { question: 'Qui a écrit « Le Petit Prince » ?', answer: 'Antoine de Saint-Exupéry' },
    { question: 'Qui a sculpté « Le Penseur » ?', answer: 'Auguste Rodin' },
    { question: 'Qui a écrit « Roméo et Juliette » ?', answer: 'William Shakespeare' },
    { question: 'Qui a composé « Les Quatre Saisons » ?', answer: 'Antonio Vivaldi' },
    { question: 'Quel compositeur devenu sourd a écrit l’« Ode à la joie » ?', answer: 'Ludwig van Beethoven' },
    { question: 'Qui a composé l’opéra « La Flûte enchantée » ?', answer: 'Wolfgang Amadeus Mozart' },
    { question: 'Qui a écrit « Les Trois Mousquetaires » ?', answer: 'Alexandre Dumas' },
    { question: 'Quel jeune Gascon rejoint Athos, Porthos et Aramis ?', answer: 'D’Artagnan' },
    { question: 'Qui a écrit « Germinal » ?', answer: 'Émile Zola' },
    { question: 'Quel peintre a réalisé « Impression, soleil levant » ?', answer: 'Claude Monet' },
    { question: 'Qui a écrit « Le Tour du monde en quatre-vingts jours » ?', answer: 'Jules Verne' },
    { question: 'Quel dramaturge a écrit « Le Malade imaginaire » ?', answer: 'Molière' },
    { question: 'Quel poète a écrit « Les Fleurs du mal » ?', answer: 'Charles Baudelaire' },
    { question: 'Qui a peint le plafond de la chapelle Sixtine ?', answer: 'Michel-Ange' },
    { question: 'Qui a écrit « L’Étranger » ?', answer: 'Albert Camus' },
    { question: 'Quel compositeur polonais est célèbre pour ses nocturnes pour piano ?', answer: 'Frédéric Chopin' },
    { question: 'Combien de cordes compte un violon ?', answer: 'Quatre' },
    { question: 'Qui a composé le « Boléro » ?', answer: 'Maurice Ravel' },
    { question: 'Qui a composé l’opéra « Carmen » ?', answer: 'Georges Bizet' },
    { question: 'En quelle année a été inaugurée la tour Eiffel ?', answer: '1889' },
    { question: 'Quel sonneur bossu est le héros de « Notre-Dame de Paris » ?', answer: 'Quasimodo' },
    { question: 'Qui a écrit « Les Fables », dont « Le Corbeau et le Renard » ?', answer: 'Jean de La Fontaine' },
    // Cinéma classique
    { question: 'Qui a réalisé « Psychose » (1960) ?', answer: 'Alfred Hitchcock' },
    { question: 'Quel acteur du muet incarnait le personnage de Charlot ?', answer: 'Charlie Chaplin' },
    { question: 'Dans quel film de 1939 Dorothy suit-elle une route de briques jaunes ?', answer: 'Le Magicien d’Oz' },
    { question: 'Qui a réalisé « Les Quatre Cents Coups » ?', answer: 'François Truffaut' },
    { question: 'Dans quelle ville remet-on chaque année la Palme d’or ?', answer: 'Cannes' },
    { question: 'Quels frères ont organisé en 1895 la première projection publique payante de cinéma ?', answer: 'Les frères Lumière' },
    { question: 'Qui joue Holly Golightly dans « Diamants sur canapé » ?', answer: 'Audrey Hepburn' },
    { question: 'Quel film de 1942 se déroule dans le café de Rick, au Maroc ?', answer: 'Casablanca' },
    { question: 'Qui a réalisé « Le Voyage dans la Lune » (1902) ?', answer: 'Georges Méliès' },
    // Sport
    { question: 'Combien de joueurs compte une équipe de football sur le terrain ?', answer: '11' },
    { question: 'Combien de joueurs compte une équipe de volley-ball sur le terrain ?', answer: 'Six' },
    { question: 'Tous les combien d’années ont lieu les Jeux olympiques d’été ?', answer: 'Tous les quatre ans' },
    { question: 'Dans quel sport utilise-t-on un volant ?', answer: 'Le badminton' },
    { question: 'Quelle est la distance officielle d’un marathon ?', answer: '42,195 km' },
    { question: 'Quel tournoi du Grand Chelem se joue sur terre battue ?', answer: 'Roland-Garros' },
    { question: 'Dans quel pays sont nés les Jeux olympiques antiques ?', answer: 'La Grèce' },
    { question: 'Quel baron français a rénové les Jeux olympiques ?', answer: 'Pierre de Coubertin' },
    { question: 'Combien de points vaut un essai au rugby à XV ?', answer: 'Cinq' },
    { question: 'De quelle couleur est le maillot du leader du Tour de France ?', answer: 'Jaune' },
    { question: 'Combien de cases compte un échiquier ?', answer: '64' },
    { question: 'Quelle pièce du jeu d’échecs se déplace uniquement en diagonale ?', answer: 'Le fou' },
    { question: 'Dans quel sport se dispute la Ryder Cup ?', answer: 'Le golf' },
    { question: 'En quelle année la France a-t-elle gagné sa première Coupe du monde de football ?', answer: '1998' },
    { question: 'Combien de trous compte un parcours de golf standard ?', answer: '18' },
    { question: 'Dans quelle ville ont eu lieu les premiers Jeux olympiques modernes, en 1896 ?', answer: 'Athènes' },
    { question: 'Combien d’anneaux figurent sur le drapeau olympique ?', answer: 'Cinq' },
    // Cuisine
    { question: 'De quelle région française la choucroute est-elle la spécialité ?', answer: 'L’Alsace' },
    { question: 'Quel fromage est indispensable à une tartiflette ?', answer: 'Le reblochon' },
    { question: 'Quel est l’ingrédient principal du guacamole ?', answer: 'L’avocat' },
    { question: 'De quel pays la paella est-elle originaire ?', answer: 'L’Espagne' },
    { question: 'Avec quelle céréale prépare-t-on un risotto ?', answer: 'Le riz' },
    { question: 'Quel légume est la base du gaspacho ?', answer: 'La tomate' },
    { question: 'Quelle ville bourguignonne a donné son nom à une moutarde célèbre ?', answer: 'Dijon' },
    { question: 'Quelle épice est réputée la plus chère au monde ?', answer: 'Le safran' },
    { question: 'Comment s’appelle la tarte aux pommes caramélisées cuite à l’envers ?', answer: 'La tarte Tatin' },
    { question: 'Avec quel lait fabrique-t-on le roquefort ?', answer: 'Le lait de brebis' },
    { question: 'De quelle ville la bouillabaisse est-elle la spécialité ?', answer: 'Marseille' },
    { question: 'Quel fruit fermente-t-on pour faire du cidre ?', answer: 'La pomme' },
    { question: 'Quel est l’ingrédient principal du houmous ?', answer: 'Le pois chiche' },
    { question: 'Quel champignon souterrain est surnommé le diamant noir ?', answer: 'La truffe' },
    { question: 'De quel pays la pizza est-elle originaire ?', answer: 'L’Italie' },
    { question: 'Quel fromage italien râpé accompagne souvent les pâtes ?', answer: 'Le parmesan' },
    { question: 'Avec quelle farine prépare-t-on les galettes bretonnes ?', answer: 'Le sarrasin (blé noir)' },
  ],

  spicy: [
    // Cocktails et boissons
    { question: 'Quel alcool est la base du mojito ?', answer: 'Le rhum blanc' },
    { question: 'Quelle herbe fraîche met-on dans un mojito ?', answer: 'La menthe' },
    { question: 'De quel pays le mojito est-il originaire ?', answer: 'Cuba' },
    { question: 'Quel soda se mélange au rhum dans un Cuba libre ?', answer: 'Le cola' },
    { question: 'Quel alcool est la base de la margarita ?', answer: 'La tequila' },
    { question: 'De quelle plante est tirée la tequila ?', answer: 'L’agave bleu' },
    { question: 'Quel alcool est la base du Moscow mule ?', answer: 'La vodka' },
    { question: 'Quelle boisson pétillante au gingembre complète un Moscow mule ?', answer: 'La ginger beer' },
    { question: 'Quel cocktail associe vodka, jus de tomate et épices ?', answer: 'Le Bloody Mary' },
    { question: 'Quel vin effervescent italien entre dans l’Aperol spritz ?', answer: 'Le prosecco' },
    { question: 'Quel apéritif bourguignon mélange vin blanc et crème de cassis ?', answer: 'Le kir' },
    { question: 'Comment s’appelle un kir préparé avec du champagne ?', answer: 'Un kir royal' },
    { question: 'Quel alcool anisé est l’apéritif emblématique de Marseille ?', answer: 'Le pastis' },
    { question: 'Quel cocktail associe rhum, crème de coco et jus d’ananas ?', answer: 'La piña colada' },
    { question: 'Quelle baie donne au gin son goût caractéristique ?', answer: 'Le genièvre' },
    { question: 'Quelle substance amère donne son goût au tonic ?', answer: 'La quinine' },
    { question: 'Quel cocktail James Bond commande-t-il « au shaker, pas à la cuillère » ?', answer: 'Le martini (vodka martini)' },
    { question: 'Quel cocktail brésilien mêle cachaça, citron vert et sucre ?', answer: 'La caïpirinha' },
    { question: 'Quel cocktail italien mélange gin, vermouth rouge et Campari à parts égales ?', answer: 'Le negroni' },
    { question: 'Quel alcool japonais est obtenu par fermentation du riz ?', answer: 'Le saké' },
    { question: 'Le cognac est une eau-de-vie de quoi ?', answer: 'De vin (raisin)' },
    { question: 'Le calvados est une eau-de-vie de quel fruit ?', answer: 'La pomme (et la poire)' },
    { question: 'De quelle ville la bière Guinness est-elle originaire ?', answer: 'Dublin' },
    { question: 'Quelle grande fête de la bière a lieu chaque année à Munich ?', answer: 'L’Oktoberfest' },
    { question: 'Quel moine bénédictin est associé à la légende de l’invention du champagne ?', answer: 'Dom Pérignon' },
    { question: 'Comment appelle-t-on l’art d’ouvrir une bouteille de champagne au sabre ?', answer: 'Le sabrage' },
    { question: 'Quel cocktail mélange tequila, jus d’orange et sirop de grenadine ?', answer: 'Le tequila sunrise' },
    { question: 'Quelle liqueur italienne a un goût d’amande amère ?', answer: 'L’amaretto' },
    { question: 'Quelle liqueur italienne est faite à partir de zestes de citron ?', answer: 'Le limoncello' },
    { question: 'Quel alcool anisé était surnommé « la fée verte » ?', answer: 'L’absinthe' },
    { question: 'Quel alcool grec anisé se trouble quand on y ajoute de l’eau ?', answer: 'L’ouzo' },
    { question: 'Quelle boisson chaude mélange café, whiskey irlandais, sucre et crème ?', answer: 'L’irish coffee' },
    { question: 'Quelle boisson gazeuse a été inventée par le pharmacien John Pemberton ?', answer: 'Le Coca-Cola' },
    { question: 'Quel jeu à boire consiste à lancer une balle de ping-pong dans des gobelets ?', answer: 'Le beer pong' },
    { question: 'Quel alcool écossais s’écrit sans « e », contrairement à son cousin irlandais ?', answer: 'Le whisky' },
    // Musique pop
    { question: 'Quel groupe de Liverpool a chanté « Yesterday » ?', answer: 'Les Beatles' },
    { question: 'Quel artiste est surnommé le « roi de la pop » ?', answer: 'Michael Jackson' },
    { question: 'Quel album de Michael Jackson sorti en 1982 contient « Billie Jean » ?', answer: 'Thriller' },
    { question: 'Quel groupe suédois a remporté l’Eurovision 1974 avec « Waterloo » ?', answer: 'ABBA' },
    { question: 'Quelle chanteuse est surnommée la « reine de la pop » ?', answer: 'Madonna' },
    { question: 'Qui chante « Rolling in the Deep » ?', answer: 'Adele' },
    { question: 'De quel groupe Freddie Mercury était-il le chanteur ?', answer: 'Queen' },
    { question: 'Quel duo français casqué a sorti « Get Lucky » ?', answer: 'Daft Punk' },
    { question: 'Qui chante « Shape of You » ?', answer: 'Ed Sheeran' },
    { question: 'Quel chanteur jamaïcain est l’icône mondiale du reggae ?', answer: 'Bob Marley' },
    { question: 'Quel girl group a chanté « Wannabe » en 1996 ?', answer: 'Les Spice Girls' },
    { question: 'Combien de membres comptaient les Spice Girls ?', answer: 'Cinq' },
    { question: 'Qui chante « Bad Romance » ?', answer: 'Lady Gaga' },
    { question: 'Quel rappeur canadien a sorti « Hotline Bling » ?', answer: 'Drake' },
    { question: 'Quel clip a été le premier à dépasser le milliard de vues sur YouTube ?', answer: 'Gangnam Style (Psy)' },
    { question: 'Quel chanteur belge a sorti « Alors on danse » ?', answer: 'Stromae' },
    { question: 'Qui chante « …Baby One More Time » et « Toxic » ?', answer: 'Britney Spears' },
    { question: 'Quel groupe grunge était mené par Kurt Cobain ?', answer: 'Nirvana' },
    { question: 'Qui chante « Single Ladies » ?', answer: 'Beyoncé' },
    { question: 'De quel girl group Beyoncé faisait-elle partie ?', answer: 'Destiny’s Child' },
    { question: 'Qui interprète « Umbrella » ?', answer: 'Rihanna' },
    { question: 'De quelle île des Caraïbes Rihanna est-elle originaire ?', answer: 'La Barbade' },
    { question: 'Quel artiste a sorti l’album « Purple Rain » ?', answer: 'Prince' },
    { question: 'Quelle chanson de Queen commence par « Is this the real life? » ?', answer: 'Bohemian Rhapsody' },
    { question: 'Quelle chanteuse française a sorti « Je veux » en 2010 ?', answer: 'Zaz' },
    { question: 'Quel chanteur français a interprété « Allumer le feu » ?', answer: 'Johnny Hallyday' },
    { question: 'Qui chante « Dernière danse » (2013) ?', answer: 'Indila' },
    { question: 'Qui chante « La Vie en rose » ?', answer: 'Édith Piaf' },
    { question: 'Quel groupe irlandais a chanté « Zombie » ?', answer: 'The Cranberries' },
    { question: 'Quel groupe britannique a sorti « Wonderwall » ?', answer: 'Oasis' },
    { question: 'Quels frères étaient à la tête d’Oasis ?', answer: 'Liam et Noel Gallagher' },
    { question: 'Quel boys band est né de l’émission « The X Factor » en 2010 ?', answer: 'One Direction' },
    { question: 'Quel chanteur est le leader du groupe U2 ?', answer: 'Bono' },
    { question: 'Quelle chanteuse interprète « All I Want for Christmas Is You » ?', answer: 'Mariah Carey' },
    { question: 'Quel groupe finlandais déguisé en monstres a gagné l’Eurovision 2006 ?', answer: 'Lordi' },
    { question: 'Quel groupe italien a remporté l’Eurovision 2021 ?', answer: 'Måneskin' },
    { question: 'Quel tube de Lou Bega égrène une liste de prénoms féminins ?', answer: 'Mambo No. 5' },
    { question: 'Quel duo espagnol a chanté la « Macarena » ?', answer: 'Los del Río' },
    { question: 'Quel DJ français a produit « Titanium » ?', answer: 'David Guetta' },
    { question: 'Quelle chanteuse américaine a sorti « Shake It Off » ?', answer: 'Taylor Swift' },
    { question: 'Qui chante « Despacito » avec Daddy Yankee ?', answer: 'Luis Fonsi' },
    { question: 'Quel groupe de K-pop a chanté « Dynamite » ?', answer: 'BTS' },
    { question: 'Quel groupe australien chante « Highway to Hell » ?', answer: 'AC/DC' },
    { question: 'Quel pas de danse glissé en arrière Michael Jackson a-t-il popularisé ?', answer: 'Le moonwalk' },
    // Dessins animés
    { question: 'Comment s’appelle la souris star de Disney ?', answer: 'Mickey' },
    { question: 'Quel est le nom du lionceau héros du « Roi lion » ?', answer: 'Simba' },
    { question: 'Comment s’appelle l’oncle de Simba ?', answer: 'Scar' },
    { question: 'Comment s’appellent le suricate et le phacochère du « Roi lion » ?', answer: 'Timon et Pumbaa' },
    { question: 'Dans quelle ville vivent les Simpson ?', answer: 'Springfield' },
    { question: 'Quel est le prénom du père de la famille Simpson ?', answer: 'Homer' },
    { question: 'Quelle marque de bière boit Homer Simpson ?', answer: 'La Duff' },
    { question: 'Comment s’appelle le fils farceur des Simpson ?', answer: 'Bart' },
    { question: 'Quel cow-boy est le jouet préféré d’Andy dans « Toy Story » ?', answer: 'Woody' },
    { question: 'Quel ranger de l’espace crie « Vers l’infini et au-delà ! » ?', answer: 'Buzz l’Éclair' },
    { question: 'Quel petit poisson-clown son père cherche-t-il dans un film Pixar ?', answer: 'Nemo' },
    { question: 'Quelle reine d’Arendelle a le pouvoir de créer de la glace ?', answer: 'Elsa' },
    { question: 'Quel bonhomme de neige accompagne Anna et Elsa ?', answer: 'Olaf' },
    { question: 'Comment s’appelle l’ogre vert de DreamWorks ?', answer: 'Shrek' },
    { question: 'Quel animal bavard accompagne Shrek ?', answer: 'L’Âne' },
    { question: 'Quel personnage vit dans un ananas sous la mer ?', answer: 'Bob l’éponge' },
    { question: 'Comment s’appelle l’étoile de mer meilleure amie de Bob l’éponge ?', answer: 'Patrick' },
    { question: 'Quel Pokémon jaune électrique accompagne Sacha ?', answer: 'Pikachu' },
    { question: 'Quel chat poursuit sans relâche la souris Jerry ?', answer: 'Tom' },
    { question: 'Quel lapin demande « Quoi d’neuf, docteur ? » ?', answer: 'Bugs Bunny' },
    { question: 'Quel druide prépare la potion magique d’Astérix ?', answer: 'Panoramix' },
    { question: 'Comment s’appelle le petit chien d’Obélix ?', answer: 'Idéfix' },
    { question: 'Comment s’appelle le chien de Tintin ?', answer: 'Milou' },
    { question: 'Quel capitaine jure « Mille millions de mille sabords ! » ?', answer: 'Le capitaine Haddock' },
    { question: 'Comment s’appellent les trois neveux de Donald ?', answer: 'Riri, Fifi et Loulou' },
    { question: 'Quel rat cuisinier est le héros de « Ratatouille » ?', answer: 'Rémy' },
    { question: 'Quel petit robot nettoie seul la Terre dans un film Pixar de 2008 ?', answer: 'WALL-E' },
    { question: 'Quels petits êtres bleus vivent dans des maisons-champignons ?', answer: 'Les Schtroumpfs' },
    { question: 'Quel dessinateur belge a créé les Schtroumpfs ?', answer: 'Peyo' },
    { question: 'Quel sorcier poursuit les Schtroumpfs avec son chat Azraël ?', answer: 'Gargamel' },
    { question: 'Quel pantin de bois voit son nez s’allonger quand il ment ?', answer: 'Pinocchio' },
    // Séries
    { question: 'Dans quelle série six amis se retrouvent-ils au Central Perk ?', answer: 'Friends' },
    { question: 'Comment s’appelle le singe de Ross dans « Friends » ?', answer: 'Marcel' },
    { question: 'Quel professeur de chimie est le héros de « Breaking Bad » ?', answer: 'Walter White' },
    { question: 'Quelle série suit notamment les familles Stark et Lannister ?', answer: 'Game of Thrones' },
    { question: 'Quelle héroïne de « Game of Thrones » est surnommée la Mère des dragons ?', answer: 'Daenerys Targaryen' },
    { question: 'Dans quelle petite ville se déroule « Stranger Things » ?', answer: 'Hawkins' },
    { question: 'Quelle série espagnole suit des braqueurs portant des noms de villes ?', answer: 'La casa de papel' },
    { question: 'Comment surnomme-t-on le cerveau des braqueurs de « La casa de papel » ?', answer: 'Le Professeur' },
    { question: 'Quelle série coréenne de Netflix met en scène des jeux d’enfants aux enjeux mortels ?', answer: 'Squid Game' },
    { question: 'Dans « How I Met Your Mother », qui répète « Legen… wait for it… dary » ?', answer: 'Barney Stinson' },
    { question: 'Qui est le patron de Dunder Mifflin dans « The Office » version américaine ?', answer: 'Michael Scott' },
    { question: 'Dans « The Big Bang Theory », quel physicien a sa place attitrée sur le canapé ?', answer: 'Sheldon Cooper' },
    { question: 'Quelle série comique française revisite la légende du roi Arthur ?', answer: 'Kaamelott' },
    { question: 'Qui a créé la série « Kaamelott » ?', answer: 'Alexandre Astier' },
    { question: 'Quelle série de la BBC transpose un célèbre détective dans le Londres actuel ?', answer: 'Sherlock' },
    { question: 'Quelle reine est au cœur de la série « The Crown » ?', answer: 'Élisabeth II' },
    { question: 'Quelle série médicale suit l’interne Meredith Grey ?', answer: 'Grey’s Anatomy' },
    { question: 'Dans « Prison Break », quel frère se fait volontairement incarcérer ?', answer: 'Michael Scofield' },
    { question: 'Quelle série Netflix suit une Américaine qui part travailler à Paris ?', answer: 'Emily in Paris' },
    { question: 'Dans quelle ville se déroule la série « Friends » ?', answer: 'New York' },
    // Jeux vidéo
    { question: 'Quel plombier moustachu est la mascotte de Nintendo ?', answer: 'Mario' },
    { question: 'Comment s’appelle le frère de Mario ?', answer: 'Luigi' },
    { question: 'Quelle princesse Mario doit-il souvent sauver ?', answer: 'Peach' },
    { question: 'Quel hérisson bleu est la mascotte de Sega ?', answer: 'Sonic' },
    { question: 'Dans quel jeu construit-on et survit-on dans un monde fait de cubes ?', answer: 'Minecraft' },
    { question: 'Quel battle royale d’Epic Games est célèbre pour ses danses ?', answer: 'Fortnite' },
    { question: 'Quel jeu soviétique consiste à empiler des pièces géométriques qui tombent ?', answer: 'Tetris' },
    { question: 'Comment s’appelle le héros de la série « The Legend of Zelda » ?', answer: 'Link' },
    { question: 'Quelle console de Sony est sortie au Japon en 1994 ?', answer: 'La PlayStation' },
    { question: 'Quel personnage jaune mange des pac-gommes en fuyant des fantômes ?', answer: 'Pac-Man' },
    { question: 'Quel jeu de Rockstar se déroule dans la ville de Los Santos ?', answer: 'GTA V' },
    { question: 'Dans « Among Us », comment appelle-t-on les traîtres ?', answer: 'Les imposteurs' },
    { question: 'Quelle console hybride de Nintendo est sortie en 2017 ?', answer: 'La Switch' },
    { question: 'Combien de Pokémon compte le Pokédex de la première génération ?', answer: '151' },
    { question: 'Quel roi des Koopa crachant du feu est l’ennemi juré de Mario ?', answer: 'Bowser' },
    { question: 'Quelle aventurière archéologue est l’héroïne de « Tomb Raider » ?', answer: 'Lara Croft' },
    { question: 'Quel gorille à cravate est une star de Nintendo ?', answer: 'Donkey Kong' },
    { question: 'Quelle langue imaginaire parlent les personnages des « Sims » ?', answer: 'Le simlish' },
    // Internet
    { question: 'Que signifie l’acronyme « LOL » ?', answer: 'Laughing out loud' },
    { question: 'Que signifie le sigle « MDR » ?', answer: 'Mort de rire' },
    { question: 'Quel réseau social avait un oiseau bleu pour logo avant de devenir X ?', answer: 'Twitter' },
    { question: 'Comment s’appelle le mème du chien shiba accompagné de « such wow » ?', answer: 'Doge' },
    { question: 'Que signifie l’acronyme « FOMO » ?', answer: 'Fear of missing out' },
    { question: 'Comment appelle-t-on un internaute qui poste pour provoquer et énerver ?', answer: 'Un troll' },
    { question: 'Que signifie l’acronyme « IRL » ?', answer: 'In real life' },
    { question: 'Quelle chanson de Rick Astley est au cœur du « Rickroll » ?', answer: 'Never Gonna Give You Up' },
    { question: 'Quel réseau social a pour logo un fantôme sur fond jaune ?', answer: 'Snapchat' },
    { question: 'Comment appelle-t-on une photo de soi prise par soi-même ?', answer: 'Un selfie' },
    { question: 'Que signifie l’acronyme « TL;DR » ?', answer: 'Too long; didn’t read' },
    { question: 'Quelle application de vidéos courtes appartient à ByteDance ?', answer: 'TikTok' },
    { question: 'Que signifie l’acronyme « GG » dans les jeux en ligne ?', answer: 'Good game' },
    // Expressions de soirée
    { question: 'Que signifie « avoir la gueule de bois » ?', answer: 'Être mal le lendemain d’une cuite' },
    { question: 'Que veut dire « faire la tournée des grands-ducs » ?', answer: 'Enchaîner les lieux de fête' },
    { question: 'Que veut dire « boire un canon » ?', answer: 'Boire un verre de vin' },
    { question: 'Que signifie « faire la grasse matinée » ?', answer: 'Dormir tard le matin' },
    { question: 'Que signifie « tirer les vers du nez » à quelqu’un ?', answer: 'Le faire parler' },
    { question: 'Que signifie « être pompette » ?', answer: 'Être un peu ivre' },
    { question: 'Que signifie « mettre les petits plats dans les grands » ?', answer: 'Recevoir avec beaucoup de soin' },
    { question: 'Comment dit-on « santé ! » en espagnol pour trinquer ?', answer: 'Salud' },
    { question: 'Comment dit-on « santé ! » en allemand pour trinquer ?', answer: 'Prost' },
    { question: 'Comment dit-on « santé ! » en italien pour trinquer ?', answer: 'Cin cin (ou Salute)' },
    { question: 'Que signifie « faire chou blanc » ?', answer: 'Échouer' },
    { question: 'Que veut dire « avoir la dalle » ?', answer: 'Avoir faim' },
    // Fêtes du monde
    { question: 'Dans quel pays célèbre-t-on le Día de los Muertos ?', answer: 'Le Mexique' },
    { question: 'Quelle ville brésilienne accueille le carnaval le plus célèbre du monde ?', answer: 'Rio de Janeiro' },
    { question: 'Quelle fête indienne se célèbre en se lançant des poudres colorées ?', answer: 'Holi' },
    { question: 'Quelle ville espagnole organise la Tomatina, une bataille de tomates ?', answer: 'Buñol' },
    { question: 'Quelle ville espagnole est célèbre pour les fêtes de San Fermín ?', answer: 'Pampelune' },
    { question: 'À quelle date fête-t-on la Saint-Patrick ?', answer: 'Le 17 mars' },
    { question: 'Quelle couleur porte-t-on traditionnellement à la Saint-Patrick ?', answer: 'Le vert' },
    { question: 'Quel jour célèbre-t-on Halloween ?', answer: 'Le 31 octobre' },
    { question: 'Quelle ville de Louisiane est célèbre pour son Mardi gras ?', answer: 'La Nouvelle-Orléans' },
    { question: 'Quelle fête française a lieu chaque 21 juin ?', answer: 'La Fête de la musique' },
    { question: 'En quel mois commence l’Oktoberfest de Munich ?', answer: 'En septembre' },
    { question: 'Quelle fête américaine se célèbre avec une dinde le 4e jeudi de novembre ?', answer: 'Thanksgiving' },
    { question: 'Quel festival éphémère se tient chaque année dans le désert du Nevada ?', answer: 'Burning Man' },
    { question: 'Quel festival de musique mythique s’est tenu en 1969 dans l’État de New York ?', answer: 'Woodstock' },
    // Cinéma populaire
    { question: 'Quel est le prénom de l’agent 007 ?', answer: 'James' },
    { question: 'Dans quelle saga trouve-t-on les chevaliers Jedi ?', answer: 'Star Wars' },
    { question: 'Qui est le père de Luke Skywalker ?', answer: 'Dark Vador' },
    { question: 'Quel jeune sorcier porte une cicatrice en forme d’éclair ?', answer: 'Harry Potter' },
    { question: 'Dans quelle maison de Poudlard Harry Potter est-il réparti ?', answer: 'Gryffondor' },
    { question: 'Dans quel volcan l’Anneau unique doit-il être détruit ?', answer: 'La montagne du Destin' },
    { question: 'Qui a réalisé « Titanic » (1997) ?', answer: 'James Cameron' },
    { question: 'Quel acteur incarne Jack dans « Titanic » ?', answer: 'Leonardo DiCaprio' },
    { question: 'Dans « Retour vers le futur », quelle voiture sert de machine à remonter le temps ?', answer: 'Une DeLorean' },
    { question: 'Quelle vitesse la DeLorean doit-elle atteindre pour voyager dans le temps ?', answer: '88 miles à l’heure' },
    { question: 'Quel film de Spielberg (1975) met en scène un grand requin blanc ?', answer: 'Les Dents de la mer' },
    { question: 'Quel parc à thème est peuplé de dinosaures dans le film de 1993 ?', answer: 'Jurassic Park' },
    { question: 'Dans « Matrix », de quelle couleur est la pilule choisie par Neo ?', answer: 'Rouge' },
    { question: 'Quel super-héros est l’alter ego de Bruce Wayne ?', answer: 'Batman' },
    { question: 'Quel est le vrai nom de Spider-Man ?', answer: 'Peter Parker' },
    { question: 'Quel acteur incarne Iron Man dans les films Marvel ?', answer: 'Robert Downey Jr.' },
    { question: 'Quel métal indestructible recouvre le squelette de Wolverine ?', answer: 'L’adamantium' },
    { question: 'Quelle comédie de Dany Boon (2008) se déroule dans le Nord ?', answer: 'Bienvenue chez les Ch’tis' },
    { question: 'Quel film français de 2011 réunit Omar Sy et François Cluzet ?', answer: 'Intouchables' },
    { question: 'Quelle actrice incarne Amélie Poulain ?', answer: 'Audrey Tautou' },
    { question: 'Dans quel film de 1993 voit-on Godefroy de Montmirail et Jacquouille ?', answer: 'Les Visiteurs' },
    { question: 'Quelle danse est devenue culte grâce à « La Cité de la peur » ?', answer: 'La Carioca' },
    { question: 'Quel acteur lance « I’ll be back » dans « Terminator » ?', answer: 'Arnold Schwarzenegger' },
    { question: 'Quel studio japonais a créé Totoro ?', answer: 'Le studio Ghibli' },
    { question: 'Quel archéologue aventurier porte un fouet et un chapeau ?', answer: 'Indiana Jones' },
    { question: 'Qui a réalisé « Pulp Fiction » ?', answer: 'Quentin Tarantino' },
    { question: 'Dans « Forrest Gump », à quoi la vie est-elle comparée ?', answer: 'Une boîte de chocolats' },
    { question: 'Quel acteur incarne Ken dans le film « Barbie » (2023) ?', answer: 'Ryan Gosling' },
    { question: 'Quel film Pixar se déroule dans la tête d’une fille, avec Joie et Tristesse ?', answer: 'Vice-versa' },
    { question: 'Quel sorcier gris guide la Communauté de l’Anneau ?', answer: 'Gandalf' },
  ],

  hot: [
    // Mythologie de l’amour
    { question: 'Quelle est la déesse grecque de l’amour et de la beauté ?', answer: 'Aphrodite' },
    { question: 'Quelle déesse romaine de l’amour a donné son nom à une planète ?', answer: 'Vénus' },
    { question: 'Quel dieu romain ailé rend amoureux avec ses flèches ?', answer: 'Cupidon' },
    { question: 'Quel est l’équivalent grec de Cupidon ?', answer: 'Éros' },
    { question: 'Selon Hésiode, de quoi est née Aphrodite ?', answer: 'De l’écume de la mer' },
    { question: 'Quel dieu forgeron est le mari d’Aphrodite ?', answer: 'Héphaïstos' },
    { question: 'Avec quel dieu de la guerre Aphrodite trompe-t-elle son mari ?', answer: 'Arès' },
    { question: 'Quelle mortelle aimée d’Éros porte un nom qui signifie « âme » ?', answer: 'Psyché' },
    { question: 'Quel prince troyen part avec Hélène, déclenchant la guerre de Troie ?', answer: 'Pâris' },
    { question: 'Quel fruit Pâris remet-il à la déesse qu’il juge la plus belle ?', answer: 'Une pomme d’or' },
    { question: 'Quel sculpteur de la mythologie tombe amoureux de sa propre statue ?', answer: 'Pygmalion' },
    { question: 'Quel jeune homme tombe amoureux de son propre reflet ?', answer: 'Narcisse' },
    { question: 'Quelle nymphe amoureuse de Narcisse ne peut que répéter les derniers mots entendus ?', answer: 'Écho' },
    { question: 'Quel musicien descend aux Enfers pour ramener son épouse Eurydice ?', answer: 'Orphée' },
    { question: 'Quel dieu grec du vin et de la fête est appelé Bacchus à Rome ?', answer: 'Dionysos' },
    { question: 'Comment appelle-t-on les fêtes romaines débridées en l’honneur de Bacchus ?', answer: 'Les bacchanales' },
    { question: 'Quel dieu de la fertilité est représenté avec un sexe démesuré ?', answer: 'Priape' },
    { question: 'Quel terme médical, désignant une érection prolongée, vient de ce dieu ?', answer: 'Le priapisme' },
    { question: 'Quelle déesse nordique est associée à l’amour et à la beauté ?', answer: 'Freyja' },
    { question: 'Quel jour de la semaine doit son nom à Vénus ?', answer: 'Le vendredi' },
    { question: 'Quel héros grec abandonne Ariane sur l’île de Naxos ?', answer: 'Thésée' },
    { question: 'Quel couple d’amants babyloniens chez Ovide a inspiré « Roméo et Juliette » ?', answer: 'Pyrame et Thisbé' },
    { question: 'Quelle épouse fidèle attend Ulysse pendant vingt ans ?', answer: 'Pénélope' },
    { question: 'Quelle nymphe retient Ulysse sept ans sur son île ?', answer: 'Calypso' },
    { question: 'De quelle divinité vient le mot « aphrodisiaque » ?', answer: 'Aphrodite' },
    { question: 'Quel adjectif lié au désir dérive du nom du dieu Éros ?', answer: 'Érotique' },
    { question: 'Quel adjectif tiré de Vénus qualifiait autrefois les maladies sexuelles ?', answer: 'Vénérien' },
    // Histoire de la séduction
    { question: 'Quelle reine d’Égypte fut l’amante de Jules César puis de Marc Antoine ?', answer: 'Cléopâtre' },
    { question: 'Quel aventurier vénitien du XVIIIe siècle est devenu synonyme de séducteur ?', answer: 'Casanova' },
    { question: 'Quel séducteur espagnol légendaire a inspiré Molière et Mozart ?', answer: 'Don Juan' },
    { question: 'Quel opéra de Mozart met en scène ce séducteur impénitent ?', answer: 'Don Giovanni' },
    { question: 'Quel valet tient le catalogue des conquêtes de Don Giovanni ?', answer: 'Leporello' },
    { question: 'Selon l’air du catalogue, combien de conquêtes Don Giovanni compte-t-il en Espagne ?', answer: '1 003' },
    { question: 'Quelle favorite de Louis XV a donné son nom à une coiffure ?', answer: 'Madame de Pompadour' },
    { question: 'Quel roi de France était surnommé le Vert-Galant pour ses nombreuses maîtresses ?', answer: 'Henri IV' },
    { question: 'Quel roi d’Angleterre a eu six épouses ?', answer: 'Henri VIII' },
    { question: 'Quel saint fête-t-on le 14 février ?', answer: 'Saint Valentin' },
    { question: 'Quel président français est mort à l’Élysée en 1899 en galante compagnie ?', answer: 'Félix Faure' },
    { question: 'Quel écrivain libertin a donné son nom au sadisme ?', answer: 'Le marquis de Sade' },
    { question: 'Quel écrivain autrichien a donné son nom au masochisme ?', answer: 'Leopold von Sacher-Masoch' },
    { question: 'Quel roman de Laclos raconte les manœuvres de séduction de Valmont et Merteuil ?', answer: 'Les Liaisons dangereuses' },
    { question: 'Quel traité indien antique est consacré à l’art d’aimer ?', answer: 'Le Kamasutra' },
    { question: 'En quelle langue le Kamasutra a-t-il été écrit ?', answer: 'Le sanskrit' },
    { question: 'À quel auteur indien attribue-t-on le Kamasutra ?', answer: 'Vatsyayana' },
    { question: 'Quel poète latin a écrit « L’Art d’aimer » ?', answer: 'Ovide' },
    { question: 'Quelle île grecque a donné le mot « lesbienne » ?', answer: 'Lesbos' },
    { question: 'Quelle poétesse grecque a donné le mot « saphisme » ?', answer: 'Sappho' },
    { question: 'Quel philosophe médiéval a vécu une passion célèbre avec Héloïse ?', answer: 'Pierre Abélard' },
    { question: 'Dans quelle ville italienne visite-t-on la maison dite de Juliette ?', answer: 'Vérone' },
    { question: 'Quel monument indien un empereur a-t-il fait bâtir en mémoire de son épouse ?', answer: 'Le Taj Mahal' },
    { question: 'Quel empereur moghol a fait construire le Taj Mahal ?', answer: 'Shah Jahan' },
    { question: 'Quel pont parisien croulait sous les cadenas d’amoureux avant leur retrait en 2015 ?', answer: 'Le pont des Arts' },
    { question: 'Combien de fois l’actrice Elizabeth Taylor s’est-elle mariée ?', answer: 'Huit fois' },
    { question: 'Quel acteur Elizabeth Taylor a-t-elle épousé deux fois ?', answer: 'Richard Burton' },
    { question: 'Quelle actrice a chanté « Happy Birthday, Mr. President » à Kennedy en 1962 ?', answer: 'Marilyn Monroe' },
    { question: 'Quel parfum Marilyn Monroe disait-elle porter pour seule tenue de nuit ?', answer: 'Chanel n° 5' },
    { question: 'Quelle actrice est la star de « Et Dieu… créa la femme » (1956) ?', answer: 'Brigitte Bardot' },
    { question: 'Quelle chanson de 1969 de Gainsbourg et Birkin fut censurée pour ses soupirs ?', answer: 'Je t’aime… moi non plus' },
    { question: 'Quelle chanson estivale de Gainsbourg (1978) parle de mer, de sexe et de soleil ?', answer: 'Sea, Sex and Sun' },
    { question: 'Quel magazine fondé par Hugh Hefner a un lapin pour logo ?', answer: 'Playboy' },
    { question: 'En quelle année est paru le premier numéro de Playboy ?', answer: '1953' },
    { question: 'Quel cabaret parisien, ouvert en 1889, a popularisé le french cancan ?', answer: 'Le Moulin-Rouge' },
    { question: 'Quel cabaret de l’avenue George-V est célèbre pour ses spectacles de nu artistique ?', answer: 'Le Crazy Horse' },
    { question: 'Quelle meneuse de revue dansait vêtue d’une ceinture de bananes ?', answer: 'Joséphine Baker' },
    { question: 'Quelle danseuse exotique néerlandaise fut accusée d’espionnage pendant la Grande Guerre ?', answer: 'Mata Hari' },
    { question: 'Au XVIIe siècle, que désignait d’abord le mot « libertin » ?', answer: 'Un libre penseur' },
    { question: 'Comment appelait-on au XIXe siècle les femmes entretenues du demi-monde ?', answer: 'Les courtisanes' },
    { question: 'Quel roman d’Alexandre Dumas fils raconte l’amour d’une courtisane ?', answer: 'La Dame aux camélias' },
    { question: 'Quel opéra de Verdi est tiré de « La Dame aux camélias » ?', answer: 'La traviata' },
    { question: 'Quel roman de Flaubert a fait scandale avec l’adultère de son héroïne Emma ?', answer: 'Madame Bovary' },
    { question: 'Quel roman de D. H. Lawrence raconte la liaison d’une aristocrate et de son garde-chasse ?', answer: 'L’Amant de lady Chatterley' },
    { question: 'Quelle écrivaine a signé le recueil érotique « Vénus Erotica » ?', answer: 'Anaïs Nin' },
    { question: 'Quel livre de la Bible est un long poème d’amour sensuel ?', answer: 'Le Cantique des cantiques' },
    // Art et nus
    { question: 'Quel peintre a réalisé « L’Origine du monde » ?', answer: 'Gustave Courbet' },
    { question: 'Dans quel musée parisien est exposée « L’Origine du monde » ?', answer: 'Le musée d’Orsay' },
    { question: 'Quel peintre autrichien a peint « Le Baiser », couvert de feuilles d’or ?', answer: 'Gustav Klimt' },
    { question: 'Quel sculpteur français a réalisé « Le Baiser » en marbre ?', answer: 'Auguste Rodin' },
    { question: 'Quel tableau de Manet (1863) montre une femme nue pique-niquant avec deux hommes habillés ?', answer: 'Le Déjeuner sur l’herbe' },
    { question: 'Quel tableau de Manet montre une courtisane nue fixant le spectateur ?', answer: 'Olympia' },
    { question: 'Quel tableau de Botticelli montre une déesse nue debout sur un coquillage ?', answer: 'La Naissance de Vénus' },
    { question: 'Quel peintre vénitien a peint « La Vénus d’Urbin » ?', answer: 'Titien' },
    { question: 'Quel tableau de Fragonard montre une jeune femme sur une balançoire dévoilant ses jupons ?', answer: 'L’Escarpolette' },
    { question: 'Quelle statue grecque sans bras est exposée au Louvre ?', answer: 'La Vénus de Milo' },
    { question: 'Quel triptyque de Jérôme Bosch montre un paradis de plaisirs charnels ?', answer: 'Le Jardin des délices' },
    // Anatomie et santé sexuelle
    { question: 'Quel organe a pour seule fonction connue le plaisir ?', answer: 'Le clitoris' },
    { question: 'Quelle hormone est surnommée « l’hormone de l’amour » ou « du câlin » ?', answer: 'L’ocytocine' },
    { question: 'Quelle hormone sexuelle est principalement produite par les testicules ?', answer: 'La testostérone' },
    { question: 'Quelles hormones sexuelles sont principalement produites par les ovaires ?', answer: 'Œstrogènes et progestérone' },
    { question: 'Le point G doit son nom à quel gynécologue allemand ?', answer: 'Ernst Gräfenberg' },
    { question: 'Quel contraceptif protège aussi des infections sexuellement transmissibles ?', answer: 'Le préservatif' },
    { question: 'Que signifie le sigle IST ?', answer: 'Infection sexuellement transmissible' },
    { question: 'Combien de jours dure en moyenne un cycle menstruel ?', answer: '28 jours' },
    { question: 'Comment s’appelle la libération d’un ovule par l’ovaire ?', answer: 'L’ovulation' },
    { question: 'Comment appelle-t-on le temps de récupération après l’orgasme masculin ?', answer: 'La période réfractaire' },
    { question: 'Quelle zone musculaire renforce-t-on avec les exercices de Kegel ?', answer: 'Le périnée' },
    { question: 'Quel couple de chercheurs américains a étudié la réponse sexuelle humaine dans les années 1960 ?', answer: 'Masters et Johnson' },
    { question: 'Quel biologiste américain a publié des rapports célèbres sur la sexualité en 1948 et 1953 ?', answer: 'Alfred Kinsey' },
    { question: 'Quel père de la psychanalyse a théorisé la libido ?', answer: 'Sigmund Freud' },
    { question: 'Que signifie le mot latin « libido » ?', answer: 'Le désir' },
    { question: 'Quelle molécule est commercialisée sous le nom de Viagra ?', answer: 'Le sildénafil' },
    { question: 'Quel laboratoire a mis le Viagra sur le marché ?', answer: 'Pfizer' },
    { question: 'Contre quelle maladie le Viagra était-il initialement testé ?', answer: 'L’angine de poitrine' },
    { question: 'De quelle couleur est le célèbre comprimé de Viagra ?', answer: 'Bleu' },
    { question: 'Quelle hormone détectent les tests de grossesse ?', answer: 'L’hCG' },
    { question: 'Combien de temps des spermatozoïdes peuvent-ils survivre dans l’appareil génital féminin ?', answer: 'Jusqu’à 5 jours' },
    { question: 'Combien de temps un ovule reste-t-il fécondable après l’ovulation ?', answer: 'Environ 24 heures' },
    { question: 'Quelle glande masculine de la taille d’une châtaigne produit une partie du sperme ?', answer: 'La prostate' },
    { question: 'Comment s’appelle la peau qui recouvre le gland ?', answer: 'Le prépuce' },
    { question: 'Comment s’appelle l’ensemble des organes génitaux externes féminins ?', answer: 'La vulve' },
    { question: 'Que signifie le mot latin « vagina » ?', answer: 'Gaine (ou fourreau)' },
    { question: 'Quel anatomiste italien a donné son nom aux trompes reliant ovaires et utérus ?', answer: 'Fallope (Falloppio)' },
    { question: 'Quel virus est responsable du sida ?', answer: 'Le VIH' },
    { question: 'Contre quel virus sexuellement transmissible un vaccin prévient-il le cancer du col de l’utérus ?', answer: 'Le papillomavirus (HPV)' },
    { question: 'Que signifie le sigle PrEP, traitement préventif contre le VIH ?', answer: 'Prophylaxie pré-exposition' },
    { question: 'Quelle journée mondiale a lieu chaque 1er décembre ?', answer: 'La Journée mondiale contre le sida' },
    { question: 'Quel neurotransmetteur du circuit de la récompense est libéré pendant le plaisir ?', answer: 'La dopamine' },
    { question: 'Comment appelle-t-on la contraception d’urgence prise après un rapport à risque ?', answer: 'La pilule du lendemain' },
    { question: 'Quel dispositif contraceptif, en cuivre ou hormonal, se place dans l’utérus ?', answer: 'Le stérilet (DIU)' },
    { question: 'Comment s’appelle la contraception masculine chirurgicale définitive ?', answer: 'La vasectomie' },
    { question: 'En quelle année la loi Neuwirth a-t-elle autorisé la contraception en France ?', answer: '1967' },
    { question: 'En quelle matière sont fabriqués la plupart des préservatifs ?', answer: 'Le latex' },
    { question: 'Avec quoi fabriquait-on des préservatifs avant le caoutchouc ?', answer: 'Des boyaux d’animaux' },
    { question: 'Quelle infection vénérienne était surnommée « le mal de Naples » ?', answer: 'La syphilis' },
    { question: 'Selon l’adage, quel est le principal organe sexuel ?', answer: 'Le cerveau' },
    { question: 'Comment appelle-t-on l’absence durable d’attirance sexuelle, vécue comme une orientation ?', answer: 'L’asexualité' },
    // Vocabulaire et expressions
    { question: 'Que signifie l’expression « faire des galipettes » ?', answer: 'Faire l’amour' },
    { question: 'Que signifie l’expression « conter fleurette » ?', answer: 'Faire la cour' },
    { question: 'Que signifie l’expression « avoir le béguin » ?', answer: 'Être amoureux' },
    { question: 'Que veut dire « avoir un ticket » avec quelqu’un ?', answer: 'Lui plaire' },
    { question: 'Que signifie « rouler une pelle » ?', answer: 'Embrasser avec la langue' },
    { question: 'Comment les anglophones appellent-ils un baiser avec la langue ?', answer: 'Un French kiss' },
    { question: 'Que veut dire « faire du gringue » ?', answer: 'Draguer' },
    { question: 'Que désigne l’expression « la petite mort » ?', answer: 'L’orgasme' },
    { question: 'Comment appelle-t-on un homme entretenu par ses maîtresses ?', answer: 'Un gigolo' },
    { question: 'Que désigne le mot « cougar » ?', answer: 'Une séductrice d’hommes plus jeunes' },
    { question: 'Comment appelle-t-on le voyage des jeunes mariés ?', answer: 'La lune de miel' },
    { question: 'Que signifie « s’envoyer en l’air » ?', answer: 'Faire l’amour' },
    { question: 'Comment appelle-t-on l’attirance érotique pour les pieds ?', answer: 'La podophilie' },
    { question: 'Comment appelle-t-on le fait d’aimer plusieurs partenaires avec l’accord de tous ?', answer: 'Le polyamour' },
    { question: 'Comment appelle-t-on l’attirance pour l’intelligence de l’autre ?', answer: 'La sapiosexualité' },
    { question: 'Comment appelle-t-on en anglais une aventure d’un soir ?', answer: 'Un one-night stand' },
    { question: 'Que signifie « avoir un polichinelle dans le tiroir » ?', answer: 'Être enceinte' },
    { question: 'Que signifie « se faire larguer » ?', answer: 'Se faire quitter' },
    { question: 'Que signifie l’expression « tenir la chandelle » ?', answer: 'Être de trop auprès d’un couple' },
    { question: 'Comment appelle-t-on quelqu’un qui tombe amoureux très facilement ?', answer: 'Un cœur d’artichaut' },
    { question: 'Que signifie « ghoster » quelqu’un ?', answer: 'Disparaître sans explication' },
    { question: 'Quelle application de rencontre a rendu célèbre le « swipe » à droite ?', answer: 'Tinder' },
    { question: 'Comment appelle-t-on un intérêt réciproque sur une appli de rencontre ?', answer: 'Un match' },
    { question: 'Quel mot désigne l’envoi de messages ou photos coquins par téléphone ?', answer: 'Le sexting' },
    { question: 'Quel mot désigne l’échange consenti de partenaires entre couples ?', answer: 'L’échangisme' },
    { question: 'Comment appelle-t-on une relation amoureuse à trois sous le même toit ?', answer: 'Un ménage à trois' },
    { question: 'Comment appelle-t-on familièrement une personne trompée ?', answer: 'Un cocu' },
    { question: 'Selon l’expression, que porte sur la tête une personne trompée ?', answer: 'Des cornes' },
    { question: 'Que signifie « XOXO » à la fin d’un message ?', answer: 'Bisous et câlins' },
    { question: 'Quel émoji de fruit est détourné pour évoquer les fesses ?', answer: 'La pêche' },
    { question: 'Quel émoji de légume est détourné pour évoquer le sexe masculin ?', answer: 'L’aubergine' },
    { question: 'Après « un peu, beaucoup, passionnément », que dit-on en effeuillant la marguerite ?', answer: 'À la folie' },
    { question: 'Comment appelle-t-on le fait de se frotter le bout du nez en guise de bisou ?', answer: 'Un bisou esquimau' },
    { question: 'Quel muscle permet de faire la bouche en baiser ?', answer: 'L’orbiculaire de la bouche' },
    { question: 'Comment appelle-t-on la science du baiser ?', answer: 'La philématologie' },
    { question: 'Comment appelle-t-on la peur de tomber amoureux ?', answer: 'La philophobie' },
    { question: 'Comment appelle-t-on la peur d’être nu ou de voir la nudité ?', answer: 'La gymnophobie' },
    { question: 'Comment appelle-t-on médicalement un suçon ?', answer: 'Un hématome (ecchymose)' },
    { question: 'Quelle position amoureuse porte le nom d’un nombre symétrique ?', answer: 'Le 69' },
    { question: 'Quel art japonais du bondage utilise des cordes ?', answer: 'Le shibari' },
    // Aphrodisiaques, fêtes et mariage
    { question: 'Quel coquillage cru est l’aliment aphrodisiaque le plus célèbre ?', answer: 'L’huître' },
    { question: 'Quelle boisson des Aztèques, à base de cacao, était réputée aphrodisiaque ?', answer: 'Le chocolat' },
    { question: 'Quelle fête chinoise est surnommée la Saint-Valentin chinoise ?', answer: 'Qixi' },
    { question: 'Au Japon, qui offre traditionnellement du chocolat le 14 février ?', answer: 'Les femmes' },
    { question: 'Comment s’appelle la fête japonaise du 14 mars où les hommes rendent la pareille ?', answer: 'Le White Day' },
    { question: 'Quelle fleur offre-t-on traditionnellement à la Saint-Valentin ?', answer: 'La rose rouge' },
    { question: 'Sous quelle plante est-il de tradition de s’embrasser pendant les fêtes de fin d’année ?', answer: 'Le gui' },
    { question: 'Dans quelle ville se trouve le quartier rouge De Wallen ?', answer: 'Amsterdam' },
    { question: 'Dans quelle ville américaine peut-on se marier en vitesse dans de petites chapelles ?', answer: 'Las Vegas' },
    { question: 'Quel pays a été le premier à légaliser le mariage homosexuel, en 2001 ?', answer: 'Les Pays-Bas' },
    { question: 'En quelle année la France a-t-elle ouvert le mariage aux couples de même sexe ?', answer: '2013' },
    { question: 'Que signifie le sigle PACS ?', answer: 'Pacte civil de solidarité' },
    { question: 'En quelle année le PACS a-t-il été créé en France ?', answer: '1999' },
    { question: 'Combien d’années de mariage fête-t-on aux noces d’or ?', answer: '50 ans' },
    { question: 'Combien d’années de mariage fête-t-on aux noces d’argent ?', answer: '25 ans' },
    { question: 'Combien d’années de mariage fête-t-on aux noces de diamant ?', answer: '60 ans' },
    { question: 'Quelles noces fête-t-on après un an de mariage ?', answer: 'Les noces de coton' },
    { question: 'À quel doigt porte-t-on traditionnellement l’alliance en France ?', answer: 'L’annulaire gauche' },
    { question: 'Quelle veine censée relier l’annulaire au cœur explique la place de l’alliance ?', answer: 'La vena amoris (veine de l’amour)' },
    { question: 'Quelle pièce de lingerie de la mariée le marié retire-t-il traditionnellement ?', answer: 'La jarretière' },
    { question: 'Quelle reine a popularisé la robe de mariée blanche en 1840 ?', answer: 'La reine Victoria' },
    { question: 'Dans quel quartier de Paris se trouve le mur des Je t’aime ?', answer: 'Montmartre' },
    // Lingerie, danse, spectacles
    { question: 'Quel sous-vêtement serrait la taille des élégantes du XIXe siècle ?', answer: 'Le corset' },
    { question: 'Quelle marque américaine de lingerie défilait avec ses « Anges » ?', answer: 'Victoria’s Secret' },
    { question: 'Quel accessoire de lingerie retient les bas à l’aide d’attaches ?', answer: 'Le porte-jarretelles' },
    { question: 'Quel genre de spectacle rétro mêle effeuillage, humour et paillettes ?', answer: 'Le burlesque' },
    { question: 'Quel maillot de bain deux-pièces a été présenté à Paris en 1946 par Louis Réard ?', answer: 'Le bikini' },
    { question: 'Le bikini doit son nom à quel lieu ?', answer: 'Un atoll des îles Marshall' },
    { question: 'Quelle danse sensuelle est originaire de République dominicaine ?', answer: 'La bachata' },
    { question: 'Quelle danse sensuelle est née sur les rives du Río de la Plata ?', answer: 'Le tango' },
    { question: 'Quelle troupe américaine de strip-teaseurs porte le nom d’un style de meubles ?', answer: 'Les Chippendales' },
    { question: 'Comment appelle-t-on la pratique de la nudité en collectivité ?', answer: 'Le naturisme' },
    { question: 'Quelle île varoise abrite un célèbre village naturiste ?', answer: 'L’île du Levant' },
    { question: 'Quelle station de l’Hérault est réputée pour son quartier naturiste ?', answer: 'Le Cap d’Agde' },
    // Cinéma, séries et musique coquins
    { question: 'Quel film de 1987 avec Patrick Swayze raconte des cours de danse lascive ?', answer: 'Dirty Dancing' },
    { question: 'Quel est le surnom de l’héroïne de « Dirty Dancing » en VF ?', answer: 'Bébé' },
    { question: 'Quel roman d’E. L. James a pour héros Christian Grey ?', answer: 'Cinquante nuances de Grey' },
    { question: 'Comment s’appelle l’héroïne de « Cinquante nuances de Grey » ?', answer: 'Anastasia Steele' },
    { question: 'Quel acteur incarne Christian Grey au cinéma ?', answer: 'Jamie Dornan' },
    { question: 'Quel thriller de 1992 avec Sharon Stone est célèbre pour un croisement de jambes ?', answer: 'Basic Instinct' },
    { question: 'Quel dernier film de Kubrick (1999) réunit Tom Cruise et Nicole Kidman ?', answer: 'Eyes Wide Shut' },
    { question: 'Quel film érotique français de 1974 a pour vedette Sylvia Kristel ?', answer: 'Emmanuelle' },
    { question: 'Quel film de 1990 avec Julia Roberts et Richard Gere est devenu une comédie romantique culte ?', answer: 'Pretty Woman' },
    { question: 'Dans « Titanic », que porte Rose quand Jack la dessine ?', answer: 'Seulement un collier' },
    { question: 'Quel film de 1989 contient une célèbre scène d’orgasme simulé au restaurant ?', answer: 'Quand Harry rencontre Sally' },
    { question: 'Quelle série HBO suit Carrie Bradshaw et ses trois amies à New York ?', answer: 'Sex and the City' },
    { question: 'Quelle série Netflix produite par Shonda Rhimes suit les amours de la haute société de la Régence ?', answer: 'La Chronique des Bridgerton' },
    { question: 'Quel acteur joue un strip-teaseur dans « Magic Mike » ?', answer: 'Channing Tatum' },
    { question: 'Quel film anglais de 1997 montre des ouvriers au chômage devenant strip-teaseurs ?', answer: 'The Full Monty' },
    { question: 'Quelle actrice sort de l’eau en bikini blanc dans « James Bond 007 contre Dr No » ?', answer: 'Ursula Andress' },
    { question: 'Quelle chanson de Marvin Gaye (1982) parle de « guérison sexuelle » ?', answer: 'Sexual Healing' },
    { question: 'Quel trio de rap féminin a chanté « Let’s Talk About Sex » ?', answer: 'Salt-N-Pepa' },
    { question: 'Quel chanteur gallois a interprété « Sex Bomb » ?', answer: 'Tom Jones' },
    { question: 'Quel trio féminin a fait de « Lady Marmalade » un tube en 1974 ?', answer: 'Labelle' },
    { question: 'Quel livre photo érotique Madonna a-t-elle publié en 1992 ?', answer: 'Sex' },
    { question: 'Quel chanteur a sorti « I Want Your Sex » en 1987 ?', answer: 'George Michael' },
    // Le règne animal
    { question: 'Quel crustacé fixé possède le plus long pénis par rapport à sa taille ?', answer: 'La balane' },
    { question: 'Comment s’appelle l’organe sexuel double des serpents mâles ?', answer: 'Les hémipénis' },
    { question: 'Quel grand singe est connu pour apaiser les conflits par le sexe ?', answer: 'Le bonobo' },
    { question: 'Quel oiseau mâle déploie sa queue en éventail pour séduire ?', answer: 'Le paon' },
    { question: 'Comment appelle-t-on le rituel de séduction des animaux ?', answer: 'La parade nuptiale' },
    { question: 'Quel insecte femelle dévore parfois le mâle pendant l’accouplement ?', answer: 'La mante religieuse' },
    { question: 'Chez quel poisson est-ce le mâle qui porte les petits dans une poche ?', answer: 'L’hippocampe' },
    { question: 'Quels petits perroquets doivent leur nom à leur vie de couple ?', answer: 'Les inséparables' },
    { question: 'Comment appelle-t-on les signaux chimiques de séduction émis par les animaux ?', answer: 'Les phéromones' },
  ],
}
