import type { Level } from '../engine'

export interface TabooCard {
  word: string
  /** Les 5 mots qu’il est interdit de prononcer. */
  forbidden: [string, string, string, string, string]
}

/** Mot interdit — faire deviner le mot sans dire les mots interdits. */
export const tabooCards: Record<Level, TabooCard[]> = {
  soft: [
    { word: 'Plage', forbidden: ['Sable', 'Mer', 'Été', 'Vacances', 'Bronzer'] },
    { word: 'Montagne', forbidden: ['Sommet', 'Neige', 'Randonnée', 'Alpes', 'Haut'] },
    { word: 'Piscine', forbidden: ['Eau', 'Nager', 'Maillot', 'Plonger', 'Bassin'] },
    { word: 'Forêt', forbidden: ['Arbres', 'Bois', 'Champignon', 'Promenade', 'Feuilles'] },
    { word: 'Désert', forbidden: ['Sable', 'Chameau', 'Chaud', 'Dune', 'Sahara'] },
    { word: 'Île', forbidden: ['Mer', 'Entourée', 'Terre', 'Océan', 'Naufragé'] },
    { word: 'Volcan', forbidden: ['Lave', 'Éruption', 'Cratère', 'Fumée', 'Magma'] },
    { word: 'Cascade', forbidden: ['Eau', 'Chute', 'Rivière', 'Tomber', 'Rocher'] },
    { word: 'Grotte', forbidden: ['Caverne', 'Roche', 'Chauve-souris', 'Sombre', 'Spéléologue'] },
    { word: 'Lac', forbidden: ['Eau', 'Pêche', 'Barque', 'Étendue', 'Cygne'] },
    { word: 'Rivière', forbidden: ['Eau', 'Pont', 'Courant', 'Fleuve', 'Pêcher'] },
    { word: 'Océan', forbidden: ['Mer', 'Atlantique', 'Vagues', 'Bateau', 'Bleu'] },
    { word: 'Prairie', forbidden: ['Herbe', 'Vache', 'Champ', 'Verte', 'Fleurs'] },
    { word: 'Jungle', forbidden: ['Liane', 'Tarzan', 'Tropicale', 'Singe', 'Végétation'] },
    { word: 'Glacier', forbidden: ['Banquise', 'Montagne', 'Fondre', 'Neige', 'Froid'] },
    { word: 'Phare', forbidden: ['Lumière', 'Mer', 'Bateau', 'Tour', 'Côte'] },
    { word: 'Château', forbidden: ['Roi', 'Princesse', 'Remparts', 'Moyen Âge', 'Fort'] },
    { word: 'Pont', forbidden: ['Rivière', 'Traverser', 'Route', 'Arche', 'Passer'] },
    { word: 'Tour Eiffel', forbidden: ['Paris', 'Fer', 'France', 'Monument', 'Haute'] },
    { word: 'Cathédrale', forbidden: ['Église', 'Cloche', 'Gothique', 'Messe', 'Vitrail'] },
    { word: 'Musée', forbidden: ['Tableau', 'Exposition', 'Visite', 'Art', 'Louvre'] },
    { word: 'Bibliothèque', forbidden: ['Livres', 'Lire', 'Silence', 'Emprunter', 'Rayon'] },
    { word: 'Cinéma', forbidden: ['Film', 'Écran', 'Pop-corn', 'Salle', 'Séance'] },
    { word: 'Théâtre', forbidden: ['Scène', 'Pièce', 'Acteur', 'Rideau', 'Spectacle'] },
    { word: 'Stade', forbidden: ['Match', 'Supporters', 'Terrain', 'Gradins', 'Foot'] },
    { word: 'Aéroport', forbidden: ['Avion', 'Valise', 'Décoller', 'Vol', 'Terminal'] },
    { word: 'Gare', forbidden: ['Train', 'Quai', 'Billet', 'Voie', 'SNCF'] },
    { word: 'Hôpital', forbidden: ['Malade', 'Médecin', 'Urgences', 'Infirmier', 'Soigner'] },
    { word: 'École', forbidden: ['Élève', 'Maître', 'Classe', 'Cartable', 'Récré'] },
    { word: 'Supermarché', forbidden: ['Courses', 'Caddie', 'Caisse', 'Rayon', 'Acheter'] },
    { word: 'Boulangerie', forbidden: ['Pain', 'Baguette', 'Croissant', 'Four', 'Farine'] },
    { word: 'Pharmacie', forbidden: ['Médicament', 'Croix verte', 'Ordonnance', 'Pilule', 'Soigner'] },
    { word: 'Restaurant', forbidden: ['Manger', 'Serveur', 'Menu', 'Table', 'Réserver'] },
    { word: 'Hôtel', forbidden: ['Chambre', 'Réception', 'Nuit', 'Étoiles', 'Dormir'] },
    { word: 'Camping', forbidden: ['Tente', 'Caravane', 'Nature', 'Dormir', 'Sac'] },
    { word: 'Ferme', forbidden: ['Animaux', 'Paysan', 'Tracteur', 'Campagne', 'Foin'] },
    { word: 'Zoo', forbidden: ['Animaux', 'Cage', 'Lion', 'Visite', 'Singe'] },
    { word: 'Cirque', forbidden: ['Clown', 'Chapiteau', 'Trapèze', 'Dompteur', 'Piste'] },
    { word: 'Parc d’attractions', forbidden: ['Manège', 'Montagnes russes', 'Disney', 'Frissons', 'Enfants'] },
    { word: 'Chat', forbidden: ['Miaou', 'Félin', 'Souris', 'Ronronner', 'Moustaches'] },
    { word: 'Chien', forbidden: ['Aboyer', 'Os', 'Laisse', 'Toutou', 'Niche'] },
    { word: 'Lion', forbidden: ['Roi', 'Crinière', 'Savane', 'Rugir', 'Félin'] },
    { word: 'Éléphant', forbidden: ['Trompe', 'Gris', 'Défenses', 'Gros', 'Afrique'] },
    { word: 'Girafe', forbidden: ['Cou', 'Long', 'Tâches', 'Haute', 'Savane'] },
    { word: 'Singe', forbidden: ['Banane', 'Primate', 'Zoo', 'Grimper', 'Gorille'] },
    { word: 'Pingouin', forbidden: ['Banquise', 'Noir', 'Blanc', 'Glace', 'Manchot'] },
    { word: 'Dauphin', forbidden: ['Mer', 'Sauter', 'Intelligent', 'Flipper', 'Nager'] },
    { word: 'Requin', forbidden: ['Squale', 'Mer', 'Aileron', 'Jaws', 'Poisson'] },
    { word: 'Baleine', forbidden: ['Géante', 'Mer', 'Jonas', 'Souffle', 'Mammifère'] },
    { word: 'Tortue', forbidden: ['Carapace', 'Lente', 'Lièvre', 'Course', 'Reptile'] },
    { word: 'Crocodile', forbidden: ['Reptile', 'Dents', 'Marais', 'Mâchoire', 'Caïman'] },
    { word: 'Serpent', forbidden: ['Venin', 'Ramper', 'Reptile', 'Mordre', 'Python'] },
    { word: 'Araignée', forbidden: ['Toile', 'Huit', 'Pattes', 'Insecte', 'Peur'] },
    { word: 'Papillon', forbidden: ['Chenille', 'Ailes', 'Voler', 'Fleur', 'Insecte'] },
    { word: 'Abeille', forbidden: ['Miel', 'Piqûre', 'Ruche', 'Fleur', 'Butiner'] },
    { word: 'Fourmi', forbidden: ['Insecte', 'Colonie', 'Petite', 'Travail', 'Cigale'] },
    { word: 'Escargot', forbidden: ['Coquille', 'Jardin', 'Bave', 'Bourgogne', 'Limace'] },
    { word: 'Grenouille', forbidden: ['Coasser', 'Mare', 'Vert', 'Sauter', 'Crapaud'] },
    { word: 'Hibou', forbidden: ['Nuit', 'Oiseau', 'Chouette', 'Plumes', 'Ululer'] },
    { word: 'Aigle', forbidden: ['Rapace', 'Oiseau', 'Voler', 'Serres', 'Royal'] },
    { word: 'Perroquet', forbidden: ['Répéter', 'Parler', 'Plumes', 'Oiseau', 'Pirate'] },
    { word: 'Cheval', forbidden: ['Galop', 'Selle', 'Équitation', 'Poney', 'Écurie'] },
    { word: 'Vache', forbidden: ['Lait', 'Meugler', 'Pré', 'Taureau', 'Tachetée'] },
    { word: 'Cochon', forbidden: ['Rose', 'Porc', 'Boue', 'Grogner', 'Ferme'] },
    { word: 'Mouton', forbidden: ['Laine', 'Bêler', 'Brebis', 'Troupeau', 'Agneau'] },
    { word: 'Poule', forbidden: ['Œuf', 'Coq', 'Pondre', 'Poussin', 'Basse-cour'] },
    { word: 'Lapin', forbidden: ['Carotte', 'Oreilles', 'Terrier', 'Pâques', 'Sauter'] },
    { word: 'Souris', forbidden: ['Chat', 'Fromage', 'Rongeur', 'Queue', 'Ordinateur'] },
    { word: 'Renard', forbidden: ['Rusé', 'Poulailler', 'Roux', 'Fable', 'Corbeau'] },
    { word: 'Loup', forbidden: ['Hurler', 'Meute', 'Lune', 'Petit Chaperon rouge', 'Garou'] },
    { word: 'Ours', forbidden: ['Hiberner', 'Miel', 'Brun', 'Grizzly', 'Peluche'] },
    { word: 'Kangourou', forbidden: ['Australie', 'Poche', 'Bondir', 'Marsupial', 'Boxeur'] },
    { word: 'Panda', forbidden: ['Bambou', 'Chine', 'Noir', 'Blanc', 'Ours'] },
    { word: 'Hérisson', forbidden: ['Piquants', 'Boule', 'Épines', 'Sonic', 'Jardin'] },
    { word: 'Écureuil', forbidden: ['Noisette', 'Arbre', 'Queue', 'Roux', 'Grimper'] },
    { word: 'Coccinelle', forbidden: ['Rouge', 'Points', 'Noirs', 'Bête à bon Dieu', 'Insecte'] },
    { word: 'Méduse', forbidden: ['Piquer', 'Mer', 'Transparente', 'Tentacules', 'Plage'] },
    { word: 'Poulpe', forbidden: ['Tentacules', 'Huit', 'Encre', 'Mer', 'Pieuvre'] },
    { word: 'Pizza', forbidden: ['Italie', 'Fromage', 'Tomate', 'Four', 'Margherita'] },
    { word: 'Hamburger', forbidden: ['Steak', 'Pain', 'Fast-food', 'Frites', 'McDonald’s'] },
    { word: 'Frites', forbidden: ['Pommes de terre', 'Ketchup', 'Huile', 'Belges', 'Cornet'] },
    { word: 'Croissant', forbidden: ['Beurre', 'Petit-déjeuner', 'Boulangerie', 'Viennoiserie', 'Lune'] },
    { word: 'Baguette', forbidden: ['Pain', 'Française', 'Boulanger', 'Croûte', 'Béret'] },
    { word: 'Fromage', forbidden: ['Camembert', 'Lait', 'Vache', 'Odeur', 'Plateau'] },
    { word: 'Chocolat', forbidden: ['Cacao', 'Tablette', 'Noir', 'Sucré', 'Praline'] },
    { word: 'Crêpe', forbidden: ['Chandeleur', 'Pâte', 'Poêle', 'Nutella', 'Sauter'] },
    { word: 'Glace', forbidden: ['Cornet', 'Vanille', 'Été', 'Boule', 'Froid'] },
    { word: 'Gâteau', forbidden: ['Four', 'Anniversaire', 'Pâtisserie', 'Bougies', 'Dessert'] },
    { word: 'Pomme', forbidden: ['Fruit', 'Rouge', 'Arbre', 'Tarte', 'Newton'] },
    { word: 'Banane', forbidden: ['Jaune', 'Peau', 'Singe', 'Fruit', 'Éplucher'] },
    { word: 'Fraise', forbidden: ['Rouge', 'Fruit', 'Tarte', 'Dessert', 'Gariguette'] },
    { word: 'Citron', forbidden: ['Jaune', 'Acide', 'Presser', 'Agrume', 'Limonade'] },
    { word: 'Tomate', forbidden: ['Rouge', 'Salade', 'Ketchup', 'Sauce', 'Légume'] },
    { word: 'Carotte', forbidden: ['Orange', 'Lapin', 'Légume', 'Râpée', 'Vue'] },
    { word: 'Spaghetti', forbidden: ['Pâtes', 'Italie', 'Bolognaise', 'Fourchette', 'Sauce'] },
    { word: 'Sushi', forbidden: ['Japon', 'Poisson', 'Riz', 'Cru', 'Baguettes'] },
    { word: 'Raclette', forbidden: ['Fromage', 'Fondre', 'Pommes de terre', 'Charcuterie', 'Appareil'] },
    { word: 'Fondue', forbidden: ['Fromage', 'Savoyarde', 'Pain', 'Caquelon', 'Fourchette'] },
    { word: 'Omelette', forbidden: ['Œufs', 'Poêle', 'Battre', 'Jambon', 'Petit-déjeuner'] },
    { word: 'Sandwich', forbidden: ['Pain', 'Jambon', 'Garnir', 'Pique-nique', 'Midi'] },
    { word: 'Soupe', forbidden: ['Bouillon', 'Chaude', 'Cuillère', 'Légumes', 'Potage'] },
    { word: 'Salade', forbidden: ['Verte', 'Laitue', 'Vinaigrette', 'Légumes', 'Tomate'] },
    { word: 'Miel', forbidden: ['Abeille', 'Ruche', 'Sucré', 'Doré', 'Pot'] },
    { word: 'Confiture', forbidden: ['Tartine', 'Fruits', 'Pot', 'Sucre', 'Maman'] },
    { word: 'Café', forbidden: ['Capsule', 'Expresso', 'Réveil', 'Tasse', 'Noir'] },
    { word: 'Thé', forbidden: ['Infusion', 'Anglais', 'Tasse', 'Sachet', 'Chaud'] },
    { word: 'Jus d’orange', forbidden: ['Pressé', 'Petit-déjeuner', 'Fruit', 'Vitamine', 'Verre'] },
    { word: 'Pop-corn', forbidden: ['Maïs', 'Cinéma', 'Éclater', 'Sucré', 'Salé'] },
    { word: 'Bonbon', forbidden: ['Sucre', 'Haribo', 'Enfant', 'Sucette', 'Dents'] },
    { word: 'Chewing-gum', forbidden: ['Mâcher', 'Menthe', 'Bulle', 'Coller', 'Haleine'] },
    { word: 'Barbe à papa', forbidden: ['Fête foraine', 'Rose', 'Sucre', 'Nuage', 'Foire'] },
    { word: 'Macaron', forbidden: ['Ladurée', 'Pâtisserie', 'Coloré', 'Amande', 'Ganache'] },
    { word: 'Éclair', forbidden: ['Chocolat', 'Pâtisserie', 'Crème', 'Orage', 'Foudre'] },
    { word: 'Yaourt', forbidden: ['Lait', 'Pot', 'Nature', 'Fruits', 'Dessert'] },
    { word: 'Cacahuète', forbidden: ['Apéro', 'Arachide', 'Beurre', 'Allergie', 'Coque'] },
    { word: 'Pompier', forbidden: ['Feu', 'Camion', 'Casque', 'Sirène', 'Éteindre'] },
    { word: 'Médecin', forbidden: ['Docteur', 'Malade', 'Cabinet', 'Soigner', 'Blouse'] },
    { word: 'Pilote', forbidden: ['Avion', 'Voler', 'Cockpit', 'Course', 'Commandant'] },
    { word: 'Boulanger', forbidden: ['Pain', 'Four', 'Farine', 'Pétrir', 'Baguette'] },
    { word: 'Policier', forbidden: ['Uniforme', 'Arrêter', 'Voleur', 'Commissariat', 'Gendarme'] },
    { word: 'Facteur', forbidden: ['Lettre', 'Courrier', 'Timbre', 'Boîte', 'La Poste'] },
    { word: 'Astronaute', forbidden: ['Espace', 'Fusée', 'Lune', 'Combinaison', 'NASA'] },
    { word: 'Dentiste', forbidden: ['Molaire', 'Carie', 'Fauteuil', 'Roulette', 'Bouche'] },
    { word: 'Coiffeur', forbidden: ['Cheveux', 'Ciseaux', 'Coupe', 'Salon', 'Brushing'] },
    { word: 'Plombier', forbidden: ['Tuyau', 'Fuite', 'Robinet', 'Eau', 'Réparer'] },
    { word: 'Professeur', forbidden: ['École', 'Élève', 'Cours', 'Tableau', 'Enseigner'] },
    { word: 'Agriculteur', forbidden: ['Champs', 'Tracteur', 'Ferme', 'Récolte', 'Blé'] },
    { word: 'Magicien', forbidden: ['Tour', 'Baguette', 'Lapin', 'Chapeau', 'Illusion'] },
    { word: 'Clown', forbidden: ['Nez rouge', 'Cirque', 'Rire', 'Maquillage', 'Perruque'] },
    { word: 'Détective', forbidden: ['Enquête', 'Indice', 'Loupe', 'Sherlock', 'Mystère'] },
    { word: 'Pirate', forbidden: ['Bateau', 'Trésor', 'Perroquet', 'Crochet', 'Cache-œil'] },
    { word: 'Chevalier', forbidden: ['Armure', 'Épée', 'Tournoi', 'Dragon', 'Moyen Âge'] },
    { word: 'Sorcière', forbidden: ['Balai', 'Chaudron', 'Chapeau', 'Potion', 'Verrue'] },
    { word: 'Cuisinier', forbidden: ['Fourneaux', 'Chef', 'Toque', 'Restaurant', 'Recette'] },
    { word: 'Photographe', forbidden: ['Appareil', 'Objectif', 'Image', 'Flash', 'Cliché'] },
    { word: 'Avocat', forbidden: ['Procès', 'Tribunal', 'Défendre', 'Robe', 'Juge'] },
    { word: 'Mécanicien', forbidden: ['Voiture', 'Garage', 'Moteur', 'Réparer', 'Huile'] },
    { word: 'Vétérinaire', forbidden: ['Animaux', 'Chien', 'Soigner', 'Chat', 'Cabinet'] },
    { word: 'Football', forbidden: ['Ballon', 'But', 'Match', 'Coupe du monde', 'Penalty'] },
    { word: 'Tennis', forbidden: ['Raquette', 'Balle', 'Filet', 'Court', 'Roland-Garros'] },
    { word: 'Basket', forbidden: ['Panier', 'Ballon', 'NBA', 'Dribbler', 'Dunk'] },
    { word: 'Rugby', forbidden: ['Ballon ovale', 'Essai', 'Mêlée', 'Plaquage', 'Ovale'] },
    { word: 'Natation', forbidden: ['Nager', 'Bassin', 'Brasse', 'Crawl', 'Piscine'] },
    { word: 'Ski', forbidden: ['Neige', 'Piste', 'Montagne', 'Bâtons', 'Station'] },
    { word: 'Golf', forbidden: ['Trou', 'Club', 'Balle', 'Green', 'Tiger Woods'] },
    { word: 'Boxe', forbidden: ['Gants', 'Ring', 'Poing', 'K.O.', 'Coup'] },
    { word: 'Judo', forbidden: ['Kimono', 'Ceinture', 'Tatami', 'Japon', 'Projection'] },
    { word: 'Escrime', forbidden: ['Épée', 'Fleuret', 'Masque', 'Duel', 'Touché'] },
    { word: 'Marathon', forbidden: ['Courir', '42 kilomètres', 'Course', 'Athlète', 'Dossard'] },
    { word: 'Surf', forbidden: ['Vague', 'Planche', 'Océan', 'Californie', 'Glisser'] },
    { word: 'Plongée', forbidden: ['Bouteille', 'Eau', 'Palmes', 'Masque', 'Poissons'] },
    { word: 'Équitation', forbidden: ['Cheval', 'Selle', 'Galop', 'Cavalier', 'Poney'] },
    { word: 'Pétanque', forbidden: ['Boules', 'Cochonnet', 'Pastis', 'Sud', 'Lancer'] },
    { word: 'Ping-pong', forbidden: ['Table', 'Raquette', 'Balle', 'Filet', 'Chine'] },
    { word: 'Volley', forbidden: ['Filet', 'Ballon', 'Plage', 'Smash', 'Service'] },
    { word: 'Badminton', forbidden: ['Volant', 'Raquette', 'Filet', 'Plume', 'Smash'] },
    { word: 'Noël', forbidden: ['Réveillon', 'Cadeaux', 'Sapin', 'Décembre', 'Rennes'] },
    { word: 'Anniversaire', forbidden: ['Gâteau', 'Bougies', 'Cadeau', 'Âge', 'Fête'] },
    { word: 'Mariage', forbidden: ['Mariée', 'Alliance', 'Robe', 'Marié', 'Église'] },
    { word: 'Halloween', forbidden: ['Citrouille', 'Bonbons', 'Déguisement', 'Monstres', 'Octobre'] },
    { word: 'Carnaval', forbidden: ['Déguisement', 'Masque', 'Défilé', 'Venise', 'Rio'] },
    { word: 'Pâques', forbidden: ['Œufs', 'Chocolat', 'Cloches', 'Lapin', 'Chasse'] },
    { word: 'Nouvel An', forbidden: ['Minuit', 'Champagne', 'Décembre', 'Résolutions', 'Réveillon'] },
    { word: 'Feu d’artifice', forbidden: ['Ciel', 'Explosion', '14 juillet', 'Couleurs', 'Pétard'] },
    { word: 'Cadeau', forbidden: ['Offrir', 'Paquet', 'Noël', 'Surprise', 'Emballage'] },
    { word: 'Sapin', forbidden: ['Noël', 'Boules', 'Guirlande', 'Décorer', 'Épines'] },
    { word: 'Père Noël', forbidden: ['Rouge', 'Barbe', 'Hotte', 'Traîneau', 'Cheminée'] },
    { word: 'Fête de la musique', forbidden: ['Juin', 'Concert', 'Rue', 'Instruments', 'Gratuit'] },
    { word: 'Galette des rois', forbidden: ['Fève', 'Couronne', 'Frangipane', 'Janvier', 'Épiphanie'] },
    { word: 'Titanic', forbidden: ['Bateau', 'Iceberg', 'Rose', 'Jack', 'Coulé'] },
    { word: 'Shrek', forbidden: ['Ogre', 'Vert', 'Âne', 'Fiona', 'Marais'] },
    { word: 'Harry Potter', forbidden: ['Sorcier', 'Poudlard', 'Baguette', 'Cicatrice', 'Lunettes'] },
    { word: 'Star Wars', forbidden: ['Jedi', 'Sabre laser', 'Dark Vador', 'Espace', 'Force'] },
    { word: 'Le Roi Lion', forbidden: ['Simba', 'Savane', 'Hakuna Matata', 'Mufasa', 'Disney'] },
    { word: 'La Reine des neiges', forbidden: ['Elsa', 'Libérée', 'Olaf', 'Glace', 'Disney'] },
    { word: 'Toy Story', forbidden: ['Woody', 'Buzz', 'Jouets', 'Pixar', 'Andy'] },
    { word: 'Batman', forbidden: ['Chauve-souris', 'Gotham', 'Joker', 'Cape', 'Super-héros'] },
    { word: 'Spider-Man', forbidden: ['Araignée', 'Toile', 'Marvel', 'Peter Parker', 'Super-héros'] },
    { word: 'Astérix', forbidden: ['Gaulois', 'Obélix', 'Potion', 'Romains', 'Village'] },
    { word: 'Pinocchio', forbidden: ['Nez', 'Mensonge', 'Bois', 'Gepetto', 'Marionnette'] },
    { word: 'Cendrillon', forbidden: ['Pantoufle', 'Minuit', 'Princesse', 'Citrouille', 'Bal'] },
    { word: 'Blanche-Neige', forbidden: ['Nains', 'Pomme', 'Sorcière', 'Miroir', 'Princesse'] },
    { word: 'Peter Pan', forbidden: ['Never Land', 'Clochette', 'Crochet', 'Voler', 'Enfant'] },
    { word: 'Aladdin', forbidden: ['Génie', 'Lampe', 'Tapis volant', 'Jasmine', 'Disney'] },
    { word: 'Mario', forbidden: ['Nintendo', 'Moustache', 'Luigi', 'Champignon', 'Plombier'] },
    { word: 'Pikachu', forbidden: ['Pokémon', 'Jaune', 'Électrique', 'Sacha', 'Poké Ball'] },
    { word: 'Dracula', forbidden: ['Vampire', 'Sang', 'Cape', 'Transylvanie', 'Crocs'] },
    { word: 'Parapluie', forbidden: ['Imperméable', 'Mouillé', 'Ouvrir', 'Abri', 'Averse'] },
    { word: 'Lunettes', forbidden: ['Voir', 'Verres', 'Vue', 'Nez', 'Soleil'] },
    { word: 'Montre', forbidden: ['Heure', 'Poignet', 'Bracelet', 'Aiguilles', 'Temps'] },
    { word: 'Valise', forbidden: ['Voyage', 'Bagage', 'Roulettes', 'Partir', 'Vacances'] },
    { word: 'Brosse à dents', forbidden: ['Rincer', 'Laver', 'Bouche', 'Matin', 'Poils'] },
    { word: 'Savon', forbidden: ['Mousse', 'Laver', 'Mains', 'Bain', 'Propre'] },
    { word: 'Miroir', forbidden: ['Reflet', 'Glace', 'Se regarder', 'Salle de bain', 'Image'] },
    { word: 'Bougie', forbidden: ['Cire', 'Flamme', 'Mèche', 'Allumer', 'Gâteau'] },
    { word: 'Réveil', forbidden: ['Matin', 'Sonner', 'Dormir', 'Heure', 'Lever'] },
    { word: 'Télécommande', forbidden: ['Écran', 'Boutons', 'Zapper', 'Piles', 'Canapé'] },
    { word: 'Aspirateur', forbidden: ['Poussière', 'Ménage', 'Nettoyer', 'Sol', 'Bruit'] },
    { word: 'Frigo', forbidden: ['Froid', 'Nourriture', 'Cuisine', 'Aimant', 'Congélateur'] },
    { word: 'Micro-ondes', forbidden: ['Chauffer', 'Plat', 'Minutes', 'Réchauffer', 'Cuisine'] },
    { word: 'Grille-pain', forbidden: ['Tartine', 'Beurre', 'Toaster', 'Petit-déjeuner', 'Tranche'] },
    { word: 'Fourchette', forbidden: ['Manger', 'Couteau', 'Dents', 'Table', 'Piquer'] },
    { word: 'Casserole', forbidden: ['Cuisine', 'Cuire', 'Poignée', 'Eau', 'Bouillir'] },
    { word: 'Balai', forbidden: ['Sorcière', 'Ménage', 'Poussière', 'Nettoyer', 'Manche'] },
    { word: 'Marteau', forbidden: ['Clou', 'Frapper', 'Outil', 'Bricolage', 'Planter'] },
    { word: 'Échelle', forbidden: ['Monter', 'Barreaux', 'Grimper', 'Pompier', 'Escalader'] },
    { word: 'Ciseaux', forbidden: ['Couper', 'Papier', 'Lames', 'Découper', 'Coiffeur'] },
    { word: 'Gomme', forbidden: ['Effacer', 'Crayon', 'Cahier', 'Erreur', 'Papier'] },
    { word: 'Cartable', forbidden: ['École', 'Dos', 'Livres', 'Élève', 'Trousse'] },
    { word: 'Guitare', forbidden: ['Cordes', 'Gratter', 'Musique', 'Rock', 'Manche'] },
    { word: 'Piano', forbidden: ['Touches', 'Blanches', 'Noires', 'Clavier', 'Pianiste'] },
    { word: 'Violon', forbidden: ['Archet', 'Cordes', 'Orchestre', 'Instrument', 'Menuhin'] },
    { word: 'Ballon', forbidden: ['Gonfler', 'Air', 'Hélium', 'Rond', 'Éclater'] },
    { word: 'Cerf-volant', forbidden: ['Vent', 'Ficelle', 'Ciel', 'Voler', 'Plage'] },
    { word: 'Toboggan', forbidden: ['Glisser', 'Parc', 'Enfant', 'Descendre', 'Piscine'] },
    { word: 'Trampoline', forbidden: ['Sauter', 'Rebondir', 'Jardin', 'Saut', 'Élastique'] },
    { word: 'Vélo', forbidden: ['Pédaler', 'Roues', 'Guidon', 'Selle', 'Casque'] },
    { word: 'Hélicoptère', forbidden: ['Rotor', 'Voler', 'Pales', 'Atterrir', 'Pilote'] },
    { word: 'Fusée', forbidden: ['Espace', 'Décoller', 'Lune', 'Astronaute', 'Lancement'] },
    { word: 'Sous-marin', forbidden: ['Mer', 'Plonger', 'Périscope', 'Torpille', 'Profondeur'] },
    { word: 'Tracteur', forbidden: ['Champ', 'Ferme', 'Agriculteur', 'Roues', 'Labourer'] },
    { word: 'Arc-en-ciel', forbidden: ['Couleurs', 'Pluie', 'Sept', 'Prisme', 'Soleil'] },
    { word: 'Orage', forbidden: ['Éclair', 'Tonnerre', 'Foudre', 'Pluie', 'Ciel'] },
    { word: 'Neige', forbidden: ['Flocon', 'Blanche', 'Hiver', 'Froid', 'Bonhomme'] },
    { word: 'Brouillard', forbidden: ['Brume', 'Visibilité', 'Épais', 'Voir', 'Nuage'] },
    { word: 'Lune', forbidden: ['Nuit', 'Étoiles', 'Pleine', 'Satellite', 'Croissant'] },
    { word: 'Tornade', forbidden: ['Vent', 'Tourbillon', 'Dégâts', 'Américaine', 'Cyclone'] },
    { word: 'Nuage', forbidden: ['Ciel', 'Blanc', 'Pluie', 'Gris', 'Coton'] },
    { word: 'Bonhomme de neige', forbidden: ['Carotte', 'Hiver', 'Boule', 'Écharpe', 'Olaf'] },
    { word: 'Sablier', forbidden: ['Temps', 'Grains', 'Heure', 'Minutes', 'Verre'] },
    { word: 'Boussole', forbidden: ['Nord', 'Aiguille', 'Direction', 'Orienter', 'Aimant'] },
    { word: 'Jumelles', forbidden: ['Voir', 'Loin', 'Observer', 'Lentilles', 'Oiseaux'] },
    { word: 'Cravate', forbidden: ['Cou', 'Nœud', 'Costume', 'Chemise', 'Bureau'] },
    { word: 'Chaussette', forbidden: ['Pied', 'Paire', 'Trou', 'Laine', 'Orteils'] },
    { word: 'Écharpe', forbidden: ['Cou', 'Hiver', 'Froid', 'Laine', 'Enrouler'] },
    { word: 'Bonnet', forbidden: ['Tête', 'Hiver', 'Laine', 'Froid', 'Pompon'] },
  ],
  spicy: [
    { word: 'Apéro', forbidden: ['Verre', 'Chips', 'Amis', 'Boire', 'Cacahuètes'] },
    { word: 'Bière', forbidden: ['Houblon', 'Pression', 'Mousse', 'Bar', 'Blonde'] },
    { word: 'Vin', forbidden: ['Raisin', 'Rouge', 'Bouteille', 'Cave', 'Bordeaux'] },
    { word: 'Champagne', forbidden: ['Bulles', 'Bouchon', 'Fête', 'Flûte', 'Reims'] },
    { word: 'Cocktail', forbidden: ['Mélange', 'Shaker', 'Paille', 'Alcool', 'Barman'] },
    { word: 'Mojito', forbidden: ['Menthe', 'Rhum', 'Citron vert', 'Cuba', 'Glaçons'] },
    { word: 'Tequila', forbidden: ['Mexique', 'Sel', 'Citron', 'Shot', 'Cul sec'] },
    { word: 'Vodka', forbidden: ['Russie', 'Alcool', 'Fort', 'Glace', 'Shot'] },
    { word: 'Whisky', forbidden: ['Écosse', 'Alcool', 'Glaçons', 'Fût', 'Ambré'] },
    { word: 'Pastis', forbidden: ['Anis', 'Marseille', 'Eau', 'Jaune', 'Apéritif'] },
    { word: 'Shot', forbidden: ['Petit verre', 'Cul sec', 'Alcool', 'Tequila', 'Avaler'] },
    { word: 'Gueule de bois', forbidden: ['Lendemain', 'Mal de tête', 'Alcool', 'Soirée', 'Aspirine'] },
    { word: 'Sangria', forbidden: ['Espagne', 'Vin', 'Fruits', 'Pichet', 'Été'] },
    { word: 'Rhum', forbidden: ['Antilles', 'Pirate', 'Canne', 'Arrangé', 'Punch'] },
    { word: 'Bar', forbidden: ['Comptoir', 'Serveur', 'Tabouret', 'Boire', 'Verre'] },
    { word: 'Boîte de nuit', forbidden: ['Danser', 'DJ', 'Videur', 'Discothèque', 'Musique'] },
    { word: 'Videur', forbidden: ['Entrée', 'Porte', 'Boîte de nuit', 'Costaud', 'Refuser'] },
    { word: 'Piste de danse', forbidden: ['Bouger', 'Boîte', 'Musique', 'Se déhancher', 'DJ'] },
    { word: 'DJ', forbidden: ['Platines', 'Mixer', 'Musique', 'Casque', 'Soirée'] },
    { word: 'Karaoké', forbidden: ['Chanter', 'Micro', 'Paroles', 'Écran', 'Faux'] },
    { word: 'Soirée étudiante', forbidden: ['Fac', 'Bière', 'Appart', 'Alcool', 'Jeunes'] },
    { word: 'Afterwork', forbidden: ['Bureau', 'Collègues', 'Verre', 'Soir', 'Travail'] },
    { word: 'Barbecue', forbidden: ['Grillades', 'Saucisses', 'Braises', 'Jardin', 'Merguez'] },
    { word: 'Beer-pong', forbidden: ['Gobelets', 'Table', 'Balle', 'Bière', 'Jeu à boire'] },
    { word: 'Cul sec', forbidden: ['Boire', 'Verre', 'Vite', 'Shot', 'Avaler'] },
    { word: 'Lendemain de fête', forbidden: ['Réveil', 'Migraine', 'Dormir', 'Soirée', 'Fatigue'] },
    { word: 'Pyjama party', forbidden: ['Dormir', 'Copines', 'Soirée', 'Oreillers', 'Film'] },
    { word: 'Dernier métro', forbidden: ['Rater', 'Nuit', 'Paris', 'Rentrer', 'Transports'] },
    { word: 'Taxi', forbidden: ['Voiture', 'Chauffeur', 'Course', 'Jaune', 'Prix'] },
    { word: 'Drague', forbidden: ['Séduire', 'Charmer', 'Bar', 'Plan', 'Phrase'] },
    { word: 'Rencard', forbidden: ['Rendez-vous', 'Dîner', 'Amoureux', 'Premier', 'Resto'] },
    { word: 'Premier baiser', forbidden: ['Bouche', 'Lèvres', 'Embrasser', 'Amoureux', 'Langue'] },
    { word: 'Râteau', forbidden: ['Refus', 'Drague', 'Rejeter', 'Jardin', 'Poser'] },
    { word: 'Tinder', forbidden: ['Swiper', 'Match', 'Appli', 'Rencontre', 'Profil'] },
    { word: 'Ghosting', forbidden: ['Disparaître', 'Message', 'Silence', 'Répondre', 'Fantôme'] },
    { word: 'Crush', forbidden: ['Amoureux', 'Béguin', 'Secret', 'Aimer', 'Plaire'] },
    { word: 'Coup de foudre', forbidden: ['Amour', 'Regard', 'Instant', 'Papillons', 'Tomber'] },
    { word: 'Saint-Valentin', forbidden: ['Février', 'Amoureux', 'Roses', 'Cœur', 'Couple'] },
    { word: 'Bouquet de roses', forbidden: ['Fleurs', 'Offrir', 'Amoureux', 'Rouge', 'Épines'] },
    { word: 'Dîner aux chandelles', forbidden: ['Romantique', 'Bougies', 'Amoureux', 'Table', 'Resto'] },
    { word: 'Slow', forbidden: ['Danser', 'Lent', 'Collés', 'Bal', 'Couple'] },
    { word: 'Flirt', forbidden: ['Séduire', 'Œillade', 'Drague', 'Sourire', 'Charme'] },
    { word: 'Jalousie', forbidden: ['Envie', 'Ex', 'Couple', 'Possessif', 'Vert'] },
    { word: 'Ex', forbidden: ['Ancien', 'Rupture', 'Passé', 'Quitté', 'Couple'] },
    { word: 'Célibataire', forbidden: ['Seul', 'Couple', 'Libre', 'Single', 'Mariage'] },
    { word: 'Couple', forbidden: ['Deux', 'Amoureux', 'Ensemble', 'Mari', 'Relation'] },
    { word: 'Demande en mariage', forbidden: ['Genou', 'Bague', 'Oui', 'Fiancée', 'Surprise'] },
    { word: 'Lune de miel', forbidden: ['Voyage', 'Jeunes mariés', 'Mariage', 'Romantique', 'Après'] },
    { word: 'Divorce', forbidden: ['Mariage', 'Séparation', 'Avocat', 'Juge', 'Fin'] },
    { word: 'Belle-mère', forbidden: ['Mari', 'Famille', 'Maman', 'Épouse', 'Dimanche'] },
    { word: 'Cocu', forbidden: ['Tromper', 'Cornes', 'Infidélité', 'Conjoint', 'Maîtresse'] },
    { word: 'Rupture', forbidden: ['Quitter', 'Couple', 'Larmes', 'Fin', 'Séparation'] },
    { word: 'Pot de glace', forbidden: ['Chagrin', 'Rupture', 'Canapé', 'Cuillère', 'Larmes'] },
    { word: 'Mensonge', forbidden: ['Vérité', 'Faux', 'Mentir', 'Pinocchio', 'Cacher'] },
    { word: 'Colocation', forbidden: ['Appartement', 'Partager', 'Loyer', 'Charges', 'Cuisine'] },
    { word: 'Voisin', forbidden: ['Bruit', 'Palier', 'Appartement', 'Immeuble', 'Sonnette'] },
    { word: 'Festival', forbidden: ['Concert', 'Musique', 'Tente', 'Scène', 'Été'] },
    { word: 'Bracelet de festival', forbidden: ['Poignet', 'Entrée', 'Plastique', 'Pass', 'Accès'] },
    { word: 'Gobelet', forbidden: ['Verre', 'Plastique', 'Consigne', 'Boire', 'Festival'] },
    { word: 'Mosh pit', forbidden: ['Pogo', 'Bousculade', 'Concert', 'Foule', 'Rock'] },
    { word: 'Tatouage', forbidden: ['Encre', 'Peau', 'Aiguille', 'Dessin', 'Studio'] },
    { word: 'Piercing', forbidden: ['Percer', 'Nez', 'Oreille', 'Anneau', 'Bijou'] },
    { word: 'Selfie', forbidden: ['Photo', 'Téléphone', 'Bras', 'Autoportrait', 'Smartphone'] },
    { word: 'Spring break', forbidden: ['Vacances', 'Étudiants', 'Américains', 'Plage', 'Fête'] },
    { word: 'Croisière', forbidden: ['Bateau', 'Mer', 'Paquebot', 'Cabine', 'Escale'] },
    { word: 'Coup de soleil', forbidden: ['Rouge', 'Peau', 'Plage', 'Crème', 'Brûler'] },
    { word: 'Bronzage', forbidden: ['Soleil', 'Peau', 'Hâle', 'Plage', 'Été'] },
    { word: 'Maillot de bain', forbidden: ['Piscine', 'Plage', 'Nager', 'Bikini', 'Short'] },
    { word: 'Crème solaire', forbidden: ['Indice', 'Soleil', 'Protection', 'Peau', 'Plage'] },
    { word: 'Transat', forbidden: ['Plage', 'Bronzer', 'Pliant', 'Détente', 'Soleil'] },
    { word: 'Auberge de jeunesse', forbidden: ['Dortoir', 'Voyage', 'Sac à dos', 'Pas cher', 'Lits superposés'] },
    { word: 'Interrail', forbidden: ['Train', 'Europe', 'Voyage', 'Pass', 'Jeunes'] },
    { word: 'Road trip', forbidden: ['Voiture', 'Route', 'Voyage', 'Amis', 'Playlist'] },
    { word: 'Bivouac', forbidden: ['Tente', 'Nature', 'Dormir', 'Randonnée', 'Feu'] },
    { word: 'Airbnb', forbidden: ['Location', 'Appartement', 'Hôte', 'Vacances', 'Réserver'] },
    { word: 'Ibiza', forbidden: ['Île', 'Fête', 'Espagne', 'Boîte', 'Électro'] },
    { word: 'Lapsus', forbidden: ['Erreur', 'Parler', 'Mot', 'Gaffe', 'Freud'] },
    { word: 'Fou rire', forbidden: ['Rigoler', 'Pleurer', 'Inarrêtable', 'Hilarant', 'Mort'] },
    { word: 'Rougir', forbidden: ['Joues', 'Gêne', 'Rouge', 'Honte', 'Timide'] },
    { word: 'Honte', forbidden: ['Gêne', 'Rougir', 'Embarrassant', 'Se cacher', 'Humiliation'] },
    { word: 'Braguette ouverte', forbidden: ['Pantalon', 'Zip', 'Oubli', 'Gêne', 'Fermeture'] },
    { word: 'Pantalon déchiré', forbidden: ['Fesses', 'Couture', 'Gêne', 'Craquer', 'Accroc'] },
    { word: 'Pet', forbidden: ['Bruit', 'Gaz', 'Odeur', 'Fesses', 'Ventre'] },
    { word: 'Rot', forbidden: ['Bruit', 'Bouche', 'Gaz', 'Bébé', 'Bière'] },
    { word: 'Hoquet', forbidden: ['Bruit', 'Boire', 'Eau', 'Peur', 'Spasme'] },
    { word: 'Gaffe', forbidden: ['Erreur', 'Maladresse', 'Bourde', 'Dire', 'Gêne'] },
    { word: 'Mytho', forbidden: ['Mentir', 'Histoires', 'Inventer', 'Faux', 'Vérité'] },
    { word: 'Message à la mauvaise personne', forbidden: ['Envoyer', 'Erreur', 'Téléphone', 'Gêne', 'Destinataire'] },
    { word: 'Vomi', forbidden: ['Dégueuler', 'Malade', 'Alcool', 'Estomac', 'Beurk'] },
    { word: 'Trou noir', forbidden: ['Mémoire', 'Soirée', 'Oublier', 'Alcool', 'Rien'] },
    { word: 'Sosie', forbidden: ['Ressembler', 'Même', 'Visage', 'Copie', 'Jumeau'] },
    { word: 'Instagram', forbidden: ['Photos', 'Story', 'Like', 'Réseau', 'Filtre'] },
    { word: 'TikTok', forbidden: ['Vidéos', 'Danse', 'Courtes', 'Chinois', 'Scroller'] },
    { word: 'Snapchat', forbidden: ['Fantôme', 'Message', 'Éphémère', 'Photo', 'Flamme'] },
    { word: 'WhatsApp', forbidden: ['Message', 'Groupe', 'Vert', 'Appli', 'Vocal'] },
    { word: 'Influenceur', forbidden: ['Réseaux', 'Followers', 'Pub', 'Instagram', 'Sponsoring'] },
    { word: 'Story', forbidden: ['Instagram', '24 heures', 'Photo', 'Publier', 'Vue'] },
    { word: 'Like', forbidden: ['Cœur', 'Pouce', 'Aimer', 'Réseau', 'Photo'] },
    { word: 'Abonnés', forbidden: ['Followers', 'Suivre', 'Réseau', 'Compte', 'Chaîne'] },
    { word: 'Hashtag', forbidden: ['Dièse', 'Réseau', 'Tweet', 'Mot-clé', 'Tendance'] },
    { word: 'Groupe WhatsApp', forbidden: ['Message', 'Amis', 'Discussion', 'Notifications', 'Famille'] },
    { word: 'Capture d’écran', forbidden: ['Photo', 'Téléphone', 'Preuve', 'Boutons', 'Image'] },
    { word: 'Mode avion', forbidden: ['Téléphone', 'Réseau', 'Couper', 'Vol', 'Silence'] },
    { word: 'Vu', forbidden: ['Message', 'Lu', 'Répondre', 'Double', 'Bleu'] },
    { word: 'Bumble', forbidden: ['Rencontre', 'Femmes', 'Jaune', 'Appli', 'Match'] },
    { word: 'Netflix', forbidden: ['Série', 'Streaming', 'Film', 'Abonnement', 'Canapé'] },
    { word: 'Série télé', forbidden: ['Épisode', 'Saison', 'Binge', 'Regarder', 'Netflix'] },
    { word: 'Uber', forbidden: ['Chauffeur', 'Voiture', 'Appli', 'Course', 'VTC'] },
    { word: 'Livraison', forbidden: ['Commande', 'Coursier', 'Colis', 'Porte', 'Sonner'] },
    { word: 'Dimanche soir', forbidden: ['Lundi', 'Blues', 'Week-end', 'Travail', 'Triste'] },
    { word: 'Lundi matin', forbidden: ['Réveil', 'Travail', 'Café', 'Week-end', 'Bureau'] },
    { word: 'Open space', forbidden: ['Bureau', 'Collègues', 'Bruit', 'Travail', 'Entreprise'] },
    { word: 'Patron', forbidden: ['Chef', 'Boss', 'Travail', 'Entreprise', 'Employé'] },
    { word: 'Réunion', forbidden: ['Bureau', 'Visio', 'Ordre du jour', 'Collègues', 'Ennuyeuse'] },
    { word: 'Collègue', forbidden: ['Bureau', 'Travail', 'Café', 'Équipe', 'Entreprise'] },
    { word: 'Salaire', forbidden: ['Argent', 'Fiche de paie', 'Mois', 'Travail', 'Virement'] },
    { word: 'Découvert', forbidden: ['Banque', 'Compte', 'Argent', 'Négatif', 'Fin du mois'] },
    { word: 'Loyer', forbidden: ['Appartement', 'Propriétaire', 'Mois', 'Payer', 'Location'] },
    { word: 'Grasse matinée', forbidden: ['Dormir', 'Lit', 'Week-end', 'Tard', 'Réveil'] },
    { word: 'Sieste', forbidden: ['Dormir', 'Après-midi', 'Canapé', 'Repos', 'Courte'] },
    { word: 'Insomnie', forbidden: ['Dormir', 'Nuit', 'Sommeil', 'Moutons', 'Éveillé'] },
    { word: 'Ronfler', forbidden: ['Bruit', 'Dormir', 'Nuit', 'Nez', 'Lit'] },
    { word: 'Cauchemar', forbidden: ['Rêve', 'Nuit', 'Peur', 'Dormir', 'Mauvais'] },
    { word: 'Procrastination', forbidden: ['Remettre', 'Demain', 'Travail', 'Plus tard', 'Paresse'] },
    { word: 'Embouteillage', forbidden: ['Voiture', 'Bouchon', 'Route', 'Bloqué', 'Klaxon'] },
    { word: 'Amende', forbidden: ['Police', 'Contravention', 'Radar', 'Payer', 'Stationnement'] },
    { word: 'Permis de conduire', forbidden: ['Voiture', 'Examen', 'Code', 'Moniteur', 'Auto-école'] },
    { word: 'Ascenseur', forbidden: ['Étage', 'Bouton', 'Monter', 'Cabine', 'Immeuble'] },
    { word: 'Escape game', forbidden: ['Énigmes', 'Enfermés', 'Équipe', 'Salle', 'Indices'] },
    { word: 'Jeu de société', forbidden: ['Plateau', 'Dés', 'Pions', 'Famille', 'Cartes'] },
    { word: 'Poker', forbidden: ['Cartes', 'Mise', 'Jetons', 'Bluff', 'Casino'] },
    { word: 'Casino', forbidden: ['Jeu', 'Roulette', 'Argent', 'Las Vegas', 'Jetons'] },
    { word: 'Bowling', forbidden: ['Quilles', 'Boule', 'Piste', 'Strike', 'Chaussures'] },
    { word: 'Laser game', forbidden: ['Tirer', 'Équipe', 'Gilet', 'Pistolet', 'Faisceau'] },
    { word: 'Paintball', forbidden: ['Billes', 'Peinture', 'Équipe', 'Masque', 'Tirer'] },
    { word: 'Montagnes russes', forbidden: ['Frissons', 'Manège', 'Vitesse', 'Parc', 'Rail'] },
    { word: 'Saut à l’élastique', forbidden: ['Vide', 'Pont', 'Corde', 'Plonger', 'Adrénaline'] },
    { word: 'Parachute', forbidden: ['Ciel', 'Sauter', 'Avion', 'Voile', 'Atterrir'] },
    { word: 'Flashmob', forbidden: ['Danse', 'Foule', 'Surprise', 'Public', 'Rue'] },
    { word: 'Chanson', forbidden: ['Refrain', 'Paroles', 'Chanter', 'Radio', 'Musique'] },
    { word: 'Playlist', forbidden: ['Musique', 'Chansons', 'Spotify', 'Écouter', 'Morceaux'] },
    { word: 'Casque audio', forbidden: ['Oreilles', 'Musique', 'Écouter', 'Bluetooth', 'Son'] },
    { word: 'Guitare électrique', forbidden: ['Rock', 'Ampli', 'Solo', 'Cordes', 'Concert'] },
    { word: 'Rockstar', forbidden: ['Concert', 'Guitare', 'Groupe', 'Célèbre', 'Scène'] },
    { word: 'Paparazzi', forbidden: ['Photos', 'Star', 'Célébrité', 'Scoop', 'Appareil'] },
    { word: 'Tapis rouge', forbidden: ['Cannes', 'Célébrités', 'Cinéma', 'Montée', 'Marches'] },
    { word: 'Oscars', forbidden: ['Statuette', 'Cinéma', 'Récompense', 'Hollywood', 'Acteur'] },
    { word: 'Télé-réalité', forbidden: ['Émission', 'Candidats', 'Caméras', 'Villa', 'Clash'] },
    { word: 'Loft', forbidden: ['Appartement', 'Industriel', 'Grand', 'Atelier', 'Plafond'] },
    { word: 'Perruque', forbidden: ['Cheveux', 'Faux', 'Déguisement', 'Tête', 'Coiffure'] },
    { word: 'Déguisement', forbidden: ['Costume', 'Soirée', 'Halloween', 'Carnaval', 'Mascarade'] },
    { word: 'Talons hauts', forbidden: ['Chaussures', 'Femme', 'Escarpins', 'Grandes', 'Pieds'] },
    { word: 'Parfum', forbidden: ['Odeur', 'Flacon', 'Senteur', 'Eau de toilette', 'Vaporiser'] },
    { word: 'Rouge à lèvres', forbidden: ['Maquillage', 'Bouche', 'Carmin', 'Embrasser', 'Tube'] },
    { word: 'Épilation', forbidden: ['Poils', 'Cire', 'Douleur', 'Peau', 'Rasoir'] },
    { word: 'Gel douche', forbidden: ['Savon', 'Mousse', 'Laver', 'Bain', 'Flacon'] },
    { word: 'Peignoir', forbidden: ['Bain', 'Douche', 'Éponge', 'Sortir', 'Serviette'] },
    { word: 'Karma', forbidden: ['Destin', 'Bien', 'Mal', 'Bouddhisme', 'Retour'] },
    { word: 'Horoscope', forbidden: ['Signe', 'Étoiles', 'Astrologie', 'Verseau', 'Prédire'] },
    { word: 'Yoga', forbidden: ['Posture', 'Tapis', 'Zen', 'Respirer', 'Méditation'] },
    { word: 'Salle de sport', forbidden: ['Muscles', 'Fonte', 'Abonnement', 'Haltères', 'Entraîner'] },
    { word: 'Régime', forbidden: ['Maigrir', 'Kilos', 'Manger', 'Poids', 'Calories'] },
    { word: 'Balance', forbidden: ['Poids', 'Kilos', 'Peser', 'Salle de bain', 'Régime'] },
  ],
  hot: [
    { word: 'Lingerie', forbidden: ['Dentelle', 'Sous-vêtements', 'Sexy', 'Soutien-gorge', 'Femme'] },
    { word: 'Soutien-gorge', forbidden: ['Poitrine', 'Bonnet', 'Lingerie', 'Agrafe', 'Seins'] },
    { word: 'Porte-jarretelles', forbidden: ['Bas', 'Lingerie', 'Cuisses', 'Sexy', 'Attache'] },
    { word: 'Bas résille', forbidden: ['Jambes', 'Filet', 'Sexy', 'Collants', 'Noirs'] },
    { word: 'Corset', forbidden: ['Taille', 'Lacets', 'Serrer', 'Lingerie', 'Baleines'] },
    { word: 'Nuisette', forbidden: ['Nuit', 'Soie', 'Lingerie', 'Dormir', 'Courte'] },
    { word: 'Tanga', forbidden: ['Culotte', 'Fesses', 'Petit', 'Ficelle', 'Lingerie'] },
    { word: 'Caleçon', forbidden: ['Boxer', 'Homme', 'Sous-vêtement', 'Slip', 'Pantalon'] },
    { word: 'Dentelle', forbidden: ['Tissu', 'Lingerie', 'Fine', 'Brodée', 'Mariée'] },
    { word: 'Satin', forbidden: ['Draps', 'Soie', 'Lisse', 'Tissu', 'Brillant'] },
    { word: 'Latex', forbidden: ['Combinaison', 'Gants', 'Brillant', 'Moulant', 'Caoutchouc'] },
    { word: 'Cuir', forbidden: ['Veste', 'Moto', 'Peau', 'Noir', 'Ceinture'] },
    { word: 'Menottes', forbidden: ['Poignets', 'Policier', 'Attacher', 'Fer', 'Clé'] },
    { word: 'Bandeau', forbidden: ['Yeux', 'Cacher', 'Noir', 'Aveugle', 'Obscurité'] },
    { word: 'Plumeau', forbidden: ['Poussière', 'Duvet', 'Chatouiller', 'Ménage', 'Caresser'] },
    { word: 'Foulard en soie', forbidden: ['Cou', 'Doux', 'Attacher', 'Tissu', 'Écharpe'] },
    { word: 'Masque de nuit', forbidden: ['Dormir', 'Yeux', 'Lumière', 'Sommeil', 'Cacher'] },
    { word: 'Huile de massage', forbidden: ['Peau', 'Masseuse', 'Dos', 'Parfumée', 'Glisser'] },
    { word: 'Massage', forbidden: ['Dos', 'Mains', 'Détente', 'Huile', 'Masseur'] },
    { word: 'Masseuse', forbidden: ['Dos', 'Mains', 'Huile', 'Détente', 'Spa'] },
    { word: 'Spa', forbidden: ['Détente', 'Massage', 'Sauna', 'Peignoir', 'Bien-être'] },
    { word: 'Sauna', forbidden: ['Chaleur', 'Vapeur', 'Bois', 'Transpirer', 'Finlande'] },
    { word: 'Hammam', forbidden: ['Vapeur', 'Chaud', 'Turc', 'Spa', 'Transpirer'] },
    { word: 'Jacuzzi', forbidden: ['Bulles', 'Eau chaude', 'Bain', 'Détente', 'Remous'] },
    { word: 'Bain moussant', forbidden: ['Baignoire', 'Savon', 'Eau', 'Détente', 'Bulles'] },
    { word: 'Douche à deux', forbidden: ['Eau', 'Savon', 'Couple', 'Salle de bain', 'Mouillé'] },
    { word: 'Pétales de roses', forbidden: ['Lit', 'Romantique', 'Fleurs', 'Rouge', 'Chambre'] },
    { word: 'Draps de soie', forbidden: ['Lit', 'Glisser', 'Lisse', 'Satin', 'Nuit'] },
    { word: 'Sous la couette', forbidden: ['Lit', 'Chaud', 'Se cacher', 'Draps', 'Nuit'] },
    { word: 'Lit double', forbidden: ['Deux', 'Matelas', 'Chambre', 'Grand', 'Dormir'] },
    { word: 'Petit-déjeuner au lit', forbidden: ['Plateau', 'Matin', 'Croissants', 'Café', 'Apporter'] },
    { word: 'Chambre d’hôtel', forbidden: ['Nuit', 'Clé', 'Lit', 'Réception', 'Réserver'] },
    { word: 'Ne pas déranger', forbidden: ['Pancarte', 'Porte', 'Hôtel', 'Poignée', 'Chambre'] },
    { word: 'Suite nuptiale', forbidden: ['Mariage', 'Hôtel', 'Luxe', 'Jeunes mariés', 'Chambre'] },
    { word: 'Love hotel', forbidden: ['Japon', 'Chambre', 'Heures', 'Couples', 'Discret'] },
    { word: 'Nuit de noces', forbidden: ['Mariage', 'Mariés', 'Premier soir', 'Lit', 'Après'] },
    { word: 'Strip-tease', forbidden: ['Déshabiller', 'Danse', 'Vêtements', 'Barre', 'Enlever'] },
    { word: 'Pole dance', forbidden: ['Barre', 'Danse', 'Acrobatie', 'Tourner', 'Club'] },
    { word: 'Lap dance', forbidden: ['Danse', 'Genoux', 'Club', 'Privée', 'Show'] },
    { word: 'Danse du ventre', forbidden: ['Orientale', 'Hanches', 'Bassin', 'Voile', 'Se déhancher'] },
    { word: 'Cabaret', forbidden: ['Spectacle', 'Plumes', 'Paillettes', 'Scène', 'Danseuses'] },
    { word: 'Burlesque', forbidden: ['Cabaret', 'Spectacle', 'Plumes', 'Pin-up', 'Humour'] },
    { word: 'Pin-up', forbidden: ['Années 50', 'Affiche', 'Rétro', 'Pose', 'Magazine'] },
    { word: 'Moulin Rouge', forbidden: ['Paris', 'Cabaret', 'Danseuses', 'Montmartre', 'French cancan'] },
    { word: 'Cinquante Nuances de Grey', forbidden: ['Film', 'Livre', 'Milliardaire', 'Chambre rouge', 'Cravate'] },
    { word: 'Kamasutra', forbidden: ['Positions', 'Inde', 'Livre', 'Couple', 'Acrobatique'] },
    { word: 'Sex-shop', forbidden: ['Boutique', 'Adultes', 'Jouets', 'Vitrine', 'Rideau'] },
    { word: 'Jeu de rôle', forbidden: ['Scénario', 'Personnage', 'Incarner', 'Couple', 'Costume'] },
    { word: 'Infirmière sexy', forbidden: ['Blouse', 'Costume', 'Déguisement', 'Hôpital', 'Seringue'] },
    { word: 'Soubrette', forbidden: ['Tablier', 'Femme de chambre', 'Costume', 'Dentelle', 'Plumeau'] },
    { word: 'Femme de chambre', forbidden: ['Hôtel', 'Ménage', 'Tablier', 'Soubrette', 'Draps'] },
    { word: 'Policier sexy', forbidden: ['Costume', 'Menottes', 'Uniforme', 'Déguisement', 'Matraque'] },
    { word: 'Tenue d’Adam', forbidden: ['Dévêtu', 'Sans vêtements', 'Homme', 'Naturel', 'Ève'] },
    { word: 'Torse nu', forbidden: ['Muscles', 'T-shirt', 'Homme', 'Abdos', 'Chemise'] },
    { word: 'Abdos', forbidden: ['Ventre', 'Muscles', 'Tablette', 'Sport', 'Chocolat'] },
    { word: 'Pectoraux', forbidden: ['Muscles', 'Torse', 'Sport', 'Fonte', 'Homme'] },
    { word: 'Décolleté', forbidden: ['Poitrine', 'Robe', 'Plongeant', 'Seins', 'Haut'] },
    { word: 'Nuque', forbidden: ['Cou', 'Cheveux', 'Embrasser', 'Dos', 'Tête'] },
    { word: 'Baiser dans le cou', forbidden: ['Embrasser', 'Frissons', 'Lèvres', 'Nuque', 'Peau'] },
    { word: 'Suçon', forbidden: ['Cou', 'Marque', 'Lèvres', 'Rouge', 'Écharpe'] },
    { word: 'Baiser langoureux', forbidden: ['Langue', 'Bouche', 'Long', 'Roulage de pelle', 'Passionné'] },
    { word: 'Roulage de pelle', forbidden: ['Langue', 'Embrasser', 'Bouche', 'Baiser', 'Longtemps'] },
    { word: 'Caresse', forbidden: ['Main', 'Doux', 'Peau', 'Toucher', 'Effleurer'] },
    { word: 'Frisson', forbidden: ['Peau', 'Poils', 'Froid', 'Plaisir', 'Dos'] },
    { word: 'Soupir', forbidden: ['Souffle', 'Bouche', 'Lâcher', 'Fatigue', 'Soulagement'] },
    { word: 'Chuchoter à l’oreille', forbidden: ['Murmurer', 'Secret', 'Bas', 'Souffle', 'Dire'] },
    { word: 'Regard langoureux', forbidden: ['Yeux', 'Séduction', 'Intense', 'Fixer', 'Charme'] },
    { word: 'Clin d’œil', forbidden: ['Cligner', 'Fermer', 'Complice', 'Séduire', 'Paupière'] },
    { word: 'Sourire en coin', forbidden: ['Malicieux', 'Lèvres', 'Séducteur', 'Sournois', 'Bouche'] },
    { word: 'Phrase d’accroche', forbidden: ['Drague', 'Premier', 'Dire', 'Séduire', 'Bar'] },
    { word: 'Séducteur', forbidden: ['Charmeur', 'Homme', 'Femmes', 'Drague', 'Don Juan'] },
    { word: 'Femme fatale', forbidden: ['Dangereuse', 'Séduisante', 'Film noir', 'Mystérieuse', 'Charme'] },
    { word: 'Chaud lapin', forbidden: ['Coureur', 'Jupons', 'Séducteur', 'Conquêtes', 'Homme'] },
    { word: 'Dom Juan', forbidden: ['Séducteur', 'Femmes', 'Théâtre', 'Molière', 'Conquêtes'] },
    { word: 'Vamp', forbidden: ['Séductrice', 'Rouge à lèvres', 'Dangereuse', 'Fatale', 'Femme'] },
    { word: 'Bombe', forbidden: ['Explosion', 'Canon', 'Sexy', 'Magnifique', 'Femme'] },
    { word: 'Beau gosse', forbidden: ['Mec', 'Séduisant', 'Canon', 'Charmant', 'Joli'] },
    { word: 'Sexy', forbidden: ['Séduisant', 'Attirant', 'Tenue', 'Charme', 'Bombe'] },
    { word: 'Torride', forbidden: ['Chaud', 'Brûlant', 'Passion', 'Intense', 'Été'] },
    { word: 'Sensuel', forbidden: ['Charnel', 'Peau', 'Caresse', 'Plaisir', 'Voluptueux'] },
    { word: 'Coquin', forbidden: ['Vilain', 'Malicieux', 'Enfant', 'Polisson', 'Pervers'] },
    { word: 'Aphrodisiaque', forbidden: ['Désir', 'Huîtres', 'Libido', 'Chocolat', 'Excitant'] },
    { word: 'Huîtres', forbidden: ['Mer', 'Citron', 'Perle', 'Noël', 'Coquillage'] },
    { word: 'Fraises au chocolat', forbidden: ['Fondue', 'Fruit', 'Saint-Valentin', 'Tremper', 'Dessert'] },
    { word: 'Chantilly', forbidden: ['Crème', 'Fouetter', 'Dessert', 'Sucre', 'Blanche'] },
    { word: 'Glaçon sur la peau', forbidden: ['Froid', 'Frisson', 'Dos', 'Fondre', 'Cube'] },
    { word: 'Libido', forbidden: ['Désir', 'Envie', 'Pulsion', 'Sexuel', 'Baisse'] },
    { word: 'Désir', forbidden: ['Envie', 'Passion', 'Vouloir', 'Attirance', 'Besoin'] },
    { word: 'Fantasme', forbidden: ['Rêve', 'Imaginer', 'Secret', 'Désir', 'Idée'] },
    { word: 'Tentation', forbidden: ['Résister', 'Succomber', 'Envie', 'Diable', 'Péché'] },
    { word: 'Péché', forbidden: ['Église', 'Mignon', 'Confession', 'Capital', 'Gourmandise'] },
    { word: 'Interdit', forbidden: ['Défendu', 'Règle', 'Panneau', 'Passer', 'Loi'] },
    { word: 'Voyeur', forbidden: ['Regarder', 'Fenêtre', 'Épier', 'Jumelles', 'Observer'] },
    { word: 'Exhibitionniste', forbidden: ['Montrer', 'Public', 'Manteau', 'Nu', 'Se dévoiler'] },
    { word: 'Bain de minuit', forbidden: ['Obscurité', 'Sans maillot', 'Mer', 'Plage', 'Baignade'] },
    { word: 'Naturisme', forbidden: ['Nu', 'Plage', 'Vêtements', 'Camping', 'Soleil'] },
    { word: 'Nudiste', forbidden: ['Peau', 'Plage', 'Sans maillot', 'Camping', 'Naturiste'] },
    { word: 'Strip poker', forbidden: ['Cartes', 'Vêtements', 'Perdre', 'Enlever', 'Jeu'] },
    { word: 'Action ou vérité', forbidden: ['Défi', 'Question', 'Choisir', 'Jeu', 'Gage'] },
    { word: 'Jeu de la bouteille', forbidden: ['Tourner', 'Cercle', 'Embrasser', 'Gage', 'Goulot'] },
    { word: 'Sept minutes au paradis', forbidden: ['Placard', 'Jeu', 'Enfermés', 'Soirée', 'Embrasser'] },
    { word: 'Gage', forbidden: ['Défi', 'Perdre', 'Action', 'Punition', 'Jeu'] },
    { word: 'Bagarre d’oreillers', forbidden: ['Lit', 'Plumes', 'Pyjama', 'Frapper', 'Coussins'] },
    { word: 'Plan d’un soir', forbidden: ['Nuit', 'Une seule', 'Rencontre', 'Bar', 'Lendemain'] },
    { word: 'Ami avec bénéfices', forbidden: ['Copain', 'Sans lendemain', 'Relation', 'Coucher', 'Sentiments'] },
    { word: 'Sexto', forbidden: ['Message', 'Téléphone', 'Coquin', 'Photo', 'Envoyer'] },
    { word: 'Nudes', forbidden: ['Photo', 'Dévoilé', 'Téléphone', 'Envoyer', 'Snap'] },
    { word: 'Amant', forbidden: ['Maîtresse', 'Tromper', 'Secret', 'Liaison', 'Mari'] },
    { word: 'Maîtresse', forbidden: ['Amant', 'Tromper', 'Secret', 'Mari', 'Liaison'] },
    { word: 'Liaison', forbidden: ['Secrète', 'Amants', 'Relation', 'Tromper', 'Cachée'] },
    { word: 'Adultère', forbidden: ['Tromper', 'Mariage', 'Infidélité', 'Amant', 'Maîtresse'] },
    { word: 'Banquette arrière', forbidden: ['Voiture', 'Siège', 'Parking', 'Derrière', 'Adolescents'] },
    { word: 'Cabine d’essayage', forbidden: ['Magasin', 'Rideau', 'Vêtements', 'Miroir', 'Tester'] },
    { word: 'Photocopieuse', forbidden: ['Bureau', 'Copier', 'Papier', 'Fesses', 'Imprimante'] },
    { word: 'Cheminée', forbidden: ['Feu', 'Bûches', 'Salon', 'Chaleur', 'Fumée'] },
    { word: 'Tapis en fourrure', forbidden: ['Peau', 'Sol', 'Chaleur', 'Animal', 'Douceur'] },
    { word: 'Coucher de soleil', forbidden: ['Romantique', 'Horizon', 'Plage', 'Orange', 'Soir'] },
    { word: 'Nuit blanche', forbidden: ['Dormir', 'Fête', 'Sans sommeil', 'Réveillé', 'Matin'] },
    { word: 'Réveil câlin', forbidden: ['Matin', 'Lit', 'Bras', 'Embrasser', 'Tendresse'] },
    { word: 'Câlin', forbidden: ['Bras', 'Serrer', 'Tendresse', 'Étreinte', 'Doudou'] },
    { word: 'Oreiller', forbidden: ['Tête', 'Dormir', 'Plumes', 'Lit', 'Taie'] },
    { word: 'Matelas', forbidden: ['Lit', 'Sommier', 'Dormir', 'Ressorts', 'Mousse'] },
    { word: 'Boxer', forbidden: ['Caleçon', 'Sous-vêtement', 'Homme', 'Chien', 'Ring'] },
    { word: 'Slip', forbidden: ['Sous-vêtement', 'Culotte', 'Calvin Klein', 'Homme', 'Kangourou'] },
    { word: 'Culotte', forbidden: ['Sous-vêtement', 'Slip', 'Dentelle', 'Femme', 'Fesses'] },
    { word: 'Boa à plumes', forbidden: ['Cabaret', 'Cou', 'Autruche', 'Déguisement', 'Rose'] },
    { word: 'Nœud papillon', forbidden: ['Cou', 'Smoking', 'Chic', 'Cravate', 'Élégant'] },
    { word: 'Smoking', forbidden: ['Noir', 'Costume', 'Soirée', 'James Bond', 'Chic'] },
    { word: 'James Bond', forbidden: ['007', 'Agent secret', 'Smoking', 'Martini', 'Espion'] },
    { word: 'Martini', forbidden: ['Olive', 'Cocktail', 'Secoué', 'Agent', 'Verre'] },
    { word: 'Chaîne à la cheville', forbidden: ['Bijou', 'Pied', 'Plage', 'Été', 'Fine'] },
    { word: 'Talons aiguilles', forbidden: ['Chaussures', 'Escarpins', 'Fins', 'Hauts', 'Pointus'] },
    { word: 'Robe fendue', forbidden: ['Jambe', 'Côté', 'Longue', 'Soirée', 'Cuisse'] },
    { word: 'Mini-jupe', forbidden: ['Courte', 'Jambes', 'Tissu', 'Ourlet', 'Années 60'] },
    { word: 'Short moulant', forbidden: ['Serré', 'Court', 'Jambes', 'Vêtement', 'Fesses'] },
    { word: 'Maillot une pièce', forbidden: ['Plage', 'Natation', 'Femme', 'Bikini', 'Piscine'] },
    { word: 'Bikini', forbidden: ['Plage', 'Deux pièces', 'Maillot', 'Haut', 'Bas'] },
    { word: 'Monokini', forbidden: ['Maillot', 'Plage', 'Haut', 'Seins nus', 'Bronzer'] },
    { word: 'Bronzer nu', forbidden: ['Soleil', 'Plage', 'Sans maillot', 'Trace', 'Peau'] },
    { word: 'Maillot de bain mouillé', forbidden: ['Eau', 'Piscine', 'Serviette', 'Transparent', 'Plage'] },
    { word: 'Concours de t-shirt mouillé', forbidden: ['Eau', 'Spring break', 'Poitrine', 'Public', 'Transparent'] },
    { word: 'Show de danseuses', forbidden: ['Scène', 'Cabaret', 'Plumes', 'Costume', 'Spectacle'] },
    { word: 'Lingerie fine', forbidden: ['Dentelle', 'Sous-vêtements', 'Chic', 'Soie', 'Sexy'] },
    { word: 'Pyjama en soie', forbidden: ['Nuit', 'Douceur', 'Chic', 'Satin', 'Dormir'] },
    { word: 'Peau douce', forbidden: ['Hydratée', 'Crème', 'Lisse', 'Caresse', 'Soyeuse'] },
    { word: 'Bougie de massage', forbidden: ['Cire', 'Huile', 'Peau', 'Parfum', 'Fondre'] },
    { word: 'Playlist sensuelle', forbidden: ['Musique', 'Ambiance', 'Slow', 'Soirée', 'Romantique'] },
    { word: 'Ambiance tamisée', forbidden: ['Lumière', 'Douce', 'Bougies', 'Intimité', 'Romantique'] },
    { word: 'Rouge passion', forbidden: ['Amour', 'Couleur', 'Rose', 'Sang', 'Fort'] },
    { word: 'Cœur qui bat', forbidden: ['Poitrine', 'Rythme', 'Émotion', 'Amoureux', 'Vite'] },
    { word: 'Joues rouges', forbidden: ['Rougir', 'Gêne', 'Timide', 'Visage', 'Chaleur'] },
    { word: 'Intimité', forbidden: ['Privé', 'Couple', 'Seuls', 'Secret', 'Discrétion'] },
    { word: 'Lune de miel torride', forbidden: ['Voyage', 'Couple', 'Hôtel', 'Mariage', 'Chaud'] },
    { word: 'Sieste coquine', forbidden: ['Après-midi', 'Lit', 'Dormir', 'Couple', 'Câlin'] },
    { word: 'Cuisine à poil', forbidden: ['Tablier', 'Nu', 'Marmite', 'Plat', 'Fourneau'] },
    { word: 'Tablier', forbidden: ['Cuisine', 'Cuisiner', 'Ventre', 'Protéger', 'Nouer'] },
    { word: 'Pompier torse nu', forbidden: ['Calendrier', 'Muscles', 'Sauveteur', 'Uniforme', 'Casque'] },
    { word: 'Calendrier sexy', forbidden: ['Mois', 'Photos', 'Pompiers', 'Mur', 'Année'] },
    { word: 'Playboy', forbidden: ['Magazine', 'Lapin', 'Poses', 'Photos', 'Couverture'] },
    { word: 'Paris la nuit', forbidden: ['Lumières', 'Seine', 'Bars', 'Tour', 'Sortir'] },
    { word: 'Premier rendez-vous', forbidden: ['Rencard', 'Stress', 'Dîner', 'Gêne', 'Rencontre'] },
    { word: 'Dernier verre', forbidden: ['Bar', 'Fermeture', 'Soir', 'Raccompagner', 'Alcool'] },
    { word: 'Café chez moi', forbidden: ['Invitation', 'Soirée', 'Appartement', 'Monter', 'Boisson'] },
    { word: 'Se faire désirer', forbidden: ['Attendre', 'Séduction', 'Languir', 'Jeu', 'Envie'] },
    { word: 'Preuve d’amour', forbidden: ['Aimer', 'Geste', 'Cadeau', 'Fidélité', 'Couple'] },
    { word: 'Passion', forbidden: ['Amour', 'Ardeur', 'Intense', 'Brûlant', 'Feu'] },
    { word: 'Gémir', forbidden: ['Bruit', 'Plaisir', 'Voix', 'Souffrir', 'Plainte'] },
    { word: 'Murs fins', forbidden: ['Voisins', 'Bruit', 'Entendre', 'Immeuble', 'Appartement'] },
    { word: 'Nuit d’ivresse', forbidden: ['Alcool', 'Soirée', 'Oublier', 'Mauvaise idée', 'Lendemain'] },
    { word: 'Mauvaise idée', forbidden: ['Regret', 'Erreur', 'Lendemain', 'Soirée', 'Fausse'] },
    { word: 'Tomber sur l’ex', forbidden: ['Ancien', 'Rue', 'Gêne', 'Hasard', 'Rencontrer'] },
  ],
}
