import type { Level } from '../engine'

/** « C'est un 10 mais… » — chacun donne la nouvelle note de la personne. */
export const tenBut: Record<Level, string[]> = {
  soft: [
    'ronfle comme un tracteur',
    'met du ketchup sur ses pâtes carbonara',
    'applaudit quand l’avion atterrit',
    'n’a jamais vu un seul Star Wars',
    'répond « ok. » avec un point à tous les messages',
    'met des chaussettes dans ses sandales',
    'parle de son ex à chaque date',
    'écoute ses vocaux en haut-parleur dans le métro',
    'déteste le fromage',
    'appelle sa mère trois fois par jour',
    'mange les céréales sans lait',
    'ne sait pas nager',
    'a peur des pigeons',
    'envoie des vocaux de cinq minutes',
    'regarde la fin des films en premier',
    'fait des jeux de mots toute la journée',
    'garde ses chaussures dans le lit',
    'trouve que l’ananas sur la pizza est la base',
    'ne rit jamais à tes blagues',
    'gagne toujours au Monopoly et le fait savoir',
    'porte des Crocs en soirée',
    'met son réveil douze fois chaque matin',
    'a 4 000 notifications non lues',
    'lit les messages sans jamais répondre',
    'mâche la bouche ouverte',
    'parle de crypto au premier rendez-vous',
    'connaît par cœur toutes les chorés TikTok',
    'claque des doigts pour appeler les serveurs',
    'laisse toujours un fond de lait dans le frigo',
    'ne ferme jamais les tiroirs',
    'chante faux sous la douche, fenêtre ouverte',
    'dit « j’arrive » en étant encore dans son lit',
    'n’éteint jamais la lumière en quittant une pièce',
    'garde tous les emballages « au cas où »',
    'regarde des vidéos sans écouteurs dans le train',
    'mange sa pizza avec un couteau et une fourchette',
    'ne sait pas faire cuire des pâtes',
    'arrive toujours dix minutes en retard, pile',
    'arrive toujours quarante minutes en avance',
    'spoile les séries sans le faire exprès',
    'dit « on se fait un truc » sans jamais proposer de date',
    'range ses livres par couleur',
    'réclame le chauffage à 25 degrés en plein mois de mai',
    'ouvre toutes les fenêtres en plein hiver',
    'dort avec la télé allumée',
    'refuse de regarder un film en VF',
    'refuse de regarder un film en VO',
    'prend trente photos de groupe avant d’être content',
    'fait quinze selfies avant d’en poster un',
    'raconte ses rêves en détail au petit-déjeuner',
    'demande des nouvelles à sa plante verte',
    'se cogne dans toutes les portes en verre',
    'fait des playlists de quatre heures pour dix minutes de trajet',
    'met de la mayonnaise sur tout',
    'met du sucre dans la salade',
    'ne mange que des plats sans sauce ni épices',
    'croque dans sa glace au lieu de la lécher',
    'rit à ses propres blagues avant la chute',
    'raconte toujours la même anecdote en soirée',
    'dit « c’était mieux avant » dès qu’on change de sujet',
    'corrige ton orthographe dans tes SMS',
    'écrit tous ses messages en majuscules',
    'répond par un pouce levé à un message de dix lignes',
    'crée un groupe WhatsApp pour absolument tout',
    'utilise l’émoji qui rit aux larmes pour une mauvaise nouvelle',
    'tape sur son clavier comme si c’était un piano',
    'laisse la vaisselle « tremper » pendant trois jours',
    'ne fait son lit que quand quelqu’un vient',
    'garde sa veste à l’intérieur, partout',
    'ne retient jamais le prénom de ses voisins',
    'raconte sa vie à des inconnus dans l’ascenseur',
    'commente le film à voix haute au cinéma',
    'fait du bruit avec son popcorn pendant les scènes tristes',
    'pleure devant les pubs de Noël',
    'hurle devant une minuscule araignée',
    'ne supporte pas qu’on touche au thermostat',
    'a une méthode infaillible pour charger le lave-vaisselle',
    'refait ton chargement de lave-vaisselle en douce',
    'range le frigo par date de péremption',
    'a une application pour chaque aspect de sa vie',
    'compte ses pas et le rappelle à chaque repas',
    'ne parle que de son prochain semi-marathon',
    'porte une banane en bandoulière, même en soirée',
    'fait du yoga dans le salon avec des chants de baleines',
    'met trois sucres dans un expresso',
    'ne boit que de l’eau tiède',
    'trempe ses croissants dans le jus d’orange',
    'mange ses pizzas avec du miel',
    'mange les kiwis avec la peau',
    'ne mange jamais de légumes',
    'ne mange que des légumes et le fait savoir',
    'devient végétarien chaque lundi et abandonne le mardi',
    'parle de son régime à chaque repas',
    'photographie chaque plat avant de manger',
    'refuse de goûter ton plat mais mange dans ton assiette',
    'pique des frites dans ton assiette sans demander',
    'dit « j’ai pas faim » puis finit ton dessert',
    'cache la dernière part de gâteau pour plus tard',
    'a toujours une excuse pour ne pas partager ses chips',
    'repart avec les sachets de sucre de tous les cafés',
    'ramène chez soi les savons de chaque hôtel',
    'vérifie quatre fois que la porte est fermée',
    'ne retrouve jamais ses clés, tous les jours',
    'cherche son téléphone alors qu’il est dans sa main',
    'cherche ses lunettes alors qu’elles sont sur sa tête',
    'rate la sortie même avec le GPS',
    'parle au GPS comme à un ennemi',
    'klaxonne dès que le feu tarde à passer au vert',
    'refuse de se garer en marche arrière',
    'dit « c’est à gauche » en pointant à droite',
    'fait la sieste partout, même en soirée',
    's’endort au cinéma à chaque film',
    'se couche à 21 h 30 même en vacances',
    'se lève à 5 h le dimanche pour faire du sport',
    'prend la douche la plus longue de l’histoire',
    'prend des douches glacées et veut te convertir',
    'se brosse les dents sous la douche',
    'laisse ses cheveux dans la bonde',
    'met du parfum en quantité industrielle',
    'refuse le déodorant « pour la planète »',
    'porte le même sweat depuis trois ans',
    'ne lave jamais son jean',
    'ne repasse jamais rien, même pour un mariage',
    'va à la boulangerie en pyjama',
    'garde ses lunettes de soleil à l’intérieur',
    'garde son bonnet au restaurant',
    'porte un short en plein hiver',
    'a toujours froid et te vole ton pull',
    'prête ses affaires et ne les rend jamais',
    'garde les Tupperware de tout le monde',
    'emprunte ton chargeur « deux minutes » pour toute la soirée',
    'a toujours 3 % de batterie',
    'n’a jamais de monnaie',
    'paie tout en pièces de un centime',
    'note chaque dépense dans un tableur, même un chewing-gum',
    'achète tout ce qui est en promo, même un tuba',
    'garde ses tickets de caisse depuis dix ans',
    'compte l’addition au centime près',
    'négocie le prix de tout, même à la boulangerie',
    'envoie des mails à 23 h pour dire que ça peut attendre demain',
    'répond « bien reçu » à un mail de félicitations',
    'dit « j’ai une réunion » pour fuir toute situation',
    'prend des notes pendant une soirée entre amis',
    'fait un PowerPoint pour choisir le restaurant',
    'termine ses SMS par « cordialement »',
    'dit « bonne continuation » à tout le monde',
    'place « du coup » toutes les trois phrases',
    'commence chaque phrase par « en fait »',
    'demande « tu vois ce que je veux dire ? » en boucle',
    'explique ses blagues après les avoir racontées',
    'vouvoie son chien',
    'dort encore avec sa peluche d’enfance',
    'joue sur son téléphone pendant les repas de famille',
    'relit les règles du jeu pendant toute la partie',
    'triche aux cartes et l’avoue en riant',
    'boude après chaque défaite à Mario Kart',
    'raconte le film de la première à la dernière minute',
    'lit à voix haute tous les panneaux en voiture',
    'répond aux questions rhétoriques',
    'met des sous-titres sur tout, même en français',
    'regarde toutes les séries en accéléré',
    'n’a jamais fini une série',
    'met en pause toutes les dix minutes pour aller aux toilettes',
    'ne regarde que des documentaires sur les requins',
    'a un avis tranché sur la bonne façon de plier un T-shirt',
    'fait sa valise cinq minutes avant le taxi',
    'emporte huit valises pour un week-end',
    'part trois mois avec un sac de dix litres et en fait un exploit',
    'photographie les couchers de soleil pendant que tu parles',
    'dit « je ne regarde jamais la télé » en citant trois séries',
    'dit « c’est un petit budget » avant de dépenser mille euros',
    'appelle tous les serveurs « chef »',
    'prend toujours « la même chose que toi » au restaurant',
    'met trois heures à choisir sur la carte',
    'écrit « mdr » sans jamais rire',
    'répond « haha » à absolument tout',
    'dort avec des chaussettes en plein été',
  ],
  spicy: [
    'est encore ami avec tous ses ex',
    'like les photos de ton ex',
    'ne paie jamais sa part au resto',
    'a un tatouage du prénom de son ex',
    'te présente comme « un pote »',
    'est toujours actif sur les applis de rencontre',
    'garde une photo de son ex en fond d’écran',
    'drague ton meilleur ami',
    'disparaît trois jours sans donner de nouvelles',
    'raconte toute votre vie à sa mère',
    'est en couple « mais c’est compliqué »',
    'ne veut jamais sortir le week-end',
    'refuse de te présenter à ses potes',
    'pleure à chaque soirée passé minuit',
    'commente les calories de ton assiette',
    'vit encore chez ses parents à 35 ans',
    'est jaloux de ton chat',
    'lit tes messages par-dessus ton épaule',
    'est sorti avec la moitié de ton groupe d’amis',
    'ne lâche jamais son téléphone pendant un date',
    'fait une scène de jalousie pour un like',
    'drague le serveur devant toi',
    'a déjà oublié ton prénom une fois',
    'poste toutes vos disputes en story',
    'parle de mariage au deuxième date',
    'refuse de dire « je t’aime » en premier, toujours',
    'ne boit que des shots de vodka-pomme',
    'fête ton anniversaire au fast-food',
    'a un « meilleur pote » qui est en fait son ex',
    'stalke les nouvelles conquêtes de son ex',
    'écrit « on se voit ce soir ? » à deux heures du matin',
    'appelle son ex dès que ça va mal',
    'répond aux stories de son ex avec un cœur',
    'garde les cadeaux de son ex dans un tiroir',
    'porte encore le sweat d’un ex',
    'compare tout à son ex',
    'numérote ses ex : « mon ex numéro 3 »',
    'tient un compteur de ses conquêtes et l’annonce',
    'drague tout le monde « juste pour rire »',
    'envoie un « ça va ? » à minuit pile',
    'te laisse en vu trois jours puis envoie un cœur',
    'répond « haha » à ton « je t’aime »',
    'like les photos de vacances de son ex à trois heures du matin',
    'disparaît puis revient comme si de rien n’était',
    'te couvre d’attentions puis disparaît sans explication',
    'dit « je ne suis pas jaloux » en lisant ton téléphone',
    'exige le code de ton téléphone',
    'veut ta position en direct, en permanence',
    'te demande de justifier chaque verre de la soirée',
    'boude pendant deux jours sans dire pourquoi',
    'répond « rien » quand tu demandes ce qui ne va pas',
    'dit « fais comme tu veux » en pensant l’inverse',
    'fait semblant de ne pas voir ton message pour te faire patienter',
    'attend toujours que tu écrives en premier',
    'évite certains quartiers « pour cause d’ex »',
    'pleure sur la chanson « de son ex »',
    'a une playlist « ex » de 400 titres',
    'écrit des textos ivre et les regrette',
    'envoie des vocaux ivre à trois heures du matin',
    'boit trop et raconte tes secrets',
    'embrasse n’importe qui après trois verres',
    'danse sur les tables en soirée',
    'part de la soirée à l’anglaise, sans prévenir',
    'rentre à 6 h et dit « j’étais chez un pote »',
    'te laisse payer les verres puis offre un shot à un inconnu',
    'commande toujours le shot le plus dégoûtant',
    's’endort dans le taxi à chaque retour de soirée',
    'se dispute avec le videur',
    'pique les verres des autres en soirée',
    'monopolise le micro au karaoké pendant une heure',
    'fait un discours ému à chaque soirée',
    'appelle tout le monde « mon frère » après deux bières',
    'propose « un dernier verre » à quatre heures du matin',
    'parle fort pour que tout le bar t’entende',
    'se trouve irrésistible après deux verres',
    'exagère à chaque fois la même histoire de soirée',
    'dit « je ne bois jamais » puis finit sur le comptoir',
    'arrive à l’apéro avec une bouteille déjà entamée',
    'ne ramène rien à l’apéro mais mange tout',
    'pose son verre de vin sur ton canapé blanc',
    'dit « je te rembourse » depuis 2021',
    'flirte avec tes collègues devant toi',
    'complimente tes amis plus que toi',
    'te compare à ses ex à voix haute',
    'parle de son ex à ta mère',
    'adore ta mère plus que toi',
    's’entend mieux avec ton père que toi',
    'recycle les cadeaux de son ex pour ton anniversaire',
    'oublie votre anniversaire de rencontre',
    'fête la Saint-Valentin avec ses potes',
    't’offre un bouquet de la station-service',
    'dit « je suis pas matérialiste » et possède quatre consoles',
    'te demande ton salaire dès le deuxième rendez-vous',
    'demande l’avis de ses parents sur chaque décision de couple',
    'dit « je suis indépendant » depuis la chambre de son enfance',
    'ramène son linge sale chez sa mère chaque week-end',
    'répète « ma mère fait mieux » à chaque repas',
    't’appelle par le prénom de son ex une fois par mois',
    'parle de trois enfants et d’un golden retriever dès le premier mois',
    'veut emménager ensemble après trois semaines',
    'te présente à toute sa famille au bout d’une semaine',
    'te met en « ma moitié » sur les réseaux dès le premier jour',
    'refuse d’officialiser votre histoire',
    'te fait passer un entretien d’embauche au premier rendez-vous',
    'dresse la liste de tes défauts dans un tableau Notion',
    'vient au rendez-vous avec un pote « au cas où »',
    'arrive aux rendez-vous avec trois heures de retard et un sourire',
    'te pose un lapin en disant « il y avait trop de monde »',
    'annule toujours à la dernière minute',
    'dit « je suis trop pris » mais poste six stories',
    'n’est jamais disponible mais toujours en ligne',
    'est « en pause » avec quelqu’un d’autre depuis un an',
    'retire son alliance en soirée',
    'a deux profils sur les applis de rencontre',
    'a une photo de profil qui date d’il y a dix ans',
    'pose avec un poisson sur toutes ses photos de profil',
    'écrit « pas de prise de tête » dans sa bio et en fait tout le temps',
    'swipe pendant que vous dînez',
    'envoie des vocaux à son ex au lieu de te répondre',
    'a enregistré le numéro de son ex sous un faux nom',
    'renomme ses ex en « Plombier » dans son répertoire',
    'regarde la story de son ex en cachette',
    'crée un faux compte pour stalker son ex',
    'a gardé le mot de passe Netflix de son ex',
    'fait semblant de ne pas connaître son ex en soirée',
    'dit que tes amis proches sont « une mauvaise influence »',
    'te demande de supprimer tes photos de vacances avec tes ex',
    'réclame un « break » après chaque dispute',
    'quitte la soirée en claquant la porte et revient dix minutes après',
    'fait la tête pendant tout le trajet en voiture',
    'fait des reproches en public avec le sourire',
    'sort une dispute de 2019 à chaque nouvelle dispute',
    's’excuse uniquement par émojis',
    'dit « désolé si tu l’as mal pris »',
    'ne dit jamais « pardon », seulement « mais »',
    'dit « c’est pas toi, c’est moi » avant même le premier baiser',
    'répète que « les relations, c’est pas son truc »',
    'a un « type » qui n’est jamais toi',
    'like les photos d’un inconnu ou d’une inconnue depuis un an',
    'prend un verre avec son ex « juste pour discuter »',
    'dîne avec son ex et dit « c’est juste un ami »',
    'raconte vos disputes à ses amis, version arrangée',
    'prend ton groupe d’amis pour un tribunal',
    'se moque de toi en public « pour rire »',
    'te corrige devant tes amis',
    'interrompt tes histoires pour les raconter mieux',
    'finit tes phrases à ta place',
    'répond à ta place quand on te pose une question',
    'choisit le restaurant et le plat que tu vas prendre',
    'demande « t’es sûr que tu vas manger ça ? »',
    'ne supporte aucun de tes amis, surtout le meilleur',
    'te ramène chez ses parents pour que sa mère te juge',
    'te teste en ne répondant pas pendant vingt-quatre heures',
    'dit « on ne se prend pas la tête » puis se prend la tête',
    'dit « t’inquiète, je gère » avant de tout oublier',
    'répond « on verra » à toutes tes propositions de week-end',
    'te présente son ex comme « quelqu’un de très important »',
    'poste des citations sur les « gens toxiques » après chaque dispute',
    'organise une soirée entre ex et t’invite « pour détendre l’ambiance »',
    'te dit « je t’aime bien » alors que tu attends autre chose',
    'te laisse faire les premiers pas depuis six mois',
    'vérifie qui like tes photos et en tient la liste',
  ],
  hot: [
    's’endort juste après les préliminaires',
    'parle de lui ou d’elle à la troisième personne au lit',
    'garde ses chaussettes pendant l’acte',
    'crie le prénom de son ex',
    'met la musique de Mario Kart pendant les câlins',
    'refuse tout bisou le matin',
    'a quarante sextoys et leur a tous donné un prénom',
    'veut toujours filmer',
    'note chaque nuit sur 20',
    'ne veut le faire que le dimanche à 15 h',
    'rit nerveusement au mauvais moment',
    'demande un avis écrit après chaque nuit',
    'embrasse avec beaucoup trop de langue',
    'a une collection de déguisements très précise',
    'ne veut jamais éteindre la lumière',
    'raconte tout à sa mère, absolument tout',
    'parle de son travail pendant les câlins',
    'mord vraiment trop fort',
    'garde son téléphone allumé « au cas où »',
    'refuse de rester dormir après',
    'dit « merci » à la fin, à chaque fois',
    'veut toujours tester une position du Kamasutra… page 147',
    'fait des bruits d’animaux',
    'n’a pas changé ses draps depuis 2019',
    'chronomètre tout',
    'planifie tout dans un agenda partagé',
    'veut absolument le faire dans la chambre d’amis de tes parents',
    'fait des commentaires sportifs en direct',
    'se lève en plein milieu pour noter une idée',
    'regarde l’heure en plein câlin',
    'demande « c’était bien ? » toutes les trois minutes',
    'fait la grimace de quelqu’un qui passe un examen',
    'garde son pyjama « pour la route »',
    'met une playlist de méditation pour l’ambiance',
    'allume trente bougies et déclenche le détecteur de fumée',
    'soupire de soulagement à la fin, un peu trop fort',
    'fait des blagues nulles au pire moment',
    'dit « bon, on y va ? » comme avant un déménagement',
    'annonce chaque étape comme un GPS',
    'demande de baisser la voix à cause des voisins, puis crie',
    'dit « pardon » à chaque mouvement',
    'se rhabille en deux secondes et demande « on mange quoi ? »',
    'ouvre le frigo directement après',
    'prend toute la place dans le lit en s’endormant en travers',
    'vole la couette toute la nuit',
    'ronfle avant même que tu aies fermé les yeux',
    'dort avec un bonnet de nuit',
    'met un masque de sommeil et des bouchons d’oreille',
    'ne supporte pas de dormir collé',
    'a toujours les pieds glacés et les pose sur toi',
    'ne prend jamais de douche avant',
    'exige une douche avant, une après, et une pendant',
    'refuse tout câlin après 22 h',
    'demande « tu as un avis sur ma technique ? »',
    'demande « tu as aimé ? » avant la fin',
    'se félicite tout seul : « là, c’était du grand art »',
    'applaudit à la fin',
    'prend un accent italien pour la romance',
    'chuchote à l’oreille avec la voix d’un documentaire animalier',
    'chuchote des recettes de cuisine à l’oreille',
    'récite les tables de multiplication pour tenir plus longtemps',
    'pense à ses impôts pour garder le contrôle',
    'met trois heures à se préparer',
    'se parfume comme pour une cérémonie',
    'porte un caleçon à motifs de dinosaures',
    'garde ses sous-vêtements « porte-bonheur » depuis dix ans',
    'enfile un pyjama polaire à tête de licorne',
    'porte un costume de super-héros et refuse de l’enlever',
    'interdit qu’on touche à sa coiffure',
    'enlève ses lentilles en plein câlin et n’y voit plus rien',
    'cherche ses lunettes à tâtons, en plein élan',
    'se cogne la tête contre le mur du lit',
    'fait tomber la lampe de chevet à chaque fois',
    'renverse la bouteille d’eau sur le lit',
    'possède un lit qui grince comme un château hanté',
    'a un matelas gonflable qui se dégonfle en cours de route',
    'insiste pour dormir sur un lit de camp',
    'a un chat qui regarde fixement',
    'a un chien qui aboie dès que ça bouge',
    'entoure le lit de peluches qui « regardent »',
    'garde un poster géant de sa star préférée au-dessus du lit',
    'laisse une chaîne d’infos allumée en fond',
    'répond à un appel de sa mère en plein milieu',
    'vérifie ses notifications entre deux moments',
    'fait une pause pour envoyer un mail pro',
    'poste une story juste après',
    'prend un selfie ensuite « pour la mémoire »',
    'dit « je t’appelle demain » et ne le fait jamais',
    'envoie un compte rendu à sa meilleure amie dans la minute',
    'tient un journal intime très détaillé',
    'commente comme un sommelier : « notes boisées, finale longue »',
    'répond « hum, intéressant » à tout',
    'répond « OK » à tout, d’une voix de robot',
    'demande « tu peux répéter ? » au pire moment',
    'dit « pas ce soir, j’ai la migraine » depuis 2020',
    'a mal au dos, à l’épaule ou au genou au mauvais moment',
    'prend la pose, puis a une crampe au mollet',
    'tousse en plein milieu',
    'éternue à chaque fois',
    'éclate de rire dès que tu enlèves ton pull',
    'donne des coups de pied dès qu’on le chatouille',
    'donne des coups de coude involontaires',
    'gigote comme un poisson sorti de l’eau',
    'reste raide comme un piquet',
    'demande « je fais quoi de mes mains ? »',
    'demande « je fais bien ? » toutes les minutes',
    'réclame un débrief de quarante-cinq minutes ensuite',
    'propose une réunion bilan le lendemain matin',
    'laisse un avis sur Internet le lendemain',
    'veut recommencer tout de suite, puis s’endort',
    'a un tableau Excel de ses envies',
    'a une liste « à faire avant 40 ans »',
    'veut tester tout ce qui se fait dans les séries',
    'veut reproduire chaque scène de film romantique, ratés compris',
    'dit des répliques de film d’amour avec le sérieux d’un acteur',
    'déclame des poèmes d’amour interminables',
    'écrit des chansons sur toi et sort la guitare au pire moment',
    'explique la philosophie du moment présent… pendant le moment',
    'raconte sa journée en détail au beau milieu',
    'demande ton avis sur la politique en plein câlin',
    'parle de football au pire moment',
    'demande « tu penses à quoi ? » toutes les dix secondes',
    'récite la liste de courses à voix haute',
    'demande « t’as pensé à acheter du pain ? » au mauvais moment',
    'parle de vos futures vacances en plein câlin',
    'se trompe de prénom puis rattrape tout avec « mon chou »',
    'n’appelle personne autrement que « mon chou »',
    'répond à une question de quiz télé en pleine action',
    'regarde un match en même temps',
    'suit le score par SMS pendant',
    'dit « attends, c’est ma série » et met en pause',
    'prétexte une urgence pour partir tôt',
    'rappelle à 23 h qu’un réveil sonne à 5 h 30',
    'fait signer une décharge avant de commencer',
    'lit le mode d’emploi à voix haute',
    'suit un tutoriel YouTube en direct',
    'demande « tu es en règle avec ton assurance ? »',
    'garde les yeux ouverts et te fixe sans cligner',
    'demande « on se dit quoi demain ? » au pire moment',
    'fait semblant de dormir pour éviter la discussion',
    'allume la lumière pour chercher son chargeur',
    'parle en dormant et dit des choses très compromettantes',
    'commente la déco de ta chambre en pleine action',
    'demande le wifi avant même de se déshabiller',
    'pose son téléphone en mode avion « pour être concentré »',
    'dit « tu n’as rien entendu » en parlant de ce bruit',
    'range tout de suite la chambre après',
    'insiste pour changer les draps à deux heures du matin',
    'garde son manteau, « il fait un peu frais »',
    'met un tablier pour l’occasion',
    'prépare un buffet pour après',
    'sort un thermomètre pour mesurer la température de la chambre',
    'fait un strip-tease sur une musique de hall de gare',
    'enlève ses vêtements dans un ordre précis et les plie',
    'dit « attends, j’ai oublié d’éteindre le four »',
    'demande si tu as pensé à fermer à clé la voiture',
    'veut dormir à l’envers, les pieds sur l’oreiller',
    'ronronne comme un chat pour faire sensuel',
    'prononce un discours de remerciement après',
    'attache ses cheveux avec ton élastique sans demander',
    'fait les gros yeux si tu touches son oreiller',
    'réclame un câlin de quinze minutes, minimum, chrono en main',
    'prend un air inspiré en regardant par la fenêtre',
  ],
}
