import type { Level } from '../engine'

/** « C'est un 10 mais… » — chacun donne la nouvelle note de la personne. */
export const tenBut: Record<Level, string[]> = {
  soft: [
    'ronfle comme un tracteur',
    'met du ketchup sur ses pâtes carbonara',
    'applaudit quand l’avion atterrit',
    'n’a jamais vu un seul Star Wars',
    'répond « ok. » avec un point à tous les messages',
    'met des chaussettes dans ses sandales',
    'parle de son ex à chaque date',
    'écoute ses vocaux en haut-parleur dans le métro',
    'déteste le fromage',
    'appelle sa mère trois fois par jour',
    'mange les céréales sans lait',
    'ne sait pas nager',
    'a peur des pigeons',
    'envoie des vocaux de cinq minutes',
    'regarde la fin des films en premier',
    'fait des jeux de mots toute la journée',
    'garde ses chaussures dans le lit',
    'trouve que l’ananas sur la pizza est la base',
    'ne rit jamais à tes blagues',
    'gagne toujours au Monopoly et le fait savoir',
    'porte des Crocs en soirée',
    'met son réveil douze fois chaque matin',
    'a 4 000 notifications non lues',
    'lit les messages sans jamais répondre',
    'mâche la bouche ouverte',
    'parle de crypto au premier rendez-vous',
    'connaît par cœur toutes les chorés TikTok',
    'claque des doigts pour appeler les serveurs',
  ],
  spicy: [
    'est encore ami avec tous ses ex',
    'like les photos de ton ex',
    'ne paie jamais sa part au resto',
    'a un tatouage du prénom de son ex',
    'te présente comme « un pote »',
    'est toujours actif sur les applis de rencontre',
    'garde une photo de son ex en fond d’écran',
    'drague ton meilleur ami',
    'disparaît trois jours sans donner de nouvelles',
    'raconte toute votre vie à sa mère',
    'est en couple « mais c’est compliqué »',
    'ne veut jamais sortir le week-end',
    'refuse de te présenter à ses potes',
    'pleure à chaque soirée passé minuit',
    'commente les calories de ton assiette',
    'vit encore chez ses parents à 35 ans',
    'est jaloux de ton chat',
    'lit tes messages par-dessus ton épaule',
    'est sorti avec la moitié de ton groupe d’amis',
    'ne lâche jamais son téléphone pendant un date',
    'fait une scène de jalousie pour un like',
    'drague le serveur devant toi',
    'a déjà oublié ton prénom une fois',
    'poste toutes vos disputes en story',
    'parle de mariage au deuxième date',
    'refuse de dire « je t’aime » en premier, toujours',
    'ne boit que des shots de vodka-pomme',
    'fête ton anniversaire au fast-food',
  ],
  hot: [
    's’endort juste après les préliminaires',
    'parle de lui ou d’elle à la troisième personne au lit',
    'garde ses chaussettes pendant l’acte',
    'crie le prénom de son ex',
    'met la musique de Mario Kart pendant les câlins',
    'refuse tout bisou le matin',
    'a quarante sextoys et leur a tous donné un prénom',
    'veut toujours filmer',
    'note chaque nuit sur 20',
    'ne veut le faire que le dimanche à 15 h',
    'rit nerveusement au mauvais moment',
    'demande un avis écrit après chaque nuit',
    'embrasse avec beaucoup trop de langue',
    'a une collection de déguisements très précise',
    'ne veut jamais éteindre la lumière',
    'raconte tout à sa mère, absolument tout',
    'parle de son travail pendant les câlins',
    'mord vraiment trop fort',
    'garde son téléphone allumé « au cas où »',
    'refuse de rester dormir après',
    'dit « merci » à la fin, à chaque fois',
    'veut toujours tester une position du Kamasutra… page 147',
    'fait des bruits d’animaux',
    'n’a pas changé ses draps depuis 2019',
    'chronomètre tout',
    'planifie tout dans un agenda partagé',
    'veut absolument le faire dans la chambre d’amis de tes parents',
    'fait des commentaires sportifs en direct',
  ],
}
