import type { Level } from '../engine'

/**
 * Action ou Vérité. Les actions impliquant quelqu'un d'autre supposent toujours
 * son accord : chacun peut refuser ou passer son tour.
 */
export const truthOrDare: { truth: Record<Level, string[]>; dare: Record<Level, string[]> } = {
  truth: {
    soft: [
      'Quelle est ta plus grosse honte au collège ?',
      'Quel est le pire cadeau que tu aies reçu ?',
      'Quelle habitude bizarre as-tu quand tu es seul ?',
      'Quel est ton plaisir coupable musical ?',
      'Quelle est la dernière chose que tu as cherchée sur Internet ?',
      'Quel mensonge as-tu raconté à tes parents et qu’ils croient encore ?',
      'Qui ici te fait le plus rire ?',
      'Quel métier voulais-tu faire enfant ?',
      'Quel est ton pire souvenir de vacances ?',
      'Quelle appli utilises-tu le plus, et combien de temps par jour ?',
      'Quel film t’a fait pleurer le plus ?',
      'Si tu pouvais échanger ta vie avec quelqu’un ici, ce serait qui ?',
      'Quelle est ta peur la plus irrationnelle ?',
      'Quel est le surnom le plus gênant qu’on t’ait donné ?',
      'Quel est le dernier mensonge que tu as dit ?',
      'Qu’est-ce que tu ne supportes pas chez les autres ?',
      'Quel est ton talent caché ?',
      'Quelle célébrité aimerais-tu rencontrer, et pourquoi ?',
      'Quelle est la chose la plus stupide que tu aies faite pour un pari ?',
      'As-tu fait semblant de rire à une blague ce soir ?',
    ],
    spicy: [
      'Qui était ton premier bisou, et comment c’était ?',
      'As-tu déjà eu un crush sur quelqu’un ici ?',
      'Quel est ton pire date ?',
      'Si tu devais recontacter un ex ce soir, lequel ?',
      'Quel est le message le plus gênant de ton téléphone ?',
      'Qui ici serait ton plan de secours pour le mariage ?',
      'As-tu déjà menti pour écourter un date ?',
      'Quelle est la pire chose que tu aies faite après quelques verres ?',
      'As-tu déjà été jaloux d’un ou une amie ici ?',
      'Combien de temps a duré ta relation la plus courte ?',
      'Qui ici embrasserais-tu si tu y étais obligé ?',
      'As-tu stalké un ex dans les dernières 24 h ?',
      'Quelle est ta technique de drague ?',
      'As-tu déjà été ghosté ? Raconte.',
      'Quel est le pire défaut de ton ex ?',
      'Avec qui ici partirais-tu en vacances en amoureux ?',
      'Quel secret n’as-tu jamais confié à ton ou ta meilleure amie ?',
      'Quelle note sur 10 te donnes-tu au premier date ?',
      'As-tu déjà craqué pour quelqu’un de déjà pris ?',
      'Quel est le message que tu regrettes le plus d’avoir envoyé ?',
    ],
    hot: [
      'Quel est ton plus grand fantasme ?',
      'Quel est l’endroit le plus fou où tu as fait l’amour ?',
      'As-tu déjà simulé ?',
      'Quelle est ta position préférée ?',
      'Qui ici trouves-tu le plus attirant ?',
      'As-tu déjà envoyé une photo coquine ? Le regrettes-tu ?',
      'Combien de partenaires as-tu eus ?',
      'Quel est ton meilleur souvenir au lit ?',
      'Et ton pire ?',
      'As-tu déjà eu un plan à trois, ou en as-tu envie ?',
      'Quelle partie du corps te fait craquer en premier ?',
      'As-tu un sextoy ? Lequel ?',
      'As-tu déjà couché le premier soir ?',
      'As-tu déjà été surpris en plein acte ?',
      'Quel est ton fantasme le plus inavouable ?',
      'Avec qui ici passerais-tu une nuit, juste une ?',
      'Quelle est la chose la plus coquine que tu aies faite en public ?',
      'Préfères-tu dominer ou être dominé ?',
      'Quel est le rêve érotique dont tu te souviens le mieux ?',
      'Qu’est-ce que tu n’as jamais osé demander au lit ?',
    ],
  },
  dare: {
    soft: [
      'Imite quelqu’un de la pièce jusqu’à ce qu’on devine qui c’est.',
      'Parle avec un accent pendant les trois prochains tours.',
      'Fais ta meilleure danse pendant 30 secondes.',
      'Chante le refrain de la dernière chanson que tu as écoutée.',
      'Laisse le groupe écrire ta prochaine story.',
      'Fais 15 squats en racontant ta journée.',
      'Raconte une blague. Si personne ne rit, recommence.',
      'Fais une déclaration d’amour dramatique à un objet de la pièce.',
      'Montre la dernière photo de ta galerie.',
      'Mime un film jusqu’à ce que quelqu’un trouve.',
      'Parle uniquement en chantant jusqu’à ton prochain tour.',
      'Fais un compliment sincère à chaque personne présente.',
      'Fais le cri de ton animal préféré.',
      'Garde une grimace pendant une minute.',
      'Appelle un ami et chante-lui joyeux anniversaire.',
      'Commente ta propre vie comme un match de foot pendant 30 secondes.',
      'Fais un défilé de mannequin d’un bout à l’autre de la pièce.',
      'Laisse quelqu’un te coiffer comme il veut.',
      'Écris un poème de quatre vers sur la personne à ta gauche.',
      'Échange un vêtement avec la personne à ta droite jusqu’au prochain tour.',
    ],
    spicy: [
      'Lis à voix haute ton dernier message envoyé.',
      'Laisse la personne à ta gauche envoyer un emoji à un contact de son choix.',
      'Fais ta meilleure technique de drague à quelqu’un ici.',
      'Montre ton historique de recherche des dernières 24 h.',
      'Envoie « tu me manques » à la troisième conversation de ta messagerie.',
      'Fais un slow de 30 secondes avec la personne de ton choix.',
      'Raconte ton pire date en le mimant.',
      'Fais un bisou sur la joue de la personne de ton choix.',
      'Laisse le groupe regarder tes dernières recherches Instagram.',
      'Imite ton ex pendant 30 secondes.',
      'Dis à quelqu’un ici ce que tu as pensé la première fois que tu l’as vu.',
      'Danse de façon sexy pendant 20 secondes.',
      'Masse les épaules de la personne à ta droite pendant une minute.',
      'Laisse quelqu’un poster une story depuis ton téléphone.',
      'Fais une déclaration à la personne en face de toi, un genou à terre.',
      'Montre ta dernière conversation avec ta mère.',
      'Échange ton haut avec quelqu’un jusqu’à la fin de la partie.',
      'Fais un câlin de 10 secondes à la personne de ton choix.',
      'Lis avec conviction une bio d’appli de rencontre choisie par le groupe.',
      'Choisis quelqu’un : il te pose une question, tu dois répondre honnêtement.',
    ],
    hot: [
      'Embrasse la personne de ton choix, si elle est d’accord, là où elle le veut.',
      'Retire un vêtement, en musique.',
      'Murmure quelque chose de coquin à l’oreille de la personne à ta gauche.',
      'Masse le cou de la personne de ton choix pendant une minute, si elle accepte.',
      'Mime ta position préférée, habillé.',
      'Laisse quelqu’un t’écrire un mot sur le bras au feutre.',
      'Fais une danse lascive de 20 secondes pour la personne de ton choix, si elle accepte.',
      'Décris ton fantasme à la personne en face de toi.',
      'Retire un vêtement de ton choix jusqu’à la fin de la partie.',
      'Fais un suçon à la personne de ton choix, si elle est d’accord.',
      'Embrasse le cou de quelqu’un ici, avec son accord.',
      'Mange un fruit de la façon la plus sensuelle possible.',
      'Fais un baiser de cinéma de 10 secondes à la personne de ton choix, si elle accepte.',
      'Les yeux bandés, devine qui te prend la main.',
      'Fais ton meilleur gémissement.',
      'Assieds-toi sur les genoux de quelqu’un jusqu’à ton prochain tour, s’il ou elle accepte.',
      'Envoie un message coquin à ton ou ta partenaire, ou passe ton tour.',
      'Embrasse le doigt de la personne de ton choix, le plus lentement possible.',
      'Décris ta dernière fois en trois mots.',
      'Donne une petite fessée à la personne de ton choix, si elle est d’accord.',
    ],
  },
}
