import type { Level } from '../engine'

/** Action ou Vérité — questions « Vérité ». */
export const truths: Record<Level, string[]> = {
  soft: [
    'Quelle est ta plus grosse honte au collège ?',
    'Quel est le pire cadeau que tu aies reçu ?',
    'Quelle habitude bizarre as-tu quand tu es seul ?',
    'Quel est ton plaisir coupable musical ?',
    'Quelle est la dernière chose que tu as cherchée sur Internet ?',
    'Quel mensonge as-tu raconté à tes parents et qu’ils croient encore ?',
    'Qui ici te fait le plus rire ?',
    'Quel métier voulais-tu faire enfant ?',
    'Quel est ton pire souvenir de vacances ?',
    'Quelle appli utilises-tu le plus, et combien de temps par jour ?',
    'Quel film t’a fait pleurer le plus ?',
    'Si tu pouvais échanger ta vie avec quelqu’un ici, ce serait qui ?',
    'Quelle est ta peur la plus irrationnelle ?',
    'Quel est le surnom le plus gênant qu’on t’ait donné ?',
    'Quel est le dernier mensonge que tu as dit ?',
    'Qu’est-ce que tu ne supportes pas chez les autres ?',
    'Quel est ton talent caché ?',
    'Quelle célébrité aimerais-tu rencontrer, et pourquoi ?',
    'Quelle est la chose la plus stupide que tu aies faite pour un pari ?',
    'As-tu fait semblant de rire à une blague ce soir ?',
    'Quel est le pire cours que tu aies eu à l’école, et pourquoi ?',
    'Quelle est la pire note que tu aies jamais eue, et dans quelle matière ?',
    'As-tu déjà triché à un examen ? Raconte comment.',
    'Quel prof t’a le plus marqué, en bien ou en mal ?',
    'Quelle bêtise d’enfance n’as-tu jamais avouée à tes parents ?',
    'Quel est ton plus vieux souvenir ?',
    'Quel dessin animé regardais-tu en boucle quand tu étais petit ?',
    'Quelle punition t’a le plus marqué quand tu étais enfant ?',
    'Quel jouet as-tu le plus regretté d’avoir perdu ou cassé ?',
    'Quelle est la pire chose que tu aies mangée par politesse ?',
    'Quel plat de ton enfance te donne encore la nausée ?',
    'Quel est le truc le plus bizarre que tu aies mangé ?',
    'Quelle est la chose la plus honteuse dans ton historique de recherche ?',
    'Quel est le dernier objet inutile que tu as acheté sur un coup de tête ?',
    'Combien as-tu dépensé pour ton achat le plus regrettable ?',
    'Quelle est la plus grosse somme que tu aies perdue ou gaspillée ?',
    'As-tu déjà oublié de payer quelque chose et fait comme si de rien n’était ?',
    'Quel est le pire job que tu aies fait, même pour une journée ?',
    'Quelle est la pire excuse que tu aies donnée pour arriver en retard ?',
    'As-tu déjà fait semblant d’être malade pour éviter quelque chose ?',
    'Quelle est la chose la plus gênante qui te soit arrivée au travail ?',
    'Quel collègue ou camarade de classe t’a rendu fou, et pourquoi ?',
    'Quel est le message le plus embarrassant que tu aies envoyé à la mauvaise personne ?',
    'As-tu déjà envoyé un mail ou un message à ton boss ou ton prof qui t’a fait regretter ?',
    'Quelle est ta plus grosse fierté jusqu’ici ?',
    'Quel défaut aimerais-tu pouvoir effacer chez toi ?',
    'Quel est ton pire défaut, selon tes proches ?',
    'Quelle qualité te manque le plus ?',
    'Quel est le compliment qui t’a le plus marqué ?',
    'Quelle est la critique qui t’a le plus blessé ?',
    'Quelle est la dernière fois que tu as pleuré, et pourquoi ?',
    'Quelle est la dernière fois que tu as eu un fou rire incontrôlable ?',
    'Quelle est la chose la plus bizarre que tu fasses quand tu es nerveux ?',
    'Quel est ton plus gros fou rire au mauvais moment ?',
    'Quelle est la pire chose que tu aies dite devant du monde sans réfléchir ?',
    'Quel est le moment où tu as eu le plus honte devant tout le monde ?',
    'Quelle erreur de prénom as-tu déjà faite devant quelqu’un ?',
    'Quel est le pire cheveu ou le pire look que tu aies eu ?',
    'Quelle photo de toi aimerais-tu voir disparaître d’Internet ?',
    'Quelle tendance de mode regrettes-tu d’avoir suivie ?',
    'Quel vêtement gardes-tu alors que tu ne le mets jamais ?',
    'Quelle est la pire coupe de cheveux que tu aies osée ?',
    'Quel est ton plus gros regret vestimentaire ?',
    'Quel est le pire cadeau que tu aies offert à quelqu’un ?',
    'As-tu déjà revendu ou re-donné un cadeau ? À qui ?',
    'Quel est le meilleur cadeau que tu aies jamais reçu ?',
    'Quel est le plus beau souvenir que tu as avec un membre de ta famille ?',
    'Qui dans ta famille te ressemble le plus, et en quoi ?',
    'Quelle phrase de tes parents t’a le plus agacé enfant ?',
    'Quelle phrase de tes parents te surprend à répéter aujourd’hui ?',
    'Quelle tradition familiale te paraît la plus étrange ?',
    'Quel est le sujet qui fait toujours s’engueuler ta famille à table ?',
    'Quel membre de ta famille te fait le plus rire ?',
    'As-tu déjà été puni à cause d’un frère, d’une sœur ou d’un cousin ?',
    'Quelle est la dispute la plus bête que tu aies eue avec un proche ?',
    'Quel est le dernier mensonge que tu as dit à un ami ?',
    'As-tu déjà trahi la confiance d’un ami ? Raconte.',
    'Quel est le meilleur souvenir que tu as avec un ami ici ?',
    'Quel ami as-tu perdu de vue, et ça te manque ?',
    'Quelle est la chose la plus folle que tu aies faite pour un ami ?',
    'Qui ici te connaît le mieux ?',
    'Qui ici est le plus mauvais en cuisine ?',
    'Qui ici serait le premier à se perdre en vacances ?',
    'Qui ici serait le meilleur colocataire, et le pire ?',
    'Qui ici pourrait devenir célèbre, et pour quelle raison ?',
    'Qui ici est le plus susceptible d’arriver en retard à son propre mariage ?',
    'Qui ici mentirait le mieux, selon toi ?',
    'Qui ici est le plus radin ?',
    'Qui ici est le plus mauvais conducteur ?',
    'Qui ici survivrait le plus longtemps sur une île déserte ?',
    'Qui ici a le meilleur style vestimentaire ?',
    'Qui ici est le plus têtu ?',
    'Qui ici est le plus drôle quand il est fatigué ?',
    'Quelle est la première chose que tu remarques chez quelqu’un ?',
    'Quelle est ta première impression sur chaque personne ici ?',
    'Quel est le dernier endroit où tu as voyagé, et qu’est-ce qui t’a le plus marqué ?',
    'Quel est le pire voyage que tu aies fait, et pourquoi ?',
    'Quelle est la chose la plus embarrassante qui t’est arrivée à l’étranger ?',
    'Quel pays rêves-tu de visiter, et pourquoi pas encore ?',
    'As-tu déjà raté un avion, un train ou un bus ? Raconte.',
    'Quelle est la pire nuit que tu aies passée à l’hôtel ou en location ?',
    'Quelle est la chose la plus bizarre que tu aies ramenée d’un voyage ?',
    'Quelle est la chose la plus effrayante que tu aies vécue en voyage ?',
    'Quel est ton pire souvenir dans les transports ?',
    'Quelle est la chose la plus bizarre que tu aies vue dans le métro ou le bus ?',
    'Quelle est la dernière chose que tu as postée sur les réseaux, et pourquoi ?',
    'Combien de temps as-tu passé sur ton téléphone aujourd’hui ?',
    'As-tu déjà eu un compte secret sur les réseaux ? Pour quoi faire ?',
    'Quel est le post le plus gênant que tu aies publié ?',
    'As-tu déjà liké une vieille photo par erreur en fouillant un profil ?',
    'Quelle est la chose la plus honteuse que tu aies partagée en ligne ?',
    'Quel influenceur ou créateur suis-tu sans oser l’avouer ?',
    'Quelle série as-tu regardée en cachette ou avec honte ?',
    'Quelle chanson connais-tu par cœur alors que tu devrais avoir honte ?',
    'Quel est le dernier film que tu as abandonné au bout de dix minutes ?',
    'Quel livre prétends-tu avoir lu sans l’avoir fini ?',
    'Quelle émission de télé regardes-tu en boucle sans te l’avouer ?',
    'Quel jeu vidéo t’a fait perdre le plus de temps ?',
    'Quelle est ta plus grande peur pour l’avenir ?',
    'De quel animal as-tu le plus peur, et pourquoi ?',
    'Quelle est la chose qui te fait le plus flipper la nuit ?',
    'As-tu peur du noir, même un tout petit peu ?',
    'Quel est ton pire cauchemar récurrent ?',
    'Quel est le rêve le plus bizarre dont tu te souviennes ?',
    'Quel est ton rêve le plus fou, celui que tu n’oses pas dire ?',
    'Si tu gagnais un million demain, quelle serait ta première dépense ?',
    'Si tu pouvais vivre n’importe où dans le monde, ce serait où ?',
    'Quel super-pouvoir choisirais-tu, et comment tu t’en servirais en vrai ?',
    'Si tu pouvais remonter le temps, quel moment de ta vie changerais-tu ?',
    'Quel conseil donnerais-tu à toi-même à quinze ans ?',
    'Qu’est-ce que tu aimerais avoir appris plus tôt dans la vie ?',
    'Quelle est la chose la plus courageuse que tu aies faite ?',
    'Quelle est la décision la plus difficile que tu aies dû prendre ?',
    'Quelle règle de vie essaies-tu de suivre sans jamais y arriver ?',
    'Quelle est ta plus grande source de stress en ce moment ?',
    'Quelle est la chose que tu remets toujours au lendemain ?',
    'Quelle corvée ménagère détestes-tu le plus ?',
    'Quel est ton niveau de désordre chez toi, honnêtement ?',
    'Quelle est la chose la plus sale ou dégoûtante que tu aies laissée traîner chez toi ?',
    'Quelle est la dernière fois que tu as fait ton lit ?',
    'Combien de temps peux-tu rester sans te doucher en vacances ?',
    'Quelle chanson chantes-tu sous la douche ?',
    'Quelle est la dernière chose que tu as faite en cachette ?',
    'Quel est le meilleur mensonge que tu aies réussi à faire croire ?',
    'As-tu déjà pris le crédit d’un travail qui n’était pas le tien ?',
    'As-tu déjà menti sur ton âge ?',
    'As-tu déjà menti dans un CV ? Sur quoi ?',
    'Quelle est la chose que tu fais en secret et que personne ne soupçonne ?',
    'Quelle est la superstition à laquelle tu crois vraiment ?',
    'Quelle est la dernière chose que tu as volée, même une bricole ?',
    'Quelle est la chose illégale la plus anodine que tu aies faite ?',
    'As-tu déjà roulé trop vite et été arrêté ? Raconte.',
    'As-tu déjà reçu une amende, et pour quelle raison idiote ?',
    'Quelle est ta pire manie en voiture ?',
    'Quelle est la chose que tu fais en conduisant et que tu ne devrais pas ?',
    'Quelle personne publique te laisse totalement indifférent alors que tout le monde l’adore ?',
    'Quel est l’avis impopulaire dont tu es le plus sûr ?',
    'Quelle est la mode ou la tendance que tu détestes le plus ?',
    'Quelle est la chose la plus surcotée selon toi ?',
    'Quelle est l’habitude d’un ami ici qui te gêne le plus ?',
    'As-tu déjà parlé dans le dos de quelqu’un ici ?',
    'Qu’est-ce que tu penses vraiment de ta ville ?',
    'Quelle est la dernière fois que tu as pris une grosse décision au hasard ?',
    'Que ferais-tu si tu étais invisible pendant une journée ?',
    'Qu’est-ce qui te donne envie de tout plaquer ?',
    'Quelle activité aimerais-tu essayer mais tu n’oses pas ?',
    'Quelle est ta meilleure anecdote de soirée de l’année ?',
    'Quelle est la chose que tu aimerais que tes amis sachent sur toi ?',
  ],
  spicy: [
    'Qui était ton premier bisou, et comment c’était ?',
    'As-tu déjà eu un crush sur quelqu’un ici ?',
    'Quel est ton pire date ?',
    'Si tu devais recontacter un ex ce soir, lequel ?',
    'Quel est le message le plus gênant de ton téléphone ?',
    'Qui ici serait ton plan de secours pour le mariage ?',
    'As-tu déjà menti pour écourter un date ?',
    'Quelle est la pire chose que tu aies faite après quelques verres ?',
    'As-tu déjà été jaloux d’un ou une amie ici ?',
    'Combien de temps a duré ta relation la plus courte ?',
    'Qui ici embrasserais-tu si tu y étais obligé ?',
    'As-tu stalké un ex dans les dernières 24 h ?',
    'Quelle est ta technique de drague ?',
    'As-tu déjà été ghosté ? Raconte.',
    'Quel est le pire défaut de ton ex ?',
    'Avec qui ici partirais-tu en vacances en amoureux ?',
    'Quel secret n’as-tu jamais confié à ton ou ta meilleure amie ?',
    'Quelle note sur 10 te donnes-tu au premier date ?',
    'As-tu déjà craqué pour quelqu’un de déjà pris ?',
    'Quel est le message que tu regrettes le plus d’avoir envoyé ?',
    'Quelle est la pire phrase d’accroche qu’on t’ait sortie ?',
    'Quelle est la pire phrase d’accroche que tu aies sortie ?',
    'Quel est le premier truc que tu regardes chez quelqu’un qui te plaît ?',
    'Comment sais-tu que quelqu’un te plaît vraiment ?',
    'As-tu déjà dragué quelqu’un en soirée en faisant semblant d’être quelqu’un d’autre ?',
    'Quel est ton pire râteau, et comment as-tu réagi ?',
    'As-tu déjà pris un vent devant tout le monde ?',
    'Quel est le plus gros vent que tu aies mis à quelqu’un ?',
    'As-tu déjà inventé une excuse pour ne pas rappeler quelqu’un ?',
    'As-tu déjà fait semblant d’avoir un copain ou une copine pour te débarrasser de quelqu’un ?',
    'Quelle est la plus longue période où tu as été célibataire, et comment tu l’as vécue ?',
    'Quel est le meilleur conseil de drague que tu aies reçu ?',
    'Quelle application de rencontre as-tu déjà utilisée, et quel profil t’a le plus marqué ?',
    'Quelle est la phrase la plus bizarre qu’on t’ait envoyée sur une appli de rencontre ?',
    'Quelle photo de profil aurais-tu honte qu’on voie sur une appli de rencontre ?',
    'As-tu déjà swipé sur quelqu’un que tu connaissais ? Que s’est-il passé ?',
    'Quel est le premier message que tu envoies à quelqu’un qui te plaît ?',
    'As-tu déjà écrit un long message pour finalement ne jamais l’envoyer ?',
    'As-tu déjà regardé le téléphone de ton ou ta partenaire ? Qu’as-tu trouvé ?',
    'As-tu déjà été jaloux au point de faire une scène ?',
    'Qu’est-ce qui te rend le plus jaloux dans une relation ?',
    'As-tu déjà été le ou la meilleur(e) ami(e) de quelqu’un qui te plaisait en secret ?',
    'As-tu déjà été amoureux d’un ou d’une amie à son insu ?',
    'Quel est ton plus beau souvenir avec un ex ?',
    'Pourquoi ta dernière relation s’est-elle terminée ?',
    'As-tu déjà quitté quelqu’un par message ?',
    'As-tu déjà été quitté par message ? Comment as-tu réagi ?',
    'Quelle est la pire raison pour laquelle tu as rompu avec quelqu’un ?',
    'Quelle est la pire raison pour laquelle quelqu’un a rompu avec toi ?',
    'As-tu déjà gardé le contact avec un ex alors que ça aurait dû s’arrêter ?',
    'As-tu déjà rappelé un ex en pleine nuit ?',
    'As-tu déjà supprimé un ex de tes réseaux dans un moment de colère ?',
    'As-tu déjà gardé des affaires d’un ex ? Lesquelles ?',
    'Quelle est la chose la plus romantique qu’on ait faite pour toi ?',
    'Quelle est la chose la plus romantique que tu aies faite pour quelqu’un ?',
    'Quel est le cadeau le plus nul que tu aies reçu d’un ex ?',
    'Quel est le pire rendez-vous romantique de ta vie ?',
    'Quel est l’endroit le plus étrange où tu as fait un rendez-vous ?',
    'As-tu déjà eu un coup de foudre ? Pour qui ?',
    'À quelle fréquence tombes-tu amoureux, honnêtement ?',
    'As-tu déjà dit « je t’aime » trop tôt ? Raconte.',
    'As-tu déjà dit « je t’aime » sans le penser ?',
    'Quelle est la phrase que tu rêves d’entendre de la personne que tu aimes ?',
    'Quel est le défaut chez un partenaire que tu ne pourrais jamais accepter ?',
    'Quel est le défaut chez un partenaire que tu accepterais finalement ?',
    'À quel moment de la relation présenterais-tu quelqu’un à tes parents ?',
    'Quelle est la pire rencontre avec les parents d’un ex ?',
    'Quelle est la chose la plus bête pour laquelle tu t’es disputé avec ton ou ta partenaire ?',
    'Qu’est-ce que tu es prêt(e) à pardonner dans un couple, et qu’est-ce qui est impardonnable ?',
    'As-tu déjà trompé quelqu’un, ou été tenté de le faire ?',
    'As-tu déjà été trompé(e) ? Comment l’as-tu découvert ?',
    'As-tu déjà sorti avec un ou une ami(e) d’un ex ?',
    'Y a-t-il quelqu’un dans ton entourage que tu pourrais aimer mais que tu fuis ?',
    'Quelle est la personne ici avec qui tu aurais le plus de mal à sortir ?',
    'Quelle est la personne ici avec qui tu aurais le plus de facilité à sortir ?',
    'Qui ici est le plus doué pour la drague ?',
    'Qui ici serait le meilleur partenaire de vie ?',
    'Qui ici est le plus romantique selon toi ?',
    'Qui ici est le plus jaloux, selon toi ?',
    'Qui ici a le meilleur sourire ?',
    'Qui ici est le plus craquant quand il ou elle rit ?',
    'Qui ici a le plus de succès en soirée ?',
    'Qui ici a le pire goût en matière de relations ?',
    'Qui ici est le plus susceptible de tomber amoureux d’un ami ?',
    'Qui ici garderait le plus longtemps le contact avec un ex ?',
    'Qui ici est le plus hypocrite quand il s’agit d’amour ?',
    'Qui ici pourrait se marier le plus vite ?',
    'Quelle est la pire chose que tu aies faite sous l’emprise de l’alcool ?',
    'Quel est ton pire souvenir de lendemain de soirée ?',
    'As-tu déjà oublié une partie de ta soirée à cause de l’alcool ? Qu’a-t-on dû te raconter ?',
    'Quelle est la chose la plus honteuse que tu aies dite en étant bourré(e) ?',
    'As-tu déjà vomi en soirée ? Où, et devant qui ?',
    'As-tu déjà dormi quelque part d’improbable après une soirée ?',
    'Quel est le message le plus gênant que tu aies envoyé en étant ivre ?',
    'As-tu déjà appelé quelqu’un en soirée alors que tu ne devrais pas ?',
    'Quelle est la boisson qui te met dans le pire état ?',
    'Combien de verres as-tu déjà bus en une soirée, au maximum ?',
    'As-tu déjà été le ou la dernier(e) debout d’une soirée ? Qu’as-tu fait ?',
    'As-tu déjà fait honte à un ami en soirée ?',
    'Quel est ton meilleur souvenir de soirée entre amis ?',
    'Quelle est la soirée dont tu as le plus honte ?',
    'As-tu déjà été jeté(e) dehors d’une soirée ou d’un bar ?',
    'As-tu déjà dansé sur une table ? Raconte.',
    'As-tu déjà fait un strip-tease ou un défi osé en soirée ?',
    'As-tu déjà chanté au karaoké en public ? Quelle chanson ?',
    'As-tu déjà embrassé quelqu’un pour un jeu ?',
    'As-tu déjà joué à action ou vérité avec une action vraiment gênante ?',
    'As-tu déjà pleuré en soirée sans raison ?',
    'As-tu déjà dit à quelqu’un ses quatre vérités en soirée ?',
    'As-tu déjà eu envie de quitter une soirée discrètement sans dire au revoir ?',
    'Quel est le secret le plus lourd que tu gardes pour un ami ?',
    'Quel secret as-tu failli révéler un soir de trop ?',
    'Quelle est la chose la plus embarrassante que tu aies faite devant un crush ?',
    'Quelle est la chose la plus embarrassante qu’un crush ait vue de toi ?',
    'Quel est le moment le plus gênant de ta vie amoureuse ?',
    'Quelle est la chose que tu as faite pour impressionner quelqu’un ?',
    'As-tu déjà menti sur ton âge, ton métier ou ta vie pour plaire ?',
    'As-tu déjà changé ta façon d’être pour plaire à quelqu’un ?',
    'As-tu déjà fait semblant d’aimer quelque chose pour séduire ?',
    'As-tu déjà pleuré pour une rupture au travail ou en public ?',
    'As-tu déjà été mis(e) dans une situation gênante par un ex en public ?',
    'As-tu déjà couru après quelqu’un qui n’en valait pas la peine ?',
    'As-tu déjà cherché à rendre un ex jaloux ?',
    'As-tu déjà posté une photo uniquement pour qu’un ex la voie ?',
    'Quelle chanson te rappelle un ex ?',
    'Quelle chanson te met dans l’ambiance pour séduire ?',
    'Quelle chanson te donne envie d’écrire à un ex ?',
    'Quelle est la pire chose que tu aies dite pendant une dispute ?',
    'As-tu déjà fait un caprice digne d’un enfant pendant une relation ?',
    'As-tu déjà abandonné quelqu’un à un rendez-vous ?',
    'As-tu déjà été en retard à un premier rendez-vous ? Quelle excuse as-tu donnée ?',
    'As-tu déjà vu un ex en soirée ? Comment ça s’est passé ?',
    'As-tu déjà dormi chez un ami pour éviter de rentrer chez ton ou ta partenaire ?',
    'As-tu déjà menti à un ami sur ta vie amoureuse ?',
    'Quelle est la pire chose que quelqu’un ait faite pour te séduire ?',
    'Quelle est la plus grande preuve d’amour que tu aies reçue ?',
    'Quel est le geste de séduction qui te fait craquer ?',
    'Quel est le geste de séduction qui te fait fuir ?',
    'Quel est le détail qui te fait craquer chez quelqu’un ?',
    'Quelle est ta plus grande peur en amour ?',
    'Quelle est la chose que tu refuses de faire dans une relation ?',
    'Es-tu plutôt romantique ou plutôt distant dans une relation ?',
    'Es-tu plutôt jaloux ou plutôt confiant dans une relation ?',
    'Qu’est-ce que tu ne dirais jamais à quelqu’un qui te plaît ?',
    'Si tu devais choisir un seul ex pour une nuit de retrouvailles, ce serait qui ?',
    'Quel est le dernier mensonge que tu as dit à une personne qui te plaisait ?',
    'À quelle fréquence mens-tu pour éviter une dispute ?',
    'Quelle est la chose la plus folle que tu aies faite par amour ?',
    'Quelle est la chose la plus lâche que tu aies faite en amour ?',
    'Quelle est la dernière fois que tu as eu les papillons dans le ventre ?',
    'Quelle est la phrase la plus nulle que tu aies dite à un premier rendez-vous ?',
    'As-tu déjà été trop collant(e) avec quelqu’un ? Raconte.',
    'As-tu déjà essayé de séduire quelqu’un devant ses amis ? Raconte.',
    'Quel est le surnom le plus ridicule qu’un ex t’ait donné ?',
    'Quel est ton pire souvenir de Saint-Valentin ?',
    'Quel est ton meilleur souvenir de Saint-Valentin ?',
    'Quelle est la pire sortie en couple que tu aies faite ?',
    'Quel est le prénom que tu as le plus envie de revoir s’afficher sur ton téléphone ?',
    'Quelle est la dernière personne à qui tu as pensé avant de t’endormir hier ?',
    'As-tu déjà fait un truc ridicule pour attirer l’attention d’un crush ?',
    'Qu’est-ce que tu ferais si ton ex t’écrivait à l’instant ?',
    'Quelle est la plus grosse erreur que tu aies faite en début de relation ?',
  ],
  hot: [
    'Quel est ton plus grand fantasme ?',
    'Quel est l’endroit le plus fou où tu as fait l’amour ?',
    'As-tu déjà simulé ?',
    'Quelle est ta position préférée ?',
    'Qui ici trouves-tu le plus attirant ?',
    'As-tu déjà envoyé une photo coquine ? Le regrettes-tu ?',
    'Combien de partenaires as-tu eus ?',
    'Quel est ton meilleur souvenir au lit ?',
    'Quel est ton pire souvenir au lit ?',
    'As-tu déjà eu un plan à trois, ou en as-tu envie ?',
    'Quelle partie du corps te fait craquer en premier ?',
    'As-tu un sextoy ? Lequel ?',
    'As-tu déjà couché le premier soir ?',
    'As-tu déjà été surpris en plein acte ?',
    'Quel est ton fantasme le plus inavouable ?',
    'Avec qui ici passerais-tu une nuit, juste une ?',
    'Quelle est la chose la plus coquine que tu aies faite en public ?',
    'Préfères-tu dominer ou être dominé ?',
    'Quel est le rêve érotique dont tu te souviens le mieux ?',
    'Qu’est-ce que tu n’as jamais osé demander au lit ?',
    'Quel est le meilleur baiser de ta vie, et avec qui ?',
    'Quel est le pire baiser que tu aies donné ou reçu ?',
    'Quelle est la zone la plus sensible de ton corps ?',
    'Quelle est la partie du corps que tu préfères embrasser ?',
    'Quel est ton moment préféré pendant les préliminaires ?',
    'Qu’est-ce qui te met le plus rapidement dans l’ambiance ?',
    'Qu’est-ce qui te coupe tout de suite l’envie ?',
    'Quelle est la phrase qui te fait fondre à l’oreille ?',
    'Quel est le geste le plus sensuel que quelqu’un ait fait sur toi ?',
    'Quelle est la chose la plus sexy qu’une personne puisse porter, selon toi ?',
    'Quelle tenue te fait le plus d’effet chez quelqu’un ?',
    'Quelle est la pièce de lingerie ou le sous-vêtement qui t’excite le plus ?',
    'As-tu déjà dormi nu(e) chez quelqu’un que tu ne connaissais presque pas ?',
    'Quel est l’endroit le plus risqué où tu aies failli te faire surprendre ?',
    'As-tu déjà fait l’amour dans une voiture ? Raconte sans détails.',
    'As-tu déjà fait l’amour en plein air ? Où ça ?',
    'As-tu déjà fait l’amour chez les parents de quelqu’un ?',
    'As-tu déjà fait l’amour sur une plage ou dans l’eau ?',
    'As-tu déjà fait l’amour dans les toilettes d’un bar ou d’une boîte ?',
    'As-tu déjà fait l’amour dans un lieu de travail ?',
    'As-tu déjà fait l’amour avec quelqu’un dont tu ne connaissais pas le prénom ?',
    'As-tu déjà eu une aventure d’un soir que tu regrettes ?',
    'As-tu déjà eu une aventure d’un soir que tu revivrais volontiers ?',
    'As-tu déjà été en relation purement physique avec quelqu’un ?',
    'As-tu déjà eu un « plan cul » récurrent avec un ami ?',
    'Quelle est la plus longue période que tu aies passée sans aucune relation intime ?',
    'Combien de fois par semaine voudrais-tu passer à l’action, idéalement ?',
    'Quelle est la fréquence idéale pour toi dans une relation ?',
    'À quel moment de la relation estimes-tu qu’on peut coucher ensemble ?',
    'Es-tu plutôt du matin, de l’après-midi ou du soir pour ça ?',
    'Préfères-tu la douceur ou la passion ?',
    'Préfères-tu les câlins avant ou après ?',
    'Préfères-tu la lumière allumée ou éteinte ?',
    'Préfères-tu prendre l’initiative ou la laisser à l’autre ?',
    'Préfères-tu les surprises ou ce qui est planifié ?',
    'Préfères-tu un partenaire expérimenté ou novice ?',
    'Préfères-tu parler pendant ou rester silencieux(se) ?',
    'Préfères-tu une nuit entière ou un moment rapide ?',
    'Quelle est la chose la plus osée que tu aies faite avec un partenaire ?',
    'Quelle est la chose la plus osée que tu aimerais essayer ?',
    'Quel jeu coquin aimerais-tu proposer à ton partenaire ?',
    'As-tu déjà joué à un jeu de rôle coquin ? Quel personnage jouais-tu ?',
    'As-tu déjà utilisé un déguisement ou une tenue spéciale pendant un moment intime ?',
    'As-tu déjà utilisé de la nourriture ou des produits pendant un moment intime ?',
    'As-tu déjà été attaché(e) ou as-tu déjà attaché quelqu’un ?',
    'As-tu déjà reçu un massage qui a dérapé ?',
    'As-tu déjà été surpris(e) en train de regarder ou lire quelque chose de coquin ?',
    'As-tu déjà lu une histoire érotique ? Laquelle t’a marqué ?',
    'Quel film ou quelle série trouves-tu le plus sensuel ?',
    'Quelle scène de film coquine t’a le plus marqué ?',
    'Quel personnage de fiction t’a fait craquer plus que de raison ?',
    'Quelle célébrité te fait le plus d’effet ?',
    'Quelle est ta plus grande insécurité physique devant quelqu’un ?',
    'Quelle partie de ton corps préfères-tu qu’on remarque ?',
    'Quelle partie de ton corps aimerais-tu qu’on remarque davantage ?',
    'Quel complexe physique as-tu du mal à dévoiler à un partenaire ?',
    'As-tu déjà eu un fou rire pendant un moment intime ?',
    'As-tu déjà eu un incident gênant pendant un moment intime ?',
    'As-tu déjà dit un mauvais prénom au pire moment ?',
    'As-tu déjà fait semblant de dormir pour éviter un rapprochement ?',
    'As-tu déjà dit non à quelqu’un qui te plaisait pourtant ? Pourquoi ?',
    'As-tu déjà regretté d’avoir dit non à une proposition coquine ?',
    'As-tu déjà dragué quelqu’un du même sexe ou eu envie de le faire ?',
    'As-tu déjà été attiré(e) par un ou une collègue, ou un prof ?',
    'As-tu déjà eu une relation avec un ou une collègue ?',
    'As-tu déjà eu envie de quelqu’un qui était l’ami ou l’amie de ton partenaire ?',
    'As-tu déjà eu envie de quelqu’un d’interdit ou de très inattendu ?',
    'As-tu déjà été tenté(e) de coucher avec un ex ? Est-ce arrivé ?',
    'As-tu déjà couché avec un ex après votre rupture ?',
    'Quel ex te reste le plus en tête dans l’intimité, sans entrer dans les détails ?',
    'Quelle est la chose qui te manque le plus d’une ancienne relation intime ?',
    'Que penses-tu des amis avec bénéfices ?',
    'Penses-tu qu’une relation sans engagement physique est possible ?',
    'Quel est ton avis sur le sexe avant le mariage ?',
    'Quel est ton avis sur les relations libres ?',
    'Quel est ton avis sur les couples échangistes ?',
    'Quel est ton avis sur les rencontres uniquement physiques via des applis ?',
    'As-tu déjà utilisé une appli de rencontre pour un plan d’un soir ?',
    'As-tu déjà vécu une rencontre en ligne qui a fini au lit ?',
    'Quelle est la chose la plus coquine que tu aies écrite par message ?',
    'As-tu déjà fait du sexting avec quelqu’un que tu venais de rencontrer ?',
    'As-tu déjà reçu une photo coquine non sollicitée ? Comment as-tu réagi ?',
    'As-tu déjà fait un appel vidéo coquin ?',
    'As-tu déjà envoyé un message coquin à la mauvaise personne ?',
    'As-tu déjà eu envie de quelqu’un à travers un écran seulement ?',
    'Quel est le message le plus coquin que tu aies reçu ?',
    'Quelle est la phrase la plus osée qu’on t’ait glissée à l’oreille ?',
    'Quel mot ou quelle phrase t’excite le plus ?',
    'Quel est ton plus gros fantasme de lieu ?',
    'Quel est ton plus gros fantasme de situation ?',
    'Quel est ton plus gros fantasme de tenue ?',
    'Quel est ton fantasme de voyage ou de vacances ?',
    'Si tu pouvais passer une nuit avec un personnage de fiction, ce serait qui ?',
    'Si tu devais choisir une personne ici pour un massage sensuel, ce serait qui ?',
    'Si tu devais choisir une personne ici pour un slow collé-serré, ce serait qui ?',
    'Si tu devais choisir une personne ici pour un baiser langoureux, ce serait qui ?',
    'Qui ici serait le meilleur au lit selon toi ?',
    'Qui ici serait le plus coquin, selon toi ?',
    'Qui ici serait le plus timide au lit ?',
    'Qui ici serait le plus doux, selon toi ?',
    'Qui ici serait le plus aventurier au lit ?',
    'Qui ici a le plus de charme sans le savoir ?',
    'Qui ici est le plus sexy quand il ou elle ne s’en rend pas compte ?',
    'Qui ici a la voix la plus sensuelle ?',
    'Qui ici a le regard le plus envoûtant ?',
    'Qui ici a les plus belles mains ?',
    'Qui ici embrasse le mieux, à ton avis ?',
    'Qui ici te donnerait envie de faire des folies ?',
    'Quel est ton rituel avant une soirée où tu espères séduire ?',
    'Quelle odeur te donne envie de te rapprocher de quelqu’un ?',
    'Quel parfum te fait craquer ?',
    'Quelle musique te met le plus dans l’ambiance ?',
    'Quelle est ta playlist idéale pour une soirée à deux ?',
    'Quelle est la boisson idéale pour une soirée coquine ?',
    'Quel est le décor idéal pour une soirée romantique et coquine ?',
    'Quel est le meilleur compliment coquin qu’on t’ait fait ?',
    'Quel compliment coquin rêverais-tu d’entendre ?',
    'Quel est le moment où tu t’es senti(e) le plus désirable ?',
    'Quel est le moment où tu t’es senti(e) le plus désiré(e) ?',
    'Quelle est la chose la plus audacieuse que tu aies faite pour séduire ?',
    'Quelle est la chose la plus audacieuse qu’on ait faite pour te séduire ?',
    'Qu’est-ce qui te rend le plus nerveux(se) avant un premier moment intime ?',
    'Qu’est-ce qui te rassure le plus avec un nouveau partenaire ?',
    'Qu’est-ce qui compte le plus pour toi au lit : l’émotion, la technique ou l’envie ?',
    'Qu’est-ce que tu aimerais que ton partenaire fasse plus souvent ?',
    'Qu’est-ce que tu aimerais que ton partenaire fasse moins souvent ?',
    'Quelle est la chose la plus romantique qu’on ait faite pour toi dans l’intimité ?',
    'Quelle est la chose la plus drôle qui te soit arrivée dans l’intimité ?',
    'As-tu déjà fait une promesse coquine que tu n’as jamais tenue ?',
    'As-tu déjà rougi à cause d’un message ou d’un regard ?',
    'As-tu déjà dansé de façon très sensuelle devant quelqu’un ?',
    'As-tu déjà fait un strip-tease, même pour rire ?',
    'As-tu déjà pris une douche à deux ?',
    'As-tu déjà pris un bain à deux, avec bougies et tout ?',
    'As-tu déjà fait un massage érotique à quelqu’un ?',
    'As-tu déjà été réveillé(e) par un câlin très entreprenant ?',
    'As-tu déjà passé une journée entière au lit avec quelqu’un ?',
    'As-tu déjà passé un week-end entier enfermé(e) avec un partenaire ?',
    'As-tu déjà eu envie de quitter un dîner pour rentrer vite avec quelqu’un ?',
    'As-tu déjà fait un baiser très long en public ?',
    'As-tu déjà été trop entreprenant(e) avec quelqu’un en soirée ?',
    'As-tu déjà été déçu(e) par quelqu’un après une longue attente ?',
    'As-tu déjà eu un coup de cœur uniquement pour le physique de quelqu’un ?',
    'Qu’est-ce qui t’attire en premier : le physique, l’humour ou l’intelligence ?',
    'Qu’est-ce qui te séduit en premier chez quelqu’un en soirée ?',
    'Comment décrirais-tu ton style de séduction en trois mots ?',
    'Quel est ton atout séduction numéro un ?',
    'Quelle est ta plus grosse erreur de séduction ?',
    'Quelle est ta plus grande qualité au lit selon tes ex ?',
    'Quelle est ton plus grand défaut au lit selon tes ex ?',
    'Quel est le conseil intime que tu donnerais à tes amis ici ?',
  ],
}
