import type { Level } from '../engine'

/** Undercover — paires de mots proches ; l'appli tire au hasard lequel est celui des civils. */
export const undercoverPairs: Record<Level, [string, string][]> = {
  soft: [
    ['Chat', 'Tigre'],
    ['Café', 'Thé'],
    ['Plage', 'Piscine'],
    ['Instagram', 'TikTok'],
    ['Chien', 'Loup'],
    ['Pizza', 'Tarte flambée'],
    ['Pomme', 'Poire'],
    ['Fraise', 'Framboise'],
    ['Banane', 'Mangue'],
    ['Orange', 'Mandarine'],
    ['Citron', 'Pamplemousse'],
    ['Cerise', 'Prune'],
    ['Raisin', 'Groseille'],
    ['Carotte', 'Radis'],
    ['Tomate', 'Poivron'],
    ['Concombre', 'Courgette'],
    ['Pomme de terre', 'Patate douce'],
    ['Salade', 'Épinards'],
    ['Chou-fleur', 'Brocoli'],
    ['Oignon', 'Échalote'],
    ['Ail', 'Gingembre'],
    ['Beurre', 'Margarine'],
    ['Lait', 'Crème'],
    ['Yaourt', 'Fromage blanc'],
    ['Camembert', 'Brie'],
    ['Emmental', 'Gruyère'],
    ['Jambon', 'Saucisson'],
    ['Poulet', 'Dinde'],
    ['Steak', 'Escalope'],
    ['Saumon', 'Thon'],
    ['Crevette', 'Langoustine'],
    ['Huître', 'Moule'],
    ['Pain', 'Brioche'],
    ['Croissant', 'Pain au chocolat'],
    ['Baguette', 'Ficelle'],
    ['Crêpe', 'Gaufre'],
    ['Gâteau', 'Tarte'],
    ['Éclair', 'Religieuse'],
    ['Macaron', 'Meringue'],
    ['Chocolat', 'Caramel'],
    ['Glace', 'Sorbet'],
    ['Bonbon', 'Chewing-gum'],
    ['Confiture', 'Miel'],
    ['Nutella', 'Speculoos'],
    ['Pâtes', 'Riz'],
    ['Spaghetti', 'Tagliatelles'],
    ['Lasagnes', 'Cannelloni'],
    ['Burger', 'Kebab'],
    ['Frites', 'Chips'],
    ['Hot-dog', 'Sandwich'],
    ['Sushi', 'Maki'],
    ['Soupe', 'Velouté'],
    ['Omelette', 'Œufs brouillés'],
    ['Quiche', 'Tourte'],
    ['Fondue', 'Raclette'],
    ['Couscous', 'Tajine'],
    ['Coca', 'Pepsi'],
    ['Jus d’orange', 'Jus de pomme'],
    ['Limonade', 'Orangina'],
    ['Eau plate', 'Eau gazeuse'],
    ['Expresso', 'Cappuccino'],
    ['Lion', 'Panthère'],
    ['Éléphant', 'Rhinocéros'],
    ['Girafe', 'Zèbre'],
    ['Singe', 'Gorille'],
    ['Ours', 'Panda'],
    ['Renard', 'Blaireau'],
    ['Lapin', 'Lièvre'],
    ['Cheval', 'Âne'],
    ['Vache', 'Chèvre'],
    ['Mouton', 'Agneau'],
    ['Cochon', 'Sanglier'],
    ['Poule', 'Canard'],
    ['Oie', 'Cygne'],
    ['Aigle', 'Faucon'],
    ['Hibou', 'Chouette'],
    ['Perroquet', 'Perruche'],
    ['Pigeon', 'Mouette'],
    ['Dauphin', 'Requin'],
    ['Baleine', 'Orque'],
    ['Tortue', 'Escargot'],
    ['Grenouille', 'Crapaud'],
    ['Serpent', 'Lézard'],
    ['Crocodile', 'Alligator'],
    ['Papillon', 'Libellule'],
    ['Abeille', 'Guêpe'],
    ['Fourmi', 'Termite'],
    ['Araignée', 'Scorpion'],
    ['Souris', 'Hamster'],
    ['Poisson rouge', 'Poisson clown'],
    ['Kangourou', 'Koala'],
    ['Pingouin', 'Manchot'],
    ['Écureuil', 'Hérisson'],
    ['Mer', 'Océan'],
    ['Montagne', 'Colline'],
    ['Forêt', 'Jungle'],
    ['Lac', 'Étang'],
    ['Rivière', 'Fleuve'],
    ['Désert', 'Savane'],
    ['Île', 'Presqu’île'],
    ['Volcan', 'Geyser'],
    ['Neige', 'Grêle'],
    ['Pluie', 'Brouillard'],
    ['Soleil', 'Lune'],
    ['Étoile', 'Comète'],
    ['Orage', 'Tempête'],
    ['Arc-en-ciel', 'Aurore boréale'],
    ['Paris', 'Londres'],
    ['New York', 'Los Angeles'],
    ['Tour Eiffel', 'Arc de Triomphe'],
    ['Louvre', 'Versailles'],
    ['Disneyland', 'Parc Astérix'],
    ['Zoo', 'Cirque'],
    ['Musée', 'Galerie'],
    ['Cinéma', 'Théâtre'],
    ['Bibliothèque', 'Librairie'],
    ['Hôpital', 'Clinique'],
    ['École', 'Collège'],
    ['Lycée', 'Université'],
    ['Boulangerie', 'Pâtisserie'],
    ['Supermarché', 'Épicerie'],
    ['Boucherie', 'Poissonnerie'],
    ['Marché', 'Brocante'],
    ['Restaurant', 'Cantine'],
    ['Hôtel', 'Auberge'],
    ['Camping', 'Chalet'],
    ['Château', 'Palais'],
    ['Église', 'Cathédrale'],
    ['Gare', 'Aéroport'],
    ['Voiture', 'Camion'],
    ['Moto', 'Scooter'],
    ['Vélo', 'Trottinette'],
    ['Train', 'Tramway'],
    ['Métro', 'Bus'],
    ['Avion', 'Hélicoptère'],
    ['Bateau', 'Voilier'],
    ['Taxi', 'Uber'],
    ['Football', 'Rugby'],
    ['Tennis', 'Badminton'],
    ['Basket', 'Handball'],
    ['Natation', 'Plongée'],
    ['Ski', 'Snowboard'],
    ['Judo', 'Karaté'],
    ['Yoga', 'Pilates'],
    ['Course à pied', 'Marche'],
    ['Golf', 'Minigolf'],
    ['Pétanque', 'Bowling'],
    ['Échecs', 'Dames'],
    ['Poker', 'Belote'],
    ['Monopoly', 'Cluedo'],
    ['Puzzle', 'Lego'],
    ['Playstation', 'Xbox'],
    ['Mario', 'Sonic'],
    ['Minecraft', 'Fortnite'],
    ['Netflix', 'Disney+'],
    ['YouTube', 'Twitch'],
    ['WhatsApp', 'Messenger'],
    ['Facebook', 'Snapchat'],
    ['Google', 'Bing'],
    ['Amazon', 'Cdiscount'],
    ['iPhone', 'Samsung'],
    ['Ordinateur', 'Tablette'],
    ['Télévision', 'Projecteur'],
    ['Casque', 'Écouteurs'],
    ['Montre', 'Bracelet'],
    ['Lunettes', 'Lentilles'],
    ['Chapeau', 'Casquette'],
    ['Écharpe', 'Foulard'],
    ['Jean', 'Jogging'],
    ['Chaussettes', 'Collants'],
    ['Baskets', 'Bottes'],
    ['Sac à dos', 'Valise'],
    ['Parapluie', 'Imperméable'],
    ['Stylo', 'Crayon'],
    ['Gomme', 'Correcteur'],
    ['Livre', 'Magazine'],
    ['Journal', 'Bande dessinée'],
    ['Canapé', 'Fauteuil'],
    ['Lit', 'Hamac'],
    ['Table', 'Bureau'],
    ['Chaise', 'Tabouret'],
    ['Armoire', 'Commode'],
    ['Miroir', 'Fenêtre'],
    ['Couteau', 'Fourchette'],
    ['Cuillère', 'Louche'],
    ['Assiette', 'Bol'],
    ['Verre', 'Tasse'],
    ['Casserole', 'Poêle'],
    ['Four', 'Micro-ondes'],
    ['Frigo', 'Congélateur'],
    ['Lave-linge', 'Lave-vaisselle'],
    ['Aspirateur', 'Balai'],
    ['Brosse à dents', 'Fil dentaire'],
    ['Shampoing', 'Gel douche'],
    ['Savon', 'Dentifrice'],
    ['Bougie', 'Lampe'],
    ['Radio', 'Podcast'],
    ['Guitare', 'Ukulélé'],
    ['Piano', 'Orgue'],
    ['Violon', 'Violoncelle'],
    ['Batterie', 'Tambour'],
    ['Flûte', 'Trompette'],
    ['Médecin', 'Infirmier'],
    ['Pompier', 'Policier'],
    ['Boulanger', 'Pâtissier'],
    ['Cuisinier', 'Serveur'],
    ['Professeur', 'Instituteur'],
    ['Avocat', 'Juge'],
    ['Pilote', 'Hôtesse de l’air'],
    ['Plombier', 'Électricien'],
    ['Facteur', 'Livreur'],
    ['Coiffeur', 'Barbier'],
    ['Chanteur', 'Rappeur'],
    ['Acteur', 'Humoriste'],
    ['Peintre', 'Sculpteur'],
    ['Écrivain', 'Journaliste'],
    ['Agriculteur', 'Jardinier'],
    ['Dentiste', 'Vétérinaire'],
    ['Noël', 'Nouvel An'],
    ['Pâques', 'Halloween'],
    ['Anniversaire', 'Mariage'],
    ['Carnaval', 'Fête de la musique'],
    ['Vacances', 'Week-end'],
    ['Cadeau', 'Carte postale'],
    ['Père Noël', 'Fée des dents'],
    ['Sapin', 'Guirlande'],
    ['Citrouille', 'Courge'],
    ['Shrek', 'Kung Fu Panda'],
    ['La Reine des neiges', 'Raiponce'],
    ['Simba', 'Bambi'],
    ['Tom et Jerry', 'Titi et Grosminet'],
    ['Mickey', 'Donald'],
    ['Spider-Man', 'Batman'],
    ['Harry Potter', 'Seigneur des anneaux'],
    ['Astérix', 'Tintin'],
    ['Pikachu', 'Bulbizarre'],
    ['Nemo', 'Dory'],
    ['Cendrillon', 'Blanche-Neige'],
    ['Pinocchio', 'Peter Pan'],
    ['McDonald’s', 'Burger King'],
    ['Nike', 'Adidas'],
    ['Zara', 'H&M'],
    ['Ikea', 'Leroy Merlin'],
    ['Renault', 'Peugeot'],
    ['Ferrari', 'Lamborghini'],
    ['Carrefour', 'Leclerc'],
    ['Haribo', 'Kinder'],
  ],
  spicy: [
    ['Bière', 'Cidre'],
    ['Vin rouge', 'Vin blanc'],
    ['Champagne', 'Prosecco'],
    ['Whisky', 'Cognac'],
    ['Vodka', 'Gin'],
    ['Rhum', 'Tequila'],
    ['Mojito', 'Caïpirinha'],
    ['Margarita', 'Piña colada'],
    ['Spritz', 'Sangria'],
    ['Pastis', 'Absinthe'],
    ['Shot', 'Cocktail'],
    ['Pinte', 'Demi'],
    ['Cuba libre', 'Gin tonic'],
    ['Bloody Mary', 'Daiquiri'],
    ['Kir', 'Martini'],
    ['Jägermeister', 'Get 27'],
    ['Limoncello', 'Amaretto'],
    ['Vin chaud', 'Grog'],
    ['Rosé', 'Bordeaux'],
    ['Beaujolais', 'Bourgogne'],
    ['Digestif', 'Apéritif'],
    ['Soirée', 'Boîte de nuit'],
    ['Bar', 'Pub'],
    ['Karaoké', 'Blind test'],
    ['Apéro', 'Afterwork'],
    ['After', 'Rave'],
    ['Festival', 'Concert'],
    ['Soirée mousse', 'Pool party'],
    ['Barbecue', 'Plancha'],
    ['Gueule de bois', 'Trou noir'],
    ['Ivre', 'Pompette'],
    ['Cuite', 'Biture'],
    ['Videur', 'Barman'],
    ['DJ', 'Danseur'],
    ['Piste de danse', 'Podium'],
    ['Slow', 'Rock'],
    ['Soirée pyjama', 'Soirée déguisée'],
    ['Jeu à boire', 'Action ou vérité'],
    ['Beer-pong', 'Flip cup'],
    ['Cartes', 'Dés'],
    ['Bouteille', 'Canette'],
    ['Glaçons', 'Paille'],
    ['Shaker', 'Verre à pied'],
    ['Ouvre-bouteille', 'Tire-bouchon'],
    ['Tapas', 'Mezze'],
    ['Cacahuètes', 'Olives'],
    ['Nachos', 'Tacos'],
    ['Brunch', 'Petit-déjeuner'],
    ['Tinder', 'Bumble'],
    ['Meetic', 'Hinge'],
    ['Rencard', 'Premier rendez-vous'],
    ['Drague', 'Flirt'],
    ['Compliment', 'Clin d’œil'],
    ['Bisou', 'Câlin'],
    ['Bouquet de roses', 'Boîte de chocolats'],
    ['Saint-Valentin', 'Anniversaire de rencontre'],
    ['Dîner aux chandelles', 'Pique-nique'],
    ['Film d’horreur', 'Comédie romantique'],
    ['Couple', 'Amis'],
    ['Ex', 'Crush'],
    ['Fiançailles', 'Demande en mariage'],
    ['Divorce', 'Séparation'],
    ['Lune de miel', 'Voyage de noces'],
    ['Cohabitation', 'Colocation'],
    ['Célibataire', 'Divorcé'],
    ['Ghosting', 'Seen'],
    ['Message vocal', 'Texto'],
    ['Story', 'Post'],
    ['Selfie', 'Photo de groupe'],
    ['Like', 'Abonné'],
    ['Influenceur', 'Streamer'],
    ['Speed dating', 'Soirée célibataires'],
    ['Match', 'Swipe'],
    ['Profil', 'Bio'],
    ['Coup de foudre', 'Amour platonique'],
    ['Papillons dans le ventre', 'Nœud à l’estomac'],
    ['Râteau', 'Posé un lapin'],
    ['Parfum', 'Eau de toilette'],
    ['Rouge à lèvres', 'Gloss'],
    ['Escarpins', 'Ballerines'],
    ['Cravate', 'Nœud papillon'],
    ['Costume', 'Smoking'],
    ['Robe de soirée', 'Robe de mariée'],
    ['Déguisement', 'Masque'],
    ['Perruque', 'Moustache'],
    ['Tatouage', 'Piercing'],
    ['Séance photo', 'Photomaton'],
    ['Ibiza', 'Mykonos'],
    ['Saint-Tropez', 'Cannes'],
    ['Bali', 'Thaïlande'],
    ['Marrakech', 'Istanbul'],
    ['Barcelone', 'Lisbonne'],
    ['Auberge de jeunesse', 'Airbnb'],
    ['All inclusive', 'Croisière'],
    ['Club de vacances', 'Colonie de vacances'],
    ['Bronzage', 'Coup de soleil'],
    ['Crème solaire', 'Huile de monoï'],
    ['Maillot de bain', 'Bikini'],
    ['Tongs', 'Claquettes'],
    ['Serviette de plage', 'Parasol'],
    ['Beach volley', 'Frisbee'],
    ['Surf', 'Kitesurf'],
    ['Snorkeling', 'Jet-ski'],
    ['Tomorrowland', 'Coachella'],
    ['Hellfest', 'Vieilles Charrues'],
    ['Oktoberfest', 'Féria'],
    ['Tente', 'Caravane'],
    ['Sac de couchage', 'Matelas gonflable'],
    ['Rougir', 'Trembler'],
    ['Fou rire', 'Hoquet'],
    ['Lapsus', 'Bafouille'],
    ['Honte', 'Embarras'],
    ['Ronfler', 'Parler en dormant'],
    ['Pet', 'Rot'],
    ['Transpirer', 'Puer'],
    ['Bégayer', 'Bredouiller'],
    ['Chute', 'Gaffe'],
    ['Mensonge', 'Excuse'],
    ['Cachotterie', 'Secret'],
    ['Trahison', 'Infidélité'],
    ['Jalousie', 'Rancune'],
    ['Dispute', 'Engueulade'],
    ['Réconciliation', 'Excuses'],
    ['Colocataire', 'Voisin'],
    ['Boss', 'Collègue'],
    ['Pot de départ', 'Séminaire'],
    ['Soirée d’entreprise', 'Repas de famille'],
    ['Belle-mère', 'Beau-père'],
    ['Bizutage', 'Baptême'],
    ['Chanson d’amour', 'Chanson triste'],
    ['Appel vidéo', 'Visio'],
    ['Boomerang', 'Gif'],
    ['Tuxedo', 'Blazer'],
    ['Bretzel', 'Popcorn'],
    ['Piscine privée', 'Rooftop'],
    ['Terrasse', 'Balcon'],
    ['Open bar', 'Happy hour'],
    ['Cave à vin', 'Brasserie'],
    ['Salon de thé', 'Bar à cocktails'],
    ['Péniche', 'Yacht'],
    ['Feu de camp', 'Cheminée'],
    ['Guitare de plage', 'Enceinte Bluetooth'],
    ['Soirée raclette', 'Soirée crêpes'],
    ['Nuit blanche', 'Grasse matinée'],
    ['Rendez-vous galant', 'Dîner romantique'],
    ['Message du matin', 'Bonne nuit'],
    ['Ancien amour', 'Amour de jeunesse'],
    ['Amie d’enfance', 'Meilleur pote'],
    ['Témoin', 'Demoiselle d’honneur'],
    ['Enterrement de vie de garçon', 'Enterrement de vie de jeune fille'],
    ['Alliance', 'Bague de fiançailles'],
    ['Faire-part', 'Liste de mariage'],
    ['Premier baiser', 'Première danse'],
    ['Soirée entre filles', 'Soirée entre potes'],
    ['Pendaison de crémaillère', 'Soirée de départ'],
    ['Cocktail sans alcool', 'Mocktail'],
    ['Pyjama party', 'Soirée télé'],
    ['Bal des pompiers', 'Fête du village'],
    ['Karaoké de voiture', 'Chorale de douche'],
    ['Sieste à la plage', 'Bain de soleil raté'],
    ['Plan drague', 'Plan galère'],
    ['Slow collé', 'Danse du canard'],
  ],
  hot: [
    ['Lingerie', 'Pyjama'],
    ['Dentelle', 'Satin'],
    ['String', 'Culotte'],
    ['Soutien-gorge', 'Brassière'],
    ['Porte-jarretelles', 'Bas résille'],
    ['Guêpière', 'Corset'],
    ['Nuisette', 'Peignoir'],
    ['Body', 'Combinaison'],
    ['Talons aiguilles', 'Bottes cuissardes'],
    ['Latex', 'Cuir'],
    ['Masque de nuit', 'Bandeau'],
    ['Menottes', 'Cordelette'],
    ['Plume', 'Chatouilles'],
    ['Fouet', 'Cravache'],
    ['Encens', 'Huile de massage'],
    ['Massage', 'Spa'],
    ['Jacuzzi', 'Sauna'],
    ['Bain moussant', 'Douche à deux'],
    ['Pétales de rose', 'Chocolat fondu'],
    ['Fraises au chocolat', 'Chantilly'],
    ['Love hotel', 'Motel'],
    ['Suite nuptiale', 'Chambre d’hôtes'],
    ['Lit king size', 'Lit à baldaquin'],
    ['Draps de soie', 'Couverture'],
    ['Strip-tease', 'Danse du ventre'],
    ['Pole dance', 'Lap dance'],
    ['Cabaret', 'Music-hall'],
    ['Soirée libertine', 'Soirée privée'],
    ['Sex-shop', 'Boutique coquine'],
    ['Préservatif', 'Pilule'],
    ['Kamasutra', 'Posture de yoga'],
    ['Patin', 'Smack'],
    ['Suçon', 'Morsure'],
    ['Caresse', 'Effleurement'],
    ['Cou', 'Nuque'],
    ['Oreille', 'Lobe'],
    ['Épaule', 'Dos'],
    ['Cuisse', 'Mollet'],
    ['Fesses', 'Hanches'],
    ['Torse', 'Abdos'],
    ['Décolleté', 'Bretelle'],
    ['Fossette', 'Grain de beauté'],
    ['Barbe', 'Moustache de velours'],
    ['Cologne', 'Aftershave'],
    ['Séduction', 'Charme'],
    ['Regard', 'Sourire'],
    ['Œillade', 'Haussement de sourcil'],
    ['Chuchoter', 'Murmurer'],
    ['Gémir', 'Soupirer'],
    ['Frissons', 'Chair de poule'],
    ['Désir', 'Fantasme'],
    ['Rêve érotique', 'Cauchemar'],
    ['Jeu de rôle', 'Jeu de société'],
    ['Costume d’infirmière', 'Costume de soubrette'],
    ['Uniforme', 'Tenue de bonne'],
    ['Mot de code', 'Mot de passe'],
    ['Préliminaires', 'Jeux de séduction'],
    ['Nuit torride', 'Nuit câline'],
    ['Nuit de noces', 'Nuit d’amour'],
    ['Aventure d’un soir', 'Histoire d’amour'],
    ['Amant', 'Maîtresse'],
    ['Liaison', 'Idylle'],
    ['Triangle amoureux', 'Plan à trois'],
    ['Jeu de la bouteille', 'Strip-poker'],
    ['Séance boudoir', 'Photo de vacances'],
    ['Nudiste', 'Naturiste'],
    ['Plage naturiste', 'Plage privée'],
    ['Bain de minuit', 'Baignade'],
    ['Topless', 'Monokini'],
    ['Boxer', 'Caleçon'],
    ['Slip', 'Short'],
    ['Plumeau', 'Éventail'],
    ['Voile', 'Résille'],
    ['Gants en cuir', 'Gants en satin'],
    ['Chaînette', 'Bijou de nombril'],
    ['Boucle d’oreille', 'Anneau'],
    ['Vernis à ongles', 'Faux ongles'],
    ['Épilation', 'Rasage'],
    ['Bain de soleil', 'Huile solaire'],
    ['Crème hydratante', 'Lotion'],
    ['Peau', 'Cheveux'],
    ['Lèvres', 'Langue'],
    ['Doigts', 'Mains'],
    ['Yeux', 'Cils'],
    ['Escapade', 'Week-end romantique'],
    ['Chambre d’hôtel', 'Chambre d’amis'],
    ['Ascenseur', 'Escalier'],
    ['Banquette arrière', 'Siège passager'],
    ['Fête privée', 'Soirée VIP'],
    ['Bal masqué', 'Soirée costumée'],
    ['Velours', 'Soie'],
    ['Paillettes', 'Plumes'],
    ['Bustier', 'Top tube'],
    ['Jupe courte', 'Mini-short'],
    ['Décolleté plongeant', 'Dos nu'],
    ['Robe fendue', 'Robe moulante'],
    ['Chemise ouverte', 'Chemise blanche'],
    ['Ceinture', 'Bretelles'],
    ['Jarretière', 'Jarretelle'],
    ['Bas', 'Mi-bas'],
    ['Chemise de nuit', 'T-shirt oversize'],
    ['Drap', 'Couette'],
    ['Oreiller', 'Coussin'],
    ['Matelas', 'Sommier'],
    ['Rideaux', 'Volets'],
    ['Lumière tamisée', 'Néon'],
    ['Playlist romantique', 'Musique d’ambiance'],
    ['Danse collée-serrée', 'Tango'],
    ['Salsa', 'Bachata'],
    ['Valse', 'Foxtrot'],
    ['Baiser fougueux', 'Baiser volé'],
    ['Étreinte', 'Enlacement'],
    ['Peau contre peau', 'Corps à corps'],
    ['Chaleur', 'Moiteur'],
    ['Pyjama de soie', 'Kimono'],
    ['Soirée lingerie', 'Soirée pyjama party'],
    ['Cadeau coquin', 'Carte coquine'],
    ['Pétillant', 'Brûlant'],
    ['Crème glacée', 'Glaçon'],
    ['Cire chaude', 'Huile tiède'],
    ['Eau de rose', 'Eau de lavande'],
    ['Tisane', 'Philtre d’amour'],
    ['Aphrodisiaque', 'Stimulant'],
    ['Huître aphrodisiaque', 'Chocolat noir'],
    ['Gingembre confit', 'Piment'],
    ['Ambiance tamisée', 'Éclairage tamisé'],
    ['Confidences sur l’oreiller', 'Secrets de lit'],
    ['Câlin du matin', 'Réveil en douceur'],
    ['Rougeur', 'Frisson'],
    ['Pantoufles', 'Mules à plumes'],
    ['Peignoir en soie', 'Robe de chambre'],
    ['Cheveux lâchés', 'Chignon défait'],
    ['Regard de braise', 'Œil de velours'],
    ['Sourire en coin', 'Rire coquin'],
    ['Mains baladeuses', 'Pied sous la table'],
    ['Message coquin', 'Photo coquine'],
    ['Playboy', 'Séducteur'],
    ['Allumeuse', 'Charmeuse'],
    ['Coquin', 'Polisson'],
    ['Sensuel', 'Sulfureux'],
    ['Chaud lapin', 'Dragueur'],
    ['Reine de beauté', 'Mannequin'],
    ['Soirée peignoirs', 'Soirée hammam'],
    ['Zone érogène', 'Point sensible'],
    ['Plaisir coupable', 'Petit péché'],
    ['Interdit', 'Tentation'],
    ['Péché mignon', 'Faiblesse'],
    ['Bisou dans le cou', 'Baiser sur l’épaule'],
    ['Chocolat blanc', 'Pâte d’amande'],
    ['Soie sauvage', 'Mousseline'],
    ['Collier de perles', 'Rivière de diamants'],
    ['Pétales', 'Bouquet'],
    ['Champagne rosé', 'Cidre pétillant'],
    ['Séance de spa', 'Soin du visage'],
    ['Cabine d’essayage', 'Salle de bain'],
    ['Balade romantique', 'Promenade au clair de lune'],
    ['Feu de cheminée', 'Plaid douillet'],
    ['Nuit à l’hôtel', 'Week-end en amoureux'],
    ['Escarpin vernis', 'Sandale à brides'],
    ['Rouge carmin', 'Rose bonbon'],
    ['Maquillage', 'Mascara'],
    ['Crème fouettée', 'Sauce chocolat'],
    ['Sérénade', 'Déclaration enflammée'],
    ['Tenue de soirée', 'Petite robe noire'],
  ],
}
