import type { Level } from '../engine'

export interface WheelForfeit {
  /** Intitulé affiché dans la case de la roue (court). */
  label: string
  /** Gage complet, adressé au joueur (tutoiement). */
  text: string
}

/** Roue des gages — Soft : gages sans alcool, Épicé : soirée et gorgées, Hot : coquin. */
export const wheelForfeits: Record<Level, WheelForfeit[]> = {
  soft: [
    // Voix et accents
    { label: 'Accent', text: 'Parle avec un accent italien jusqu’à ton prochain tour.' },
    { label: 'Québécois', text: 'Parle avec un accent québécois pendant deux minutes.' },
    { label: 'Pirate', text: 'Parle comme un pirate jusqu’à la fin du prochain tour.' },
    { label: 'Robot', text: 'Parle comme un robot jusqu’à ton prochain tour.' },
    { label: 'Accent', text: 'Prends l’accent du Sud pour raconter ta journée en trente secondes.' },
    { label: 'Chuchote', text: 'Ne parle qu’en chuchotant jusqu’à ton prochain tour.' },
    { label: 'Voix aiguë', text: 'Parle avec une voix de dessin animé très aiguë jusqu’à ton prochain tour.' },
    { label: 'Voix grave', text: 'Parle avec une voix très grave jusqu’à ton prochain tour.' },
    { label: 'Ralenti', text: 'Parle et bouge au ralenti pendant une minute.' },
    { label: 'Rimes', text: 'Ne parle qu’en rimes jusqu’à ton prochain tour.' },
    { label: 'Interdit', text: 'Tu n’as pas le droit de dire « oui » ni « non » jusqu’à ton prochain tour.' },
    { label: 'Anglais', text: 'Ne parle qu’en anglais jusqu’à ton prochain tour.' },
    { label: 'Présentateur', text: 'Commente ce que fait chaque joueur comme un commentateur sportif pendant une minute.' },
    { label: 'Bébé', text: 'Parle comme un bébé pendant ta prochaine phrase, puis explique pourquoi tu pleures.' },
    { label: 'Sans je', text: 'Parle de toi sans jamais dire « je » jusqu’à ton prochain tour.' },
    // Chant
    { label: 'Refrain', text: 'Chante à tue-tête le refrain de ta chanson préférée.' },
    { label: 'Chanson', text: 'Chante ton prénom sur l’air de « Joyeux anniversaire ».' },
    { label: 'Opéra', text: 'Chante une comptine de ton enfance en mode opéra.' },
    { label: 'Chanson', text: 'Invente une chanson de dix secondes sur la personne à ta gauche.' },
    { label: 'Karaoké', text: 'Chante une chanson du groupe en changeant toutes les paroles pour parler de nourriture.' },
    { label: 'Rap', text: 'Fais un freestyle de vingt secondes sur le thème de la soirée.' },
    { label: 'Yodel', text: 'Fais un yodel du mieux que tu peux pendant dix secondes.' },
    { label: 'Chorale', text: 'Chante la dernière phrase prononcée par quelqu’un comme si c’était une chanson.' },
    { label: 'Publicité', text: 'Chante un jingle de publicité que tout le monde connaît.' },
    { label: 'Beatbox', text: 'Fais du beatbox pendant quinze secondes, même si tu ne sais pas.' },
    // Imitations
    { label: 'Animal', text: 'Imite un animal jusqu’à ce que le groupe devine lequel.' },
    { label: 'Météo', text: 'Présente la météo de demain comme un vrai présentateur télé.' },
    { label: 'Dessin animé', text: 'Imite un personnage de dessin animé jusqu’à ce qu’on le devine.' },
    { label: 'Prof', text: 'Joue le prof le plus sévère que tu aies connu pendant vingt secondes.' },
    { label: 'Cinéma', text: 'Imite une scène de film célèbre, le groupe doit trouver laquelle.' },
    { label: 'Chat', text: 'Fais le chat qui se réveille, avec ronronnements et étirements.' },
    { label: 'Dinosaure', text: 'Marche et rugis comme un dinosaure pendant dix secondes.' },
    { label: 'Hôtesse', text: 'Fais la démonstration des consignes de sécurité d’un avion, très sérieusement.' },
    { label: 'Cuisinier', text: 'Présente une recette imaginaire comme dans une émission de cuisine.' },
    { label: 'Voyante', text: 'Joue la voyante et prédis l’avenir de deux joueurs au choix.' },
    { label: 'Mannequin', text: 'Défile dans la pièce comme sur un podium de mode.' },
    { label: 'Super-héros', text: 'Prends la pose d’un super-héros et annonce ton super-pouvoir ridicule.' },
    { label: 'Pub', text: 'Fais la pub d’un objet qui traîne dans la pièce, comme un vendeur surexcité.' },
    // Danse
    { label: 'Danse', text: 'Danse sans musique pendant vingt secondes avec le plus grand sérieux.' },
    { label: 'Danse', text: 'Fais la danse de la pluie en y mettant tout ton cœur.' },
    { label: 'Sol brûlant', text: 'Danse comme si le sol était brûlant pendant vingt secondes.' },
    { label: 'Moonwalk', text: 'Tente un moonwalk dans la pièce, même sans talent.' },
    { label: 'Chorégraphie', text: 'Invente une mini-chorégraphie de dix secondes et fais-la apprendre à un joueur.' },
    { label: 'Danse', text: 'Fais la danse la plus célèbre des années 2000 que tu connaisses.' },
    { label: 'Robot', text: 'Danse comme un robot dont les piles sont presque vides.' },
    { label: 'Slow', text: 'Danse un slow imaginaire avec une chaise, en la regardant dans les yeux.' },
    { label: 'Tango', text: 'Danse un tango seul, en jouant les deux partenaires.' },
    { label: 'Ballet', text: 'Fais une pirouette gracieuse et salue comme une danseuse étoile.' },
    // Mime
    { label: 'Mime', text: 'Mime un film célèbre, sans un mot, jusqu’à ce qu’on le devine.' },
    { label: 'Mime', text: 'Mime ton métier ou ta passion, le groupe a trente secondes pour trouver.' },
    { label: 'Mime', text: 'Mime une activité du quotidien en la rendant la plus dramatique possible.' },
    { label: 'Statue', text: 'Reste immobile comme une statue jusqu’à ton prochain tour.' },
    { label: 'Ralenti', text: 'Mime un match de sport en slow motion, le groupe doit trouver le sport.' },
    { label: 'Chef', text: 'Mime la préparation d’un plat, le groupe doit deviner lequel.' },
    { label: 'Scène', text: 'Mime une scène de dispute entre deux personnages en jouant les deux rôles.' },
    // Compliments
    { label: 'Compliment', text: 'Fais un compliment sincère à chaque joueur, un par un.' },
    { label: 'Qualités', text: 'Cite trois vraies qualités de la personne à ta gauche.' },
    { label: 'Compliment', text: 'Complimente quelqu’un en le comparant à un animal flatteur.' },
    { label: 'Éloge', text: 'Fais l’éloge du joueur de ton choix comme à une remise de médaille.' },
    { label: 'Merci', text: 'Remercie un joueur pour quelque chose de précis qu’il a fait pour toi.' },
    { label: 'Surnom', text: 'Donne un surnom flatteur à chaque joueur, et justifie-le.' },
    { label: 'Fan', text: 'Dis ce que tu admires le plus chez la personne à ta droite.' },
    { label: 'Poème', text: 'Compose un petit poème de deux vers pour le joueur de ton choix.' },
    { label: 'Discours', text: 'Prononce un discours de remerciements comme si tu recevais un prix.' },
    // Sport léger
    { label: 'Pompes', text: 'Fais dix pompes, sur les genoux si tu préfères.' },
    { label: 'Squats', text: 'Fais quinze squats en comptant à voix haute.' },
    { label: 'Gainage', text: 'Tiens la planche vingt secondes pendant que le groupe compte.' },
    { label: 'Jumping', text: 'Fais vingt jumping jacks sans te tromper dans le compte.' },
    { label: 'Équilibre', text: 'Tiens sur un seul pied pendant trente secondes, les yeux ouverts.' },
    { label: 'Étirements', text: 'Fais cinq étirements de ton choix et explique le bienfait de chacun.' },
    { label: 'Chaise', text: 'Tiens la position de la chaise contre un mur pendant vingt secondes.' },
    { label: 'Corde', text: 'Mime du saut à la corde pendant vingt secondes sans t’arrêter.' },
    { label: 'Yoga', text: 'Prends une posture de yoga de ton choix et tiens-la en respirant calmement.' },
    { label: 'Sprint', text: 'Cours sur place à fond pendant dix secondes.' },
    { label: 'Abdos', text: 'Fais dix abdos en regardant un joueur dans les yeux.' },
    { label: 'Fentes', text: 'Fais dix fentes en chantant l’alphabet.' },
    // Téléphone
    { label: 'Écran', text: 'Montre ton fond d’écran au groupe et explique pourquoi tu l’as choisi.' },
    { label: 'Galerie', text: 'Montre la dernière photo de ta galerie et raconte son histoire.' },
    { label: 'Souvenir', text: 'Montre ta plus vieille photo conservée dans ton téléphone et raconte-la.' },
    { label: 'Selfie', text: 'Prends un selfie avec la grimace la plus ridicule possible.' },
    { label: 'Emojis', text: 'Montre tes trois emojis les plus utilisés et justifie ce choix.' },
    { label: 'Playlist', text: 'Fais écouter dix secondes de ta chanson la plus écoutée du moment.' },
    { label: 'Message', text: 'Envoie un message gentil à quelqu’un qui n’est pas présent ce soir.' },
    { label: 'Vocal', text: 'Enregistre un message vocal de remerciement pour l’hôte de la soirée.' },
    { label: 'Photo', text: 'Prends une photo de groupe où tout le monde fait la même pose.' },
    { label: 'Appli', text: 'Montre ton application la plus utilisée et explique pourquoi elle t’est utile.' },
    // Révélations légères
    { label: 'Manie', text: 'Révèle une petite manie dont tu n’as jamais parlé au groupe.' },
    { label: 'Vacances', text: 'Raconte ta pire anecdote de vacances.' },
    { label: 'Maladresse', text: 'Avoue ta plus grosse maladresse en public.' },
    { label: 'Fou rire', text: 'Raconte le plus gros fou rire de ta vie.' },
    { label: 'Talent', text: 'Dévoile un talent caché et fais-en la démonstration.' },
    { label: 'Enfance', text: 'Raconte ton plus vieux souvenir d’enfance.' },
    { label: 'Rêve', text: 'Raconte le rêve le plus étrange dont tu te souviennes.' },
    { label: 'Peur', text: 'Avoue une petite peur ridicule que tu as depuis toujours.' },
    { label: 'Cadeau', text: 'Décris le pire cadeau que tu aies jamais reçu.' },
    { label: 'Honte', text: 'Raconte un moment de honte qui te fait sourire aujourd’hui.' },
    { label: 'Film', text: 'Avoue ton film ou ta série préférée qui n’est pas très cool.' },
    { label: 'Métier', text: 'Dis le métier que tu rêvais de faire à dix ans.' },
    { label: 'Plat', text: 'Révèle ton plat préféré et celui que tu ne supportes pas.' },
    { label: 'Superpouvoir', text: 'Dis quel pouvoir tu choisirais et comment tu l’utiliserais au quotidien.' },
    { label: 'Premier job', text: 'Raconte ton tout premier petit boulot et ce que tu en as appris.' },
    { label: 'Coup cœur', text: 'Raconte ton dernier coup de cœur culturel et convaincs le groupe.' },
    // Jeux de langage
    { label: 'Alphabet', text: 'Récite l’alphabet à l’envers le plus vite possible.' },
    { label: 'Virelangue', text: 'Dis trois fois de suite « Les chaussettes de l’archiduchesse sont-elles sèches ».' },
    { label: 'Catégorie', text: 'Cite dix capitales en vingt secondes.' },
    { label: 'Mots', text: 'Cite huit fruits commençant par des lettres différentes en dix secondes.' },
    { label: 'Contraire', text: 'Réponds à chaque question par son contraire jusqu’à ton prochain tour.' },
    { label: 'Mot', text: 'Raconte une histoire en une minute sans utiliser la lettre « a » dans la première phrase.' },
    { label: 'Défi', text: 'Compte de dix à zéro en changeant de langue à chaque chiffre.' },
    { label: 'Énigme', text: 'Invente une devinette et fais-la deviner au groupe en moins d’une minute.' },
    { label: 'Histoire', text: 'Invente une histoire de trente secondes avec trois objets de la pièce.' },
    { label: 'Conte', text: 'Raconte « Le Petit Chaperon rouge » en une minute en version moderne.' },
    { label: 'Mots liés', text: 'Dis un mot, puis chaque joueur doit enchaîner avec un mot associé sans hésiter.' },
    { label: 'Lecture', text: 'Lis à voix haute l’étiquette d’un objet de la pièce comme un poème épique.' },
    { label: 'Pitch', text: 'Fais en trente secondes le pitch d’un film dont le héros est un grille-pain.' },
    { label: 'Journal', text: 'Annonce le journal télévisé de la soirée avec le plus grand sérieux.' },
    // Grimaces et fous rires
    { label: 'Grimace', text: 'Fais la grimace la plus laide possible et garde-la dix secondes.' },
    { label: 'Sans rire', text: 'Regarde un joueur dans les yeux vingt secondes sans rire.' },
    { label: 'Cri', text: 'Pousse le cri de Tarzan le plus convaincant possible.' },
    { label: 'Rire', text: 'Fais éclater de rire un joueur de ton choix en moins de trente secondes.' },
    { label: 'Bruitage', text: 'Fais les bruitages d’un orage pendant dix secondes avec ta bouche.' },
    { label: 'Duel', text: 'Fais un concours de regard sans cligner avec le joueur de ton choix.' },
    { label: 'Langue', text: 'Touche ton nez avec ta langue, ou essaie pendant dix secondes.' },
    { label: 'Sourire', text: 'Souris sans interruption jusqu’à ton prochain tour.' },
    { label: 'Fou rire', text: 'Fais un rire de sorcière ou de méchant de film pendant dix secondes.' },
    // Objets et défis
    { label: 'Livre', text: 'Marche dans la pièce avec un livre sur la tête, sans le faire tomber.' },
    { label: 'Défi', text: 'Fais tenir une cuillère en équilibre sur ton nez pendant dix secondes.' },
    { label: 'Dessin', text: 'Dessine le portrait d’un joueur en trente secondes, sans lever le crayon.' },
    { label: 'Origami', text: 'Plie une feuille en forme d’animal en une minute, le groupe devine lequel.' },
    { label: 'Tour', text: 'Construis une tour de six objets de la pièce qui tienne debout.' },
    { label: 'Jonglage', text: 'Tente de jongler avec trois objets mous pendant dix secondes.' },
    { label: 'Aveugle', text: 'Dessine une maison les yeux fermés et montre le résultat.' },
    { label: 'Pièce', text: 'Lance une pièce, et réussis à la rattraper trois fois de suite.' },
    { label: 'Sac', text: 'Choisis un objet dans la pièce et vends-le comme s’il valait des millions.' },
    { label: 'Cache', text: 'Cache un objet dans la pièce, les autres ont une minute pour le trouver.' },
    { label: 'Déguisement', text: 'Déguise-toi avec ce que tu trouves en trente secondes.' },
    { label: 'Chapeau', text: 'Fabrique un chapeau avec ce que tu trouves et porte-le jusqu’à la fin du tour.' },
    // Questions et sociabilité
    { label: 'Question', text: 'Pose à chaque joueur une question amusante dont tu n’as jamais eu la réponse.' },
    { label: 'Pari', text: 'Propose un pari amusant au joueur de ton choix, il doit l’accepter ou répondre à une question.' },
    { label: 'Interview', text: 'Interviewe le joueur de ton choix comme une célébrité en trois questions.' },
    { label: 'Top 3', text: 'Donne ton top trois des films de ta vie et défends-le.' },
    { label: 'Souhait', text: 'Fais un vœu pour chaque joueur de la pièce, à voix haute.' },
    { label: 'Avis', text: 'Donne un avis tranché sur un débat futile, comme l’ananas sur la pizza.' },
    { label: 'Duo', text: 'Choisis un joueur et inventez ensemble un salut secret en dix secondes.' },
    { label: 'Hymne', text: 'Invente un cri de ralliement pour le groupe et fais-le répéter à tous.' },
    { label: 'Prénom', text: 'Dis une qualité pour chaque lettre du prénom de la personne à ta gauche.' },
    { label: 'Prédiction', text: 'Prédis ce que fera chaque joueur dans dix ans, avec beaucoup de conviction.' },
    { label: 'Hymne', text: 'Chante l’hymne officiel d’un pays imaginaire que tu viens d’inventer.' },
    { label: 'Télé-achat', text: 'Vante un balai comme dans une émission de télé-achat, avec ferveur.' },
    { label: 'Girafe', text: 'Marche comme une girafe pendant dix secondes en étirant le cou.' },
    { label: 'Mot-clé', text: 'Lance un mot au hasard et fais-en une phrase publicitaire de dix secondes.' },
    // Bonus : Joker
    { label: 'Joker', text: 'Tu es dispensé de gage pour ce tour : savoure ta chance.' },
    { label: 'Joker', text: 'Joker ! Aucun gage pour toi, tu peux lever les bras en vainqueur.' },
    { label: 'Joker', text: 'Le gage est annulé : tu passes ton tour, mais tu dois saluer le groupe.' },
    // Bonus : Tu choisis
    { label: 'Tu choisis', text: 'Désigne le joueur de ton choix : c’est lui qui fait le prochain gage.' },
    { label: 'Tu choisis', text: 'Nomme un joueur qui devra relever le prochain gage à ta place.' },
    { label: 'Tu choisis', text: 'Pointe du doigt la personne qui fera le gage suivant, sans justification.' },
    // Bonus : Rejoue
    { label: 'Rejoue', text: 'Relance la roue tout de suite et assume ce que tu obtiens.' },
    { label: 'Rejoue', text: 'Seconde chance : tourne encore la roue et applique le résultat.' },
    { label: 'Rejoue', text: 'Reviens à la case départ en relançant la roue, sans râler.' },
    // Bonus : Tout le monde
    { label: 'Tout le monde', text: 'Tout le monde se lève et danse librement pendant dix secondes.' },
    { label: 'Tout le monde', text: 'Tout le monde fait sa meilleure grimace en même temps, sur ton signal.' },
    { label: 'Tout le monde', text: 'Tout le monde pousse un grand cri de victoire à trois.' },
  ],
  spicy: [
    // Drague légère
    { label: 'Drague', text: 'Lance ta meilleure phrase de drague au joueur de ton choix, sans rire.' },
    { label: 'Drague', text: 'Drague une chaise comme si c’était la personne de ta vie.' },
    { label: 'Regard', text: 'Fixe un joueur dans les yeux dix secondes en souriant, sans rien dire.' },
    { label: 'Séduction', text: 'Fais ton plus beau clin d’œil à un joueur, avec l’air le plus charmeur possible.' },
    { label: 'Compliment', text: 'Complimente le style du joueur de ton choix en étant le plus charmeur possible.' },
    { label: 'Premier rdv', text: 'Joue la première phrase que tu dirais à un premier rendez-vous raté.' },
    { label: 'Rencontre', text: 'Rejoue ta pire tentative de drague devant le groupe.' },
    { label: 'Match', text: 'Écris à voix haute la bio de profil de rencontre du joueur à ta droite.' },
    { label: 'Charme', text: 'Marche vers un joueur comme dans un film romantique et dis-lui une réplique culte.' },
    { label: 'Déclaration', text: 'Fais une déclaration d’amour dramatique à ton plat préféré.' },
    { label: 'Séducteur', text: 'Fais un défilé de séducteur ou de séductrice, avec la musique dans la tête.' },
    { label: 'Roméo', text: 'Récite une tirade romantique improvisée au joueur de ton choix, avec son accord.' },
    { label: 'Compliment', text: 'Dis ce qui te plaît le plus chez la personne à ta gauche, sans passer par l’humour.' },
    { label: 'Rendez-vous', text: 'Propose un rendez-vous idéal au joueur de ton choix et détaille le programme.' },
    { label: 'Swipe', text: 'Swipe à droite ou à gauche sur chaque joueur, à voix haute, et justifie-toi.' },
    { label: 'Chanson', text: 'Chante une chanson d’amour au joueur de ton choix, avec son accord.' },
    { label: 'Regard', text: 'Soutiens le regard d’un joueur pendant quinze secondes, le premier qui rit perd.' },
    { label: 'Poésie', text: 'Écris et lis un petit poème d’amour de trois lignes pour un joueur de ton choix.' },
    { label: 'Séducteur', text: 'Séduis le groupe en trente secondes avec une seule qualité que tu as.' },
    { label: 'Surprise', text: 'Fais un compliment inattendu à chaque joueur, qui doit être précis.' },
    // Gêne et défis
    { label: 'Gêne', text: 'Raconte ton moment le plus gênant en soirée.' },
    { label: 'Honte', text: 'Raconte la pire honte de ton adolescence en détail.' },
    { label: 'Première', text: 'Raconte ton premier vrai rendez-vous, sans rien enjoliver.' },
    { label: 'Ex', text: 'Dis une chose que tu as aimée chez un de tes anciens, sans citer son nom.' },
    { label: 'Pire date', text: 'Raconte ton pire rendez-vous galant, avec les détails.' },
    { label: 'Message', text: 'Lis à voix haute ton dernier message envoyé, si tu l’assumes.' },
    { label: 'Faux pas', text: 'Raconte la pire maladresse que tu aies faite devant quelqu’un qui te plaisait.' },
    { label: 'Mensonge', text: 'Avoue un petit mensonge que tu as raconté à tes proches.' },
    { label: 'Mauvais plan', text: 'Raconte ta plus mauvaise idée de soirée, avec le résultat.' },
    { label: 'Pire look', text: 'Décris le pire look que tu aies porté et pourquoi tu l’as aimé.' },
    { label: 'Pire cadeau', text: 'Raconte le cadeau le plus gênant que tu aies offert ou reçu.' },
    { label: 'Réseaux', text: 'Montre ta plus vieille photo de profil sur un réseau social.' },
    { label: 'Journal', text: 'Lis à voix haute une vieille note ou un vieux message de ton adolescence, s’il en reste.' },
    { label: 'Surnom', text: 'Avoue le surnom le plus ridicule qu’on t’ait donné.' },
    { label: 'Stalk', text: 'Avoue la dernière fois que tu as regardé le profil d’un ex ou d’un crush.' },
    { label: 'Tentation', text: 'Dis la plus grosse folie que tu as faite par amour.' },
    { label: 'Balance', text: 'Dis ce que tu penses vraiment de la tenue du joueur de ton choix, avec bienveillance.' },
    { label: 'Flop', text: 'Raconte la fois où tu as le plus mal géré un râteau.' },
    { label: 'Mystère', text: 'Révèle une chose de toi que presque personne ici ne sait.' },
    { label: 'Aveu', text: 'Fais un aveu que tu gardais pour toi, tant qu’il ne blesse personne.' },
    // Révélations entre amis
    { label: 'Qui', text: 'Désigne le joueur qui serait le plus doué pour la drague, et explique-toi.' },
    { label: 'Casting', text: 'Choisis qui jouerait le séducteur d’un film dans le groupe, et justifie-toi.' },
    { label: 'Pronostic', text: 'Dis qui sera en couple le premier dans le groupe, avec ta raison.' },
    { label: 'Mariage', text: 'Désigne les deux joueurs qui feraient le meilleur couple, et explique pourquoi.' },
    { label: 'Chouchou', text: 'Dis lequel des joueurs tu confierais tout, et pourquoi.' },
    { label: 'Pire colocs', text: 'Choisis avec qui tu ne partirais jamais en vacances, avec une raison drôle.' },
    { label: 'Premier', text: 'Dis ton premier ressenti sur la personne à ta gauche la première fois que tu l’as vue.' },
    { label: 'Double vie', text: 'Imagine la double vie secrète d’un joueur, avec les détails.' },
    { label: 'Étoile', text: 'Désigne le joueur le plus susceptible de devenir célèbre, et pourquoi.' },
    { label: 'Menteur', text: 'Désigne qui ment le mieux dans le groupe, et raconte pourquoi.' },
    { label: 'Fête', text: 'Dis qui serait le pire invité à un mariage, avec tendresse.' },
    { label: 'Ange', text: 'Dis qui est la personne la plus gentille du groupe et ce qu’elle t’a apporté.' },
    // Gorgées
    { label: 'Gorgée', text: 'Bois une gorgée, puis désigne quelqu’un qui en boit une aussi.' },
    { label: 'Deux gorgées', text: 'Bois deux gorgées en regardant un joueur dans les yeux.' },
    { label: 'Santé', text: 'Porte un toast à un joueur de ton choix et bois une gorgée.' },
    { label: 'Trois gorgées', text: 'Raconte une anecdote gênante ou bois trois gorgées.' },
    { label: 'Vérité', text: 'Réponds à une question perso du groupe, ou bois deux gorgées.' },
    { label: 'Toast', text: 'Fais un toast humoristique à l’amitié, puis bois une petite gorgée.' },
    { label: 'Gage ou boire', text: 'Chante quelques secondes d’une chanson, ou bois deux gorgées.' },
    { label: 'Gorgée', text: 'Bois une gorgée à chaque fois que quelqu’un rit pendant les trente prochaines secondes.' },
    { label: 'Jamais', text: 'Dis une chose que tu n’as jamais faite, ceux qui l’ont faite boivent une gorgée.' },
    { label: 'Qui ici', text: 'Pose une question « Qui ici… », ceux concernés boivent une gorgée.' },
    { label: 'Dernier', text: 'Bois une gorgée si tu as déjà envoyé un message à la mauvaise personne.' },
    { label: 'Duo', text: 'Choisis un joueur : vous buvez chacun une gorgée et trinquez en vous regardant.' },
    { label: 'Pari', text: 'Parie sur le résultat d’un pile ou face : si tu perds, bois deux gorgées.' },
    { label: 'Santé', text: 'Invente un toast original de dix secondes, puis bois une gorgée.' },
    { label: 'Contre', text: 'Défie un joueur au pierre-feuille-ciseaux : le perdant boit deux gorgées.' },
    { label: 'Gorgée', text: 'Donne deux gorgées à répartir comme tu veux entre les autres joueurs.' },
    { label: 'Confession', text: 'Avoue une chose dont tu es fier ou fière, puis bois une gorgée pour fêter ça.' },
    { label: 'Roi', text: 'Deviens roi ou reine du groupe : donne une règle à respecter, sinon on boit une gorgée.' },
    { label: 'Interdit', text: 'Dis « santé » avant chaque phrase jusqu’à ton prochain tour, ou bois une gorgée à chaque oubli.' },
    { label: 'Gorgée', text: 'Bois une gorgée en imitant une publicité pour une boisson imaginaire.' },
    { label: 'Trinque', text: 'Trinque avec chaque joueur en lui disant un mot gentil, puis bois une gorgée.' },
    { label: 'Gorgée', text: 'Bois une gorgée si tu as déjà dit « je t’aime » trop vite à quelqu’un.' },
    { label: 'Tournée', text: 'Fais boire une gorgée à tous ceux qui portent la même couleur que toi.' },
    { label: 'Gorgée', text: 'Bois une gorgée si tu as déjà fait semblant de rire à une blague.' },
    { label: 'Sobre', text: 'Bois une gorgée d’eau et lance un défi de ton choix à un joueur.' },
    { label: 'Mini-gorgée', text: 'Bois une gorgée si tu as déjà fait une soirée que tu regrettes.' },
    { label: 'Pari', text: 'Si tu te trompes à la devinette suivante, bois trois gorgées : le groupe choisit la question.' },
    // Imitations de soirée
    { label: 'Karaoké', text: 'Chante un tube de soirée en faisant semblant d’avoir un micro, avec chorégraphie.' },
    { label: 'DJ', text: 'Joue le DJ avec ta bouche pendant vingt secondes et chauffe la salle.' },
    { label: 'Piste', text: 'Fais ta danse de soirée la plus gênante pendant quinze secondes.' },
    { label: 'Playlist', text: 'Choisis une chanson pour l’ambiance et explique ce qu’elle dit de toi.' },
    { label: 'Videur', text: 'Joue le videur de boîte de nuit et choisis qui entre dans la pièce, avec sérieux.' },
    { label: 'Serveur', text: 'Joue le serveur d’un grand restaurant et décris le menu de la soirée.' },
    { label: 'Animateur', text: 'Fais une présentation de la soirée comme un animateur de télé survolté.' },
    { label: 'Toast', text: 'Prononce un discours de mariage improvisé pour deux joueurs au choix.' },
    { label: 'Concours', text: 'Organise un mini-concours de grimaces et désigne le gagnant, sans tricher.' },
    { label: 'Star', text: 'Fais un autographe fictif à chaque joueur avec un message personnalisé.' },
    { label: 'Bal', text: 'Invite un joueur à danser quelques secondes, avec son accord.' },
    { label: 'Chorale', text: 'Lance un refrain que tout le groupe doit chanter avec toi.' },
    { label: 'Défilé', text: 'Défile avec la tenue de la soirée comme sur un tapis rouge.' },
    { label: 'Pas de danse', text: 'Apprends à un joueur un pas de danse en vingt secondes.' },
    { label: 'Pose', text: 'Pose pour une photo de couverture de magazine, avec une moue travaillée.' },
    { label: 'Duel', text: 'Lance un duel de danse avec un joueur au choix, le groupe vote.' },
    { label: 'Mime', text: 'Mime la pire soirée de ta vie, le groupe doit comprendre ce qui s’est passé.' },
    { label: 'Fatigue', text: 'Imite quelqu’un de très fatigué qui essaie de rester poli, pendant vingt secondes.' },
    { label: 'Orateur', text: 'Fais un discours enflammé pour que le groupe aille danser, sans rien oublier.' },
    { label: 'Film', text: 'Rejoue une scène d’amour de film culte avec un joueur consentant.' },
    // Téléphone et réseaux
    { label: 'Contact', text: 'Montre le contact le plus marrant de ton répertoire et explique l’histoire.' },
    { label: 'Dernier', text: 'Dis le dernier prénom qui t’a écrit et raconte votre lien.' },
    { label: 'Story', text: 'Poste une story du groupe avec la phrase que le groupe te souffle.' },
    { label: 'Recherche', text: 'Dis la dernière chose que tu as cherchée sur internet.' },
    { label: 'Galerie', text: 'Montre la photo de toi dont tu as le moins honte et celle dont tu as le plus honte.' },
    { label: 'Appel', text: 'Appelle un proche qui en a envie et chante-lui « Joyeux anniversaire » en avance.' },
    { label: 'Vocal', text: 'Envoie un vocal à un ami en lui disant à quel point il compte pour toi.' },
    { label: 'Réseau', text: 'Montre ton historique de recherche de la semaine, ou raconte un secret à la place.' },
    { label: 'Photo', text: 'Prends une photo de toi la plus charmeuse possible et montre-la au groupe.' },
    { label: 'Clavier', text: 'Dis à voix haute le dernier mot que tu as tapé sur ton téléphone.' },
    { label: 'Musique', text: 'Montre tes trois chansons les plus écoutées, même celles que tu caches.' },
    { label: 'Appli', text: 'Montre l’appli que tu caches dans un dossier et dis pourquoi tu l’as.' },
    // Compliments directs
    { label: 'Franc', text: 'Dis une qualité et un petit défaut du joueur à ta gauche, avec bienveillance.' },
    { label: 'Premier', text: 'Dis ce que tu as pensé de chaque joueur en le rencontrant.' },
    { label: 'Style', text: 'Donne une note de style à chaque joueur, sur dix, avec un compliment.' },
    { label: 'Voix', text: 'Dis à quel personnage de film chaque joueur te fait penser.' },
    { label: 'Duo', text: 'Associe deux joueurs en duo comique ou romantique dans un film et justifie.' },
    { label: 'Rêve', text: 'Raconte un rêve étrange où figurait un joueur de la soirée, avec humour.' },
    { label: 'Signe', text: 'Devine le signe astrologique de trois joueurs, avec ton raisonnement.' },
    { label: 'Défaut', text: 'Avoue ton plus gros défaut en soirée, sans te défendre.' },
    { label: 'Point fort', text: 'Dis pourquoi tu serais un ou une excellente partenaire de voyage.' },
    { label: 'Dix ans', text: 'Dis ce que tu espères que le groupe dira de toi dans dix ans.' },
    // Défis rapides
    { label: 'Vite', text: 'Cite sept prénoms d’acteurs en dix secondes, ou bois une gorgée.' },
    { label: 'Pose', text: 'Prends dix poses de mannequin en trente secondes.' },
    { label: 'Rire', text: 'Fais rire un joueur en moins de vingt secondes sans le toucher.' },
    { label: 'Question', text: 'Réponds à une question rapide du groupe sans hésiter plus de deux secondes.' },
    { label: 'Défi', text: 'Tiens vingt secondes sans cligner des yeux, le groupe contrôle.' },
    { label: 'Mime', text: 'Mime une émotion forte, le groupe doit la deviner en dix secondes.' },
    { label: 'Chrono', text: 'Fais dix squats en trente secondes en récitant une tirade romantique.' },
    { label: 'Trio', text: 'Cite trois choses que tu aimes chez toi, à voix haute et sans modestie.' },
    { label: 'Pirouette', text: 'Fais trois tours sur toi-même puis marche droit vers une chaise.' },
    { label: 'Anecdote', text: 'Raconte une anecdote de soirée en moins de trente secondes.' },
    { label: 'Fierté', text: 'Raconte ce dont tu es le plus fier en ce moment, sans fausse modestie.' },
    { label: 'Question', text: 'Pose une question audacieuse au joueur de ton choix, il peut refuser.' },
    { label: 'Confidence', text: 'Dis ce que tu aimerais changer dans ta façon de draguer.' },
    { label: 'Selfie', text: 'Prends un selfie en pose de séducteur avec le joueur de ton choix, avec son accord.' },
    { label: 'Défi', text: 'Fais rougir un joueur avec un compliment, sans passer par l’humour.' },
    { label: 'Bio', text: 'Rédige à voix haute ta bio de réseau social comme si elle était ultra prétentieuse.' },
    { label: 'Talent', text: 'Montre ton talent de séduction le plus inattendu en dix secondes.' },
    { label: 'Pile', text: 'Réponds franchement à la question « Pile ou face ? » que le groupe te pose sur ta vie amoureuse.' },
    { label: 'Sérénade', text: 'Fais une sérénade improvisée à un joueur, avec son accord, en un seul couplet.' },
    { label: 'Premier', text: 'Dis ce que tu remarques en premier chez quelqu’un qui te plaît.' },
    { label: 'Pire phrase', text: 'Invente la pire phrase d’accroche du monde et dis-la avec aplomb.' },
    { label: 'Courrier', text: 'Dicte à voix haute une lettre d’amour pour ton plat préféré.' },
    { label: 'Prétexte', text: 'Donne le meilleur prétexte pour aborder quelqu’un qui te plaît en soirée.' },
    { label: 'Cours', text: 'Donne un cours de drague de trente secondes au groupe, avec exemples.' },
    { label: 'Ex', text: 'Raconte pourquoi une de tes histoires s’est terminée, sans critiquer la personne.' },
    { label: 'Coup de foudre', text: 'Raconte ton plus beau coup de foudre, ou invente-le, le groupe devra deviner.' },
    { label: 'Réplique', text: 'Joue la réplique la plus romantique d’un film culte avec la voix qui va avec.' },
    { label: 'Rencontre', text: 'Joue la rencontre la plus mignonne que tu imagines avec le joueur à ta droite.' },
    { label: 'Quiz', text: 'Réponds à une question perso du groupe, le joueur à ta gauche la choisit.' },
    { label: 'Ambiance', text: 'Annonce l’ambiance de la soirée comme dans une boîte de nuit chic.' },
    { label: 'Affiche', text: 'Pose en couple pour une affiche de film romantique avec un joueur, avec son accord.' },
    { label: 'Tendre', text: 'Fais un compliment tendre à la personne qui t’a offert à boire pour la dernière fois.' },
    // Bonus : Joker
    { label: 'Joker', text: 'Tu es sauvé : aucun gage ce tour, mais tu choisis qui doit boire une gorgée.' },
    { label: 'Joker', text: 'Joker ! Passe ton tour avec le sourire, le gage n’est pas pour toi.' },
    { label: 'Joker', text: 'La chance sourit : tu es dispensé de gage jusqu’à ton prochain passage.' },
    // Bonus : Tu choisis
    { label: 'Tu choisis', text: 'Désigne qui doit relever le prochain gage à ta place, et explique ton choix.' },
    { label: 'Tu choisis', text: 'Tu nommes un joueur qui tourne la roue et subit le gage suivant.' },
    { label: 'Tu choisis', text: 'Choisis une victime : elle fera le prochain gage, avec ton soutien.' },
    // Bonus : Rejoue
    { label: 'Rejoue', text: 'Relance la roue immédiatement, le résultat s’applique sans discussion.' },
    { label: 'Rejoue', text: 'Nouvelle chance : relance la roue et accepte le verdict, bon ou mauvais.' },
    { label: 'Rejoue', text: 'Reprends la roue et tourne encore, sans commentaire.' },
    // Bonus : Tout le monde
    { label: 'Tout le monde', text: 'Tout le monde trinque et se lance un compliment à voix haute.' },
    { label: 'Tout le monde', text: 'Tout le monde boit une gorgée et lève son verre à la santé de la soirée.' },
    { label: 'Tout le monde', text: 'Tout le monde doit imiter ton prochain geste pendant dix secondes.' },
  ],
  hot: [
    // Chuchotements
    { label: 'Chuchote', text: 'Chuchote un compliment coquin à l’oreille du joueur de ton choix, avec son accord.' },
    { label: 'Murmure', text: 'Murmure ce qui te plaît le plus chez la personne à ta gauche, très près de son oreille.' },
    { label: 'Secret', text: 'Chuchote un secret à un joueur, qui décide s’il le répète au groupe.' },
    { label: 'Voix douce', text: 'Lis une phrase du quotidien d’une voix sensuelle, comme un présentateur de radio de nuit.' },
    { label: 'Radio', text: 'Fais une annonce de radio de nuit d’une voix grave et envoûtante.' },
    { label: 'Souffle', text: 'Souffle doucement un « bonne nuit » à l’oreille d’un joueur, avec son accord.' },
    { label: 'Poème', text: 'Dis à voix basse un poème d’amour improvisé à la personne de ton choix.' },
    { label: 'Confidence', text: 'Chuchote ce que tu trouves le plus séduisant chez quelqu’un du groupe.' },
    { label: 'Déclaration', text: 'Dis « tu me plais » d’une voix langoureuse à un joueur, avec son accord.' },
    { label: 'Prénom', text: 'Prononce le prénom d’un joueur de la façon la plus sensuelle possible.' },
    { label: 'Séduction', text: 'Dis ta phrase de séduction préférée à l’oreille de la personne à ta droite.' },
    { label: 'ASMR', text: 'Fais de l’ASMR pendant dix secondes, en chuchotant un compliment à un joueur consentant.' },
    { label: 'Mots doux', text: 'Murmure trois mots doux au joueur de ton choix, avec son accord.' },
    { label: 'Secret doux', text: 'Raconte à voix basse ton plus beau souvenir romantique à une seule personne.' },
    // Bisous et gestes tendres (avec accord)
    { label: 'Bisou', text: 'Fais un bisou sur la joue du joueur de ton choix, avec son accord.' },
    { label: 'Main', text: 'Fais un baisemain à la personne de ton choix, avec son accord.' },
    { label: 'Bisou', text: 'Fais un bisou sur le front de la personne à ta gauche, avec son accord.' },
    { label: 'Cou', text: 'Fais un petit bisou dans le cou d’un joueur, uniquement avec son accord.' },
    { label: 'Joue', text: 'Pose délicatement ta joue contre celle d’un joueur et reste ainsi trois secondes, avec son accord.' },
    { label: 'Câlin', text: 'Fais un long câlin au joueur de ton choix pendant dix secondes, avec son accord.' },
    { label: 'Massage', text: 'Masse les épaules d’un joueur pendant vingt secondes, avec son accord.' },
    { label: 'Mains', text: 'Tiens la main d’un joueur de ton choix dix secondes en le regardant, avec son accord.' },
    { label: 'Nuque', text: 'Masse doucement la nuque d’un joueur pendant dix secondes, avec son accord.' },
    { label: 'Caresse', text: 'Caresse doucement la main d’un joueur du bout des doigts, avec son accord.' },
    { label: 'Bise', text: 'Fais la bise la plus lente de ta vie à un joueur, avec son accord.' },
    { label: 'Front', text: 'Pose ton front contre celui d’un joueur et respirez ensemble, avec son accord.' },
    { label: 'Dos', text: 'Dessine un cœur dans le dos d’un joueur avec ton doigt, avec son accord.' },
    { label: 'Étreinte', text: 'Serre un joueur dans tes bras en lui disant ce qui te plaît chez lui, avec son accord.' },
    { label: 'Baiser', text: 'Fais un baiser soufflé au joueur de ton choix, le plus théâtral possible.' },
    { label: 'Doigts', text: 'Entrelace tes doigts avec ceux d’un joueur pendant dix secondes, avec son accord.' },
    { label: 'Poignet', text: 'Fais un baiser sur le poignet d’un joueur consentant, très doucement.' },
    { label: 'Bisous', text: 'Déposez chacun un petit bisou sur la joue de l’autre, avec l’accord de chacun.' },
    { label: 'Tendresse', text: 'Fais un câlin à la personne qui t’a le plus fait rire ce soir, avec son accord.' },
    { label: 'Cheveux', text: 'Passe doucement la main dans les cheveux d’un joueur, avec son accord.' },
    // Danses lascives et ambiance
    { label: 'Danse', text: 'Danse de façon très lascive pendant quinze secondes devant tout le monde.' },
    { label: 'Slow', text: 'Danse un slow collé-serré avec le joueur de ton choix, avec son accord.' },
    { label: 'Tango', text: 'Danse un tango avec un joueur consentant, regard intense obligatoire.' },
    { label: 'Déhanché', text: 'Fais ton plus beau déhanché pendant vingt secondes.' },
    { label: 'Bachata', text: 'Danse quelques secondes une bachata avec un joueur, avec son accord.' },
    { label: 'Salsa', text: 'Fais un pas de salsa sensuel et invite un joueur à te suivre, avec son accord.' },
    { label: 'Lent', text: 'Danse au ralenti sur une musique imaginaire, avec le plus d’assurance possible.' },
    { label: 'Chaise', text: 'Danse autour d’une chaise comme dans un clip, sans rien retirer.' },
    { label: 'Clip', text: 'Joue la star d’un clip sensuel pendant vingt secondes, tout habillé.' },
    { label: 'Roulis', text: 'Fais des ondulations d’épaules et de hanches pendant quinze secondes.' },
    { label: 'Valse', text: 'Fais une valse romantique avec un joueur consentant, tête droite et regard fixe.' },
    { label: 'Pose', text: 'Prends la pose la plus sexy possible, tout habillé, et garde-la dix secondes.' },
    { label: 'Défilé', text: 'Défile comme sur un podium de mode, tout habillé et en riant.' },
    { label: 'Ambiance', text: 'Choisis une chanson sensuelle et danse dessus pendant vingt secondes.' },
    { label: 'Face à face', text: 'Danse devant un joueur consentant comme dans un film, sans contact et tout habillé.' },
    { label: 'Charme', text: 'Marche lentement vers le joueur de ton choix en le fixant dans les yeux, avec le sourire.' },
    { label: 'Duo danse', text: 'Fais danser un joueur consentant au creux de ton bras sur dix secondes de slow.' },
    { label: 'Années 80', text: 'Danse sur une chanson d’amour comme si tu étais dans un clip des années 80.' },
    { label: 'Hanches', text: 'Fais un mouvement de hanches de star de la pop à quelqu’un, avec le sourire.' },
    { label: 'Lumière', text: 'Danse dix secondes dans la pénombre en laissant ton ombre faire le spectacle.' },
    // Retirer un accessoire ou un vêtement non intime
    { label: 'Accessoire', text: 'Retire lentement un accessoire de ton choix et pose-le devant le joueur qui te plaît le plus.' },
    { label: 'Chaussette', text: 'Retire une chaussette avec le plus de sensualité possible.' },
    { label: 'Veste', text: 'Retire ta veste ou ton pull de façon très théâtrale, avec un regard de séducteur.' },
    { label: 'Montre', text: 'Retire ta montre ou ton bracelet avec une lenteur calculée, en regardant quelqu’un.' },
    { label: 'Bijou', text: 'Retire un bijou comme si tu dévoilais un grand secret, puis offre-le du regard à quelqu’un.' },
    { label: 'Chaussures', text: 'Retire tes chaussures avec un regard charmeur et pose-les à côté d’un joueur.' },
    { label: 'Écharpe', text: 'Retire ton écharpe ou ta ceinture de façon théâtrale et lance-la sur une chaise.' },
    { label: 'Lunettes', text: 'Retire tes lunettes ou ta casquette avec un regard de film, puis secoue les cheveux.' },
    { label: 'Manches', text: 'Retrousse tes manches lentement en fixant un joueur dans les yeux.' },
    { label: 'Chemise', text: 'Déboutonne un seul bouton de ta chemise ou ouvre ton gilet, le plus lentement possible.' },
    { label: 'Mocassin', text: 'Retire une chaussure et fais-la tourner autour de ton doigt, comme dans un film.' },
    { label: 'Foulard', text: 'Prends un foulard ou un tissu, et fais-le glisser lentement sur ton épaule.' },
    { label: 'Pull', text: 'Retire ton pull ou ta veste en une seule fois, avec le plus de panache possible.' },
    { label: 'Cravate', text: 'Dénoue ta cravate ou ton accessoire de cou le plus lentement possible.' },
    { label: 'Gilet', text: 'Retire un gilet, une veste ou un manteau, et donne-le à un joueur consentant.' },
    { label: 'Prête', text: 'Prête un vêtement non intime à un joueur et aide-le à l’enfiler, avec son accord.' },
    { label: 'Échange', text: 'Échange un accessoire avec le joueur de ton choix pour le reste du tour, avec son accord.' },
    // Séduction et regards
    { label: 'Regard', text: 'Fixe le joueur de ton choix pendant quinze secondes sans rire, avec un sourire charmeur.' },
    { label: 'Séduis', text: 'Séduis le joueur de ton choix en vingt secondes, sans le toucher.' },
    { label: 'Clin d’œil', text: 'Fais un clin d’œil appuyé à trois joueurs différents, de façon charmeuse.' },
    { label: 'Mordille', text: 'Mordille ta lèvre en fixant un joueur, avec le plus de malice possible.' },
    { label: 'Lèvres', text: 'Envoie un baiser du bout des doigts à celui ou celle qui te plaît le plus.' },
    { label: 'Duel', text: 'Fais un duel de regards avec un joueur : le premier qui rit ou détourne les yeux perd.' },
    { label: 'Phrase', text: 'Dis ta pire phrase de drague avec la voix la plus sensuelle possible.' },
    { label: 'Aimant', text: 'Fais en sorte de rapprocher un joueur de toi avec un seul regard, sans parler.' },
    { label: 'Sourire', text: 'Souris au joueur de ton choix avec ton sourire le plus ravageur pendant dix secondes.' },
    { label: 'Bouche', text: 'Fais la moue la plus charmeuse que tu puisses faire, et tiens-la cinq secondes.' },
    { label: 'Tentation', text: 'Dis à un joueur en le regardant ce que tu aimerais lui offrir ce soir, sans malaise.' },
    { label: 'Intrigue', text: 'Dis une phrase mystérieuse à un joueur, avec la voix d’un séducteur de film.' },
    { label: 'Entrée', text: 'Fais une entrée remarquée dans la pièce comme un héros de film romantique.' },
    { label: 'Pause', text: 'Fais une pause très théâtrale avant ta prochaine phrase, avec un sourire en coin.' },
    { label: 'Odeur', text: 'Raconte quel parfum ou quelle odeur te fait craquer, sans plus de détails.' },
    { label: 'Fixette', text: 'Regarde un joueur dans les yeux le temps de dire un compliment lent et appuyé.' },
    // Aveux et questions coquines (soft)
    { label: 'Aveu', text: 'Avoue le moment le plus romantique de ta vie.' },
    { label: 'Baiser', text: 'Raconte ton plus beau premier baiser, ou ton pire, avec humour.' },
    { label: 'Crush', text: 'Raconte ton plus gros crush et pourquoi il t’a marqué.' },
    { label: 'Fantasme', text: 'Décris ton rendez-vous romantique de rêve dans les moindres détails.' },
    { label: 'Atout', text: 'Dis ce que tu penses être ton plus gros atout de séduction.' },
    { label: 'Craque', text: 'Dis ce qui te fait craquer chez quelqu’un, à voix haute et sans filtre.' },
    { label: 'Ambiance', text: 'Décris la soirée idéale pour une première fois avec quelqu’un, version romantique et pudique.' },
    { label: 'Détail', text: 'Dis quelle partie du visage tu remarques en premier chez quelqu’un.' },
    { label: 'Premier pas', text: 'Dis si tu fais le premier pas ou si tu attends, et raconte un exemple.' },
    { label: 'Râteau', text: 'Raconte le plus gros râteau que tu aies pris, avec les détails gênants.' },
    { label: 'Regret', text: 'Avoue une occasion romantique que tu as ratée par timidité.' },
    { label: 'Parfum', text: 'Décris le parfum ou l’odeur qui te rend fou ou folle, sans plus de détails.' },
    { label: 'Tentation', text: 'Dis ce que tu ferais lors d’un week-end romantique parfait.' },
    { label: 'Preuve', text: 'Dis comment tu montres à quelqu’un qu’il te plaît quand tu es sûr de toi.' },
    { label: 'Tenue', text: 'Avoue la tenue dans laquelle tu te sens le plus séduisant ou séduisante.' },
    { label: 'Pire', text: 'Raconte l’idée la plus ridicule qu’on t’ait donnée pour séduire quelqu’un.' },
    { label: 'Rêve', text: 'Décris ton premier rêve où tu étais amoureux ou amoureuse d’un inconnu.' },
    { label: 'Charme', text: 'Dis ce que le joueur à ta gauche possède de plus charmant, sans humour.' },
    { label: 'Jalousie', text: 'Raconte la dernière fois où tu as été jaloux ou jalouse, et pourquoi.' },
    { label: 'Jeu', text: 'Dis à quel jeu de séduction tu aimes jouer en soirée.' },
    // Gorgées
    { label: 'Gorgée', text: 'Bois une gorgée, puis lance un regard de braise au joueur de ton choix.' },
    { label: 'Deux gorgées', text: 'Raconte un moment coquin mais pudique, ou bois deux gorgées.' },
    { label: 'Trois gorgées', text: 'Fais un compliment très direct à un joueur, ou bois trois gorgées.' },
    { label: 'Toast', text: 'Porte un toast sensuel à la soirée et bois une gorgée.' },
    { label: 'Dernier bisou', text: 'Dis quand tu as embrassé quelqu’un pour la dernière fois, ou bois deux gorgées.' },
    { label: 'Jamais', text: 'Dis une chose coquine que tu n’as jamais faite, ceux qui l’ont faite boivent une gorgée.' },
    { label: 'Duo', text: 'Trinque avec un joueur en croisant les bras, avec son accord, et buvez une gorgée chacun.' },
    { label: 'Pari', text: 'Si tu rates ton prochain clin d’œil séducteur, bois deux gorgées.' },
    { label: 'Santé', text: 'Trinque avec chaque joueur en lui disant un compliment doux, puis bois une gorgée.' },
    { label: 'Verdict', text: 'Dis qui est le plus séduisant du groupe, ou bois trois gorgées.' },
    { label: 'Gorgée', text: 'Bois une gorgée si tu as déjà été amoureux ou amoureuse d’un ami proche.' },
    { label: 'Gorgée', text: 'Bois une gorgée si tu as déjà envoyé un message audacieux à la mauvaise personne.' },
    { label: 'Répartis', text: 'Répartis trois gorgées entre les joueurs qui t’ont déjà fait craquer.' },
    { label: 'Secret', text: 'Chuchote un secret à un joueur, ou bois deux gorgées pour le garder.' },
    { label: 'Regard', text: 'Bois une gorgée sans quitter des yeux le joueur de ton choix.' },
    { label: 'Tournée', text: 'Tous ceux qui ont déjà fait un câlin ce soir boivent une gorgée, toi compris.' },
    { label: 'Gorgée', text: 'Bois une gorgée si tu as déjà dansé collé-serré avec un inconnu.' },
    { label: 'Pari', text: 'Perds au pierre-feuille-ciseaux contre un joueur et bois deux gorgées en le félicitant.' },
    { label: 'Gorgée', text: 'Bois une gorgée si tu as déjà fait semblant de ne pas voir un crush.' },
    { label: 'Désir', text: 'Dis ce que tu désires le plus cette année, ou bois deux gorgées.' },
    // Duo et défis à deux
    { label: 'Duo', text: 'Tenez-vous la main avec un joueur pendant les deux prochains tours, avec son accord.' },
    { label: 'Duo', text: 'Choisis un joueur et fais-lui un compliment en le prenant par les épaules, avec son accord.' },
    { label: 'Miroir', text: 'Imite chaque geste d’un joueur consentant pendant vingt secondes, comme dans un miroir.' },
    { label: 'Slow', text: 'Demande à un joueur de danser un slow avec toi sur une chanson imaginaire, avec son accord.' },
    { label: 'Dos à dos', text: 'Reste dos à dos avec un joueur consentant et devinez ce que pense l’autre.' },
    { label: 'Duo', text: 'Choisis un joueur pour chanter un duo d’amour avec toi, avec son accord.' },
    { label: 'Question', text: 'Pose une question intime mais pudique au joueur de ton choix, il peut refuser.' },
    { label: 'Aveux', text: 'Échange des confidences romantiques de trente secondes avec un joueur, à voix basse.' },
    { label: 'Yeux fermés', text: 'Devine le visage d’un joueur consentant en effleurant à peine ses mains, yeux fermés.' },
    { label: 'Danse', text: 'Danse joue contre joue avec le joueur de ton choix pendant dix secondes, avec son accord.' },
    { label: 'Mots doux', text: 'Dis un mot doux dans une langue étrangère à l’oreille d’un joueur, avec son accord.' },
    { label: 'Cavalier', text: 'Offre ton bras comme dans un bal à un joueur, avec son accord, et fais un tour de la pièce.' },
    { label: 'Bougie', text: 'Allume une bougie ou la lampe d’un téléphone et dis un compliment romantique à la lueur.' },
    { label: 'Frisson', text: 'Souffle doucement sur ta paume vers un joueur, comme un baiser envoyé.' },
    { label: 'Éventail', text: 'Évente un joueur avec ta main en le complimentant sur son charme, avec son accord.' },
    { label: 'Compliments', text: 'Fais trois compliments sensuels à trois joueurs différents, sans vulgarité.' },
    { label: 'Rituel', text: 'Fais un rituel de séduction : regard, sourire, geste, et tiens la pose cinq secondes.' },
    { label: 'Épaule', text: 'Pose doucement ta tête sur l’épaule d’un joueur pendant dix secondes, avec son accord.' },
    { label: 'Vœu', text: 'Fais un vœu romantique pour la soirée et dis-le à voix basse à quelqu’un.' },
    { label: 'Lenteur', text: 'Prends ton temps pour dire « bonsoir » à chaque joueur, avec une voix lente et séduisante.' },
    { label: 'Danse', text: 'Danse sur place les yeux fermés, en imaginant la meilleure soirée de ta vie, pendant quinze secondes.' },
    { label: 'Enlace', text: 'Enlace un joueur, avec son accord, et dis-lui un compliment doux à l’oreille.' },
    { label: 'Charme', text: 'Fais le tour de la pièce en saluant chaque joueur avec un baisemain, avec son accord.' },
    { label: 'Soir', text: 'Dis la phrase que tu murmurerais pour clore une soirée parfaite.' },
    { label: 'Rouge', text: 'Fais rougir un joueur avec un compliment élégant et précis.' },
    // Bonus : Joker
    { label: 'Joker', text: 'Tu es sauvé : aucun gage coquin pour toi ce tour, respire et souris.' },
    { label: 'Joker', text: 'Joker ! Tu gardes tes secrets et tes vêtements ce tour, profites-en.' },
    { label: 'Joker', text: 'Le charme t’a sauvé : tu es dispensé de gage jusqu’à ton prochain tour.' },
    // Bonus : Tu choisis
    { label: 'Tu choisis', text: 'Désigne le joueur qui devra relever le prochain gage à ta place.' },
    { label: 'Tu choisis', text: 'Offre le prochain gage au joueur de ton choix, avec un sourire malicieux.' },
    { label: 'Tu choisis', text: 'Choisis qui tourne la roue après toi, et lance-lui un regard de défi.' },
    // Bonus : Rejoue
    { label: 'Rejoue', text: 'Relance la roue tout de suite, et tu devras faire le gage avec le plus grand sérieux.' },
    { label: 'Rejoue', text: 'Seconde chance : tourne encore la roue et assume ce qui arrive.' },
    { label: 'Rejoue', text: 'Le destin insiste : relance la roue et accepte ce que tu obtiens.' },
    // Bonus : Tout le monde
    { label: 'Tout le monde', text: 'Tout le monde échange un compliment à voix basse avec son voisin de gauche.' },
    { label: 'Tout le monde', text: 'Tout le monde fait un slow imaginaire avec son verre pendant dix secondes.' },
    { label: 'Tout le monde', text: 'Tout le monde trinque en se regardant dans les yeux et boit une gorgée.' },
  ],
}
