import type { Level } from '../engine'

/** « Qui pourrait le plus… » — à 3, tout le monde pointe quelqu'un du doigt. */
export const whoCould: Record<Level, string[]> = {
  soft: [
    'survivre seul sur une île déserte',
    'devenir célèbre sur Internet',
    'oublier l’anniversaire de son meilleur ami',
    'se perdre avec un GPS',
    'adopter dix chats',
    'devenir président de la République',
    'pleurer devant une pub',
    'arriver en retard à son propre mariage',
    'gagner à un jeu télé',
    'finir en garde à vue pour une bêtise',
    'manger un truc tombé par terre',
    'se faire arnaquer en ligne',
    'partir vivre à l’autre bout du monde du jour au lendemain',
    'rire au pire moment possible',
    'devenir millionnaire',
    'passer une journée entière en pyjama',
    'casser son téléphone cette année',
    'lancer une entreprise improbable',
    'se battre avec une mouette pour un sandwich',
    'trébucher dans les escaliers ce soir',
    'raconter un secret sans faire exprès',
    'devenir prof',
    'écrire un livre',
    'avoir un enfant en premier',
    'oublier où est garée sa voiture',
    'chanter faux au karaoké avec une confiance totale',
    'dormir pendant un film au cinéma',
    'se faire tatouer sur un coup de tête',
  ],
  spicy: [
    'envoyer un message à son ex ce soir',
    'finir la soirée en pleurant',
    'embrasser quelqu’un ce soir',
    'se marier avec quelqu’un rencontré en vacances',
    'tromper son ou sa partenaire',
    'se faire ghoster cette semaine',
    'avoir le plus d’ex',
    'se remettre avec son ex',
    'faire une déclaration après quelques verres',
    'finir la soirée sans chaussures',
    'perdre son téléphone ce soir',
    'être le premier à rentrer se coucher',
    'tomber amoureux d’une star',
    'draguer un inconnu ce soir',
    'avoir un crush secret dans cette pièce',
    'dire oui à un mariage à Las Vegas',
    'mentir sur son CV',
    'quitter quelqu’un par SMS',
    'faire la fête trois jours de suite',
    'avoir deux dates le même soir',
    'stalker un crush jusqu’en 2015 sur Instagram',
    'se faire refouler d’une boîte',
    'être malade avant minuit',
    'avoir une liaison avec son boss',
    'se faire sortir d’un bar',
    'finir sur le canapé d’un inconnu',
    'pleurer en écoutant Céline Dion',
    'avoir un compte secret sur les réseaux',
  ],
  hot: [
    'avoir un plan à trois',
    'coucher le premier soir',
    'avoir le plus de partenaires',
    'avoir une vie secrète très coquine',
    'faire l’amour dans un lieu public',
    'avoir des menottes dans sa table de nuit',
    'envoyer des photos coquines',
    'avoir un sex friend en ce moment',
    'faire un strip-tease ce soir',
    'être le meilleur coup de la pièce',
    'avoir déjà simulé',
    'coucher avec quelqu’un de cette pièce',
    'avoir fait les choses les plus bizarres au lit',
    'faire carrière dans le cinéma pour adultes',
    'avoir une collection de sextoys',
    'avoir couché au travail',
    'fantasmer sur quelqu’un d’ici',
    'avoir un rendez-vous coquin ce week-end',
    'aimer se faire dominer',
    'avoir déjà été surpris en plein acte',
    'faire l’amour dans un avion',
    'avoir le fantasme le plus fou',
    'tester le naturisme',
    'passer une nuit blanche pour de très bonnes raisons',
    'être sorti avec l’ex de quelqu’un ici',
    'aller dans un club libertin',
    'faire un rêve érotique cette nuit',
    'dire le prénom de quelqu’un d’autre au lit',
  ],
}
