import type { Level } from '../engine'

/** « Qui pourrait le plus… » — à 3, tout le monde pointe quelqu'un du doigt. */
export const whoCould: Record<Level, string[]> = {
  soft: [
    'survivre seul sur une île déserte',
    'devenir célèbre sur Internet',
    'oublier l’anniversaire de son meilleur ami',
    'se perdre avec un GPS',
    'adopter dix chats',
    'devenir président de la République',
    'pleurer devant une pub',
    'arriver en retard à son propre mariage',
    'gagner à un jeu télé',
    'finir en garde à vue pour une bêtise',
    'manger un truc tombé par terre',
    'se faire arnaquer en ligne',
    'partir vivre à l’autre bout du monde du jour au lendemain',
    'rire au pire moment possible',
    'devenir millionnaire',
    'passer une journée entière en pyjama',
    'casser son téléphone cette année',
    'lancer une entreprise improbable',
    'se battre avec une mouette pour un sandwich',
    'trébucher dans les escaliers ce soir',
    'raconter un secret sans faire exprès',
    'devenir prof',
    'écrire un livre',
    'avoir un enfant en premier',
    'oublier où est garée sa voiture',
    'chanter faux au karaoké avec une confiance totale',
    'dormir pendant un film au cinéma',
    'se faire tatouer sur un coup de tête',
    'devenir une légende dans son métier',
    'gagner au loto sans le savoir',
    'rater son train à cause d’un café',
    'se faire des amis dans une file d’attente',
    'apprendre une langue étrangère en trois mois',
    'survivre à une apocalypse zombie',
    'tout planifier jusqu’à la dernière minute',
    'perdre ses clés trois fois par semaine',
    'rater un examen pourtant facile',
    'devenir une star de TikTok',
    'faire un discours devant mille personnes sans trembler',
    'se faire voler son sandwich au bureau',
    'devenir champion olympique d’un sport bizarre',
    'manger le même plat tous les jours pendant un an',
    'cuisiner un repas immangeable',
    'gagner un concours de cuisine à la télé',
    'faire le tour du monde à vélo',
    'devenir astronaute',
    'acheter un truc inutile à 3 h du matin',
    'tomber en panne d’essence',
    'rester coincé dans un ascenseur',
    'écrire un best-seller sans le vouloir',
    'devenir influenceur voyage',
    'se réveiller en retard le jour d’un examen',
    'laisser son téléphone dans un taxi',
    'négocier un rabais sur n’importe quoi',
    'ouvrir un restaurant et le fermer en six mois',
    'faire pousser un potager entier',
    'se faire adopter par un chien errant',
    'perdre un pari stupide',
    'tout oublier le jour de son départ en vacances',
    'faire sa valise à la dernière minute',
    'prendre un coup de soleil en plein hiver',
    'danser sur une table',
    'fonder un club complètement absurde',
    'devenir le meilleur ami de son voisin',
    'se faire repérer dans la foule d’un concert',
    'gagner une partie de Monopoly sans tricher',
    'se fâcher à cause d’un jeu de société',
    'ne jamais lire la notice',
    'rester coincé dehors sans ses clés',
    'faire une blague au pire moment',
    'passer une nuit dans une cabane perdue en forêt',
    'apprendre un instrument en autodidacte',
    'jouer dans un film',
    'se faire élire délégué de quelque chose',
    'courir un marathon sans s’entraîner',
    'déménager trois fois en un an',
    'rater sa sortie d’autoroute',
    'parler tout seul dans la rue',
    's’endormir dans le métro et rater son arrêt',
    'se tromper de salle de réunion',
    'devenir chef étoilé',
    'devenir youtubeur',
    'parier sur le bon cheval',
    'tomber dans une fontaine',
    'se faire reconnaître dans la rue',
    'faire un câlin à un inconnu',
    'se disputer avec un robot de service client',
    'se lier d’amitié avec un animal sauvage',
    'veiller le dernier à une soirée jeux',
    'vivre dans un camion aménagé',
    'finir un livre en une nuit',
    'faire du bénévolat sans jamais se plaindre',
    'gagner un blind test',
    'retenir la date d’anniversaire de tout le monde',
    'envoyer un message au mauvais destinataire',
    'appeler quelqu’un par le mauvais prénom',
    'rater un gâteau qui s’effondre au four',
    'adopter un animal exotique',
    'accepter un défi sans réfléchir',
    'gagner un concours de grimaces',
    'apprendre à jongler en une semaine',
    'se faire passer pour un expert sans rien y connaître',
    'vendre n’importe quoi à n’importe qui',
    'craquer pour des soldes complètement inutiles',
    'devenir maire de son village',
    'acheter une maison en ruine pour la retaper',
    'partir en randonnée en tongs',
    'oublier de payer une facture',
    'partir camper sans rien préparer',
    'rater son avion',
    'devenir expert en théories du complot rigolotes',
    'prendre un selfie au pire moment',
    'être le dernier à comprendre une blague',
    'raconter la même histoire cinq fois dans la soirée',
    'se perdre dans un supermarché',
    'devenir pro de jeux vidéo',
    'passer des heures bloqué sur un seul niveau de jeu',
    'tomber en panne de batterie au pire moment',
    'payer beaucoup trop cher un truc en vacances',
    'se faire embarquer dans une chorale',
    'gagner un concours de danse',
    'rester zen dans un embouteillage',
    'prendre la parole sans qu’on lui demande',
    'se déguiser pour rien un mardi',
    'rater un spectacle de magie devant tout le monde',
    'prendre un abonnement à la salle de sport et n’y aller qu’une fois',
    'apprendre à surfer en une semaine',
    'offrir le pire cadeau de l’histoire',
    'recevoir un cadeau et faire semblant d’aimer',
    'devenir une figure locale',
    'partir vivre à la montagne avec des chèvres',
    'se retrouver mêlé à une situation absurde',
    'gagner une course de caddies',
    'se faire battre par un enfant de huit ans à un jeu vidéo',
    'trouver un trésor enterré',
    'participer à une expérience scientifique bizarre',
    'tomber sur une célébrité au supermarché',
    'prendre un chemin de traverse et se perdre',
    'collectionner des objets complètement inutiles',
    'rater une marche en descendant l’escalier',
    'sortir avec son pull à l’envers sans le savoir',
    's’inscrire à un concours de talents',
    'regarder une série entière en un week-end',
    'passer pour un génie sans rien faire',
    'faire toutes les brocantes tous les week-ends',
    'raconter n’importe quoi avec aplomb',
    'tenir une journée entière sans son téléphone',
    'trouver l’amour dans une file d’attente',
    'inventer un mot qui entre dans le dictionnaire',
    'gagner un concours de crêpes',
    'se prendre une porte vitrée',
    'vivre dans un château',
    'fonder une famille nombreuse',
    'se lancer en politique',
    'monter un meuble sans notice',
    'faire un barbecue en pleine tempête',
    'partir en vacances sans rien réserver',
    'monter dans le mauvais avion',
    'inventer un truc qui change le monde',
    'rester calme pendant une catastrophe',
    'paniquer à cause d’une araignée',
    'devenir dresseur de chiens',
    'retrouver des pièces en trop après un montage',
    'faire un discours de mariage mémorable',
    'sauter en parachute sans hésiter',
    'devenir expert en blagues de papa',
  ],
  spicy: [
    'envoyer un message à son ex ce soir',
    'finir la soirée en pleurant',
    'embrasser quelqu’un ce soir',
    'se marier avec quelqu’un rencontré en vacances',
    'tromper son ou sa partenaire',
    'se faire ghoster cette semaine',
    'avoir le plus d’ex',
    'se remettre avec son ex',
    'faire une déclaration après quelques verres',
    'finir la soirée sans chaussures',
    'perdre son téléphone ce soir',
    'être le premier à rentrer se coucher',
    'tomber amoureux d’une star',
    'draguer un inconnu ce soir',
    'avoir un crush secret dans cette pièce',
    'dire oui à un mariage à Las Vegas',
    'mentir sur son CV',
    'quitter quelqu’un par SMS',
    'faire la fête trois jours de suite',
    'avoir deux dates le même soir',
    'stalker un crush jusqu’en 2015 sur Instagram',
    'se faire refouler d’une boîte',
    'être malade avant minuit',
    'avoir une liaison avec son boss',
    'se faire sortir d’un bar',
    'finir sur le canapé d’un inconnu',
    'pleurer en écoutant Céline Dion',
    'avoir un compte secret sur les réseaux',
    'liker une vieille photo de son ex par erreur',
    'appeler son ex en pleine nuit',
    'se faire démasquer en train de mentir',
    'flirter avec le serveur pour avoir un verre gratuit',
    'oublier le prénom de la personne avec qui il discute',
    'se réveiller sans se souvenir de la veille',
    'danser sur une table dans une boîte',
    'monter sur scène au karaoké sans qu’on lui demande',
    'envoyer un vocal de dix minutes à un crush',
    'se faire poser un lapin à un rencard',
    'rester ami avec tous ses ex',
    'lâcher un secret après deux verres',
    'se fâcher avec un ami pour une histoire de cœur',
    'inviter son ex à son mariage',
    'se faire larguer par message',
    'craquer pour le meilleur ami de son ex',
    'passer la nuit à parler de son ex',
    'écrire un texto qu’il regrettera le lendemain',
    'laisser un message sans réponse pendant trois jours',
    'faire une scène de jalousie en public',
    's’inscrire sur une appli de rencontres en cachette',
    'avoir plusieurs matchs en même temps sur une appli',
    'mentir sur sa taille sur une appli de rencontres',
    'flirter avec le ou la partenaire d’un ami',
    'se faire surprendre en train de stalker quelqu’un',
    'envoyer un message à la mauvaise personne et le regretter',
    'pleurer à un mariage sans connaître les mariés',
    'finir la soirée à côté des toilettes',
    's’endormir sur le canapé en pleine soirée',
    'se faire recaler à l’entrée d’une soirée',
    'partir de la soirée sans dire au revoir',
    'rentrer à l’aube sans savoir comment',
    'oublier son sac dans un bar',
    'perdre ses clés en soirée',
    'crier des secrets pendant un karaoké',
    'se créer un faux profil sur les réseaux',
    'raconter les secrets des autres pour faire rire',
    'répandre une rumeur sans le vouloir',
    'être le dernier à comprendre un ragot',
    'faire croire qu’il est célibataire alors qu’il ne l’est pas',
    'tomber amoureux en vacances',
    'se marier trop jeune',
    'avoir un coup de foudre dans le métro',
    'faire du charme pour obtenir un service',
    'boire le verre d’un inconnu par erreur',
    'insister pour payer la tournée',
    'proposer un dernier verre à 4 h du matin',
    'oublier de payer son addition',
    'se vanter d’un exploit imaginaire',
    'se faire griller par ses parents après une sortie',
    'organiser une soirée qui dégénère',
    'se faire plaindre par les voisins après une soirée',
    'pousser un action ou vérité beaucoup trop loin',
    'faire une déclaration d’amour sur les réseaux',
    'poster une photo qu’il regrettera le lendemain',
    'avoir un dossier de captures d’écran compromettantes',
    's’abonner à son crush pour voir ce qu’il fait',
    'ignorer un message pour faire croire qu’il est occupé',
    'écrire à son ex le jour de son anniversaire',
    'garder les affaires de son ex',
    'changer trois fois d’avis sur un rendez-vous',
    'se déclarer et se prendre un râteau',
    'se faire éconduire avec élégance',
    'offrir un cadeau trop gros à un premier rendez-vous',
    'inviter quelqu’un à dîner juste pour l’impressionner',
    'mentir pour éviter un rencard',
    'inventer une excuse ridicule pour annuler une soirée',
    'faire semblant d’être malade pour sécher une sortie',
    'tomber sur son ex le pire jour possible',
    'avoir une histoire avec un collègue',
    'sortir avec le meilleur ami d’un ami',
    'faire croire à un couple avec un ami',
    'se faire passer pour le couple de quelqu’un pour fuir un lourd',
    'pleurer devant une comédie romantique',
    'rester coincé dans une relation compliquée',
    'dire « je t’aime » beaucoup trop tôt',
    'présenter un partenaire à sa famille au bout d’une semaine',
    'casser un verre en soirée',
    'renverser sa boisson sur quelqu’un',
    'faire un toast interminable',
    's’endormir pendant un premier rendez-vous',
    'se faire offrir un verre par un inconnu',
    'refuser un verre pour la première fois de sa vie',
    'jouer les cupidons et tout rater',
    'parler d’un ami dans un groupe où il est présent',
    'envoyer une capture d’écran à la personne concernée',
    'transformer une soirée tranquille en nuit blanche',
    'tomber amoureux de son colocataire',
    'partir en week-end improvisé avec un crush',
    'mentir sur son métier à un rendez-vous',
    'donner un faux numéro à un lourd',
    'passer la nuit dehors sans prévenir ses amis',
    'pleurer en relisant un vieux message',
    'relire tous les anciens messages de son ex',
    'supprimer puis réinstaller une appli de rencontres',
    'se montrer en couple sur les réseaux beaucoup trop tôt',
    'liker une publication de son crush à 2 h du matin',
    'chanter sous la fenêtre de quelqu’un',
    's’incruster à une soirée sans être invité',
    'se faire des amis dans les toilettes d’une boîte',
    'raconter toute sa vie à un chauffeur de taxi',
    'se faire draguer par la personne la moins attendue',
    'être la cause d’une dispute de couple',
    'casser avec quelqu’un à cause d’un détail ridicule',
    'se mettre en couple pour la mauvaise raison',
    'être jaloux de l’ex de son partenaire',
    'faire une crise pour un « vu » sans réponse',
    'faire semblant de partir de soirée et revenir',
    'être le seul déguisé à une soirée',
    'se faire prendre en photo dans une position gênante',
    'tomber de sa chaise en pleine soirée',
    'faire un discours gênant à un mariage',
    'rire tout seul dans un restaurant chic',
    'mentir sur le nombre de ses ex',
    'prétendre être un grand fêtard alors qu’il dort à 22 h',
    'flirter sans s’en rendre compte',
    'draguer avec des phrases d’accroche nulles',
    'poser une question gênante devant tout le monde',
    'mettre une photo de couple en fond d’écran dès la première semaine',
    'relancer une conversation avec « coucou ça va ? » à minuit',
    'inviter tout le monde chez lui sans prévenir',
    'sortir la bouteille de trop',
    'donner de très mauvais conseils sentimentaux',
    'débarquer à la soirée de son ex',
    'trouver un prétexte pour revoir son ex',
    'dire du mal de quelqu’un qui arrive juste derrière lui',
    'devenir ami avec le nouveau de son ex',
    'faire un gage ridicule sans broncher',
    'avouer un crush devant tout le monde',
    'se mettre en couple pendant un voyage entre amis',
    'oublier le prénom de son rencard en plein dîner',
    'être le premier à craquer à un jeu à boire',
    'pleurer dans le VTC en rentrant',
    'dépenser tout son budget en une seule soirée',
    'tomber amoureux de quelqu’un croisé à la salle de sport',
  ],
  hot: [
    'avoir un plan à trois',
    'coucher le premier soir',
    'avoir le plus de partenaires',
    'avoir une vie secrète très coquine',
    'faire l’amour dans un lieu public',
    'avoir des menottes dans sa table de nuit',
    'envoyer des photos coquines',
    'avoir un sex friend en ce moment',
    'faire un strip-tease ce soir',
    'être le meilleur coup de la pièce',
    'avoir déjà simulé',
    'coucher avec quelqu’un de cette pièce',
    'avoir fait les choses les plus bizarres au lit',
    'faire carrière dans le cinéma pour adultes',
    'avoir une collection de sextoys',
    'avoir couché au travail',
    'fantasmer sur quelqu’un d’ici',
    'avoir un rendez-vous coquin ce week-end',
    'aimer se faire dominer',
    'avoir déjà été surpris en plein acte',
    'faire l’amour dans un avion',
    'avoir le fantasme le plus fou',
    'tester le naturisme',
    'passer une nuit blanche pour de très bonnes raisons',
    'être sorti avec l’ex de quelqu’un ici',
    'aller dans un club libertin',
    'faire un rêve érotique cette nuit',
    'dire le prénom de quelqu’un d’autre au lit',
    'avoir déjà fait l’amour dans une voiture',
    'avoir déjà fait l’amour dans un ascenseur',
    'avoir déjà fait l’amour sur la plage',
    'envoyer un message coquin à la mauvaise personne',
    'cacher un tiroir secret rempli de dessous coquins',
    'avoir la lingerie la plus audacieuse',
    'porter de la lingerie sexy un jour sans raison',
    'acheter un jouet coquin en secret',
    'tester un jeu de rôle coquin',
    'se déguiser pour pimenter une soirée à deux',
    'faire un massage qui dérape',
    'donner les meilleurs massages sensuels',
    'être le meilleur embrasseur de la pièce',
    'danser un slow très collé-serré',
    'dormir nu toutes les nuits',
    'se baigner nu en pleine nuit',
    'faire du bronzage intégral',
    'rougir en pleine conversation coquine',
    'avoir une playlist spéciale pour les moments à deux',
    'allumer les bougies pour une soirée de séduction',
    'avoir vécu une aventure d’un soir qu’il n’oubliera jamais',
    'regretter une aventure d’un soir',
    'faire trop de bruit et réveiller tout l’immeuble',
    'avoir un faible pour les uniformes',
    'avoir un faible pour les accents étrangers',
    'craquer pour une voix grave',
    'envoyer un sexto en pleine réunion',
    'se faire surprendre en plein sexto',
    'recevoir une photo coquine qu’il n’attendait pas',
    'garder précieusement une photo coquine',
    'regarder un film érotique en cachette',
    'lire des romans érotiques en cachette',
    'connaître le Kamasutra par cœur',
    'essayer une position acrobatique et finir par éclater de rire',
    'rire pendant un moment intime',
    'faire une gaffe monumentale dans un moment intime',
    's’endormir en plein câlin coquin',
    'cacher un tatouage à un endroit secret',
    'avoir un piercing que personne n’a jamais vu',
    'flirter avec un inconnu dans un ascenseur',
    'embrasser un inconnu au nouvel an',
    'embrasser deux personnes différentes dans la même soirée',
    'embrasser un ami de longue date par curiosité',
    'coucher avec un ex par nostalgie',
    'retourner voir un ex pour une dernière nuit',
    'passer une nuit avec quelqu’un sans connaître son prénom',
    'fantasmer sur un collègue',
    'draguer un serveur pour de bon',
    'glisser son numéro sur un ticket de caisse',
    'glisser un mot coquin dans la poche de quelqu’un',
    'envoyer des fleurs avec un message osé',
    'commander un dîner aux chandelles pour séduire',
    'préparer un dîner aphrodisiaque',
    'utiliser le chocolat pour pimenter une soirée',
    'perdre en premier à un strip-poker',
    'jouer à action ou vérité dans un sens très coquin',
    'inventer un code secret pour les rendez-vous coquins',
    'avoir un surnom coquin pour son ou sa partenaire',
    'craquer pour les murmures à l’oreille',
    'draguer avec une phrase très osée',
    'envoyer un message coquin à son crush ce soir',
    'être le plus audacieux en matière de séduction',
    'avoir déjà fait l’amour dans une tente',
    'partir camper rien que pour l’intimité',
    'réserver un hôtel pour une journée entière à deux',
    'réserver un week-end romantique avec une idée derrière la tête',
    'louer un jacuzzi pour un week-end à deux',
    'faire l’amour sous la douche',
    'prendre des bains moussants en couple',
    'faire l’amour dans les toilettes d’une boîte',
    's’éclipser discrètement d’une soirée avec quelqu’un',
    'disparaître d’une fête avec un crush',
    'proposer un plan coquin dès le premier rendez-vous',
    'faire le premier pas',
    'faire patienter son crush pendant des semaines',
    'allumer quelqu’un sans aller plus loin',
    'se faire allumer sans comprendre',
    'faire monter la tension dans une pièce',
    'ressentir une tension palpable avec quelqu’un d’ici',
    'être attiré par le ou la partenaire d’un ami',
    'avoir eu un flirt au bureau',
    'avoir déjà couché avec un ami',
    'avoir une histoire coquine avec un voisin',
    'dormir chez quelqu’un sans vraiment dormir',
    'passer un week-end entier au lit',
    'passer une journée entière au lit à deux',
    'se faire surprendre par ses beaux-parents avec son partenaire',
    'oublier ses dessous chez quelqu’un',
    'repartir avec les vêtements de quelqu’un d’autre',
    'faire un tour en voiture sans destination pour se retrouver seul',
    'avoir un fantasme déjà avoué à son partenaire',
    'avoir un fantasme qu’il n’avouera jamais',
    'aimer prendre les commandes',
    'aimer qu’on lui murmure des mots doux et crus',
    'être le plus bruyant au lit',
    'être le plus discret au lit',
    'être le plus romantique avant d’enchaîner',
    'être le plus fougueux',
    'être le plus patient',
    'être le plus gourmand',
    'danser collé-serré avec un inconnu',
    'faire un petit show sensuel pour son partenaire',
    'danser langoureusement sur la piste',
    's’inscrire à un cours de pole dance',
    'poser pour un shooting boudoir',
    'faire une séance photo sexy',
    'poster une photo trop dénudée sur les réseaux',
    'tomber amoureux après une seule nuit',
    'ne jamais rappeler après une nuit',
    'disparaître au petit matin sans un mot',
    'inventer une urgence pour partir tôt le matin',
    'rester dormir alors qu’il comptait partir',
    'préparer le petit-déjeuner au lit',
    'draguer en plein cours de salsa',
    'faire un test de compatibilité avant de s’engager',
    'avoir une liste d’endroits insolites où faire l’amour',
    'fêter la Saint-Valentin sans sortir du lit',
    'faire l’amour avec les lumières allumées',
    'dire « je t’aime » pendant un moment intime sans le penser',
    'perdre un pari coquin',
    'relever un défi coquin en soirée',
    'utiliser une appli de rencontres uniquement pour les plans d’un soir',
    'chercher un partenaire de jeu coquin sur une appli',
    'avoir un match avec quelqu’un d’ici sur une appli',
    'flirter avec quelqu’un d’ici sans que personne le sache',
    'craquer pour un sourire en coin',
    'se laisser tenter par un massage aux huiles',
    'aimer être séduit lentement',
    'aimer les préliminaires interminables',
    'écrire une lettre d’amour très osée',
    'écrire une histoire érotique sous pseudo',
    'changer de pseudo sur une appli pour se lâcher',
    'parler de ses fantasmes à un inconnu',
    'rougir en achetant un jouet coquin',
  ],
}
