import type { Level } from '../engine'

/** Qui de nous deux ? — en duo, chacun pointe celui des deux qui correspond le mieux. */
export const whoOfUs: Record<Level, string[]> = {
  soft: [
    // Caractère et défauts
    'est le plus têtu',
    'est le plus lunatique',
    'est le plus bordélique',
    'est le plus maniaque',
    'est le plus organisé',
    'est le plus spontané',
    'est le plus radin',
    'est le plus gourmand',
    'est le plus susceptible',
    'est le plus joueur',
    'est le plus patient',
    'est le plus distrait',
    'est le plus pessimiste',
    'est le plus optimiste',
    'est le plus curieux',
    'est le plus paresseux',
    'est le plus sportif',
    'est le plus timide en public',
    'est le plus bavard',
    'est le plus rancunier',
    'est le plus gaffeur',
    'est le plus stressé',
    'est le plus nostalgique',
    'est le plus tête en l’air',
    'est le plus dramatique pour un petit bobo',
    'est le plus doué de ses mains',
    'est le plus sentimental',
    'est le plus généreux',
    'est le plus soupe au lait',
    'est le plus calme en cas de crise',
    // Sommeil et réveil
    's’endort en premier devant un film',
    'ronfle le plus fort',
    'parle le plus dans son sommeil',
    'pique la couverture pendant la nuit',
    'se réveille le plus de mauvaise humeur',
    'appuie le plus de fois sur “snooze”',
    'met le plus de temps à émerger le matin',
    'fait la grasse matinée le plus longtemps',
    'va se coucher en premier',
    'a le plus de mal à s’endormir',
    'fait les rêves les plus bizarres',
    'a le plus froid en hiver',
    'a le plus chaud en été',
    'prend le plus de place dans le lit',
    'fait la sieste le plus facilement',
    // Retards et organisation
    'arrive toujours en retard',
    'prépare sa valise le plus tard',
    'oublie le plus souvent quelque chose en partant',
    'perd le plus souvent ses clés',
    'perd le plus souvent son téléphone',
    'oublie le plus souvent les dates importantes',
    'dit “j’arrive dans cinq minutes” et en met trente',
    'est le premier prêt pour sortir',
    'met le plus de temps à se préparer',
    'laisse tout à la dernière minute',
    'fait le plus de listes',
    'se souvient le mieux des anniversaires',
    'oublie le plus souvent ce qu’il allait chercher dans la pièce',
    'rate le plus souvent son train ou son bus',
    // Ménage et maison
    'laisse traîner le plus de chaussettes',
    'oublie le plus souvent de sortir la poubelle',
    'fait le plus souvent la vaisselle',
    'range le mieux',
    'déteste le plus faire le ménage',
    'met le plus de temps à plier le linge',
    'laisse les tiroirs ouverts',
    'laisse la lumière allumée en quittant une pièce',
    'ne referme jamais les placards',
    'fait le plus de bricolage à la maison',
    'monte le mieux un meuble sans la notice',
    'perd le plus vite la notice',
    'a le plus de mal à jeter des affaires',
    'entasse le plus de choses inutiles',
    'règle le chauffage le plus haut',
    'aère le plus souvent la maison',
    // Cuisine et repas
    'cuisine le mieux',
    'brûle le plus de plats',
    'mange le plus vite',
    'goûte dans l’assiette de l’autre sans demander',
    'grignote le plus entre les repas',
    'oublie le plus souvent la liste de courses',
    'dévalise le plus le frigo la nuit',
    'se plaint le plus de la faim',
    'a le goût le plus difficile',
    'est le plus aventureux dans l’assiette',
    'ajoute le plus de sel',
    'termine toujours le dernier carré de chocolat',
    'serait le plus nul pour un concours de cuisine',
    'prend le plus de dessert',
    'fait le meilleur café ou thé',
    // Argent
    'fait le plus de dépenses inutiles',
    'économise le mieux',
    'oublierait de payer une facture',
    'achète le plus de choses en solde dont il n’a pas besoin',
    'surveille le plus son compte en banque',
    'est le plus tenté par les achats en ligne',
    'commande le plus souvent des livraisons',
    'négocie le mieux un prix',
    'gérerait le mieux un budget serré',
    'offre les cadeaux les plus réussis',
    'est le plus nul pour choisir un cadeau',
    'achète le plus de gadgets inutiles',
    // Voyages et transports
    'emporte trop de bagages en voyage',
    'se perd le plus facilement sans GPS',
    'conduit le mieux',
    'râle le plus dans les embouteillages',
    'organise le mieux un voyage',
    'prend le plus de photos en vacances',
    'se réveille le plus tôt en vacances',
    'rêve le plus d’un tour du monde',
    'supporte le moins bien le décalage horaire',
    'aurait le plus peur en avion',
    'se débrouillerait le mieux dans un pays inconnu',
    'parle le mieux les langues étrangères',
    'a le plus le mal des transports',
    'choisirait la montagne plutôt que la mer en premier',
    // Disputes et réconciliations
    'boude le plus longtemps',
    'fait le premier pas après une dispute',
    's’excuse en premier après une dispute',
    'a toujours le dernier mot',
    'reconnaît ses torts le plus difficilement',
    'élève le plus la voix',
    's’énerve le plus vite',
    'se calme le plus vite',
    'ressort le plus de vieux sujets pendant une dispute',
    'part le plus facilement claquer la porte',
    'a le plus souvent raison',
    'fait rire l’autre pour désamorcer une dispute',
    'garde le plus longtemps de la rancune',
    'se dispute le plus pour des détails',
    // Émotions et affection
    'dirait “je t’aime” en premier',
    'pleure le plus facilement devant un film',
    'est le plus câlin',
    'fait le plus de compliments',
    'écrit les plus beaux messages',
    'a le plus de mal à exprimer ses émotions',
    'est le plus romantique',
    'pense le plus aux petites attentions',
    'se souvient le mieux de la date de votre rencontre',
    'est le plus tendre quand l’autre est malade',
    'ferait le plus de folies pour l’autre',
    'est le plus gêné par les démonstrations d’affection en public',
    'a pleuré le premier à un mariage',
    'garde le plus de souvenirs sentimentaux',
    // Humour et conversation
    'rit le plus fort',
    'fait les meilleures blagues',
    'raconte le plus de fois la même histoire',
    'parle le plus',
    'écoute le mieux',
    'coupe le plus la parole',
    'fait le plus d’imitations',
    'a le fou rire le plus facile',
    'fait les pires jeux de mots',
    'est le plus drôle quand il est fatigué',
    'passe le plus de temps au téléphone avec ses proches',
    'sait le mieux remonter le moral',
    // Téléphone et écrans
    'passe le plus de temps sur son téléphone',
    'répond le plus vite aux messages',
    'laisse le plus de messages vocaux',
    'ignore le plus ses notifications',
    'a la galerie photo la plus remplie',
    'a le plus d’applications inutiles',
    'a le téléphone le plus souvent à plat',
    'a le plus de captures d’écran en vrac',
    'regarde le plus de vidéos absurdes',
    'envoie le plus de mèmes',
    'est le plus accro aux séries',
    'passe le plus de temps sur les réseaux sociaux',
    'a l’écran le plus fissuré',
    // Famille, amis et fêtes
    'est le plus proche de sa famille',
    'appelle le plus souvent ses parents',
    'est le plus à l’aise avec les inconnus',
    'prépare le mieux les fêtes de famille',
    'se déguiserait le plus volontiers pour Halloween',
    'est le plus excité à Noël',
    'cache le mieux un cadeau',
    'devine le mieux ce qu’il y a dans un paquet',
    'organise le mieux une fête surprise',
    'garde le mieux un secret',
    'est le plus sociable en soirée',
    'rentre le premier d’une soirée',
    'danse le mieux',
    'chante le plus faux sous la douche',
    'connaît le plus de paroles de chansons',
    // Souvenirs, passions et avenir
    'se souvient le mieux des détails',
    'a la meilleure mémoire des visages',
    'parlerait le plus de vos souvenirs de vacances',
    'rêve le plus d’avoir un animal',
    'serait le plus doué avec des enfants',
    'serait le plus fou de son animal',
    'veut le plus déménager à la campagne',
    'rêve le plus d’une grande maison',
    'ferait le plus de sacrifices pour sa carrière',
    'changerait le plus facilement de métier',
    'est le plus lent à prendre une décision',
    'a le plus d’idées farfelues',
    'se lancerait le plus vite dans un nouveau projet',
    'abandonnerait le plus vite un nouveau hobby',
    'tiendrait le plus longtemps sans écran',
    'gagnerait à un jeu de société',
    'triche le plus aux jeux',
    'est le plus mauvais perdant',
    'réussirait le mieux un jeu télévisé',
    'survivrait le mieux sur une île déserte',
  ],
  spicy: [
    // Jalousie et séduction
    'est le plus jaloux',
    'fait le plus de scènes de jalousie',
    'regarde le plus les autres dans la rue',
    'drague le plus sans s’en rendre compte',
    'se fait le plus draguer',
    'cache le mieux sa jalousie',
    'stalke le plus les profils des autres',
    'surveille le plus les abonnés de l’autre',
    'aime le plus quand l’autre est jaloux',
    'ferait le plus de scènes si l’autre dansait avec quelqu’un',
    'a le sourire le plus charmeur',
    'séduit le plus facilement un inconnu',
    'est le plus doué pour le regard qui tue',
    'envoie le plus de messages charmeurs',
    'flirte le plus avec le serveur ou la serveuse',
    'est le plus à l’aise pour draguer',
    'a le plus de succès sur les applis de rencontre',
    'a le plus de chance de se faire offrir un verre',
    'a déjà fait croire à un inconnu qu’il était célibataire',
    'se sent le plus flatté par un compliment d’un inconnu',
    'a le plus peur de perdre l’autre',
    'est le plus possessif',
    'est le plus détendu quand l’autre sort sans lui',
    'regarde le plus le téléphone de l’autre en douce',
    'a le plus craqué pour un collègue',
    'a le plus de mal à résister à un beau sourire',
    'a eu le plus de coups de foudre',
    // Ex
    'parle le plus de ses ex',
    'est resté le plus en bons termes avec un ex',
    'a gardé le plus de souvenirs de ses ex',
    'a eu le plus de relations avant vous',
    'a le plus de mal à tourner la page',
    'a le plus d’ex encore dans ses contacts',
    'a failli retourner avec un ex',
    'serait le plus gêné de croiser un ex',
    'a le pire souvenir de rupture',
    'a le plus fait pleurer un ex',
    'a le plus pleuré après une rupture',
    'a déjà quitté quelqu’un par message',
    'serait le plus mal à l’aise face à l’ex de l’autre',
    'a rompu le plus vite',
    // Soirées et alcool
    'tient le mieux l’alcool',
    'est le plus bavard quand il a bu',
    'est le plus câlin quand il a bu',
    'devient le plus émotif après trois verres',
    'a eu la plus grosse gueule de bois',
    'finit toujours le dernier à la soirée',
    'danse le plus sur les tables',
    'chante le plus fort au karaoké',
    'raconte le plus de secrets quand il a bu',
    'a oublié le plus de choses après une soirée',
    'a le plus de trous de mémoire',
    'est le plus lourd quand il a un verre dans le nez',
    'commande le plus de tournées',
    'serait le plus nul à un jeu à boire',
    'a le plus fait une bêtise en soirée',
    'est le plus agaçant quand il est ivre',
    'dort le plus vite après une soirée arrosée',
    'oublie le plus de rentrer à l’heure',
    'a déjà dormi sur le canapé d’un inconnu',
    'est le plus tenté de rester une heure de plus',
    'fait le plus de promesses qu’il ne tient pas en soirée',
    'se fait le plus d’amis dans une soirée',
    'envoie le plus de messages gênants après minuit',
    'se réveille le plus perdu après une soirée',
    'a le pire karaoké quand il a bu',
    'a le plus souvent “juste un dernier verre” avant de partir',
    'a le plus honte de sa dernière soirée',
    'a déjà perdu le plus de choses en soirée',
    'a le plus de blagues douteuses après quelques verres',
    // Mensonges et secrets
    'ment le mieux',
    'rougit le plus quand il ment',
    'a le plus de secrets',
    'cache le plus de choses à l’autre',
    'fait le plus de petits mensonges pour éviter une dispute',
    'ment le plus pour paraître plus intéressant',
    'ment le plus sur l’heure de son retour',
    'ment le plus sur ses dépenses',
    'ment le plus sur ce qu’il a mangé',
    'a déjà fait croire qu’il n’avait pas vu un message',
    'est le plus nul pour mentir',
    'craque le plus vite à un interrogatoire',
    'a le plus de choses à cacher sur son téléphone',
    'a un compte secret sur un réseau social',
    'a déjà menti pour éviter une soirée',
    'garde le plus de choses pour lui',
    'raconte le plus de choses à ses amis sur le couple',
    'a déjà inventé une excuse pour arriver en retard',
    'fait semblant le plus souvent d’aimer un cadeau',
    'a déjà fait semblant d’aimer un plat',
    'a déjà fait semblant de comprendre une blague',
    'a déjà fait semblant d’avoir écouté',
    'cacherait le mieux une surprise',
    'est le plus doué pour trouver des excuses',
    'a le plus de mal à avouer une bêtise',
    'a déjà caché un achat à l’autre',
    'a le plus de petits secrets inavouables',
    // Disputes et pardon
    'provoque le plus de disputes',
    'dit des choses qu’il regrette en pleine dispute',
    'crie le plus fort dans une dispute',
    'ressasse le plus longtemps une dispute',
    'reste le plus silencieux pendant une dispute',
    'fait le plus de reproches',
    'a eu le plus de crises de nerfs',
    'pardonne le plus difficilement',
    'a le plus de mal à demander pardon',
    'dort le plus mal après une dispute',
    'répond le plus sèchement par message',
    'fait le plus souvent la tête devant des amis',
    'ose le plus dire ses quatre vérités',
    'met le plus de mauvaise foi dans une discussion',
    'dirait “comme tu veux” en pensant le contraire',
    'ne dirait jamais ce qui l’agace vraiment',
    'a déjà fait semblant d’aller bien alors que non',
    'est le plus doué pour une réconciliation sur l’oreiller',
    'a déjà claqué la porte au milieu d’une dispute',
    'a le plus de mal à ne pas relever une remarque',
    'a le plus de mal à lâcher son téléphone pendant une dispute',
    // Comportements et fierté
    'est le plus fier',
    'est le plus attaché à son image',
    'est le plus influençable',
    'est le plus manipulateur',
    'est le plus sournois',
    'est le plus charmeur pour obtenir ce qu’il veut',
    'est le plus doué pour se faire pardonner',
    'est le plus joueur avec le feu',
    'est le plus tentant à provoquer',
    'prend le plus de risques',
    'est le plus téméraire',
    'est le plus sûr de lui',
    'est le plus dépendant de l’avis des autres',
    'est le plus insolent',
    'a le plus fort caractère',
    'se sent le plus supérieur dans un débat',
    'a le moins de limites',
    // Vie sociale et réseaux
    'likerait en cachette la photo d’un inconnu',
    'poste les photos les plus flatteuses',
    'a le plus d’abonnés',
    'répond le plus tard aux messages de l’autre',
    'a déjà ignoré exprès un appel',
    'a déjà vu un message qu’il n’aurait pas dû lire',
    'garde le plus de captures d’écran gênantes',
    'a le plus de conversations privées avec des amis',
    'a le plus de mal à se déconnecter',
    'ouvre le plus de messages en douce',
    'est le plus tenté de regarder les stories de ses ex',
    'est le plus tenté de vérifier le dernier message de l’autre',
    'est le plus inquiet quand l’autre ne répond pas',
    'a le plus mal réagi à un “vu” sans réponse',
    // Couple et avenir
    'a le plus peur de l’engagement',
    'veut le plus d’enfants',
    'veut le plus se marier',
    'a le plus parlé de mariage',
    'serait le plus stressé le jour du mariage',
    'dépenserait le plus pour un mariage',
    'a le plus envie d’emménager ensemble pour de bon',
    'a le plus hésité avant de s’engager',
    'a le plus changé depuis le début de la relation',
    'aurait le plus de mal à tout quitter pour l’autre',
    'est le plus attaché à son indépendance',
    'ferait le plus de compromis pour que ça marche',
    'a le plus envie de voyager seul',
    'a le plus peur de la routine',
    'ressent le plus le besoin d’espace',
    'tient le plus aux traditions',
    'se projette le plus loin dans l’avenir',
    'saurait le mieux faire son deuil d’une relation',
    'serait le plus perdu sans l’autre',
    'serait le plus malheureux sans l’autre',
    'a dit “je t’aime” le plus tôt',
    'a eu le plus de doutes au début de votre histoire',
    'a regretté le plus de choses depuis votre rencontre',
    'a fait les premiers pas pour vous rencontrer',
    'a vite compris que ça allait durer',
    'a le plus peur d’être quitté',
    'a le plus peur d’être trompé',
    'pardonnerait le plus difficilement une trahison',
    'pardonnerait le plus vite une erreur',
    'est le plus honnête sur ses sentiments',
    'cache le plus ses larmes',
    'se confie le plus aux amis plutôt qu’à l’autre',
  ],
  hot: [
    // Premiers pas et séduction
    'a fait le premier pas pour vous embrasser',
    'a craqué le premier physiquement',
    'a le plus rougi lors du premier baiser',
    'embrasse le mieux',
    'embrasse le plus longtemps',
    'embrasse le plus passionnément',
    'a le regard le plus brûlant',
    'drague le plus en public',
    'dit les mots les plus doux à l’oreille',
    'donne les plus beaux compliments sur le physique',
    'complimente le plus le corps de l’autre',
    'rend l’autre le plus rouge de gêne',
    'séduit le plus avec ses mots',
    'séduit le plus avec ses yeux',
    'fait le plus d’efforts pour plaire',
    'fait le plus de clins d’œil complices',
    'est le plus joueur dans la séduction',
    'est le plus entreprenant',
    'est le plus doué pour mettre l’ambiance',
    'est le plus mystérieux',
    'se prête le mieux au jeu de la séduction à distance',
    // Câlins et tendresse
    'est le plus câlin au réveil',
    'fait les plus longs câlins',
    'propose un massage en premier',
    'masse le mieux',
    'caresse le plus doucement',
    'dort le plus collé à l’autre',
    'prend le plus de place pour se serrer',
    'a les mains les plus baladeuses',
    'a le plus besoin de contact physique',
    'est le plus tactile en public',
    'tient le plus la main',
    'fait le plus de bisous dans le cou',
    'aime le plus les baisers dans le cou',
    'aime le plus qu’on lui gratte le dos',
    'se serre le plus fort contre l’autre quand il fait froid',
    'frissonne le plus facilement',
    'rougit le plus à la moindre caresse',
    'sait le mieux trouver les bons gestes',
    'fait des câlins pour obtenir ce qu’il veut',
    // Initiative et désir
    'propose le plus souvent une soirée en amoureux',
    'prend le plus souvent l’initiative le soir',
    'a le plus d’envies spontanées',
    'est le plus enthousiaste le matin',
    'dit “pas ce soir” le plus souvent',
    'dit “oui” le plus vite',
    'a le plus d’énergie le soir',
    'a le plus d’énergie le matin',
    'a le plus de mal à résister à l’autre',
    'a le plus de désir en vacances',
    'a le plus de désir après une dispute',
    'a le plus de désir après une soirée entre amis',
    'a le plus de désir à la fin d’une longue semaine',
    'oublie le plus facilement les soucis dans les bras de l’autre',
    'se laisse le plus facilement tenter',
    'fait le plus d’allusions coquines',
    'fait le plus de blagues coquines',
    'a les idées les plus malicieuses',
    'demande le plus souvent “on monte ?”',
    'est le plus pressé de rentrer après un dîner',
    'a le plus envie de se retrouver seul avec l’autre en soirée',
    'a déjà fait comprendre par un simple regard qu’il voulait rentrer',
    'devient le plus entreprenant après un bon repas',
    'a le plus souvent envie de passer à l’acte à un moment inattendu',
    'est le plus coquin quand l’autre est occupé',
    // Messages et fantasmes
    'envoie les messages les plus coquins',
    'envoie le plus de photos osées',
    'envoie le plus de messages doux en pleine journée',
    'écrit les mots les plus coquins',
    'a le plus d’imagination',
    'a les fantasmes les plus audacieux',
    'avoue le plus ses fantasmes',
    'a le plus de mal à parler de ses envies',
    'parle le plus de ses envies',
    'a le plus de mal à dire ce qu’il aime',
    'dit le plus ce qu’il aime',
    'propose le plus d’idées nouvelles',
    'est le plus ouvert aux nouvelles expériences',
    'est le plus partant pour tester un nouveau jeu coquin',
    'est le plus tenté par une nouvelle expérience dans la chambre',
    'a le plus envie de pimenter la routine',
    'est le plus gêné d’aborder le sujet',
    'est le plus tenté par un cadeau coquin',
    'achèterait le plus facilement de la lingerie ou un accessoire coquin',
    'serait le plus ravi d’un cadeau coquin',
    'serait le plus embarrassé d’un cadeau coquin devant la famille',
    'a déjà lu le plus de livres coquins',
    'a déjà regardé le plus de films coquins',
    'a le plus d’idées pour une soirée spéciale',
    'préparerait le mieux une surprise romantique',
    'préparerait le mieux une soirée en tête-à-tête',
    'a le plus pensé à une soirée osée à deux',
    'serait le plus fier de proposer un jeu de rôle',
    'serait le plus doué pour un jeu de rôle',
    'serait le plus convaincant dans un déguisement coquin',
    'se déguiserait le plus facilement pour pimenter la soirée',
    'serait le plus prêt à tenter un jeu de bandeau',
    'serait le plus prêt à se laisser surprendre',
    'aime le plus être surpris',
    'aime le plus surprendre',
    'aime le plus mener la danse',
    'aime le plus se laisser guider',
    // Lieux, bruit et discrétion
    'oserait le plus un lieu insolite',
    'est le plus tenté par un lieu risqué',
    'est le plus pudique',
    'est le plus exhibitionniste',
    'est le moins gêné par son corps',
    'se balade le plus nu dans l’appartement',
    'est le plus gêné d’être vu nu',
    'est le plus bruyant',
    'est le plus discret',
    'est le plus gêné par les murs fins',
    'serait le plus gêné d’être entendu par les voisins',
    'serait le plus gêné d’être surpris',
    'a le plus peur de se faire surprendre',
    'a déjà failli se faire surprendre par quelqu’un',
    'est le plus stressé dans une maison qui n’est pas la sienne',
    'est le plus tenté pendant un voyage',
    'est le plus tenté dans un hôtel',
    'préfère le plus l’hôtel à la maison',
    'préfère le plus le lit plutôt qu’ailleurs',
    'aime le plus la douche à deux',
    'a le plus envie d’un bain à deux',
    'aime le plus les bougies et la musique douce',
    'a le plus d’idées de playlist pour une soirée en amoureux',
    'allume le plus vite la musique pour créer l’ambiance',
    'éteint le plus vite la lumière',
    'préfère le plus faire ça en pleine lumière',
    // Préliminaires et complicité
    'est le plus patient pendant les préliminaires',
    'est le plus pressé',
    'prend le plus son temps',
    'est le plus attentif aux envies de l’autre',
    'est le plus doué pour deviner ce qui plaît à l’autre',
    'est le plus doué avec ses mains',
    'est le plus doué avec sa bouche',
    'est le plus doué pour faire monter la tension',
    'est le plus généreux au lit',
    'est le plus égoïste au lit',
    'est le plus gêné d’être regardé',
    'est le plus joueur sous la couette',
    'est le plus gourmand de câlins',
    'est le plus endurant',
    'est le plus fatigué après',
    'dort en premier après un câlin coquin',
    'a le plus envie de discuter après',
    'a le plus faim après',
    'se lève le premier après',
    'est le plus tendre après',
    'a le plus besoin de câlins après',
    'se rendort le plus vite après',
    'rit le plus fort pendant un moment intime',
    'a le fou rire le plus facile dans un moment intime',
    'dirait le plus “je t’aime” dans un moment intime',
    'a le plus pleuré d’émotion après un moment fort',
    'sait le plus faire patienter l’autre pour le plaisir',
    'aime le plus chuchoter des mots doux',
    'aime le plus les mots crus murmurés',
    'est le plus doué pour mettre l’autre à l’aise',
    'est le plus doué pour rassurer l’autre dans l’intimité',
    // Routine, humour et vie de couple
    'se plaint le plus du manque de câlins',
    'se plaint le plus de la fréquence',
    'est le plus gêné de parler de sexualité',
    'est le plus à l’aise pour parler d’intimité avec ses amis',
    'raconte le plus de détails à ses amis',
    'parle le plus à ses amis de votre vie intime',
    'a le plus d’anecdotes drôles sur vos nuits',
    'se souvient le mieux de votre première nuit',
    'se souvient le mieux de votre premier baiser',
    'se souvient le mieux de votre premier weekend en amoureux',
    'a gardé le plus de souvenirs coquins',
    'a le plus envie de refaire une première fois',
    'a le plus envie de recommencer comme au début',
    'est le plus touché par une soirée comme au début',
    'a le plus besoin de se sentir désiré',
    'a le plus besoin de se sentir désirable',
    'a le plus peur que le désir s’éteigne',
    'a le plus d’inquiétudes sur son physique',
    'a le plus de complexes',
    'est le plus rassuré par un regard',
    'passe le plus de temps à se faire beau ou belle avant un rendez-vous',
    'a le plus envie de se faire désirer',
    'a la tenue la plus sexy du dressing',
    'porte le plus de belles choses sous la tenue de ville',
    'fait le plus tourner la tête dans une soirée',
    'serait le plus fier de montrer l’autre en public',
    'est le plus doué pour réveiller l’autre en douceur',
    'a le plus réveillé l’autre en pleine nuit',
    'a le plus envie d’un câlin quand l’autre dort',
    'a le plus de mal à dormir loin de l’autre',
    'est le plus manquant quand l’autre voyage',
    'dirait le plus “tu me manques” par message',
    'dirait le plus “j’ai envie de toi” par message',
    'ferait le plus de kilomètres pour retrouver l’autre le soir',
    'aurait le plus de mal à tenir sans câlins une semaine',
    'serait le plus fort pour une soirée d’anniversaire inoubliable',
    'organiserait le mieux un weekend de rêve à deux',
    'serait le plus doué pour un défi de séduction',
    'serait le plus joueur pour une soirée sans écran ni distraction',
    'serait le plus ému de réécrire une lettre d’amour',
  ],
}
