import type { Level } from '../engine'

/** « Tu préfères… » — deux options, chacun choisit son camp. */
export const wouldYouRather: Record<Level, [string, string][]> = {
  soft: [
    ['ne plus jamais manger de fromage', 'ne plus jamais manger de chocolat'],
    ['pouvoir voler', 'être invisible'],
    ['vivre sans musique', 'vivre sans films ni séries'],
    ['avoir toujours trop chaud', 'avoir toujours trop froid'],
    ['parler toutes les langues', 'parler aux animaux'],
    ['revivre ton enfance', 'voir ton futur dans dix ans'],
    ['être toujours en retard de 10 minutes', 'toujours en avance de 30 minutes'],
    ['avoir des spaghettis à la place des cheveux', 'transpirer du sirop d’érable'],
    ['vivre à la mer', 'vivre à la montagne'],
    ['ne plus avoir Internet', 'ne plus avoir d’eau chaude'],
    ['dire tout ce que tu penses', 'ne plus jamais parler'],
    ['être riche et inconnu', 'célèbre et fauché'],
    ['avoir un chat qui parle', 'un chien qui parle'],
    ['manger uniquement des pizzas', 'uniquement des burgers'],
    ['te téléporter', 'remonter le temps'],
    ['éternuer à chaque mensonge', 'avoir le hoquet à chaque compliment'],
    ['vivre dans un film Disney', 'dans un jeu vidéo'],
    ['ne plus jamais dormir', 'ne plus jamais manger'],
    ['connaître la date de ta mort', 'la cause de ta mort'],
    ['être le plus drôle de la soirée', 'le plus beau de la soirée'],
    ['perdre ton téléphone', 'perdre ton portefeuille'],
    ['avoir une mémoire parfaite', 'une intuition parfaite'],
    ['un été sans fin', 'un hiver sans fin'],
    ['avoir des pieds de canard', 'des mains en pinces de crabe'],
    ['chanter au lieu de parler', 'danser au lieu de marcher'],
    // Superpouvoirs
    ['marcher sur l’eau', 'respirer sous l’eau'],
    ['lire dans les pensées', 'contrôler la météo'],
    ['avoir une force surhumaine', 'une vitesse surhumaine'],
    ['arrêter le temps', 'revenir cinq minutes en arrière quand tu veux'],
    ['te transformer en n’importe quel animal', 'en n’importe quel objet'],
    ['guérir toutes les maladies', 'mettre fin à la faim dans le monde'],
    ['voir à travers les murs', 'entendre à des kilomètres'],
    ['faire apparaître le repas de ton choix', 'faire disparaître n’importe quel objet'],
    ['ne jamais tomber malade', 'ne jamais être fatigué'],
    ['voler très lentement', 'courir à 100 km/h'],
    ['te dédoubler une fois par jour', 'te téléporter deux fois par jour'],
    ['parler aux plantes', 'parler aux objets'],
    ['avoir une vue de faucon', 'un odorat de chien'],
    ['être immunisé contre l’ennui', 'immunisé contre la faim'],
    // Nourriture
    ['manger des pâtes tous les jours', 'du riz tous les jours'],
    ['manger sucré à tous les repas', 'salé à tous les repas'],
    ['des frites à volonté', 'du chocolat à volonté'],
    ['ne plus jamais manger de pain', 'ne plus jamais manger de pâtes'],
    ['un petit-déj d’hôtel tous les jours', 'un dîner gastronomique une fois par an'],
    ['manger des insectes grillés', 'des escargots à l’ail'],
    ['ne manger que chaud', 'ne manger que froid'],
    ['goûter tous les fromages du monde', 'tous les chocolats du monde'],
    ['cuisiner comme un chef étoilé', 'pâtisser comme un champion'],
    ['ne plus jamais utiliser ton four', 'ne plus jamais utiliser ton micro-ondes'],
    ['des pizzas à l’ananas pour toujours', 'des pizzas sans fromage pour toujours'],
    ['du ketchup sur tout', 'de la mayonnaise sur tout'],
    ['manger toujours debout', 'toujours assis par terre'],
    ['un buffet à volonté chaque midi', 'un resto étoilé chaque mois'],
    ['ne boire que de l’eau', 'ne boire que du soda'],
    ['une glace menthe-chocolat tous les jours', 'une glace caramel tous les jours'],
    // Voyages
    ['faire le tour du monde en voilier', 'en van aménagé'],
    ['visiter Tokyo', 'visiter New York'],
    ['une semaine au Sahara', 'une semaine au pôle Nord'],
    ['dormir sous tente en vacances', 'à l’hôtel cinq étoiles'],
    ['partir à l’aventure sans plan', 'tout planifier à la minute près'],
    ['ne plus jamais prendre l’avion', 'ne plus jamais prendre le train'],
    ['partir dans la jungle amazonienne', 'en Antarctique'],
    ['voir une aurore boréale', 'plonger parmi les baleines'],
    ['une croisière de trois mois', 'un road trip de trois mois'],
    ['habiter à l’étranger pour toujours', 'ne jamais quitter ton pays'],
    ['avoir des billets d’avion gratuits à vie', 'des hôtels gratuits à vie'],
    ['explorer l’espace', 'explorer le fond des océans'],
    // Travail et argent
    ['gagner un million tout de suite', 'recevoir 5 000 € par mois à vie'],
    ['un travail passionnant mal payé', 'un travail ennuyeux très bien payé'],
    ['travailler quatre jours par semaine', 'dix mois par an'],
    ['être ton propre patron', 'avoir un patron génial'],
    ['ne plus jamais aller en réunion', 'ne plus jamais recevoir d’e-mails'],
    ['travailler de chez toi', 'dans un bureau avec vue sur la mer'],
    ['gagner au loto une fois', 'ne jamais payer ton loyer'],
    ['faire un métier en pleine nature', 'un métier dans l’espace'],
    ['une promotion sans augmentation', 'une augmentation sans promotion'],
    ['créer ta propre entreprise', 'être salarié avec la sécurité'],
    ['deux heures de trajet vers un super boulot', 'un boulot moyen à cinq minutes'],
    ['être expert dans un seul domaine', 'bon dans tous les domaines'],
    ['finir le travail à 15 h tous les jours', 'faire la grasse matinée tous les jours'],
    ['dépenser sans compter pendant un mois', 'ne rien dépenser pendant un an'],
    ['avoir 10 000 € à dépenser pour toi', 'les offrir à un proche'],
    // Famille et amis
    ['passer Noël avec toute ta famille', 'avec tous tes amis'],
    ['avoir un grand frère', 'une petite sœur'],
    ['un meilleur ami très drôle', 'un meilleur ami très sage'],
    ['vivre avec tes parents toute ta vie', 'à 10 000 km d’eux'],
    ['avoir dix amis proches', 'mille amis moyens'],
    ['un dîner de famille chaque dimanche', 'un week-end ensemble chaque mois'],
    ['organiser une grande fête surprise', 'en recevoir une'],
    ['offrir le cadeau parfait', 'recevoir le cadeau parfait'],
    // Technologie
    ['ne plus avoir de réseaux sociaux', 'ne plus avoir de jeux vidéo'],
    ['un robot qui fait ton ménage', 'un robot qui fait tes courses'],
    ['une voiture qui roule toute seule', 'un vélo qui ne crève jamais'],
    ['un téléphone à batterie infinie', 'un ordinateur qui ne plante jamais'],
    ['vivre sans ordinateur', 'vivre sans téléphone'],
    ['une IA qui répond à tout', 'un ami qui dit toujours la vérité'],
    ['du Wi-Fi partout mais lent', 'du Wi-Fi seulement chez toi mais ultra rapide'],
    ['jouer en réalité virtuelle', 'jouer à un jeu de plateau géant'],
    ['un casque qui annule tous les bruits', 'des lunettes qui traduisent tout'],
    ['un smartphone indestructible', 'une voiture indestructible'],
    // Absurdes
    ['avoir un nez de clown à vie', 'des chaussures de clown à vie'],
    ['avoir des bras de deux mètres', 'des jambes de deux mètres'],
    ['éternuer des confettis', 'roter des bulles de savon'],
    ['n’avoir que des chaussettes dépareillées', 'que des stylos presque vides'],
    ['avoir un perroquet qui répète tout', 'un chat qui te juge en silence'],
    ['avoir une voix de dessin animé', 'une voix de robot'],
    ['marcher comme un canard toute la journée', 'parler en rimes toute la journée'],
    ['avoir des cheveux qui changent de couleur', 'des ongles qui brillent dans le noir'],
    ['être suivi par une fanfare', 'être suivi par un mime'],
    ['avoir une musique d’ambiance à chaque entrée', 'des rires enregistrés à chaque blague'],
    ['avoir un pigeon comme animal de compagnie', 'une poule dans ton salon'],
    ['vivre dans une maison en forme de chaussure', 'en forme d’ananas'],
    ['être appelé « Votre Altesse »', 'être applaudi chaque fois que tu entres'],
    ['avoir un fou rire permanent', 'un hoquet permanent'],
    ['ne parler qu’en chuchotant', 'ne parler qu’en criant'],
    ['avoir des pieds qui sentent la rose', 'des mains qui sentent le chocolat'],
    ['porter un costume de dinosaure une semaine', 'un costume de hot-dog un mois'],
    ['faire tes courses en rollers', 'en trottinette électrique'],
    // Éthique légère
    ['dire une petite vérité qui blesse', 'un petit mensonge qui rassure'],
    ['rendre un portefeuille avec 500 € dedans', 'le garder en secret'],
    ['sauver un chat', 'sauver cinq poissons rouges'],
    ['donner la moitié de ton salaire', 'faire du bénévolat un jour par semaine'],
    ['être sincère et maladroit', 'poli mais hypocrite'],
    ['gagner en trichant', 'perdre en jouant honnêtement'],
    ['avoir toujours raison', 'être aimé de tout le monde'],
    ['être célèbre pour une erreur', 'oublié pour une grande réussite'],
    // Confort
    ['un canapé ultra confortable', 'un lit ultra confortable'],
    ['des vacances de luxe en dormant mal', 'un camping en dormant comme un bébé'],
    ['une douche toujours à la bonne température', 'des chaussures toujours à ta pointure'],
    ['avoir toujours les pieds au chaud', 'toujours un bon oreiller'],
    ['vivre avec la clim', 'vivre avec un feu de cheminée'],
    ['un plaid toujours à portée de main', 'une tasse de thé toujours chaude'],
    ['ne jamais avoir de courbatures', 'ne jamais avoir mal au dos'],
    ['faire la sieste tous les jours', 'dormir quatre heures par nuit mais en forme'],
    ['un dressing de rêve', 'une cuisine de rêve'],
    ['un petit appartement en plein centre', 'une grande maison loin de tout'],
    // Célébrité
    ['être connu dans le monde entier', 'adoré dans ta ville seulement'],
    ['avoir un million d’abonnés', 'un seul fan absolument fidèle'],
    ['être le héros d’un film', 'le personnage d’un jeu vidéo'],
    ['avoir ta statue sur la place du village', 'une rue à ton nom'],
    ['écrire un livre à succès', 'composer un tube mondial'],
    ['jouer dans un film à gros budget', 'gagner un concours de cuisine télévisé'],
    ['être célèbre grâce à ton talent', 'grâce à une vidéo virale'],
    // Animaux
    ['un chien qui te comprend', 'un chat qui t’obéit'],
    ['nager avec des dauphins', 'caresser un panda'],
    ['te réveiller avec le chant d’un coq', 'avec les léchouilles d’un chien'],
    ['adopter un chien de refuge', 'un chat de refuge'],
    ['avoir une ferme avec des alpagas', 'un refuge pour hérissons'],
    ['élever des abeilles', 'élever des poules'],
    ['faire un safari en Afrique', 'plonger avec des requins-baleines'],
    ['avoir une tortue qui vit 200 ans', 'un perroquet qui parle comme toi'],
    ['avoir un chat grand comme un tigre', 'un tigre petit comme un chat'],
    // Sport
    ['gagner la Coupe du monde', 'gagner Roland-Garros'],
    ['courir un marathon', 'grimper l’Everest'],
    ['être excellent en natation', 'excellent en escalade'],
    ['sauter comme un kangourou', 'nager comme un dauphin'],
    ['faire du sport tous les matins', 'te balader tous les soirs'],
    ['faire du parachute', 'du saut à l’élastique'],
    ['avoir les abdos d’un athlète', 'l’endurance d’un marathonien'],
    ['être très flexible', 'très costaud'],
    ['courir dix kilomètres sous la pluie', 'nager dans de l’eau glacée'],
    // Divers
    ['vivre dans un château', 'vivre dans un phare'],
    ['apprendre le piano en un jour', 'apprendre une langue en une semaine'],
    ['ne jamais perdre tes clés', 'ne jamais perdre ton chargeur'],
    ['voir un film sans le son', 'écouter un film sans l’image'],
    ['avoir tous les livres du monde', 'toutes les chansons du monde'],
    ['un printemps éternel', 'les quatre saisons tous les ans'],
    ['voir un coucher de soleil chaque soir', 'un lever de soleil chaque matin'],
    ['lire un livre par semaine', 'regarder un film par jour'],
    ['avoir un jardin potager', 'une terrasse sur les toits'],
    ['te perdre dans une forêt', 'dans une grande ville inconnue'],
    ['une mémoire des visages', 'une mémoire des prénoms'],
    ['sentir toujours le pain chaud', 'toujours la mer'],
    ['faire un puzzle de 5 000 pièces', 'construire un Lego de 5 000 pièces'],
    ['jouer aux échecs contre un robot', 'aux cartes contre un magicien'],
    ['faire la queue une heure par jour', 'faire le ménage une heure par jour'],
    ['inventer un objet du quotidien', 'lancer une mode mondiale'],
  ],
  spicy: [
    ['lire les messages de ton ex', 'que ton ex lise les tiens'],
    ['embrasser quelqu’un ici', 'boire un verre de sauce piquante'],
    ['un date parfait sans lendemain', 'une relation moyenne qui dure'],
    ['que ton historique de recherche soit public', 'que tes messages privés le soient'],
    ['sortir avec ton boss', 'avec ton ou ta meilleure amie'],
    ['ne plus jamais boire d’alcool', 'ne plus jamais faire la fête'],
    ['que ta mère voie tes photos de soirée', 'que ton boss les voie'],
    ['un partenaire jaloux', 'un partenaire qui s’en fiche totalement'],
    ['être ghosté', 'ghoster quelqu’un que tu aimes bien'],
    ['te réveiller à côté de ton ex', 'à côté d’un inconnu'],
    ['un premier date au resto chic', 'un premier date au bowling'],
    ['savoir ce que tout le monde pense de toi', 'que personne ne pense à toi'],
    ['rester ami avec tous tes ex', 'ne plus jamais les revoir'],
    ['raconter ta pire honte', 'lire ton dernier message à voix haute'],
    ['un crush célèbre inaccessible', 'un crush réciproque mais compliqué'],
    ['te marier demain', 'ne jamais te marier'],
    ['danser seul sur la table', 'chanter seul au micro'],
    ['avoir mauvaise haleine au premier bisou', 'le hoquet pendant tout le date'],
    ['que tes potes choisissent ton partenaire', 'que tes parents le choisissent'],
    ['rompre par message vocal', 'par lettre manuscrite'],
    ['faire la fête jusqu’à 6 h', 'rentrer à minuit et être en forme demain'],
    ['partager ton lit avec un ronfleur', 'avec quelqu’un qui prend toute la couette'],
    ['envoyer un message bourré à ton ex', 'à ton boss'],
    ['tomber amoureux en vacances', 'au travail'],
    ['avouer un crush secret', 'garder le secret pour toujours'],
    // Exs et ruptures
    ['que ton ex te recontacte à 3 h du matin', 'que ton crush te laisse en vu'],
    ['te faire larguer par SMS', 'te faire larguer en public'],
    ['sortir avec le meilleur ami de ton ex', 'avec l’ex de ton meilleur ami'],
    ['dire « je t’aime » en premier', 'l’entendre en premier'],
    ['te remettre avec ton ex', 'tomber sur un parfait inconnu'],
    ['inviter ton ex à ton mariage', 'ne pas inviter ton meilleur ami'],
    ['voir ton ex heureux avec ton ami', 'voir ton ami malheureux avec ton ex'],
    ['que ton ex rencontre ta famille', 'que ta famille rencontre ton crush'],
    ['aller en vacances avec ton ex', 'avec la famille de ton partenaire'],
    ['assister à un mariage seul', 'avec ton ex'],
    ['faire un slow avec ton ex', 'un slow avec ton boss'],
    ['liker une vieille photo de ton ex', 'répondre par erreur à sa story'],
    ['découvrir que ton ex te stalke encore', 'que tu stalkes encore ton ex'],
    ['être le plan B de quelqu’un', 'avoir un plan B pour tout le monde'],
    ['recevoir une lettre d’excuses de ton ex', 'un énorme bouquet de ton ex'],
    ['un ex qui te hait', 'un ex qui t’aime encore'],
    // Dates et couple
    ['un date à l’aveugle', 'un date organisé par une appli'],
    ['un date qui parle de son ex toute la soirée', 'qui regarde son téléphone toute la soirée'],
    ['un date qui arrive 30 min en retard', 'un date qui arrive 30 min en avance'],
    ['payer pour deux au premier date', 'séparer l’addition au centime'],
    ['oublier le prénom de ton date', 'qu’il oublie le tien'],
    ['un partenaire trop collant', 'un partenaire trop distant'],
    ['un partenaire qui oublie ton anniversaire', 'qui oublie votre anniversaire de couple'],
    ['rencontrer ses parents dès le premier mois', 'seulement après deux ans'],
    ['partager ton compte en banque', 'le code de ton téléphone'],
    ['un couple qui se dispute beaucoup mais passionné', 'un couple calme sans étincelle'],
    ['un partenaire drôle mais sans ambition', 'un partenaire ambitieux mais sans humour'],
    ['faire le premier pas', 'attendre qu’on le fasse'],
    ['te faire poser un lapin', 'poser un lapin à quelqu’un que tu apprécies'],
    ['avoir un crush sur un collègue', 'sur ton voisin'],
    ['être célibataire pour toujours', 'en couple avec quelqu’un qui ne te convient pas'],
    ['dire non à un mariage', 'dire oui à quelqu’un que tu aimes à moitié'],
    ['une vie de couple sans dispute', 'une vie de couple sans silence gênant'],
    ['vivre ensemble au bout d’un mois', 'ne jamais vivre ensemble'],
    ['un partenaire qui ne rit pas à tes blagues', 'qui rit à toutes tes blagues, même nulles'],
    ['un amour de jeunesse retrouvé', 'un amour inattendu au travail'],
    ['que ton partenaire garde ses ex en amis', 'qu’il les efface tous'],
    ['un partenaire qui ne cuisine jamais', 'qui ne range jamais'],
    ['un partenaire qui chante faux sous la douche', 'qui parle seul dans la voiture'],
    ['un couple fusionnel', 'un couple qui garde chacun sa vie'],
    // Crush et séduction
    ['te faire draguer par un collègue', 'par le patron de ton ex'],
    ['te faire flirter par un ami de ton ex', 'par le frère de ton ex'],
    ['embrasser ton meilleur ami', 'embrasser la meilleure amie de ton ex'],
    ['inviter ton crush à dîner', 'l’inviter à une soirée chez toi'],
    ['dire ce que tu ressens à ton crush', 'le dire à tous les autres'],
    ['un baiser sous la pluie', 'un baiser sur la plage'],
    ['qu’on découvre ton crush pour quelqu’un d’ici', 'que ce quelqu’un le devine'],
    ['être la personne la plus mystérieuse de la soirée', 'la plus marrante'],
    ['passer une soirée avec ton ex et ton crush', 'avec ton boss et tes parents'],
    ['draguer au bar', 'te faire draguer au bar'],
    ['lire le journal intime de ton crush', 'lui laisser lire le tien'],
    ['un crush qui t’ignore', 'un crush qui te colle'],
    ['flirter à la machine à café', 'flirter à la salle de sport'],
    ['recevoir un compliment inattendu d’un inconnu', 'en faire un à ton crush'],
    ['envoyer « je t’aime » au mauvais contact', 'liker une vieille photo de ton crush'],
    // Alcool et soirées
    ['avoir la gueule de bois pendant un entretien', 'pendant un mariage'],
    ['finir la soirée sur le canapé d’un inconnu', 'dans un taxi à 80 €'],
    ['perdre ton téléphone en soirée', 'perdre tes clés en soirée'],
    ['être le plus bourré de la soirée', 'le plus sobre de la soirée'],
    ['faire un karaoké devant tes collègues', 'un discours ivre à un mariage'],
    ['rentrer à pied à 4 h du matin', 'dormir chez quelqu’un que tu connais à peine'],
    ['t’endormir en pleine soirée', 'être le dernier debout'],
    ['avaler une cuillère de moutarde', 'boire cul sec un shot de vinaigre'],
    ['participer à un jeu à boire', 'être le chauffeur de la soirée'],
    ['boire un cocktail mystère', 'une bière tiède'],
    ['faire tes confidences ivre', 'les faire à jeun'],
    ['te réveiller sans souvenirs de la veille', 'avec trop de souvenirs'],
    ['une soirée mémorable et risquée', 'une soirée calme et agréable'],
    ['une soirée déguisée', 'une soirée pyjama'],
    ['danser sur la table devant tes amis', 'chanter faux devant des inconnus'],
    ['un after jusqu’à midi', 'un dîner aux chandelles à 19 h'],
    ['animer la soirée', 'te cacher dans la cuisine'],
    ['commander un verre pour tout le bar', 'te faire offrir un verre par un inconnu'],
    ['jouer à action ou vérité', 'jouer à la bouteille'],
    ['une gueule de bois monstrueuse mais une soirée géniale', 'une soirée plate sans lendemain difficile'],
    // Secrets et gêne sociale
    ['qu’on lise ta conversation avec ton meilleur ami', 'qu’on lise ton agenda'],
    ['savoir qui parle dans ton dos', 'savoir qui t’a ghosté'],
    ['qu’un secret de ton meilleur ami soit révélé', 'qu’un des tiens le soit'],
    ['garder un secret qui te ronge', 'le révéler et perdre un ami'],
    ['entendre ce que tes amis disent de toi', 'ce que ton ex dit de toi'],
    ['avouer que tu as menti sur ton CV', 'sur tes hobbies'],
    ['dire la vérité sur ton âge', 'sur ton salaire'],
    ['te faire surprendre en train de chanter seul', 'en train de danser seul'],
    ['envoyer un message à la mauvaise personne', 'répondre à tous par erreur'],
    ['te tromper de prénom devant ton crush', 'devant ton boss'],
    ['pleurer devant tout le monde', 'rire sans pouvoir t’arrêter'],
    ['avoir ton pire cliché affiché au bureau', 'ta pire vidéo en story'],
    ['que ta mère lise tes messages', 'que ton père lise tes recherches'],
    ['dire à ton ami que son partenaire le trompe', 'ne rien dire'],
    ['qu’on voie ton fond d’écran', 'qu’on voie ta liste de lecture'],
    ['croiser ton ex avec ton nouveau date', 'croiser ton boss en pyjama'],
    ['faire un pari gênant avec un ami', 'relever un défi gênant devant le groupe'],
    ['bégayer en déclarant ta flamme', 'oublier ton texte en public'],
    ['entendre ta propre voix enregistrée', 'te voir en vidéo en train de danser'],
    ['te faire pardonner avec un bouquet', 'te faire pardonner avec un grand discours'],
    ['que ton meilleur ami sorte avec ton ex', 'que ta sœur sorte avec ton ex'],
    ['répondre « oui » à tout pendant une soirée', 'répondre « non » à tout'],
    ['organiser une soirée qui tourne mal', 'rater la soirée de ta vie'],
    ['faire un strip-tease raté', 'un tango raté devant tout le monde'],
    // Encore des dilemmes
    ['être le premier à dire « on se met ensemble »', 'attendre que l’autre le dise'],
    ['envoyer un texto à ton ex pour son anniversaire', 'lui envoyer un meme sans rien dire'],
    ['te faire demander en mariage en public', 'te faire demander en privé'],
    ['un crush qui te répond après trois jours', 'un crush qui te répond en trois secondes'],
    ['sortir avec quelqu’un de plus jeune', 'avec quelqu’un de plus âgé'],
    ['un partenaire qui te présente à tout le monde', 'un partenaire qui te garde secret'],
    ['perdre un pari et appeler ton ex', 'perdre un pari et appeler ton boss'],
    ['une relation à distance passionnée', 'une relation proche mais routinière'],
    ['rencontrer l’amour de ta vie à 20 ans', 'le rencontrer à 50 ans'],
    ['savoir combien de personnes ont un crush sur toi', 'savoir qui exactement'],
    ['tomber amoureux de ton colocataire', 'de ton prof de sport'],
    ['partir en week-end avec ton date sans le connaître', 'annuler au dernier moment'],
    ['te réveiller avec un mot doux sur l’oreiller', 'avec le petit-déj au lit'],
    ['danser un slow avec ton crush', 'chanter un duo avec ton crush'],
    ['trinquer avec ton ex', 'trinquer avec ton pire ennemi'],
    ['recevoir un bouquet anonyme', 'une lettre d’amour anonyme'],
    ['te faire offrir un verre par ton crush', 'lui en offrir un'],
    ['que ton crush voie ton ancienne photo de profil', 'ton vieux skyblog'],
    ['faire la bise à ton ex en soirée', 'l’éviter toute la soirée'],
    ['accompagner ton ami à son date', 'écrire ses messages à sa place'],
    ['rire à une blague nulle de ton date', 'lui dire franchement qu’elle est nulle'],
    ['un baiser volé pendant la danse', 'un baiser volé sur le balcon'],
    ['raconter ta pire rupture', 'raconter ton plus gros râteau'],
    ['réciter un poème à ton crush', 'chanter à sa porte'],
    ['organiser un dîner pour ton crush et son ex', 'pour ton ex et son crush'],
    ['révéler que tu as un faible pour quelqu’un ici', 'que tu en avais un'],
    ['vivre une histoire secrète pendant un an', 'une histoire publique de trois mois'],
    ['partager la facture de resto avec ton ex', 'avec ton boss'],
    ['une soirée trop arrosée mais géniale', 'une soirée sobre mais ennuyeuse'],
    ['voir ton ex pleurer à ton mariage', 'rire à ton mariage'],
    ['dire à ton boss ce que tu penses de lui', 'à ton ex ce que tu penses d’elle'],
    ['tomber en public devant ton crush', 'renverser un verre sur lui'],
    ['te marier à Las Vegas sur un coup de tête', 'organiser un mariage dans un château'],
    ['envoyer un message vocal de 5 minutes', 'écouter un message vocal de 5 minutes'],
    ['être le meilleur ami du couple', 'être le témoin du couple'],
    ['offrir un cadeau raté à ton date', 'recevoir un cadeau raté de ton date'],
    ['draguer maladroitement un inconnu', 'te faire draguer maladroitement par un inconnu'],
    ['demander le numéro de ton crush', 'te le faire demander'],
  ],
  hot: [
    ['faire l’amour sans s’embrasser', 's’embrasser sans faire l’amour'],
    ['toujours la lumière allumée', 'toujours dans le noir'],
    ['un plan à trois', 'un strip-tease devant tes amis'],
    ['que ton partenaire lise tes fantasmes', 'lire les siens'],
    ['tout le temps au-dessus', 'tout le temps en dessous'],
    ['une nuit avec ton crush célèbre', 'une semaine avec ton crush réel'],
    ['dominer', 'être dominé'],
    ['un câlin langoureux de deux heures', 'un moment passionné de dix minutes'],
    ['le faire dans un ascenseur', 'dans une cabine d’essayage'],
    ['envoyer une photo coquine à la mauvaise personne', 'qu’on t’entende à travers le mur'],
    ['le meilleur coup de ta vie avec un ex', 'un très bon coup avec un inconnu'],
    ['que ton partenaire soit trop bavard au lit', 'totalement silencieux'],
    ['tester les menottes', 'tester le bandeau sur les yeux'],
    ['le faire à la plage', 'dans la forêt'],
    ['un massage sensuel', 'un strip-tease rien que pour toi'],
    ['que tes voisins t’entendent', 'que tes colocs te surprennent'],
    ['le faire tous les jours pendant un mois', 'une seule fois par mois mais incroyable'],
    ['jouer un jeu de rôle', 'tourner une sextape que personne ne verra'],
    ['découvrir les fantasmes de quelqu’un ici', 'que quelqu’un ici découvre les tiens'],
    ['une nuit avec la personne la plus douée de la pièce', 'avec la plus attirante'],
    ['être surpris par tes parents', 'par les parents de ton partenaire'],
    ['un soir dans un club libertin', 'un soir dans un camp naturiste'],
    ['des préliminaires parfaits', 'un final parfait'],
    ['faire l’amour sous la douche', 'dans un jacuzzi'],
    ['dire un fantasme à voix haute', 'en réaliser un ce mois-ci'],
    // Lieux
    ['le faire sur un balcon', 'dans une voiture'],
    ['dans un train de nuit', 'dans un avion'],
    ['dans une cuisine en pleine nuit', 'sur le canapé du salon'],
    ['dans une piscine la nuit', 'sous la pluie dans un jardin'],
    ['sur un toit avec vue sur la ville', 'dans une tente sous les étoiles'],
    ['dans une chambre d’hôtel de luxe', 'dans une cabane perdue dans les bois'],
    ['dans un sauna', 'dans un hammam'],
    ['dans un cinéma presque vide', 'dans un parking souterrain'],
    ['en pleine nuit à la plage', 'au lever du soleil à la campagne'],
    ['chez un ami pendant sa soirée', 'dans la chambre d’amis chez tes beaux-parents'],
    ['dans une cave à vin', 'dans un champ de lavande'],
    // Rôles et jeux
    ['jouer le patron', 'jouer l’employé'],
    ['te déguiser en infirmier ou infirmière', 'en pompier ou en agent secret'],
    ['jouer le séducteur mystérieux', 'jouer l’inconnu rencontré dans un bar'],
    ['un strip-poker', 'une partie de cache-cache coquine'],
    ['des cartes à gratter coquines', 'un jeu de dés coquin'],
    ['un jeu de rôle improvisé', 'un jeu de rôle préparé à l’avance'],
    ['te faire attacher avec une écharpe', 'attacher ton partenaire avec une écharpe'],
    ['un défi coquin chaque jour pendant une semaine', 'un seul défi coquin extrême'],
    ['un jeu de gages avec ton partenaire', 'un jeu de questions osées'],
    ['une chasse au trésor coquine à la maison', 'un rendez-vous mystère surprise'],
    ['jouer le rôle de l’étranger charmant', 'celui du voisin trop gentil'],
    // Ambiance et préliminaires
    ['un massage à l’huile', 'un bain à deux aux chandelles'],
    ['des bougies parfumées', 'une playlist de rêve'],
    ['de la lingerie fine', 'la chemise de ton partenaire'],
    ['des glaçons sur la peau', 'du chocolat fondu sur la peau'],
    ['des plumes', 'des baisers dans le cou'],
    ['un parfum qui te rend fou', 'un regard qui te rend fou'],
    ['une lumière tamisée', 'une lumière de bougies'],
    ['recevoir un massage du dos', 'en donner un à ton partenaire'],
    ['des caresses lentes pendant une heure', 'un baiser fougueux de dix minutes'],
    ['une ambiance jazz', 'une ambiance rock'],
    ['des draps en soie', 'des draps en coton tout frais'],
    ['un bain moussant à deux', 'une douche à deux'],
    ['te faire déshabiller lentement', 'déshabiller lentement ton partenaire'],
    ['un baiser dans le cou', 'un baiser sur le ventre'],
    ['danser un slow collé-serré', 'danser un tango sensuel'],
    ['un dîner aux chandelles qui finit bien', 'un petit-déj au lit qui finit bien'],
    // Fréquence et timing
    ['le matin au réveil', 'tard le soir'],
    ['une nuit torride par semaine', 'un petit câlin coquin chaque jour'],
    ['des moments spontanés', 'des moments planifiés'],
    ['dormir nu toute l’année', 'en pyjama toute l’année'],
    ['une sieste coquine', 'une nuit blanche coquine'],
    ['un week-end entier au lit', 'un week-end au spa à deux'],
    ['une nuit passionnée suivie d’une semaine de pause', 'un peu de passion chaque soir'],
    ['la passion des débuts pour toujours', 'la complicité des vieux couples'],
    ['une passion éclair', 'une passion qui dure'],
    // Communication
    ['des mots doux à l’oreille', 'des mots crus à l’oreille'],
    ['dire tout ce que tu aimes au lit', 'deviner ce que ton partenaire aime'],
    ['un partenaire qui murmure', 'un partenaire qui gémit fort'],
    ['demander ce que tu veux', 'qu’on le devine'],
    ['dire « stop » en riant', 'dire « encore » en rougissant'],
    ['parler pendant', 'rester silencieux pendant'],
    ['des sextos toute la journée', 'une soirée sans un mot'],
    ['recevoir un message coquin au travail', 'en envoyer un en réunion'],
    ['un partenaire qui te complimente sans arrêt', 'qui te regarde sans rien dire'],
    ['avouer une expérience gênante', 'garder ton passé secret'],
    // Fantasmes et curiosité
    ['un fantasme réalisé et raté', 'un fantasme jamais tenté'],
    ['découvrir un jouet coquin à deux', 'un livre érotique à lire à voix haute'],
    ['te filmer en cachette', 'te faire filmer en cachette'],
    ['un miroir au-dessus du lit', 'un miroir en face du lit'],
    ['un fantasme jamais avoué', 'un fantasme déjà vécu'],
    ['une nuit avec un acteur de cinéma', 'une nuit avec une chanteuse'],
    ['une expérience exotique en vacances', 'une aventure d’un soir en voyage'],
    ['une soirée coquine entre amis', 'une soirée coquine à deux'],
    ['recevoir une surprise coquine au bureau', 'à la maison'],
    ['regarder un film érotique à deux', 'lire une histoire érotique ensemble'],
    ['un week-end libertin', 'un week-end romantique'],
    ['une nuit sans limites', 'une nuit avec des règles très précises'],
    ['inventer un fantasme avec ton partenaire', 'réaliser le sien'],
    // Séduction et premier soir
    ['coucher le premier soir', 'attendre trois mois'],
    ['un baiser fougueux en public', 'une caresse discrète sous la table'],
    ['te faire séduire', 'séduire'],
    ['séduire par ton regard', 'séduire par ta voix'],
    ['un premier baiser très tendre', 'un premier baiser fougueux'],
    ['un partenaire très expérimenté', 'un partenaire tendre et timide'],
    ['une aventure d’un soir', 'une longue histoire passionnée'],
    ['un plan cul sans lendemain', 'un ami avec des avantages'],
    ['séduire le plus beau de la soirée', 'séduire le plus drôle'],
    ['être séduit par un compliment', 'être séduit par un geste'],
    ['un tatouage coquin caché', 'un piercing caché'],
    ['te réveiller en l’embrassant', 'te réveiller en préparant le petit-déj'],
    ['un partenaire qui prend les devants', 'un partenaire qui attend ton signal'],
    // Gêne et humour
    ['avoir un fou rire en plein moment', 'avoir une crampe en plein moment'],
    ['que ton chien entre en plein moment', 'que ton alarme sonne en plein moment'],
    ['rougir jusqu’aux oreilles', 'avoir la voix qui tremble'],
    ['des chatouilles incontrôlables', 'un hoquet incontrôlable'],
    ['te tromper de prénom au pire moment', 'dire « merci » au pire moment'],
    ['que ton partenaire ronfle juste après', 'qu’il s’endorme juste après'],
    ['que la couette tombe', 'que le lit grince'],
    ['entendre ton voisin à travers le mur', 'que ton voisin t’entende'],
    ['découvrir que ton partenaire a un fantasme étrange', 'que le tien le surprend'],
    ['une nuit géniale mais un lendemain gênant', 'une nuit moyenne mais un lendemain tendre'],
    ['une nuit passionnée avec un partenaire timide', 'une nuit maladroite avec un partenaire audacieux'],
    ['te réveiller avec un message coquin de ton ex', 'avec un message coquin de ton crush'],
    // Encore des dilemmes
    ['un dîner romantique avec un massage', 'une soirée dansante avec un baiser'],
    ['un coup de foudre passionné', 'une longue amitié qui devient plus'],
    ['un partenaire qui t’emmène en week-end surprise', 'qui prépare la soirée à la maison'],
    ['une surprise coquine à l’aveugle', 'une surprise coquine en pleine lumière'],
    ['une nuit de tendresse', 'une nuit de passion débridée'],
    ['un partenaire qui sent bon', 'un partenaire qui embrasse très bien'],
    ['un baiser dans la nuque', 'un baiser sur la main'],
    ['un partenaire sportif aux muscles saillants', 'un partenaire intellectuel au regard profond'],
    ['faire le premier pas', 'te faire entraîner par ton partenaire'],
    ['une danse lascive devant toi', 'une chanson murmurée à l’oreille'],
    ['un baiser qui dure une minute entière', 'dix petits baisers volés'],
    ['te déshabiller toi-même devant ton partenaire', 'te faire déshabiller du regard'],
    ['un partenaire avec une voix grave', 'un partenaire avec un sourire irrésistible'],
    ['un fantasme dans une bibliothèque', 'un fantasme dans un bureau après la fermeture'],
    ['une nuit à l’hôtel avec ton ex', 'une nuit à l’hôtel avec un inconnu'],
    ['une lettre d’amour très osée', 'une vidéo d’amour très osée'],
    ['un week-end très coquin avec ton partenaire', 'un week-end très romantique avec un inconnu'],
    ['tester un jouet coquin ce soir', 'attendre l’occasion parfaite'],
    ['avoir un partenaire qui mène la danse', 'un partenaire qui suit ton rythme'],
    ['un bal masqué où personne ne se reconnaît', 'un dîner où tout le monde se reconnaît'],
    ['un partenaire qui sait tout de toi', 'un partenaire qui te découvre chaque nuit'],
    ['découvrir une zone sensible que tu ignorais', 'découvrir celle de ton partenaire'],
    ['une dispute qui se termine au lit', 'un câlin qui se termine en dispute'],
    ['un « bonjour » coquin le matin', 'un « bonne nuit » coquin le soir'],
    ['un rendez-vous en tenue de soirée sexy', 'un rendez-vous en tenue décontractée sexy'],
    ['dormir collés toute la nuit', 'dormir chacun de son côté après'],
    ['un partenaire très sensible aux caresses', 'un partenaire très sensible aux mots'],
    ['un soir de pluie sous la couette', 'un soir d’été sur le balcon'],
    ['avoir un mot de passe coquin avec ton partenaire', 'un signe secret en public'],
    ['un baiser volé dans un couloir', 'une main glissée sous la table'],
    ['changer de coiffure pour séduire', 'changer de parfum pour séduire'],
    ['le meilleur souvenir coquin de ta vie', 'le plus drôle'],
    ['une tenue sexy sous un manteau', 'un manteau sexy sur rien'],
    ['être complimenté sur ton corps', 'être complimenté sur ton esprit'],
    ['un baiser inattendu dans une soirée', 'une main qui frôle la tienne'],
    ['avouer ton fantasme préféré à ton crush', 'à ton meilleur ami'],
    ['un partenaire qui adore les surprises coquines', 'un partenaire qui adore les rituels coquins'],
    ['un baiser sur un pont à Paris', 'un baiser sous la neige'],
    ['te faire murmurer des promesses à l’oreille', 'te faire écrire des promesses sur un papier'],
    ['une nuit sous les étoiles à deux', 'une nuit dans un palace à deux'],
    ['un partenaire qui te regarde droit dans les yeux', 'un partenaire qui ferme les yeux'],
    ['te réveiller enlacé', 'te réveiller seul avec un mot doux'],
  ],
}
