import type { Level } from '../engine'

/** « Tu préfères… » — deux options, chacun choisit son camp. */
export const wouldYouRather: Record<Level, [string, string][]> = {
  soft: [
    ['ne plus jamais manger de fromage', 'ne plus jamais manger de chocolat'],
    ['pouvoir voler', 'être invisible'],
    ['vivre sans musique', 'vivre sans films ni séries'],
    ['avoir toujours trop chaud', 'avoir toujours trop froid'],
    ['parler toutes les langues', 'parler aux animaux'],
    ['revivre ton enfance', 'voir ton futur dans dix ans'],
    ['être toujours en retard de 10 minutes', 'toujours en avance de 30 minutes'],
    ['avoir des spaghettis à la place des cheveux', 'transpirer du sirop d’érable'],
    ['vivre à la mer', 'vivre à la montagne'],
    ['ne plus avoir Internet', 'ne plus avoir d’eau chaude'],
    ['dire tout ce que tu penses', 'ne plus jamais parler'],
    ['être riche et inconnu', 'célèbre et fauché'],
    ['avoir un chat qui parle', 'un chien qui parle'],
    ['manger uniquement des pizzas', 'uniquement des burgers'],
    ['te téléporter', 'remonter le temps'],
    ['éternuer à chaque mensonge', 'avoir le hoquet à chaque compliment'],
    ['vivre dans un film Disney', 'dans un jeu vidéo'],
    ['ne plus jamais dormir', 'ne plus jamais manger'],
    ['connaître la date de ta mort', 'la cause de ta mort'],
    ['être le plus drôle de la soirée', 'le plus beau de la soirée'],
    ['perdre ton téléphone', 'perdre ton portefeuille'],
    ['avoir une mémoire parfaite', 'une intuition parfaite'],
    ['un été sans fin', 'un hiver sans fin'],
    ['avoir des pieds de canard', 'des mains en pinces de crabe'],
    ['chanter au lieu de parler', 'danser au lieu de marcher'],
  ],
  spicy: [
    ['lire les messages de ton ex', 'que ton ex lise les tiens'],
    ['embrasser quelqu’un ici', 'boire un verre de sauce piquante'],
    ['un date parfait sans lendemain', 'une relation moyenne qui dure'],
    ['que ton historique de recherche soit public', 'que tes messages privés le soient'],
    ['sortir avec ton boss', 'avec ton ou ta meilleure amie'],
    ['ne plus jamais boire d’alcool', 'ne plus jamais faire la fête'],
    ['que ta mère voie tes photos de soirée', 'que ton boss les voie'],
    ['un partenaire jaloux', 'un partenaire qui s’en fiche totalement'],
    ['être ghosté', 'ghoster quelqu’un que tu aimes bien'],
    ['te réveiller à côté de ton ex', 'à côté d’un inconnu'],
    ['un premier date au resto chic', 'un premier date au bowling'],
    ['savoir ce que tout le monde pense de toi', 'que personne ne pense à toi'],
    ['rester ami avec tous tes ex', 'ne plus jamais les revoir'],
    ['raconter ta pire honte', 'lire ton dernier message à voix haute'],
    ['un crush célèbre inaccessible', 'un crush réciproque mais compliqué'],
    ['te marier demain', 'ne jamais te marier'],
    ['danser seul sur la table', 'chanter seul au micro'],
    ['avoir mauvaise haleine au premier bisou', 'le hoquet pendant tout le date'],
    ['que tes potes choisissent ton partenaire', 'que tes parents le choisissent'],
    ['rompre par message vocal', 'par lettre manuscrite'],
    ['faire la fête jusqu’à 6 h', 'rentrer à minuit et être en forme demain'],
    ['partager ton lit avec un ronfleur', 'avec quelqu’un qui prend toute la couette'],
    ['envoyer un message bourré à ton ex', 'à ton boss'],
    ['tomber amoureux en vacances', 'au travail'],
    ['avouer un crush secret', 'garder le secret pour toujours'],
  ],
  hot: [
    ['faire l’amour sans s’embrasser', 's’embrasser sans faire l’amour'],
    ['toujours la lumière allumée', 'toujours dans le noir'],
    ['un plan à trois', 'un strip-tease devant tes amis'],
    ['que ton partenaire lise tes fantasmes', 'lire les siens'],
    ['tout le temps au-dessus', 'tout le temps en dessous'],
    ['une nuit avec ton crush célèbre', 'une semaine avec ton crush réel'],
    ['dominer', 'être dominé'],
    ['un câlin langoureux de deux heures', 'un moment passionné de dix minutes'],
    ['le faire dans un ascenseur', 'dans une cabine d’essayage'],
    ['envoyer une photo coquine à la mauvaise personne', 'qu’on t’entende à travers le mur'],
    ['le meilleur coup de ta vie avec un ex', 'un très bon coup avec un inconnu'],
    ['que ton partenaire soit trop bavard au lit', 'totalement silencieux'],
    ['tester les menottes', 'tester le bandeau sur les yeux'],
    ['le faire à la plage', 'dans la forêt'],
    ['un massage sensuel', 'un strip-tease rien que pour toi'],
    ['que tes voisins t’entendent', 'que tes colocs te surprennent'],
    ['le faire tous les jours pendant un mois', 'une seule fois par mois mais incroyable'],
    ['jouer un jeu de rôle', 'tourner une sextape que personne ne verra'],
    ['découvrir les fantasmes de quelqu’un ici', 'que quelqu’un ici découvre les tiens'],
    ['une nuit avec la personne la plus douée de la pièce', 'avec la plus attirante'],
    ['être surpris par tes parents', 'par les parents de ton partenaire'],
    ['un soir dans un club libertin', 'un soir dans un camp naturiste'],
    ['des préliminaires parfaits', 'un final parfait'],
    ['faire l’amour sous la douche', 'dans un jacuzzi'],
    ['dire un fantasme à voix haute', 'en réaliser un ce mois-ci'],
  ],
}
