import type { Level } from '../engine'

/** Ni oui ni non — questions pièges qui appellent un « oui » ou un « non » réflexe. */
export const yesNoQuestions: Record<Level, string[]> = {
  soft: [
    // Évidences
    'Tu t’appelles bien comme ça ?',
    'Tu es bien en train de me répondre ?',
    'Tu es un être humain ?',
    'Tu es debout en ce moment ?',
    'Tu n’es pas assis, n’est-ce pas ?',
    'Tu as deux yeux ?',
    'Tu portes des chaussures ?',
    'Tu as un téléphone sur toi ?',
    'Tu n’es pas en train de rêver ?',
    'Tu es bien dans cette pièce ?',
    'Tu entends ma question ?',
    'Tu me comprends ?',
    'Tu parles français ?',
    'Tu ne parles pas français, c’est ça ?',
    'Tu as des cheveux ?',
    'Tu n’as pas de pouces ?',
    'Tu respires en ce moment ?',
    'Tu as des vêtements sur toi ?',
    'Tu connais ton prénom ?',
    'Tu es bien réveillé ?',
    'Tu es en train de jouer ?',
    'Tu as une bouche ?',
    'Tu es bien dans ton assiette ?',
    // Relances et fausses confirmations
    'Tu es sûr ?',
    'Donc c’est non ?',
    'Donc c’est oui ?',
    'Tu en es certain ?',
    'Tu ne veux pas changer de réponse ?',
    'Tu as bien dit ça ?',
    'Tu me confirmes ?',
    'C’est ton dernier mot ?',
    'Tu hésites un peu ?',
    'Tu réfléchis encore ?',
    'Tu es vraiment sûr de toi ?',
    'Tu me disais le contraire tout à l’heure, non ?',
    'Tu n’as pas peur de te tromper ?',
    // Le jeu lui-même
    'Tu trouves que ce jeu est facile ?',
    'Tu vas tenir 60 secondes ?',
    'Tu as le trac ?',
    'Tu es concentré ?',
    'Tu es prêt ?',
    'On commence ?',
    'Tu veux arrêter ?',
    'Tu as déjà joué à ce jeu ?',
    'Tu as chaud ?',
    'Tu as froid ?',
    'Tu as soif ?',
    'Tu es fatigué ?',
    'Tu es de bonne humeur ?',
    'Tu souris là ?',
    'Tu es en train de rire ?',
    'Tu as un doute ?',
    'Tu sens que tu vas craquer ?',
    'Tu n’as pas envie de gagner ?',
    'Tu es mauvais perdant ?',
    'Tu as déjà triché aux cartes ?',
    // Nourriture
    'Tu as déjà mangé une pizza ?',
    'Tu n’aimes pas le chocolat ?',
    'Tu as déjà goûté des escargots ?',
    'Tu manges de la viande ?',
    'Tu ne manges jamais de légumes ?',
    'Tu bois du café le matin ?',
    'Tu n’aimes pas les bonbons ?',
    'Tu as déjà raté une recette ?',
    'Tu préfères le sucré au salé ?',
    'Tu as déjà brûlé des pâtes ?',
    'Tu aimes les fruits de mer ?',
    'Tu as déjà mangé une glace en hiver ?',
    'Tu n’as jamais mangé de fromage ?',
    'Tu as pris un petit-déjeuner aujourd’hui ?',
    'Tu aimes la pizza à l’ananas ?',
    'Tu ne détestes pas les épinards ?',
    'Tu as déjà fait un gâteau ?',
    'Tu as faim là, maintenant ?',
    'Tu bois de l’eau tous les jours ?',
    'Tu as déjà mangé une crêpe ?',
    'Tu aimes les œufs au plat ?',
    'Tu as déjà mis du ketchup sur des pâtes ?',
    'Tu manges du pain avec tout ?',
    'Tu as déjà mangé des sushis ?',
    'Tu as déjà mangé un plat tombé par terre ?',
    'Tu as déjà léché le couvercle d’un yaourt ?',
    'Tu as déjà mangé des céréales au dîner ?',
    'Tu aimes le fromage qui sent fort ?',
    'Tu as déjà mangé plus de dix bonbons d’un coup ?',
    // Voyages et sorties
    'Tu as déjà pris l’avion ?',
    'Tu es déjà allé à l’étranger ?',
    'Tu aimes la plage ?',
    'Tu n’as jamais vu la neige ?',
    'Tu as déjà dormi dans une tente ?',
    'Tu as le permis de conduire ?',
    'Tu sais faire du vélo ?',
    'Tu as déjà raté un train ?',
    'Tu as déjà pris le métro ?',
    'Tu aimes voyager ?',
    'Tu es déjà monté sur un bateau ?',
    'Tu as déjà vu la mer ?',
    'Tu préfères la montagne à la mer ?',
    'Tu t’es déjà perdu en ville ?',
    'Tu as déjà fait du ski ?',
    'Tu as déjà pris un taxi ?',
    'Tu as déjà dormi dans un train ?',
    'Tu as déjà visité un château ?',
    'Tu as déjà fait un tour de manège ?',
    'Tu as déjà gagné un jouet à la fête foraine ?',
    // Animaux
    'Tu as un animal de compagnie ?',
    'Tu as peur des araignées ?',
    'Tu n’as pas peur des serpents ?',
    'Tu aimes les chats ?',
    'Tu préfères les chiens ?',
    'Tu as déjà caressé un cheval ?',
    'Tu as déjà été mordu par un chien ?',
    'Tu as déjà vu un éléphant en vrai ?',
    'Tu as déjà nourri des canards ?',
    'Tu as déjà eu un poisson rouge ?',
    'Tu aimes les oiseaux ?',
    'Tu as déjà parlé à un animal ?',
    // Loisirs, médias, sport
    'Tu as déjà regardé un film d’horreur ?',
    'Tu aimes la musique ?',
    'Tu sais chanter ?',
    'Tu chantes sous la douche ?',
    'Tu joues d’un instrument ?',
    'Tu as déjà joué aux jeux vidéo ?',
    'Tu aimes lire ?',
    'Tu n’as jamais lu un livre en entier ?',
    'Tu as déjà pleuré devant un film ?',
    'Tu regardes des séries ?',
    'Tu as déjà dansé en public ?',
    'Tu sais danser ?',
    'Tu as déjà fait un puzzle ?',
    'Tu as déjà gagné à un jeu de société ?',
    'Tu as déjà joué au Monopoly ?',
    'Tu aimes le sport ?',
    'Tu as déjà fait du sport aujourd’hui ?',
    'Tu as déjà couru un marathon ?',
    'Tu regardes le foot ?',
    'Tu as déjà pris un selfie ?',
    'Tu as un compte sur les réseaux sociaux ?',
    'Tu aimes les films d’animation ?',
    'Tu as déjà écrit un poème ?',
    'Tu écoutes de la musique tous les jours ?',
    'Tu as déjà fait une partie de cartes ?',
    'Tu as déjà joué aux échecs ?',
    'Tu as déjà fait du théâtre ?',
    // Quotidien
    'Tu te lèves tôt ?',
    'Tu es du matin ?',
    'Tu aimes faire la grasse matinée ?',
    'Tu as déjà dormi en cours ?',
    'Tu as déjà oublié ton portable ?',
    'Tu as déjà perdu tes clés ?',
    'Tu fais ton lit tous les matins ?',
    'Tu te brosses les dents deux fois par jour ?',
    'Tu as déjà raté ton réveil ?',
    'Tu es toujours à l’heure ?',
    'Tu as déjà oublié un anniversaire ?',
    'Tu ronfles ?',
    'Tu parles en dormant ?',
    'Tu as déjà fait un cauchemar ?',
    'Tu as déjà marché pieds nus dehors ?',
    'Tu aimes la pluie ?',
    'Tu as déjà dansé sous la pluie ?',
    'Tu as déjà fait un bonhomme de neige ?',
    'Tu as déjà cassé un verre ?',
    'Tu as déjà cassé l’écran de ton téléphone ?',
    'Tu as déjà sauté dans une flaque ?',
    'Tu aimes le silence ?',
    'Tu as déjà fait la sieste ?',
    'Tu as des lunettes ?',
    'Tu as déjà porté un déguisement ?',
    'Tu as déjà gagné quelque chose à un concours ?',
    'Tu as déjà trouvé de l’argent par terre ?',
    'Tu as déjà fait un vœu en soufflant des bougies ?',
    // Surprises
    'Tu es un extraterrestre ?',
    'Tu as déjà parlé à un fantôme ?',
    'Tu es un robot ?',
    'Tu sais voler ?',
    'Tu as une cape de super-héros ?',
    'Tu viens de la Lune ?',
    'Tu as déjà croisé un dinosaure ?',
    'Tu es déjà allé sur Mars ?',
    'Tu es un vampire ?',
    'Tu crois aux fantômes ?',
    'Tu as un jumeau caché ?',
    'Tu es un pirate ?',
    'Tu parles couramment le klingon ?',
    'Tu as déjà vu une licorne ?',
    'Tu as déjà gagné un million ?',
    'Tu es capable de lire dans les pensées ?',
    // Doubles négations
    'Tu ne pourrais pas ne pas aimer les crêpes ?',
    'Tu n’es pas sans savoir nager ?',
    'Tu ne dis pas que tu n’aimes pas le chocolat ?',
    'Ce n’est pas faux que tu aimes dormir, si ?',
    'Tu ne refuserais pas une part de gâteau ?',
    'Tu n’es pas contre un bon dessert ?',
    'Tu ne détestes pas les vacances ?',
    'Tu ne penses pas que tu n’as pas faim ?',
    'Tu n’as pas dit que tu n’aimais pas les chats ?',
    'Tu n’es pas du genre à ne jamais rire ?',
    'Tu n’es jamais en retard, c’est bien ça ?',
    'Tu ne vas pas me dire que tu n’aimes pas la glace ?',
    'Tu ne serais pas contre une pizza maintenant ?',
    'Tu n’es pas quelqu’un qui n’aime pas voyager ?',
    'Tu ne refuses jamais une glace ?',
    'Tu n’es pas fâché avec les maths ?',
    'Tu ne trouves pas que ce n’est pas difficile ?',
    'Tu ne me diras pas que tu n’as jamais menti ?',
  ],
  spicy: [
    // Alcool et soirées
    'Tu as déjà trop bu en soirée ?',
    'Tu as déjà eu la gueule de bois ?',
    'Tu bois de l’alcool ce soir ?',
    'Tu es sobre en ce moment ?',
    'Tu as déjà vomi après une soirée ?',
    'Tu as déjà dansé sur une table ?',
    'Tu as déjà chanté au karaoké en étant bien éméché ?',
    'Tu as déjà oublié une partie de ta soirée ?',
    'Tu as déjà dormi chez quelqu’un sans l’avoir prévu ?',
    'Tu aimes la bière ?',
    'Tu as déjà fait un cul sec ?',
    'Tu as déjà bu un shot de tequila ?',
    'Tu préfères le vin rouge au blanc ?',
    'Tu as déjà mélangé plusieurs alcools ?',
    'Tu trinques toujours en regardant dans les yeux ?',
    'Tu sais préparer un cocktail ?',
    'Tu as déjà bu un verre au petit matin ?',
    'Tu as déjà fini une soirée au kebab ?',
    'Tu as déjà perdu ta veste en soirée ?',
    'Tu as déjà appelé un taxi à 4 heures du matin ?',
    'Tu as déjà dormi sur un canapé qui n’était pas le tien ?',
    'Tu as déjà fait la fête jusqu’au lever du soleil ?',
    'Tu as déjà perdu ton téléphone en soirée ?',
    'Tu as déjà joué à un jeu à boire ?',
    'Tu as déjà gagné un concours de boisson ?',
    'Tu as déjà fait semblant d’être ivre ?',
    'Tu as déjà dit « je ne bois plus jamais » en le pensant ?',
    'Tu as déjà bu une bière chaude par politesse ?',
    'Tu as déjà été le dernier à quitter une soirée ?',
    'Tu as déjà quitté une soirée en cachette ?',
    'Tu as déjà fait ton entrée en soirée complètement déguisé ?',
    'Tu as déjà vomi dans la voiture de quelqu’un ?',
    'Tu as déjà été raccompagné parce que tu avais trop bu ?',
    'Tu as déjà bu un verre à midi un lundi ?',
    'Tu as déjà dit des choses que tu regrettes après quelques verres ?',
    'Tu as déjà fait une promesse folle à minuit ?',
    'Tu as déjà confondu ton verre avec celui d’un autre ?',
    'Tu as déjà fini en pyjama chez un ami après une soirée ?',
    'Tu as déjà pris une photo floue que tu ne comprends pas le lendemain ?',
    // Drague
    'Tu as déjà dragué en soirée ?',
    'Tu as déjà pris un râteau ?',
    'Tu as déjà eu un rencard raté ?',
    'Tu as déjà posé un lapin à quelqu’un ?',
    'Tu as déjà eu un coup de foudre ?',
    'Tu as déjà utilisé une appli de rencontre ?',
    'Tu as déjà ghosté quelqu’un ?',
    'Tu as déjà été ghosté ?',
    'Tu as déjà fait un faux profil ?',
    'Tu as déjà menti sur ta taille sur une appli ?',
    'Tu as déjà donné un faux numéro ?',
    'Tu as déjà fait des yeux doux à quelqu’un ?',
    'Tu as déjà fait le premier pas ?',
    'Tu as déjà craqué pour un accent ?',
    'Tu as déjà craqué pour un sourire ?',
    'Tu as déjà dragué le serveur ou la serveuse ?',
    'Tu as déjà été dragué par un inconnu ?',
    'Tu as déjà demandé un numéro à un inconnu ?',
    'Tu as déjà utilisé une phrase d’accroche ridicule ?',
    'Tu as déjà fait croire que tu étais en couple pour éviter un dragueur ?',
    'Tu as déjà été timide au moment d’aborder quelqu’un ?',
    'Tu as déjà rougi en lisant un message ?',
    'Tu as déjà relu cent fois un message avant de l’envoyer ?',
    'Tu as déjà attendu une réponse en fixant ton téléphone ?',
    'Tu as déjà fait semblant d’être occupé pour te faire désirer ?',
    'Tu as déjà fait un compliment qui est tombé à plat ?',
    'Tu as déjà ri trop fort à une blague pour plaire ?',
    'Tu as déjà fait semblant d’aimer un film pour un rencard ?',
    'Tu as déjà payé l’addition pour impressionner ?',
    'Tu as déjà fait un crush sur un ami ?',
    'Tu as déjà été amoureux d’un ami en secret ?',
    // Couple et ex
    'Tu es en couple en ce moment ?',
    'Tu es célibataire ?',
    'Tu n’es pas célibataire, n’est-ce pas ?',
    'Tu as déjà menti à ton partenaire ?',
    'Tu as déjà été jaloux ?',
    'Tu as déjà fouillé le téléphone de quelqu’un ?',
    'Tu as déjà vécu en couple ?',
    'Tu as déjà dit « je t’aime » trop vite ?',
    'Tu as déjà fait semblant d’aimer un cadeau ?',
    'Tu as déjà laissé quelqu’un en vu ?',
    'Tu as déjà été largué par message ?',
    'Tu as déjà largué quelqu’un par message ?',
    'Tu as déjà pleuré à cause d’un chagrin d’amour ?',
    'Tu as déjà envoyé un message à ton ex ?',
    'Tu es encore en contact avec ton ex ?',
    'Tu as déjà stalké quelqu’un sur Instagram ?',
    'Tu as déjà liké une vieille photo par erreur ?',
    'Tu as déjà gardé les affaires d’un ex ?',
    'Tu as déjà revu un ex en cachette ?',
    'Tu as déjà été ami avec un ex ?',
    'Tu as déjà rencontré les parents de quelqu’un ?',
    'Tu as déjà fait croire que tu aimais la famille de ton partenaire ?',
    'Tu as déjà oublié un anniversaire de couple ?',
    'Tu as déjà fait une scène de jalousie ?',
    'Tu as déjà quitté quelqu’un le jour de son anniversaire ?',
    'Tu as déjà été trompé ?',
    'Tu as déjà soupçonné quelqu’un de te tromper ?',
    'Tu as déjà gardé un secret à ton partenaire ?',
    'Tu as déjà dit « on reste amis » ?',
    'Tu as déjà demandé une pause dans une relation ?',
    'Tu as déjà fait une déclaration d’amour en public ?',
    'Tu as déjà écrit une lettre d’amour ?',
    'Tu as déjà offert des fleurs ?',
    'Tu as déjà passé un week-end en amoureux ?',
    'Tu as déjà fait semblant d’avoir oublié un rendez-vous ?',
    'Tu as déjà changé de style pour plaire à quelqu’un ?',
    'Tu as déjà pensé à ton ex pendant un autre rendez-vous ?',
    'Tu as déjà supprimé des photos après une rupture ?',
    'Tu as déjà gardé un pull qui n’était pas à toi ?',
    // Gênes en tout genre
    'Tu as déjà fait pipi sous la douche ?',
    'Tu as déjà pété en public ?',
    'Tu as déjà vomi en public ?',
    'Tu as déjà confondu deux personnes ?',
    'Tu as déjà répondu « toi aussi » à un serveur qui te souhaitait bon appétit ?',
    'Tu as déjà appelé un professeur « maman » ?',
    'Tu as déjà envoyé un message à la mauvaise personne ?',
    'Tu as déjà publié une photo gênante ?',
    'Tu as déjà fait un discours raté ?',
    'Tu as déjà ri à un enterrement ?',
    'Tu as déjà menti sur ton âge ?',
    'Tu as déjà fait semblant d’être malade ?',
    'Tu as déjà séché un cours ou le boulot ?',
    'Tu as déjà pleuré au travail ?',
    'Tu as déjà dit du mal d’un ami dans son dos ?',
    'Tu as déjà été surpris à dire du mal de quelqu’un ?',
    'Tu as déjà gardé un secret qui te pèse ?',
    'Tu as déjà fait un fou rire incontrôlable au mauvais moment ?',
    'Tu as déjà déchiré ton pantalon en public ?',
    'Tu as déjà oublié le prénom de quelqu’un juste après l’avoir appris ?',
    'Tu as déjà fait semblant de connaître une chanson ?',
    'Tu as déjà ouvert le mauvais cadeau devant tout le monde ?',
    'Tu as déjà fait la bise à quelqu’un qui voulait te serrer la main ?',
    'Tu as déjà salué quelqu’un qui ne te saluait pas ?',
    'Tu as déjà été pris à parler tout seul ?',
    'Tu as déjà fait semblant de téléphoner pour éviter quelqu’un ?',
    'Tu as déjà été bloqué dans un ascenseur ?',
    'Tu as déjà mis un statut passif-agressif sur les réseaux ?',
    'Tu as déjà ri de quelqu’un qui est tombé ?',
    'Tu as déjà dit « j’arrive » en étant encore chez toi ?',
    'Tu as déjà menti pour annuler une soirée ?',
    'Tu as déjà fait une blague qui a tout gâché ?',
    'Tu as déjà été recalé à un entretien d’embauche ?',
    'Tu as déjà écrit « mdr » sans avoir ri ?',
    'Tu as déjà écouté une conversation qui ne te concernait pas ?',
    'Tu as déjà envoyé un message trop vite en répondant à ton patron ?',
    'Tu as déjà été pris la main dans le sac ?',
    'Tu as déjà rejeté une invitation en sachant que tu étais libre ?',
    'Tu as déjà fait un toast ridicule ?',
    'Tu as déjà oublié où tu avais dormi ?',
    'Tu as déjà dansé sur une chanson que tu détestes ?',
    'Tu as déjà fait un pari idiot en soirée ?',
    'Tu as déjà embrassé quelqu’un pour un pari ?',
    'Tu as déjà raté le dernier métro exprès ?',
    'Tu as déjà envoyé un vocal gênant en pleine nuit ?',
    'Tu as déjà prétendu être célibataire alors que non ?',
    // Relances, doubles négations, pièges
    'Tu en es bien sûr ?',
    'Tu ne mens pas là ?',
    'Tu me jures que c’est vrai ?',
    'Tu veux changer ta réponse ?',
    'Donc tu avoues ?',
    'Tu ne dirais pas non à un deuxième verre ?',
    'Tu n’as jamais menti pour éviter une soirée ?',
    'Tu ne regrettes pas d’avoir écrit à ton ex ?',
    'Tu ne peux pas dire que tu n’as jamais été jaloux ?',
    'Tu n’es pas sorti hier soir, c’est ça ?',
    'Tu ne bois jamais d’alcool, c’est bien ça ?',
    'Tu n’es pas du genre à rester jusqu’à la fin d’une soirée ?',
    'Tu ne refuserais pas un dernier verre pour la route ?',
    'Tu n’as jamais envoyé de message gênant, je me trompe ?',
    'Tu ne serais pas contre un petit shot ?',
    'Tu n’as jamais fait semblant d’aimer une soirée ?',
    'Tu ne nous caches rien sur ton ex, n’est-ce pas ?',
    'Tu n’es pas déjà tombé amoureux en soirée ?',
    'Tu ne serais pas un peu jaloux ?',
    'Tu n’as pas déjà eu un crush sur quelqu’un d’ici ?',
    'Tu ne me dis pas que tu n’as jamais rien regretté ?',
    'Tu n’es pas sans histoire sentimentale, si ?',
  ],
  hot: [
    // Séduction et baisers
    'Tu as déjà fait un strip-tease ?',
    'Tu as déjà envoyé une photo sexy ?',
    'Tu as déjà reçu un message coquin ?',
    'Tu as déjà embrassé quelqu’un le premier soir ?',
    'Tu as déjà passé la nuit chez un inconnu ?',
    'Tu as déjà eu un plan d’un soir ?',
    'Tu as déjà eu un ami avec bénéfices ?',
    'Tu as déjà flirté avec un collègue ou une collègue ?',
    'Tu as déjà fantasmé sur une célébrité ?',
    'Tu as déjà dormi nu ?',
    'Tu as déjà pris une douche à deux ?',
    'Tu as déjà bronzé nu ?',
    'Tu as déjà fait du naturisme ?',
    'Tu as déjà eu un fou rire au mauvais moment au lit ?',
    'Tu as déjà fait un massage sensuel ?',
    'Tu as déjà joué à un jeu coquin ?',
    'Tu as déjà porté de la lingerie coquine ?',
    'Tu as déjà fait un jeu de rôle déguisé ?',
    'Tu as déjà utilisé des menottes en peluche ?',
    'Tu as déjà été surpris en plein câlin ?',
    'Tu as déjà fait l’amour dans un endroit insolite ?',
    'Tu as déjà fait l’amour en vacances ?',
    'Tu as déjà fait l’amour dans une voiture ?',
    'Tu as déjà eu un suçon ?',
    'Tu as déjà caché un suçon ?',
    'Tu as déjà embrassé deux personnes dans la même soirée ?',
    'Tu as déjà eu un coup de cœur pour un ami d’ami ?',
    'Tu as déjà joué à action ou vérité avec des gages coquins ?',
    'Tu as déjà fait des câlins sous la couette un dimanche ?',
    'Tu es déjà tombé amoureux en une soirée ?',
    'Tu as déjà eu un coup de chaud en regardant une série ?',
    'Tu as déjà regardé un film un peu osé ?',
    'Tu as déjà lu un roman érotique ?',
    'Tu as déjà tenté un baiser dans un ascenseur ?',
    'Tu as déjà embrassé quelqu’un sous la pluie ?',
    'Tu as déjà fait un baiser langoureux en public ?',
    'Tu as déjà été séduit par une voix ?',
    'Tu as déjà eu un fantasme que tu n’oses pas avouer ?',
    'Tu as déjà joué à enlever un vêtement au poker ?',
    'Tu as déjà pris un bain à deux ?',
    'Tu as déjà fait un dîner aux chandelles pour séduire ?',
    'Tu as déjà mis de la musique pour séduire ?',
    'Tu as déjà dansé collé-serré ?',
    'Tu as déjà été réveillé par un baiser ?',
    'Tu as déjà un tatouage caché ?',
    'Tu as déjà fait un rêve très coquin ?',
    'Tu es déjà sorti avec deux personnes en même temps ?',
    'Tu as déjà fini au lit dès le premier rendez-vous ?',
    'Tu as déjà fait ça en silence pour ne pas réveiller les voisins ?',
    'Tu as déjà fait un fou rire pendant un moment intime ?',
    'Tu es plutôt câlin ?',
    'Tu aimes les massages ?',
    'Tu aimes être embrassé dans le cou ?',
    'Tu es chatouilleux ?',
    'Tu as déjà fait un massage à quelqu’un pour le séduire ?',
    'Tu as déjà acheté de la lingerie pour une soirée spéciale ?',
    'Tu as déjà mis un parfum pour séduire ?',
    'Tu as déjà mangé une fraise à deux ?',
    'Tu as déjà fait passer un glaçon de bouche en bouche ?',
    'Tu as déjà été invité chez quelqu’un « pour un dernier verre » ?',
    'Tu as déjà dit « on dort juste ensemble » ?',
    'Tu as déjà été tenté par un plan à trois ?',
    'Tu as déjà fait un strip-tease raté ?',
    'Tu as déjà dansé de façon très sensuelle devant un miroir ?',
    'Tu as déjà joué à la bouteille avec des gages ?',
    'Tu as déjà envoyé un message coquin à la mauvaise personne ?',
    'Tu as déjà regretté un message envoyé après minuit ?',
    'Tu as déjà fait une nuit blanche à deux ?',
    'Tu as déjà dormi sans rien du tout un soir d’été ?',
    'Tu as déjà été surpris sans t’y attendre par un baiser volé ?',
    'Tu as déjà volé un baiser ?',
    'Tu as déjà fait craquer quelqu’un d’un seul regard ?',
    'Tu as déjà eu des papillons dans le ventre en plein rendez-vous ?',
    'Tu as déjà fait du charme pour obtenir un service ?',
    'Tu as déjà eu un coup de cœur pour un inconnu dans le métro ?',
    'Tu as déjà fait un plan drague avec un ami complice ?',
    'Tu as déjà glissé un petit mot doux dans une poche ?',
    'Tu as déjà eu un crush sur un ami de ton ex ?',
    'Tu as déjà fait un câlin un peu trop long ?',
    'Tu as déjà embrassé quelqu’un dont tu ne connaissais pas le prénom ?',
    'Tu as déjà mal compris un signe de séduction ?',
    'Tu as déjà fait un bisou près des lèvres par « accident » ?',
    'Tu as déjà fait semblant d’avoir froid pour te rapprocher ?',
    'Tu as déjà joué avec tes cheveux pour attirer l’attention ?',
    'Tu as déjà fait un clin d’œil à quelqu’un d’inconnu ?',
    'Tu as déjà ouvert un bouton de plus pour séduire ?',
    'Tu as déjà passé un après-midi entier sous la couette ?',
    'Tu as déjà laissé un mot sur un pare-brise pour un inconnu ?',
    'Tu as déjà été mal à l’aise après un baiser ?',
    'Tu as déjà dit « c’était une erreur » après une nuit ?',
    'Tu as déjà quitté une chambre sur la pointe des pieds au petit matin ?',
    'Tu as déjà fait le trajet du retour en portant les mêmes vêtements que la veille ?',
    'Tu as déjà passé une nuit sans dormir pour une autre raison ?',
    'Tu as déjà trouvé un message coquin sur le téléphone de quelqu’un d’autre ?',
    'Tu as déjà fait semblant d’avoir sommeil pour éviter un moment intime ?',
    'Tu as déjà eu peur d’être entendu à travers un mur ?',
    'Tu as déjà été entendu à travers un mur ?',
    'Tu as déjà fait un SMS à un ex un peu éméché ?',
    'Tu as déjà fini dans le lit de quelqu’un que tu venais de rencontrer ?',
    'Tu as déjà rougi devant ton crush ?',
    'Tu as déjà fait l’amour sous les étoiles ?',
    'Tu as déjà fait tomber ta serviette devant quelqu’un ?',
    'Tu as déjà été vu en petite tenue par un voisin ?',
    'Tu as déjà fait la fête en sous-vêtements ?',
    'Tu as déjà dansé en sous-vêtements pour rigoler ?',
    'Tu as déjà fait un strip-poker ?',
    'Tu as déjà fait du charme à un ami en soirée par jeu ?',
    'Tu as déjà été jaloux d’un baiser vu en soirée ?',
    'Tu as déjà fait un slow avec quelqu’un qui te plaisait ?',
    'Tu as déjà échangé un regard intense avec un inconnu ?',
    'Tu as déjà fait un bisou dans le cou à quelqu’un ?',
    'Tu as déjà gardé un souvenir d’une nuit torride ?',
    'Tu as déjà fait un bain moussant en amoureux ?',
    'Tu as déjà lancé un « tu viens ? » plein de sous-entendus ?',
    'Tu as déjà mis des bougies pour créer l’ambiance ?',
    'Tu as déjà utilisé une playlist spéciale pour une soirée à deux ?',
    'Tu as déjà fait semblant de dormir pour qu’on te porte jusqu’au lit ?',
    'Tu as déjà fait un fantasme de déguisement ?',
    'Tu as déjà porté un uniforme pour séduire ?',
    'Tu as déjà rêvé de quelqu’un qui est dans cette pièce ?',
    'Tu as déjà fait un clin d’œil appuyé à un inconnu dans un bar ?',
    'Tu as déjà dansé très près de quelqu’un sans le connaître ?',
    'Tu as déjà reçu une proposition indécente ?',
    'Tu as déjà écrit un message très osé sans l’envoyer ?',
    'Tu as déjà fait un jeu de séduction avec des cartes ?',
    'Tu as déjà passé une soirée à échanger des regards complices ?',
    'Tu as déjà chuchoté quelque chose de coquin à l’oreille de quelqu’un ?',
    'Tu as déjà été troublé par un contact de mains ?',
    'Tu as déjà fait un câlin qui s’est transformé en autre chose ?',
    'Tu as déjà fait un strip-tease devant ton partenaire ?',
    'Tu as déjà fait la cuisine en tenue très légère ?',
    'Tu as déjà tenté un baiser dans le cou en dansant ?',
    'Tu as déjà joué à action ou vérité en petite tenue ?',
    'Tu as déjà laissé tes lèvres traîner un peu trop longtemps ?',
    'Tu as déjà eu un rendez-vous qui s’est fini à l’aube ?',
    // Relances et pièges
    'Tu rougis un peu, non ?',
    'Tu nous as vraiment tout dit ?',
    'Tu as une hésitation dans la voix, tu sais ?',
    'Tu n’oses pas répondre ?',
    'Tu réponds trop vite pour dire la vérité ?',
    'Tu es sûr de ne pas vouloir en dire plus ?',
    'Tu ne veux pas nous raconter la suite ?',
    // Doubles négations coquines
    'Tu ne dirais pas non à un petit massage ?',
    'Tu n’as jamais rêvé de te faire séduire par un inconnu ?',
    'Tu ne serais pas contre un baiser volé ?',
    'Tu n’es pas du genre à ne jamais flirter ?',
    'Tu ne refuserais pas un dîner aux chandelles ?',
    'Tu n’as jamais envoyé de message coquin, c’est bien ça ?',
    'Tu ne détestes pas qu’on te fasse un compliment sur ton physique ?',
    'Tu n’as jamais fait de rêve coquin, c’est ça ?',
    'Tu n’es pas insensible aux câlins, si ?',
    'Tu ne dormirais jamais sans rien sur toi, n’est-ce pas ?',
    'Tu ne te souviens pas de ton dernier baiser, c’est ça ?',
    'Tu n’as pas déjà craqué pour quelqu’un d’interdit ?',
    'Tu ne m’as pas dit que tu n’avais jamais rougi ?',
    'Tu n’as jamais envisagé un bain à deux ?',
    'Tu ne trouves pas qu’il fait chaud ici ?',
    'Tu n’es pas du genre à avoir peur du ridicule au lit ?',
    'Tu ne serais pas tenté par un jeu de gages un peu osé ?',
    'Tu n’as jamais été attiré par quelqu’un de plus âgé que toi ?',
    'Tu n’as pas déjà fait semblant de dormir pour éviter un câlin ?',
    'Tu ne dirais jamais non à un compliment sur ton sourire ?',
    'Tu n’as jamais tenté un regard de braise ?',
    'Tu ne portes pas un sous-vêtement original aujourd’hui ?',
    'Tu n’as pas peur de te faire embrasser ce soir ?',
    // Questions surprenantes
    'Tu as déjà rêvé d’une plage déserte à deux ?',
    'Tu as déjà fait un baiser sous le gui ?',
    'Tu as déjà dansé un tango ?',
    'Tu as déjà fait du charme à un barman ?',
    'Tu as déjà joué aux cartes en tenue légère ?',
    'Tu as déjà fait un bisou à ton reflet dans un miroir ?',
    'Tu as déjà dit « je suis fou de toi » sans le penser ?',
    'Tu as déjà passé la nuit à discuter jusqu’au matin avec un crush ?',
    'Tu as déjà reçu un message vocal très séduisant ?',
    'Tu as déjà fait un strip-tease pour rire devant des amis ?',
  ],
}
