import { dilemma, choice, fx } from '../helpers'
import type { DilemmaDefinition } from '../../../game-engine/dilemmas'

/**
 * Dilemmes sportifs (terrain + entraînement) — emplacement 1.
 * 12 dilemmes : pression du match, choix tactiques, gestion du corps.
 */
export const sportDilemmas: DilemmaDefinition[] = [
  dilemma({
    id: 'p5_match_penalty_decisif',
    title: 'Le penalty de la 89e',
    body: 'Quatre-vingt-neuvième minute du derby. Ton équipe obtient un penalty et le stade entier retient son souffle. Le tireur habituel est sorti sur blessure. Ton coéquipier le plus expérimenté réclame le ballon, sûr de lui. Rater ici peut hanter une saison entière ; marquer peut changer ton statut pour toujours. Le capitaine te regarde. À toi de tendre la main, ou pas.',
    category: 'match',
    tags: ['penalty', 'derby', 'pression'],
    rarity: 'common',
    weight: 16,
    ageMin: 16,
    ageMax: 39,
    cooldownSeasons: 3,
    choices: [
      choice({
        id: 'prendre',
        label: 'Prendre le ballon et assumer',
        stance: 'ambitious',
        riskPreview: 'Gloire possible, échec public possible.',
        immediate: [
          fx.skillCheck(
            'stat',
            'sangFroid',
            48,
            [
              fx.resource('reputationSportive', 8),
              fx.resource('moral', 7),
              fx.relation('fans', 8),
              fx.flag('derby_hero'),
            ],
            [
              fx.resource('reputationSportive', -6),
              fx.resource('moral', -8),
              fx.resource('confianceEntraineur', -4),
            ],
          ),
        ],
        hidden: [fx.hidden('grandsMatchs', 3), fx.hidden('ambition', 2)],
      }),
      choice({
        id: 'laisser',
        label: 'Laisser l’ancien tirer',
        stance: 'prudent',
        riskPreview: 'Pas de risque immédiat, occasion envolée.',
        immediate: [
          fx.relation('teammates', 5),
          fx.resource('moral', -3),
          fx.flag('penalty_refuse'),
        ],
        hidden: [fx.hidden('resistancePression', -2), fx.hidden('loyaute', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p5_match_consigne_ignoree',
    title: 'La consigne ou l’instinct',
    body: 'Le coach t’a demandé de rester bloqué sur ton côté, sans exception. Mais depuis vingt minutes, tu vois l’espace béant dans l’axe que personne n’attaque. Le score est nul, le public s’impatiente. Si tu quittes ta zone et que ça paie, tu es un génie. Si l’adversaire contre dans ton dos, tu seras le coupable désigné de la semaine.',
    category: 'match',
    tags: ['tactique', 'liberte'],
    rarity: 'common',
    weight: 15,
    ageMin: 16,
    ageMax: 37,
    cooldownSeasons: 3,
    choices: [
      choice({
        id: 'instinct',
        label: 'Suivre ton instinct et plonger dans l’axe',
        stance: 'high_risk',
        riskPreview: 'Coup d’éclat ou clash tactique avec le staff.',
        immediate: [
          fx.skillCheck(
            'stat',
            'vision',
            50,
            [
              fx.resource('reputationSportive', 6),
              fx.resource('moral', 5),
              fx.stat('vision', 1),
            ],
            [
              fx.relation('coach', -8),
              fx.resource('discipline', -4),
            ],
          ),
        ],
        hidden: [fx.hidden('adaptabilite', 2), fx.hidden('professionnalisme', -2)],
      }),
      choice({
        id: 'consigne',
        label: 'Respecter le plan à la lettre',
        stance: 'loyal',
        riskPreview: 'Confiance du staff, match peut-être terne.',
        immediate: [
          fx.relation('coach', 6),
          fx.resource('discipline', 4),
          fx.resource('moral', -2),
        ],
        hidden: [fx.hidden('professionnalisme', 3)],
      }),
    ],
  }),

  dilemma({
    id: 'p5_match_capitaine_un_soir',
    title: 'Le brassard tombe dans tes mains',
    body: 'Le capitaine est suspendu, son remplaçant malade. Une heure avant le coup d’envoi, le coach traverse le vestiaire et pose le brassard devant toi. Certains anciens détournent le regard : ils estiment que ce n’était pas ton tour. Porter le brassard t’expose : la moindre erreur sera commentée. Le refuser peut passer pour un manque de caractère.',
    category: 'match',
    tags: ['leadership', 'vestiaire'],
    rarity: 'uncommon',
    weight: 10,
    ageMin: 19,
    ageMax: 36,
    cooldownSeasons: 4,
    prerequisites: [{ type: 'minResource', id: 'confianceEntraineur', value: 45 }],
    choices: [
      choice({
        id: 'accepter',
        label: 'Enfiler le brassard et hausser la voix',
        stance: 'ambitious',
        riskPreview: 'Statut renforcé, anciens à convaincre.',
        immediate: [
          fx.stat('leadership', 2),
          fx.resource('reputationSportive', 4),
          fx.relation('teammates', -3),
          fx.flag('capitaine_un_soir'),
        ],
        delayed: [
          fx.delayed(1, [fx.relation('teammates', 6), fx.stat('leadership', 1)]),
        ],
        hidden: [fx.hidden('ambition', 3)],
      }),
      choice({
        id: 'suggerer',
        label: 'Proposer qu’un ancien le porte',
        stance: 'loyal',
        riskPreview: 'Vestiaire apaisé, occasion manquée.',
        immediate: [
          fx.relation('teammates', 6),
          fx.resource('cohesionVestiaire', 5),
          fx.resource('confianceEntraineur', -3),
        ],
        hidden: [fx.hidden('loyaute', 3), fx.hidden('ambition', -2)],
      }),
    ],
  }),

  dilemma({
    id: 'p5_match_crampes_80e',
    title: 'Tenir ou lever la main',
    body: 'Match capital, 80e minute, ton mollet se durcit à chaque sprint. Le banc te fixe, prêt à lancer le remplaçant. Si tu lèves la main, tu protèges ton corps mais tu quittes le combat au pire moment. Si tu serres les dents, tu peux arracher la victoire — ou te déchirer devant tout le monde et payer pendant des mois.',
    category: 'match',
    tags: ['corps', 'fatigue'],
    rarity: 'common',
    weight: 14,
    ageMin: 17,
    ageMax: 39,
    cooldownSeasons: 3,
    choices: [
      choice({
        id: 'tenir',
        label: 'Serrer les dents jusqu’au bout',
        stance: 'high_risk',
        riskPreview: 'Héroïsme possible, muscle en sursis.',
        immediate: [
          fx.resource('confianceEntraineur', 5),
          fx.resource('fatigue', 10),
          fx.chance(0.35, [fx.resource('sante', -12), fx.resource('forme', -8)]),
        ],
        hidden: [fx.hidden('fragilitePhysique', 3), fx.hidden('resistancePression', 2)],
      }),
      choice({
        id: 'sortir',
        label: 'Demander le changement',
        stance: 'prudent',
        riskPreview: 'Corps préservé, image de fragilité.',
        immediate: [
          fx.resource('sante', 5),
          fx.resource('forme', 3),
          fx.resource('reputationSportive', -3),
          fx.resource('moral', -3),
        ],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p5_match_provocation_adverse',
    title: 'Il cherche le carton',
    body: 'Depuis le début du match, ton vis-à-vis te provoque : semelles discrètes, insultes chuchotées, petit sourire à chaque coup de sifflet. L’arbitre ne voit rien. Ton sang bout. Répondre sur le terrain peut le faire craquer — ou te faire expulser. L’ignorer préserve l’équipe, mais il continuera, et tout le stade voit que tu subis.',
    category: 'match',
    tags: ['discipline', 'provocation'],
    rarity: 'common',
    weight: 14,
    ageMin: 16,
    ageMax: 38,
    cooldownSeasons: 3,
    choices: [
      choice({
        id: 'repondre',
        label: 'Lui rendre coup pour coup',
        stance: 'individualist',
        riskPreview: 'Duel assumé, arbitre imprévisible.',
        immediate: [
          fx.skillCheck(
            'stat',
            'sangFroid',
            55,
            [fx.resource('reputationSportive', 4), fx.resource('moral', 4)],
            [
              fx.resource('discipline', -8),
              fx.relation('coach', -5),
              fx.resource('reputationSportive', -3),
            ],
          ),
        ],
        hidden: [fx.hidden('resistancePression', 2)],
      }),
      choice({
        id: 'ignorer',
        label: 'Jouer ton match, rien d’autre',
        stance: 'prudent',
        riskPreview: 'Maîtrise saluée, frustration rentrée.',
        immediate: [
          fx.resource('discipline', 5),
          fx.relation('coach', 4),
          fx.resource('moral', -3),
        ],
        hidden: [fx.hidden('professionnalisme', 3), fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p5_match_soir_de_gala',
    title: 'Quarante-cinq minutes parfaites',
    body: 'Mi-temps d’un match de gala télévisé. Tu viens de livrer la meilleure période de ta carrière : tout te réussit, le public adverse applaudit. Dans le vestiaire, le coach propose de te sortir pour te préserver, le résultat étant acquis. Rester, c’est viser le match légendaire. Sortir, c’est écouter ton corps et laisser la lumière à un autre.',
    category: 'match',
    tags: ['performance', 'gala'],
    rarity: 'rare',
    weight: 5,
    ageMin: 18,
    ageMax: 36,
    cooldownSeasons: 5,
    unique: true,
    prerequisites: [{ type: 'minResource', id: 'forme', value: 55 }],
    choices: [
      choice({
        id: 'rester',
        label: 'Rejouer la seconde période entière',
        stance: 'ambitious',
        riskPreview: 'Nuit historique possible, fatigue certaine.',
        immediate: [
          fx.resource('fatigue', 8),
          fx.skillCheck(
            'hidden',
            'grandsMatchs',
            45,
            [
              fx.resource('reputationSportive', 10),
              fx.resource('popularite', 8),
              fx.relation('media', 6),
            ],
            [fx.resource('forme', -4), fx.resource('moral', -3)],
          ),
        ],
        hidden: [fx.hidden('ambition', 3)],
      }),
      choice({
        id: 'sortir',
        label: 'Sortir sous l’ovation',
        stance: 'prudent',
        riskPreview: 'Sagesse applaudie, légende inachevée.',
        immediate: [
          fx.resource('sante', 4),
          fx.resource('forme', 4),
          fx.relation('coach', 5),
          fx.resource('popularite', 3),
        ],
        hidden: [fx.hidden('professionnalisme', 3), fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p5_training_stage_hivernal',
    title: 'La trêve qui peut tout changer',
    body: 'La trêve arrive et ton club te laisse deux options. Un stage d’entraînement intensif à l’étranger, réputé pour transformer les joueurs — et pour en casser certains. Ou une vraie coupure chez toi, réclamée par ton corps et ta famille. Les places dans le onze se joueront à la reprise. Ton principal concurrent, lui, a déjà réservé son billet pour le stage.',
    category: 'training',
    tags: ['preparation', 'treve'],
    rarity: 'common',
    weight: 14,
    ageMin: 17,
    ageMax: 34,
    cooldownSeasons: 3,
    choices: [
      choice({
        id: 'stage',
        label: 'Partir en stage intensif',
        stance: 'ambitious',
        riskPreview: 'Progrès rapides, corps mis à l’épreuve.',
        immediate: [
          fx.stat('endurance', 2),
          fx.stat('puissance', 1),
          fx.resource('fatigue', 12),
          fx.relation('family', -5),
          fx.chance(0.2, [fx.resource('sante', -8)]),
        ],
        hidden: [fx.hidden('ambition', 2), fx.hidden('professionnalisme', 2)],
      }),
      choice({
        id: 'coupure',
        label: 'Couper vraiment, corps et tête',
        stance: 'emotional',
        riskPreview: 'Fraîcheur retrouvée, concurrence relancée.',
        immediate: [
          fx.resource('sante', 8),
          fx.resource('bienEtre', 8),
          fx.resource('fatigue', -15),
          fx.resource('confianceEntraineur', -3),
        ],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p5_training_video_supplementaire',
    title: 'L’analyste te veut à 7 heures',
    body: 'L’analyste vidéo du club t’a repéré : il propose des sessions individuelles à sept heures du matin, avant l’entraînement collectif. Il jure que c’est ce qui sépare les bons des grands. Tes coéquipiers ricanent déjà sur « le premier de la classe ». Accepter, c’est des semaines de réveils brutaux pour un gain invisible au début. Refuser, c’est peut-être passer à côté d’un déclic.',
    category: 'training',
    tags: ['video', 'progression'],
    rarity: 'common',
    weight: 13,
    ageMin: 16,
    ageMax: 33,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'accepter',
        label: 'Accepter les sessions de 7 heures',
        stance: 'ambitious',
        riskPreview: 'Lecture du jeu affinée, sommeil sacrifié.',
        immediate: [
          fx.stat('tactique', 2),
          fx.stat('placement', 1),
          fx.resource('fatigue', 6),
        ],
        delayed: [fx.delayed(1, [fx.stat('vision', 2), fx.resource('confianceEntraineur', 4)])],
        hidden: [fx.hidden('professionnalisme', 3)],
      }),
      choice({
        id: 'refuser',
        label: 'Garder ton énergie pour le terrain',
        stance: 'prudent',
        riskPreview: 'Fraîcheur préservée, étiquette de dilettante.',
        immediate: [
          fx.resource('bienEtre', 4),
          fx.relation('teammates', 3),
          fx.resource('confianceEntraineur', -2),
        ],
        hidden: [fx.hidden('professionnalisme', -2)],
      }),
    ],
  }),

  dilemma({
    id: 'p5_training_preparateur_prive',
    title: 'Un préparateur rien que pour toi',
    body: 'Un préparateur physique réputé propose de te suivre à titre privé. Son programme est pointu, ses résultats documentés — et ses honoraires très élevés. Le staff du club voit ces arrangements d’un mauvais œil : deux méthodes qui se contredisent peuvent abîmer un corps. Payer, c’est investir sur toi en contournant le club. Refuser, c’est rester dans le rang.',
    category: 'training',
    tags: ['preparation', 'investissement'],
    rarity: 'uncommon',
    weight: 10,
    ageMin: 19,
    ageMax: 33,
    cooldownSeasons: 4,
    prerequisites: [{ type: 'minResource', id: 'financesPersonnelles', value: 30 }],
    choices: [
      choice({
        id: 'payer',
        label: 'Engager le préparateur en privé',
        stance: 'financial',
        riskPreview: 'Physique optimisé, staff du club froissé.',
        immediate: [
          fx.cash(-9000),
          fx.stat('endurance', 2),
          fx.stat('vitesse', 1),
          fx.resource('confianceEntraineur', -4),
        ],
        hidden: [fx.hidden('ambition', 3), fx.hidden('professionnalisme', 2)],
      }),
      choice({
        id: 'club',
        label: 'Faire confiance au staff du club',
        stance: 'loyal',
        riskPreview: 'Harmonie préservée, plafond peut-être plus bas.',
        immediate: [
          fx.relation('coach', 4),
          fx.resource('discipline', 3),
          fx.resource('moral', -2),
        ],
        hidden: [fx.hidden('loyaute', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p5_training_surclassement',
    title: 'Invité chez les grands',
    body: 'Le coach de l’équipe première te convoque à l’entraînement des pros toute la semaine. C’est l’occasion que tu attends depuis toujours — et le piège classique : les anciens testent les jeunes qui montent, fort et sans cadeau. Jouer ton jeu à fond peut t’ouvrir des portes ou humilier un cadre. Te fondre dans le décor est plus sûr, mais qui se souvient des invisibles ?',
    category: 'training',
    tags: ['jeunesse', 'opportunite'],
    rarity: 'uncommon',
    weight: 12,
    ageMin: 16,
    ageMax: 19,
    cooldownSeasons: 2,
    careerStages: ['centre_formation', 'contrat_espoir'],
    choices: [
      choice({
        id: 'fond',
        label: 'Jouer à fond, tant pis pour les ego',
        stance: 'ambitious',
        riskPreview: 'Impression forte ou vestiaire refroidi.',
        immediate: [
          fx.skillCheck(
            'hidden',
            'potentiel',
            50,
            [
              fx.resource('confianceEntraineur', 8),
              fx.resource('reputationSportive', 5),
            ],
            [fx.relation('teammates', -6), fx.resource('moral', -4)],
          ),
        ],
        hidden: [fx.hidden('ambition', 3)],
      }),
      choice({
        id: 'observer',
        label: 'Observer, apprendre, respecter la hiérarchie',
        stance: 'prudent',
        riskPreview: 'Intégration douce, occasion peut-être unique.',
        immediate: [
          fx.relation('teammates', 4),
          fx.stat('tactique', 1),
          fx.resource('confianceEntraineur', -2),
        ],
        hidden: [fx.hidden('professionnalisme', 2), fx.hidden('ambition', -1)],
      }),
    ],
  }),

  dilemma({
    id: 'p5_match_terrain_impraticable',
    title: 'Un terrain à se briser une cheville',
    body: 'Pluie battante, pelouse ravagée : le terrain est à la limite du praticable, mais l’arbitre maintient le match. Ton style repose sur les appuis et les changements de direction — exactement ce que ce bourbier punit. Adapter ton jeu, jouer simple et laisser passer l’orage ? Ou imposer ton style malgré le risque, parce qu’un match se gagne aussi par l’audace ?',
    category: 'match',
    tags: ['conditions', 'corps'],
    rarity: 'common',
    weight: 12,
    ageMin: 16,
    ageMax: 38,
    cooldownSeasons: 3,
    choices: [
      choice({
        id: 'simple',
        label: 'Jouer simple, protéger tes appuis',
        stance: 'prudent',
        riskPreview: 'Match discret, chevilles intactes.',
        immediate: [
          fx.resource('sante', 3),
          fx.resource('reputationSportive', -2),
          fx.resource('discipline', 3),
        ],
        hidden: [fx.hidden('constance', 2)],
      }),
      choice({
        id: 'imposer',
        label: 'Imposer ton style malgré le bourbier',
        stance: 'high_risk',
        riskPreview: 'Différence possible, blessure qui rôde.',
        immediate: [
          fx.skillCheck(
            'stat',
            'controle',
            52,
            [fx.resource('reputationSportive', 6), fx.resource('moral', 5)],
            [fx.chance(0.4, [fx.resource('sante', -10)]), fx.resource('forme', -4)],
          ),
        ],
        hidden: [fx.hidden('grandsMatchs', 2), fx.hidden('fragilitePhysique', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p5_match_derby_tifo',
    title: 'Le derby s’invite dans ta semaine',
    body: 'Semaine de derby. La ville ne parle que de ça, les supporters t’interpellent à chaque feu rouge, et un groupe d’ultras te demande publiquement de « mouiller le maillot comme un enfant du club ». La pression peut te porter ou t’écraser. Tu peux embrasser le rôle et en faire ton match, ou te couper de tout le bruit et préparer ça comme un match ordinaire.',
    category: 'match',
    tags: ['derby', 'pression'],
    rarity: 'common',
    weight: 13,
    ageMin: 17,
    ageMax: 37,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'embrasser',
        label: 'En faire ton match, devant tout le monde',
        stance: 'emotional',
        riskPreview: 'Communion avec le public, pression maximale.',
        immediate: [
          fx.relation('fans', 8),
          fx.resource('popularite', 5),
          fx.skillCheck(
            'hidden',
            'resistancePression',
            50,
            [fx.resource('reputationSportive', 6), fx.flag('derby_hero')],
            [fx.resource('moral', -6), fx.resource('forme', -3)],
          ),
        ],
        hidden: [fx.hidden('grandsMatchs', 2)],
      }),
      choice({
        id: 'bulle',
        label: 'Te couper du bruit, préparer froidement',
        stance: 'prudent',
        riskPreview: 'Tête froide, supporters tenus à distance.',
        immediate: [
          fx.resource('moral', 3),
          fx.resource('discipline', 3),
          fx.relation('fans', -4),
        ],
        hidden: [fx.hidden('constance', 3), fx.hidden('resistancePression', 1)],
      }),
    ],
  }),
]
