import { dilemma, choice, fx } from '../helpers'
import type { DilemmaDefinition } from '../../../game-engine/dilemmas'

/**
 * Phase 9 — Agents. Compromis réels, ≥2 dimensions par choix. Certains posent
 * un nouveau profil d'agent (setAgent) ou dégradent une relation club plus tard.
 */
export const agentsDilemmas: DilemmaDefinition[] = [
  dilemma({
    id: 'p9_agt_commission_transfert',
    title: 'L’agent veut sa part du transfert',
    body: 'Ton agent réclame un pourcentage sur ta prime de transfert, au-delà du prévu. Céder graisse la relation et rogne ton gain personnel. Refuser protège ton argent et refroidit l’homme qui tient les fils de ta prochaine signature.',
    category: 'agent',
    tags: ['agent', 'commission', 'transfert'],
    rarity: 'common',
    weight: 8,
    ageMin: 20,
    ageMax: 35,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'ceder',
        label: 'Lâcher un pourcentage de plus',
        stance: 'emotional',
        riskPreview: 'Relation graissée, gain personnel rogné.',
        immediate: [fx.cash(-18000), fx.res('moral', 2)],
        hidden: [fx.hidden('loyaute', 1)],
      }),
      choice({
        id: 'refuser',
        label: 'Refuser le supplément',
        stance: 'financial',
        riskPreview: 'Argent protégé, agent refroidi.',
        immediate: [fx.res('financesPersonnelles', 4), fx.res('moral', -3)],
        hidden: [fx.hidden('constance', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('reputationSportive', -3)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p9_agt_conflit_interet',
    title: 'Ton agent gère aussi ton concurrent',
    body: 'Tu découvres que ton agent représente le rival qui vise ta place. Exiger l’exclusivité te protège d’un conflit d’intérêts et le force à choisir un camp. Fermer les yeux garde son réseau puissant à ton service, au prix d’un doute permanent sur ses vraies priorités.',
    category: 'agent',
    tags: ['agent', 'conflit'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 20,
    ageMax: 35,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'exclusivite',
        label: 'Exiger l’exclusivité',
        stance: 'professional',
        riskPreview: 'Conflit écarté, réseau peut-être perdu.',
        immediate: [fx.res('reputationSportive', 3), fx.res('financesPersonnelles', -2)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
      choice({
        id: 'fermer',
        label: 'Fermer les yeux',
        stance: 'prudent',
        riskPreview: 'Réseau gardé, doute permanent.',
        immediate: [fx.res('confianceEntraineur', 2), fx.res('bienEtre', -3)],
        hidden: [fx.hidden('constance', 1)],
        delayed: [fx.delayed(2, [fx.chance(0.3, [fx.res('confianceEntraineur', -5)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p9_agt_pousse_depart',
    title: 'Ton agent allume la mèche',
    body: 'Pour toucher une commission de transfert, ton agent critique ton club dans la presse afin de forcer ton départ. Le laisser faire peut t’ouvrir de belles portes et empoisonner ta relation avec des dirigeants humiliés. Le recadrer préserve le lien au club et te ferme des opportunités qu’il agitait.',
    category: 'agent',
    tags: ['agent', 'medias', 'transfert'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 21,
    ageMax: 34,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'laisser',
        label: 'Le laisser allumer la mèche',
        stance: 'ambitious',
        riskPreview: 'Portes ouvertes, dirigeants humiliés.',
        immediate: [fx.res('reputationSportive', 3), fx.rel('coach', -5)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(2, [fx.chance(0.5, [fx.res('confianceEntraineur', -6)])])],
      }),
      choice({
        id: 'recadrer',
        label: 'Le recadrer fermement',
        stance: 'loyal',
        riskPreview: 'Lien au club préservé, opportunités fermées.',
        immediate: [fx.rel('coach', 5), fx.res('reputationSportive', -2)],
        hidden: [fx.hidden('loyaute', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_agt_agence_star',
    title: 'L’agence des stars te veut',
    body: 'Une agence surpuissante, carnet d’adresses planétaire, propose de te représenter. La rejoindre ouvre les portes des plus grands clubs et te noie parmi cent autres dossiers. Rester avec ton agent actuel garde une attention sur mesure et te prive d’un réseau qui change une carrière.',
    category: 'agent',
    tags: ['agent', 'reseau'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 20,
    ageMax: 32,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'rejoindre',
        label: 'Rejoindre l’agence des stars',
        stance: 'ambitious',
        riskPreview: 'Réseau planétaire, attention diluée.',
        immediate: [fx.setAgent('connecte'), fx.res('reputationSportive', 3), fx.res('bienEtre', -2)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('reputationSportive', 4)])])],
      }),
      choice({
        id: 'rester',
        label: 'Garder ton agent attentif',
        stance: 'loyal',
        riskPreview: 'Suivi sur mesure, réseau limité.',
        immediate: [fx.res('bienEtre', 3), fx.res('reputationSportive', -2)],
        hidden: [fx.hidden('loyaute', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_agt_famille',
    title: 'Un proche veut devenir ton agent',
    body: 'Un membre de ta famille rêve de gérer ta carrière, par amour plus que par métier. Lui confier ce rôle scelle une confiance totale et mise ton avenir sur son inexpérience. Choisir un pro aguerri sécurise tes intérêts et blesse un proche qui espérait vivre l’aventure avec toi.',
    category: 'agent',
    tags: ['agent', 'famille'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 18,
    ageMax: 30,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'proche',
        label: 'Confier ta carrière au proche',
        stance: 'emotional',
        riskPreview: 'Confiance totale, avenir sur l’inexpérience.',
        immediate: [fx.setAgent('loyal'), fx.rel('family', 8)],
        hidden: [fx.hidden('loyaute', 3)],
        delayed: [fx.delayed(2, [fx.chance(0.35, [fx.res('financesPersonnelles', -6)])])],
      }),
      choice({
        id: 'pro',
        label: 'Choisir un pro aguerri',
        stance: 'professional',
        riskPreview: 'Intérêts sécurisés, proche blessé.',
        immediate: [fx.res('financesPersonnelles', 3), fx.rel('family', -6)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_agt_double_jeu',
    title: 'Négocié dans ton dos',
    body: 'Tu apprends que ton agent a démarché un club sans t’en parler. Le confronter et reprendre la main affirme ton autorité et fragilise une relation de travail rodée. Laisser courir pour ne pas froisser ses réseaux garde la machine en marche et t’installe dans une méfiance corrosive.',
    category: 'agent',
    tags: ['agent', 'confiance'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 20,
    ageMax: 35,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'confronter',
        label: 'Le confronter et reprendre la main',
        stance: 'professional',
        riskPreview: 'Autorité affirmée, relation fragilisée.',
        immediate: [fx.res('reputationSportive', 2), fx.res('moral', -3)],
        hidden: [fx.hidden('resistancePression', 2)],
      }),
      choice({
        id: 'laisser',
        label: 'Laisser courir pour ses réseaux',
        stance: 'prudent',
        riskPreview: 'Machine en marche, méfiance corrosive.',
        immediate: [fx.res('confianceEntraineur', 2), fx.res('bienEtre', -3)],
        hidden: [fx.hidden('constance', 1)],
        delayed: [fx.delayed(2, [fx.chance(0.3, [fx.res('moral', -5)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p9_agt_mandat_exclusif',
    title: 'Moins de commission, plus d’années',
    body: 'Ton agent baisse sa commission en échange d’un mandat exclusif de longue durée. Signer allège chaque deal futur et t’attache à lui même s’il décline. Refuser garde ta liberté de changer et te fait payer plus cher chaque négociation à venir.',
    category: 'agent',
    tags: ['agent', 'commission', 'mandat'],
    rarity: 'common',
    weight: 5,
    ageMin: 20,
    ageMax: 35,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'signer',
        label: 'Signer le mandat exclusif',
        stance: 'financial',
        riskPreview: 'Deals allégés, liberté d’en changer perdue.',
        immediate: [fx.res('financesPersonnelles', 4), fx.res('reputationSportive', -1)],
        hidden: [fx.hidden('constance', 2)],
        delayed: [fx.delayed(2, [fx.chance(0.3, [fx.res('moral', -4)])])],
      }),
      choice({
        id: 'refuser',
        label: 'Garder ta liberté',
        stance: 'individualist',
        riskPreview: 'Liberté gardée, négociations plus chères.',
        immediate: [fx.res('reputationSportive', 2), fx.res('financesPersonnelles', -3)],
        hidden: [fx.hidden('ambition', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_agt_debutant_passion',
    title: 'Le jeune agent plein de feu',
    body: 'Un agent débutant, passionné et affamé, te promet un dévouement absolu ; un requin établi, lui, garantit des résultats froids. Miser sur la jeunesse crée un lien fort et te prive du poids d’un vétéran dans les négociations. Choisir le requin muscle tes contrats et sacrifie la chaleur humaine.',
    category: 'agent',
    tags: ['agent', 'choix'],
    rarity: 'common',
    weight: 5,
    ageMin: 18,
    ageMax: 30,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'jeune',
        label: 'Miser sur le jeune passionné',
        stance: 'emotional',
        riskPreview: 'Lien fort, poids en négociation en moins.',
        immediate: [fx.setAgent('loyal'), fx.res('moral', 4)],
        hidden: [fx.hidden('loyaute', 2)],
        delayed: [fx.delayed(2, [fx.chance(0.3, [fx.res('financesPersonnelles', -4)])])],
      }),
      choice({
        id: 'requin',
        label: 'Choisir le requin établi',
        stance: 'financial',
        riskPreview: 'Contrats musclés, chaleur humaine sacrifiée.',
        immediate: [fx.setAgent('agressif'), fx.res('financesPersonnelles', 4), fx.res('bienEtre', -3)],
        hidden: [fx.hidden('ambition', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_agt_cadeaux',
    title: 'Une pluie de cadeaux suspects',
    body: 'Ton agent te couvre de montres et de voyages, façon d’acheter ta fidélité avant une renégociation. Accepter la manne profite à ton confort et t’enferme dans une dette morale envers lui. Refuser poliment garde ton indépendance de jugement et vexe un homme qui n’aime pas qu’on décline sa générosité.',
    category: 'agent',
    tags: ['agent', 'ethique', 'cadeaux'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 19,
    ageMax: 35,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'accepter',
        label: 'Accepter la manne',
        stance: 'emotional',
        riskPreview: 'Confort dopé, dette morale contractée.',
        immediate: [fx.res('bienEtre', 4), fx.res('discipline', -3)],
        hidden: [fx.hidden('loyaute', -1)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('financesPersonnelles', -5)])])],
      }),
      choice({
        id: 'refuser',
        label: 'Refuser pour rester libre',
        stance: 'ethical',
        riskPreview: 'Jugement libre, agent vexé.',
        immediate: [fx.res('discipline', 3), fx.res('moral', -2)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_agt_fuite_negociation',
    title: 'Ton agent balance à la presse',
    body: 'Pour faire pression sur ton club, ton agent divulgue le contenu de vos négociations. La manœuvre peut accélérer un accord et braquer des dirigeants qui détestent la place publique. Exiger la discrétion protège le lien au club et ralentit un dossier qu’il voulait débloquer par la force.',
    category: 'agent',
    tags: ['agent', 'medias', 'negociation'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 20,
    ageMax: 34,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'laisser',
        label: 'Laisser la pression jouer',
        stance: 'high_risk',
        riskPreview: 'Accord accéléré, dirigeants braqués.',
        immediate: [fx.res('financesPersonnelles', 3), fx.rel('coach', -5)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(2, [fx.chance(0.4, [fx.res('confianceEntraineur', -6)])])],
      }),
      choice({
        id: 'discretion',
        label: 'Exiger la discrétion',
        stance: 'loyal',
        riskPreview: 'Lien préservé, dossier ralenti.',
        immediate: [fx.rel('coach', 4), fx.res('financesPersonnelles', -2)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_agt_passer_prudent',
    title: 'Un agent calme après les tempêtes',
    body: 'Fatigué des coups fourrés, tu envisages un agent prudent qui privilégie la stabilité. Passer chez lui apaise ta carrière et bride tes coups d’éclat financiers. Rester dans l’agressivité garde tes gros contrats et t’use dans un tourbillon permanent de bras de fer.',
    category: 'agent',
    tags: ['agent', 'stabilite'],
    rarity: 'common',
    weight: 5,
    ageMin: 22,
    ageMax: 37,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'prudent',
        label: 'Passer à un agent prudent',
        stance: 'prudent',
        riskPreview: 'Carrière apaisée, coups d’éclat bridés.',
        immediate: [fx.setAgent('prudent'), fx.res('bienEtre', 5), fx.res('financesPersonnelles', -3)],
        hidden: [fx.hidden('constance', 2)],
      }),
      choice({
        id: 'agressif',
        label: 'Rester dans le rapport de force',
        stance: 'financial',
        riskPreview: 'Gros contrats gardés, usure permanente.',
        immediate: [fx.res('financesPersonnelles', 4), fx.res('bienEtre', -4)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('moral', -5)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p9_agt_opportuniste',
    title: 'Celui qui promet la lune',
    body: 'Un agent opportuniste te jure des contrats mirobolants et un avenir doré, commission salée à la clé. Le suivre peut faire décoller tes revenus ou t’embarquer dans des paris hasardeux. Décliner garde tes pieds sur terre et laisse filer des promesses parfois tenues.',
    category: 'agent',
    tags: ['agent', 'risque'],
    rarity: 'common',
    weight: 5,
    ageMin: 20,
    ageMax: 33,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'suivre',
        label: 'Suivre l’opportuniste',
        stance: 'ambitious',
        riskPreview: 'Revenus qui décollent ou paris hasardeux.',
        immediate: [fx.setAgent('opportuniste'), fx.res('reputationSportive', 2)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(2, [fx.chance(0.35, [fx.res('financesPersonnelles', -6)])])],
      }),
      choice({
        id: 'decliner',
        label: 'Garder les pieds sur terre',
        stance: 'prudent',
        riskPreview: 'Sagesse gardée, promesses laissées.',
        immediate: [fx.res('bienEtre', 3), fx.res('financesPersonnelles', -2)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_agt_renvoyer',
    title: 'Virer ton agent en pleine négo',
    body: 'En plein dossier crucial, ton agent multiplie les fautes et te coûte cher. Le renvoyer sur-le-champ stoppe l’hémorragie et jette le chaos dans une négociation déjà tendue. Le garder jusqu’au bout assure une continuité et te fait subir ses erreurs jusqu’à la signature.',
    category: 'agent',
    tags: ['agent', 'rupture'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 20,
    ageMax: 36,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'virer',
        label: 'Le renvoyer sur-le-champ',
        stance: 'high_risk',
        riskPreview: 'Hémorragie stoppée, chaos dans la négo.',
        immediate: [fx.setAgent('prudent'), fx.res('financesPersonnelles', -3)],
        hidden: [fx.hidden('resistancePression', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('reputationSportive', 3)])])],
      }),
      choice({
        id: 'garder',
        label: 'Le garder jusqu’au bout',
        stance: 'prudent',
        riskPreview: 'Continuité assurée, erreurs subies.',
        immediate: [fx.res('bienEtre', 2), fx.res('financesPersonnelles', -4)],
        hidden: [fx.hidden('constance', 1)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_agt_part_sponsors',
    title: 'Il veut aussi tes sponsors',
    body: 'Ton agent réclame désormais une part sur tes contrats commerciaux, en plus du sportif. Accepter unifie ta gestion sous une main experte et grignote tes revenus d’image. Confier tes sponsors à un autre spécialiste protège cette manne et multiplie les interlocuteurs qui se marchent dessus.',
    category: 'agent',
    tags: ['agent', 'sponsors', 'commission'],
    rarity: 'common',
    weight: 5,
    ageMin: 20,
    ageMax: 35,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'unifier',
        label: 'Tout confier à ton agent',
        stance: 'prudent',
        riskPreview: 'Gestion unifiée, revenus d’image rognés.',
        immediate: [fx.res('bienEtre', 3), fx.res('financesPersonnelles', -3)],
        hidden: [fx.hidden('loyaute', 1)],
      }),
      choice({
        id: 'separer',
        label: 'Séparer sportif et commercial',
        stance: 'financial',
        riskPreview: 'Manne protégée, interlocuteurs qui s’emmêlent.',
        immediate: [fx.res('popularite', 3), fx.res('bienEtre', -3)],
        hidden: [fx.hidden('professionnalisme', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.rel('sponsors', -4)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p9_agt_loyaute_test',
    title: 'Fidèle mais dépassé',
    body: 'L’agent qui t’a soutenu dans l’ombre peine désormais à suivre le très haut niveau. Le garder par gratitude honore votre histoire et plafonne tes contrats. Le remplacer par un ténor booste ta carrière et trahit celui qui croyait en toi quand personne d’autre ne le faisait.',
    category: 'agent',
    tags: ['agent', 'loyaute'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 23,
    ageMax: 36,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'garder',
        label: 'Le garder par gratitude',
        stance: 'loyal',
        riskPreview: 'Histoire honorée, contrats plafonnés.',
        immediate: [fx.res('moral', 4), fx.res('financesPersonnelles', -3)],
        hidden: [fx.hidden('loyaute', 3)],
      }),
      choice({
        id: 'remplacer',
        label: 'Le remplacer par un ténor',
        stance: 'ambitious',
        riskPreview: 'Carrière boostée, fidèle trahi.',
        immediate: [fx.setAgent('connecte'), fx.res('moral', -4)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('financesPersonnelles', 5)])])],
      }),
    ],
  }),
]
