import { dilemma, choice, fx } from '../helpers'
import type { DilemmaDefinition } from '../../../game-engine/dilemmas'

/**
 * Phase 9 — Contrats & salaires. Compromis réels, ≥2 dimensions par choix,
 * conséquences retardées. Emplacement 2 (carrière).
 */
export const contratsDilemmas: DilemmaDefinition[] = [
  dilemma({
    id: 'p9_ctr_gros_salaire_banc',
    title: 'Le pont d’or qui sent le banc',
    body: 'Un club te double le salaire mais ne te promet qu’un rôle de doublure. Signer remplit ton compte et gèle ton temps de jeu. Décliner pour un contrat plus modeste ailleurs garde ta place de titulaire et laisse filer une sécurité financière rare.',
    category: 'contract',
    tags: ['contrat', 'salaire', 'temps_de_jeu'],
    rarity: 'common',
    weight: 9,
    ageMin: 20,
    ageMax: 34,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'signer',
        label: 'Signer le pont d’or',
        stance: 'financial',
        riskPreview: 'Compte rempli, temps de jeu gelé.',
        immediate: [fx.cash(45000), fx.res('reputationSportive', -4)],
        hidden: [fx.hidden('ambition', -1)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('confianceEntraineur', -6)])])],
      }),
      choice({
        id: 'jouer',
        label: 'Choisir de jouer, payé moins',
        stance: 'professional',
        riskPreview: 'Place gardée, sécurité laissée.',
        immediate: [fx.res('confianceEntraineur', 5), fx.res('financesPersonnelles', -3)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_ctr_salaire_bas_role_central',
    title: 'Moins payé, mais au cœur du projet',
    body: 'Un club te propose un salaire sous ta valeur en te bâtissant l’équipe autour. Accepter place ta carrière au centre et rogne tes revenus. Exiger le tarif du marché sécurise tes finances et refroidit un projet qui voulait faire de toi son patron.',
    category: 'contract',
    tags: ['contrat', 'salaire', 'statut'],
    rarity: 'common',
    weight: 9,
    ageMin: 20,
    ageMax: 33,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'centre',
        label: 'Accepter le rôle central sous-payé',
        stance: 'ambitious',
        riskPreview: 'Carrière au centre, revenus rognés.',
        immediate: [fx.res('reputationSportive', 5), fx.res('financesPersonnelles', -4)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('confianceEntraineur', 6)])])],
      }),
      choice({
        id: 'marche',
        label: 'Exiger le tarif du marché',
        stance: 'financial',
        riskPreview: 'Finances sécurisées, projet refroidi.',
        immediate: [fx.cash(30000), fx.rel('coach', -5)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_ctr_long_vs_court',
    title: 'Long et sûr, ou court et libre',
    body: 'Deux offres du même club : cinq ans verrouillés, ou deux ans flexibles. Le long terme t’assoit financièrement et t’enchaîne si le projet capote. Le court terme garde ta liberté de rebondir et t’expose au vide si une blessure survient d’ici là.',
    category: 'contract',
    tags: ['contrat', 'duree', 'securite'],
    rarity: 'common',
    weight: 8,
    ageMin: 19,
    ageMax: 33,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'long',
        label: 'Signer long et sécurisé',
        stance: 'prudent',
        riskPreview: 'Assise financière, liberté enchaînée.',
        immediate: [fx.res('financesPersonnelles', 6), fx.res('reputationSportive', -2)],
        hidden: [fx.hidden('constance', 2)],
        delayed: [fx.delayed(2, [fx.chance(0.3, [fx.res('moral', -6)])])],
      }),
      choice({
        id: 'court',
        label: 'Signer court et flexible',
        stance: 'ambitious',
        riskPreview: 'Liberté gardée, vide possible si blessé.',
        immediate: [fx.res('reputationSportive', 3), fx.res('financesPersonnelles', -3)],
        hidden: [fx.hidden('ambition', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_ctr_prime_vs_variable',
    title: 'Prime immédiate ou salaire variable',
    body: 'Le club propose soit une grosse prime à la signature, soit un fixe modeste dopé aux bonus de performance. La prime te sécurise tout de suite et plafonne ton gain. Le variable récompense tes exploits et te laisse les mains vides si la saison déraille.',
    category: 'contract',
    tags: ['contrat', 'prime', 'variable'],
    rarity: 'common',
    weight: 8,
    ageMin: 19,
    ageMax: 34,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'prime',
        label: 'Prendre la prime à la signature',
        stance: 'prudent',
        riskPreview: 'Sécurité immédiate, gain plafonné.',
        immediate: [fx.cash(50000), fx.res('reputationSportive', -2)],
        hidden: [fx.hidden('constance', 2)],
      }),
      choice({
        id: 'variable',
        label: 'Miser sur le variable',
        stance: 'ambitious',
        riskPreview: 'Exploits récompensés, saison ratée = zéro.',
        immediate: [fx.res('reputationSportive', 3), fx.res('financesPersonnelles', -3)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.cash(60000)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p9_ctr_baisse_pour_rester',
    title: 'Baisser ton salaire pour rester',
    body: 'Le club, à court d’argent, te demande d’accepter une coupe salariale pour continuer l’aventure. Consentir grave ta fidélité dans la mémoire des supporters et allège ton portefeuille. Refuser protège tes revenus et te dessine en mercenaire aux yeux d’un public qui t’aimait.',
    category: 'contract',
    tags: ['contrat', 'salaire', 'fidelite'],
    rarity: 'uncommon',
    weight: 7,
    ageMin: 22,
    ageMax: 36,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'consentir',
        label: 'Accepter la coupe pour rester',
        stance: 'loyal',
        riskPreview: 'Fidélité gravée, portefeuille allégé.',
        immediate: [fx.rel('fans', 8), fx.res('financesPersonnelles', -5)],
        hidden: [fx.hidden('loyaute', 3)],
        delayed: [fx.delayed(2, [fx.flag('fan_favorite'), fx.chance(0.5, [fx.rel('fans', 6)])])],
      }),
      choice({
        id: 'refuser',
        label: 'Refuser toute baisse',
        stance: 'financial',
        riskPreview: 'Revenus protégés, image de mercenaire.',
        immediate: [fx.res('financesPersonnelles', 4), fx.rel('fans', -7)],
        hidden: [fx.hidden('ambition', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_ctr_clause_rendement',
    title: 'Une clause qui parie sur tes buts',
    body: 'Le club indexe une part de ton salaire sur des objectifs chiffrés très hauts. Signer cette clause peut gonfler tes revenus si tu exploses les compteurs, ou te pousser à forcer au mépris de ton corps. La refuser garde un fixe serein et laisse un joli complément sur la table.',
    category: 'contract',
    tags: ['contrat', 'clause', 'rendement'],
    rarity: 'common',
    weight: 7,
    ageMin: 19,
    ageMax: 33,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'signer',
        label: 'Accepter la clause de rendement',
        stance: 'ambitious',
        riskPreview: 'Revenus dopés possibles, corps sous pression.',
        immediate: [fx.res('reputationSportive', 3), fx.res('fatigue', 4)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('sante', -6)])])],
      }),
      choice({
        id: 'refuser',
        label: 'Garder un fixe serein',
        stance: 'prudent',
        riskPreview: 'Sérénité gardée, complément laissé.',
        immediate: [fx.res('bienEtre', 3), fx.res('financesPersonnelles', -2)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_ctr_annee_optionnelle',
    title: 'À qui l’année en option ?',
    body: 'La négociation coince sur l’année optionnelle : au club ou à toi ? La laisser au club rassure les dirigeants et te met à leur merci en fin de contrat. L’exiger de ton côté sécurise ton avenir et durcit des pourparlers qui pourraient capoter.',
    category: 'contract',
    tags: ['contrat', 'clause', 'negociation'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 20,
    ageMax: 35,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'club',
        label: 'Laisser l’option au club',
        stance: 'prudent',
        riskPreview: 'Dirigeants rassurés, avenir à leur merci.',
        immediate: [fx.res('confianceEntraineur', 4), fx.res('reputationSportive', -2)],
        hidden: [fx.hidden('loyaute', 2)],
        delayed: [fx.delayed(2, [fx.chance(0.3, [fx.res('moral', -5)])])],
      }),
      choice({
        id: 'toi',
        label: 'Exiger l’option de ton côté',
        stance: 'financial',
        riskPreview: 'Avenir sécurisé, pourparlers durcis.',
        immediate: [fx.res('reputationSportive', 3), fx.rel('coach', -4)],
        hidden: [fx.hidden('ambition', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_ctr_promesse_capitanat',
    title: 'Prolonger sur une promesse',
    body: 'Le club t’offre une prolongation dorée en te promettant le brassard « bientôt ». Signer sur cette parole te lie et mise ta carrière sur un engagement flou. Réclamer la promesse noir sur blanc protège tes intérêts et vexe une direction qui n’aime pas être bousculée.',
    category: 'contract',
    tags: ['contrat', 'prolongation', 'promesse'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 22,
    ageMax: 35,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'confiance',
        label: 'Signer sur parole',
        stance: 'loyal',
        riskPreview: 'Lien scellé, promesse floue en pari.',
        immediate: [fx.flag('contract_extended'), fx.rel('coach', 6), fx.res('financesPersonnelles', -2)],
        hidden: [fx.hidden('loyaute', 2)],
        delayed: [fx.delayed(2, [fx.debt('ctr_brassard', 'Le brassard promis reste à venir', 1)])],
      }),
      choice({
        id: 'ecrit',
        label: 'Exiger la promesse par écrit',
        stance: 'prudent',
        riskPreview: 'Intérêts protégés, direction vexée.',
        immediate: [fx.res('reputationSportive', 2), fx.rel('coach', -5)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_ctr_clause_liberatoire',
    title: 'Clause basse ou salaire haut',
    body: 'Le club accepte l’un ou l’autre : un salaire supérieur, ou une clause libératoire basse qui facilitera ton départ. Le salaire garnit ton compte et t’emprisonne au club. La clause t’ouvre les portes de demain et te fait renoncer à un fixe plus confortable aujourd’hui.',
    category: 'contract',
    tags: ['contrat', 'clause', 'salaire'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 20,
    ageMax: 32,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'salaire',
        label: 'Prendre le salaire supérieur',
        stance: 'financial',
        riskPreview: 'Compte garni, porte de sortie fermée.',
        immediate: [fx.cash(35000), fx.res('reputationSportive', -2)],
        hidden: [fx.hidden('constance', 2)],
      }),
      choice({
        id: 'clause',
        label: 'Exiger une clause basse',
        stance: 'ambitious',
        riskPreview: 'Avenir ouvert, fixe moins confortable.',
        immediate: [fx.res('reputationSportive', 3), fx.res('financesPersonnelles', -3)],
        hidden: [fx.hidden('ambition', 3)],
        delayed: [fx.delayed(2, [fx.chance(0.4, [fx.res('reputationSportive', 4)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p9_ctr_fidelite_vs_prime',
    title: 'Bonus de fidélité ou cash tout de suite',
    body: 'Le club te laisse choisir : une prime immédiate, ou un gros bonus de fidélité versé si tu restes trois ans. Le cash comble un besoin présent et te libère de tout engagement. Le bonus futur récompense la patience et parie sur une stabilité que rien ne garantit.',
    category: 'contract',
    tags: ['contrat', 'prime', 'fidelite'],
    rarity: 'common',
    weight: 6,
    ageMin: 20,
    ageMax: 34,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'cash',
        label: 'Prendre le cash immédiat',
        stance: 'financial',
        riskPreview: 'Besoin comblé, engagement dénoué.',
        immediate: [fx.cash(28000), fx.rel('coach', -3)],
        hidden: [fx.hidden('ambition', 1)],
      }),
      choice({
        id: 'fidelite',
        label: 'Parier sur le bonus de fidélité',
        stance: 'loyal',
        riskPreview: 'Patience récompensée, stabilité incertaine.',
        immediate: [fx.rel('coach', 5), fx.res('financesPersonnelles', -2)],
        hidden: [fx.hidden('loyaute', 2)],
        delayed: [fx.delayed(3, [fx.chance(0.6, [fx.cash(70000)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p9_ctr_geste_recrutement',
    title: 'Un geste salarial pour un renfort',
    body: 'Le club recruterait la pièce manquante si tu lissais ton salaire sur deux ans. Faire ce geste renforce l’équipe et ta stature de leader, au prix de ta trésorerie. Refuser protège tes revenus et prive le groupe d’un renfort que tout le monde réclame.',
    category: 'contract',
    tags: ['contrat', 'salaire', 'collectif'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 23,
    ageMax: 36,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'geste',
        label: 'Faire le geste salarial',
        stance: 'collective',
        riskPreview: 'Équipe renforcée, trésorerie ponctionnée.',
        immediate: [fx.res('cohesionVestiaire', 6), fx.res('financesPersonnelles', -5)],
        hidden: [fx.hidden('loyaute', 2)],
        delayed: [fx.delayed(2, [fx.chance(0.4, [fx.res('reputationSportive', 4)])])],
      }),
      choice({
        id: 'refuser',
        label: 'Garder ton salaire intact',
        stance: 'financial',
        riskPreview: 'Revenus protégés, renfort manqué.',
        immediate: [fx.res('financesPersonnelles', 3), fx.res('cohesionVestiaire', -4)],
        hidden: [fx.hidden('ambition', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_ctr_salaire_differe',
    title: 'Le salaire payé plus tard',
    body: 'Le club, en difficulté, propose d’étaler une part de ton salaire sur les saisons futures. Accepter aide la maison à respirer et fragilise ta sécurité si elle coule. Exiger d’être payé rubis sur l’ongle protège ton argent et met une pression que la trésorerie ne supportera peut-être pas.',
    category: 'contract',
    tags: ['contrat', 'salaire', 'risque'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 21,
    ageMax: 36,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'etaler',
        label: 'Accepter le paiement différé',
        stance: 'loyal',
        riskPreview: 'Club soulagé, sécurité fragilisée.',
        immediate: [fx.rel('coach', 6), fx.res('financesPersonnelles', -4)],
        hidden: [fx.hidden('loyaute', 2)],
        delayed: [fx.delayed(2, [fx.chance(0.35, [fx.cash(-40000)])])],
      }),
      choice({
        id: 'rubis',
        label: 'Exiger d’être payé maintenant',
        stance: 'financial',
        riskPreview: 'Argent protégé, pression sur le club.',
        immediate: [fx.res('financesPersonnelles', 4), fx.rel('coach', -5)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_ctr_droits_image',
    title: 'Qui possède ton image ?',
    body: 'Le club veut inclure tes droits à l’image dans le contrat, contre un joli complément. Céder ces droits gonfle ton salaire et laisse le club exploiter ton visage à sa guise. Les conserver protège ton indépendance commerciale et te prive d’un chèque que peu refusent.',
    category: 'contract',
    tags: ['contrat', 'image', 'droits'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 20,
    ageMax: 34,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'ceder',
        label: 'Céder tes droits à l’image',
        stance: 'financial',
        riskPreview: 'Salaire gonflé, visage exploité par le club.',
        immediate: [fx.cash(32000), fx.res('popularite', -3)],
        hidden: [fx.hidden('constance', 1)],
        delayed: [fx.delayed(2, [fx.chance(0.3, [fx.rel('sponsors', -5)])])],
      }),
      choice({
        id: 'garder',
        label: 'Garder tes droits',
        stance: 'ambitious',
        riskPreview: 'Indépendance gardée, chèque refusé.',
        immediate: [fx.res('popularite', 3), fx.res('financesPersonnelles', -3)],
        hidden: [fx.hidden('ambition', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_ctr_prime_maintien',
    title: 'Ta prime liée au maintien',
    body: 'Le club conditionne un gros bonus au maintien de l’équipe en fin de saison. Accepter ce pari te motive à sauver le club et suspend tes gains à un classement incertain. Réclamer un fixe garanti sécurise ton salaire et prive un vestiaire fragile d’un leader engagé jusqu’au bout.',
    category: 'contract',
    tags: ['contrat', 'prime', 'maintien'],
    rarity: 'common',
    weight: 5,
    ageMin: 21,
    ageMax: 36,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'parier',
        label: 'Lier ta prime au maintien',
        stance: 'collective',
        riskPreview: 'Motivation décuplée, gains suspendus au classement.',
        immediate: [fx.res('cohesionVestiaire', 5), fx.res('financesPersonnelles', -2)],
        hidden: [fx.hidden('resistancePression', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.45, [fx.cash(45000)])])],
      }),
      choice({
        id: 'fixe',
        label: 'Exiger un fixe garanti',
        stance: 'financial',
        riskPreview: 'Salaire sécurisé, engagement mis en doute.',
        immediate: [fx.res('financesPersonnelles', 3), fx.res('cohesionVestiaire', -3)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_ctr_clause_anti_rival',
    title: 'Interdit de signer chez l’ennemi',
    body: 'Le club veut une clause t’empêchant de rejoindre son grand rival, contre un bonus. L’accepter t’attache aux fans et te ferme une porte parfois lucrative. La refuser garde toutes tes options ouvertes et froisse une direction qui craint de te voir un jour en face.',
    category: 'contract',
    tags: ['contrat', 'clause', 'rivalite'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 21,
    ageMax: 34,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'accepter',
        label: 'Accepter la clause anti-rival',
        stance: 'loyal',
        riskPreview: 'Fans conquis, porte lucrative fermée.',
        immediate: [fx.rel('fans', 6), fx.res('financesPersonnelles', -2)],
        hidden: [fx.hidden('loyaute', 2)],
      }),
      choice({
        id: 'refuser',
        label: 'Garder toutes tes options',
        stance: 'ambitious',
        riskPreview: 'Options ouvertes, direction froissée.',
        immediate: [fx.res('reputationSportive', 3), fx.rel('coach', -4)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(2, [fx.chance(0.3, [fx.rel('fans', -5)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p9_ctr_prime_match',
    title: 'Primes de match ou gros fixe',
    body: 'On te laisse arbitrer entre un salaire fixe élevé et un fixe bas rehaussé par de fortes primes à chaque titularisation. Le fixe rassure et t’endort. Les primes récompensent la régularité sur le terrain et s’effondrent si le coach te fait tourner ou si tu te blesses.',
    category: 'contract',
    tags: ['contrat', 'prime', 'variable'],
    rarity: 'common',
    weight: 5,
    ageMin: 19,
    ageMax: 34,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'fixe',
        label: 'Choisir le gros fixe',
        stance: 'prudent',
        riskPreview: 'Sécurité, mais moins de récompense au mérite.',
        immediate: [fx.cash(30000), fx.res('reputationSportive', -2)],
        hidden: [fx.hidden('constance', 2)],
      }),
      choice({
        id: 'primes',
        label: 'Miser sur les primes de match',
        stance: 'ambitious',
        riskPreview: 'Régularité payée, rotation = gains en chute.',
        immediate: [fx.res('reputationSportive', 3), fx.res('financesPersonnelles', -2)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.cash(40000)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p9_ctr_signer_avant_blessure',
    title: 'Signer vite, avant les examens',
    body: 'Ton agent te presse de parapher avant des examens médicaux qui pourraient révéler une fragilité. Signer maintenant verrouille un contrat que le verdict ferait fondre, au prix d’un mensonge par omission. Attendre la transparence protège ton honnêteté et menace l’accord si ton corps parle.',
    category: 'contract',
    tags: ['contrat', 'sante', 'ethique'],
    rarity: 'rare',
    weight: 4,
    ageMin: 22,
    ageMax: 36,
    cooldownSeasons: 6,
    choices: [
      choice({
        id: 'signer',
        label: 'Signer avant les examens',
        stance: 'high_risk',
        riskPreview: 'Contrat verrouillé, mensonge par omission.',
        immediate: [fx.cash(40000), fx.res('discipline', -4)],
        hidden: [fx.hidden('professionnalisme', -2)],
        delayed: [fx.delayed(2, [fx.chance(0.35, [fx.res('reputationSportive', -6)])])],
      }),
      choice({
        id: 'attendre',
        label: 'Attendre la transparence',
        stance: 'ethical',
        riskPreview: 'Honnêteté gardée, accord menacé.',
        immediate: [fx.res('reputationSportive', 3), fx.res('financesPersonnelles', -3)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_ctr_premier_gros',
    title: 'Ton premier vrai gros contrat',
    body: 'À peine sorti du centre, un contrat qui change ta vie t’est tendu. Le signer sans broncher assure ta famille et peut te griser trop vite. Négocier des garanties de progression cadre ton avenir et risque d’agacer un club qui pensait t’avoir pour une bouchée de pain.',
    category: 'contract',
    tags: ['contrat', 'jeune', 'salaire'],
    rarity: 'common',
    weight: 7,
    ageMin: 16,
    ageMax: 21,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'signer',
        label: 'Signer sans discuter',
        stance: 'emotional',
        riskPreview: 'Famille assurée, tête qui peut enfler.',
        immediate: [fx.cash(25000), fx.res('bienEtre', 4)],
        hidden: [fx.hidden('ambition', 1)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('discipline', -4)])])],
      }),
      choice({
        id: 'negocier',
        label: 'Négocier des garanties',
        stance: 'professional',
        riskPreview: 'Avenir cadré, club agacé.',
        immediate: [fx.res('confianceEntraineur', 4), fx.rel('coach', -3)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_ctr_veteran_rabais',
    title: 'Finir au rabais, mais chez toi',
    body: 'En fin de carrière, ton club de cœur t’offre un contrat symbolique pour boucler la boucle. L’accepter grave ton nom dans l’histoire du club et réduit tes derniers gros revenus. Chercher un dernier chèque ailleurs remplit le compte et ternit l’image de l’enfant du club.',
    category: 'contract',
    tags: ['contrat', 'veteran', 'fidelite'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 31,
    ageMax: 38,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'coeur',
        label: 'Finir chez toi au rabais',
        stance: 'loyal',
        riskPreview: 'Nom gravé, derniers gros revenus rognés.',
        immediate: [fx.rel('fans', 8), fx.res('financesPersonnelles', -4)],
        hidden: [fx.hidden('loyaute', 3)],
        delayed: [fx.delayed(2, [fx.flag('fan_favorite'), fx.chance(0.5, [fx.rel('fans', 5)])])],
      }),
      choice({
        id: 'ailleurs',
        label: 'Chercher un dernier chèque',
        stance: 'financial',
        riskPreview: 'Compte rempli, image d’enfant du club ternie.',
        immediate: [fx.cash(45000), fx.rel('fans', -6)],
        hidden: [fx.hidden('ambition', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_ctr_reneg_grosse_saison',
    title: 'Renégocier après l’exploit',
    body: 'Une saison énorme te met en position de force pour renégocier. Frapper fort maintenant maximise tes gains et fatigue une direction qui te trouve gourmand. Temporiser par respect du contrat en cours soigne ta relation au club et laisse filer une fenêtre qui ne se rouvrira pas.',
    category: 'contract',
    tags: ['contrat', 'renegociation', 'salaire'],
    rarity: 'common',
    weight: 6,
    ageMin: 21,
    ageMax: 33,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'frapper',
        label: 'Renégocier tout de suite',
        stance: 'ambitious',
        riskPreview: 'Gains maximisés, direction agacée.',
        immediate: [fx.cash(40000), fx.rel('coach', -5)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('confianceEntraineur', -5)])])],
      }),
      choice({
        id: 'temporiser',
        label: 'Respecter le contrat en cours',
        stance: 'loyal',
        riskPreview: 'Relation soignée, fenêtre laissée passer.',
        immediate: [fx.rel('coach', 6), fx.res('financesPersonnelles', -3)],
        hidden: [fx.hidden('loyaute', 2)],
      }),
    ],
  }),
]
