import { dilemma, choice, fx } from '../helpers'
import type { DilemmaDefinition } from '../../../game-engine/dilemmas'

/**
 * Phase 9 — Dépenses & entourage. Compromis réels, ≥2 dimensions par choix.
 * Le train de vie peut créer une pression financière plusieurs saisons après.
 */
export const depensesDilemmas: DilemmaDefinition[] = [
  dilemma({
    id: 'p9_dep_maison_luxe',
    title: 'La villa de tes rêves',
    body: 'Une villa somptueuse te fait de l’œil, bien au-dessus de tes besoins. L’acheter comble un rêve d’enfant et alourdit durablement tes charges. Rester raisonnable protège ton patrimoine et laisse un manque, celui de n’avoir pas croqué la vie quand tu le pouvais.',
    category: 'lifestyle',
    tags: ['depenses', 'train_de_vie', 'patrimoine'],
    rarity: 'common',
    weight: 7,
    ageMin: 21,
    ageMax: 36,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'acheter',
        label: 'Acheter la villa de rêve',
        stance: 'emotional',
        riskPreview: 'Rêve comblé, charges durablement alourdies.',
        immediate: [fx.cash(-70000), fx.res('bienEtre', 6)],
        hidden: [fx.hidden('constance', -1)],
        delayed: [fx.delayed(2, [fx.chance(0.4, [fx.res('financesPersonnelles', -8)])])],
      }),
      choice({
        id: 'raisonnable',
        label: 'Rester raisonnable',
        stance: 'prudent',
        riskPreview: 'Patrimoine protégé, plaisir différé.',
        immediate: [fx.res('financesPersonnelles', 5), fx.res('moral', -3)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_dep_voitures',
    title: 'Le garage de collectionneur',
    body: 'Les bolides de luxe s’alignent et la tentation d’une collection te démange. En aligner une flotte flatte ton image et engloutit une fortune vite dépréciée. Te contenter d’une belle auto garde ton compte solide et te prive d’un plaisir clinquant que d’autres affichent sans complexe.',
    category: 'lifestyle',
    tags: ['depenses', 'train_de_vie'],
    rarity: 'common',
    weight: 6,
    ageMin: 20,
    ageMax: 34,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'flotte',
        label: 'Aligner une flotte de bolides',
        stance: 'emotional',
        riskPreview: 'Image flattée, fortune vite dépréciée.',
        immediate: [fx.cash(-45000), fx.res('popularite', 4)],
        hidden: [fx.hidden('ambition', 1)],
        delayed: [fx.delayed(2, [fx.chance(0.3, [fx.res('financesPersonnelles', -6)])])],
      }),
      choice({
        id: 'sobre',
        label: 'Une seule belle auto',
        stance: 'prudent',
        riskPreview: 'Compte solide, plaisir clinquant en moins.',
        immediate: [fx.res('financesPersonnelles', 4), fx.res('popularite', -2)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_dep_entourage_grandit',
    title: 'Ton clan s’élargit, ta note aussi',
    body: 'Cousins, potes, conseillers : ton entourage grossit et vit largement à tes crochets. Tout financer sans compter entretient la loyauté du clan et fait fondre tes réserves. Serrer les cordons de la bourse protège ton argent et refroidit des proches habitués à la générosité.',
    category: 'lifestyle',
    tags: ['depenses', 'entourage'],
    rarity: 'common',
    weight: 6,
    ageMin: 20,
    ageMax: 36,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'financer',
        label: 'Tout financer sans compter',
        stance: 'emotional',
        riskPreview: 'Clan loyal, réserves qui fondent.',
        immediate: [fx.cash(-30000), fx.rel('friends', 6)],
        hidden: [fx.hidden('loyaute', 2)],
        delayed: [fx.delayed(2, [fx.chance(0.35, [fx.res('financesPersonnelles', -7)])])],
      }),
      choice({
        id: 'serrer',
        label: 'Serrer les cordons',
        stance: 'financial',
        riskPreview: 'Argent protégé, proches refroidis.',
        immediate: [fx.res('financesPersonnelles', 5), fx.rel('friends', -6)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_dep_staff_perso',
    title: 'Chef, chauffeur, kiné à demeure',
    body: 'Monter un staff personnel — chef, kiné, chauffeur — te libère l’esprit à prix d’or. L’installer optimise ta vie de sportif et pèse lourd chaque mois. Faire sans préserve tes économies et te charge d’un quotidien logistique qui grignote ton énergie de compétiteur.',
    category: 'lifestyle',
    tags: ['depenses', 'staff', 'bien_etre'],
    rarity: 'common',
    weight: 6,
    ageMin: 21,
    ageMax: 36,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'monter',
        label: 'Monter un staff à demeure',
        stance: 'professional',
        riskPreview: 'Vie optimisée, coût mensuel lourd.',
        immediate: [fx.res('forme', 4), fx.res('financesPersonnelles', -5)],
        hidden: [fx.hidden('professionnalisme', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('bienEtre', 5)])])],
      }),
      choice({
        id: 'sans',
        label: 'Gérer par toi-même',
        stance: 'prudent',
        riskPreview: 'Économies gardées, énergie grignotée.',
        immediate: [fx.res('financesPersonnelles', 4), fx.res('fatigue', 3)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_dep_extravagant',
    title: 'La vie jet-set à plein régime',
    body: 'Soirées, palaces, voyages privés : le grand train de vie t’ouvre les bras. Vivre à cent à l’heure dope ton moral et ta popularité, et menace ton équilibre financier. Garder les pieds sur terre protège ton avenir et te fait passer pour un rabat-joie dans ton milieu.',
    category: 'lifestyle',
    tags: ['depenses', 'train_de_vie', 'extravagant'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 21,
    ageMax: 33,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'jetset',
        label: 'Vivre à cent à l’heure',
        stance: 'emotional',
        riskPreview: 'Moral et popularité dopés, équilibre menacé.',
        immediate: [fx.res('moral', 6), fx.res('popularite', 4)],
        hidden: [fx.hidden('constance', -2)],
        delayed: [fx.delayed(2, [fx.chance(0.45, [fx.res('financesPersonnelles', -9)])])],
      }),
      choice({
        id: 'terre',
        label: 'Garder les pieds sur terre',
        stance: 'prudent',
        riskPreview: 'Avenir protégé, image de rabat-joie.',
        immediate: [fx.res('financesPersonnelles', 6), fx.res('popularite', -3)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_dep_maison_parents',
    title: 'Offrir une maison à tes parents',
    body: 'Tu rêves d’offrir aux tiens la maison qu’ils n’ont jamais eue. Le faire honore un serment d’enfant et ponctionne lourdement ton capital. Reporter ce cadeau consolide ton patrimoine et laisse tes parents dans un logement modeste, ce qui te ronge en silence.',
    category: 'money',
    tags: ['depenses', 'famille', 'patrimoine'],
    rarity: 'common',
    weight: 6,
    ageMin: 20,
    ageMax: 37,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'offrir',
        label: 'Offrir la maison à tes parents',
        stance: 'emotional',
        riskPreview: 'Serment honoré, capital ponctionné.',
        immediate: [fx.cash(-60000), fx.rel('family', 10)],
        hidden: [fx.hidden('loyaute', 3)],
      }),
      choice({
        id: 'reporter',
        label: 'Reporter le cadeau',
        stance: 'financial',
        riskPreview: 'Patrimoine consolidé, remords qui ronge.',
        immediate: [fx.res('financesPersonnelles', 5), fx.res('moral', -4)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_dep_ami_emprunt',
    title: 'Un ami d’enfance te demande gros',
    body: 'Un ami de toujours, au bord de la faillite, te supplie d’un prêt conséquent. L’aider sauve peut-être sa peau et met ton argent en jeu sans garantie. Refuser protège tes finances et brise net une amitié forgée bien avant les stades pleins.',
    category: 'money',
    tags: ['depenses', 'amitie', 'pret'],
    rarity: 'common',
    weight: 6,
    ageMin: 20,
    ageMax: 37,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'preter',
        label: 'Lui prêter la somme',
        stance: 'emotional',
        riskPreview: 'Ami sauvé peut-être, argent sans garantie.',
        immediate: [fx.cash(-35000), fx.rel('friends', 8)],
        hidden: [fx.hidden('loyaute', 2)],
        delayed: [fx.delayed(2, [fx.chance(0.4, [fx.rel('friends', -6)])])],
      }),
      choice({
        id: 'refuser',
        label: 'Protéger tes finances',
        stance: 'financial',
        riskPreview: 'Argent protégé, amitié brisée.',
        immediate: [fx.res('financesPersonnelles', 4), fx.rel('friends', -8)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_dep_gala_charite',
    title: 'Ton propre gala de charité',
    body: 'Organiser un gala caritatif tape-à-l’œil soigne ton image de bienfaiteur. Le monter mobilise une belle somme et une énergie folle pour une cause réelle. T’en tenir à un don discret garde ton argent et te prive du rayonnement d’un événement à ton nom.',
    category: 'money',
    tags: ['depenses', 'charite', 'image'],
    rarity: 'common',
    weight: 5,
    ageMin: 22,
    ageMax: 37,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'gala',
        label: 'Monter un gala à ton nom',
        stance: 'media_savvy',
        riskPreview: 'Rayonnement gagné, somme et énergie mobilisées.',
        immediate: [fx.cash(-25000), fx.res('popularite', 6)],
        hidden: [fx.hidden('ambition', 1)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.rel('fans', 5)])])],
      }),
      choice({
        id: 'discret',
        label: 'Faire un don discret',
        stance: 'ethical',
        riskPreview: 'Argent gardé, rayonnement moindre.',
        immediate: [fx.cash(-6000), fx.res('bienEtre', 3)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_dep_optimisation',
    title: 'Le montage fiscal trop beau',
    body: 'Un conseiller te vante un montage fiscal agressif qui allégerait fortement tes impôts. L’adopter grossit tes économies et te met dans le viseur d’un contrôle. Rester dans les clous protège ta tranquillité et te laisse payer plein pot pendant que d’autres optimisent sans scrupule.',
    category: 'money',
    tags: ['depenses', 'fiscalite', 'risque'],
    rarity: 'uncommon',
    weight: 4,
    ageMin: 22,
    ageMax: 37,
    cooldownSeasons: 6,
    choices: [
      choice({
        id: 'optimiser',
        label: 'Adopter le montage agressif',
        stance: 'high_risk',
        riskPreview: 'Économies grossies, contrôle qui guette.',
        immediate: [fx.cash(30000), fx.res('discipline', -3)],
        hidden: [fx.hidden('ambition', 1)],
        delayed: [fx.delayed(2, [fx.chance(0.35, [fx.res('reputationSportive', -6)])])],
      }),
      choice({
        id: 'clous',
        label: 'Rester dans les clous',
        stance: 'ethical',
        riskPreview: 'Tranquillité gardée, plein pot payé.',
        immediate: [fx.res('discipline', 3), fx.res('financesPersonnelles', -3)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_dep_couple_train',
    title: 'Le grand train de vie du couple',
    body: 'Ta moitié rêve d’un standing éclatant que tes revenus semblent permettre. Suivre cette cadence renforce votre bonheur et gonfle des dépenses difficiles à réduire. Freiner par prudence protège ton avenir et installe des tensions au sein du couple.',
    category: 'lifestyle',
    tags: ['depenses', 'couple', 'train_de_vie'],
    rarity: 'common',
    weight: 5,
    ageMin: 21,
    ageMax: 36,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'suivre',
        label: 'Suivre la cadence',
        stance: 'emotional',
        riskPreview: 'Bonheur renforcé, dépenses dures à réduire.',
        immediate: [fx.rel('partner', 8), fx.res('financesPersonnelles', -5)],
        hidden: [fx.hidden('loyaute', 1)],
        delayed: [fx.delayed(2, [fx.chance(0.4, [fx.res('financesPersonnelles', -6)])])],
      }),
      choice({
        id: 'freiner',
        label: 'Freiner par prudence',
        stance: 'prudent',
        riskPreview: 'Avenir protégé, tensions dans le couple.',
        immediate: [fx.res('financesPersonnelles', 5), fx.rel('partner', -6)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_dep_securite',
    title: 'Ta sécurité a un prix',
    body: 'Après des menaces, un service de sécurité coûteux te propose une protection permanente. L’engager apaise ta famille et ampute sérieusement ton budget. T’en passer garde ton argent et te laisse, toi et les tiens, exposés à une inquiétude qui ne dort jamais.',
    category: 'lifestyle',
    tags: ['depenses', 'securite', 'famille'],
    rarity: 'uncommon',
    weight: 4,
    ageMin: 22,
    ageMax: 37,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'engager',
        label: 'Engager la sécurité',
        stance: 'prudent',
        riskPreview: 'Famille apaisée, budget amputé.',
        immediate: [fx.cash(-28000), fx.rel('family', 6)],
        hidden: [fx.hidden('professionnalisme', 1)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('bienEtre', 4)])])],
      }),
      choice({
        id: 'sans',
        label: 'T’en passer',
        stance: 'financial',
        riskPreview: 'Argent gardé, inquiétude permanente.',
        immediate: [fx.res('financesPersonnelles', 4), fx.res('bienEtre', -4)],
        hidden: [fx.hidden('resistancePression', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_dep_fete_privee',
    title: 'Une fête digne d’une légende',
    body: 'Tu veux marquer le coup avec une fête privée démesurée pour tes proches. La déployer soude ton entourage et brûle une somme rondelette en une nuit. La jouer sobre garde ton argent et laisse une occasion de communion s’éteindre sans éclat.',
    category: 'lifestyle',
    tags: ['depenses', 'fete', 'entourage'],
    rarity: 'common',
    weight: 5,
    ageMin: 20,
    ageMax: 35,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'demesuree',
        label: 'Déployer la grande fête',
        stance: 'emotional',
        riskPreview: 'Entourage soudé, somme brûlée en une nuit.',
        immediate: [fx.cash(-22000), fx.rel('friends', 7)],
        hidden: [fx.hidden('loyaute', 1)],
      }),
      choice({
        id: 'sobre',
        label: 'La jouer sobre',
        stance: 'prudent',
        riskPreview: 'Argent gardé, communion sans éclat.',
        immediate: [fx.res('financesPersonnelles', 4), fx.rel('friends', -3)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_dep_conseiller',
    title: 'Un gestionnaire de fortune coûteux',
    body: 'Un gestionnaire réputé propose de piloter ton patrimoine, honoraires costauds à la clé. Le confier optimise tes finances et te délègue le contrôle de ton argent. Gérer seul économise ses commissions et t’expose aux erreurs d’un amateur face à des sommes qui donnent le vertige.',
    category: 'money',
    tags: ['depenses', 'patrimoine', 'gestion'],
    rarity: 'common',
    weight: 5,
    ageMin: 21,
    ageMax: 37,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'confier',
        label: 'Confier à un gestionnaire',
        stance: 'prudent',
        riskPreview: 'Finances optimisées, contrôle délégué.',
        immediate: [fx.res('financesPersonnelles', 3), fx.cash(-12000)],
        hidden: [fx.hidden('professionnalisme', 2)],
        delayed: [fx.delayed(2, [fx.chance(0.4, [fx.cash(30000)])])],
      }),
      choice({
        id: 'seul',
        label: 'Gérer ton argent seul',
        stance: 'individualist',
        riskPreview: 'Commissions économisées, erreurs d’amateur possibles.',
        immediate: [fx.res('financesPersonnelles', 2), fx.res('bienEtre', -2)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_dep_frere_carriere',
    title: 'Financer le rêve de ton frère',
    body: 'Ton frère veut percer dans un domaine incertain et compte sur ton argent. Le financer soutient un rêve familial et engloutit des fonds sans certitude de retour. Refuser protège ton patrimoine et fissure un lien fraternel qui pensait pouvoir compter sur toi.',
    category: 'money',
    tags: ['depenses', 'famille', 'entourage'],
    rarity: 'common',
    weight: 5,
    ageMin: 20,
    ageMax: 37,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'financer',
        label: 'Financer le rêve fraternel',
        stance: 'emotional',
        riskPreview: 'Rêve soutenu, fonds engloutis sans certitude.',
        immediate: [fx.cash(-30000), fx.rel('family', 7)],
        hidden: [fx.hidden('loyaute', 2)],
        delayed: [fx.delayed(2, [fx.chance(0.4, [fx.rel('family', -5)])])],
      }),
      choice({
        id: 'refuser',
        label: 'Protéger ton patrimoine',
        stance: 'financial',
        riskPreview: 'Patrimoine protégé, lien fraternel fissuré.',
        immediate: [fx.res('financesPersonnelles', 4), fx.rel('family', -7)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_dep_ecole_enfants',
    title: 'Le meilleur pour tes enfants',
    body: 'Tu peux offrir à tes enfants une éducation d’élite hors de prix. La financer sécurise leur avenir et pèse chaque année sur ton budget. Choisir plus modeste préserve ton patrimoine et te laisse le doute d’avoir privé les tiens du meilleur alors que tu le pouvais.',
    category: 'lifestyle',
    tags: ['depenses', 'famille', 'avenir'],
    rarity: 'common',
    weight: 5,
    ageMin: 26,
    ageMax: 38,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'elite',
        label: 'Offrir l’éducation d’élite',
        stance: 'emotional',
        riskPreview: 'Avenir des enfants sécurisé, budget alourdi.',
        immediate: [fx.cash(-24000), fx.rel('family', 7)],
        hidden: [fx.hidden('loyaute', 2)],
        delayed: [fx.delayed(2, [fx.chance(0.3, [fx.res('financesPersonnelles', -5)])])],
      }),
      choice({
        id: 'modeste',
        label: 'Choisir plus modeste',
        stance: 'prudent',
        riskPreview: 'Patrimoine préservé, doute lancinant.',
        immediate: [fx.res('financesPersonnelles', 4), fx.res('moral', -3)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),
]
