import { dilemma, choice, fx } from '../helpers'
import type { DilemmaDefinition } from '../../../game-engine/dilemmas'

/**
 * Phase 9 — Fin de carrière (angle économique). Compromis réels, ≥2 dimensions.
 * ageMin élevé — garde-fou moteur sur la catégorie career_end.
 */
export const finDilemmas: DilemmaDefinition[] = [
  dilemma({
    id: 'p9_fin_derniere_offre',
    title: 'Le dernier gros chèque',
    body: 'À l’heure du crépuscule, une ligue lointaine pose un pont d’or pour un ultime contrat. L’accepter sécurise ton après-carrière et t’éloigne des tiens pour une saison exotique. Raccrocher dignement chez toi préserve ta fin de conte et laisse filer une fortune tardive.',
    category: 'career_end',
    tags: ['fin_carriere', 'argent', 'derniere_offre'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 32,
    ageMax: 38,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'accepter',
        label: 'Prendre le dernier gros chèque',
        stance: 'financial',
        riskPreview: 'Après-carrière sécurisé, exil d’une saison.',
        immediate: [fx.flag('transfer_accepted'), fx.cash(80000), fx.rel('family', -5)],
        hidden: [fx.hidden('ambition', 1)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('moral', -6)])])],
      }),
      choice({
        id: 'raccrocher',
        label: 'Raccrocher dignement chez toi',
        stance: 'loyal',
        riskPreview: 'Belle fin de conte, fortune tardive laissée.',
        immediate: [fx.rel('fans', 7), fx.res('financesPersonnelles', -4)],
        hidden: [fx.hidden('loyaute', 3)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_fin_sommet_ou_saison',
    title: 'Partir au sommet ou une saison de plus',
    body: 'Tu sors d’une saison référence : t’arrêter là graverait une image parfaite. Raccrocher au zénith fige une légende sans tache et te prive d’un dernier salaire. Rejouer une saison ajoute des gains et menace de ternir un tableau que tout le monde admire.',
    category: 'career_end',
    tags: ['fin_carriere', 'sommet', 'heritage'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 31,
    ageMax: 38,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'sommet',
        label: 'Partir au sommet',
        stance: 'loyal',
        riskPreview: 'Légende figée, dernier salaire perdu.',
        immediate: [fx.flag('wants_retirement'), fx.rel('fans', 8), fx.res('financesPersonnelles', -3)],
        hidden: [fx.hidden('loyaute', 2)],
      }),
      choice({
        id: 'saison',
        label: 'Rejouer une saison',
        stance: 'resilient',
        riskPreview: 'Gains ajoutés, tableau menacé de ternir.',
        immediate: [fx.res('financesPersonnelles', 4), fx.res('fatigue', 5)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.35, [fx.res('reputationSportive', -5)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p9_fin_costume_dirigeant',
    title: 'Le costume de dirigeant',
    body: 'Un club t’offre un poste de direction bien rémunéré, à condition d’arrêter maintenant. Enfiler le costume assure ton avenir et referme brutalement ta vie de joueur. Refuser pour continuer garde le maillot et laisse filer une reconversion en or offerte au bon moment.',
    category: 'career_end',
    tags: ['fin_carriere', 'reconversion', 'argent'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 32,
    ageMax: 38,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'costume',
        label: 'Enfiler le costume de dirigeant',
        stance: 'professional',
        riskPreview: 'Avenir assuré, vie de joueur refermée.',
        immediate: [fx.flag('wants_retirement'), fx.res('financesPersonnelles', 6), fx.res('moral', -3)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
      choice({
        id: 'continuer',
        label: 'Refuser pour continuer à jouer',
        stance: 'resilient',
        riskPreview: 'Maillot gardé, reconversion en or manquée.',
        immediate: [fx.res('moral', 4), fx.res('financesPersonnelles', -3)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('fatigue', 6)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p9_fin_jubile',
    title: 'Un jubilé qui remplit les caisses',
    body: 'On te propose d’organiser un jubilé grandiose, moitié hommage moitié tiroir-caisse. Le monter t’offre une somme et un adieu spectaculaire, au risque de sentir l’opération commerciale. Le refuser garde ta sortie sobre et prive tes fans d’une dernière communion.',
    category: 'career_end',
    tags: ['fin_carriere', 'jubile', 'argent'],
    rarity: 'common',
    weight: 5,
    ageMin: 32,
    ageMax: 38,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'monter',
        label: 'Monter le grand jubilé',
        stance: 'media_savvy',
        riskPreview: 'Somme et adieu spectaculaires, parfum commercial.',
        immediate: [fx.cash(45000), fx.res('reputationSportive', -2)],
        hidden: [fx.hidden('ambition', 1)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.rel('fans', 6)])])],
      }),
      choice({
        id: 'sobre',
        label: 'Garder une sortie sobre',
        stance: 'ethical',
        riskPreview: 'Sortie digne, dernière communion perdue.',
        immediate: [fx.res('bienEtre', 3), fx.res('financesPersonnelles', -2)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_fin_mentor_paye_peu',
    title: 'Finir en mentor mal payé',
    body: 'Un club jeune te veut comme guide de vestiaire pour un salaire symbolique. Accepter ce rôle nourrit ton héritage et rogne tes derniers gros revenus. Chercher un dernier contrat lucratif ailleurs remplit le compte et te prive d’une mission de transmission qui donnerait du sens.',
    category: 'career_end',
    tags: ['fin_carriere', 'transmission', 'salaire'],
    rarity: 'common',
    weight: 5,
    ageMin: 31,
    ageMax: 38,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'mentor',
        label: 'Finir en mentor',
        stance: 'loyal',
        riskPreview: 'Héritage nourri, derniers gros revenus rognés.',
        immediate: [fx.rel('teammates', 7), fx.res('financesPersonnelles', -4)],
        hidden: [fx.hidden('loyaute', 3)],
        delayed: [fx.delayed(1, [fx.flag('fan_favorite'), fx.chance(0.4, [fx.rel('fans', 5)])])],
      }),
      choice({
        id: 'contrat',
        label: 'Chercher un dernier contrat lucratif',
        stance: 'financial',
        riskPreview: 'Compte rempli, mission de sens perdue.',
        immediate: [fx.cash(35000), fx.rel('teammates', -3)],
        hidden: [fx.hidden('ambition', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_fin_vendre_vie',
    title: 'Vendre ton histoire, tout de suite',
    body: 'Un groupe veut acheter d’un bloc tes droits d’image et ta légende naissante. Vendre maintenant sécurise une fortune et cède le contrôle de ton récit à des tiers. Garder la main préserve ton indépendance et parie sur une valeur future que rien ne garantit.',
    category: 'career_end',
    tags: ['fin_carriere', 'image', 'patrimoine'],
    rarity: 'uncommon',
    weight: 4,
    ageMin: 31,
    ageMax: 38,
    cooldownSeasons: 6,
    choices: [
      choice({
        id: 'vendre',
        label: 'Vendre ton histoire',
        stance: 'financial',
        riskPreview: 'Fortune sécurisée, récit cédé à des tiers.',
        immediate: [fx.cash(75000), fx.res('popularite', -3)],
        hidden: [fx.hidden('constance', 1)],
        delayed: [fx.delayed(2, [fx.chance(0.3, [fx.res('reputationSportive', -4)])])],
      }),
      choice({
        id: 'garder',
        label: 'Garder la main sur ton récit',
        stance: 'ambitious',
        riskPreview: 'Indépendance gardée, valeur future incertaine.',
        immediate: [fx.res('popularite', 3), fx.res('financesPersonnelles', -4)],
        hidden: [fx.hidden('ambition', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_fin_retour_racines',
    title: 'Un dernier tour chez toi',
    body: 'Ton tout premier club te tend un contrat symbolique pour finir là où tout a commencé. Y retourner scelle une boucle émouvante et t’éloigne d’offres bien plus lucratives. Poursuivre ailleurs remplit une dernière fois le compte et laisse un adieu aux racines à l’état de rêve.',
    category: 'career_end',
    tags: ['fin_carriere', 'retour', 'fidelite'],
    rarity: 'common',
    weight: 5,
    ageMin: 32,
    ageMax: 38,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'retourner',
        label: 'Boucler la boucle chez toi',
        stance: 'loyal',
        riskPreview: 'Boucle émouvante, offres lucratives laissées.',
        immediate: [fx.flag('transfer_accepted'), fx.flag('home_return'), fx.rel('fans', 8), fx.res('financesPersonnelles', -3)],
        hidden: [fx.hidden('loyaute', 3)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('bienEtre', 5)])])],
      }),
      choice({
        id: 'ailleurs',
        label: 'Un dernier chèque ailleurs',
        stance: 'financial',
        riskPreview: 'Compte rempli, adieu aux racines rêvé.',
        immediate: [fx.cash(40000), fx.rel('fans', -5)],
        hidden: [fx.hidden('ambition', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_fin_investir_apres',
    title: 'Tout miser sur l’après',
    body: 'Ta reconversion demande d’engager dès maintenant une large part de tes économies. Investir gros prépare une seconde vie florissante et met en péril ta sécurité si le foot s’arrête tôt. Attendre la retraite garde ton matelas intact et retarde un projet qui n’attend que toi.',
    category: 'career_end',
    tags: ['fin_carriere', 'investissement', 'reconversion'],
    rarity: 'uncommon',
    weight: 4,
    ageMin: 30,
    ageMax: 37,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'investir',
        label: 'Engager gros dans l’après',
        stance: 'ambitious',
        riskPreview: 'Seconde vie préparée, sécurité en péril.',
        immediate: [
          fx.makeInvestment({ investmentId: 'p9_reconversion', label: 'Projet de reconversion', cost: 65000, sector: 'entreprise' }),
          fx.res('moral', 3),
        ],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(3, [fx.chance(0.5, [fx.cash(60000)]), fx.chance(0.3, [fx.cash(-30000)])])],
      }),
      choice({
        id: 'attendre',
        label: 'Attendre la retraite',
        stance: 'prudent',
        riskPreview: 'Matelas intact, projet retardé.',
        immediate: [fx.res('financesPersonnelles', 4), fx.res('moral', -2)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_fin_tournee_exhibition',
    title: 'Une tournée d’adieu payante',
    body: 'Des organisateurs te proposent une tournée d’exhibitions à travers le monde, grasse rémunération à la clé. La faire remplit tes poches et t’épuise loin des tiens pour un football sans enjeu. La décliner préserve ton énergie et referme une manne facile qu’on n’offre qu’aux légendes.',
    category: 'career_end',
    tags: ['fin_carriere', 'argent', 'exhibition'],
    rarity: 'common',
    weight: 4,
    ageMin: 32,
    ageMax: 38,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'tournee',
        label: 'Faire la tournée d’adieu',
        stance: 'financial',
        riskPreview: 'Poches remplies, épuisement loin des tiens.',
        immediate: [fx.cash(55000), fx.res('fatigue', 5)],
        hidden: [fx.hidden('ambition', 1)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.rel('family', -5)])])],
      }),
      choice({
        id: 'decliner',
        label: 'Décliner la tournée',
        stance: 'professional',
        riskPreview: 'Énergie préservée, manne facile refermée.',
        immediate: [fx.res('bienEtre', 4), fx.res('financesPersonnelles', -3)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_fin_transmission_empire',
    title: 'Léguer ou vendre ton empire',
    body: 'Tes affaires prospèrent : les confier à ta famille ou tout vendre pour du cash immédiat ? Transmettre aux tiens pérennise un héritage et t’expose aux querelles familiales autour de l’argent. Vendre en bloc sécurise une somme nette et efface l’œuvre patiemment bâtie.',
    category: 'career_end',
    tags: ['fin_carriere', 'patrimoine', 'famille'],
    rarity: 'uncommon',
    weight: 4,
    ageMin: 32,
    ageMax: 38,
    cooldownSeasons: 6,
    choices: [
      choice({
        id: 'leguer',
        label: 'Léguer à ta famille',
        stance: 'loyal',
        riskPreview: 'Héritage pérennisé, querelles familiales possibles.',
        immediate: [fx.rel('family', 8), fx.res('financesPersonnelles', -2)],
        hidden: [fx.hidden('loyaute', 3)],
        delayed: [fx.delayed(2, [fx.chance(0.3, [fx.rel('family', -6)])])],
      }),
      choice({
        id: 'vendre',
        label: 'Vendre en bloc',
        stance: 'financial',
        riskPreview: 'Somme nette sécurisée, œuvre effacée.',
        immediate: [fx.cash(70000), fx.rel('family', -4)],
        hidden: [fx.hidden('constance', 1)],
      }),
    ],
  }),
]
