import { dilemma, choice, fx } from '../helpers'
import type { DilemmaDefinition } from '../../../game-engine/dilemmas'

/**
 * Phase 9 — Investissements & patrimoine. Placements narratifs simples, à
 * échéance connue. Certains produisent un événement plusieurs saisons après.
 * Jamais d'argent réel, aucune mécanique de pari.
 */
export const investissementsDilemmas: DilemmaDefinition[] = [
  dilemma({
    id: 'p9_inv_club_formateur',
    title: 'Investir dans ton club formateur',
    body: 'Le petit club qui t’a tout appris cherche des fonds pour survivre. Y injecter ton argent grave ton nom dans son histoire et engage une somme au retour incertain. T’abstenir protège ton patrimoine et laisse peut-être disparaître le berceau de ta carrière.',
    category: 'money',
    tags: ['investissement', 'club', 'heritage'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 24,
    ageMax: 38,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'investir',
        label: 'Sauver ton club formateur',
        stance: 'loyal',
        riskPreview: 'Nom gravé, somme au retour incertain.',
        immediate: [
          fx.makeInvestment({ investmentId: 'p9_club_formateur', label: 'Club formateur', cost: 70000, sector: 'sport' }),
          fx.res('reputationSportive', 3),
        ],
        hidden: [fx.hidden('loyaute', 3)],
        delayed: [fx.delayed(3, [fx.chance(0.5, [fx.rel('fans', 8)]), fx.chance(0.3, [fx.cash(-30000)])])],
      }),
      choice({
        id: 'abstenir',
        label: 'Protéger ton patrimoine',
        stance: 'financial',
        riskPreview: 'Patrimoine protégé, berceau menacé.',
        immediate: [fx.res('financesPersonnelles', 4), fx.rel('fans', -4)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_inv_vignoble',
    title: 'Un domaine viticole à ton nom',
    body: 'Un vignoble prestigieux cherche un investisseur au long cours. En prendre une part bâtit un patrimoine de terroir et immobilise tes fonds des années durant. Passer ton tour garde tes liquidités et laisse filer un placement aussi patient que gratifiant.',
    category: 'money',
    tags: ['investissement', 'patrimoine'],
    rarity: 'common',
    weight: 5,
    ageMin: 25,
    ageMax: 38,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'investir',
        label: 'Investir dans le vignoble',
        stance: 'financial',
        riskPreview: 'Patrimoine de terroir, fonds immobilisés longtemps.',
        immediate: [
          fx.makeInvestment({ investmentId: 'p9_vignoble', label: 'Domaine viticole', cost: 80000, sector: 'patrimoine' }),
          fx.res('bienEtre', 2),
        ],
        hidden: [fx.hidden('constance', 2)],
        delayed: [fx.delayed(4, [fx.chance(0.6, [fx.cash(50000)]), fx.chance(0.2, [fx.cash(-25000)])])],
      }),
      choice({
        id: 'passer',
        label: 'Garder tes liquidités',
        stance: 'prudent',
        riskPreview: 'Liquidités gardées, placement patient manqué.',
        immediate: [fx.res('financesPersonnelles', 3), fx.res('moral', -1)],
        hidden: [fx.hidden('professionnalisme', 1)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_inv_hotel',
    title: 'Un hôtel de charme',
    body: 'Des associés te proposent d’ouvrir un hôtel de charme dans une ville prisée. Y investir crée un actif visible et t’entraîne dans un métier exigeant que tu ne connais pas. Refuser garde ton argent tranquille et te prive d’un projet qui aurait pu porter ton nom.',
    category: 'money',
    tags: ['investissement', 'entreprise'],
    rarity: 'common',
    weight: 5,
    ageMin: 24,
    ageMax: 38,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'investir',
        label: 'Ouvrir l’hôtel de charme',
        stance: 'ambitious',
        riskPreview: 'Actif visible, métier exigeant inconnu.',
        immediate: [
          fx.makeInvestment({ investmentId: 'p9_hotel', label: 'Hôtel de charme', cost: 75000, sector: 'entreprise' }),
          fx.res('popularite', 2),
        ],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(3, [fx.chance(0.5, [fx.cash(55000)]), fx.chance(0.35, [fx.cash(-35000)])])],
      }),
      choice({
        id: 'refuser',
        label: 'Garder ton argent tranquille',
        stance: 'prudent',
        riskPreview: 'Argent tranquille, projet à ton nom manqué.',
        immediate: [fx.res('financesPersonnelles', 4), fx.res('moral', -2)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_inv_esport',
    title: 'Une équipe d’esport à racheter',
    body: 'Un collectif d’esport monte et cherche un mécène pour exploser. En prendre les rênes te branche sur une jeunesse énorme et parie sur un secteur volatil. Décliner garde ton capital au sec et laisse filer une vitrine que ta génération adore.',
    category: 'money',
    tags: ['investissement', 'esport', 'image'],
    rarity: 'uncommon',
    weight: 4,
    ageMin: 21,
    ageMax: 35,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'investir',
        label: 'Racheter l’équipe d’esport',
        stance: 'high_risk',
        riskPreview: 'Vitrine jeunesse, secteur volatil.',
        immediate: [
          fx.makeInvestment({ investmentId: 'p9_esport', label: 'Équipe esport', cost: 50000, sector: 'technologie' }),
          fx.res('popularite', 4),
        ],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(3, [fx.chance(0.4, [fx.cash(70000)]), fx.chance(0.45, [fx.cash(-30000)])])],
      }),
      choice({
        id: 'decliner',
        label: 'Garder ton capital au sec',
        stance: 'prudent',
        riskPreview: 'Capital protégé, vitrine générationnelle manquée.',
        immediate: [fx.res('financesPersonnelles', 3), fx.res('popularite', -2)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_inv_energie',
    title: 'Un parc d’énergie propre',
    body: 'Un projet d’énergie renouvelable cherche des fonds pour sortir de terre. Y participer aligne ton image sur une cause d’avenir et bloque ton capital sur un rendement lent. Renoncer garde tes billes disponibles et te prive d’un placement aussi vertueux que patient.',
    category: 'money',
    tags: ['investissement', 'energie'],
    rarity: 'common',
    weight: 4,
    ageMin: 23,
    ageMax: 38,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'investir',
        label: 'Financer l’énergie propre',
        stance: 'ethical',
        riskPreview: 'Image d’avenir, capital bloqué et lent.',
        immediate: [
          fx.makeInvestment({ investmentId: 'p9_energie', label: 'Parc solaire', cost: 60000, sector: 'entreprise' }),
          fx.res('popularite', 3),
        ],
        hidden: [fx.hidden('professionnalisme', 1)],
        delayed: [fx.delayed(4, [fx.chance(0.6, [fx.cash(45000)]), fx.chance(0.2, [fx.cash(-20000)])])],
      }),
      choice({
        id: 'renoncer',
        label: 'Garder tes billes disponibles',
        stance: 'prudent',
        riskPreview: 'Liquidités gardées, placement vertueux manqué.',
        immediate: [fx.res('financesPersonnelles', 3), fx.res('popularite', -1)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_inv_locatif',
    title: 'Un parc d’appartements à louer',
    body: 'Un promoteur te propose d’acheter plusieurs logements à mettre en location. Bâtir ce parc génère des revenus réguliers et t’expose aux tracas de propriétaire. Rester à l’écart garde ta trésorerie souple et laisse dormir une source de rente que beaucoup t’envieraient.',
    category: 'money',
    tags: ['investissement', 'immobilier', 'rente'],
    rarity: 'common',
    weight: 5,
    ageMin: 24,
    ageMax: 38,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'investir',
        label: 'Bâtir ton parc locatif',
        stance: 'financial',
        riskPreview: 'Revenus réguliers, tracas de propriétaire.',
        immediate: [
          fx.makeInvestment({ investmentId: 'p9_locatif', label: 'Parc locatif', cost: 90000, sector: 'immobilier' }),
          fx.res('fatigue', 2),
        ],
        hidden: [fx.hidden('professionnalisme', 2)],
        delayed: [fx.delayed(3, [fx.chance(0.65, [fx.cash(40000)]), fx.chance(0.2, [fx.cash(-20000)])])],
      }),
      choice({
        id: 'ecart',
        label: 'Garder ta trésorerie souple',
        stance: 'prudent',
        riskPreview: 'Souplesse gardée, source de rente endormie.',
        immediate: [fx.res('financesPersonnelles', 4), fx.res('moral', -2)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_inv_marque_perso',
    title: 'Lancer ta propre marque',
    body: 'Créer ta griffe de vêtements transformerait ta notoriété en business. La lancer capitalise sur ton image et engage des fonds sur un marché impitoyable. Y renoncer garde ton argent à l’abri et laisse ton nom sans empreinte commerciale propre.',
    category: 'money',
    tags: ['investissement', 'marque', 'image'],
    rarity: 'uncommon',
    weight: 4,
    ageMin: 22,
    ageMax: 36,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'lancer',
        label: 'Lancer ta griffe',
        stance: 'ambitious',
        riskPreview: 'Image capitalisée, marché impitoyable.',
        immediate: [
          fx.makeInvestment({ investmentId: 'p9_marque', label: 'Marque personnelle', cost: 55000, sector: 'mode' }),
          fx.res('popularite', 4),
        ],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(3, [fx.chance(0.45, [fx.cash(60000)]), fx.chance(0.4, [fx.cash(-30000)])])],
      }),
      choice({
        id: 'renoncer',
        label: 'Garder ton argent à l’abri',
        stance: 'prudent',
        riskPreview: 'Argent à l’abri, empreinte commerciale absente.',
        immediate: [fx.res('financesPersonnelles', 3), fx.res('popularite', -2)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_inv_academie',
    title: 'Une académie de jeunes à ton nom',
    body: 'Fonder une académie formerait les talents de demain et porterait ton héritage. La bâtir engage un capital lourd et te lie à un projet de très longue haleine. Reporter garde tes finances légères et diffère un rêve de transmission qui te tient à cœur.',
    category: 'money',
    tags: ['investissement', 'academie', 'heritage'],
    rarity: 'uncommon',
    weight: 4,
    ageMin: 27,
    ageMax: 38,
    cooldownSeasons: 6,
    choices: [
      choice({
        id: 'fonder',
        label: 'Fonder l’académie',
        stance: 'ethical',
        riskPreview: 'Héritage bâti, capital lourd engagé.',
        immediate: [
          fx.makeInvestment({ investmentId: 'p9_academie', label: 'Académie de jeunes', cost: 95000, sector: 'sport' }),
          fx.res('reputationSportive', 3),
        ],
        hidden: [fx.hidden('loyaute', 2)],
        delayed: [fx.delayed(4, [fx.chance(0.5, [fx.rel('fans', 8)]), fx.chance(0.25, [fx.cash(-30000)])])],
      }),
      choice({
        id: 'reporter',
        label: 'Reporter le projet',
        stance: 'prudent',
        riskPreview: 'Finances légères, rêve de transmission différé.',
        immediate: [fx.res('financesPersonnelles', 4), fx.res('moral', -2)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_inv_ami_projet',
    title: 'Le projet d’un ancien coéquipier',
    body: 'Un ancien partenaire te propose d’entrer au capital de son application prometteuse. Investir soutient un ami et parie sur une idée séduisante mais fragile. Refuser protège tes fonds et peut froisser une amitié bâtie sur les terrains d’avant la gloire.',
    category: 'money',
    tags: ['investissement', 'amitie', 'technologie'],
    rarity: 'common',
    weight: 5,
    ageMin: 21,
    ageMax: 36,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'investir',
        label: 'Entrer au capital',
        stance: 'emotional',
        riskPreview: 'Ami soutenu, idée séduisante mais fragile.',
        immediate: [
          fx.makeInvestment({ investmentId: 'p9_app_ami', label: 'Application d’un ami', cost: 40000, sector: 'technologie' }),
          fx.rel('friends', 6),
        ],
        hidden: [fx.hidden('loyaute', 2)],
        delayed: [fx.delayed(3, [fx.chance(0.4, [fx.cash(55000)]), fx.chance(0.45, [fx.rel('friends', -6)])])],
      }),
      choice({
        id: 'refuser',
        label: 'Protéger tes fonds',
        stance: 'financial',
        riskPreview: 'Fonds protégés, amitié froissée.',
        immediate: [fx.res('financesPersonnelles', 4), fx.rel('friends', -5)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_inv_fonds_volatil',
    title: 'Un fonds au rendement fou',
    body: 'Un fonds ultra-volatil promet des rendements spectaculaires, ou des pertes tout aussi brutales. Y placer une part vise un gros gain et met une somme sérieuse en danger. L’éviter protège ton capital et te fera peut-être ronger de regret si le fonds s’envole.',
    category: 'money',
    tags: ['investissement', 'risque'],
    rarity: 'uncommon',
    weight: 4,
    ageMin: 21,
    ageMax: 37,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'placer',
        label: 'Placer dans le fonds volatil',
        stance: 'high_risk',
        riskPreview: 'Gros gain visé, somme en danger.',
        immediate: [
          fx.makeInvestment({ investmentId: 'p9_fonds', label: 'Fonds volatil', cost: 45000, sector: 'technologie' }),
          fx.res('financesPersonnelles', -2),
        ],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(2, [fx.chance(0.35, [fx.cash(80000)]), fx.chance(0.55, [fx.cash(-35000)])])],
      }),
      choice({
        id: 'eviter',
        label: 'Éviter le fonds',
        stance: 'prudent',
        riskPreview: 'Capital protégé, regret possible.',
        immediate: [fx.res('financesPersonnelles', 4), fx.res('moral', -1)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_inv_diversifier',
    title: 'Tout au même endroit ou éparpillé',
    body: 'Ton conseiller t’exhorte à diversifier tes placements plutôt qu’à tout concentrer. Diversifier lisse tes risques et dilue tes espoirs de gros gain. Concentrer sur un pari fort vise le jackpot et t’expose à tout perdre si ce seul cheval trébuche.',
    category: 'money',
    tags: ['patrimoine', 'strategie'],
    rarity: 'common',
    weight: 4,
    ageMin: 22,
    ageMax: 38,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'diversifier',
        label: 'Diversifier tes placements',
        stance: 'prudent',
        riskPreview: 'Risques lissés, gros gain dilué.',
        immediate: [fx.res('financesPersonnelles', 4), fx.res('moral', -1)],
        hidden: [fx.hidden('constance', 2)],
        delayed: [fx.delayed(2, [fx.chance(0.5, [fx.cash(20000)])])],
      }),
      choice({
        id: 'concentrer',
        label: 'Tout miser sur un pari fort',
        stance: 'high_risk',
        riskPreview: 'Jackpot visé, tout perdre si ça trébuche.',
        immediate: [fx.res('reputationSportive', 1), fx.res('financesPersonnelles', -2)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(2, [fx.chance(0.35, [fx.cash(60000)]), fx.chance(0.45, [fx.cash(-30000)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p9_inv_revente',
    title: 'Vendre à perte ou attendre',
    body: 'Un de tes actifs a plongé et pèse sur ton moral. Le revendre à perte purge la plaie et acte une moins-value douloureuse. Le garder en espérant un rebond immobilise ton argent et prolonge une incertitude qui te ronge saison après saison.',
    category: 'money',
    tags: ['patrimoine', 'gestion'],
    rarity: 'common',
    weight: 4,
    ageMin: 22,
    ageMax: 38,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'vendre',
        label: 'Vendre à perte',
        stance: 'prudent',
        riskPreview: 'Plaie purgée, moins-value actée.',
        immediate: [fx.cash(-15000), fx.res('bienEtre', 3)],
        hidden: [fx.hidden('constance', 2)],
      }),
      choice({
        id: 'garder',
        label: 'Attendre un rebond',
        stance: 'high_risk',
        riskPreview: 'Argent immobilisé, incertitude prolongée.',
        immediate: [fx.res('financesPersonnelles', -2), fx.res('moral', -2)],
        hidden: [fx.hidden('resistancePression', 2)],
        delayed: [fx.delayed(2, [fx.chance(0.4, [fx.cash(35000)]), fx.chance(0.4, [fx.cash(-20000)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p9_inv_fondation',
    title: 'Créer ta fondation',
    body: 'Fonder une œuvre à ton nom pérenniserait ton engagement bien après le foot. La créer bâtit ton héritage et engage une dotation conséquente à perpétuité. Y renoncer garde ton argent pour les tiens et laisse ton influence s’éteindre avec ta carrière.',
    category: 'money',
    tags: ['patrimoine', 'heritage', 'image'],
    rarity: 'uncommon',
    weight: 4,
    ageMin: 27,
    ageMax: 38,
    cooldownSeasons: 6,
    choices: [
      choice({
        id: 'creer',
        label: 'Créer ta fondation',
        stance: 'ethical',
        riskPreview: 'Héritage bâti, dotation conséquente engagée.',
        immediate: [fx.cash(-40000), fx.res('popularite', 5)],
        hidden: [fx.hidden('loyaute', 2)],
        delayed: [fx.delayed(2, [fx.chance(0.5, [fx.rel('fans', 6)])])],
      }),
      choice({
        id: 'renoncer',
        label: 'Garder pour les tiens',
        stance: 'prudent',
        riskPreview: 'Argent gardé, influence qui s’éteindra.',
        immediate: [fx.res('financesPersonnelles', 4), fx.res('popularite', -2)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_inv_rachat_parts',
    title: 'Racheter tes propres droits',
    body: 'Une société détient encore une part de tes droits d’image ; tu peux la racheter cher. Reprendre le contrôle libère tes revenus futurs et vide ta trésorerie d’un coup. Laisser courir garde ton cash et te fait partager tes gains commerciaux pour des années.',
    category: 'money',
    tags: ['patrimoine', 'droits', 'image'],
    rarity: 'uncommon',
    weight: 4,
    ageMin: 24,
    ageMax: 37,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'racheter',
        label: 'Racheter tes droits',
        stance: 'financial',
        riskPreview: 'Revenus futurs libérés, trésorerie vidée.',
        immediate: [fx.cash(-50000), fx.res('popularite', 2)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(3, [fx.chance(0.6, [fx.cash(45000)])])],
      }),
      choice({
        id: 'laisser',
        label: 'Laisser courir',
        stance: 'prudent',
        riskPreview: 'Cash gardé, gains partagés des années.',
        immediate: [fx.res('financesPersonnelles', 3), fx.res('popularite', -1)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_inv_epargne_blindee',
    title: 'Tout sécuriser, quitte à stagner',
    body: 'Tenté par la prudence absolue, tu envisages de tout placer sur des supports garantis. Blinder ton épargne te met à l’abri et gèle toute chance de faire fructifier gros. Garder une poche de risque vise plus haut et menace une part de ce que tu as durement gagné.',
    category: 'money',
    tags: ['patrimoine', 'strategie'],
    rarity: 'common',
    weight: 4,
    ageMin: 23,
    ageMax: 38,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'blinder',
        label: 'Tout sécuriser',
        stance: 'prudent',
        riskPreview: 'À l’abri, croissance gelée.',
        immediate: [fx.res('financesPersonnelles', 5), fx.res('moral', -2)],
        hidden: [fx.hidden('constance', 2)],
      }),
      choice({
        id: 'risque',
        label: 'Garder une poche de risque',
        stance: 'ambitious',
        riskPreview: 'Viser plus haut, une part exposée.',
        immediate: [fx.res('reputationSportive', 1), fx.res('financesPersonnelles', -2)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(2, [fx.chance(0.4, [fx.cash(40000)]), fx.chance(0.35, [fx.cash(-20000)])])],
      }),
    ],
  }),
]
