import { dilemma, choice, fx } from '../helpers'
import type { DilemmaDefinition } from '../../../game-engine/dilemmas'

/**
 * Phase 9 — Sponsors. Compromis réels, ≥2 dimensions par choix. Certains
 * signent un contrat (signSponsor), en rompent un (endSponsor) ou bloquent
 * un secteur futur (sponsor_ban).
 */
export const sponsorsDilemmas: DilemmaDefinition[] = [
  dilemma({
    id: 'p9_spo_exclusivite_bloquante',
    title: 'Une exclusivité qui ferme des portes',
    body: 'Un géant de la tech t’offre un pont d’or, à condition de t’interdire toute marque de mode pendant le contrat. Signer remplit ton compte et te prive des futures offres du luxe. Refuser garde ton champ commercial ouvert et laisse filer un chèque énorme.',
    category: 'sponsors',
    tags: ['sponsors', 'exclusivite', 'argent'],
    rarity: 'uncommon',
    weight: 7,
    ageMin: 20,
    ageMax: 34,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'signer',
        label: 'Signer l’exclusivité tech',
        stance: 'financial',
        riskPreview: 'Compte rempli, secteur mode verrouillé.',
        immediate: [
          fx.signSponsor({
            sponsorId: 'p9_nexora_max',
            name: 'Nexora Max',
            sector: 'technologie',
            prestige: 80,
            annualPay: 85000,
            durationSeasons: 3,
            imageTag: 'tech',
            reputationRisk: 12,
            exclusive: true,
          }),
          fx.flag('sponsor_ban:mode'),
          fx.res('popularite', 3),
          fx.res('bienEtre', -2),
        ],
        hidden: [fx.hidden('ambition', 1)],
      }),
      choice({
        id: 'refuser',
        label: 'Garder ton champ ouvert',
        stance: 'ambitious',
        riskPreview: 'Options gardées, chèque énorme refusé.',
        immediate: [fx.res('popularite', 2), fx.res('financesPersonnelles', -4)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_spo_local_fidele',
    title: 'La petite marque de ton enfance',
    body: 'Une marque locale qui t’a habillé gamin veut t’associer, pour trois fois rien. Signer avec elle réchauffe ton image de terroir et rapporte des clopinettes. Chasser des contrats plus juteux gonfle tes revenus et snobe ceux qui t’ont soutenu avant la gloire.',
    category: 'sponsors',
    tags: ['sponsors', 'local', 'fidelite'],
    rarity: 'common',
    weight: 6,
    ageMin: 19,
    ageMax: 37,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'signer',
        label: 'Signer avec la marque locale',
        stance: 'loyal',
        riskPreview: 'Image de terroir, revenus dérisoires.',
        immediate: [
          fx.signSponsor({
            sponsorId: 'p9_brume_racines',
            name: 'Racines Brume',
            sector: 'marque_locale',
            prestige: 28,
            annualPay: 9000,
            durationSeasons: 2,
            imageTag: 'local',
            reputationRisk: 4,
            exclusive: false,
          }),
          fx.rel('fans', 6),
          fx.res('financesPersonnelles', -2),
        ],
        hidden: [fx.hidden('loyaute', 2)],
      }),
      choice({
        id: 'chasser',
        label: 'Chasser plus juteux',
        stance: 'financial',
        riskPreview: 'Revenus gonflés, soutiens d’avant snobés.',
        immediate: [fx.res('financesPersonnelles', 3), fx.rel('fans', -4)],
        hidden: [fx.hidden('ambition', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_spo_controverse',
    title: 'L’argent sale d’un sponsor voyou',
    body: 'Une marque au sulfureux parfum aligne une somme indécente pour ton image. Encaisser règle bien des soucis et t’associe à une réputation toxique. Refuser protège ton image et laisse filer un chèque qui hante longtemps les regrets.',
    category: 'sponsors',
    tags: ['sponsors', 'ethique', 'argent'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 20,
    ageMax: 36,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'encaisser',
        label: 'Encaisser malgré la controverse',
        stance: 'financial',
        riskPreview: 'Soucis réglés, réputation toxique collée.',
        immediate: [fx.cash(60000), fx.res('reputationSportive', -5)],
        hidden: [fx.hidden('ambition', 1)],
        delayed: [fx.delayed(1, [fx.chance(0.35, [fx.rel('fans', -6)])])],
      }),
      choice({
        id: 'refuser',
        label: 'Refuser l’argent sale',
        stance: 'ethical',
        riskPreview: 'Image protégée, magot laissé.',
        immediate: [fx.res('reputationSportive', 4), fx.res('financesPersonnelles', -3)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_spo_rupture_image',
    title: 'Ton sponsor plombe ton image',
    body: 'Un scandale éclabousse une de tes marques et déteint sur toi. Rompre le contrat coupe le lien toxique et t’expose à une pénalité douloureuse. L’honorer jusqu’au bout respecte ta signature et te fait porter le poids d’un partenaire devenu infréquentable.',
    category: 'sponsors',
    tags: ['sponsors', 'rupture', 'image'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 19,
    ageMax: 37,
    cooldownSeasons: 5,
    prerequisites: [{ type: 'hasFlag', key: 'sponsor_active' }],
    choices: [
      choice({
        id: 'rompre',
        label: 'Rompre le contrat toxique',
        stance: 'ethical',
        riskPreview: 'Lien coupé, pénalité douloureuse.',
        immediate: [fx.endSponsor(undefined, 4), fx.cash(-25000)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
      choice({
        id: 'honorer',
        label: 'Honorer ta signature',
        stance: 'loyal',
        riskPreview: 'Parole tenue, image un temps ternie.',
        immediate: [fx.res('reputationSportive', -3), fx.rel('sponsors', 5)],
        hidden: [fx.hidden('loyaute', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('popularite', -4)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p9_spo_surenchere',
    title: 'Deux marques se disputent ton nom',
    body: 'Un prestige mondial et un discret payeur se battent pour t’avoir. Choisir le prestige dore ton image et paie moins. Choisir le gros chèque garnit ton compte et t’associe à une marque sans éclat. Une seule signature possible, l’autre partira froissée.',
    category: 'sponsors',
    tags: ['sponsors', 'prestige', 'argent'],
    rarity: 'common',
    weight: 5,
    ageMin: 20,
    ageMax: 34,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'prestige',
        label: 'Choisir le prestige',
        stance: 'ambitious',
        riskPreview: 'Image dorée, chèque plus léger.',
        immediate: [
          fx.signSponsor({
            sponsorId: 'p9_atelier_prestige',
            name: 'Atelier Prestige',
            sector: 'mode',
            prestige: 78,
            annualPay: 40000,
            durationSeasons: 2,
            imageTag: 'luxury',
            reputationRisk: 12,
            exclusive: false,
          }),
          fx.res('financesPersonnelles', -2),
        ],
        hidden: [fx.hidden('ambition', 2)],
      }),
      choice({
        id: 'cash',
        label: 'Choisir le gros chèque',
        stance: 'financial',
        riskPreview: 'Compte garni, marque sans éclat.',
        immediate: [
          fx.signSponsor({
            sponsorId: 'p9_payeur_discret',
            name: 'Payeur Discret',
            sector: 'application',
            prestige: 44,
            annualPay: 60000,
            durationSeasons: 2,
            imageTag: 'tech',
            reputationRisk: 16,
            exclusive: false,
          }),
          fx.res('popularite', -2),
        ],
        hidden: [fx.hidden('constance', 1)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_spo_clause_comportement',
    title: 'Un sponsor qui surveille ta vie',
    body: 'Une marque huppée exige une clause de comportement stricte : ni sortie, ni écart, sous peine de rupture. Signer paie grassement et met ta vie privée sous cloche. Refuser garde ta liberté de vivre et laisse filer un partenariat très rémunérateur.',
    category: 'sponsors',
    tags: ['sponsors', 'clause', 'image'],
    rarity: 'common',
    weight: 5,
    ageMin: 20,
    ageMax: 34,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'signer',
        label: 'Accepter la clause stricte',
        stance: 'financial',
        riskPreview: 'Paie grasse, vie privée sous cloche.',
        immediate: [
          fx.signSponsor({
            sponsorId: 'p9_maison_stricte',
            name: 'Maison Stricte',
            sector: 'mode',
            prestige: 70,
            annualPay: 50000,
            durationSeasons: 3,
            imageTag: 'luxury',
            reputationRisk: 14,
            exclusive: false,
          }),
          fx.res('bienEtre', -4),
        ],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
      choice({
        id: 'refuser',
        label: 'Garder ta liberté de vivre',
        stance: 'individualist',
        riskPreview: 'Liberté gardée, partenariat perdu.',
        immediate: [fx.res('bienEtre', 4), fx.res('financesPersonnelles', -3)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_spo_ambassadeur_mondial',
    title: 'Ambassadeur aux quatre coins du globe',
    body: 'Une marque planétaire veut faire de toi son visage mondial, agenda de tournages compris. Accepter décuple tes revenus commerciaux et grignote ton temps de récupération. Décliner protège ta fraîcheur sportive et referme une vitrine que le monde entier regarderait.',
    category: 'sponsors',
    tags: ['sponsors', 'mondial', 'temps'],
    rarity: 'rare',
    weight: 4,
    ageMin: 23,
    ageMax: 34,
    cooldownSeasons: 6,
    choices: [
      choice({
        id: 'accepter',
        label: 'Devenir ambassadeur mondial',
        stance: 'media_savvy',
        riskPreview: 'Revenus décuplés, récupération grignotée.',
        immediate: [
          fx.signSponsor({
            sponsorId: 'p9_globe_brand',
            name: 'Globe Brand',
            sector: 'sport',
            prestige: 90,
            annualPay: 120000,
            durationSeasons: 3,
            imageTag: 'clean',
            reputationRisk: 15,
            exclusive: false,
          }),
          fx.res('fatigue', 5),
        ],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('forme', -6)])])],
      }),
      choice({
        id: 'decliner',
        label: 'Protéger ta fraîcheur',
        stance: 'professional',
        riskPreview: 'Fraîcheur gardée, vitrine mondiale refermée.',
        immediate: [fx.res('forme', 4), fx.res('financesPersonnelles', -4)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_spo_equity_startup',
    title: 'Payé en parts, pas en cash',
    body: 'Une jeune marque te propose de la rémunérer non en argent mais en parts de son capital. Accepter parie sur son envol et t’expose à ne rien toucher si elle sombre. Exiger du cash sécurise ta rémunération et te prive d’un jackpot si la marque explose.',
    category: 'sponsors',
    tags: ['sponsors', 'equity', 'risque'],
    rarity: 'uncommon',
    weight: 4,
    ageMin: 21,
    ageMax: 35,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'parts',
        label: 'Être payé en parts',
        stance: 'high_risk',
        riskPreview: 'Envol possible, zéro si la marque sombre.',
        immediate: [fx.res('reputationSportive', 2), fx.res('financesPersonnelles', -2)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(3, [fx.chance(0.35, [fx.cash(75000)])])],
      }),
      choice({
        id: 'cash',
        label: 'Exiger du cash',
        stance: 'financial',
        riskPreview: 'Rémunération sûre, jackpot manqué.',
        immediate: [fx.cash(20000), fx.res('reputationSportive', -1)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_spo_clash_club',
    title: 'Ton sponsor contre celui du club',
    body: 'Une marque te veut alors qu’elle rivalise frontalement avec le sponsor officiel du club. Signer défend ton indépendance commerciale et agace des dirigeants pris en tenaille. Renoncer par respect du club protège ton lien interne et sacrifie un partenariat personnel lucratif.',
    category: 'sponsors',
    tags: ['sponsors', 'club', 'conflit'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 20,
    ageMax: 34,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'signer',
        label: 'Défendre ton indépendance',
        stance: 'individualist',
        riskPreview: 'Indépendance affirmée, dirigeants agacés.',
        immediate: [fx.cash(35000), fx.rel('coach', -5)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('confianceEntraineur', -4)])])],
      }),
      choice({
        id: 'renoncer',
        label: 'Renoncer par respect du club',
        stance: 'loyal',
        riskPreview: 'Lien interne protégé, contrat sacrifié.',
        immediate: [fx.rel('coach', 5), fx.res('financesPersonnelles', -3)],
        hidden: [fx.hidden('loyaute', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_spo_renouveler',
    title: 'Renouveler, mais à la baisse',
    body: 'Un sponsor arrivant à terme propose de continuer, à des conditions revues en baisse. Renouveler conserve un revenu régulier et acte ta cote commerciale déclinante. Laisser filer garde ta valeur affichée intacte et t’expose à ne rien retrouver d’équivalent.',
    category: 'sponsors',
    tags: ['sponsors', 'renouvellement'],
    rarity: 'common',
    weight: 5,
    ageMin: 21,
    ageMax: 37,
    cooldownSeasons: 4,
    prerequisites: [{ type: 'hasFlag', key: 'sponsor_active' }],
    choices: [
      choice({
        id: 'renouveler',
        label: 'Renouveler à la baisse',
        stance: 'prudent',
        riskPreview: 'Revenu régulier, cote déclinante actée.',
        immediate: [fx.res('financesPersonnelles', 3), fx.res('reputationSportive', -2)],
        hidden: [fx.hidden('constance', 2)],
      }),
      choice({
        id: 'laisser',
        label: 'Laisser filer le contrat',
        stance: 'ambitious',
        riskPreview: 'Valeur affichée gardée, vide possible.',
        immediate: [fx.endSponsor(undefined, 0), fx.res('reputationSportive', 2)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('financesPersonnelles', -4)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p9_spo_produit_douteux',
    title: 'Vanter un produit miracle',
    body: 'Une marque te paie pour vanter un complément « miracle » aux vertus douteuses. Prêter ton visage rapporte gros et engage ta crédibilité auprès de ceux qui te croient. Refuser protège ta parole et te prive d’un contrat que la morale seule fait hésiter.',
    category: 'sponsors',
    tags: ['sponsors', 'ethique', 'sante'],
    rarity: 'common',
    weight: 5,
    ageMin: 20,
    ageMax: 36,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'preter',
        label: 'Prêter ton visage au produit',
        stance: 'financial',
        riskPreview: 'Gros gain, crédibilité engagée.',
        immediate: [fx.cash(30000), fx.res('reputationSportive', -4)],
        hidden: [fx.hidden('ambition', 1)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.rel('fans', -5)])])],
      }),
      choice({
        id: 'refuser',
        label: 'Protéger ta parole',
        stance: 'ethical',
        riskPreview: 'Crédibilité gardée, contrat refusé.',
        immediate: [fx.res('reputationSportive', 3), fx.res('financesPersonnelles', -2)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_spo_cause_engagee',
    title: 'Une cause qui divise',
    body: 'Une marque engagée sur un sujet clivant veut t’associer à son combat. T’engager donne du sens à ton image et t’expose aux foudres de ceux que la cause hérisse. Rester neutre préserve ton consensus et te fait passer pour tiède aux yeux de ceux qui espéraient ton soutien.',
    category: 'sponsors',
    tags: ['sponsors', 'engagement', 'image'],
    rarity: 'uncommon',
    weight: 4,
    ageMin: 21,
    ageMax: 36,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'engager',
        label: 'T’engager pour la cause',
        stance: 'ethical',
        riskPreview: 'Image porteuse de sens, foudres possibles.',
        immediate: [
          fx.signSponsor({
            sponsorId: 'p9_cause_elan',
            name: 'Élan Engagé',
            sector: 'association',
            prestige: 42,
            annualPay: 12000,
            durationSeasons: 3,
            imageTag: 'ethical',
            reputationRisk: 20,
            exclusive: false,
          }),
          fx.res('popularite', 4),
        ],
        hidden: [fx.hidden('resistancePression', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.35, [fx.res('popularite', -5)])])],
      }),
      choice({
        id: 'neutre',
        label: 'Rester neutre',
        stance: 'prudent',
        riskPreview: 'Consensus gardé, image de tiède.',
        immediate: [fx.res('bienEtre', 3), fx.res('popularite', -3)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_spo_micro_influence',
    title: 'Petits contrats ou un gros mastodonte',
    body: 'Tu peux multiplier de petits partenariats authentiques ou tout miser sur un mastodonte unique. La constellation de micro-contrats muscle ta proximité et éparpille ton énergie. Le gros contrat unique simplifie ta vie et t’enchaîne à une seule marque toute-puissante.',
    category: 'sponsors',
    tags: ['sponsors', 'strategie'],
    rarity: 'common',
    weight: 5,
    ageMin: 19,
    ageMax: 34,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'micro',
        label: 'Multiplier les petits contrats',
        stance: 'media_savvy',
        riskPreview: 'Proximité musclée, énergie éparpillée.',
        immediate: [fx.res('popularite', 5), fx.res('fatigue', 3)],
        hidden: [fx.hidden('adaptabilite', 2)],
      }),
      choice({
        id: 'mastodonte',
        label: 'Tout miser sur un mastodonte',
        stance: 'financial',
        riskPreview: 'Vie simplifiée, dépendance à une marque.',
        immediate: [fx.cash(35000), fx.res('popularite', -2)],
        hidden: [fx.hidden('constance', 1)],
        delayed: [fx.delayed(2, [fx.chance(0.3, [fx.rel('sponsors', -4)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p9_spo_exclu_pays',
    title: 'Exclusivité dans ton pays',
    body: 'Une marque veut l’exclusivité de ton image sur ton sol natal, gros chèque à l’appui. Accepter verrouille ton marché domestique et bloque tout concurrent local. Refuser garde ton pays ouvert à d’autres et sacrifie une somme conséquente offerte pour ta seule terre d’origine.',
    category: 'sponsors',
    tags: ['sponsors', 'exclusivite', 'pays'],
    rarity: 'common',
    weight: 4,
    ageMin: 20,
    ageMax: 35,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'accepter',
        label: 'Accepter l’exclusivité nationale',
        stance: 'financial',
        riskPreview: 'Marché verrouillé, concurrents locaux bloqués.',
        immediate: [fx.cash(40000), fx.res('popularite', -2)],
        hidden: [fx.hidden('constance', 1)],
        delayed: [fx.delayed(2, [fx.chance(0.3, [fx.rel('sponsors', -4)])])],
      }),
      choice({
        id: 'refuser',
        label: 'Garder ton pays ouvert',
        stance: 'ambitious',
        riskPreview: 'Marché ouvert, somme conséquente refusée.',
        immediate: [fx.res('popularite', 3), fx.res('financesPersonnelles', -3)],
        hidden: [fx.hidden('ambition', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_spo_tournage_prepa',
    title: 'Un tournage en pleine préparation',
    body: 'Un sponsor exige un tournage lourd la semaine d’un match capital. Honorer le contrat respecte tes engagements commerciaux et sabote ta préparation. Reporter protège ton match et t’expose à une pénalité et à la colère d’une marque qui n’aime pas attendre.',
    category: 'sponsors',
    tags: ['sponsors', 'preparation', 'timing'],
    rarity: 'common',
    weight: 5,
    ageMin: 19,
    ageMax: 35,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'honorer',
        label: 'Honorer le tournage',
        stance: 'financial',
        riskPreview: 'Engagement tenu, préparation sabotée.',
        immediate: [fx.res('financesPersonnelles', 3), fx.res('forme', -4)],
        hidden: [fx.hidden('professionnalisme', -1)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('confianceEntraineur', -5)])])],
      }),
      choice({
        id: 'reporter',
        label: 'Reporter pour le match',
        stance: 'professional',
        riskPreview: 'Match protégé, pénalité et marque fâchée.',
        immediate: [fx.res('forme', 3), fx.cash(-15000)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),
]
