import { dilemma, choice, fx } from '../helpers'
import type { DilemmaDefinition } from '../../../game-engine/dilemmas'

/**
 * Phase 9 — Transferts. Compromis réels, ≥2 dimensions par choix, effets
 * retardés. Certains choix posent `transfer_accepted` (mouvement au bilan).
 */
export const transfertsDilemmas: DilemmaDefinition[] = [
  dilemma({
    id: 'p9_trf_star_ailleurs',
    title: 'Star ici, numéro parmi d’autres là-bas',
    body: 'Un club modeste veut bâtir son équipe autour de toi ; une écurie huppée t’offrirait un rôle de rotation dans une armada de vedettes. Rester la figure de proue nourrit ton importance et ta cote sportive. Rejoindre les grands décroche des trophées et te dilue dans la masse.',
    category: 'transfer',
    tags: ['transfert', 'statut', 'ambition'],
    rarity: 'common',
    weight: 9,
    ageMin: 20,
    ageMax: 32,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'figure',
        label: 'Rester la figure de proue',
        stance: 'loyal',
        riskPreview: 'Importance nourrie, palmarès repoussé.',
        immediate: [fx.res('reputationSportive', 4), fx.rel('fans', 5), fx.res('financesPersonnelles', -3)],
        hidden: [fx.hidden('loyaute', 2)],
      }),
      choice({
        id: 'grands',
        label: 'Rejoindre l’armada huppée',
        stance: 'ambitious',
        riskPreview: 'Trophées visés, dilution dans la masse.',
        immediate: [fx.flag('transfer_accepted'), fx.res('reputationSportive', 3), fx.res('cohesionVestiaire', -3)],
        hidden: [fx.hidden('ambition', 3)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('confianceEntraineur', -6)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p9_trf_championnat_riche',
    title: 'L’or d’un championnat oublié',
    body: 'Une ligue lointaine et peu cotée déverse un pactole pour t’attirer. Y aller sécurise ta vie à jamais et t’efface des radars du haut niveau. Rester dans l’élite préserve ta cote et ton rêve de sommet, en refusant une somme que la raison peine à écarter.',
    category: 'transfer',
    tags: ['transfert', 'argent', 'prestige'],
    rarity: 'common',
    weight: 8,
    ageMin: 24,
    ageMax: 35,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'or',
        label: 'Prendre l’or de l’exotisme',
        stance: 'financial',
        riskPreview: 'Vie sécurisée, radars du haut niveau perdus.',
        immediate: [fx.cash(90000), fx.res('reputationSportive', -6)],
        hidden: [fx.hidden('ambition', -1)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('reputationSportive', -4)])])],
      }),
      choice({
        id: 'elite',
        label: 'Rester dans l’élite',
        stance: 'ambitious',
        riskPreview: 'Cote préservée, pactole refusé.',
        immediate: [fx.res('reputationSportive', 4), fx.res('financesPersonnelles', -4)],
        hidden: [fx.hidden('ambition', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_trf_pret_gros_club',
    title: 'Un prêt pour te faire un nom',
    body: 'Un géant veut te prêter un an à un club qui te fera jouer, avant de te récupérer. Accepter t’offre du temps de jeu de gala et te met à la merci de leur décision finale. Refuser garde le contrôle de ton destin et ferme peut-être la porte du grand club à jamais.',
    category: 'transfer',
    tags: ['transfert', 'pret', 'temps_de_jeu'],
    rarity: 'common',
    weight: 7,
    ageMin: 18,
    ageMax: 26,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'accepter',
        label: 'Accepter le prêt tremplin',
        stance: 'ambitious',
        riskPreview: 'Temps de jeu de gala, destin entre leurs mains.',
        immediate: [fx.flag('transfer_accepted'), fx.res('reputationSportive', 3), fx.res('bienEtre', -2)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('reputationSportive', 4)])])],
      }),
      choice({
        id: 'refuser',
        label: 'Garder le contrôle de ton destin',
        stance: 'prudent',
        riskPreview: 'Contrôle gardé, porte du géant peut-être fermée.',
        immediate: [fx.res('confianceEntraineur', 3), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_trf_fidelite_vs_sommet',
    title: 'Rester fidèle ou viser le sommet',
    body: 'Ton club t’a tout donné, mais un cador frappe à la porte pile à ton pic. Rester honore ta parole et gèle ton ascension au moment idéal. Partir saisit la fenêtre de ta vie et t’expose au procès en trahison de tout un peuple qui te croyait des leurs.',
    category: 'transfer',
    tags: ['transfert', 'fidelite', 'ambition'],
    rarity: 'uncommon',
    weight: 7,
    ageMin: 22,
    ageMax: 31,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'rester',
        label: 'Rester fidèle',
        stance: 'loyal',
        riskPreview: 'Parole honorée, ascension gelée.',
        immediate: [fx.rel('fans', 8), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('loyaute', 3)],
        delayed: [fx.delayed(2, [fx.flag('fan_favorite'), fx.chance(0.5, [fx.rel('fans', 5)])])],
      }),
      choice({
        id: 'partir',
        label: 'Saisir la fenêtre au sommet',
        stance: 'ambitious',
        riskPreview: 'Fenêtre saisie, procès en trahison.',
        immediate: [fx.flag('transfer_accepted'), fx.res('reputationSportive', 5), fx.rel('fans', -8)],
        hidden: [fx.hidden('ambition', 3)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_trf_derniere_minute',
    title: 'L’offre de la dernière heure',
    body: 'À quelques minutes de la clôture du mercato, une offre inattendue déboule. Foncer sans réfléchir peut être le coup de ta vie comme un saut dans le vide sans garanties. Laisser passer par prudence conserve ta stabilité et te fera peut-être regretter l’occasion tout l’hiver.',
    category: 'transfer',
    tags: ['transfert', 'mercato', 'impulsivite'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 20,
    ageMax: 33,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'foncer',
        label: 'Foncer sur l’offre éclair',
        stance: 'high_risk',
        riskPreview: 'Coup de ta vie ou saut dans le vide.',
        immediate: [fx.flag('transfer_accepted'), fx.res('reputationSportive', 3), fx.res('bienEtre', -3)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.35, [fx.res('moral', -6)])])],
      }),
      choice({
        id: 'passer',
        label: 'Laisser passer par prudence',
        stance: 'prudent',
        riskPreview: 'Stabilité gardée, regret possible tout l’hiver.',
        immediate: [fx.res('bienEtre', 3), fx.res('reputationSportive', -2)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_trf_vendu_force',
    title: 'Le club décide de te vendre',
    body: 'Pour renflouer ses caisses, ton club te met sur le marché sans te demander ton avis. Accepter une belle destination proposée transforme la contrainte en opportunité maîtrisée. T’arc-bouter pour rester impose ta volonté et t’enferme dans un placard doré où plus personne ne compte sur toi.',
    category: 'transfer',
    tags: ['transfert', 'contrainte', 'club'],
    rarity: 'common',
    weight: 6,
    ageMin: 21,
    ageMax: 34,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'accepter',
        label: 'Choisir ta meilleure porte de sortie',
        stance: 'prudent',
        riskPreview: 'Contrainte maîtrisée, club de cœur quitté.',
        immediate: [fx.flag('transfer_accepted'), fx.res('reputationSportive', 3), fx.rel('fans', -3)],
        hidden: [fx.hidden('adaptabilite', 2)],
      }),
      choice({
        id: 'rester',
        label: 'T’arc-bouter pour rester',
        stance: 'resilient',
        riskPreview: 'Volonté imposée, placard doré assuré.',
        immediate: [fx.res('reputationSportive', 2), fx.res('confianceEntraineur', -6)],
        hidden: [fx.hidden('resistancePression', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('moral', -6)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p9_trf_retour_pays',
    title: 'Rentrer au pays qui t’a vu grandir',
    body: 'Un club de ta région natale t’ouvre les bras pour un retour aux sources. Rentrer comble ton cœur et ta famille, loin des sommets sportifs et des gros salaires. Poursuivre l’aventure ailleurs garde ta trajectoire ascendante et repousse des retrouvailles que le temps rend précieuses.',
    category: 'transfer',
    tags: ['transfert', 'retour', 'famille'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 26,
    ageMax: 37,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'rentrer',
        label: 'Rentrer au pays',
        stance: 'emotional',
        riskPreview: 'Cœur et famille comblés, ambition sportive freinée.',
        immediate: [fx.flag('transfer_accepted'), fx.flag('home_return'), fx.rel('family', 8), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('loyaute', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('bienEtre', 6)])])],
      }),
      choice({
        id: 'poursuivre',
        label: 'Poursuivre l’aventure ailleurs',
        stance: 'ambitious',
        riskPreview: 'Trajectoire gardée, retrouvailles repoussées.',
        immediate: [fx.res('reputationSportive', 4), fx.rel('family', -5)],
        hidden: [fx.hidden('ambition', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_trf_record_pression',
    title: 'Le transfert qui écrase de zéros',
    body: 'Un club pose un montant record sur ta tête. Accepter t’installe sous une pression écrasante où chaque ballon perdu devient un scandale. Rester à ton niveau de valeur préserve ta sérénité et laisse filer un transfert historique dont on aurait parlé longtemps.',
    category: 'transfer',
    tags: ['transfert', 'record', 'pression'],
    rarity: 'rare',
    weight: 4,
    ageMin: 21,
    ageMax: 30,
    cooldownSeasons: 6,
    choices: [
      choice({
        id: 'accepter',
        label: 'Assumer le transfert record',
        stance: 'ambitious',
        riskPreview: 'Historique, pression écrasante à porter.',
        immediate: [fx.flag('transfer_accepted'), fx.res('reputationSportive', 6), fx.res('bienEtre', -5)],
        hidden: [fx.hidden('resistancePression', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('moral', -8)])])],
      }),
      choice({
        id: 'rester',
        label: 'Rester à ta juste valeur',
        stance: 'prudent',
        riskPreview: 'Sérénité gardée, transfert historique manqué.',
        immediate: [fx.res('bienEtre', 4), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_trf_echange',
    title: 'Un joueur contre un autre',
    body: 'Ton transfert prend la forme d’un échange : tu pars, un autre arrive dans l’autre sens. Accepter le deal fluidifie ta sortie et te réduit à une monnaie d’échange. Le refuser affirme que tu vaux mieux qu’un troc et fait capoter un montage que les deux clubs voulaient boucler.',
    category: 'transfer',
    tags: ['transfert', 'echange', 'ego'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 22,
    ageMax: 34,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'accepter',
        label: 'Accepter l’échange',
        stance: 'prudent',
        riskPreview: 'Sortie fluide, réduit à une monnaie d’échange.',
        immediate: [fx.flag('transfer_accepted'), fx.res('reputationSportive', -2), fx.res('financesPersonnelles', 3)],
        hidden: [fx.hidden('adaptabilite', 2)],
      }),
      choice({
        id: 'refuser',
        label: 'Refuser d’être un troc',
        stance: 'individualist',
        riskPreview: 'Fierté affirmée, montage bloqué.',
        immediate: [fx.res('reputationSportive', 3), fx.rel('coach', -4)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('confianceEntraineur', -4)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p9_trf_coach_sceptique',
    title: 'Le club te veut, pas son coach',
    body: 'Un beau projet t’appelle, mais l’entraîneur n’a jamais réclamé ton profil. Signer quand même te lance un défi grisant et t’expose à un coach qui te snobera. Attendre un club vraiment convaincu par ton style sécurise ton temps de jeu et laisse filer une belle vitrine.',
    category: 'transfer',
    tags: ['transfert', 'coach', 'temps_de_jeu'],
    rarity: 'common',
    weight: 6,
    ageMin: 20,
    ageMax: 33,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'signer',
        label: 'Relever le défi malgré le coach',
        stance: 'high_risk',
        riskPreview: 'Défi grisant, coach qui pourrait te snober.',
        immediate: [fx.flag('transfer_accepted'), fx.res('reputationSportive', 3), fx.res('confianceEntraineur', -3)],
        hidden: [fx.hidden('resistancePression', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('confianceEntraineur', -6)])])],
      }),
      choice({
        id: 'attendre',
        label: 'Attendre un club convaincu',
        stance: 'prudent',
        riskPreview: 'Temps de jeu sécurisé, vitrine manquée.',
        immediate: [fx.res('confianceEntraineur', 4), fx.res('reputationSportive', -2)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_trf_partir_libre',
    title: 'Aller au bout pour partir libre',
    body: 'En fin de contrat, tu peux filer libre l’été prochain et empocher une énorme prime à la signature ailleurs. Attendre maximise ton gain personnel et prive ton club de toute indemnité, ce qu’il ne te pardonnera pas. Prolonger maintenant rassure la maison et sacrifie le jackpot de la liberté.',
    category: 'transfer',
    tags: ['transfert', 'libre', 'argent'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 23,
    ageMax: 35,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'libre',
        label: 'Aller au bout pour partir libre',
        stance: 'financial',
        riskPreview: 'Jackpot personnel, club privé d’indemnité.',
        immediate: [fx.res('financesPersonnelles', 5), fx.rel('coach', -6)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.5, [fx.cash(80000)])])],
      }),
      choice({
        id: 'prolonger',
        label: 'Prolonger et rassurer le club',
        stance: 'loyal',
        riskPreview: 'Maison rassurée, jackpot sacrifié.',
        immediate: [fx.flag('contract_extended'), fx.rel('coach', 6), fx.res('financesPersonnelles', -3)],
        hidden: [fx.hidden('loyaute', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_trf_club_crise_ambition',
    title: 'Un projet fou dans un club fragile',
    body: 'Un club au bord du gouffre te promet un rôle de sauveur et un projet démesuré. T’y engager peut faire de toi une légende locale ou te faire couler avec le navire. Choisir la stabilité d’un club sain protège ta carrière et te fait passer à côté d’une aventure inoubliable.',
    category: 'transfer',
    tags: ['transfert', 'risque', 'projet'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 22,
    ageMax: 34,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'sauveur',
        label: 'Devenir le sauveur',
        stance: 'high_risk',
        riskPreview: 'Légende locale ou naufrage assuré.',
        immediate: [fx.flag('transfer_accepted'), fx.res('reputationSportive', 4), fx.res('financesPersonnelles', -3)],
        hidden: [fx.hidden('ambition', 3)],
        delayed: [fx.delayed(2, [fx.chance(0.4, [fx.res('reputationSportive', -6)])])],
      }),
      choice({
        id: 'stable',
        label: 'Choisir un club sain',
        stance: 'prudent',
        riskPreview: 'Carrière protégée, aventure manquée.',
        immediate: [fx.res('bienEtre', 3), fx.res('reputationSportive', -2)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_trf_ldc_vs_depart',
    title: 'Une saison de plus pour l’Europe',
    body: 'Ton club vise la coupe continentale, un rêve à portée, mais un club supérieur te veut dès maintenant. Rester une saison de plus chasse ce rêve et retarde ton élévation. Partir tout de suite grimpe une marche et t’arrache à un groupe qui touchait l’histoire du bout des doigts.',
    category: 'transfer',
    tags: ['transfert', 'europe', 'timing'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 22,
    ageMax: 33,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'rester',
        label: 'Rester pour le rêve européen',
        stance: 'collective',
        riskPreview: 'Rêve chassé, élévation retardée.',
        immediate: [fx.rel('teammates', 6), fx.res('reputationSportive', -2)],
        hidden: [fx.hidden('loyaute', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('reputationSportive', 5)])])],
      }),
      choice({
        id: 'partir',
        label: 'Grimper une marche maintenant',
        stance: 'ambitious',
        riskPreview: 'Marche gravie, groupe historique quitté.',
        immediate: [fx.flag('transfer_accepted'), fx.res('reputationSportive', 4), fx.rel('teammates', -5)],
        hidden: [fx.hidden('ambition', 3)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_trf_expatriation_famille',
    title: 'Un contrat en or, à l’autre bout du monde',
    body: 'Une destination lointaine t’offre un pont d’or, mais déracine toute ta famille. Partir enrichit ton compte et bouleverse l’équilibre de tes proches. Décliner protège ta tribu et referme une porte financière que peu ont la chance de voir s’ouvrir.',
    category: 'transfer',
    tags: ['transfert', 'famille', 'argent'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 24,
    ageMax: 36,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'partir',
        label: 'Partir malgré le déracinement',
        stance: 'financial',
        riskPreview: 'Compte enrichi, équilibre familial bousculé.',
        immediate: [fx.flag('transfer_accepted'), fx.cash(70000), fx.rel('family', -7)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('moral', -6)])])],
      }),
      choice({
        id: 'decliner',
        label: 'Protéger ta famille',
        stance: 'emotional',
        riskPreview: 'Tribu protégée, porte dorée refermée.',
        immediate: [fx.rel('family', 8), fx.res('financesPersonnelles', -4)],
        hidden: [fx.hidden('loyaute', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_trf_reconversion_poste',
    title: 'Recruté pour un tout autre rôle',
    body: 'Un club te veut, mais pour t’installer à un poste que tu n’as jamais tenu. Accepter cette reconversion élargit ta palette et te jette dans l’inconnu au plus mauvais moment. Refuser garde ton identité de jeu et laisse filer un projet qui croyait en une facette cachée de toi.',
    category: 'transfer',
    tags: ['transfert', 'poste', 'reconversion'],
    rarity: 'common',
    weight: 5,
    ageMin: 23,
    ageMax: 35,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'accepter',
        label: 'Accepter la reconversion',
        stance: 'ambitious',
        riskPreview: 'Palette élargie, saut dans l’inconnu.',
        immediate: [fx.flag('transfer_accepted'), fx.stat('tactique', 2), fx.res('reputationSportive', -2)],
        hidden: [fx.hidden('adaptabilite', 3)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('confianceEntraineur', 5)])])],
      }),
      choice({
        id: 'refuser',
        label: 'Garder ton identité de jeu',
        stance: 'prudent',
        riskPreview: 'Repères gardés, projet audacieux manqué.',
        immediate: [fx.res('reputationSportive', 2), fx.res('financesPersonnelles', -2)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_trf_promu_ambitieux',
    title: 'Le promu qui voit grand',
    body: 'Un club fraîchement monté, plein d’argent et d’ambition, te déroule le tapis rouge. Le rejoindre te place au cœur d’un projet emballant mais bâti sur du sable si les résultats manquent. Rester dans un club établi assure ta stabilité et te prive d’une folle épopée en construction.',
    category: 'transfer',
    tags: ['transfert', 'projet', 'risque'],
    rarity: 'common',
    weight: 5,
    ageMin: 21,
    ageMax: 33,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'rejoindre',
        label: 'Rejoindre le promu ambitieux',
        stance: 'ambitious',
        riskPreview: 'Projet emballant, château de sable possible.',
        immediate: [fx.flag('transfer_accepted'), fx.cash(30000), fx.res('reputationSportive', -2)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(2, [fx.chance(0.35, [fx.res('reputationSportive', -5)])])],
      }),
      choice({
        id: 'rester',
        label: 'Rester dans un club établi',
        stance: 'prudent',
        riskPreview: 'Stabilité assurée, épopée manquée.',
        immediate: [fx.res('confianceEntraineur', 3), fx.res('financesPersonnelles', -2)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_trf_clause_activee',
    title: 'Un géant paie ta clause',
    body: 'Un mastodonte débloque ta clause libératoire d’un coup, sans négociation possible pour ton club. Filer réalise un rêve immense et laisse tes dirigeants furieux d’un départ subi. Rester malgré tout par gratitude gèle ton envol et t’enferme dans des regrets tenaces.',
    category: 'transfer',
    tags: ['transfert', 'clause', 'ambition'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 21,
    ageMax: 31,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'filer',
        label: 'Répondre à l’appel du géant',
        stance: 'ambitious',
        riskPreview: 'Rêve réalisé, dirigeants furieux.',
        immediate: [fx.flag('transfer_accepted'), fx.res('reputationSportive', 5), fx.rel('coach', -6)],
        hidden: [fx.hidden('ambition', 3)],
      }),
      choice({
        id: 'rester',
        label: 'Rester par gratitude',
        stance: 'loyal',
        riskPreview: 'Envol gelé, regrets tenaces.',
        immediate: [fx.rel('coach', 6), fx.res('moral', -4)],
        hidden: [fx.hidden('loyaute', 3)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('moral', -6)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p9_trf_club_retient',
    title: 'Ton club refuse de te lâcher',
    body: 'Une belle offre est là, mais ton club active tout pour te retenir contre ton gré. Forcer ton départ impose tes envies et brise net la confiance des dirigeants. Céder et rester préserve la paix et t’installe dans la frustration de l’occasion volée.',
    category: 'transfer',
    tags: ['transfert', 'club', 'conflit'],
    rarity: 'common',
    weight: 5,
    ageMin: 21,
    ageMax: 33,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'forcer',
        label: 'Forcer ton départ',
        stance: 'ambitious',
        riskPreview: 'Envies imposées, confiance brisée.',
        immediate: [fx.flag('transfer_accepted'), fx.res('reputationSportive', 3), fx.rel('coach', -8)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('confianceEntraineur', -6)])])],
      }),
      choice({
        id: 'ceder',
        label: 'Céder et rester en paix',
        stance: 'prudent',
        riskPreview: 'Paix préservée, frustration installée.',
        immediate: [fx.rel('coach', 5), fx.res('moral', -4)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p9_trf_prime_signature_geante',
    title: 'Une prime à la signature vertigineuse',
    body: 'Un club moins huppé compense son manque de prestige par une prime à la signature démesurée. L’empocher règle ta vie et écorne un peu ton standing sportif. Viser plus haut sans ce chèque préserve ta cote et refuse une somme qui ne se représentera pas de sitôt.',
    category: 'transfer',
    tags: ['transfert', 'prime', 'prestige'],
    rarity: 'common',
    weight: 5,
    ageMin: 22,
    ageMax: 34,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'empocher',
        label: 'Empocher la prime géante',
        stance: 'financial',
        riskPreview: 'Vie réglée, standing sportif écorné.',
        immediate: [fx.flag('transfer_accepted'), fx.cash(85000), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('constance', 1)],
      }),
      choice({
        id: 'viser',
        label: 'Viser plus haut sans le chèque',
        stance: 'ambitious',
        riskPreview: 'Cote préservée, magot refusé.',
        immediate: [fx.res('reputationSportive', 4), fx.res('financesPersonnelles', -4)],
        hidden: [fx.hidden('ambition', 3)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('reputationSportive', 3)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p9_trf_ville_lumiere',
    title: 'La vitrine ou le terrain',
    body: 'Une capitale médiatique t’offre lumière, sponsors et vie trépidante, mais un banc probable. Un club discret te garantit du jeu loin des projecteurs. Choisir la lumière dope ta notoriété et menace ton temps de jeu. Choisir le terrain nourrit ta carrière et t’éloigne des grandes vitrines.',
    category: 'transfer',
    tags: ['transfert', 'medias', 'temps_de_jeu'],
    rarity: 'common',
    weight: 5,
    ageMin: 21,
    ageMax: 33,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'lumiere',
        label: 'Choisir la vitrine médiatique',
        stance: 'media_savvy',
        riskPreview: 'Notoriété dopée, temps de jeu menacé.',
        immediate: [fx.flag('transfer_accepted'), fx.res('popularite', 6), fx.res('confianceEntraineur', -3)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('reputationSportive', -5)])])],
      }),
      choice({
        id: 'terrain',
        label: 'Choisir le terrain discret',
        stance: 'professional',
        riskPreview: 'Carrière nourrie, vitrines évitées.',
        immediate: [fx.res('confianceEntraineur', 5), fx.res('popularite', -3)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),
]
