import { dilemma, choice, chainEpisode, fx } from '../helpers'
import type { DilemmaDefinition } from '../../../game-engine/dilemmas'

/**
 * Phase 10 — Conséquences à long terme : 6 nouvelles chaînes narratives sur les
 * thèmes manquants (sponsor controversé, gestion financière, course au record,
 * documentaire, fuite de données, jeune protégé).
 *
 * Mécanique existante réutilisée : le `_start` (emplacement 2) pose un flag et
 * met en file l'épisode suivant (fx.queue), qui occupe un des deux emplacements
 * annuels — aucune décision supplémentaire. Chaque chaîne : 3–5 étapes, issues
 * multiples (échec + rebond), au moins une conséquence longue (delayed), échos
 * du passé ({years}). Refuser au départ = chaîne non lancée (abandon).
 */
export const chainesLongTermeDilemmas: DilemmaDefinition[] = [
  // ═══════════ Chaîne 1 — Sponsor controversé ═══════════
  dilemma({
    id: 'p10_chain_sponsor_start',
    title: 'La marque sulfureuse au gros chèque',
    body: 'Une marque au parfum de scandale t’offre une somme indécente pour ton image. Signer remplit ton compte et t’accroche une étiquette risquée que le public surveille. Refuser protège ta réputation et laisse filer un pactole que d’autres saisiront sans état d’âme.',
    category: 'sponsors',
    tags: ['sponsors', 'controverse', 'chaine'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 20,
    ageMax: 35,
    unique: true,
    choices: [
      choice({
        id: 'signer',
        label: 'Signer avec la marque sulfureuse',
        stance: 'financial',
        riskPreview: 'Compte rempli, étiquette risquée.',
        immediate: [fx.flag('controversial_sponsor'), fx.cash(50000), fx.res('reputationSportive', -3)],
        delayed: [fx.delayed(1, [fx.queue('p10_chain_sponsor_ep2')])],
        hidden: [fx.hidden('ambition', 1)],
      }),
      choice({
        id: 'refuser',
        label: 'Refuser par prudence',
        stance: 'ethical',
        riskPreview: 'Image protégée, pactole laissé.',
        immediate: [fx.res('reputationSportive', 3), fx.res('financesPersonnelles', -3)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),
  chainEpisode({
    id: 'p10_chain_sponsor_ep2',
    previousEventId: 'p10_chain_sponsor_start',
    prerequisites: [{ type: 'hasFlag', key: 'controversial_sponsor' }],
    title: 'La grogne enfle',
    body: 'Les supporters digèrent mal ton association et les médias remuent le passé de la marque. Doubler la mise et défendre ton choix dope tes revenus et attise la colère. Prendre tes distances désamorce la crise et t’oblige à rendre une partie du gâteau.',
    tags: ['sponsors', 'controverse'],
    echoes: [
      { flag: 'controversial_sponsor', text: 'Ce tumulte vient du sponsor sulfureux signé il y a {years} saisons.' },
    ],
    choices: [
      choice({
        id: 'doubler',
        label: 'Doubler la mise',
        stance: 'high_risk',
        riskPreview: 'Revenus dopés, colère attisée.',
        immediate: [fx.flag('sponsor_doubled'), fx.res('popularite', 3), fx.rel('fans', -6)],
        delayed: [fx.delayed(1, [fx.queue('p10_chain_sponsor_ep3_scandale')])],
        hidden: [fx.hidden('ambition', 2)],
      }),
      choice({
        id: 'distance',
        label: 'Prendre tes distances',
        stance: 'prudent',
        riskPreview: 'Crise désamorcée, gâteau rendu.',
        immediate: [fx.flag('sponsor_distanced'), fx.res('reputationSportive', 2), fx.res('financesPersonnelles', -3)],
        delayed: [fx.delayed(1, [fx.queue('p10_chain_sponsor_ep3_rebond')])],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),
  chainEpisode({
    id: 'p10_chain_sponsor_ep3_scandale',
    previousEventId: 'p10_chain_sponsor_ep2',
    prerequisites: [{ type: 'hasFlag', key: 'sponsor_doubled' }],
    title: 'La marque implose',
    body: 'La marque s’effondre dans un scandale retentissant et ton visage y reste collé. Encaisser tes dernières primes profite de la manne jusqu’au bout et grave la tache. T’excuser publiquement limite les dégâts et te fait rendre l’argent devant tout le monde.',
    tags: ['sponsors', 'scandale'],
    rarity: 'rare',
    echoes: [
      { flag: 'controversial_sponsor', text: 'Le sponsor que tu défendais depuis {years} saisons vient de te trahir.' },
    ],
    choices: [
      choice({
        id: 'encaisser',
        label: 'Encaisser jusqu’au bout',
        stance: 'financial',
        riskPreview: 'Manne saisie, tache gravée.',
        immediate: [fx.flag('sponsor_scandal'), fx.cash(30000), fx.res('reputationSportive', -6)],
        delayed: [fx.delayed(2, [fx.rel('fans', -6)])],
        hidden: [fx.hidden('loyaute', -2)],
      }),
      choice({
        id: 'excuser',
        label: 'T’excuser publiquement',
        stance: 'ethical',
        riskPreview: 'Dégâts limités, argent rendu.',
        immediate: [fx.res('reputationSportive', 2), fx.cash(-20000)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),
  chainEpisode({
    id: 'p10_chain_sponsor_ep3_rebond',
    previousEventId: 'p10_chain_sponsor_ep2',
    prerequisites: [{ type: 'hasFlag', key: 'sponsor_distanced' }],
    title: 'Le pari de la rédemption',
    body: 'Ton retrait à temps t’a épargné le naufrage ; reste à reconstruire ton image. Assumer publiquement ton erreur touche le public et coûte un dernier chèque. Faire profil bas préserve ta tranquillité et laisse planer un doute qui s’effacera lentement.',
    tags: ['sponsors', 'rebond'],
    echoes: [
      { flag: 'controversial_sponsor', text: 'Tu as su te retirer à temps du sponsor douteux d’il y a {years} saisons.' },
    ],
    choices: [
      choice({
        id: 'assumer',
        label: 'Assumer et te racheter',
        stance: 'ethical',
        riskPreview: 'Public touché, dernier chèque rendu.',
        immediate: [fx.flag('image_rebuilt'), fx.rel('fans', 6), fx.cash(-12000)],
        delayed: [fx.delayed(2, [fx.rel('fans', 5)])],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
      choice({
        id: 'profil_bas',
        label: 'Faire profil bas',
        stance: 'prudent',
        riskPreview: 'Tranquillité gardée, doute qui traîne.',
        immediate: [fx.res('bienEtre', 3), fx.res('popularite', -3)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  // ═══════════ Chaîne 2 — Mauvaise gestion financière ═══════════
  dilemma({
    id: 'p10_chain_finance_start',
    title: 'Vivre bien au-dessus de tes moyens',
    body: 'Grisé par tes premiers gros chèques, tu multiplies les folies sans regarder les comptes. Foncer dans le luxe dope ton moral et creuse un trou que personne ne surveille. Te discipliner protège ton avenir et te prive du frisson d’une vie sans limites.',
    category: 'lifestyle',
    tags: ['depenses', 'gestion', 'chaine'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 19,
    ageMax: 33,
    unique: true,
    choices: [
      choice({
        id: 'foncer',
        label: 'Foncer dans le luxe',
        stance: 'emotional',
        riskPreview: 'Moral dopé, trou qui se creuse.',
        immediate: [fx.flag('overspending'), fx.res('moral', 5), fx.cash(-40000)],
        delayed: [fx.delayed(1, [fx.queue('p10_chain_finance_ep2')])],
        hidden: [fx.hidden('constance', -2)],
      }),
      choice({
        id: 'discipline',
        label: 'Te discipliner tout de suite',
        stance: 'prudent',
        riskPreview: 'Avenir protégé, frisson refusé.',
        immediate: [fx.res('financesPersonnelles', 5), fx.res('moral', -3)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),
  chainEpisode({
    id: 'p10_chain_finance_ep2',
    previousEventId: 'p10_chain_finance_start',
    prerequisites: [{ type: 'hasFlag', key: 'overspending' }],
    title: 'Les dettes rattrapent le rêve',
    body: 'Les factures s’empilent et ton banquier s’inquiète pour de bon. Vendre tes joujoux et serrer la ceinture stoppe l’hémorragie et blesse ton orgueil. Emprunter encore pour tenir le train de vie repousse le mur et fonce droit dessus.',
    tags: ['depenses', 'dette'],
    echoes: [
      { flag: 'overspending', text: 'Ces dettes remontent au train de vie lancé il y a {years} saisons.' },
    ],
    choices: [
      choice({
        id: 'serrer',
        label: 'Vendre et serrer la ceinture',
        stance: 'prudent',
        riskPreview: 'Hémorragie stoppée, orgueil blessé.',
        immediate: [fx.flag('finance_tightened'), fx.res('financesPersonnelles', 4), fx.res('moral', -4)],
        delayed: [fx.delayed(1, [fx.queue('p10_chain_finance_ep3_rebond')])],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
      choice({
        id: 'emprunter',
        label: 'Emprunter encore',
        stance: 'high_risk',
        riskPreview: 'Mur repoussé, catastrophe foncée dessus.',
        immediate: [fx.flag('finance_borrowed'), fx.cash(25000), fx.res('bienEtre', -4)],
        delayed: [fx.delayed(1, [fx.queue('p10_chain_finance_ep3_ruine')])],
        hidden: [fx.hidden('ambition', 1)],
      }),
    ],
  }),
  chainEpisode({
    id: 'p10_chain_finance_ep3_ruine',
    previousEventId: 'p10_chain_finance_ep2',
    prerequisites: [{ type: 'hasFlag', key: 'finance_borrowed' }],
    title: 'Le château s’écroule',
    body: 'La spirale se referme : tu dois jouer pour rembourser, pas pour gagner. Tout liquider en urgence sauve l’essentiel et solde tes rêves à perte. Te battre pour garder les apparences protège ton image et enfonce le clou pour des années.',
    tags: ['depenses', 'ruine'],
    rarity: 'rare',
    echoes: [
      { flag: 'overspending', text: 'Voilà où mènent {years} saisons de dépenses sans compter.' },
    ],
    choices: [
      choice({
        id: 'liquider',
        label: 'Tout liquider en urgence',
        stance: 'prudent',
        riskPreview: 'Essentiel sauvé, rêves soldés à perte.',
        immediate: [fx.flag('financial_ruin'), fx.cash(-30000), fx.res('bienEtre', 3)],
        delayed: [fx.delayed(2, [fx.res('financesPersonnelles', -6)])],
        hidden: [fx.hidden('constance', 2)],
      }),
      choice({
        id: 'apparences',
        label: 'Sauver les apparences',
        stance: 'emotional',
        riskPreview: 'Image tenue, clou enfoncé des années.',
        immediate: [fx.flag('financial_ruin'), fx.res('popularite', 2), fx.res('bienEtre', -6)],
        delayed: [fx.delayed(2, [fx.res('moral', -8)])],
        hidden: [fx.hidden('resistancePression', 2)],
      }),
    ],
  }),
  chainEpisode({
    id: 'p10_chain_finance_ep3_rebond',
    previousEventId: 'p10_chain_finance_ep2',
    prerequisites: [{ type: 'hasFlag', key: 'finance_tightened' }],
    title: 'Repartir sur des bases saines',
    body: 'À force de rigueur, tu redresses la barre avant le naufrage. T’engager dans une gestion stricte pérennise ta remontée et t’impose une vie sans éclat. Relâcher un peu tes efforts t’accorde une bouffée d’air et rouvre la porte aux vieux démons.',
    tags: ['depenses', 'rebond'],
    echoes: [
      { flag: 'overspending', text: 'Tu as redressé la barre après les folies d’il y a {years} saisons.' },
    ],
    choices: [
      choice({
        id: 'rigueur',
        label: 'T’imposer une gestion stricte',
        stance: 'professional',
        riskPreview: 'Remontée pérennisée, vie sans éclat.',
        immediate: [fx.flag('finances_recovered'), fx.res('financesPersonnelles', 5), fx.res('moral', -2)],
        delayed: [fx.delayed(2, [fx.res('financesPersonnelles', 5)])],
        hidden: [fx.hidden('professionnalisme', 3)],
      }),
      choice({
        id: 'relacher',
        label: 'Relâcher un peu',
        stance: 'emotional',
        riskPreview: 'Bouffée d’air, vieux démons de retour.',
        immediate: [fx.res('moral', 4), fx.res('financesPersonnelles', -3)],
        hidden: [fx.hidden('constance', -1)],
      }),
    ],
  }),

  // ═══════════ Chaîne 3 — Course au record ═══════════
  dilemma({
    id: 'p10_chain_record_start',
    title: 'La presse te sacre chasseur de record',
    body: 'Les médias font de toi le candidat à un record historique et la machine s’emballe. Embrasser la quête décuple ta motivation et t’enferme dans une pression permanente. Minimiser l’affaire protège ta sérénité et déçoit un public déjà accroché au feuilleton.',
    category: 'media',
    tags: ['record', 'medias', 'chaine'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 21,
    ageMax: 34,
    unique: true,
    choices: [
      choice({
        id: 'embrasser',
        label: 'Embrasser la quête du record',
        stance: 'ambitious',
        riskPreview: 'Motivation décuplée, pression permanente.',
        immediate: [fx.flag('record_chase'), fx.res('reputationSportive', 3), fx.res('bienEtre', -3)],
        delayed: [fx.delayed(1, [fx.queue('p10_chain_record_ep2')])],
        hidden: [fx.hidden('ambition', 3)],
      }),
      choice({
        id: 'minimiser',
        label: 'Minimiser l’affaire',
        stance: 'prudent',
        riskPreview: 'Sérénité gardée, public déçu.',
        immediate: [fx.res('bienEtre', 3), fx.rel('fans', -4)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),
  chainEpisode({
    id: 'p10_chain_record_ep2',
    previousEventId: 'p10_chain_record_start',
    prerequisites: [{ type: 'hasFlag', key: 'record_chase' }],
    title: 'La pression au bord de la rupture',
    body: 'Chaque match devient un référendum et le compteur t’obsède jusque dans ton sommeil. T’acharner seul vers la marque flatte ton ego et t’isole du collectif. Jouer d’abord pour l’équipe apaise le vestiaire et éloigne le record de tes mains.',
    tags: ['record', 'pression'],
    echoes: [
      { flag: 'record_chase', text: 'Cette obsession dure depuis que la presse t’a sacré, il y a {years} saisons.' },
    ],
    choices: [
      choice({
        id: 'acharner',
        label: 'T’acharner vers la marque',
        stance: 'individualist',
        riskPreview: 'Ego flatté, collectif délaissé.',
        immediate: [fx.flag('record_pushed'), fx.res('reputationSportive', 3), fx.res('cohesionVestiaire', -5)],
        delayed: [fx.delayed(1, [fx.queue('p10_chain_record_ep3_gloire')])],
        hidden: [fx.hidden('ambition', 2)],
      }),
      choice({
        id: 'collectif',
        label: 'Jouer d’abord pour l’équipe',
        stance: 'collective',
        riskPreview: 'Vestiaire apaisé, record qui s’éloigne.',
        immediate: [fx.flag('record_teamfirst'), fx.res('cohesionVestiaire', 5), fx.res('reputationSportive', -2)],
        delayed: [fx.delayed(1, [fx.queue('p10_chain_record_ep3_sacrifice')])],
        hidden: [fx.hidden('loyaute', 2)],
      }),
    ],
  }),
  chainEpisode({
    id: 'p10_chain_record_ep3_gloire',
    previousEventId: 'p10_chain_record_ep2',
    prerequisites: [{ type: 'hasFlag', key: 'record_pushed' }],
    title: 'Le record, coûte que coûte',
    body: 'La marque tombe dans un dernier effort qui te laisse sur les genoux. Savourer la gloire grave ton nom dans l’histoire et paie ton corps au prix fort. Enchaîner sans souffler défie l’épuisement et menace de tout gâcher juste après le sommet.',
    tags: ['record', 'gloire'],
    rarity: 'rare',
    echoes: [
      { flag: 'record_chase', text: 'Le record poursuivi depuis {years} saisons est enfin à toi.' },
    ],
    choices: [
      choice({
        id: 'savourer',
        label: 'Savourer et lever le pied',
        stance: 'professional',
        riskPreview: 'Nom gravé, corps payé au prix fort.',
        immediate: [fx.flag('record_broken'), fx.res('reputationSportive', 6), fx.res('fatigue', 6)],
        delayed: [fx.delayed(2, [fx.res('forme', -8)])],
        hidden: [fx.hidden('grandsMatchs', 3)],
      }),
      choice({
        id: 'enchainer',
        label: 'Enchaîner sans souffler',
        stance: 'high_risk',
        riskPreview: 'Épuisement défié, sommet menacé.',
        immediate: [fx.flag('record_broken'), fx.res('reputationSportive', 3), fx.res('fatigue', 8)],
        delayed: [fx.delayed(1, [fx.res('sante', -8)])],
        hidden: [fx.hidden('ambition', 2)],
      }),
    ],
  }),
  chainEpisode({
    id: 'p10_chain_record_ep3_sacrifice',
    previousEventId: 'p10_chain_record_ep2',
    prerequisites: [{ type: 'hasFlag', key: 'record_teamfirst' }],
    title: 'Le record que tu as laissé filer',
    body: 'Tu as offert la balle du record à un partenaire au moment décisif. Assumer ce geste grandit ta stature de leader et enterre à jamais ta marque personnelle. Regretter en silence ronge ton moral et te vaut malgré tout le respect du vestiaire.',
    tags: ['record', 'sacrifice'],
    echoes: [
      { flag: 'record_chase', text: 'Tu as renoncé au record que tu chassais depuis {years} saisons.' },
    ],
    choices: [
      choice({
        id: 'assumer',
        label: 'Assumer ton geste',
        stance: 'collective',
        riskPreview: 'Stature grandie, marque enterrée.',
        immediate: [fx.flag('fan_favorite'), fx.rel('teammates', 8), fx.res('reputationSportive', -2)],
        delayed: [fx.delayed(2, [fx.rel('fans', 5)])],
        hidden: [fx.hidden('loyaute', 3)],
      }),
      choice({
        id: 'regretter',
        label: 'Regretter en silence',
        stance: 'resilient',
        riskPreview: 'Respect gagné, moral rongé.',
        immediate: [fx.rel('teammates', 5), fx.res('moral', -5)],
        hidden: [fx.hidden('resistancePression', 2)],
      }),
    ],
  }),

  // ═══════════ Chaîne 4 — Documentaire médiatique ═══════════
  dilemma({
    id: 'p10_chain_docu_start',
    title: '{journaliste} veut filmer ta vie',
    body: 'Une production propose une série documentaire immersive sur ta saison. Ouvrir tes portes promet une notoriété planétaire et livre ton intimité au montage. Refuser garde ta vie à l’abri et laisse filer une vitrine mondiale offerte à peu de joueurs.',
    category: 'media',
    tags: ['medias', 'documentaire', 'chaine'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 21,
    ageMax: 35,
    unique: true,
    prerequisites: [{ type: 'minNpcRelation', npc: 'journalist', value: 40 }],
    choices: [
      choice({
        id: 'ouvrir',
        label: 'Ouvrir tes portes',
        stance: 'media_savvy',
        riskPreview: 'Notoriété planétaire, intimité livrée.',
        immediate: [fx.flag('documentary_deal'), fx.res('popularite', 6), fx.res('bienEtre', -3)],
        delayed: [fx.delayed(1, [fx.queue('p10_chain_docu_ep2')])],
        hidden: [fx.hidden('ambition', 2)],
      }),
      choice({
        id: 'refuser',
        label: 'Protéger ta vie privée',
        stance: 'prudent',
        riskPreview: 'Intimité gardée, vitrine manquée.',
        immediate: [fx.res('bienEtre', 4), fx.res('popularite', -3)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),
  chainEpisode({
    id: 'p10_chain_docu_ep2',
    previousEventId: 'p10_chain_docu_start',
    prerequisites: [{ type: 'hasFlag', key: 'documentary_deal' }],
    title: 'La caméra filme trop',
    body: 'Le tournage capte tes colères, tes doutes, une dispute de trop. Laisser tout à l’écran offre une vérité brute et t’expose sans filet. Exiger de couper les scènes gênantes protège ton image et donne un montage lisse que personne ne partagera.',
    tags: ['medias', 'documentaire'],
    echoes: [
      { flag: 'documentary_deal', text: 'La caméra que tu avais laissée entrer il y a {years} saisons ne te lâche plus.' },
    ],
    choices: [
      choice({
        id: 'brut',
        label: 'Tout laisser à l’écran',
        stance: 'high_risk',
        riskPreview: 'Vérité brute, exposition sans filet.',
        immediate: [fx.flag('docu_raw'), fx.res('popularite', 4), fx.res('reputationSportive', -2)],
        delayed: [fx.delayed(1, [fx.queue('p10_chain_docu_ep3_viral')])],
        hidden: [fx.hidden('resistancePression', 2)],
      }),
      choice({
        id: 'couper',
        label: 'Couper les scènes gênantes',
        stance: 'prudent',
        riskPreview: 'Image protégée, montage sans relief.',
        immediate: [fx.flag('docu_cut'), fx.res('bienEtre', 3), fx.res('popularite', -3)],
        delayed: [fx.delayed(1, [fx.queue('p10_chain_docu_ep3_lisse')])],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),
  chainEpisode({
    id: 'p10_chain_docu_ep3_viral',
    previousEventId: 'p10_chain_docu_ep2',
    prerequisites: [{ type: 'hasFlag', key: 'docu_raw' }],
    title: 'La sortie qui embrase tout',
    body: 'Le documentaire cartonne, mais une scène crue tourne contre toi en boucle. Assumer ta vérité séduit les uns et te colle une réputation de tête brûlée. Tenter de recadrer le récit calme la tempête et sent la manœuvre désespérée.',
    tags: ['medias', 'viral'],
    rarity: 'rare',
    echoes: [
      { flag: 'documentary_deal', text: 'Le documentaire ouvert il y a {years} saisons te revient en pleine figure.' },
    ],
    choices: [
      choice({
        id: 'assumer',
        label: 'Assumer ta vérité',
        stance: 'resilient',
        riskPreview: 'Public séduit, réputation de tête brûlée.',
        immediate: [fx.flag('docu_exposed'), fx.res('popularite', 5), fx.res('reputationSportive', -3)],
        delayed: [fx.delayed(2, [fx.res('reputationSportive', -3)])],
        hidden: [fx.hidden('resistancePression', 3)],
      }),
      choice({
        id: 'recadrer',
        label: 'Tenter de recadrer le récit',
        stance: 'media_savvy',
        riskPreview: 'Tempête calmée, manœuvre visible.',
        immediate: [fx.res('reputationSportive', 2), fx.res('bienEtre', -3)],
        hidden: [fx.hidden('professionnalisme', 1)],
      }),
    ],
  }),
  chainEpisode({
    id: 'p10_chain_docu_ep3_lisse',
    previousEventId: 'p10_chain_docu_ep2',
    prerequisites: [{ type: 'hasFlag', key: 'docu_cut' }],
    title: 'Le documentaire trop propre',
    body: 'Ta version aseptisée sort sans faire de vagues, et les fans crient à l’imposture. En rire publiquement désarme les critiques et t’étiquette en joueur sous contrôle. L’ignorer garde ta dignité et laisse s’installer l’image d’un produit sans âme.',
    tags: ['medias', 'documentaire'],
    echoes: [
      { flag: 'documentary_deal', text: 'Le documentaire lissé d’il y a {years} saisons te colle une image de façade.' },
    ],
    choices: [
      choice({
        id: 'rire',
        label: 'En rire publiquement',
        stance: 'media_savvy',
        riskPreview: 'Critiques désarmées, image sous contrôle.',
        immediate: [fx.flag('docu_polished'), fx.res('popularite', 3), fx.res('reputationSportive', -1)],
        hidden: [fx.hidden('adaptabilite', 2)],
      }),
      choice({
        id: 'ignorer',
        label: 'Ignorer les critiques',
        stance: 'prudent',
        riskPreview: 'Dignité gardée, image sans âme.',
        immediate: [fx.res('bienEtre', 3), fx.res('popularite', -3)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  // ═══════════ Chaîne 5 — Fuite de données ═══════════
  dilemma({
    id: 'p10_chain_data_start',
    title: 'Tes données privées fuitent',
    body: 'Des données confidentielles — médicales, contractuelles — atterrissent en ligne. Riposter fort et porter plainte affiche ta fermeté et donne de l’écho au scandale. Étouffer l’affaire discrètement évite le bruit et laisse la fuite empoisonner les coulisses.',
    category: 'media',
    tags: ['medias', 'donnees', 'chaine'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 20,
    ageMax: 36,
    unique: true,
    prerequisites: [{ type: 'maxNpcRelation', npc: 'journalist', value: 60 }],
    choices: [
      choice({
        id: 'riposter',
        label: 'Riposter et porter plainte',
        stance: 'ethical',
        riskPreview: 'Fermeté affichée, écho donné au scandale.',
        immediate: [fx.flag('data_leak'), fx.res('reputationSportive', 2), fx.res('bienEtre', -3)],
        delayed: [fx.delayed(1, [fx.queue('p10_chain_data_ep2')])],
        hidden: [fx.hidden('resistancePression', 2)],
      }),
      choice({
        id: 'etouffer',
        label: 'Étouffer discrètement',
        stance: 'prudent',
        riskPreview: 'Bruit évité, coulisses empoisonnées.',
        immediate: [fx.flag('data_leak'), fx.flag('data_buried'), fx.res('bienEtre', 2), fx.res('reputationSportive', -2)],
        delayed: [fx.delayed(2, [fx.queue('p10_chain_data_ep3_ombre')])],
        hidden: [fx.hidden('constance', 1)],
      }),
    ],
  }),
  chainEpisode({
    id: 'p10_chain_data_ep2',
    previousEventId: 'p10_chain_data_start',
    prerequisites: [{ type: 'hasFlag', key: 'data_leak' }],
    title: 'La piste mène à l’intérieur',
    body: 'L’enquête pointe une taupe dans ton propre entourage. Aller au bout et la démasquer assainit ton camp et déclenche une guerre interne. Classer l’affaire par lassitude te ramène la paix et laisse le coupable libre de recommencer.',
    tags: ['medias', 'donnees', 'enquete'],
    echoes: [
      { flag: 'data_leak', text: 'La fuite d’il y a {years} saisons cachait une trahison de tes proches.' },
    ],
    choices: [
      choice({
        id: 'demasquer',
        label: 'Démasquer la taupe',
        stance: 'ethical',
        riskPreview: 'Camp assaini, guerre interne déclenchée.',
        immediate: [fx.flag('data_pursued'), fx.res('reputationSportive', 3), fx.res('cohesionVestiaire', -4)],
        delayed: [fx.delayed(1, [fx.queue('p10_chain_data_ep3_justice')])],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
      choice({
        id: 'classer',
        label: 'Classer l’affaire',
        stance: 'prudent',
        riskPreview: 'Paix revenue, coupable libre.',
        immediate: [fx.flag('data_buried'), fx.res('bienEtre', 3), fx.res('reputationSportive', -2)],
        delayed: [fx.delayed(2, [fx.queue('p10_chain_data_ep3_ombre')])],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),
  chainEpisode({
    id: 'p10_chain_data_ep3_justice',
    previousEventId: 'p10_chain_data_ep2',
    prerequisites: [{ type: 'hasFlag', key: 'data_pursued' }],
    title: 'La vérité éclate',
    body: 'Tu confonds le coupable au grand jour, mais l’étalage relance tout le déballage. Poursuivre jusqu’au procès obtient réparation et t’enchaîne des mois à une bataille épuisante. Pardonner publiquement referme la plaie et laisse un goût d’inachevé.',
    tags: ['medias', 'justice'],
    rarity: 'rare',
    echoes: [
      { flag: 'data_leak', text: 'Justice enfin rendue pour la fuite d’il y a {years} saisons.' },
    ],
    choices: [
      choice({
        id: 'proces',
        label: 'Poursuivre jusqu’au procès',
        stance: 'resilient',
        riskPreview: 'Réparation obtenue, bataille épuisante.',
        immediate: [fx.flag('data_cleared'), fx.res('reputationSportive', 4), fx.res('bienEtre', -5)],
        delayed: [fx.delayed(2, [fx.res('reputationSportive', 3)])],
        hidden: [fx.hidden('resistancePression', 3)],
      }),
      choice({
        id: 'pardonner',
        label: 'Pardonner publiquement',
        stance: 'ethical',
        riskPreview: 'Plaie refermée, goût d’inachevé.',
        immediate: [fx.flag('data_cleared'), fx.rel('fans', 5), fx.res('reputationSportive', -1)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),
  chainEpisode({
    id: 'p10_chain_data_ep3_ombre',
    previousEventId: 'p10_chain_data_start',
    prerequisites: [{ type: 'hasFlag', key: 'data_buried' }],
    title: 'L’ombre qui ne s’efface pas',
    body: 'Étouffée un temps, l’affaire ressurgit quand tu t’y attends le moins. Prendre les devants et tout révéler enfin reprend la main et rouvre une blessure mal cicatrisée. Nier encore protège l’instant et laisse un doute te suivre jusqu’au bout.',
    tags: ['medias', 'donnees'],
    echoes: [
      { flag: 'data_leak', text: 'La fuite étouffée il y a {years} saisons refait surface.' },
    ],
    choices: [
      choice({
        id: 'reveler',
        label: 'Tout révéler enfin',
        stance: 'ethical',
        riskPreview: 'Main reprise, blessure rouverte.',
        immediate: [fx.flag('data_shadow'), fx.res('reputationSportive', 2), fx.res('bienEtre', -4)],
        delayed: [fx.delayed(2, [fx.rel('fans', 4)])],
        hidden: [fx.hidden('resistancePression', 2)],
      }),
      choice({
        id: 'nier',
        label: 'Nier encore',
        stance: 'prudent',
        riskPreview: 'Instant protégé, doute qui te suit.',
        immediate: [fx.flag('data_shadow'), fx.res('bienEtre', 2), fx.res('reputationSportive', -3)],
        delayed: [fx.delayed(2, [fx.res('popularite', -4)])],
        hidden: [fx.hidden('constance', -1)],
      }),
    ],
  }),

  // ═══════════ Chaîne 6 — Le jeune protégé ═══════════
  dilemma({
    id: 'p10_chain_protege_start',
    title: 'Prendre un espoir sous ton aile',
    body: 'Un jeune surdoué débarque et te demande de le guider dans la jungle du haut niveau. L’adopter forge un lien fort et t’ajoute une charge et un futur concurrent. Le tenir à distance protège ta place et laisse un talent livré à lui-même.',
    category: 'teammates',
    tags: ['vestiaire', 'protege', 'chaine'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 24,
    ageMax: 37,
    unique: true,
    choices: [
      choice({
        id: 'adopter',
        label: 'Le prendre sous ton aile',
        stance: 'collective',
        riskPreview: 'Lien fort, futur concurrent armé.',
        immediate: [fx.flag('mentoring_prodigy'), fx.rel('teammates', 6), fx.res('fatigue', 2)],
        delayed: [fx.delayed(2, [fx.queue('p10_chain_protege_ep2')])],
        hidden: [fx.hidden('loyaute', 2)],
      }),
      choice({
        id: 'distance',
        label: 'Le tenir à distance',
        stance: 'individualist',
        riskPreview: 'Place protégée, talent abandonné.',
        immediate: [fx.res('reputationSportive', 2), fx.rel('teammates', -4)],
        hidden: [fx.hidden('ambition', 2)],
      }),
    ],
  }),
  chainEpisode({
    id: 'p10_chain_protege_ep2',
    previousEventId: 'p10_chain_protege_start',
    prerequisites: [{ type: 'hasFlag', key: 'mentoring_prodigy' }],
    title: 'L’élève dépasse le maître',
    body: 'Ton protégé explose et vise désormais ta place de titulaire. Continuer à le pousser grandit ton héritage et accélère ta propre relégation. Le freiner discrètement retarde l’échéance et trahit la confiance d’un gamin qui t’admire.',
    tags: ['vestiaire', 'protege'],
    echoes: [
      { flag: 'mentoring_prodigy', text: 'Le gamin que tu formes depuis {years} saisons est prêt à te doubler.' },
    ],
    choices: [
      choice({
        id: 'pousser',
        label: 'Continuer à le pousser',
        stance: 'collective',
        riskPreview: 'Héritage grandi, relégation accélérée.',
        immediate: [fx.flag('protege_pushed'), fx.rel('teammates', 5), fx.res('reputationSportive', -3)],
        delayed: [fx.delayed(1, [fx.queue('p10_chain_protege_ep3_heritage')])],
        hidden: [fx.hidden('loyaute', 2)],
      }),
      choice({
        id: 'freiner',
        label: 'Le freiner discrètement',
        stance: 'individualist',
        riskPreview: 'Échéance retardée, confiance trahie.',
        immediate: [fx.flag('protege_held'), fx.res('reputationSportive', 2), fx.res('cohesionVestiaire', -3)],
        delayed: [fx.delayed(1, [fx.queue('p10_chain_protege_ep3_trahison')])],
        hidden: [fx.hidden('loyaute', -2)],
      }),
    ],
  }),
  chainEpisode({
    id: 'p10_chain_protege_ep3_heritage',
    previousEventId: 'p10_chain_protege_ep2',
    prerequisites: [{ type: 'hasFlag', key: 'protege_pushed' }],
    title: 'Le flambeau bien passé',
    body: 'Le jour où il éclate, le gamin te remercie devant tout le stade. Passer le relais avec grâce couronne ton rôle de mentor et acte ton retrait. T’accrocher encore un peu retarde l’adieu et ternit un tableau presque parfait.',
    tags: ['vestiaire', 'heritage'],
    rarity: 'rare',
    echoes: [
      { flag: 'mentoring_prodigy', text: 'Le protégé formé depuis {years} saisons devient ce que tu as fait de lui.' },
    ],
    choices: [
      choice({
        id: 'relais',
        label: 'Passer le relais avec grâce',
        stance: 'loyal',
        riskPreview: 'Rôle de mentor couronné, retrait acté.',
        immediate: [fx.flag('mentor_legacy'), fx.flag('fan_favorite'), fx.rel('teammates', 6), fx.res('reputationSportive', -2)],
        delayed: [fx.delayed(2, [fx.rel('fans', 6)])],
        hidden: [fx.hidden('loyaute', 3)],
      }),
      choice({
        id: 'accrocher',
        label: 'T’accrocher encore un peu',
        stance: 'resilient',
        riskPreview: 'Adieu retardé, tableau terni.',
        immediate: [fx.flag('mentor_legacy'), fx.res('reputationSportive', 2), fx.rel('teammates', -3)],
        hidden: [fx.hidden('ambition', 2)],
      }),
    ],
  }),
  chainEpisode({
    id: 'p10_chain_protege_ep3_trahison',
    previousEventId: 'p10_chain_protege_ep2',
    prerequisites: [{ type: 'hasFlag', key: 'protege_held' }],
    title: 'Le gamin a tout compris',
    body: 'Ton protégé découvre tes manœuvres et le fait savoir sans ménagement. Reconnaître ta faute désamorce la rancœur et écorne ta stature devant le groupe. Nier en bloc sauve les apparences et te vaut l’inimitié durable d’un talent que tu as déçu.',
    tags: ['vestiaire', 'trahison'],
    echoes: [
      { flag: 'mentoring_prodigy', text: 'Le gamin protégé depuis {years} saisons n’oubliera pas ta trahison.' },
    ],
    choices: [
      choice({
        id: 'reconnaitre',
        label: 'Reconnaître ta faute',
        stance: 'ethical',
        riskPreview: 'Rancœur désamorcée, stature écornée.',
        immediate: [fx.flag('mentor_betrayed'), fx.rel('teammates', 3), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
      choice({
        id: 'nier',
        label: 'Nier en bloc',
        stance: 'individualist',
        riskPreview: 'Apparences sauvées, inimitié durable.',
        immediate: [fx.flag('mentor_betrayed'), fx.res('reputationSportive', 1), fx.rel('teammates', -6)],
        delayed: [fx.delayed(2, [fx.res('cohesionVestiaire', -5)])],
        hidden: [fx.hidden('loyaute', -2)],
      }),
    ],
  }),
]
