import { dilemma, choice, fx } from '../helpers'
import type { DilemmaDefinition } from '../../../game-engine/dilemmas'

/**
 * Phase 8 — Blessures & santé. Inclut alerte de données biométriques.
 * Situations neuves, distinctes du lot Phase 5. Emplacement 1 (sportif).
 */
export const blessureDilemmas: DilemmaDefinition[] = [
  dilemma({
    id: 'p8_inj_biometrie',
    title: 'Tes capteurs sonnent l’alarme',
    body: 'Les données biométriques du club clignotent rouge : surcharge, risque de blessure imminent. Écouter les chiffres et te mettre au repos protège ton corps mais te sort du groupe pour l’affiche. Ignorer l’alerte pour jouer défie la science et t’expose à la déchirure que tout le monde voit venir.',
    category: 'injury',
    tags: ['sante', 'biometrie', 'donnees'],
    rarity: 'uncommon',
    weight: 7,
    ageMin: 18,
    ageMax: 37,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'ecouter',
        label: 'Écouter les données, te reposer',
        stance: 'professional',
        riskPreview: 'Corps protégé, absent pour l’affiche.',
        immediate: [fx.res('sante', 5), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('professionnalisme', 3)],
      }),
      choice({
        id: 'ignorer',
        label: 'Ignorer l’alerte et jouer',
        stance: 'high_risk',
        riskPreview: 'Match honoré, déchirure qui menace.',
        immediate: [fx.res('confianceEntraineur', 4), fx.res('fatigue', 6)],
        hidden: [fx.hidden('resistancePression', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('sante', -12)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_inj_commotion',
    title: 'Un choc à la tête, et la finale',
    body: 'Un choc violent te laisse groggy à l’entrée d’un match capital. Sortir et suivre le protocole protège ton cerveau, priorité qu’aucun trophée ne vaut, mais abandonne l’équipe. Serrer les dents pour rester honore le collectif et joue avec un organe qui ne pardonne pas les paris.',
    category: 'injury',
    tags: ['sante', 'commotion', 'tete'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 17,
    ageMax: 38,
    cooldownSeasons: 6,
    choices: [
      choice({
        id: 'sortir',
        label: 'Sortir et suivre le protocole',
        stance: 'professional',
        riskPreview: 'Cerveau protégé, équipe abandonnée.',
        immediate: [fx.res('sante', 4), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('professionnalisme', 3)],
      }),
      choice({
        id: 'rester',
        label: 'Serrer les dents et rester',
        stance: 'high_risk',
        riskPreview: 'Collectif servi, tête mise en jeu.',
        immediate: [fx.rel('teammates', 5), fx.res('sante', -6)],
        hidden: [fx.hidden('resistancePression', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.35, [fx.res('sante', -10)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_inj_genou_chronique',
    title: 'Ce genou qui ne guérit jamais',
    body: 'Ton genou t’élance à chaque reprise ; les médecins prônent une gestion prudente sur la durée. Réduire ta charge prolonge ta carrière et te fait tourner à mi-régime, moins décisif. Ignorer la gêne pour tout donner maximise tes matchs à haut niveau et rapproche l’usure irréversible.',
    category: 'injury',
    tags: ['sante', 'chronique', 'gestion'],
    rarity: 'common',
    weight: 6,
    ageMin: 24,
    ageMax: 38,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'gerer',
        label: 'Gérer prudemment ta charge',
        stance: 'professional',
        riskPreview: 'Carrière prolongée, rendement bridé.',
        immediate: [fx.res('sante', 4), fx.res('reputationSportive', -2)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
      choice({
        id: 'forcer',
        label: 'Tout donner malgré la gêne',
        stance: 'resilient',
        riskPreview: 'Matchs de haut vol, usure accélérée.',
        immediate: [fx.res('reputationSportive', 4), fx.res('sante', -5)],
        hidden: [fx.hidden('fragilitePhysique', 2)],
        delayed: [fx.delayed(2, [fx.chance(0.35, [fx.res('sante', -10)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_inj_burnout',
    title: 'La tête au bout du rouleau',
    body: 'Ce n’est pas le corps, c’est le mental qui lâche : plus d’envie, plus de sommeil, un vide. Poser quelques jours loin du foot pour te reconstruire soigne l’essentiel mais alarme le club. Serrer les dents en silence sauve les apparences et enfonce un peu plus une spirale que personne ne voit.',
    category: 'injury',
    tags: ['sante', 'mental', 'burnout'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 18,
    ageMax: 37,
    cooldownSeasons: 6,
    choices: [
      choice({
        id: 'pause',
        label: 'Prendre du recul quelques jours',
        stance: 'professional',
        riskPreview: 'Mental réparé, club alarmé.',
        immediate: [fx.res('bienEtre', 8), fx.res('confianceEntraineur', -4)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
      choice({
        id: 'serrer',
        label: 'Serrer les dents en silence',
        stance: 'resilient',
        riskPreview: 'Apparences sauvées, spirale qui creuse.',
        immediate: [fx.res('reputationSportive', 2), fx.res('bienEtre', -6)],
        hidden: [fx.hidden('resistancePression', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.35, [fx.res('moral', -10)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_inj_antidouleurs',
    title: 'La pilule qui efface la douleur',
    body: 'Le staff médical te propose des antidouleurs plus musclés pour tenir la cadence. Les accepter t’efface la souffrance et te rend disponible, au risque d’une accoutumance sournoise. Les refuser garde ta lucidité sur ton corps et te laisse boiter là où d’autres avaleraient sans réfléchir.',
    category: 'injury',
    tags: ['sante', 'medicaments', 'ethique'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 19,
    ageMax: 37,
    cooldownSeasons: 6,
    choices: [
      choice({
        id: 'accepter',
        label: 'Accepter les antidouleurs',
        stance: 'high_risk',
        riskPreview: 'Disponible et sans douleur, accoutumance sournoise.',
        immediate: [fx.res('forme', 4), fx.res('sante', -3)],
        hidden: [fx.hidden('professionnalisme', -2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('sante', -8)])])],
      }),
      choice({
        id: 'refuser',
        label: 'Refuser et écouter ton corps',
        stance: 'professional',
        riskPreview: 'Lucidité gardée, douleur endurée.',
        immediate: [fx.res('sante', 3), fx.res('confianceEntraineur', -3)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_inj_avis_contraires',
    title: 'Deux médecins, deux verdicts',
    body: 'Le médecin du club te déclare apte ; ton spécialiste personnel réclame trois semaines de plus. Suivre le club te remet vite au jeu et lui plaît, au prix d’un retour peut-être précipité. Écouter ton spécialiste protège ton corps et défie ouvertement le staff médical de la maison.',
    category: 'injury',
    tags: ['sante', 'staff', 'retour'],
    rarity: 'common',
    weight: 6,
    ageMin: 19,
    ageMax: 38,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'club',
        label: 'Suivre le médecin du club',
        stance: 'prudent',
        riskPreview: 'Retour rapide, corps peut-être bâclé.',
        immediate: [fx.res('confianceEntraineur', 5), fx.res('sante', -3)],
        hidden: [fx.hidden('adaptabilite', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('sante', -8)])])],
      }),
      choice({
        id: 'specialiste',
        label: 'Écouter ton spécialiste',
        stance: 'professional',
        riskPreview: 'Corps protégé, staff maison défié.',
        immediate: [fx.res('sante', 5), fx.rel('coach', -5)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_inj_test_rate_cache',
    title: 'Le test de retour que tu as raté',
    body: 'Ton test physique de reprise est en dessous des seuils, mais toi seul le sais vraiment. Le taire te renvoie sur le terrain plus vite et rassure tout le monde, sur une jambe qui n’est pas prête. L’avouer repousse ton retour et te prive d’une place que d’autres saisiront sans hésiter.',
    category: 'injury',
    tags: ['sante', 'retour', 'secret'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 19,
    ageMax: 37,
    cooldownSeasons: 6,
    choices: [
      choice({
        id: 'taire',
        label: 'Taire le test raté',
        stance: 'high_risk',
        riskPreview: 'Retour accéléré, jambe pas prête.',
        immediate: [fx.res('reputationSportive', 3), fx.res('sante', -4)],
        hidden: [fx.hidden('professionnalisme', -2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('sante', -10)])])],
      }),
      choice({
        id: 'avouer',
        label: 'Avouer et attendre',
        stance: 'ethical',
        riskPreview: 'Corps respecté, place laissée à d’autres.',
        immediate: [fx.res('sante', 4), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_inj_nutrition',
    title: 'Le régime qui bouscule tes habitudes',
    body: 'Un nutritionniste veut révolutionner ton alimentation, à rebours de tout ce qui te réussissait. Suivre son plan strict peut affûter ton corps ou te couper de tes repères et de ton confort. Garder tes habitudes préserve ton bien-être et ferme la porte à un gain physique peut-être décisif.',
    category: 'injury',
    tags: ['sante', 'nutrition', 'hygiene'],
    rarity: 'common',
    weight: 5,
    ageMin: 18,
    ageMax: 36,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'suivre',
        label: 'Suivre le plan strict',
        stance: 'professional',
        riskPreview: 'Corps affûté possible, repères bousculés.',
        immediate: [fx.res('forme', 4), fx.res('bienEtre', -3)],
        hidden: [fx.hidden('professionnalisme', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('sante', 5)])])],
      }),
      choice({
        id: 'habitudes',
        label: 'Garder tes habitudes',
        stance: 'prudent',
        riskPreview: 'Confort gardé, gain physique manqué.',
        immediate: [fx.res('bienEtre', 3), fx.res('forme', -2)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_inj_recuperation_gadget',
    title: 'La récupération dernier cri',
    body: 'Un protocole de récupération à la mode, coûteux et non prouvé, séduit une partie du vestiaire. L’adopter peut accélérer tes lendemains de match ou n’être qu’un gadget qui te vide le portefeuille. T’en tenir aux méthodes classiques garde ton argent et te laisse peut-être un cran derrière les curieux.',
    category: 'injury',
    tags: ['sante', 'recuperation', 'mode'],
    rarity: 'common',
    weight: 5,
    ageMin: 19,
    ageMax: 37,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'adopter',
        label: 'Adopter le protocole à la mode',
        stance: 'high_risk',
        riskPreview: 'Lendemains meilleurs peut-être, portefeuille vidé.',
        immediate: [fx.cash(-12000), fx.res('forme', 3)],
        hidden: [fx.hidden('adaptabilite', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('sante', 4)])])],
      }),
      choice({
        id: 'classique',
        label: 'Rester aux méthodes éprouvées',
        stance: 'prudent',
        riskPreview: 'Argent gardé, un cran derrière peut-être.',
        immediate: [fx.res('financesPersonnelles', 3), fx.res('forme', -2)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_inj_charge_gros_match',
    title: 'Ménagé, mais le grand match arrive',
    body: 'Le staff veut gérer ta charge, or l’affiche du siècle se profile pile à ce moment. Te préserver comme prévu sécurise ta saison entière et te fait manquer le rendez-vous que tout le monde attend. Forcer pour être là honore le grand soir et grille des réserves que tu paieras plus tard.',
    category: 'injury',
    tags: ['sante', 'charge', 'grand_match'],
    rarity: 'common',
    weight: 6,
    ageMin: 20,
    ageMax: 37,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'preserver',
        label: 'Te préserver comme prévu',
        stance: 'professional',
        riskPreview: 'Saison sécurisée, grand rendez-vous manqué.',
        immediate: [fx.res('forme', 4), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
      choice({
        id: 'forcer',
        label: 'Forcer pour le grand match',
        stance: 'resilient',
        riskPreview: 'Grand soir honoré, réserves grillées.',
        immediate: [fx.res('reputationSportive', 5), fx.res('fatigue', 7)],
        hidden: [fx.hidden('grandsMatchs', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('forme', -8)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_inj_retour_public',
    title: 'Le public réclame ton retour',
    body: 'À peine remis à moitié, tu sens la pression des tribunes et des médias qui te veulent déjà de retour. Céder à l’attente t’offre un retour héroïque et un risque de rechute immédiate. Tenir ton calendrier de reprise protège ton corps et déçoit un public qui t’oubliera vite si tu tardes.',
    category: 'injury',
    tags: ['sante', 'retour', 'medias'],
    rarity: 'common',
    weight: 6,
    ageMin: 19,
    ageMax: 37,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'ceder',
        label: 'Revenir pour le public',
        stance: 'high_risk',
        riskPreview: 'Retour héroïque, rechute qui guette.',
        immediate: [fx.rel('fans', 8), fx.res('sante', -5)],
        hidden: [fx.hidden('resistancePression', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('sante', -8)])])],
      }),
      choice({
        id: 'calendrier',
        label: 'Tenir ton calendrier',
        stance: 'professional',
        riskPreview: 'Corps protégé, public déçu.',
        immediate: [fx.res('sante', 5), fx.rel('fans', -4)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_inj_rehab_solitude',
    title: 'La rééducation, seul dans ton coin',
    body: 'De longs mois de rééducation t’éloignent du groupe et rongent ton moral. Rester traîner au vestiaire malgré l’inutilité entretient ton lien social, au prix d’un rythme de soin perturbé. T’isoler pour te concentrer sur ta reconstruction optimise ta reprise et creuse une distance que le groupe finira par acter.',
    category: 'injury',
    tags: ['sante', 'reeducation', 'mental'],
    rarity: 'common',
    weight: 5,
    ageMin: 19,
    ageMax: 37,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'groupe',
        label: 'Rester près du groupe',
        stance: 'collective',
        riskPreview: 'Lien gardé, soins un peu perturbés.',
        immediate: [fx.res('bienEtre', 4), fx.res('sante', -2)],
        hidden: [fx.hidden('loyaute', 2)],
      }),
      choice({
        id: 'isoler',
        label: 'T’isoler pour te reconstruire',
        stance: 'professional',
        riskPreview: 'Reprise optimisée, distance qui s’installe.',
        immediate: [fx.res('sante', 5), fx.res('cohesionVestiaire', -4)],
        hidden: [fx.hidden('professionnalisme', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('moral', -5)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_inj_petit_bobo_repos',
    title: 'Un bobo commode avant un match inutile',
    body: 'Une gêne mineure te donne un prétexte pour souffler avant une rencontre sans enjeu. Grossir le bobo t’offre un repos bienvenu mais trompe le staff et écorne ta fiabilité si ça se sait. Jouer malgré tout prouve ton sérieux et gaspille une occasion rare de recharger les batteries.',
    category: 'injury',
    tags: ['sante', 'repos', 'ethique'],
    rarity: 'common',
    weight: 5,
    ageMin: 20,
    ageMax: 37,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'grossir',
        label: 'Grossir le bobo pour souffler',
        stance: 'individualist',
        riskPreview: 'Repos gagné, fiabilité écornée si ça se sait.',
        immediate: [fx.res('forme', 4), fx.res('discipline', -3)],
        hidden: [fx.hidden('professionnalisme', -2)],
        delayed: [fx.delayed(1, [fx.chance(0.25, [fx.res('confianceEntraineur', -6)])])],
      }),
      choice({
        id: 'jouer',
        label: 'Jouer malgré la gêne',
        stance: 'professional',
        riskPreview: 'Sérieux prouvé, batteries jamais rechargées.',
        immediate: [fx.res('confianceEntraineur', 4), fx.res('fatigue', 4)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_inj_sommeil_clinique',
    title: 'Tes nuits te lâchent',
    body: 'Des insomnies chroniques rongent tes performances sans que personne ne le sache. Entrer dans une clinique du sommeil traite le mal à la racine mais s’ébruite et inquiète le club. Encaisser tes nuits blanches préserve le secret et te fait aborder chaque match avec un réservoir déjà entamé.',
    category: 'injury',
    tags: ['sante', 'sommeil', 'mental'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 19,
    ageMax: 37,
    cooldownSeasons: 6,
    choices: [
      choice({
        id: 'clinique',
        label: 'Consulter une clinique du sommeil',
        stance: 'professional',
        riskPreview: 'Mal traité, inquiétude ébruitée.',
        immediate: [fx.res('sante', 5), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('professionnalisme', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('forme', 5)])])],
      }),
      choice({
        id: 'encaisser',
        label: 'Encaisser tes nuits blanches',
        stance: 'resilient',
        riskPreview: 'Secret gardé, réservoir entamé.',
        immediate: [fx.res('bienEtre', -3), fx.res('reputationSportive', 2)],
        hidden: [fx.hidden('resistancePression', 2)],
      }),
    ],
  }),
]
