import { dilemma, choice, fx } from '../helpers'
import type { DilemmaDefinition } from '../../../game-engine/dilemmas'

/**
 * Phase 8 — Entraîneur. Situations neuves, distinctes du lot Phase 5/7.
 * Emplacement 1 (sportif) / 2 (carrière) selon le thème.
 */
export const coachDilemmas: DilemmaDefinition[] = [
  dilemma({
    id: 'p8_coach_rotation',
    title: 'Reposé pour le choc de la saison',
    body: 'Le coach t’annonce au repos juste avant l’affiche que tout le pays attend. Il parle de gestion, tu entends « écarté ». Accepter sa rotation preserve ton corps et sa confiance ; réclamer ta place à tout prix affirme ton statut mais défie ouvertement son autorité.',
    category: 'coach',
    tags: ['coach', 'rotation', 'statut'],
    rarity: 'common',
    weight: 8,
    ageMin: 20,
    ageMax: 36,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'accepter',
        label: 'Accepter d’être reposé',
        stance: 'professional',
        riskPreview: 'Corps ménagé, place de titulaire en jeu.',
        immediate: [fx.res('forme', 4), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
      choice({
        id: 'exiger',
        label: 'Exiger de jouer le choc',
        stance: 'ambitious',
        riskPreview: 'Statut affirmé, autorité défiée.',
        immediate: [fx.res('reputationSportive', 4), fx.rel('coach', -7)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('fatigue', 8)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_coach_eloge_public',
    title: 'Encensé en conférence de presse',
    body: 'Le coach te désigne publiquement comme son homme de base pour la saison. Le compliment gonfle ta cote mais installe une pression permanente à chaque match raté. Tempérer ses louanges devant la presse te protège du contrecoup et refroidit un peu la main qu’il te tend.',
    category: 'coach',
    tags: ['coach', 'pression', 'medias'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 18,
    ageMax: 34,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'assumer',
        label: 'Assumer le rôle de leader',
        stance: 'ambitious',
        riskPreview: 'Cote en hausse, pression écrasante.',
        immediate: [fx.res('reputationSportive', 5), fx.res('bienEtre', -4)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('moral', -6)])])],
      }),
      choice({
        id: 'temperer',
        label: 'Tempérer les louanges',
        stance: 'prudent',
        riskPreview: 'Pression allégée, coach un peu déçu.',
        immediate: [fx.res('bienEtre', 3), fx.rel('coach', -4)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_coach_servir_star',
    title: 'Jouer pour la star maison',
    body: 'Le coach te demande de te sacrifier pour faire briller la vedette du club : lui offrir les ballons, gommer tes initiatives. Obéir soigne le collectif et ta relation au staff, mais fond ton apport visible. T’affranchir pour exister risque de te griller aux yeux du coach.',
    category: 'coach',
    tags: ['coach', 'role', 'collectif'],
    rarity: 'common',
    weight: 7,
    ageMin: 18,
    ageMax: 34,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'servir',
        label: 'Te sacrifier pour la vedette',
        stance: 'collective',
        riskPreview: 'Coach satisfait, apport personnel dilué.',
        immediate: [fx.res('confianceEntraineur', 6), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('loyaute', 2)],
      }),
      choice({
        id: 'exister',
        label: 'Jouer ta propre carte',
        stance: 'individualist',
        riskPreview: 'Stats gonflées, coach refroidi.',
        immediate: [fx.res('reputationSportive', 4), fx.rel('coach', -6)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('cohesionVestiaire', -5)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_coach_adjoint_contredit',
    title: 'Deux voix, un seul terrain',
    body: 'L’adjoint te glisse des consignes qui contredisent celles du coach principal. Suivre l’adjoint peut coller à la vérité du terrain mais te placer du mauvais côté d’un conflit de staff. T’en tenir au patron évite les ennuis et te prive parfois du meilleur conseil.',
    category: 'coach',
    tags: ['coach', 'staff', 'consigne'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 18,
    ageMax: 36,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'adjoint',
        label: 'Suivre l’adjoint',
        stance: 'high_risk',
        riskPreview: 'Bon conseil suivi, conflit de staff frôlé.',
        immediate: [fx.stat('tactique', 2), fx.rel('coach', -5)],
        hidden: [fx.hidden('adaptabilite', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('confianceEntraineur', -5)])])],
      }),
      choice({
        id: 'patron',
        label: 'Respecter le coach principal',
        stance: 'loyal',
        riskPreview: 'Hiérarchie tenue, conseil ignoré.',
        immediate: [fx.res('confianceEntraineur', 4), fx.res('reputationSportive', -2)],
        hidden: [fx.hidden('loyaute', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_coach_hors_position',
    title: 'Testé à un poste inconnu',
    body: 'Le temps d’un match, le coach te bombarde à un poste que tu n’as jamais tenu. Relever le défi montre ta polyvalence mais t’expose à un fiasco public. Refuser poliment protège tes repères et laisse entendre que tu manques de solutions quand l’équipe en a besoin.',
    category: 'coach',
    tags: ['coach', 'poste', 'polyvalence'],
    rarity: 'common',
    weight: 7,
    ageMin: 18,
    ageMax: 36,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'relever',
        label: 'Relever le défi',
        stance: 'ambitious',
        riskPreview: 'Polyvalence prouvée, fiasco possible.',
        immediate: [fx.stat('tactique', 2), fx.res('fatigue', 4)],
        hidden: [fx.hidden('adaptabilite', 3)],
        delayed: [fx.delayed(1, [fx.chance(0.35, [fx.res('reputationSportive', -5)])])],
      }),
      choice({
        id: 'refuser',
        label: 'Refuser poliment',
        stance: 'prudent',
        riskPreview: 'Repères gardés, coach déçu.',
        immediate: [fx.res('bienEtre', 2), fx.rel('coach', -5)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_coach_brassard_conditions',
    title: 'Le brassard, mais à ses conditions',
    body: 'Le coach t’offre le capitanat, à condition de relayer sa parole et d’étouffer les grognes du vestiaire. Accepter t’élève et te charge d’un rôle de porte-voix parfois ingrat. Décliner préserve ta liberté auprès du groupe et referme une porte qui ne se rouvre pas souvent.',
    category: 'coach',
    tags: ['coach', 'capitanat', 'statut'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 22,
    ageMax: 37,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'accepter',
        label: 'Accepter le brassard',
        stance: 'ambitious',
        riskPreview: 'Statut gagné, rôle de porte-voix ingrat.',
        immediate: [fx.stat('leadership', 2), fx.res('cohesionVestiaire', -4)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('confianceEntraineur', 6)])])],
      }),
      choice({
        id: 'decliner',
        label: 'Décliner pour garder ta liberté',
        stance: 'loyal',
        riskPreview: 'Groupe préservé, occasion refermée.',
        immediate: [fx.rel('teammates', 5), fx.rel('coach', -6)],
        hidden: [fx.hidden('loyaute', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_coach_ultimatum_forme',
    title: 'Reviens plus affûté, ou reste dehors',
    body: 'Le coach juge ta condition physique en dessous et pose un ultimatum : t’affûter en deux semaines ou perdre ta place. Te plier à son plan brutal peut te relancer ou te cramer. Contester ses tests remet en cause sa méthode et durcit un bras de fer que tu peux perdre.',
    category: 'coach',
    tags: ['coach', 'forme', 'ultimatum'],
    rarity: 'common',
    weight: 7,
    ageMin: 19,
    ageMax: 36,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'plier',
        label: 'Suivre son plan à la lettre',
        stance: 'professional',
        riskPreview: 'Relance possible, surcharge qui use.',
        immediate: [fx.res('confianceEntraineur', 5), fx.res('fatigue', 6)],
        hidden: [fx.hidden('professionnalisme', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.35, [fx.res('forme', 6)])])],
      }),
      choice({
        id: 'contester',
        label: 'Contester ses tests',
        stance: 'individualist',
        riskPreview: 'Méthode défiée, bras de fer risqué.',
        immediate: [fx.res('bienEtre', 3), fx.rel('coach', -8)],
        hidden: [fx.hidden('resistancePression', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_coach_critique_presse',
    title: 'Le coach te vise dans la presse',
    body: 'En conférence, le coach pointe ton manque d’implication devant tous les micros. Répondre publiquement défend ton honneur mais transforme un froid en guerre ouverte. Encaisser en silence protège l’unité de façade et laisse penser que tu acceptes le reproche sans broncher.',
    category: 'coach',
    tags: ['coach', 'medias', 'conflit'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 19,
    ageMax: 37,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'repondre',
        label: 'Répondre publiquement',
        stance: 'high_risk',
        riskPreview: 'Honneur défendu, guerre ouverte déclenchée.',
        immediate: [fx.res('reputationSportive', 3), fx.rel('coach', -10)],
        hidden: [fx.hidden('resistancePression', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('confianceEntraineur', -6)])])],
      }),
      choice({
        id: 'encaisser',
        label: 'Encaisser en silence',
        stance: 'professional',
        riskPreview: 'Façade tenue, reproche semblant accepté.',
        immediate: [fx.res('discipline', 3), fx.res('moral', -5)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_coach_soutien_menace',
    title: 'Ton coach au bord de l’éjection',
    body: 'La direction hésite à limoger ton entraîneur. Il te demande discrètement un mot de soutien à la presse. Le défendre publiquement peut le sauver et sceller votre lien, ou te faire couler avec lui s’il tombe. Te taire protège ton avenir et ressemble à une trahison.',
    category: 'coach',
    tags: ['coach', 'loyaute', 'medias'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 20,
    ageMax: 38,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'soutenir',
        label: 'Le soutenir publiquement',
        stance: 'loyal',
        riskPreview: 'Lien scellé, chute commune possible.',
        immediate: [fx.rel('coach', 10), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('loyaute', 3)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('confianceEntraineur', -6)])])],
      }),
      choice({
        id: 'taire',
        label: 'Te taire prudemment',
        stance: 'prudent',
        riskPreview: 'Avenir préservé, goût de trahison.',
        immediate: [fx.res('bienEtre', 2), fx.rel('coach', -8)],
        hidden: [fx.hidden('ambition', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_coach_banc_pour_jeune',
    title: 'Sacrifié pour un espoir maison',
    body: 'Le coach mise sur un jeune très prometteur et te relègue pour le lancer. Jouer le grand frère exemplaire soigne ton image et le vestiaire, au prix de ton temps de jeu. Faire ouvertement barrage à ce gamin défend ta place mais te dessine en frein au projet.',
    category: 'coach',
    tags: ['coach', 'jeune', 'temps_de_jeu'],
    rarity: 'common',
    weight: 7,
    ageMin: 24,
    ageMax: 38,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'exemplaire',
        label: 'Jouer le grand frère',
        stance: 'collective',
        riskPreview: 'Image soignée, temps de jeu grignoté.',
        immediate: [fx.rel('teammates', 6), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('professionnalisme', 3)],
      }),
      choice({
        id: 'barrage',
        label: 'Défendre bec et ongles ta place',
        stance: 'individualist',
        riskPreview: 'Place gardée, image de frein.',
        immediate: [fx.res('reputationSportive', 3), fx.rel('coach', -6)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('cohesionVestiaire', -5)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_coach_stage_commando',
    title: 'Le stage qui casse les jambes',
    body: 'Le coach impose un stage commando hors saison, à la limite du raisonnable. Tout donner prouve ton engagement et bâtit un socle physique, au risque de la blessure de trop. Lever le pied discrètement te préserve mais s’aperçoit vite et te range parmi les tièdes.',
    category: 'training',
    tags: ['coach', 'stage', 'engagement'],
    rarity: 'common',
    weight: 7,
    ageMin: 18,
    ageMax: 35,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'donner',
        label: 'Tout donner au stage',
        stance: 'resilient',
        riskPreview: 'Socle physique bâti, blessure qui guette.',
        immediate: [fx.res('forme', 5), fx.res('fatigue', 8)],
        hidden: [fx.hidden('professionnalisme', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.25, [fx.res('sante', -8)])])],
      }),
      choice({
        id: 'menager',
        label: 'Te ménager discrètement',
        stance: 'prudent',
        riskPreview: 'Corps épargné, réputation de tiède.',
        immediate: [fx.res('bienEtre', 3), fx.res('confianceEntraineur', -5)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_coach_antijeu_consigne',
    title: 'Consigne : gratter chaque seconde',
    body: 'Menés au tableau d’affichage renversé, le coach ordonne l’antijeu total : simuler, ralentir, saouler l’arbitre. Exécuter peut voler un résultat précieux mais salit ton image et t’attire des cartons. Refuser de jouer ce rôle garde ta dignité et t’isole d’un banc obsédé par la victoire.',
    category: 'coach',
    tags: ['coach', 'antijeu', 'ethique'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 19,
    ageMax: 38,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'executer',
        label: 'Gratter chaque seconde',
        stance: 'high_risk',
        riskPreview: 'Résultat volé, image et cartons en jeu.',
        immediate: [fx.res('confianceEntraineur', 5), fx.res('discipline', -5)],
        hidden: [fx.hidden('ambition', 1)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.rel('fans', -6)])])],
      }),
      choice({
        id: 'refuser',
        label: 'Refuser de tricher',
        stance: 'ethical',
        riskPreview: 'Dignité gardée, banc contrarié.',
        immediate: [fx.res('reputationSportive', 3), fx.rel('coach', -6)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_coach_replis_defensifs',
    title: 'Attaquant sommé de défendre',
    body: 'Le coach exige que tu couvres tout ton couloir défensivement, quitte à t’éteindre offensivement. Te muer en soldat du repli séduit le staff et solidifie l’équipe, mais éteint ce qui fait ta valeur. Garder ton énergie pour attaquer préserve tes stats et agace un coach obsédé par l’équilibre.',
    category: 'coach',
    tags: ['coach', 'role', 'defense'],
    rarity: 'common',
    weight: 7,
    ageMin: 18,
    ageMax: 35,
    positions: ['winger', 'cam'],
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'defendre',
        label: 'Te muer en soldat du repli',
        stance: 'collective',
        riskPreview: 'Staff conquis, éclat offensif éteint.',
        immediate: [fx.res('confianceEntraineur', 6), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('adaptabilite', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('fatigue', 8)])])],
      }),
      choice({
        id: 'attaquer',
        label: 'Garder ton énergie offensive',
        stance: 'individualist',
        riskPreview: 'Stats préservées, coach agacé.',
        immediate: [fx.stat('finition', 1), fx.rel('coach', -6)],
        hidden: [fx.hidden('ambition', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_coach_veto_transfert',
    title: 'Le coach bloque ton départ',
    body: 'Une offre t’ouvre les portes d’un club supérieur, mais le coach pose son veto : il te juge indispensable. Rester par respect pour lui nourrit votre lien et gèle ta carrière une saison. Forcer la sortie ouvre l’horizon mais brise net la confiance patiemment bâtie.',
    category: 'coach',
    tags: ['coach', 'transfert', 'loyaute'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 20,
    ageMax: 33,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'rester',
        label: 'Rester par respect',
        stance: 'loyal',
        riskPreview: 'Lien nourri, carrière gelée une saison.',
        immediate: [fx.rel('coach', 8), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('loyaute', 3)],
      }),
      choice({
        id: 'forcer',
        label: 'Forcer ton départ',
        stance: 'ambitious',
        riskPreview: 'Horizon ouvert, confiance brisée.',
        immediate: [fx.flag('transfer_accepted'), fx.rel('coach', -10)],
        hidden: [fx.hidden('ambition', 3)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('reputationSportive', 5)])])],
      }),
    ],
  }),
]
