import { dilemma, choice, fx } from '../helpers'
import type { DilemmaDefinition } from '../../../game-engine/dilemmas'

/**
 * Phase 8 — Concurrence & rivalité. Inclut rival recruté au même club et
 * recrue imposée par le propriétaire. Emplacement 2 (carrière) surtout.
 */
export const concurrenceDilemmas: DilemmaDefinition[] = [
  dilemma({
    id: 'p8_conc_rival_meme_club',
    title: 'Ton rival signe dans ton club',
    body: 'Celui que tu affrontais match après match débarque à ton poste, dans ton vestiaire. L’accueillir en pro désamorce la guerre et impressionne le staff, au prix d’un concurrent choyé. Le glacer d’entrée marque ton territoire et installe une tension quotidienne dont l’équipe fera les frais.',
    category: 'rivalry',
    tags: ['concurrence', 'recrue', 'poste'],
    rarity: 'uncommon',
    weight: 7,
    ageMin: 19,
    ageMax: 36,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'accueillir',
        label: 'L’accueillir en professionnel',
        stance: 'professional',
        riskPreview: 'Staff séduit, concurrent renforcé.',
        immediate: [fx.res('reputationSportive', 3), fx.res('confianceEntraineur', 4)],
        hidden: [fx.hidden('professionnalisme', 3)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('reputationSportive', -4)])])],
      }),
      choice({
        id: 'glacer',
        label: 'Marquer ton territoire',
        stance: 'individualist',
        riskPreview: 'Message envoyé, tension quotidienne.',
        immediate: [fx.res('reputationSportive', 2), fx.res('cohesionVestiaire', -5)],
        hidden: [fx.hidden('ambition', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_conc_proprio_recrue',
    title: 'Le propriétaire t’impose un concurrent',
    body: 'Le propriétaire signe à prix d’or une star à ton poste, pour son image plus que pour l’équipe. La prendre sous ton aile flatte le patron et sécurise ta relation avec la direction, au prix de ta place. Lui faire barrage défend ton statut et te met à dos l’homme qui signe les chèques.',
    category: 'rivalry',
    tags: ['concurrence', 'proprietaire', 'poste'],
    rarity: 'rare',
    weight: 4,
    ageMin: 20,
    ageMax: 35,
    cooldownSeasons: 6,
    choices: [
      choice({
        id: 'accompagner',
        label: 'Composer avec la recrue',
        stance: 'prudent',
        riskPreview: 'Patron flatté, ta place menacée.',
        immediate: [fx.res('reputationSportive', 2), fx.res('confianceEntraineur', -3)],
        hidden: [fx.hidden('adaptabilite', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.rel('sponsors', 5)])])],
      }),
      choice({
        id: 'barrage',
        label: 'Défendre ta place bec et ongles',
        stance: 'ambitious',
        riskPreview: 'Statut défendu, propriétaire remonté.',
        immediate: [fx.res('reputationSportive', 4), fx.rel('coach', -3)],
        hidden: [fx.hidden('ambition', 3)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('confianceEntraineur', -6)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_conc_prodige_centre',
    title: 'Le prodige du centre pousse fort',
    body: 'Un gamin de la formation crève les entraînements et vise ta place. L’aider à progresser grandit le club et ton aura de mentor, mais accélère ta propre relégation. Le brider subtilement retarde l’échéance et abîme ta réputation si le vestiaire découvre ton petit jeu.',
    category: 'rivalry',
    tags: ['concurrence', 'jeune', 'centre'],
    rarity: 'common',
    weight: 7,
    ageMin: 24,
    ageMax: 37,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'aider',
        label: 'L’aider à éclore',
        stance: 'ethical',
        riskPreview: 'Aura de mentor, relégation accélérée.',
        immediate: [fx.res('reputationSportive', 3), fx.res('confianceEntraineur', -3)],
        hidden: [fx.hidden('professionnalisme', 3)],
      }),
      choice({
        id: 'brider',
        label: 'Le brider en douce',
        stance: 'individualist',
        riskPreview: 'Échéance repoussée, image en péril si ça se sait.',
        immediate: [fx.res('reputationSportive', 2), fx.res('cohesionVestiaire', -4)],
        hidden: [fx.hidden('loyaute', -2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.rel('teammates', -5)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_conc_retour_pret',
    title: 'Le concurrent revient affamé',
    body: 'Prêté puis rappelé, un rival direct revient transformé, décidé à te voler ta place. Hausser ton niveau pour le contenir te tire vers le haut mais t’épuise nerveusement. Jouer la carte de l’ancienneté auprès du coach te protège un temps et sent la place acquise plus que méritée.',
    category: 'rivalry',
    tags: ['concurrence', 'pret', 'poste'],
    rarity: 'common',
    weight: 7,
    ageMin: 20,
    ageMax: 36,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'hausser',
        label: 'Hausser ton niveau',
        stance: 'resilient',
        riskPreview: 'Progrès forcés, usure nerveuse.',
        immediate: [fx.res('reputationSportive', 4), fx.res('fatigue', 5)],
        hidden: [fx.hidden('resistancePression', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('confianceEntraineur', 4)])])],
      }),
      choice({
        id: 'ancien',
        label: 'Jouer l’ancienneté',
        stance: 'prudent',
        riskPreview: 'Place gardée, mérite discutable.',
        immediate: [fx.res('confianceEntraineur', 3), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_conc_ami_meme_poste',
    title: 'Ton meilleur ami vise ta place',
    body: 'Ton pote du vestiaire et toi visez désormais le même poste de titulaire. Jouer franc jeu et l’affronter loyalement protège votre amitié, quitte à lui offrir ta place. User des coulisses pour peser sur le coach sécurise ton avenir et empoisonne un lien qui te tenait debout.',
    category: 'rivalry',
    tags: ['concurrence', 'amitie', 'poste'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 19,
    ageMax: 36,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'loyal',
        label: 'L’affronter loyalement',
        stance: 'loyal',
        riskPreview: 'Amitié protégée, place peut-être cédée.',
        immediate: [fx.rel('friends', 6), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('loyaute', 3)],
      }),
      choice({
        id: 'coulisses',
        label: 'Jouer des coulisses',
        stance: 'individualist',
        riskPreview: 'Avenir sécurisé, amitié empoisonnée.',
        immediate: [fx.res('confianceEntraineur', 4), fx.rel('friends', -8)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('moral', -5)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_conc_blessure_rival',
    title: 'Ton rival tombe, la voie s’ouvre',
    body: 'Le concurrent qui te barrait la route se blesse gravement. Rester classe et lui témoigner du soutien grandit ton image, mais te ramollit peut-être au moment de saisir ta chance. Foncer sans état d’âme pour t’installer maximise ta fenêtre et te dessine en rapace aux yeux du groupe.',
    category: 'rivalry',
    tags: ['concurrence', 'blessure', 'opportunite'],
    rarity: 'common',
    weight: 6,
    ageMin: 19,
    ageMax: 37,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'classe',
        label: 'Rester classe et le soutenir',
        stance: 'ethical',
        riskPreview: 'Image grandie, faim peut-être émoussée.',
        immediate: [fx.rel('teammates', 6), fx.res('reputationSportive', -2)],
        hidden: [fx.hidden('professionnalisme', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('cohesionVestiaire', 4)])])],
      }),
      choice({
        id: 'foncer',
        label: 'Foncer pour t’installer',
        stance: 'ambitious',
        riskPreview: 'Fenêtre saisie, image de rapace.',
        immediate: [fx.res('reputationSportive', 4), fx.rel('teammates', -4)],
        hidden: [fx.hidden('ambition', 3)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_conc_numero_maillot',
    title: 'Il réclame ton numéro fétiche',
    body: 'Une recrue clinquante veut ton numéro, celui qui te colle à la peau depuis tes débuts. Le lui céder contre une compensation apaise et arrondit tes finances, mais t’arrache un symbole. Le garder coûte que coûte affirme ton statut et lance une petite guerre d’ego dès le premier jour.',
    category: 'rivalry',
    tags: ['concurrence', 'symbole', 'ego'],
    rarity: 'common',
    weight: 5,
    ageMin: 20,
    ageMax: 37,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'ceder',
        label: 'Céder ton numéro',
        stance: 'financial',
        riskPreview: 'Paix et compensation, symbole arraché.',
        immediate: [fx.cash(15000), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('adaptabilite', 2)],
      }),
      choice({
        id: 'garder',
        label: 'Garder ton numéro',
        stance: 'individualist',
        riskPreview: 'Statut affirmé, guerre d’ego lancée.',
        immediate: [fx.res('reputationSportive', 3), fx.res('cohesionVestiaire', -3)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.rel('teammates', -4)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_conc_duel_mediatique',
    title: 'La presse monte votre duel en épingle',
    body: 'Les médias opposent sans cesse ton nom à celui d’un partenaire pour la même place. Entrer dans le jeu et surjouer la rivalité dope ta visibilité mais fracture le vestiaire. Éteindre le feu publiquement protège le groupe et te prive d’un projecteur que ton concurrent, lui, saisira.',
    category: 'rivalry',
    tags: ['concurrence', 'medias'],
    rarity: 'common',
    weight: 6,
    ageMin: 19,
    ageMax: 36,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'jouer',
        label: 'Surjouer la rivalité',
        stance: 'media_savvy',
        riskPreview: 'Visibilité dopée, vestiaire fracturé.',
        immediate: [fx.res('popularite', 5), fx.res('cohesionVestiaire', -5)],
        hidden: [fx.hidden('ambition', 2)],
      }),
      choice({
        id: 'eteindre',
        label: 'Éteindre le feu',
        stance: 'collective',
        riskPreview: 'Groupe protégé, projecteur laissé au rival.',
        immediate: [fx.res('cohesionVestiaire', 4), fx.res('popularite', -3)],
        hidden: [fx.hidden('professionnalisme', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.rel('teammates', 4)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_conc_poste_partage',
    title: 'Un poste pour deux, à mi-temps',
    body: 'Le coach décide de vous faire tourner, ton concurrent et toi, une mi-temps chacun. Jouer le jeu du partage montre ta maturité et garde le staff serein, au prix d’un rythme haché. Refuser ce mi-temps réclame le poste entier et force un choix qui peut te désigner perdant.',
    category: 'rivalry',
    tags: ['concurrence', 'rotation', 'poste'],
    rarity: 'common',
    weight: 6,
    ageMin: 19,
    ageMax: 36,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'partager',
        label: 'Accepter le partage',
        stance: 'collective',
        riskPreview: 'Maturité montrée, rythme haché.',
        immediate: [fx.res('confianceEntraineur', 4), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('adaptabilite', 2)],
      }),
      choice({
        id: 'entier',
        label: 'Réclamer le poste entier',
        stance: 'ambitious',
        riskPreview: 'Tout ou rien, désigné perdant possible.',
        immediate: [fx.res('reputationSportive', 3), fx.rel('coach', -5)],
        hidden: [fx.hidden('ambition', 3)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('confianceEntraineur', -6)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_conc_veteran_barre',
    title: 'Le vétéran qui te barre la route',
    body: 'Un cadre vieillissant s’accroche à la place que tout le monde te promet. Patienter en soutien respecte l’ordre des choses et fige ta progression une saison de plus. Pousser ouvertement pour sa mise à l’écart accélère ton avènement et te fait passer pour l’ingrat qui chasse les anciens.',
    category: 'rivalry',
    tags: ['concurrence', 'veteran', 'poste'],
    rarity: 'common',
    weight: 6,
    ageMin: 19,
    ageMax: 30,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'patienter',
        label: 'Patienter en soutien',
        stance: 'prudent',
        riskPreview: 'Ordre respecté, progression figée.',
        immediate: [fx.rel('teammates', 4), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
      choice({
        id: 'pousser',
        label: 'Pousser pour ta chance',
        stance: 'ambitious',
        riskPreview: 'Avènement accéléré, image d’ingrat.',
        immediate: [fx.res('reputationSportive', 3), fx.rel('teammates', -5)],
        hidden: [fx.hidden('ambition', 3)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('confianceEntraineur', 4)])])],
      }),
    ],
  }),
]
