import { dilemma, choice, fx } from '../helpers'
import type { DilemmaDefinition } from '../../../game-engine/dilemmas'

/**
 * Phase 8 — Médias & supporters. Inclut vidéo virale, fuite de conversation,
 * compte usurpé, membre du staff vendant des infos. Emplacement 2 surtout.
 */
export const mediaDilemmas: DilemmaDefinition[] = [
  dilemma({
    id: 'p8_media_video_virale',
    title: 'La vidéo qui tourne en boucle',
    body: 'Une vidéo de toi en soirée, sortie de son contexte, devient virale en une nuit. T’expliquer publiquement éteint la rumeur mais entretient le buzz une semaine de plus. Faire le mort laisse la tempête passer d’elle-même et laisse aussi le récit t’échapper aux mains des commentateurs.',
    category: 'media',
    tags: ['medias', 'reseaux', 'buzz'],
    rarity: 'uncommon',
    weight: 7,
    ageMin: 18,
    ageMax: 35,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'expliquer',
        label: 'T’expliquer publiquement',
        stance: 'media_savvy',
        riskPreview: 'Rumeur éteinte, buzz prolongé une semaine.',
        immediate: [fx.res('reputationSportive', 3), fx.res('popularite', -3)],
        hidden: [fx.hidden('resistancePression', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('reputationSportive', 3)])])],
      }),
      choice({
        id: 'silence',
        label: 'Faire le mort',
        stance: 'prudent',
        riskPreview: 'Tempête qui passe, récit qui t’échappe.',
        immediate: [fx.res('bienEtre', 2), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_media_fuite_conversation',
    title: 'Ta conversation privée fuite',
    body: 'Un échange privé où tu critiquais un coéquipier atterrit dans la presse. Assumer tes mots et t’excuser en face désamorce mais officialise la brouille. Nier être l’auteur protège la relation en surface et t’expose à un démenti si d’autres preuves sortent du chapeau.',
    category: 'media',
    tags: ['medias', 'fuite', 'vestiaire'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 18,
    ageMax: 37,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'assumer',
        label: 'Assumer et t’excuser',
        stance: 'ethical',
        riskPreview: 'Tension désamorcée, brouille officialisée.',
        immediate: [fx.rel('teammates', 5), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
      choice({
        id: 'nier',
        label: 'Nier en être l’auteur',
        stance: 'high_risk',
        riskPreview: 'Relation sauvée en façade, démenti possible.',
        immediate: [fx.res('reputationSportive', 2), fx.res('discipline', -3)],
        hidden: [fx.hidden('loyaute', -2)],
        delayed: [fx.delayed(1, [fx.chance(0.35, [fx.res('reputationSportive', -6)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_media_compte_usurpe',
    title: 'Quelqu’un poste en ton nom',
    body: 'Un faux compte à ton effigie déverse des propos scandaleux que tout le monde te prête. Le démentir vite et porter plainte rétablit la vérité mais donne de l’écho à l’imposteur. Ignorer l’affaire évite de nourrir le feu et laisse une fraction du public croire que c’était bien toi.',
    category: 'media',
    tags: ['medias', 'reseaux', 'usurpation'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 18,
    ageMax: 36,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'dementir',
        label: 'Démentir et porter plainte',
        stance: 'ethical',
        riskPreview: 'Vérité rétablie, écho donné à l’imposteur.',
        immediate: [fx.res('reputationSportive', 4), fx.res('bienEtre', -3)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
      choice({
        id: 'ignorer',
        label: 'Ignorer le faux compte',
        stance: 'prudent',
        riskPreview: 'Feu non nourri, doute qui persiste.',
        immediate: [fx.res('bienEtre', 2), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('constance', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('popularite', -4)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_media_staff_taupe',
    title: 'Une taupe vend le vestiaire',
    body: 'Tu découvres qu’un membre du staff monnaie des infos internes à des journalistes et des parieurs. Le dénoncer à la direction assainit le club mais déclenche une chasse aux sorcières qui t’éclaboussera. Te taire préserve la paix apparente et te rend complice d’une fuite qui vous coûtera cher.',
    category: 'media',
    tags: ['medias', 'staff', 'ethique'],
    rarity: 'rare',
    weight: 4,
    ageMin: 20,
    ageMax: 38,
    cooldownSeasons: 6,
    choices: [
      choice({
        id: 'denoncer',
        label: 'Dénoncer la taupe',
        stance: 'ethical',
        riskPreview: 'Club assaini, chasse aux sorcières éclaboussante.',
        immediate: [fx.res('reputationSportive', 3), fx.res('cohesionVestiaire', -4)],
        hidden: [fx.hidden('professionnalisme', 3)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.rel('teammates', -5)])])],
      }),
      choice({
        id: 'taire',
        label: 'Te taire et laisser courir',
        stance: 'prudent',
        riskPreview: 'Paix de façade, complicité qui coûtera.',
        immediate: [fx.res('bienEtre', 2), fx.res('discipline', -3)],
        hidden: [fx.hidden('loyaute', -1)],
        delayed: [fx.delayed(2, [fx.chance(0.3, [fx.res('reputationSportive', -6)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_media_boycott',
    title: 'Boycotter le média qui t’enterre',
    body: 'Un média multiplie les papiers à charge contre toi. Le boycotter ostensiblement fait du bruit et rallie tes fans, mais te ferme des portes et passe pour de la susceptibilité. Continuer à lui parler normalement désamorce l’animosité et te fait avaler des couleuvres semaine après semaine.',
    category: 'media',
    tags: ['medias', 'boycott'],
    rarity: 'common',
    weight: 5,
    ageMin: 19,
    ageMax: 37,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'boycotter',
        label: 'Boycotter ostensiblement',
        stance: 'high_risk',
        riskPreview: 'Fans ralliés, portes fermées.',
        immediate: [fx.rel('fans', 6), fx.rel('media', -8)],
        hidden: [fx.hidden('resistancePression', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('popularite', -4)])])],
      }),
      choice({
        id: 'continuer',
        label: 'Continuer à lui parler',
        stance: 'professional',
        riskPreview: 'Animosité désamorcée, couleuvres avalées.',
        immediate: [fx.rel('media', 5), fx.res('bienEtre', -3)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_media_podcast_cash',
    title: 'Le podcast qui veut du vrai',
    body: 'Un podcast très suivi t’invite pour un entretien sans filtre, cash et intime. Te livrer vraiment crée un moment fort et une popularité neuve, mais chaque phrase peut être découpée contre toi. Rester en pilotage automatique protège ton image et livre un épisode fade que personne ne partagera.',
    category: 'media',
    tags: ['medias', 'interview', 'popularite'],
    rarity: 'common',
    weight: 6,
    ageMin: 18,
    ageMax: 36,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'livrer',
        label: 'Te livrer sans filtre',
        stance: 'media_savvy',
        riskPreview: 'Popularité neuve, phrases découpables.',
        immediate: [fx.res('popularite', 6), fx.res('reputationSportive', -2)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('reputationSportive', -5)])])],
      }),
      choice({
        id: 'automatique',
        label: 'Rester en pilotage automatique',
        stance: 'prudent',
        riskPreview: 'Image protégée, épisode oubliable.',
        immediate: [fx.res('bienEtre', 2), fx.res('popularite', -3)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_media_chronique_ghost',
    title: 'Une chronique signée de ton nom',
    body: 'Un journal te propose une chronique lucrative que tu ne feras qu’effleurer : un nègre écrira l’essentiel. Accepter arrondit tes revenus et ta visibilité, au risque d’un texte polémique qu’on te collera. Refuser garde ton intégrité et laisse filer un cachet confortable pour trois lignes par semaine.',
    category: 'media',
    tags: ['medias', 'chronique', 'argent'],
    rarity: 'common',
    weight: 5,
    ageMin: 20,
    ageMax: 38,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'accepter',
        label: 'Signer la chronique',
        stance: 'financial',
        riskPreview: 'Revenus et visibilité, texte polémique possible.',
        immediate: [fx.cash(14000), fx.res('reputationSportive', -2)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.rel('teammates', -4)])])],
      }),
      choice({
        id: 'refuser',
        label: 'Refuser la facilité',
        stance: 'ethical',
        riskPreview: 'Intégrité gardée, cachet laissé.',
        immediate: [fx.res('reputationSportive', 2), fx.res('financesPersonnelles', -2)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_fans_fresque',
    title: 'Une fresque à ton effigie',
    body: 'Des supporters veulent peindre un mur immense à ton image dans le quartier du stade. Bénir le projet et t’afficher soude ton lien au public, mais te met une pression de statue vivante. Le décliner par pudeur protège ta légèreté et blesse des fans qui voulaient graver ton nom.',
    category: 'fans',
    tags: ['supporters', 'image', 'quartier'],
    rarity: 'common',
    weight: 5,
    ageMin: 20,
    ageMax: 38,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'benir',
        label: 'Bénir la fresque',
        stance: 'media_savvy',
        riskPreview: 'Lien scellé, pression de statue vivante.',
        immediate: [fx.rel('fans', 8), fx.res('bienEtre', -3)],
        hidden: [fx.hidden('ambition', 2)],
      }),
      choice({
        id: 'decliner',
        label: 'Décliner par pudeur',
        stance: 'prudent',
        riskPreview: 'Légèreté gardée, fans blessés.',
        immediate: [fx.res('bienEtre', 3), fx.rel('fans', -5)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_fans_ultimatum',
    title: 'Les ultras posent leurs conditions',
    body: 'Après une série ratée, les ultras te convoquent et exigent des résultats sous peine de rendre ta vie impossible. Aller les affronter en face impose le respect mais peut dégénérer. Les éviter soigneusement préserve ta tranquillité et laisse enfler une défiance qui s’abattra au premier faux pas.',
    category: 'fans',
    tags: ['supporters', 'ultras', 'pression'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 20,
    ageMax: 38,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'affronter',
        label: 'Aller les affronter en face',
        stance: 'resilient',
        riskPreview: 'Respect imposé, échange qui peut déraper.',
        immediate: [fx.rel('fans', 6), fx.res('bienEtre', -4)],
        hidden: [fx.hidden('resistancePression', 3)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('moral', -5)])])],
      }),
      choice({
        id: 'eviter',
        label: 'Les éviter soigneusement',
        stance: 'prudent',
        riskPreview: 'Tranquillité gardée, défiance qui enfle.',
        immediate: [fx.res('bienEtre', 2), fx.rel('fans', -6)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_fans_autographe_camera',
    title: 'Ton refus d’autographe filmé',
    body: 'Pressé et à cran, tu refuses un autographe à un gamin, et une caméra capte tout. Rattraper le coup en retrouvant l’enfant pour un vrai moment répare l’image, au prix de ton temps et de ta fatigue. Laisser passer mise sur l’oubli et laisse la séquence coller à ta réputation.',
    category: 'fans',
    tags: ['supporters', 'image', 'reseaux'],
    rarity: 'common',
    weight: 5,
    ageMin: 18,
    ageMax: 37,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'rattraper',
        label: 'Retrouver l’enfant et réparer',
        stance: 'ethical',
        riskPreview: 'Image réparée, temps et énergie dépensés.',
        immediate: [fx.rel('fans', 7), fx.res('fatigue', 3)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
      choice({
        id: 'laisser',
        label: 'Miser sur l’oubli',
        stance: 'prudent',
        riskPreview: 'Énergie gardée, séquence qui colle.',
        immediate: [fx.res('bienEtre', 2), fx.res('popularite', -4)],
        hidden: [fx.hidden('constance', 1)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.rel('fans', -4)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_media_pause_reseaux',
    title: 'Quitter les réseaux après le lynchage',
    body: 'Un déferlement de haine en ligne t’assaille après une contre-performance. Couper les réseaux protège ton mental mais te coupe aussi de tes fans et de tes contrats d’image. Rester connecté et répondre entretient le lien commercial et t’expose chaque jour à un flot que peu de têtes encaissent.',
    category: 'media',
    tags: ['medias', 'reseaux', 'mental'],
    rarity: 'common',
    weight: 5,
    ageMin: 18,
    ageMax: 36,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'couper',
        label: 'Couper les réseaux',
        stance: 'professional',
        riskPreview: 'Mental protégé, lien commercial coupé.',
        immediate: [fx.res('bienEtre', 6), fx.res('popularite', -4)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
      choice({
        id: 'rester',
        label: 'Rester connecté et répondre',
        stance: 'media_savvy',
        riskPreview: 'Lien gardé, flot de haine quotidien.',
        immediate: [fx.res('popularite', 3), fx.res('bienEtre', -5)],
        hidden: [fx.hidden('resistancePression', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('moral', -6)])])],
      }),
    ],
  }),
]
