import { dilemma, choice, fx } from '../helpers'
import type { DilemmaDefinition } from '../../../game-engine/dilemmas'

/**
 * Phase 8 — Événements originaux (données, algorithmes, image numérique).
 * Situations rares et modernes, sans équivalent dans les lots existants.
 */
export const originauxDilemmas: DilemmaDefinition[] = [
  dilemma({
    id: 'p8_orig_algorithme',
    title: 'L’algorithme te classe mal',
    body: 'Le modèle statistique du club te note sous ta vraie valeur ressentie et guide désormais les choix du staff. Te plier à ses préconisations rassure les dirigeants friands de données, au prix de ton instinct. Jouer contre le modèle défend ton football et te met en porte-à-faux avec toute une direction convertie aux chiffres.',
    category: 'training',
    tags: ['donnees', 'algorithme', 'staff'],
    rarity: 'rare',
    weight: 4,
    ageMin: 19,
    ageMax: 37,
    cooldownSeasons: 6,
    choices: [
      choice({
        id: 'plier',
        label: 'Te plier au modèle',
        stance: 'prudent',
        riskPreview: 'Dirigeants rassurés, instinct bridé.',
        immediate: [fx.res('confianceEntraineur', 5), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('adaptabilite', 2)],
      }),
      choice({
        id: 'instinct',
        label: 'Jouer contre les chiffres',
        stance: 'individualist',
        riskPreview: 'Football défendu, direction contrariée.',
        immediate: [fx.res('reputationSportive', 3), fx.rel('coach', -5)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('confianceEntraineur', 5)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_orig_ia_vente',
    title: 'L’IA recommande ta vente',
    body: 'Le logiciel de recrutement du club te désigne comme l’actif à vendre pour équilibrer les comptes. Accepter le principe d’un départ te laisse choisir ta sortie plutôt que la subir. Batailler pour rester défie une machine que la direction croit infaillible et t’expose à une saison de placard programmée.',
    category: 'transfer',
    tags: ['donnees', 'ia', 'transfert'],
    rarity: 'rare',
    weight: 4,
    ageMin: 21,
    ageMax: 34,
    cooldownSeasons: 6,
    choices: [
      choice({
        id: 'partir',
        label: 'Choisir ta sortie',
        stance: 'ambitious',
        riskPreview: 'Départ maîtrisé, repères et vestiaire perdus.',
        immediate: [fx.flag('transfer_accepted'), fx.res('reputationSportive', 2), fx.res('cohesionVestiaire', -3)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('reputationSportive', 4)])])],
      }),
      choice({
        id: 'rester',
        label: 'Batailler pour rester',
        stance: 'resilient',
        riskPreview: 'Machine défiée, saison de placard possible.',
        immediate: [fx.res('reputationSportive', 3), fx.res('confianceEntraineur', -4)],
        hidden: [fx.hidden('resistancePression', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_orig_gps_public',
    title: 'Tes données de course exposées',
    body: 'Le club publie tes distances parcourues, et les tribunes te jugent moins courageux que tes chiffres bruts. Répondre en te tuant à courir fait taire la critique mais épuise tes réserves. Expliquer que tout ne se mesure pas en kilomètres défend ton intelligence de jeu et laisse une frange du public convaincue de ta paresse.',
    category: 'media',
    tags: ['donnees', 'supporters', 'effort'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 19,
    ageMax: 37,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'courir',
        label: 'Te tuer à la course',
        stance: 'resilient',
        riskPreview: 'Critique éteinte, réserves épuisées.',
        immediate: [fx.rel('fans', 5), fx.res('fatigue', 6)],
        hidden: [fx.hidden('resistancePression', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('forme', -6)])])],
      }),
      choice({
        id: 'expliquer',
        label: 'Défendre ton intelligence de jeu',
        stance: 'professional',
        riskPreview: 'Jeu défendu, frange convaincue de ta paresse.',
        immediate: [fx.stat('tactique', 2), fx.rel('fans', -4)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_orig_documentaire_star',
    title: 'Une série mondiale sur toi',
    body: 'Une plateforme veut faire de ta vie le cœur d’une série documentaire diffusée partout. T’ouvrir en grand promet une notoriété planétaire et une manne, au prix de ton intimité livrée au monde. Refuser garde ta vie à l’abri et laisse passer une vitrine que peu de joueurs se voient offrir.',
    category: 'media',
    tags: ['medias', 'documentaire', 'image'],
    rarity: 'legendary',
    weight: 3,
    ageMin: 23,
    ageMax: 37,
    cooldownSeasons: 8,
    choices: [
      choice({
        id: 'ouvrir',
        label: 'Ouvrir ta vie à la série',
        stance: 'media_savvy',
        riskPreview: 'Notoriété planétaire, intimité livrée.',
        immediate: [fx.res('popularite', 10), fx.res('bienEtre', -6)],
        hidden: [fx.hidden('ambition', 3)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('reputationSportive', -5)])])],
      }),
      choice({
        id: 'refuser',
        label: 'Protéger ta vie privée',
        stance: 'prudent',
        riskPreview: 'Intimité gardée, vitrine mondiale manquée.',
        immediate: [fx.res('bienEtre', 5), fx.res('popularite', -4)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_orig_jeu_video_note',
    title: 'Ta note dans le jeu fait polémique',
    body: 'Le jeu vidéo phare te sous-note d’un cran et la toile s’enflamme. Monter au créneau publiquement amuse tes fans et te rend sympathique, mais t’enferme dans une querelle futile. Prendre de la hauteur préserve ton sérieux et laisse s’installer une note que des millions de joueurs prendront pour argent comptant.',
    category: 'media',
    tags: ['medias', 'jeu_video', 'image'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 18,
    ageMax: 34,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'creneau',
        label: 'Monter au créneau',
        stance: 'media_savvy',
        riskPreview: 'Fans amusés, querelle futile assumée.',
        immediate: [fx.res('popularite', 5), fx.res('reputationSportive', -2)],
        hidden: [fx.hidden('ambition', 1)],
      }),
      choice({
        id: 'hauteur',
        label: 'Prendre de la hauteur',
        stance: 'professional',
        riskPreview: 'Sérieux gardé, note gravée pour des millions.',
        immediate: [fx.res('reputationSportive', 2), fx.res('popularite', -3)],
        hidden: [fx.hidden('professionnalisme', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('popularite', 4)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_orig_capteur_contrat',
    title: 'Un contrat piloté par tes capteurs',
    body: 'Le club propose des primes indexées sur tes données GPS : distance, sprints, intensité mesurés à chaque match. Signer promet des gains si tu cours, au risque de te pousser à la surchauffe pour gonfler des chiffres. Refuser garde ta liberté de gestion et te prive d’un complément de revenu bien réel.',
    category: 'contract',
    tags: ['donnees', 'contrat', 'primes'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 20,
    ageMax: 35,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'signer',
        label: 'Signer les primes aux données',
        stance: 'financial',
        riskPreview: 'Gains si tu cours, surchauffe qui guette.',
        immediate: [fx.cash(10000), fx.res('fatigue', 4)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('sante', -6)])])],
      }),
      choice({
        id: 'refuser',
        label: 'Refuser l’indexation',
        stance: 'prudent',
        riskPreview: 'Liberté gardée, revenu complémentaire perdu.',
        immediate: [fx.res('bienEtre', 3), fx.res('financesPersonnelles', -2)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),
]
