import { dilemma, choice, fx } from '../helpers'
import type { DilemmaDefinition } from '../../../game-engine/dilemmas'

/**
 * Phase 8 — Performance & terrain (spécificités par poste).
 * Situations neuves, distinctes du lot Phase 5. Emplacement 1 (sportif).
 */
export const perfDilemmas: DilemmaDefinition[] = [
  // ---------------- Gardien ----------------
  dilemma({
    id: 'p8_gk_relance_risquee',
    title: 'Relancer au pied sous le pressing',
    body: 'Le coach veut une relance courte pour construire de derrière. Deux attaquants te sautent dessus dès que tu prends le ballon. Jouer proprement séduit le staff mais un contre-pied coûterait un but ; dégager loin te met à l’abri, moins ton entraîneur.',
    category: 'match',
    tags: ['gardien', 'relance', 'pressing'],
    rarity: 'common',
    weight: 9,
    ageMin: 17,
    ageMax: 38,
    positions: ['gk'],
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'construire',
        label: 'Jouer court et construire',
        stance: 'ambitious',
        riskPreview: 'Coach séduit, perte de balle dangereuse possible.',
        immediate: [fx.res('confianceEntraineur', 5), fx.res('fatigue', 4)],
        hidden: [fx.hidden('adaptabilite', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('confianceEntraineur', -6)])])],
      }),
      choice({
        id: 'degager',
        label: 'Dégager long, assurer',
        stance: 'prudent',
        riskPreview: 'Sécurité immédiate, projet de jeu ignoré.',
        immediate: [fx.res('bienEtre', 3), fx.res('confianceEntraineur', -4)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_gk_banc_prolonge',
    title: 'Des mois entiers sur le banc',
    body: 'Le titulaire enchaîne les clean sheets et tu n’as plus joué depuis l’automne. Ronger ton frein en pro modèle nourrit ton mental mais grille ta saison ; réclamer un départ hivernal relance ta carrière, au risque de tout casser avec le club.',
    category: 'match',
    tags: ['gardien', 'temps_de_jeu', 'banc'],
    rarity: 'uncommon',
    weight: 7,
    ageMin: 19,
    ageMax: 35,
    positions: ['gk'],
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'attendre',
        label: 'Rester pro et attendre ta chance',
        stance: 'professional',
        riskPreview: 'Respect du staff, saison peut-être blanche.',
        immediate: [fx.res('confianceEntraineur', 6), fx.res('moral', -5)],
        hidden: [fx.hidden('professionnalisme', 3)],
      }),
      choice({
        id: 'partir',
        label: 'Réclamer un départ en prêt',
        stance: 'ambitious',
        riskPreview: 'Temps de jeu visé, relation club fragilisée.',
        immediate: [fx.res('moral', 4), fx.rel('coach', -8)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('reputationSportive', 4)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_gk_sortie_aerienne',
    title: 'Aller chercher dans les airs',
    body: 'Corner adverse, pluie battante, six-mètres bondé. Sortir au poing peut dégager le danger comme finir en boulette au ralenti. Rester sur ta ligne rassure mais laisse un attaquant seul face au deuxième poteau. Le stade retient son souffle.',
    category: 'match',
    tags: ['gardien', 'sortie', 'aerien'],
    rarity: 'common',
    weight: 8,
    ageMin: 17,
    ageMax: 38,
    positions: ['gk'],
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'sortir',
        label: 'Sortir dans la mêlée',
        stance: 'high_risk',
        riskPreview: 'Danger écarté, boulette filmée possible.',
        immediate: [fx.res('reputationSportive', 4), fx.res('sante', -3)],
        hidden: [fx.hidden('grandsMatchs', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('reputationSportive', -6)])])],
      }),
      choice({
        id: 'ligne',
        label: 'Tenir ta ligne',
        stance: 'prudent',
        riskPreview: 'Position sûre, attaquant laissé libre.',
        immediate: [fx.res('bienEtre', 2), fx.res('confianceEntraineur', -3)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_gk_erreur_apres_match',
    title: 'Ta boulette tourne en boucle',
    body: 'Ta relance ratée a offert la défaite et la vidéo tourne partout. En conférence, endosser la faute apaise le vestiaire mais te colle une étiquette ; pointer un coéquipier mal placé te dédouane et fissure le groupe. Le micro attend.',
    category: 'match',
    tags: ['gardien', 'erreur', 'medias'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 18,
    ageMax: 38,
    positions: ['gk'],
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'assumer',
        label: 'Assumer publiquement la faute',
        stance: 'ethical',
        riskPreview: 'Vestiaire soudé, étiquette qui colle.',
        immediate: [fx.rel('teammates', 8), fx.res('reputationSportive', -4)],
        hidden: [fx.hidden('professionnalisme', 3)],
      }),
      choice({
        id: 'devier',
        label: 'Renvoyer sur le placement',
        stance: 'individualist',
        riskPreview: 'Image sauvée, vestiaire refroidi.',
        immediate: [fx.res('reputationSportive', 2), fx.rel('teammates', -8)],
        hidden: [fx.hidden('loyaute', -2)],
      }),
    ],
  }),

  // ---------------- Défenseur ----------------
  dilemma({
    id: 'p8_def_duel_physique',
    title: 'Le 50/50 qui fait mal',
    body: 'Un ballon en cloche, l’attaquant lancé, personne pour couvrir. Y aller franc dégage le danger mais peut t’envoyer au tapis ou concéder la faute ; temporiser garde ton intégrité et t’expose à te faire déborder. Ton corps décidera vite.',
    category: 'match',
    tags: ['defense', 'duel'],
    rarity: 'common',
    weight: 9,
    ageMin: 17,
    ageMax: 38,
    positions: ['cb', 'fb'],
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'franc',
        label: 'Y aller franchement',
        stance: 'high_risk',
        riskPreview: 'Danger coupé, choc ou faute possible.',
        immediate: [fx.res('reputationSportive', 4), fx.res('sante', -4)],
        hidden: [fx.hidden('resistancePression', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.25, [fx.res('sante', -8)])])],
      }),
      choice({
        id: 'temporiser',
        label: 'Temporiser et contenir',
        stance: 'prudent',
        riskPreview: 'Corps préservé, débordement possible.',
        immediate: [fx.res('bienEtre', 2), fx.res('confianceEntraineur', -3)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_def_ligne_hors_jeu',
    title: 'Monter la ligne au bon moment',
    body: 'Leur buteur vit sur la profondeur. Jouer le hors-jeu haut l’annule s’il part trop tôt, mais un décalage et il file seul au but. Décrocher bas ferme la profondeur et invite l’adversaire à camper dans ton camp toute la mi-temps.',
    category: 'match',
    tags: ['defense', 'placement', 'ligne'],
    rarity: 'common',
    weight: 8,
    ageMin: 18,
    ageMax: 38,
    positions: ['cb'],
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'monter',
        label: 'Jouer la ligne haute',
        stance: 'ambitious',
        riskPreview: 'Adversaire neutralisé, un décalage et c’est but.',
        immediate: [fx.stat('placement', 2), fx.res('fatigue', 3)],
        hidden: [fx.hidden('grandsMatchs', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('confianceEntraineur', -5)])])],
      }),
      choice({
        id: 'decrocher',
        label: 'Décrocher et fermer',
        stance: 'prudent',
        riskPreview: 'Profondeur fermée, pression subie longtemps.',
        immediate: [fx.res('bienEtre', 2), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_def_leadership_ligne',
    title: 'Une défense qui part en vrille',
    body: 'Tes partenaires de charnière se cherchent, les couvertures sautent. Prendre la parole et tout organiser peut stabiliser le bloc ou froisser un ancien qui n’aime pas les ordres. Rester concentré sur ton périmètre te protège, mais la ligne continue de sombrer.',
    category: 'match',
    tags: ['defense', 'leadership'],
    rarity: 'uncommon',
    weight: 7,
    ageMin: 20,
    ageMax: 38,
    positions: ['cb', 'fb'],
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'organiser',
        label: 'Prendre la ligne en main',
        stance: 'collective',
        riskPreview: 'Bloc stabilisé, ancien vexé possible.',
        immediate: [fx.stat('leadership', 2), fx.rel('teammates', -4)],
        hidden: [fx.hidden('loyaute', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('confianceEntraineur', 5)])])],
      }),
      choice({
        id: 'perimetre',
        label: 'Assurer ton seul secteur',
        stance: 'individualist',
        riskPreview: 'Toi solide, la ligne coule quand même.',
        immediate: [fx.stat('placement', 2), fx.res('cohesionVestiaire', -4)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_def_relance_longue',
    title: 'La diagonale qui casse les lignes',
    body: 'Tu lèves la tête : l’ailier appelle dans le dos du latéral, quarante mètres plus loin. Tenter la diagonale peut lancer une action de but ou offrir une contre-attaque si tu la manques. Jouer simple à côté ne prend aucun risque et endort le match.',
    category: 'match',
    tags: ['defense', 'relance', 'passe'],
    rarity: 'common',
    weight: 8,
    ageMin: 18,
    ageMax: 38,
    positions: ['cb', 'fb'],
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'diagonale',
        label: 'Tenter la diagonale',
        stance: 'ambitious',
        riskPreview: 'Action lancée, contre possible si ratée.',
        immediate: [fx.stat('passe', 2), fx.res('fatigue', 2)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('confianceEntraineur', -4)])])],
      }),
      choice({
        id: 'simple',
        label: 'Jouer simple à côté',
        stance: 'prudent',
        riskPreview: 'Zéro risque, jeu qui ronronne.',
        immediate: [fx.stat('controle', 1), fx.res('reputationSportive', -2)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  // ---------------- Milieu ----------------
  dilemma({
    id: 'p8_mid_gestion_rythme',
    title: 'Accélérer ou endormir le match',
    body: 'Vous menez d’un but, il reste vingt minutes. Baisser le rythme et garder le ballon use l’adversaire mais invite la critique des tribunes qui veulent du spectacle. Relancer les offensives peut tuer le match ou t’exposer à un contre fatal si tu perds le fil.',
    category: 'match',
    tags: ['milieu', 'rythme', 'gestion'],
    rarity: 'common',
    weight: 9,
    ageMin: 18,
    ageMax: 38,
    positions: ['cdm', 'cm', 'cam'],
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'temporiser',
        label: 'Casser le rythme et gérer',
        stance: 'prudent',
        riskPreview: 'Adversaire usé, tribunes qui sifflent.',
        immediate: [fx.stat('tactique', 2), fx.rel('fans', -4)],
        hidden: [fx.hidden('constance', 2)],
      }),
      choice({
        id: 'accelerer',
        label: 'Relancer les attaques',
        stance: 'ambitious',
        riskPreview: 'Match à tuer, contre fatal possible.',
        immediate: [fx.res('reputationSportive', 3), fx.res('fatigue', 5)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('confianceEntraineur', -5)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_mid_passe_risquee',
    title: 'La passe qui tue ou qui trahit',
    body: 'Une ouverture s’ouvre entre trois défenseurs vers ton attaquant lancé. La tenter peut créer le but du soir ou finir en perte sèche relayée en boucle. Choisir la sécurité latérale conserve le ballon mais laisse filer l’occasion la plus tranchante du match.',
    category: 'match',
    tags: ['milieu', 'passe', 'risque'],
    rarity: 'common',
    weight: 9,
    ageMin: 18,
    ageMax: 38,
    positions: ['cm', 'cam'],
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'tenter',
        label: 'Tenter la passe décisive',
        stance: 'ambitious',
        riskPreview: 'But possible, perte sèche exposée.',
        immediate: [fx.stat('vision', 2), fx.res('fatigue', 2)],
        hidden: [fx.hidden('grandsMatchs', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.35, [fx.res('reputationSportive', 5)])])],
      }),
      choice({
        id: 'securite',
        label: 'Assurer sur le côté',
        stance: 'prudent',
        riskPreview: 'Ballon gardé, occasion évaporée.',
        immediate: [fx.stat('controle', 1), fx.res('reputationSportive', -2)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_mid_fatigue_pressing',
    title: 'Presser jusqu’à la rupture',
    body: 'Le plan demande un pressing tout-terrain, mais tes cuisses hurlent depuis la 60e. Continuer à courir asphyxie l’adversaire et plaît au coach, au prix d’un risque de claquage. Économiser tes jambes te protège et ouvre des espaces que l’équipe paiera cash.',
    category: 'match',
    tags: ['milieu', 'fatigue', 'pressing'],
    rarity: 'common',
    weight: 8,
    ageMin: 18,
    ageMax: 36,
    positions: ['cdm', 'cm'],
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'presser',
        label: 'Presser jusqu’au bout',
        stance: 'resilient',
        riskPreview: 'Coach ravi, claquage qui guette.',
        immediate: [fx.res('confianceEntraineur', 5), fx.res('fatigue', 8)],
        hidden: [fx.hidden('resistancePression', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.25, [fx.res('sante', -8)])])],
      }),
      choice({
        id: 'economiser',
        label: 'Gérer tes efforts',
        stance: 'prudent',
        riskPreview: 'Jambes sauvées, espaces offerts.',
        immediate: [fx.res('bienEtre', 3), fx.res('confianceEntraineur', -4)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_mid_leadership_jeune',
    title: 'Un débutant tétanisé à tes côtés',
    body: 'Le gamin lancé dans le grand bain tremble et perd chaque ballon. Le couvrir en permanence le rassure mais double ta charge et grignote ton propre match. Le laisser affronter la tempête l’endurcit ou l’enfonce, et le coach t’en tiendra responsable.',
    category: 'match',
    tags: ['milieu', 'leadership', 'jeune'],
    rarity: 'uncommon',
    weight: 7,
    ageMin: 22,
    ageMax: 38,
    positions: ['cdm', 'cm'],
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'couvrir',
        label: 'Le couvrir sans relâche',
        stance: 'collective',
        riskPreview: 'Gamin rassuré, ton match sacrifié.',
        immediate: [fx.stat('leadership', 2), fx.res('fatigue', 5)],
        hidden: [fx.hidden('loyaute', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.rel('teammates', 6)])])],
      }),
      choice({
        id: 'laisser',
        label: 'Le laisser affronter seul',
        stance: 'individualist',
        riskPreview: 'Ton jeu préservé, gamin exposé.',
        immediate: [fx.res('reputationSportive', 2), fx.res('cohesionVestiaire', -4)],
        hidden: [fx.hidden('ambition', 2)],
      }),
    ],
  }),

  // ---------------- Attaquant ----------------
  dilemma({
    id: 'p8_att_penalty_pression',
    title: 'Le penalty après ton raté',
    body: 'Tu as manqué le dernier, et voilà un nouveau penalty crucial. Reprendre le ballon peut exorciser ta peur ou t’enfoncer un peu plus si tu trembles encore. Le laisser à un partenaire calme protège l’équipe mais avoue ton doute devant tout un stade.',
    category: 'match',
    tags: ['attaquant', 'penalty', 'pression'],
    rarity: 'uncommon',
    weight: 8,
    ageMin: 18,
    ageMax: 38,
    positions: ['winger', 'st'],
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'tirer',
        label: 'Reprendre le ballon',
        stance: 'resilient',
        riskPreview: 'Rédemption possible, nouveau raté dévastateur.',
        immediate: [fx.stat('sangFroid', 2), fx.res('fatigue', 2)],
        hidden: [fx.hidden('resistancePression', 3)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('moral', -8)])])],
      }),
      choice({
        id: 'ceder',
        label: 'Laisser tirer un partenaire',
        stance: 'collective',
        riskPreview: 'Équipe protégée, doute affiché.',
        immediate: [fx.rel('teammates', 5), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('resistancePression', -2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_att_record_repos',
    title: 'Un record à portée, un corps à ménager',
    body: 'Il te manque deux buts pour ton record personnel, mais les barrages arrivent et le staff veut te faire souffler. Forcer pour la ligne d’histoire flatte ton ego au risque de finir sur les rotules. Te reposer préserve l’équipe et laisse filer une marque symbolique.',
    category: 'match',
    tags: ['attaquant', 'record', 'gestion'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 20,
    ageMax: 36,
    positions: ['st'],
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'forcer',
        label: 'Aller chercher le record',
        stance: 'individualist',
        riskPreview: 'Marque en vue, réserves épuisées.',
        immediate: [fx.res('reputationSportive', 5), fx.res('fatigue', 7)],
        hidden: [fx.hidden('ambition', 3)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('forme', -8)])])],
      }),
      choice({
        id: 'souffler',
        label: 'Souffler pour les barrages',
        stance: 'professional',
        riskPreview: 'Fraîcheur gardée, record laissé filer.',
        immediate: [fx.res('forme', 5), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_att_faux_neuf',
    title: 'Décrocher au lieu de fixer',
    body: 'Le coach te demande de jouer faux-neuf : décrocher, créer, oublier tes stats de buteur. Le rôle libère l’équipe et prouve ta polyvalence, mais fond ta réputation de finisseur. Refuser et rester à la pointe garde ton identité et cadenasse une animation qui tourne à vide.',
    category: 'match',
    tags: ['attaquant', 'role', 'collectif'],
    rarity: 'uncommon',
    weight: 7,
    ageMin: 19,
    ageMax: 36,
    positions: ['st', 'winger'],
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'accepter',
        label: 'Endosser le faux-neuf',
        stance: 'collective',
        riskPreview: 'Équipe fluidifiée, stats de buteur diluées.',
        immediate: [fx.stat('vision', 2), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('adaptabilite', 3)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('confianceEntraineur', 5)])])],
      }),
      choice({
        id: 'refuser',
        label: 'Rester à la pointe',
        stance: 'individualist',
        riskPreview: 'Identité gardée, animation qui coince.',
        immediate: [fx.stat('finition', 1), fx.rel('coach', -6)],
        hidden: [fx.hidden('ambition', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_att_celebration',
    title: 'La célébration qui divise',
    body: 'Tu brises enfin ta disette d’un but au bout du temps additionnel. Une célébration provocante devant le parcage adverse enflamme tes fans et t’expose au carton et aux représailles. La jouer sobre calme tout le monde mais laisse s’évaporer un moment de pure catharsis.',
    category: 'match',
    tags: ['attaquant', 'celebration', 'medias'],
    rarity: 'common',
    weight: 7,
    ageMin: 18,
    ageMax: 34,
    positions: ['winger', 'st'],
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'provoquer',
        label: 'Célébrer avec provocation',
        stance: 'high_risk',
        riskPreview: 'Fans conquis, carton et retour de bâton.',
        immediate: [fx.rel('fans', 8), fx.res('discipline', -5)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('reputationSportive', -5)])])],
      }),
      choice({
        id: 'sobre',
        label: 'Rester sobre et digne',
        stance: 'professional',
        riskPreview: 'Image lisse, moment sans relief.',
        immediate: [fx.res('discipline', 3), fx.rel('fans', -3)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  // ---------------- Terrain (tous postes) ----------------
  dilemma({
    id: 'p8_perf_temps_additionnel',
    title: 'Cinq minutes pour tout changer',
    body: 'Score nul, cinq minutes de plus, et un choix collectif : tout envoyer pour arracher la victoire ou verrouiller le point acquis. Attaquer peut faire basculer la saison ou offrir le contre qui vous condamne. Sécuriser rassure, mais laisse un goût d’occasion manquée.',
    category: 'match',
    tags: ['collectif', 'gestion', 'fin_de_match'],
    rarity: 'common',
    weight: 9,
    ageMin: 17,
    ageMax: 38,
    cooldownSeasons: 3,
    choices: [
      choice({
        id: 'attaquer',
        label: 'Tout tenter pour gagner',
        stance: 'ambitious',
        riskPreview: 'Victoire possible, contre fatal en embuscade.',
        immediate: [fx.res('reputationSportive', 4), fx.res('fatigue', 5)],
        hidden: [fx.hidden('grandsMatchs', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('moral', -6)])])],
      }),
      choice({
        id: 'securiser',
        label: 'Assurer le point',
        stance: 'prudent',
        riskPreview: 'Point pris, regret d’avoir spéculé.',
        immediate: [fx.stat('tactique', 1), fx.rel('fans', -3)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_perf_carton_gestion',
    title: 'Averti, jouer avec le feu',
    body: 'Un jaune en poche dès la demi-heure, et l’adversaire te cherche exprès. Rester agressif garde ton impact mais un second carton te sort et handicape l’équipe. Lever le pied t’éloigne du rouge et te transforme en passager, cible facile pour leurs attaques.',
    category: 'match',
    tags: ['discipline', 'gestion'],
    rarity: 'common',
    weight: 8,
    ageMin: 17,
    ageMax: 38,
    cooldownSeasons: 3,
    choices: [
      choice({
        id: 'agressif',
        label: 'Rester dans l’impact',
        stance: 'high_risk',
        riskPreview: 'Impact gardé, expulsion possible.',
        immediate: [fx.res('reputationSportive', 3), fx.res('discipline', -4)],
        hidden: [fx.hidden('resistancePression', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('confianceEntraineur', -6)])])],
      }),
      choice({
        id: 'assagir',
        label: 'Lever le pied prudemment',
        stance: 'prudent',
        riskPreview: 'Rouge évité, présence diluée.',
        immediate: [fx.res('discipline', 4), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),
]
