import { dilemma, choice, fx } from '../helpers'
import type { DilemmaDefinition } from '../../../game-engine/dilemmas'

/**
 * Phase 8 — Sélection nationale. Situations neuves, distinctes du lot Phase 5/7.
 * Emplacement 2 (carrière).
 */
export const selectionDilemmas: DilemmaDefinition[] = [
  dilemma({
    id: 'p8_nat_forfait_amical',
    title: 'Club ou pays pour un amical',
    body: 'Ton club te presse de déclarer forfait pour un match amical sans enjeu et de rester te reposer. Répondre à l’appel national honore le maillot et t’use avant une échéance de club. Déclarer forfait ménage ton corps et te fait passer pour un déserteur aux yeux du sélectionneur.',
    category: 'national_team',
    tags: ['selection', 'club', 'gestion'],
    rarity: 'common',
    weight: 7,
    ageMin: 19,
    ageMax: 35,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'repondre',
        label: 'Répondre à l’appel national',
        stance: 'loyal',
        riskPreview: 'Maillot honoré, usure avant le club.',
        immediate: [fx.res('reputationSportive', 4), fx.res('fatigue', 6)],
        hidden: [fx.hidden('loyaute', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('confianceEntraineur', -5)])])],
      }),
      choice({
        id: 'forfait',
        label: 'Déclarer forfait pour souffler',
        stance: 'professional',
        riskPreview: 'Corps ménagé, image de déserteur.',
        immediate: [fx.res('forme', 4), fx.res('reputationSportive', -4)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_nat_capitanat',
    title: 'Le brassard de la nation',
    body: 'Le sélectionneur t’offre le capitanat national avant une campagne majeure. L’accepter grave ton nom mais te met sous une pression et une exposition immenses. Le refuser par humilité préserve ta sérénité et fait douter d’une ambition que les grands leaders n’hésitent jamais à afficher.',
    category: 'national_team',
    tags: ['selection', 'capitanat', 'statut'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 24,
    ageMax: 36,
    cooldownSeasons: 6,
    choices: [
      choice({
        id: 'accepter',
        label: 'Prendre le brassard national',
        stance: 'ambitious',
        riskPreview: 'Nom gravé, exposition immense.',
        immediate: [fx.stat('leadership', 2), fx.res('bienEtre', -4)],
        hidden: [fx.hidden('ambition', 3)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('reputationSportive', 6)])])],
      }),
      choice({
        id: 'refuser',
        label: 'Refuser par humilité',
        stance: 'prudent',
        riskPreview: 'Sérénité gardée, ambition mise en doute.',
        immediate: [fx.res('bienEtre', 3), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_nat_naturalisation',
    title: 'Une grande nation te courtise',
    body: 'Une sélection prestigieuse te propose une naturalisation express et un rôle de titulaire. Changer de maillot t’ouvre les grands tournois mais te coupe de tes racines et de ton public d’origine. Rester fidèle à ta nation modeste honore tes couleurs et t’enferme peut-être loin de la lumière.',
    category: 'national_team',
    tags: ['selection', 'naturalisation', 'identite'],
    rarity: 'rare',
    weight: 4,
    ageMin: 20,
    ageMax: 30,
    cooldownSeasons: 6,
    choices: [
      choice({
        id: 'changer',
        label: 'Accepter la naturalisation',
        stance: 'ambitious',
        riskPreview: 'Grands tournois ouverts, racines coupées.',
        immediate: [fx.res('reputationSportive', 5), fx.rel('fans', -6)],
        hidden: [fx.hidden('ambition', 3)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('moral', -6)])])],
      }),
      choice({
        id: 'fidele',
        label: 'Rester fidèle à tes couleurs',
        stance: 'loyal',
        riskPreview: 'Racines honorées, lumière peut-être manquée.',
        immediate: [fx.rel('fans', 6), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('loyaute', 3)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_nat_selectionneur_conflit',
    title: 'En désaccord avec le sélectionneur',
    body: 'Le sélectionneur t’enferme dans un plan de jeu que tu juges suicidaire. Exécuter sans broncher préserve ta place en sélection et étouffe ton instinct. Défendre ta vision en réunion peut faire évoluer le plan comme te renvoyer en club, rayé de la liste pour insubordination.',
    category: 'national_team',
    tags: ['selection', 'coach', 'conflit'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 21,
    ageMax: 36,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'executer',
        label: 'Exécuter sans broncher',
        stance: 'prudent',
        riskPreview: 'Place gardée, instinct étouffé.',
        immediate: [fx.res('reputationSportive', 2), fx.res('moral', -3)],
        hidden: [fx.hidden('constance', 2)],
      }),
      choice({
        id: 'defendre',
        label: 'Défendre ta vision',
        stance: 'high_risk',
        riskPreview: 'Plan peut-être infléchi, liste peut-être perdue.',
        immediate: [fx.stat('tactique', 2), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('resistancePression', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.35, [fx.res('reputationSportive', 4)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_nat_risque_tournoi',
    title: 'Diminué à l’aube du grand tournoi',
    body: 'Une gêne persistante te fragilise juste avant le tournoi continental que tu attends depuis toujours. Forcer pour y être réalise un rêve et joue ta santé sur une jambe incertaine. Déclarer forfait protège ton corps et laisse filer la scène dont chaque enfant du pays a rêvé.',
    category: 'national_team',
    tags: ['selection', 'sante', 'tournoi'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 21,
    ageMax: 36,
    cooldownSeasons: 6,
    choices: [
      choice({
        id: 'forcer',
        label: 'Forcer pour le tournoi',
        stance: 'resilient',
        riskPreview: 'Rêve réalisé, santé jouée.',
        immediate: [fx.res('reputationSportive', 5), fx.res('sante', -5)],
        hidden: [fx.hidden('grandsMatchs', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('sante', -10)])])],
      }),
      choice({
        id: 'forfait',
        label: 'Renoncer pour te protéger',
        stance: 'professional',
        riskPreview: 'Corps protégé, scène de rêve manquée.',
        immediate: [fx.res('sante', 5), fx.res('moral', -5)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_nat_snub_reaction',
    title: 'Ton nom absent de la liste',
    body: 'Malgré une belle saison, le sélectionneur t’écarte sans explication. Sortir du silence dans la presse défend ta cause mais peut te griller définitivement. Ravaler ta colère et travailler en silence garde la porte entrouverte et laisse penser que tu acceptes l’injustice sans réagir.',
    category: 'national_team',
    tags: ['selection', 'snub', 'medias'],
    rarity: 'common',
    weight: 6,
    ageMin: 20,
    ageMax: 35,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'parler',
        label: 'Sortir du silence publiquement',
        stance: 'high_risk',
        riskPreview: 'Cause défendue, grillage définitif possible.',
        immediate: [fx.res('reputationSportive', 3), fx.res('bienEtre', -3)],
        hidden: [fx.hidden('resistancePression', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('reputationSportive', -5)])])],
      }),
      choice({
        id: 'travailler',
        label: 'Travailler en silence',
        stance: 'professional',
        riskPreview: 'Porte entrouverte, injustice semblant acceptée.',
        immediate: [fx.res('discipline', 4), fx.res('moral', -4)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_nat_jeune_mentor',
    title: 'Former celui qui vise ta place',
    body: 'En sélection, un jeune surdoué débarque à ton poste et te demande conseil. Le former en grand frère grandit le groupe et ton image, tout en armant ton propre remplaçant. Le tenir à distance protège ta place et te dessine en cadre égoïste que le vestiaire jugera vite.',
    category: 'national_team',
    tags: ['selection', 'jeune', 'transmission'],
    rarity: 'common',
    weight: 5,
    ageMin: 26,
    ageMax: 37,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'former',
        label: 'Le former en grand frère',
        stance: 'collective',
        riskPreview: 'Image grandie, remplaçant armé.',
        immediate: [fx.rel('teammates', 5), fx.res('reputationSportive', -2)],
        hidden: [fx.hidden('professionnalisme', 3)],
      }),
      choice({
        id: 'distance',
        label: 'Le tenir à distance',
        stance: 'individualist',
        riskPreview: 'Place gardée, image d’égoïste.',
        immediate: [fx.res('reputationSportive', 2), fx.rel('teammates', -5)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('cohesionVestiaire', -4)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_nat_geste_symbole',
    title: 'Un geste sous l’hymne',
    body: 'On te presse de porter un message symbolique fort au moment de l’hymne, devant le monde entier. Le faire t’érige en voix courageuse mais te plonge dans une tempête qui dépasse le football. T’abstenir protège ta carrière et te fait taxer de lâcheté par ceux qui espéraient ta prise de position.',
    category: 'national_team',
    tags: ['selection', 'symbole', 'medias'],
    rarity: 'rare',
    weight: 4,
    ageMin: 21,
    ageMax: 36,
    cooldownSeasons: 6,
    choices: [
      choice({
        id: 'faire',
        label: 'Porter le message',
        stance: 'ethical',
        riskPreview: 'Voix courageuse, tempête hors football.',
        immediate: [fx.res('popularite', 5), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('resistancePression', 3)],
        delayed: [fx.delayed(1, [fx.chance(0.35, [fx.rel('sponsors', -6)])])],
      }),
      choice({
        id: 'abstenir',
        label: 'T’abstenir prudemment',
        stance: 'prudent',
        riskPreview: 'Carrière protégée, accusation de lâcheté.',
        immediate: [fx.res('bienEtre', 2), fx.res('popularite', -4)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_nat_prime_federation',
    title: 'Bras de fer sur les primes',
    body: 'La fédération rechigne à verser les primes promises et le groupe hésite à hausser le ton. Mener la fronde avec tes coéquipiers défend vos droits mais t’expose aux représailles des dirigeants. Rester en retrait ménage la fédération et te fait passer pour tiède auprès d’un vestiaire qui compte ses soutiens.',
    category: 'national_team',
    tags: ['selection', 'primes', 'argent'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 22,
    ageMax: 37,
    cooldownSeasons: 6,
    choices: [
      choice({
        id: 'mener',
        label: 'Mener la fronde',
        stance: 'collective',
        riskPreview: 'Droits défendus, représailles possibles.',
        immediate: [fx.rel('teammates', 7), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('loyaute', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('reputationSportive', -4)])])],
      }),
      choice({
        id: 'retrait',
        label: 'Rester en retrait',
        stance: 'prudent',
        riskPreview: 'Fédération ménagée, image de tiède.',
        immediate: [fx.res('reputationSportive', 2), fx.rel('teammates', -6)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_nat_retraite_internationale',
    title: 'Tirer ta révérence en sélection',
    body: 'Les allers-retours internationaux t’épuisent et grignotent tes saisons de club. Te retirer de la sélection préserve ton corps et ton club, mais referme un chapitre glorieux avant l’heure. Continuer coûte que coûte prolonge l’aventure nationale et hypothèque des saisons entières usées par les voyages.',
    category: 'national_team',
    tags: ['selection', 'fin_carriere', 'gestion'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 29,
    ageMax: 37,
    cooldownSeasons: 6,
    choices: [
      choice({
        id: 'retirer',
        label: 'Te retirer de la sélection',
        stance: 'professional',
        riskPreview: 'Corps et club préservés, chapitre refermé tôt.',
        immediate: [fx.res('forme', 5), fx.res('reputationSportive', -3)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
      choice({
        id: 'continuer',
        label: 'Continuer coûte que coûte',
        stance: 'resilient',
        riskPreview: 'Aventure prolongée, saisons de club hypothéquées.',
        immediate: [fx.res('reputationSportive', 3), fx.res('fatigue', 6)],
        hidden: [fx.hidden('loyaute', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('forme', -6)])])],
      }),
    ],
  }),
]
