import { dilemma, choice, fx } from '../helpers'
import type { DilemmaDefinition } from '../../../game-engine/dilemmas'

/**
 * Phase 8 — Vestiaire. Situations neuves (inclut documentaire vestiaire et
 * jeune copiant ton style). Emplacement 1/2 selon le thème.
 */
export const vestiaireDilemmas: DilemmaDefinition[] = [
  dilemma({
    id: 'p8_vest_clans',
    title: 'Deux clans se forment',
    body: 'Le groupe se fend en deux camps qui ne se parlent plus qu’en façade. Rejoindre le clan majoritaire te met à l’abri mais nourrit la fracture. Rester neutre au milieu préserve ton intégrité et t’expose à devenir la cible des deux bords à la première tension.',
    category: 'teammates',
    tags: ['vestiaire', 'clans'],
    rarity: 'common',
    weight: 8,
    ageMin: 18,
    ageMax: 38,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'rejoindre',
        label: 'Rejoindre le clan dominant',
        stance: 'individualist',
        riskPreview: 'Position confortable, fracture entretenue.',
        immediate: [fx.rel('teammates', 5), fx.res('cohesionVestiaire', -5)],
        hidden: [fx.hidden('adaptabilite', 2)],
      }),
      choice({
        id: 'neutre',
        label: 'Rester au-dessus des camps',
        stance: 'ethical',
        riskPreview: 'Intégrité gardée, cible des deux bords.',
        immediate: [fx.res('reputationSportive', 3), fx.rel('teammates', -4)],
        hidden: [fx.hidden('professionnalisme', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('cohesionVestiaire', 5)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_vest_documentaire',
    title: 'Une caméra vit dans le vestiaire',
    body: 'Une production filme le vestiaire tout au long de la saison, sans filtre. Te livrer vraiment offre des images fortes et une popularité neuve, mais expose tes coups de sang et tes doutes. Rester lisse protège ton image et fait de toi le figurant fade d’un récit qui t’échappe.',
    category: 'teammates',
    tags: ['vestiaire', 'documentaire', 'medias'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 19,
    ageMax: 36,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'livrer',
        label: 'Te livrer face caméra',
        stance: 'media_savvy',
        riskPreview: 'Popularité neuve, coups de sang exposés.',
        immediate: [fx.res('popularite', 7), fx.res('bienEtre', -4)],
        hidden: [fx.hidden('ambition', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('reputationSportive', -5)])])],
      }),
      choice({
        id: 'lisse',
        label: 'Rester lisse et discret',
        stance: 'prudent',
        riskPreview: 'Image protégée, rôle de figurant.',
        immediate: [fx.res('bienEtre', 3), fx.res('popularite', -3)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_vest_jeune_copie',
    title: 'Un gamin calque tout sur toi',
    body: 'Un jeune du centre imite ta coupe, tes gestes, ton attitude jusqu’à la caricature. Le prendre sous ton aile flatte ton statut et forge un allié fidèle, mais te charge d’une responsabilité. L’ignorer garde ta tranquillité et laisse s’étioler une admiration qui pouvait grandir la légende.',
    category: 'teammates',
    tags: ['vestiaire', 'jeune', 'transmission'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 24,
    ageMax: 38,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'guider',
        label: 'Le prendre sous ton aile',
        stance: 'collective',
        riskPreview: 'Allié fidèle, responsabilité en plus.',
        immediate: [fx.rel('teammates', 6), fx.res('fatigue', 2)],
        hidden: [fx.hidden('loyaute', 2)],
        delayed: [fx.delayed(2, [fx.chance(0.4, [fx.res('reputationSportive', 4)])])],
      }),
      choice({
        id: 'ignorer',
        label: 'Le laisser à distance',
        stance: 'individualist',
        riskPreview: 'Tranquillité gardée, admiration gâchée.',
        immediate: [fx.res('bienEtre', 2), fx.rel('teammates', -4)],
        hidden: [fx.hidden('ambition', 1)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_vest_supplement_louche',
    title: 'Le petit coup de pouce interdit',
    body: 'Un partenaire te glisse un « complément » qui, dit-il, l’a transformé. Céder pourrait booster tes sensations mais te fait franchir une ligne dangereuse pour ton corps et ta réputation. Refuser net protège ton intégrité et te vaut les moqueries de ceux qui jouent avec le feu.',
    category: 'teammates',
    tags: ['vestiaire', 'ethique', 'sante'],
    rarity: 'rare',
    weight: 4,
    ageMin: 18,
    ageMax: 34,
    cooldownSeasons: 6,
    choices: [
      choice({
        id: 'refuser',
        label: 'Refuser sans hésiter',
        stance: 'ethical',
        riskPreview: 'Intégrité intacte, moqueries encaissées.',
        immediate: [fx.res('sante', 3), fx.rel('teammates', -4)],
        hidden: [fx.hidden('professionnalisme', 3)],
      }),
      choice({
        id: 'tenter',
        label: 'Tenter le coup de pouce',
        stance: 'high_risk',
        riskPreview: 'Sensations dopées, corps et image en jeu.',
        immediate: [fx.res('forme', 5), fx.res('discipline', -4)],
        hidden: [fx.hidden('professionnalisme', -3)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.res('sante', -10)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_vest_recrue_ego',
    title: 'La recrue au très gros ego',
    body: 'Un renfort talentueux mais imbuvable pourrit l’ambiance dès le premier jour. Le recadrer devant tous rétablit l’ordre au risque d’un clash public. Le laisser faire préserve la paix apparente et laisse le poison se diffuser dans un groupe qui commence déjà à se déliter.',
    category: 'teammates',
    tags: ['vestiaire', 'recrue', 'autorite'],
    rarity: 'common',
    weight: 7,
    ageMin: 22,
    ageMax: 38,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'recadrer',
        label: 'Le recadrer devant tous',
        stance: 'collective',
        riskPreview: 'Ordre rétabli, clash public possible.',
        immediate: [fx.stat('leadership', 2), fx.res('cohesionVestiaire', 4)],
        hidden: [fx.hidden('loyaute', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.rel('teammates', -6)])])],
      }),
      choice({
        id: 'laisser',
        label: 'Laisser filer pour la paix',
        stance: 'prudent',
        riskPreview: 'Paix de façade, poison qui diffuse.',
        immediate: [fx.res('bienEtre', 2), fx.res('cohesionVestiaire', -5)],
        hidden: [fx.hidden('constance', 1)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_vest_amendes',
    title: 'La caisse des amendes',
    body: 'Cadre du groupe, tu tiens la caisse des amendes. Sanctionner un intouchable en retard affirme l’équité mais froisse une star qui rapporte gros. Fermer les yeux préserve la relation avec les gros bras et sape la règle que tout le monde regarde en douce.',
    category: 'teammates',
    tags: ['vestiaire', 'discipline', 'autorite'],
    rarity: 'common',
    weight: 6,
    ageMin: 23,
    ageMax: 38,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'sanctionner',
        label: 'Sanctionner sans exception',
        stance: 'ethical',
        riskPreview: 'Équité affirmée, star froissée.',
        immediate: [fx.res('cohesionVestiaire', 5), fx.rel('teammates', -4)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
      choice({
        id: 'fermer',
        label: 'Fermer les yeux pour la star',
        stance: 'individualist',
        riskPreview: 'Relation gardée, règle sapée.',
        immediate: [fx.rel('teammates', 4), fx.res('cohesionVestiaire', -4)],
        hidden: [fx.hidden('loyaute', -1)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('cohesionVestiaire', -4)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_vest_integration_recrue',
    title: 'Le renfort qui ne parle à personne',
    body: 'Un joueur venu de loin reste muré dans sa solitude, perdu par la langue et la culture. L’aider à s’intégrer soude le groupe et t’ajoute une charge quotidienne. Te concentrer sur ton seul football protège ton énergie et laisse un coéquipier sombrer dans l’isolement, au détriment de l’équipe.',
    category: 'teammates',
    tags: ['vestiaire', 'integration'],
    rarity: 'common',
    weight: 6,
    ageMin: 19,
    ageMax: 38,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'aider',
        label: 'L’aider à s’intégrer',
        stance: 'collective',
        riskPreview: 'Groupe soudé, charge quotidienne.',
        immediate: [fx.res('cohesionVestiaire', 5), fx.res('fatigue', 2)],
        hidden: [fx.hidden('loyaute', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.4, [fx.rel('teammates', 6)])])],
      }),
      choice({
        id: 'concentrer',
        label: 'Rester sur ton football',
        stance: 'individualist',
        riskPreview: 'Énergie gardée, coéquipier isolé.',
        immediate: [fx.res('bienEtre', 2), fx.res('cohesionVestiaire', -4)],
        hidden: [fx.hidden('ambition', 1)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_vest_coloc_tournee',
    title: 'Le coéquipier de chambre insupportable',
    body: 'En déplacement, on te colle un partenaire bruyant qui saccage ton sommeil d’avant-match. Exiger de changer de chambre protège ta préparation mais le vexe et jase dans le groupe. Prendre sur toi préserve la bonne entente et te fait aborder la rencontre les yeux cernés.',
    category: 'teammates',
    tags: ['vestiaire', 'deplacement', 'preparation'],
    rarity: 'common',
    weight: 5,
    ageMin: 18,
    ageMax: 36,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'changer',
        label: 'Exiger de changer de chambre',
        stance: 'professional',
        riskPreview: 'Sommeil préservé, coéquipier vexé.',
        immediate: [fx.res('forme', 3), fx.rel('teammates', -5)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
      choice({
        id: 'endurer',
        label: 'Prendre sur toi',
        stance: 'collective',
        riskPreview: 'Entente gardée, nuit sacrifiée.',
        immediate: [fx.res('cohesionVestiaire', 3), fx.res('fatigue', 5)],
        hidden: [fx.hidden('constance', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('forme', -5)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_vest_critique_coequipier',
    title: 'Un partenaire te charge dans la presse',
    body: 'Un coéquipier glisse en interview que tu joues perso. Lui répondre dans les médias rétablit ta version mais transforme un différend interne en feuilleton public. Régler ça en privé, dans le vestiaire, garde la façade propre et laisse l’attaque impunie flotter dans les têtes.',
    category: 'teammates',
    tags: ['vestiaire', 'medias', 'conflit'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 19,
    ageMax: 37,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'public',
        label: 'Répondre dans les médias',
        stance: 'high_risk',
        riskPreview: 'Version rétablie, feuilleton public lancé.',
        immediate: [fx.res('reputationSportive', 3), fx.res('cohesionVestiaire', -6)],
        hidden: [fx.hidden('resistancePression', 2)],
      }),
      choice({
        id: 'prive',
        label: 'Régler ça en privé',
        stance: 'collective',
        riskPreview: 'Façade propre, attaque impunie.',
        immediate: [fx.res('cohesionVestiaire', 4), fx.res('moral', -3)],
        hidden: [fx.hidden('professionnalisme', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.rel('teammates', 4)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_vest_leader_vieillissant',
    title: 'Le vieux lion défie le nouveau',
    body: 'L’ancien patron du vestiaire, sur le déclin, s’oppose à une jeune voix qui monte. Soutenir l’ancien honore les codes mais fige un groupe qui a besoin d’air. Adouber le nouveau souffle bouscule la hiérarchie et te vaut l’inimitié durable d’un homme qui régnait ici avant toi.',
    category: 'teammates',
    tags: ['vestiaire', 'hierarchie', 'leadership'],
    rarity: 'uncommon',
    weight: 6,
    ageMin: 22,
    ageMax: 38,
    cooldownSeasons: 5,
    choices: [
      choice({
        id: 'ancien',
        label: 'Soutenir l’ancien patron',
        stance: 'loyal',
        riskPreview: 'Codes honorés, groupe figé.',
        immediate: [fx.rel('teammates', 5), fx.res('cohesionVestiaire', -3)],
        hidden: [fx.hidden('loyaute', 2)],
      }),
      choice({
        id: 'nouveau',
        label: 'Adouber le nouveau souffle',
        stance: 'ambitious',
        riskPreview: 'Air neuf, inimitié durable gagnée.',
        immediate: [fx.res('cohesionVestiaire', 4), fx.rel('teammates', -4)],
        hidden: [fx.hidden('adaptabilite', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('reputationSportive', 3)])])],
      }),
    ],
  }),

  dilemma({
    id: 'p8_vest_business_maillots',
    title: 'Le petit trafic du vestiaire',
    body: 'Un coéquipier revend en douce maillots et places, en te proposant ta part. Participer arrondit tes fins de mois et te lie au groupe, au risque d’un scandale si ça fuite. Refuser et alerter le club protège ton image mais fait de toi le rapporteur que personne n’aime.',
    category: 'teammates',
    tags: ['vestiaire', 'ethique', 'argent'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 19,
    ageMax: 36,
    cooldownSeasons: 6,
    choices: [
      choice({
        id: 'participer',
        label: 'Prendre ta part discrètement',
        stance: 'financial',
        riskPreview: 'Petit gain, scandale possible si ça fuite.',
        immediate: [fx.cash(6000), fx.res('discipline', -4)],
        hidden: [fx.hidden('professionnalisme', -2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.res('reputationSportive', -6)])])],
      }),
      choice({
        id: 'alerter',
        label: 'Refuser et prévenir le club',
        stance: 'ethical',
        riskPreview: 'Image propre, étiquette de rapporteur.',
        immediate: [fx.res('discipline', 4), fx.rel('teammates', -6)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_vest_rituel_groupe',
    title: 'Le rituel d’avant-match du groupe',
    body: 'Le vestiaire s’est inventé un rituel collectif un peu envahissant avant chaque match. T’y plier renforce l’unité et te fond dans le groupe, au prix de ta routine perso qui te réussit. T’en tenir à ta préparation garde tes repères et te marginalise doucement des soirs de communion.',
    category: 'teammates',
    tags: ['vestiaire', 'rituel', 'preparation'],
    rarity: 'common',
    weight: 5,
    ageMin: 18,
    ageMax: 37,
    cooldownSeasons: 4,
    choices: [
      choice({
        id: 'suivre',
        label: 'Suivre le rituel collectif',
        stance: 'collective',
        riskPreview: 'Unité renforcée, routine perso perdue.',
        immediate: [fx.res('cohesionVestiaire', 5), fx.res('forme', -2)],
        hidden: [fx.hidden('adaptabilite', 2)],
      }),
      choice({
        id: 'routine',
        label: 'Garder ta routine à toi',
        stance: 'individualist',
        riskPreview: 'Repères gardés, mise à l’écart douce.',
        immediate: [fx.res('forme', 3), fx.res('cohesionVestiaire', -3)],
        hidden: [fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p8_vest_greve_primes',
    title: 'Le vestiaire menace de faire grève',
    body: 'Primes impayées : le groupe veut boycotter l’entraînement pour peser sur la direction. Suivre le mouvement montre ta solidarité mais t’expose aux foudres du club et des supporters. Refuser de gréver protège ta relation avec les dirigeants et te fait passer pour un briseur aux yeux des tiens.',
    category: 'teammates',
    tags: ['vestiaire', 'greve', 'argent'],
    rarity: 'uncommon',
    weight: 5,
    ageMin: 20,
    ageMax: 38,
    cooldownSeasons: 6,
    choices: [
      choice({
        id: 'suivre',
        label: 'Suivre la grève du groupe',
        stance: 'collective',
        riskPreview: 'Solidarité affichée, foudres du club.',
        immediate: [fx.rel('teammates', 8), fx.res('reputationSportive', -4)],
        hidden: [fx.hidden('loyaute', 2)],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.rel('fans', -6)])])],
      }),
      choice({
        id: 'refuser',
        label: 'Refuser de faire grève',
        stance: 'prudent',
        riskPreview: 'Dirigeants ménagés, étiquette de briseur.',
        immediate: [fx.res('reputationSportive', 2), fx.rel('teammates', -8)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),
]
