import type { DilemmaDefinition } from '../../game-engine/dilemmas'
import { chainEpisode, choice, dilemma, fx } from './helpers'

export const chainDilemmas: DilemmaDefinition[] = [
  // ——— Chaîne loyauté (4 épisodes) ———
  dilemma({
    id: 'chain_loyalty_01',
    title: 'Offre discrète d’un rival',
    body: 'Un dirigeant d’un club rival te contacte par message privé. Il te promet un projet sportif séduisant sans passer par ton agent officiel.',
    category: 'transfer',
    tags: ['chain', 'loyaute', 'transfer'],
    rarity: 'uncommon',
    weight: 25,
    ageMin: 20,
    ageMax: 34,
    choices: [
      choice({
        id: 'ecouter',
        label: 'Accepter d’écouter sa proposition en secret',
        stance: 'ambitious',
        riskPreview: 'Porte entrouverte vers l’inconnu.',
        immediate: [fx.flag('loyalty_contact_rival')],
        nextEventIds: ['chain_loyalty_02'],
      }),
      choice({
        id: 'refuser',
        label: 'Refuser et signaler l’approche à ton directeur sportif',
        stance: 'loyal',
        riskPreview: 'Tu renforces la confiance du club actuel.',
        immediate: [fx.rel('coach', 6), fx.res('confianceEntraineur', 5)],
        hidden: [fx.hidden('loyaute', 3)],
      }),
    ],
  }),

  chainEpisode({
    id: 'chain_loyalty_02',
    previousEventId: 'chain_loyalty_01',
    title: 'Visite nocturne du recruteur',
    body: 'Le recruteur insiste pour te rencontrer dans un hôtel discret avant la trêve. Il a déjà préparé une offre salariale écrite.',
    tags: ['chain', 'loyaute'],
    rarity: 'uncommon',
    choices: [
      choice({
        id: 'y_aller',
        label: 'Te rendre à la rencontre sans informer ton club',
        stance: 'high_risk',
        riskPreview: 'Tu accumules des secrets.',
        immediate: [fx.flag('loyalty_rencontre_secrete')],
        nextEventIds: ['chain_loyalty_03'],
        hidden: [fx.res('discipline', -3)],
      }),
      choice({
        id: 'annuler',
        label: 'Annuler et couper le contact',
        stance: 'prudent',
        riskPreview: 'Tu fermes la porte, le rival se venge peut-être.',
        immediate: [fx.removeFlag('loyalty_contact_rival'), fx.res('moral', 3)],
      }),
    ],
  }),

  chainEpisode({
    id: 'chain_loyalty_03',
    previousEventId: 'chain_loyalty_02',
    title: 'Fuite dans la presse régionale',
    body: 'Une rumeur circule : tu aurais rencontré un dirigeant rival. Ton entraîneur te convoque sans sourire. Le recruteur nie, ton agent panique.',
    tags: ['chain', 'loyaute', 'media'],
    rarity: 'uncommon',
    choices: [
      choice({
        id: 'mentir',
        label: 'Nier toute rencontre devant le staff',
        stance: 'individualist',
        riskPreview: 'Tu gagnes du temps, pas de la confiance.',
        immediate: [fx.rel('coach', -4), fx.flag('loyalty_mensonge')],
        nextEventIds: ['chain_loyalty_04'],
      }),
      choice({
        id: 'avouer',
        label: 'Avouer la rencontre et présenter tes excuses',
        stance: 'ethical',
        riskPreview: 'Crise immédiate, réconciliation possible.',
        immediate: [fx.rel('coach', -2), fx.res('confianceEntraineur', -5)],
        nextEventIds: ['chain_loyalty_04'],
        hidden: [fx.hidden('loyaute', 1)],
      }),
    ],
  }),

  chainEpisode({
    id: 'chain_loyalty_04',
    previousEventId: 'chain_loyalty_03',
    title: 'Ultimatum du club',
    body: 'Le directeur sportif te propose un renouvellement anticipé avec clause de fidélité — ou une mise à l’écart temporaire le temps que la poussière retombe.',
    tags: ['chain', 'loyaute', 'contrat'],
    rarity: 'uncommon',
    choices: [
      choice({
        id: 'signer_fidelite',
        label: 'Signer le renouvellement avec clause de fidélité',
        stance: 'loyal',
        riskPreview: 'Tu scelles ton avenir ici.',
        immediate: [fx.cash(8000), fx.res('confianceEntraineur', 8), fx.removeFlag('loyalty_mensonge')],
        hidden: [fx.hidden('loyaute', 4)],
      }),
      choice({
        id: 'accepter_banc',
        label: 'Accepter la mise à l’écart et laisser ton agent négocier ton départ',
        stance: 'ambitious',
        riskPreview: 'Tu brises le lien, tu ouvres le marché.',
        immediate: [fx.rel('coach', -8), fx.res('reputationSportive', 3)],
        delayed: [fx.delayed(2, [fx.res('popularite', -4)])],
      }),
    ],
  }),

  // ——— Chaîne tempête médiatique (5 épisodes) ———
  dilemma({
    id: 'chain_media_storm_01',
    title: 'Capture virale mal interprétée',
    body: 'Une vidéo te montre en train de sourire après une défaite. En quelques heures, les commentaires deviennent une tempête nationale.',
    category: 'media',
    tags: ['chain', 'media', 'viral'],
    rarity: 'uncommon',
    weight: 20,
    ageMin: 18,
    ageMax: 35,
    choices: [
      choice({
        id: 'reagir_vite',
        label: 'Publier une explication immédiate en story',
        stance: 'prudent',
        riskPreview: 'Tu prends les devants, erreurs possibles.',
        immediate: [fx.rel('media', 3), fx.res('popularite', 2)],
        nextEventIds: ['chain_media_storm_02'],
      }),
      choice({
        id: 'silence',
        label: 'Laisser le club communiquer à ta place',
        stance: 'loyal',
        riskPreview: 'Tu évites le piège, la tempête continue.',
        immediate: [fx.rel('coach', 2), fx.res('moral', -4)],
        nextEventIds: ['chain_media_storm_02'],
      }),
    ],
  }),

  chainEpisode({
    id: 'chain_media_storm_02',
    previousEventId: 'chain_media_storm_01',
    title: 'Plateau télé hostile',
    body: 'Une chaîne nationale t’invite sur un plateau « pour t’expliquer ». Le présentateur a réputation de mener des interrogatoires agressifs.',
    tags: ['chain', 'media'],
    rarity: 'uncommon',
    choices: [
      choice({
        id: 'accepter_plateau',
        label: 'Accepter le plateau en direct',
        stance: 'ambitious',
        riskPreview: 'Tu te bats pour ton image en public.',
        immediate: [fx.res('fatigue', 4)],
        nextEventIds: ['chain_media_storm_03'],
        hidden: [
          fx.skillCheck('hidden', 'resistancePression', 58, [
            fx.res('popularite', 6),
          ], [fx.res('moral', -8)]),
        ],
      }),
      choice({
        id: 'decliner_plateau',
        label: 'Décliner et laisser ton avocat répondre par communiqué',
        stance: 'prudent',
        riskPreview: 'Tu te protèges, on parle de lâcheté.',
        immediate: [fx.rel('media', -4), fx.res('discipline', 2)],
        nextEventIds: ['chain_media_storm_03'],
      }),
    ],
  }),

  chainEpisode({
    id: 'chain_media_storm_03',
    previousEventId: 'chain_media_storm_02',
    title: 'Coéquipier commente en off',
    body: 'Un coéquipier commente la polémique en off dans un podcast sans te prévenir. Il laisse entendre que tu « ne prends pas assez les défaites ».',
    tags: ['chain', 'media', 'vestiaire'],
    rarity: 'uncommon',
    choices: [
      choice({
        id: 'confronter',
        label: 'Le confronter devant le groupe',
        stance: 'individualist',
        riskPreview: 'Tu rétablis ta vérité, le vestiaire s’embrase.',
        immediate: [fx.rel('teammates', -5), fx.res('cohesionVestiaire', -6)],
        nextEventIds: ['chain_media_storm_04'],
      }),
      choice({
        id: 'regler_prive',
        label: 'Régler ça en privé avec le capitaine',
        stance: 'ethical',
        riskPreview: 'Médiation discrète, issue incertaine.',
        immediate: [fx.rel('teammates', 1)],
        nextEventIds: ['chain_media_storm_04'],
        hidden: [
          fx.skillCheck('stat', 'leadership', 55, [
            fx.res('cohesionVestiaire', 4),
          ], [fx.rel('teammates', -3)]),
        ],
      }),
    ],
  }),

  chainEpisode({
    id: 'chain_media_storm_04',
    previousEventId: 'chain_media_storm_03',
    title: 'Sponsor menace de suspendre',
    body: 'Ton sponsor principal menace de geler les paiements si tu ne « rétablis pas la vérité » publiquement selon leur script.',
    tags: ['chain', 'media', 'sponsor'],
    rarity: 'uncommon',
    choices: [
      choice({
        id: 'lire_script',
        label: 'Lire leur communiqué pré-rédigé',
        stance: 'financial',
        riskPreview: 'Trésorerie sauvée, crédibilité entamée.',
        immediate: [fx.cash(5000), fx.rel('sponsors', 4), fx.rel('fans', -4)],
        nextEventIds: ['chain_media_storm_05'],
      }),
      choice({
        id: 'refuser_script',
        label: 'Refuser le script et assumer ta version',
        stance: 'ethical',
        riskPreview: 'Tu perds de l’argent, tu gagnes en cohérence.',
        immediate: [fx.rel('sponsors', -6), fx.rel('fans', 5)],
        nextEventIds: ['chain_media_storm_05'],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  chainEpisode({
    id: 'chain_media_storm_05',
    previousEventId: 'chain_media_storm_04',
    title: 'Retour au calme ou rupture',
    body: 'La tempête faiblit. Tu dois choisir comment clore le chapitre : tourner la page devant les supporters ou porter plainte pour diffamation.',
    tags: ['chain', 'media'],
    rarity: 'uncommon',
    choices: [
      choice({
        id: 'tourner_page',
        label: 'Remercier les supporters et tourner la page',
        stance: 'loyal',
        riskPreview: 'Clôture apaisée, certains restent sceptiques.',
        immediate: [fx.rel('fans', 4), fx.res('moral', 5), fx.res('popularite', 3)],
      }),
      choice({
        id: 'plainte',
        label: 'Porter plainte contre les médias les plus agressifs',
        stance: 'ambitious',
        riskPreview: 'Bataille juridique longue et coûteuse.',
        immediate: [fx.cash(-10000), fx.rel('media', -8)],
        delayed: [
          fx.delayed(3, [
            fx.chance(0.5, [fx.res('reputationSportive', 6)]),
            fx.chance(0.5, [fx.res('popularite', -5)]),
          ]),
        ],
      }),
    ],
  }),

  // ——— Chaîne deal agent (4 épisodes) ———
  dilemma({
    id: 'chain_agent_deal_01',
    title: 'Agent alternatif insistant',
    body: 'Un agent influent te propose de rompre avec le tien en échange d’un réseau « plus adapté à ton niveau ». Il affirme avoir déjà parlé à trois clubs.',
    category: 'agent',
    tags: ['chain', 'agent'],
    rarity: 'uncommon',
    weight: 22,
    ageMin: 19,
    ageMax: 33,
    choices: [
      choice({
        id: 'ecouter_offre',
        label: 'L’écouter en secret dans un café',
        stance: 'ambitious',
        riskPreview: 'Tu ouvres une brèche avec ton agent actuel.',
        immediate: [fx.flag('agent_alternatif_contact')],
        nextEventIds: ['chain_agent_deal_02'],
      }),
      choice({
        id: 'raccrocher',
        label: 'Raccrocher et prévenir ton agent actuel',
        stance: 'loyal',
        riskPreview: 'Loyauté récompensée ou naïveté.',
        immediate: [fx.res('discipline', 3), fx.hidden('loyaute', 2)],
      }),
    ],
  }),

  chainEpisode({
    id: 'chain_agent_deal_02',
    previousEventId: 'chain_agent_deal_01',
    title: 'Contrat miroir sur la table',
    body: 'L’agent alternatif te présente un contrat miroir : commission réduite, bonus sur transfert, et une clause te laissant choisir ton prochain club.',
    tags: ['chain', 'agent'],
    rarity: 'uncommon',
    choices: [
      choice({
        id: 'signer_miroir',
        label: 'Signer le contrat miroir sans résilier l’ancien',
        stance: 'high_risk',
        riskPreview: 'Double représentation — zone grise.',
        immediate: [fx.flag('double_agent'), fx.cash(3000)],
        nextEventIds: ['chain_agent_deal_03'],
      }),
      choice({
        id: 'negocier_transition',
        label: 'Exiger une transition propre avec ton agent actuel',
        stance: 'prudent',
        riskPreview: 'Processus lent, moins de surprises.',
        immediate: [fx.res('discipline', 2)],
        nextEventIds: ['chain_agent_deal_03'],
      }),
    ],
  }),

  chainEpisode({
    id: 'chain_agent_deal_03',
    previousEventId: 'chain_agent_deal_02',
    title: 'Ton agent actuel découvre tout',
    body: 'Ton agent actuel te confronte avec des captures d’écran. Il menace de révéler tes négociations parallèles au club si tu ne reviens pas en arrière.',
    tags: ['chain', 'agent'],
    rarity: 'uncommon',
    choices: [
      choice({
        id: 'revenir',
        label: 'Revenir vers lui et rompre avec l’agent alternatif',
        stance: 'loyal',
        riskPreview: 'Tu répares une relation, tu fermes des portes.',
        immediate: [fx.removeFlag('double_agent'), fx.rel('coach', 2)],
        nextEventIds: ['chain_agent_deal_04'],
      }),
      choice({
        id: 'assumer_rupture',
        label: 'Assumer la rupture publiquement',
        stance: 'individualist',
        riskPreview: 'Tu contrôles le récit, le club panique.',
        immediate: [fx.flag('rupture_agent_publique'), fx.res('confianceEntraineur', -4)],
        nextEventIds: ['chain_agent_deal_04'],
      }),
    ],
  }),

  chainEpisode({
    id: 'chain_agent_deal_04',
    previousEventId: 'chain_agent_deal_03',
    title: 'Nouveau chapitre ou retour de flamme',
    body: 'La situation se stabilise. Tu dois officialiser ton représentant pour la saison à venir et calmer le club.',
    tags: ['chain', 'agent'],
    rarity: 'uncommon',
    choices: [
      choice({
        id: 'garder_nouveau',
        label: 'Officialiser l’agent alternatif',
        stance: 'ambitious',
        riskPreview: 'Nouveau réseau, nouvelles promesses.',
        immediate: [fx.removeFlag('agent_alternatif_contact'), fx.res('reputationSportive', 3)],
        delayed: [fx.delayed(2, [fx.chance(0.5, [fx.cash(15000)])])],
      }),
      choice({
        id: 'reconciliation',
        label: 'Renégocier avec ton agent d’origine à de meilleures conditions',
        stance: 'prudent',
        riskPreview: 'Stabilité retrouvée, commission élevée.',
        immediate: [fx.removeFlag('rupture_agent_publique'), fx.res('confianceEntraineur', 4)],
        hidden: [fx.hidden('loyaute', 2)],
      }),
    ],
  }),

  // ——— Chaîne pari médical (3 épisodes) ———
  dilemma({
    id: 'chain_injury_gamble_01',
    title: 'Blessure avant match décisif',
    body: 'Tu as une déchirure légère à la cuisse. Le staff te laisse vingt-quatre heures pour décider si tu joues la demi-finale ou non.',
    category: 'injury',
    tags: ['chain', 'blessure', 'match'],
    rarity: 'uncommon',
    weight: 24,
    ageMin: 19,
    ageMax: 36,
    choices: [
      choice({
        id: 'jouer_gamble',
        label: 'Jouer avec infiltration approuvée par le staff',
        stance: 'high_risk',
        riskPreview: 'Héros potentiel, récidive probable.',
        immediate: [fx.res('sante', -5), fx.flag('injury_gamble_joue')],
        nextEventIds: ['chain_injury_gamble_02'],
      }),
      choice({
        id: 'laisser_place',
        label: 'Laisser ta place au remplaçant',
        stance: 'prudent',
        riskPreview: 'Tu protèges ton corps, tu manques le moment.',
        immediate: [fx.res('sante', 6), fx.res('confianceEntraineur', -2)],
        nextEventIds: ['chain_injury_gamble_02'],
      }),
    ],
  }),

  chainEpisode({
    id: 'chain_injury_gamble_02',
    previousEventId: 'chain_injury_gamble_01',
    title: 'Conséquences immédiates',
    body: 'Le match est derrière toi. Tu sens une douleur différente — ou au contraire un soulagement immense. Le médecin veut des examens complémentaires.',
    tags: ['chain', 'blessure'],
    rarity: 'uncommon',
    choices: [
      choice({
        id: 'examens_complets',
        label: 'Accepter tous les examens et repos forcé',
        stance: 'prudent',
        riskPreview: 'Diagnostic clair, absence probable.',
        immediate: [fx.res('sante', 8), fx.res('forme', -4)],
        nextEventIds: ['chain_injury_gamble_03'],
      }),
      choice({
        id: 'minimiser',
        label: 'Minimiser les symptômes pour rester disponible',
        stance: 'high_risk',
        riskPreview: 'Tu restes dans le groupe, tu mens au staff.',
        immediate: [fx.res('forme', 3), fx.flag('injury_gamble_minimise')],
        nextEventIds: ['chain_injury_gamble_03'],
        hidden: [fx.res('confianceEntraineur', -3)],
      }),
    ],
  }),

  chainEpisode({
    id: 'chain_injury_gamble_03',
    previousEventId: 'chain_injury_gamble_02',
    title: 'Verdict médical final',
    body: 'Les résultats arrivent en pleine semaine de championnat. Tu dois accepter le protocole imposé ou chercher un second avis agressif.',
    tags: ['chain', 'blessure'],
    rarity: 'uncommon',
    choices: [
      choice({
        id: 'accepter_protocole',
        label: 'Suivre le protocole du club sans discuter',
        stance: 'loyal',
        riskPreview: 'Reprise saine, temps perdu.',
        immediate: [fx.res('sante', 10), fx.res('confianceEntraineur', 4)],
        hidden: [fx.hidden('fragilitePhysique', -2)],
      }),
      choice({
        id: 'second_avis',
        label: 'Consulter un spécialiste externe recommandé par ton entourage',
        stance: 'individualist',
        riskPreview: 'Retour accéléré ou conflit médical.',
        immediate: [fx.flag('second_avis_externe')],
        delayed: [
          fx.delayed(2, [
            fx.chance(0.4, [fx.res('forme', 8), fx.res('confianceEntraineur', -6)]),
            fx.chance(0.6, [fx.res('sante', -10)]),
          ]),
        ],
      }),
    ],
  }),

  // ——— Chaîne ascension banc (4 épisodes) ———
  dilemma({
    id: 'chain_bench_rise_01',
    title: 'Opportunité en coupe',
    body: 'Le titulaire de ton poste est suspendu pour le quart de finale de coupe. L’entraîneur te regarde dans le couloir sans dire un mot.',
    category: 'match',
    tags: ['chain', 'banc', 'opportunite'],
    rarity: 'uncommon',
    weight: 28,
    ageMin: 17,
    ageMax: 28,
    prerequisites: [{ type: 'maxMinutesLastSeason', value: 600 }],
    choices: [
      choice({
        id: 'preparer_serieux',
        label: 'Préparer le match comme une finale personnelle',
        stance: 'ambitious',
        riskPreview: 'Tu mets la pression sur tes épaules.',
        immediate: [fx.res('moral', 5), fx.res('fatigue', 4)],
        nextEventIds: ['chain_bench_rise_02'],
      }),
      choice({
        id: 'rester_sobre',
        label: 'Rester sobre et suivre le plan sans en faire trop',
        stance: 'prudent',
        riskPreview: 'Approche professionnelle, moins de buzz.',
        immediate: [fx.res('discipline', 3), fx.res('confianceEntraineur', 2)],
        nextEventIds: ['chain_bench_rise_02'],
      }),
    ],
  }),

  chainEpisode({
    id: 'chain_bench_rise_02',
    previousEventId: 'chain_bench_rise_01',
    title: 'Performance convaincante',
    body: 'Tu as livré une bonne performance. Les journaux parlent de toi pour la première fois de la saison. Le titulaire revient disponible pour la demi-finale.',
    tags: ['chain', 'banc'],
    rarity: 'uncommon',
    choices: [
      choice({
        id: 'demander_continuite',
        label: 'Demander à conserver la place pour la demi-finale',
        stance: 'ambitious',
        riskPreview: 'Tu défies la hiérarchie établie.',
        immediate: [fx.rel('coach', -2), fx.res('reputationSportive', 4)],
        nextEventIds: ['chain_bench_rise_03'],
      }),
      choice({
        id: 'céder_place',
        label: 'Affirmer que le titulaire mérite de revenir',
        stance: 'loyal',
        riskPreview: 'Tu gagnes le respect, tu retournes au banc.',
        immediate: [fx.rel('teammates', 5), fx.res('cohesionVestiaire', 4)],
        nextEventIds: ['chain_bench_rise_03'],
      }),
    ],
  }),

  chainEpisode({
    id: 'chain_bench_rise_03',
    previousEventId: 'chain_bench_rise_02',
    title: 'Titulaire blessé à l’échauffement',
    body: 'Le titulaire se blesse à l’échauffement. Tu as trente minutes pour te préparer mentalement. L’entraîneur te serre l’épaule sans un mot.',
    tags: ['chain', 'banc', 'blessure'],
    rarity: 'uncommon',
    choices: [
      choice({
        id: 'embrasser_role',
        label: 'Entrer avec l’intention de décider du match',
        stance: 'ambitious',
        riskPreview: 'Moment de gloire ou d’effondrement.',
        immediate: [fx.res('moral', 6)],
        nextEventIds: ['chain_bench_rise_04'],
        hidden: [
          fx.skillCheck('stat', 'sangFroid', 50, [
            fx.res('reputationSportive', 8),
            fx.res('confianceEntraineur', 6),
          ], [fx.res('moral', -6)]),
        ],
      }),
      choice({
        id: 'jouer_collectif',
        label: 'Te fondre dans le collectif sans te mettre en avant',
        stance: 'loyal',
        riskPreview: 'Tu sers l’équipe, moins de lumière.',
        immediate: [fx.res('cohesionVestiaire', 5), fx.stat('tactique', 1)],
        nextEventIds: ['chain_bench_rise_04'],
      }),
    ],
  }),

  chainEpisode({
    id: 'chain_bench_rise_04',
    previousEventId: 'chain_bench_rise_03',
    title: 'Nouveau statut dans la rotation',
    body: 'Après la coupe, l’entraîneur évoque un « nouveau rôle » pour toi. Tu peux devenir rotation régulière ou retomber dans l’ombre selon ta réponse.',
    tags: ['chain', 'banc'],
    rarity: 'uncommon',
    choices: [
      choice({
        id: 'accepter_rotation',
        label: 'Accepter un rôle de rotation régulière sans exiger le titularisme',
        stance: 'prudent',
        riskPreview: 'Progression stable, plafond visible.',
        immediate: [fx.res('confianceEntraineur', 6), fx.res('forme', 4)],
        delayed: [fx.delayed(2, [fx.res('reputationSportive', 5)])],
      }),
      choice({
        id: 'exiger_titre',
        label: 'Exiger un statut de titulaire avant la reprise',
        stance: 'individualist',
        riskPreview: 'Tu forces une décision, tu risques tout.',
        immediate: [fx.rel('coach', -4), fx.hidden('ambition', 3)],
        delayed: [
          fx.delayed(1, [
            fx.chance(0.45, [fx.res('confianceEntraineur', 8)]),
            fx.chance(0.55, [fx.res('cohesionVestiaire', -5)]),
          ]),
        ],
      }),
    ],
  }),

  // ——— Chaîne crise gardien (4 épisodes) ———
  dilemma({
    id: 'chain_gk_crisis_01',
    title: 'Erreur sur penalty',
    body: 'Tu as touché le penalty mais le ballon est quand même entré. Les réseaux sociaux s’enflamment et un ancien gardien légendaire du club critique ta technique en direct.',
    category: 'match',
    tags: ['chain', 'gardien', 'crise'],
    rarity: 'uncommon',
    weight: 22,
    ageMin: 18,
    ageMax: 38,
    positions: ['gk'],
    choices: [
      choice({
        id: 'analyser_froidement',
        label: 'Analyser froidement la vidéo avec ton coach gardiens',
        stance: 'prudent',
        riskPreview: 'Travail constructif, ego touché.',
        immediate: [fx.stat('placement', 2), fx.res('moral', -3)],
        nextEventIds: ['chain_gk_crisis_02'],
      }),
      choice({
        id: 'bloquer_critiques',
        label: 'Couper les réseaux et éviter les commentaires',
        stance: 'individualist',
        riskPreview: 'Tu te protèges, tu t’isoles.',
        immediate: [fx.res('moral', 2), fx.rel('media', -3)],
        nextEventIds: ['chain_gk_crisis_02'],
      }),
    ],
  }),

  chainEpisode({
    id: 'chain_gk_crisis_02',
    previousEventId: 'chain_gk_crisis_01',
    title: 'Concurrence au poste annoncée',
    body: 'Le club annonce publiquement qu’il cherche un gardien expérimenté en renfort. Ton agent te propose une conférence de presse pour répondre.',
    tags: ['chain', 'gardien'],
    rarity: 'uncommon',
    choices: [
      choice({
        id: 'tenir_conf',
        label: 'Tenir une conférence pour affirmer ta confiance',
        stance: 'ambitious',
        riskPreview: 'Tu assumes le feu, tu t’exposes davantage.',
        immediate: [fx.rel('media', 5), fx.res('popularite', 3)],
        nextEventIds: ['chain_gk_crisis_03'],
      }),
      choice({
        id: 'silence_pro',
        label: 'Rester silencieux et travailler sans commenter',
        stance: 'prudent',
        riskPreview: 'Discrétion professionnelle, rumeurs persistent.',
        immediate: [fx.res('discipline', 4), fx.hidden('professionnalisme', 2)],
        nextEventIds: ['chain_gk_crisis_03'],
      }),
    ],
  }),

  chainEpisode({
    id: 'chain_gk_crisis_03',
    previousEventId: 'chain_gk_crisis_02',
    title: 'Match de verrouillage',
    body: 'L’entraîneur te laisse titulaire pour un match où tu ne dois surtout pas encaisser. Le renfort recruté t’observe depuis le banc.',
    tags: ['chain', 'gardien', 'match'],
    rarity: 'uncommon',
    choices: [
      choice({
        id: 'clean_sheet',
        label: 'Jouer ultra-sécuritaire, aucune prise de risque',
        stance: 'prudent',
        riskPreview: 'Clean sheet possible, peu de heroism.',
        immediate: [fx.stat('tactique', 2)],
        nextEventIds: ['chain_gk_crisis_04'],
        hidden: [
          fx.skillCheck('stat', 'sangFroid', 55, [
            fx.res('confianceEntraineur', 8),
            fx.res('reputationSportive', 5),
          ], [fx.res('moral', -7)]),
        ],
      }),
      choice({
        id: 'sorties_agressives',
        label: 'Imposer tes sorties agressives pour montrer ta valeur',
        stance: 'high_risk',
        riskPreview: 'Tu te distingues ou tu confirmes les doutes.',
        immediate: [fx.stat('puissance', 1)],
        nextEventIds: ['chain_gk_crisis_04'],
        hidden: [
          fx.chance(0.5, [fx.res('reputationSportive', 7)]),
          fx.chance(0.5, [fx.res('confianceEntraineur', -6)]),
        ],
      }),
    ],
  }),

  chainEpisode({
    id: 'chain_gk_crisis_04',
    previousEventId: 'chain_gk_crisis_03',
    title: 'Décision du club',
    body: 'La direction convoque entraîneur, gardien adjoint et toi. Ils annoncent une décision sur la hiérarchie du poste pour les six prochains mois.',
    tags: ['chain', 'gardien'],
    rarity: 'uncommon',
    choices: [
      choice({
        id: 'accepter_concurrence',
        label: 'Accepter une concurrence ouverte avec le renfort',
        stance: 'loyal',
        riskPreview: 'Tu restes, tu te bats chaque semaine.',
        immediate: [fx.res('moral', 4), fx.res('confianceEntraineur', 3)],
        hidden: [fx.hidden('constance', 2)],
      }),
      choice({
        id: 'demander_pret',
        label: 'Demander un prêt pour jouer titulaire ailleurs',
        stance: 'ambitious',
        riskPreview: 'Tu quittes temporairement, tu relances ta carrière.',
        immediate: [fx.flag('gk_demande_pret'), fx.res('reputationSportive', 2)],
        delayed: [fx.delayed(2, [fx.res('forme', 5)])],
      }),
    ],
  }),

  // ——— Chaîne promesse transfert (5 épisodes) ———
  dilemma({
    id: 'chain_transfer_promise_01',
    title: 'Rumeur de clause cachée',
    body: 'Un journaliste te contacte : il prétend connaître l’existence d’une clause secrète dans ton contrat. Il te demande confirmation avant de publier.',
    category: 'contract',
    tags: ['chain', 'transfer', 'clause'],
    rarity: 'uncommon',
    weight: 18,
    ageMin: 20,
    ageMax: 35,
    choices: [
      choice({
        id: 'nier_clause',
        label: 'Nier l’existence d’une clause et menacer de plainte',
        stance: 'prudent',
        riskPreview: 'Tu bloques la publication, tu attises la curiosité.',
        immediate: [fx.rel('media', -3), fx.flag('clause_rumeur')],
        nextEventIds: ['chain_transfer_promise_02'],
      }),
      choice({
        id: 'confirmer_off',
        label: 'Confirmer officieusement en échange de discrétion',
        stance: 'high_risk',
        riskPreview: 'Tu contrôles partiellement le récit.',
        immediate: [fx.rel('media', 4), fx.flag('clause_confirmee')],
        nextEventIds: ['chain_transfer_promise_02'],
      }),
    ],
  }),

  chainEpisode({
    id: 'chain_transfer_promise_02',
    previousEventId: 'chain_transfer_promise_01',
    title: 'Réaction du club à la rumeur',
    body: 'Le club publie un communiqué démentant toute clause secrète. Ton agent te dit que deux clubs ont quand même intensifié leurs contacts cette semaine.',
    tags: ['chain', 'transfer', 'rumeur'],
    rarity: 'uncommon',
    choices: [
      choice({
        id: 'calmer_agent',
        label: 'Demander à ton agent de calmer les contacts externes',
        stance: 'loyal',
        riskPreview: 'Tu apais le club, tu fermes des portes.',
        immediate: [fx.rel('coach', 4), fx.res('confianceEntraineur', 3)],
        nextEventIds: ['chain_transfer_promise_03'],
      }),
      choice({
        id: 'laisser_agent',
        label: 'Laisser ton agent explorer les options sans engager',
        stance: 'ambitious',
        riskPreview: 'Marché ouvert, tension interne.',
        immediate: [fx.flag('transfer_options_ouvertes')],
        nextEventIds: ['chain_transfer_promise_03'],
      }),
    ],
  }),

  chainEpisode({
    id: 'chain_transfer_promise_03',
    previousEventId: 'chain_transfer_promise_02',
    title: 'Premier mois sans nouvelle',
    body: 'Un mois s’est écoulé depuis la promesse verbale du président. Aucun document n’arrive. Ton agent reçoit pourtant des appels d’un club étranger.',
    tags: ['chain', 'transfer', 'promesse'],
    rarity: 'uncommon',
    choices: [
      choice({
        id: 'relancer_president',
        label: 'Relancer le président en privé',
        stance: 'prudent',
        riskPreview: 'Tu rappelles l’engagement, tu peux le braquer.',
        immediate: [fx.rel('coach', -1)],
        nextEventIds: ['chain_transfer_promise_04'],
      }),
      choice({
        id: 'ecouter_etranger',
        label: 'Écouter l’offre étrangère sans engager le club',
        stance: 'ambitious',
        riskPreview: 'Option B activée, loyauté en jeu.',
        immediate: [fx.flag('offre_etrangere_ecoutee')],
        nextEventIds: ['chain_transfer_promise_04'],
      }),
    ],
  }),

  chainEpisode({
    id: 'chain_transfer_promise_04',
    previousEventId: 'chain_transfer_promise_03',
    title: 'Contrat partiellement rédigé',
    body: 'Le club te transmet enfin un projet de contrat — avec un salaire inférieur à la promesse initiale. Le président parle de « contexte économique difficile ».',
    tags: ['chain', 'transfer', 'contrat'],
    rarity: 'uncommon',
    choices: [
      choice({
        id: 'signer_reduit',
        label: 'Signer la version réduite pour rester loyal',
        stance: 'loyal',
        riskPreview: 'Tu honores ta parole, tu gagnes moins.',
        immediate: [fx.cash(5000), fx.res('confianceEntraineur', 5)],
        nextEventIds: ['chain_transfer_promise_05'],
        hidden: [fx.hidden('loyaute', 3)],
      }),
      choice({
        id: 'refuser_exiger',
        label: 'Refuser et exiger le montant promis par écrit',
        stance: 'financial',
        riskPreview: 'Négociation dure, relation présidentielle tendue.',
        immediate: [fx.rel('coach', -3), fx.flag('conflit_president')],
        nextEventIds: ['chain_transfer_promise_05'],
      }),
    ],
  }),

  chainEpisode({
    id: 'chain_transfer_promise_05',
    previousEventId: 'chain_transfer_promise_04',
    title: 'Fuite sur tes exigences',
    body: 'Un média local publie que tu aurais « exigé un salaire XXL ». Le président nie la promesse verbale. Le vestiaire commente.',
    tags: ['chain', 'transfer', 'media'],
    rarity: 'uncommon',
    choices: [
      choice({
        id: 'publier_preuve',
        label: 'Menacer de publier des échanges privés',
        stance: 'high_risk',
        riskPreview: 'Guerre ouverte avec la direction.',
        immediate: [fx.rel('media', 4), fx.flag('guerre_president')],
        nextEventIds: ['chain_transfer_promise_06'],
      }),
      choice({
        id: 'calmer_jeux',
        label: 'Calmer le jeu via un communiqué commun',
        stance: 'prudent',
        riskPreview: 'Apaisement partiel, promesses floues.',
        immediate: [fx.rel('coach', 2), fx.res('cohesionVestiaire', 2)],
        nextEventIds: ['chain_transfer_promise_06'],
      }),
    ],
  }),

  chainEpisode({
    id: 'chain_transfer_promise_06',
    previousEventId: 'chain_transfer_promise_05',
    title: 'Résolution du dossier',
    body: 'La saison avance. Tu dois trancher : rester en renégociant, partir en libre selon ta clause, ou accepter un statut de leader sans reconnaissance financière.',
    tags: ['chain', 'transfer'],
    rarity: 'uncommon',
    choices: [
      choice({
        id: 'rester_leader',
        label: 'Rester comme leader reconnu sans nouveau contrat',
        stance: 'loyal',
        riskPreview: 'Statut symbolique, frustration financière.',
        immediate: [fx.res('reputationSportive', 4), fx.rel('teammates', 4)],
        hidden: [fx.hidden('ambition', -1)],
      }),
      choice({
        id: 'partir_libre',
        label: 'Activer ta clause et partir en fin de saison',
        stance: 'ambitious',
        riskPreview: 'Nouveau départ, rupture avec les fans.',
        immediate: [fx.flag('depart_clause_active'), fx.res('popularite', -5)],
        delayed: [fx.delayed(2, [fx.res('reputationSportive', 6)])],
      }),
    ],
  }),

  // ——— Chaîne legacy (6 épisodes) ———
  dilemma({
    id: 'chain_legacy_01',
    title: 'Héritage du club sur tes épaules',
    body: 'Le club célèbre un anniversaire historique. On te demande de porter le maillot rétro lors d’une séance ouverte aux supporters. Une légende locale commentera ta démarche.',
    category: 'narrative_chain',
    tags: ['chain', 'legacy', 'club'],
    rarity: 'uncommon',
    weight: 16,
    ageMin: 22,
    ageMax: 38,
    prerequisites: [{ type: 'minResource', id: 'reputationSportive', value: 65 }],
    choices: [
      choice({
        id: 'porter_retro',
        label: 'Porter le maillot rétro avec fierté devant les supporters',
        stance: 'loyal',
        riskPreview: 'Tu incarnes l’histoire du club.',
        immediate: [fx.rel('fans', 6), fx.res('popularite', 4)],
        nextEventIds: ['chain_legacy_02'],
      }),
      choice({
        id: 'decliner_retro',
        label: 'Décliner poliment pour te concentrer sur le présent',
        stance: 'individualist',
        riskPreview: 'Tu évites la comparaison, certains déçus.',
        immediate: [fx.res('moral', 2), fx.rel('fans', -2)],
        nextEventIds: ['chain_legacy_02'],
      }),
    ],
  }),

  chainEpisode({
    id: 'chain_legacy_02',
    previousEventId: 'chain_legacy_01',
    title: 'Conseils de la légende',
    body: 'La légende du club te confie ses rituels avant les grands matchs. Elle insiste : « Si tu veux entrer dans l’histoire, tu dois changer ton rapport à la pression. »',
    tags: ['chain', 'legacy', 'mentor'],
    rarity: 'uncommon',
    choices: [
      choice({
        id: 'adopter_rituels',
        label: 'Adopter ses rituels à la lettre',
        stance: 'loyal',
        riskPreview: 'Tu entres dans sa ombre, tu progresses peut-être.',
        immediate: [fx.hidden('grandsMatchs', 3), fx.res('moral', 4)],
        nextEventIds: ['chain_legacy_03'],
      }),
      choice({
        id: 'adapter_rituels',
        label: 'Adapter ses conseils à ta personnalité',
        stance: 'individualist',
        riskPreview: 'Tu te construis ton propre chemin.',
        immediate: [fx.hidden('constance', 2), fx.res('moral', 2)],
        nextEventIds: ['chain_legacy_03'],
      }),
    ],
  }),

  chainEpisode({
    id: 'chain_legacy_03',
    previousEventId: 'chain_legacy_02',
    title: 'Invitation au conseil des anciens',
    body: 'Le club t’invite au conseil des anciens avant un match mémorable. Tu y croises des figures qui ont façonné l’identité du club.',
    tags: ['chain', 'legacy'],
    rarity: 'uncommon',
    choices: [
      choice({
        id: 'parler_discours',
        label: 'Prendre la parole lors du discours d’ouverture',
        stance: 'ambitious',
        riskPreview: 'Tu assumes une voix historique.',
        immediate: [fx.stat('leadership', 2), fx.rel('fans', 5)],
        nextEventIds: ['chain_legacy_04'],
      }),
      choice({
        id: 'ecouter_discret',
        label: 'Écouter et rester discret',
        stance: 'prudent',
        riskPreview: 'Tu absorbes, tu ne t’imposes pas.',
        immediate: [fx.hidden('adaptabilite', 2), fx.res('bienEtre', 3)],
        nextEventIds: ['chain_legacy_04'],
      }),
    ],
  }),

  chainEpisode({
    id: 'chain_legacy_04',
    previousEventId: 'chain_legacy_03',
    title: 'Match mémorable annoncé',
    body: 'Le club annonce une soirée « héritage » autour de ton prochain match au stade. La légende veut te remettre son brassard symbolique avant le coup d’envoi.',
    tags: ['chain', 'legacy', 'match'],
    rarity: 'uncommon',
    choices: [
      choice({
        id: 'accepter_brassard',
        label: 'Accepter le brassard symbolique publiquement',
        stance: 'emotional',
        riskPreview: 'Moment électrique, poids énorme.',
        immediate: [fx.res('popularite', 8), fx.res('moral', 5)],
        nextEventIds: ['chain_legacy_05'],
        hidden: [fx.res('fatigue', 4)],
      }),
      choice({
        id: 'decliner_brassard',
        label: 'Décliner et proposer un hommage discret après le match',
        stance: 'prudent',
        riskPreview: 'Tu évites le théâtre, certains déçus.',
        immediate: [fx.rel('fans', -2), fx.hidden('resistancePression', 2)],
        nextEventIds: ['chain_legacy_05'],
      }),
    ],
  }),

  chainEpisode({
    id: 'chain_legacy_05',
    previousEventId: 'chain_legacy_04',
    title: 'Performance sous les projecteurs',
    body: 'Le match est là. Les anciens, la presse et la légende te regardent. Tu sens que cette soirée peut définir ton chapitre au club.',
    tags: ['chain', 'legacy', 'match'],
    rarity: 'uncommon',
    choices: [
      choice({
        id: 'tout_donner',
        label: 'Jouer sans calculer ta dépense d’énergie',
        stance: 'ambitious',
        riskPreview: 'Gloire ou épuisement.',
        immediate: [fx.res('fatigue', 10)],
        nextEventIds: ['chain_legacy_06'],
        hidden: [
          fx.skillCheck('hidden', 'grandsMatchs', 60, [
            fx.res('reputationSportive', 10),
            fx.rel('fans', 8),
          ], [fx.res('moral', -8)]),
        ],
      }),
      choice({
        id: 'jeu_collectif',
        label: 'Faire briller l’équipe plutôt que ton individualité',
        stance: 'loyal',
        riskPreview: 'Tu sers le collectif, moins de une.',
        immediate: [fx.res('cohesionVestiaire', 6), fx.rel('teammates', 5)],
        nextEventIds: ['chain_legacy_06'],
      }),
    ],
  }),

  chainEpisode({
    id: 'chain_legacy_06',
    previousEventId: 'chain_legacy_05',
    title: 'Inscription dans l’histoire',
    body: 'Les réactions affluent après la soirée. Le club te propose d’inaugurer une plaque au centre d’entraînement — ou de garder une discrétion jusqu’à la fin de ta carrière.',
    tags: ['chain', 'legacy'],
    rarity: 'uncommon',
    choices: [
      choice({
        id: 'inaugurer_plaque',
        label: 'Accepter la plaque et un discours devant les jeunes',
        stance: 'emotional',
        riskPreview: 'Tu deviens symbole du club.',
        immediate: [fx.res('popularite', 10), fx.rel('fans', 8), fx.hidden('grandsMatchs', 3)],
        hidden: [fx.flag('legacy_inscrit')],
      }),
      choice({
        id: 'reporter_hommage',
        label: 'Reporter tout hommage public à plus tard',
        stance: 'prudent',
        riskPreview: 'Tu gardes de la marge, la légende comprend ou non.',
        immediate: [fx.res('bienEtre', 4), fx.res('moral', 3)],
        hidden: [fx.hidden('ambition', 1)],
      }),
    ],
  }),
]
