import type { DilemmaDefinition } from '../../game-engine/dilemmas'
import { choice, dilemma, fx } from './helpers'

export const commonDilemmas: DilemmaDefinition[] = [
  dilemma({
    id: 'entrainement_intensif_matin',
    title: 'Séance matinale surprise',
    body: 'L’entraîneur adjoint convoque une séance supplémentaire à l’aube. Plusieurs coéquipiers chuchotent qu’ils comptent s’excuser pour une « contrainte familiale » inventée.',
    category: 'training',
    tags: ['entrainement', 'discipline'],
    rarity: 'common',
    weight: 85,
    ageMin: 16,
    ageMax: 38,
    choices: [
      choice({
        id: 'participer',
        label: 'Te présenter en avance, sans discuter',
        stance: 'prudent',
        riskPreview: 'Fatigue accrue possible, mais l’encadrement te remarque.',
        immediate: [fx.res('fatigue', 8), fx.res('forme', 3)],
        delayed: [fx.delayed(1, [fx.res('confianceEntraineur', 5)])],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
      choice({
        id: 'boycott_discret',
        label: 'Suivre le mouvement et envoyer un message d’excuse',
        stance: 'individualist',
        riskPreview: 'Tu gagnes du repos, mais le groupe sait qui manque.',
        immediate: [fx.res('fatigue', -5), fx.rel('teammates', 4)],
        delayed: [fx.delayed(1, [fx.res('confianceEntraineur', -6)])],
        hidden: [fx.hidden('constance', -2)],
      }),
    ],
  }),

  dilemma({
    id: 'match_capitaine_bracelet',
    title: 'Brassard offert en urgence',
    body: 'Le capitaine sort sur blessure et l’entraîneur te tend le brassard avant la reprise. Le vestiaire te regarde : certains attendent des consignes fermes, d’autres veulent qu’on joue librement.',
    category: 'match',
    tags: ['match', 'leadership'],
    rarity: 'uncommon',
    weight: 55,
    ageMin: 20,
    ageMax: 36,
    choices: [
      choice({
        id: 'discipline_tactique',
        label: 'Rappeler le plan de jeu et calmer le rythme',
        stance: 'prudent',
        riskPreview: 'Tu prends des responsabilités visibles sur le terrain.',
        immediate: [fx.stat('tactique', 2), fx.res('cohesionVestiaire', 3)],
        delayed: [fx.delayed(1, [fx.res('confianceEntraineur', 4)])],
        hidden: [fx.stat('leadership', 2)],
      }),
      choice({
        id: 'liberte_offensive',
        label: 'Encourager le pressing et la prise de risque',
        stance: 'ambitious',
        riskPreview: 'L’équipe peut briller ou se désorganiser.',
        immediate: [fx.stat('vitesse', 1), fx.res('forme', 4)],
        delayed: [
          fx.delayed(1, [
            fx.chance(0.5, [fx.res('reputationSportive', 6)]),
            fx.chance(0.5, [fx.res('discipline', -4)]),
          ]),
        ],
        hidden: [fx.hidden('grandsMatchs', 1)],
      }),
    ],
  }),

  dilemma({
    id: 'coach_critique_publique',
    title: 'Critique en conférence de presse',
    body: 'Après une défaite serrée, l’entraîneur cite ton nom lors d’une conférence de presse pour illustrer un manque d’intensité défensive. Les journalistes te tendent déjà le micro au mixed zone.',
    category: 'coach',
    tags: ['coach', 'media'],
    rarity: 'common',
    weight: 70,
    ageMin: 18,
    ageMax: 40,
    choices: [
      choice({
        id: 'assumer',
        label: 'Reconnaître ta part de responsabilité devant la presse',
        stance: 'ethical',
        riskPreview: 'Tu montres de la maturité, mais tu t’exposes.',
        immediate: [fx.rel('media', 5), fx.rel('coach', 2)],
        delayed: [fx.delayed(1, [fx.res('popularite', 3)])],
        hidden: [fx.hidden('resistancePression', 2)],
      }),
      choice({
        id: 'contredire',
        label: 'Nuancer en expliquant les consignes reçues',
        stance: 'individualist',
        riskPreview: 'Tu défends ta version, au risque d’irriter l’encadrement.',
        immediate: [fx.rel('coach', -5), fx.rel('teammates', 3)],
        hidden: [fx.hidden('loyaute', -2), fx.res('confianceEntraineur', -4)],
      }),
    ],
  }),

  dilemma({
    id: 'vestiaire_blague_grenier',
    title: 'Blague qui va trop loin',
    body: 'Un coéquipier lance une blague sur ton accent régional devant tout le vestiaire. Le groupe rit nerveusement. Personne ne dit rien pour l’instant.',
    category: 'teammates',
    tags: ['vestiaire', 'cohesion'],
    rarity: 'common',
    weight: 75,
    ageMin: 16,
    ageMax: 34,
    choices: [
      choice({
        id: 'repondre_humour',
        label: 'Répondre avec une vanne plus cinglante',
        stance: 'individualist',
        riskPreview: 'Tu reprends la main, mais l’ambiance peut se tendre.',
        immediate: [fx.rel('teammates', -2), fx.res('moral', 4)],
        hidden: [fx.hidden('constance', 1)],
      }),
      choice({
        id: 'en_parler_calme',
        label: 'Demander un échange à l’écart après l’entraînement',
        stance: 'prudent',
        riskPreview: 'Approche mature, résultat incertain.',
        immediate: [fx.rel('teammates', 2), fx.res('bienEtre', 3)],
        delayed: [
          fx.delayed(1, [
            fx.skillCheck('hidden', 'professionnalisme', 55, [
              fx.res('cohesionVestiaire', 5),
            ], [fx.rel('teammates', -3)]),
          ]),
        ],
      }),
    ],
  }),

  dilemma({
    id: 'media_reseaux_trop_honnete',
    title: 'Story trop sincère',
    body: 'Tu publies une story après une victoire en laissant entendre que la tactique du coach t’a surpris. Un journaliste reprend la capture avant que tu ne la supprimes.',
    category: 'media',
    tags: ['reseaux', 'communication'],
    rarity: 'common',
    weight: 65,
    ageMin: 17,
    ageMax: 32,
    choices: [
      choice({
        id: 'excuser_maladresse',
        label: 'Présenter ça comme une maladresse et t’excuser',
        stance: 'prudent',
        riskPreview: 'Tu apais les tensions internes.',
        immediate: [fx.rel('coach', 3), fx.rel('media', -2)],
        hidden: [fx.res('popularite', -2)],
      }),
      choice({
        id: 'assumer_propos',
        label: 'Assumer ton ressenti et appeler à plus de clarté',
        stance: 'ambitious',
        riskPreview: 'Les supporters te soutiennent peut-être, le staff moins.',
        immediate: [fx.rel('coach', -6), fx.rel('fans', 5)],
        delayed: [fx.delayed(2, [fx.res('reputationSportive', 4)])],
        hidden: [fx.hidden('ambition', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'argent_pret_ami',
    title: 'Prêt demandé par un proche',
    body: 'Un ami d’enfance te demande une avance importante pour lancer une affaire douteuse. Il promet de rembourser « dès le premier contrat signé ».',
    category: 'money',
    tags: ['finances', 'entourage'],
    rarity: 'common',
    weight: 60,
    ageMin: 19,
    ageMax: 45,
    choices: [
      choice({
        id: 'refuser_clairement',
        label: 'Refuser en expliquant que tu ne mélanges pas amitié et argent',
        stance: 'prudent',
        riskPreview: 'Tu protèges ton épargne, la relation peut souffrir.',
        immediate: [fx.rel('friends', -5), fx.res('financesPersonnelles', 0)],
        hidden: [fx.hidden('professionnalisme', 1)],
      }),
      choice({
        id: 'preter_partiel',
        label: 'Prêter une somme modérée sans garantie',
        stance: 'emotional',
        riskPreview: 'Tu aides quelqu’un de proche, avec un risque financier.',
        immediate: [fx.cash(-8000), fx.rel('friends', 6)],
        delayed: [
          fx.delayed(2, [
            fx.chance(0.35, [fx.cash(12000)]),
            fx.chance(0.65, [fx.rel('friends', -4)]),
          ]),
        ],
      }),
    ],
  }),

  dilemma({
    id: 'blessure_douteuse_reprise',
    title: 'Douleur persistante à la reprise',
    body: 'Tu sens une gêne à la cuisse depuis trois jours. Le staff médical te laisse le choix : repos complet ou participation limitée au prochain match important.',
    category: 'injury',
    tags: ['sante', 'match'],
    rarity: 'common',
    weight: 72,
    ageMin: 18,
    ageMax: 38,
    choices: [
      choice({
        id: 'repos_complet',
        label: 'Suivre l’avis prudent et renoncer au match',
        stance: 'prudent',
        riskPreview: 'Tu manques une occasion de briller.',
        immediate: [fx.res('sante', 8), fx.res('forme', -3)],
        delayed: [fx.delayed(1, [fx.res('confianceEntraineur', -2)])],
        hidden: [fx.hidden('fragilitePhysique', -1)],
      }),
      choice({
        id: 'jouer_endormi',
        label: 'Prendre des anti-inflammatoires et jouer',
        stance: 'high_risk',
        riskPreview: 'Tu tiens sur le moment, la récidive guette.',
        immediate: [fx.res('forme', 5), fx.res('sante', -6)],
        delayed: [
          fx.delayed(1, [
            fx.chance(0.4, [fx.res('reputationSportive', 5)]),
            fx.chance(0.6, [fx.res('sante', -10), fx.res('fatigue', 8)]),
          ]),
        ],
        hidden: [fx.hidden('grandsMatchs', 1)],
      }),
    ],
  }),

  dilemma({
    id: 'famille_demenagement',
    title: 'Ta famille veut déménager',
    body: 'Tes parents envisagent de s’installer à l’autre bout du pays pour des raisons professionnelles. Ils te demandent ton avis alors que tu viens enfin de t’installer dans ta routine actuelle.',
    category: 'family',
    tags: ['famille', 'equilibre'],
    rarity: 'uncommon',
    weight: 50,
    ageMin: 16,
    ageMax: 28,
    choices: [
      choice({
        id: 'encourager',
        label: 'Les encourager à saisir cette opportunité',
        stance: 'loyal',
        riskPreview: 'Tu soutiens leurs projets, tu t’éloignes un peu.',
        immediate: [fx.rel('family', 6), fx.res('bienEtre', -3)],
        delayed: [fx.delayed(2, [fx.res('moral', -4)])],
      }),
      choice({
        id: 'demander_rester',
        label: 'Avouer que leur présence t’aide dans ta progression',
        stance: 'emotional',
        riskPreview: 'Tu priorises ton confort sportif, avec culpabilité possible.',
        immediate: [fx.rel('family', -3), fx.res('moral', 5)],
        hidden: [fx.hidden('loyaute', 1)],
      }),
    ],
  }),

  dilemma({
    id: 'style_vie_fete_anniversaire',
    title: 'Fête d’anniversaire la veille du match',
    body: 'Un coéquipier organise une soirée bruyante la veille d’un déplacement. L’entraîneur a rappelé le couvre-feu, mais l’ambiance est déjà lancée dans le groupe.',
    category: 'lifestyle',
    tags: ['nuit', 'discipline'],
    rarity: 'common',
    weight: 68,
    ageMin: 17,
    ageMax: 30,
    choices: [
      choice({
        id: 'partir_tot',
        label: 'Passer trente minutes puis rentrer dormir',
        stance: 'prudent',
        riskPreview: 'Tu respectes les consignes sans te couper du groupe.',
        immediate: [fx.res('discipline', 4), fx.rel('teammates', 1)],
        hidden: [fx.res('fatigue', -2)],
      }),
      choice({
        id: 'rester_feter',
        label: 'Rester jusqu’au bout pour ne pas passer pour le rabat-joie',
        stance: 'individualist',
        riskPreview: 'Ambiance garantie, sommeil incertain.',
        immediate: [fx.rel('teammates', 5), fx.res('fatigue', 10)],
        delayed: [fx.delayed(1, [fx.res('forme', -5), fx.res('confianceEntraineur', -3)])],
      }),
    ],
  }),

  dilemma({
    id: 'mental_pression_penalty',
    title: 'Penalty décisif à tirer',
    body: 'Le match est à égalité. L’arbitre siffle un penalty et tu te retrouves seul face au gardien. Tu sens les mains moites et le banc retenir son souffle.',
    category: 'mental',
    tags: ['penalty', 'pression'],
    rarity: 'uncommon',
    weight: 45,
    ageMin: 18,
    ageMax: 40,
    choices: [
      choice({
        id: 'frappe_puissance',
        label: 'Frapper fort dans l’angle, sans changer d’avis',
        stance: 'ambitious',
        riskPreview: 'Un geste décisif, dans les deux sens.',
        immediate: [],
        hidden: [
          fx.skillCheck('stat', 'sangFroid', 60, [
            fx.stat('finition', 2),
            fx.res('reputationSportive', 6),
          ], [fx.res('moral', -8), fx.res('confianceEntraineur', -3)]),
        ],
      }),
      choice({
        id: 'feinte_lente',
        label: 'Approcher lentement et chercher la feinte',
        stance: 'prudent',
        riskPreview: 'Tu mets la pression sur le gardien, pas sur toi.',
        immediate: [fx.stat('controle', 1)],
        hidden: [
          fx.skillCheck('stat', 'technique', 55, [
            fx.res('popularite', 4),
          ], [fx.res('moral', -5)]),
        ],
      }),
    ],
  }),

  dilemma({
    id: 'sponsors_contrat_image',
    title: 'Clause image contraignante',
    body: 'Un sponsor te propose une campagne lucrative avec une clause d’exclusivité qui limiterait tes apparitions caritatives habituelles.',
    category: 'sponsors',
    tags: ['sponsor', 'image'],
    rarity: 'uncommon',
    weight: 48,
    ageMin: 20,
    ageMax: 38,
    choices: [
      choice({
        id: 'accepter_contrat',
        label: 'Signer et négocier une dérogation limitée',
        stance: 'financial',
        riskPreview: 'Revenus en hausse, image plus contrôlée.',
        immediate: [fx.cash(15000), fx.rel('sponsors', 8)],
        delayed: [fx.delayed(2, [fx.rel('fans', -3)])],
        hidden: [fx.hidden('professionnalisme', 1)],
      }),
      choice({
        id: 'refuser_sponsor',
        label: 'Refuser pour garder ta liberté associative',
        stance: 'ethical',
        riskPreview: 'Tu perds un contrat, tu gagnes en cohérence.',
        immediate: [fx.rel('fans', 4), fx.rel('sponsors', -4)],
        hidden: [fx.hidden('loyaute', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'supporters_chant_personnel',
    title: 'Chant des supporters',
    body: 'Les ultras composent un chant à ton nom avant un derby. Une partie du club craint que ça te monte à la tête ; une autre y voit un soutien précieux.',
    category: 'fans',
    tags: ['supporters', 'derby'],
    rarity: 'common',
    weight: 62,
    ageMin: 18,
    ageMax: 35,
    choices: [
      choice({
        id: 'remercier',
        label: 'Saluer la tribune et remercier publiquement',
        stance: 'emotional',
        riskPreview: 'Tu renforces le lien avec les fans.',
        immediate: [fx.rel('fans', 8), fx.res('popularite', 5)],
        delayed: [fx.delayed(1, [fx.res('discipline', -2)])],
      }),
      choice({
        id: 'rester_discret',
        label: 'Rester sobre et rediriger l’attention vers l’équipe',
        stance: 'loyal',
        riskPreview: 'Tu évites l’individualisme, certains supporters déçus.',
        immediate: [fx.res('cohesionVestiaire', 4), fx.rel('fans', -2)],
        hidden: [fx.hidden('resistancePression', 1)],
      }),
    ],
  }),

  dilemma({
    id: 'contrat_renegociation_prematuree',
    title: 'Agent insistant pour renégocier',
    body: 'Ton agent pousse pour rouvrir ton contrat après une bonne série, alors que le club rappelle que tu es engagé encore deux saisons. Le directeur sportif te convoque « informellement ».',
    category: 'contract',
    tags: ['contrat', 'agent'],
    rarity: 'uncommon',
    weight: 52,
    ageMin: 19,
    ageMax: 33,
    choices: [
      choice({
        id: 'laisser_agent',
        label: 'Laisser ton agent mener les discussions',
        stance: 'financial',
        riskPreview: 'Tu restes en retrait, le club peut le vivre mal.',
        immediate: [fx.rel('coach', -2)],
        delayed: [
          fx.delayed(1, [
            fx.chance(0.5, [fx.cash(10000)]),
            fx.chance(0.5, [fx.res('confianceEntraineur', -6)]),
          ]),
        ],
      }),
      choice({
        id: 'rassurer_club',
        label: 'Rassurer le club sur ta motivation actuelle',
        stance: 'loyal',
        riskPreview: 'Tu apais le staff, ton agent n’est pas content.',
        immediate: [fx.rel('coach', 5), fx.res('confianceEntraineur', 4)],
        hidden: [fx.hidden('ambition', -1)],
      }),
    ],
  }),

  dilemma({
    id: 'agent_pourcentage_match',
    title: 'Prime sur match offerte par l’agent',
    body: 'Ton agent te propose une prime s’il parvient à te faire convoquer en sélection nationale cette saison. Il te demande de refuser un stage commercial concurrent.',
    category: 'agent',
    tags: ['agent', 'selection'],
    rarity: 'uncommon',
    weight: 44,
    ageMin: 18,
    ageMax: 34,
    choices: [
      choice({
        id: 'accepter_arrangement',
        label: 'Accepter l’arrangement et suivre son plan',
        stance: 'financial',
        riskPreview: 'Tu mises sur son réseau, pas sur toi seul.',
        immediate: [fx.flag('agent_deal_accepte')],
        delayed: [
          fx.delayed(2, [
            fx.chance(0.45, [fx.res('reputationSportive', 7)]),
            fx.chance(0.55, [fx.res('discipline', -5)]),
          ]),
        ],
      }),
      choice({
        id: 'refuser_conflit',
        label: 'Refuser et garder le contrôle de ton calendrier',
        stance: 'individualist',
        riskPreview: 'Autonomie préservée, relation tendue.',
        immediate: [fx.rel('sponsors', 3)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'transfer_rumeur_ete',
    title: 'Rumeur de transfert estivale',
    body: 'La presse locale évoque ton départ vers un club voisin. Ton entraîneur te demande si tu as « nourri » ces informations. Tu n’as rien confirmé, mais tu as bien écouté les contacts.',
    category: 'transfer',
    tags: ['transfer', 'rumeur'],
    rarity: 'common',
    weight: 58,
    ageMin: 20,
    ageMax: 36,
    choices: [
      choice({
        id: 'nier',
        label: 'Nier toute démarche et affirmer ton engagement',
        stance: 'loyal',
        riskPreview: 'Tu calmes le club, tu te fermes des options.',
        immediate: [fx.rel('coach', 4), fx.res('confianceEntraineur', 3)],
        hidden: [fx.hidden('loyaute', 1)],
      }),
      choice({
        id: 'etre_honnete',
        label: 'Admettre avoir reçu des appels sans demander à partir',
        stance: 'ethical',
        riskPreview: 'Transparence appréciée ou mal ressentie.',
        immediate: [fx.rel('coach', -3), fx.res('reputationSportive', 2)],
        delayed: [fx.delayed(1, [fx.res('popularite', -2)])],
      }),
    ],
  }),

  dilemma({
    id: 'selection_nationale_convocation',
    title: 'Convocation nationale surprise',
    body: 'Tu es convoqué pour un stage avec l’équipe nationale alors que ton club dispute une phase décisive. L’entraîneur te rappelle que le staff n’est « pas obligé » de te laisser partir sereinement.',
    category: 'national_team',
    tags: ['selection', 'club'],
    rarity: 'uncommon',
    weight: 42,
    ageMin: 19,
    ageMax: 35,
    choices: [
      choice({
        id: 'partir_selection',
        label: 'Honorer la convocation sans négocier',
        stance: 'ambitious',
        riskPreview: 'Tu gravis un échelon, le club peut s’en souvenir.',
        immediate: [fx.res('reputationSportive', 8), fx.rel('coach', -4)],
        delayed: [fx.delayed(2, [fx.stat('placement', 2)])],
        hidden: [fx.hidden('grandsMatchs', 2)],
      }),
      choice({
        id: 'discuter_compromis',
        label: 'Proposer un compromis de dates avec les deux staffs',
        stance: 'prudent',
        riskPreview: 'Tu cherches l’équilibre, sans garantie.',
        immediate: [fx.rel('coach', 2)],
        hidden: [
          fx.skillCheck('hidden', 'adaptabilite', 58, [
            fx.res('confianceEntraineur', 4),
            fx.res('reputationSportive', 4),
          ], [fx.res('moral', -4)]),
        ],
      }),
    ],
  }),

  dilemma({
    id: 'entrainement_individualise',
    title: 'Programme individualisé proposé',
    body: 'Le préparateur physique te propose un plan sur mesure avec séances privées. D’autres joueurs commencent à murmurer que tu bénéficies d’un traitement de faveur.',
    category: 'training',
    tags: ['preparation', 'vestiaire'],
    rarity: 'common',
    weight: 63,
    ageMin: 17,
    ageMax: 33,
    choices: [
      choice({
        id: 'accepter_plan',
        label: 'Accepter le programme et ignorer les commentaires',
        stance: 'ambitious',
        riskPreview: 'Progression ciblée, tensions possibles.',
        immediate: [fx.stat('endurance', 2), fx.rel('teammates', -3)],
        delayed: [fx.delayed(2, [fx.res('forme', 5)])],
      }),
      choice({
        id: 'partager_seances',
        label: 'Proposer d’inviter deux coéquipiers aux séances',
        stance: 'loyal',
        riskPreview: 'Tu partages l’avantage, tu dilues le plan.',
        immediate: [fx.rel('teammates', 5), fx.stat('endurance', 1)],
        hidden: [fx.stat('leadership', 1)],
      }),
    ],
  }),

  dilemma({
    id: 'match_simulation_adversaire',
    title: 'Faute subie ou simulation ?',
    body: 'Tu t’effondres dans la surface après un contact léger. L’arbitre hésite. Ton coéquipier te chuchote de te relever ; l’adversaire te fixe avec mépris.',
    category: 'match',
    tags: ['arbitrage', 'ethique'],
    rarity: 'common',
    weight: 66,
    ageMin: 18,
    ageMax: 38,
    choices: [
      choice({
        id: 'rester_ground',
        label: 'Rester au sol et laisser l’arbitre décider',
        stance: 'high_risk',
        riskPreview: 'Penalty possible, réputation ternie aussi.',
        immediate: [fx.rel('teammates', 2)],
        hidden: [
          fx.chance(0.55, [fx.res('reputationSportive', -4)]),
          fx.chance(0.45, [fx.stat('finition', 1)]),
        ],
      }),
      choice({
        id: 'se_relever',
        label: 'Te relever et continuer le jeu',
        stance: 'ethical',
        riskPreview: 'Respect gagné, occasion manquée peut-être.',
        immediate: [fx.rel('teammates', 4), fx.hidden('professionnalisme', 2)],
        delayed: [fx.delayed(1, [fx.rel('media', 3)])],
      }),
    ],
  }),

  dilemma({
    id: 'coach_changement_poste',
    title: 'Changement de poste imposé',
    body: 'L’entraîneur veut te faire jouer un rôle différent pour compenser une absence. Ce n’est pas ta zone de confort, mais l’équipe a besoin de toi là.',
    category: 'coach',
    tags: ['tactique', 'adaptation'],
    rarity: 'common',
    weight: 64,
    ageMin: 17,
    ageMax: 35,
    choices: [
      choice({
        id: 'accepter_role',
        label: 'Accepter sans discuter et travailler le nouveau rôle',
        stance: 'loyal',
        riskPreview: 'Tu te mets au service du collectif.',
        immediate: [fx.stat('tactique', 2), fx.res('confianceEntraineur', 4)],
        hidden: [fx.hidden('adaptabilite', 2)],
      }),
      choice({
        id: 'negocier_compromis',
        label: 'Proposer un compromis mi-poste mi-zone habituelle',
        stance: 'individualist',
        riskPreview: 'Tu défends ton identité de jeu.',
        immediate: [fx.rel('coach', -2), fx.stat('dribble', 1)],
        delayed: [
          fx.delayed(1, [
            fx.chance(0.5, [fx.res('forme', 4)]),
            fx.chance(0.5, [fx.res('cohesionVestiaire', -3)]),
          ]),
        ],
      }),
    ],
  }),

  dilemma({
    id: 'vestiaire_cap_senior',
    title: 'Initiative du cap des seniors',
    body: 'Les cadres organisent une amende interne après une mauvaise passe en championnat. Ils te demandent de choisir le montant pour un jeune qui a manqué deux entraînements.',
    category: 'teammates',
    tags: ['discipline', 'hierarchie'],
    rarity: 'uncommon',
    weight: 50,
    ageMin: 22,
    ageMax: 38,
    choices: [
      choice({
        id: 'amende_douce',
        label: 'Proposer une amende symbolique et un tour de vestiaire',
        stance: 'prudent',
        riskPreview: 'Tu adoucis la sanction, les cadres froncent.',
        immediate: [fx.rel('teammates', 3), fx.res('discipline', 2)],
        hidden: [fx.stat('leadership', 1)],
      }),
      choice({
        id: 'amende_lourde',
        label: 'Suggérer une amende salée pour marquer le coup',
        stance: 'ambitious',
        riskPreview: 'Tu gagnes le respect des cadres, pas des jeunes.',
        immediate: [fx.rel('teammates', 5), fx.res('cohesionVestiaire', -4)],
        hidden: [fx.hidden('constance', -1)],
      }),
    ],
  }),

  dilemma({
    id: 'media_interview_provocante',
    title: 'Question piège en interview',
    body: 'Un présentateur télé te demande si ton club « vise encore le titre » après trois matchs nuls. La réponse sera découpée en bandes-annonces.',
    category: 'media',
    tags: ['tele', 'objectifs'],
    rarity: 'common',
    weight: 61,
    ageMin: 18,
    ageMax: 36,
    choices: [
      choice({
        id: 'reponse_prudente',
        label: 'Répondre de façon mesurée et collective',
        stance: 'prudent',
        riskPreview: 'Peu de buzz, peu de risque.',
        immediate: [fx.rel('media', 2), fx.rel('coach', 2)],
      }),
      choice({
        id: 'reponse_ambitieuse',
        label: 'Affirmer haut et fort que le titre reste l’objectif',
        stance: 'ambitious',
        riskPreview: 'Tu crées une attente énorme autour de toi.',
        immediate: [fx.rel('fans', 5), fx.res('popularite', 4)],
        delayed: [
          fx.delayed(2, [
            fx.debt('promesse_titre', 'Promesse médiatique sur le titre', 3),
          ]),
        ],
      }),
    ],
  }),

  dilemma({
    id: 'argent_investissement_conseil',
    title: 'Conseil d’investissement d’un coéquipier',
    body: 'Un coéquipier expérimenté te parle d’un placement « sans risque » lié à l’immobilier de luxe. Il veut que tu entres avec lui avant la trêve.',
    category: 'money',
    tags: ['investissement', 'confiance'],
    rarity: 'uncommon',
    weight: 47,
    ageMin: 21,
    ageMax: 40,
    choices: [
      choice({
        id: 'investir',
        label: 'Investir une part de tes économies',
        stance: 'financial',
        riskPreview: 'Gain possible, arnaque possible aussi.',
        immediate: [fx.cash(-12000)],
        delayed: [
          fx.delayed(3, [
            fx.chance(0.4, [fx.cash(20000)]),
            fx.chance(0.6, [fx.cash(-5000), fx.rel('teammates', -4)]),
          ]),
        ],
      }),
      choice({
        id: 'decliner',
        label: 'Décliner poliment et garder ton épargne',
        stance: 'prudent',
        riskPreview: 'Tu protèges ton argent, il se sent snobé.',
        immediate: [fx.rel('teammates', -2), fx.hidden('professionnalisme', 1)],
      }),
    ],
  }),

  dilemma({
    id: 'blessure_kinesitherapeute_prive',
    title: 'Kiné privé recommandé',
    body: 'Un kinésithérapeute indépendant te propose un protocole accéléré en marge du staff médical du club. Il garantit une reprise plus rapide, sans certificat officiel.',
    category: 'injury',
    tags: ['medical', 'reprise'],
    rarity: 'uncommon',
    weight: 49,
    ageMin: 19,
    ageMax: 37,
    choices: [
      choice({
        id: 'suivre_club',
        label: 'Refuser et suivre exclusivement le protocole du club',
        stance: 'loyal',
        riskPreview: 'Reprise plus lente, confiance staff intacte.',
        immediate: [fx.res('sante', 4), fx.res('confianceEntraineur', 3)],
        hidden: [fx.hidden('fragilitePhysique', -1)],
      }),
      choice({
        id: 'essayer_prive',
        label: 'Tester le protocole privé en secret',
        stance: 'high_risk',
        riskPreview: 'Gain de temps espéré, sanction si découvert.',
        immediate: [fx.res('sante', 6), fx.flag('kine_prive_utilise')],
        delayed: [
          fx.delayed(1, [
            fx.chance(0.5, [fx.res('forme', 6)]),
            fx.chance(0.5, [fx.res('confianceEntraineur', -8)]),
          ]),
        ],
      }),
    ],
  }),

  dilemma({
    id: 'famille_presence_match_loin',
    title: 'Match loin, famille en déplacement',
    body: 'Tes proches veulent te suivre pour un match à l’autre bout du pays. Le trajet coûte cher et tu as un rendez-vous médical important la veille.',
    category: 'family',
    tags: ['deplacement', 'soutien'],
    rarity: 'common',
    weight: 57,
    ageMin: 16,
    ageMax: 32,
    choices: [
      choice({
        id: 'inviter_famille',
        label: 'Leur payer le déplacement et les accueillir',
        stance: 'emotional',
        riskPreview: 'Soutien moral fort, fatigue et coût réels.',
        immediate: [fx.cash(-3000), fx.rel('family', 7), fx.res('moral', 5)],
        hidden: [fx.res('fatigue', 3)],
      }),
      choice({
        id: 'demander_rester',
        label: 'Leur demander de regarder à la télé cette fois',
        stance: 'prudent',
        riskPreview: 'Tu préserveras ton énergie, déception possible.',
        immediate: [fx.rel('family', -3), fx.res('fatigue', -4)],
      }),
    ],
  }),

  dilemma({
    id: 'style_vie_nutrition_extreme',
    title: 'Régime extrême avant les vacances',
    body: 'Un influenceur bien-être te propose un régime drastique pour « optimiser ta silhouette médiatique » avant les photos officielles de la saison.',
    category: 'lifestyle',
    tags: ['nutrition', 'image'],
    rarity: 'common',
    weight: 59,
    ageMin: 18,
    ageMax: 34,
    choices: [
      choice({
        id: 'suivre_regime',
        label: 'Suivre le régime pendant deux semaines',
        stance: 'ambitious',
        riskPreview: 'Tu minces vite, l’énergie peut chuter.',
        immediate: [fx.res('forme', -3), fx.res('popularite', 4)],
        delayed: [fx.delayed(1, [fx.res('sante', -4), fx.res('fatigue', 5)])],
      }),
      choice({
        id: 'refuser_nutritionniste',
        label: 'Refuser et consulter le nutritionniste du club',
        stance: 'prudent',
        riskPreview: 'Approche saine, moins spectaculaire.',
        immediate: [fx.res('sante', 3), fx.res('discipline', 2)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'mental_psychologue_propose',
    title: 'Séance avec le psychologue du club',
    body: 'Le staff te propose de rencontrer le psychologue sportif après une série de mauvaises performances. Certains coéquipiers rigolent en entendant le mot « mental ».',
    category: 'mental',
    tags: ['psychologie', 'forme'],
    rarity: 'common',
    weight: 60,
    ageMin: 17,
    ageMax: 38,
    choices: [
      choice({
        id: 'accepter_seance',
        label: 'Accepter deux séances confidentielles',
        stance: 'prudent',
        riskPreview: 'Tu travailles ta tête, rumeurs possibles.',
        immediate: [fx.res('moral', 6), fx.res('confianceEntraineur', 2)],
        delayed: [fx.delayed(2, [fx.hidden('resistancePression', 3)])],
      }),
      choice({
        id: 'refuser_seul',
        label: 'Refuser et affirmer que tu vas t’en sortir seul',
        stance: 'individualist',
        riskPreview: 'Fierté intacte, charge mentale inchangée.',
        immediate: [fx.res('moral', -2), fx.rel('teammates', 2)],
        hidden: [fx.hidden('constance', -1)],
      }),
    ],
  }),

  dilemma({
    id: 'sponsors_evenement_charite',
    title: 'Gala caritatif en pleine semaine de match',
    body: 'Ton sponsor principal organise un gala caritatif en soirée, trois jours avant un match crucial. Ta présence est « fortement souhaitée ».',
    category: 'sponsors',
    tags: ['charite', 'planning'],
    rarity: 'uncommon',
    weight: 46,
    ageMin: 20,
    ageMax: 38,
    choices: [
      choice({
        id: 'assister_gala',
        label: 'Assister au gala et tenir un discours court',
        stance: 'loyal',
        riskPreview: 'Tu honores ton sponsor, tu sacrifies du repos.',
        immediate: [fx.rel('sponsors', 6), fx.res('fatigue', 6)],
        delayed: [fx.delayed(1, [fx.res('forme', -3)])],
      }),
      choice({
        id: 'decliner_gala',
        label: 'Décliner pour te concentrer sur le match',
        stance: 'prudent',
        riskPreview: 'Tu protèges ta performance, contrat tendu.',
        immediate: [fx.rel('sponsors', -5), fx.res('forme', 3)],
        hidden: [fx.res('confianceEntraineur', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'supporters_critique_apres_defaite',
    title: 'Huées après la défaite',
    body: 'Les supporters scandent ton nom en huant après une défaite à domicile. Tu passes devant eux pour rentrer aux vestiaires, seul, sans staff.',
    category: 'fans',
    tags: ['defaite', 'pression'],
    rarity: 'common',
    weight: 67,
    ageMin: 18,
    ageMax: 40,
    choices: [
      choice({
        id: 'saluer_malgré_tout',
        label: 'Lever la main en signe de reconnaissance',
        stance: 'ethical',
        riskPreview: 'Tu montres du respect, pas forcément compris.',
        immediate: [fx.rel('fans', 3), fx.res('moral', -3)],
        hidden: [fx.hidden('resistancePression', 2)],
      }),
      choice({
        id: 'passer_vite',
        label: 'Baisser la tête et accélérer le pas',
        stance: 'individualist',
        riskPreview: 'Tu te protèges, la relation avec les fans se tend.',
        immediate: [fx.rel('fans', -5), fx.res('moral', -5)],
        delayed: [fx.delayed(1, [fx.res('popularite', -4)])],
      }),
    ],
  }),

  dilemma({
    id: 'contrat_clause_relegation',
    title: 'Clause en cas de relégation',
    body: 'Le club te propose une extension avec une clause de départ facilitée si l’équipe descend. C’est une sécurité pour toi, un signal d’alarme pour les supporters.',
    category: 'contract',
    tags: ['clause', 'avenir'],
    rarity: 'uncommon',
    weight: 51,
    ageMin: 21,
    ageMax: 35,
    choices: [
      choice({
        id: 'signer_clause',
        label: 'Signer avec la clause de sortie',
        stance: 'financial',
        riskPreview: 'Tu sécurises ton avenir, le message public est froid.',
        immediate: [fx.cash(5000), fx.rel('fans', -4)],
        hidden: [fx.hidden('ambition', 2)],
      }),
      choice({
        id: 'refuser_clause',
        label: 'Refuser la clause et parier sur le maintien',
        stance: 'loyal',
        riskPreview: 'Tu envoies un signal fort, tu restes exposé.',
        immediate: [fx.rel('fans', 6), fx.rel('coach', 3)],
        delayed: [fx.delayed(2, [fx.res('reputationSportive', 3)])],
      }),
    ],
  }),

  dilemma({
    id: 'transfer_visite_discrete',
    title: 'Visite discrète d’un recruteur',
    body: 'Un recruteur te contacte pour une visite privée de leurs installations pendant la trêve. Personne au club n’est au courant pour l’instant.',
    category: 'transfer',
    tags: ['recruteur', 'discretion'],
    rarity: 'uncommon',
    weight: 43,
    ageMin: 20,
    ageMax: 36,
    choices: [
      choice({
        id: 'visite_secrete',
        label: 'Accepter la visite en solo',
        stance: 'ambitious',
        riskPreview: 'Tu explores une porte, fuite possible.',
        immediate: [fx.flag('visite_recruteur')],
        delayed: [
          fx.delayed(1, [
            fx.chance(0.4, [fx.res('reputationSportive', 5)]),
            fx.chance(0.6, [fx.res('confianceEntraineur', -5)]),
          ]),
        ],
      }),
      choice({
        id: 'informer_club',
        label: 'Informer ton directeur sportif avant toute démarche',
        stance: 'loyal',
        riskPreview: 'Transparence totale, options réduites.',
        immediate: [fx.rel('coach', 4), fx.res('confianceEntraineur', 5)],
        hidden: [fx.hidden('loyaute', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'entrainement_punition_collective',
    title: 'Punition collective après élimination',
    body: 'Après une élimination en coupe, l’entraîneur impose un footing punitif à toute l’équipe. Tu as déjà accumulé beaucoup de minutes et sens tes jambes lourdes.',
    category: 'training',
    tags: ['fatigue', 'collectif'],
    rarity: 'common',
    weight: 69,
    ageMin: 18,
    ageMax: 38,
    choices: [
      choice({
        id: 'subir_collective',
        label: 'Encaisser la séance sans te plaindre',
        stance: 'loyal',
        riskPreview: 'Tu montres l’exemple, tu payes physiquement.',
        immediate: [fx.res('fatigue', 10), fx.res('cohesionVestiaire', 4)],
        hidden: [fx.res('sante', -3)],
      }),
      choice({
        id: 'demander_alternatif',
        label: 'Demander un travail alternatif au préparateur',
        stance: 'individualist',
        riskPreview: 'Tu protèges ton corps, tu passes pour fragile.',
        immediate: [fx.res('fatigue', 2), fx.rel('coach', -3)],
        delayed: [fx.delayed(1, [fx.res('forme', 4)])],
      }),
    ],
  }),

  dilemma({
    id: 'coach_conflit_adjoint',
    title: 'Conflit entre entraîneur et adjoint',
    body: 'Tu surprends une dispute vive entre l’entraîneur principal et son adjoint à propos de ton temps de jeu. Ils se taisent en te voyant.',
    category: 'coach',
    tags: ['staff', 'temps_jeu'],
    rarity: 'uncommon',
    weight: 48,
    ageMin: 19,
    ageMax: 35,
    choices: [
      choice({
        id: 'faire_semblant',
        label: 'Faire semblant de n’avoir rien entendu',
        stance: 'prudent',
        riskPreview: 'Tu évites le drama, tu restes dans le flou.',
        immediate: [fx.res('confianceEntraineur', 0)],
        hidden: [fx.hidden('resistancePression', 1)],
      }),
      choice({
        id: 'demander_clarte',
        label: 'Demander une explication claire sur ton rôle',
        stance: 'ambitious',
        riskPreview: 'Tu forces une réponse, tu prends des risques politiques.',
        immediate: [fx.rel('coach', -2)],
        delayed: [
          fx.delayed(1, [
            fx.skillCheck('hidden', 'ambition', 60, [
              fx.res('confianceEntraineur', 5),
            ], [fx.res('cohesionVestiaire', -4)]),
          ]),
        ],
      }),
    ],
  }),
]
