import type { DilemmaDefinition } from '../../game-engine/dilemmas'
import { choice, dilemma, fx } from './helpers'

/** Exactement 10 événements rares ou légendaires. */
export const rareDilemmas: DilemmaDefinition[] = [
  dilemma({
    id: 'rare_agent_douteux_offre',
    title: 'Offre en liquide sans trace',
    body: 'Un intermédiaire inconnu te propose une prime en liquide pour « faciliter » un transfert vers un club étranger. Aucun contrat écrit, juste une mallette et un sourire.',
    category: 'agent',
    tags: ['rare', 'corruption', 'transfer'],
    rarity: 'legendary',
    weight: 8,
    unique: true,
    ageMin: 20,
    ageMax: 36,
    choices: [
      choice({
        id: 'refuser_signaler',
        label: 'Refuser et alerter le compliance officer du club',
        stance: 'ethical',
        riskPreview: 'Tu te mets à l’abri juridiquement.',
        immediate: [fx.rel('coach', 5), fx.hidden('professionnalisme', 3)],
        hidden: [fx.flag('agent_douteux_refuse')],
      }),
      choice({
        id: 'ecouter_sans_engager',
        label: 'Écouter les détails sans t’engager',
        stance: 'high_risk',
        riskPreview: 'Information ou piège — difficile à savoir.',
        immediate: [fx.flag('agent_douteux_contact')],
        delayed: [
          fx.delayed(1, [
            fx.chance(0.3, [fx.cash(50000)]),
            fx.chance(0.7, [fx.res('discipline', -15), fx.res('reputationSportive', -10)]),
          ]),
        ],
      }),
    ],
  }),

  dilemma({
    id: 'rare_rivalite_declaree',
    title: 'Déclaration de rivalité publique',
    body: 'Un joueur star d’un rival régional te provoque en direct sur les réseaux sociaux, t’accusant de « te cacher derrière ton équipe ». La polémique explose avant le derby.',
    category: 'media',
    tags: ['rare', 'rivalite', 'derby'],
    rarity: 'rare',
    weight: 15,
    unique: true,
    ageMin: 19,
    ageMax: 35,
    choices: [
      choice({
        id: 'repondre_pique',
        label: 'Répondre par une pique ciblée sur ses statistiques',
        stance: 'individualist',
        riskPreview: 'Buzz garanti, pression décuplée.',
        immediate: [fx.rel('media', 8), fx.res('popularite', 6)],
        delayed: [fx.delayed(1, [fx.debt('rivalite_derby', 'Rivalité médiatique avant derby', 2)])],
        hidden: [fx.flag('rivalite_publique'), fx.queue('chain_media_storm_01', 0)],
      }),
      choice({
        id: 'ignorer',
        label: 'Ignorer et laisser le club communiquer',
        stance: 'prudent',
        riskPreview: 'Tu évites l’escalade, certains te trouvent timide.',
        immediate: [fx.rel('coach', 3), fx.res('discipline', 3)],
        hidden: [fx.hidden('resistancePression', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'rare_promesse_club_secrete',
    title: 'Promesse secrète du président',
    body: 'Le président du club te reçoit en privé et te promet verbalement un renouvellement XXL si tu refuses toute négociation avec d’autres clubs cette saison.',
    category: 'contract',
    tags: ['rare', 'promesse', 'president'],
    rarity: 'rare',
    weight: 12,
    unique: true,
    ageMin: 21,
    ageMax: 34,
    choices: [
      choice({
        id: 'croire_promesse',
        label: 'Accepter la promesse et refuser tout contact externe',
        stance: 'loyal',
        riskPreview: 'Engagement moral fort, preuve faible.',
        immediate: [fx.flag('promesse_president'), fx.rel('coach', 4)],
        nextEventIds: ['chain_transfer_promise_01'],
        hidden: [fx.debt('promesse_verbal', 'Promesse verbale du président', 3)],
      }),
      choice({
        id: 'exiger_ecrit',
        label: 'Exiger une clause écrite avant de t’engager',
        stance: 'prudent',
        riskPreview: 'Tu sécurises, le président peut se vexer.',
        immediate: [fx.rel('coach', -2), fx.hidden('professionnalisme', 2)],
        delayed: [
          fx.delayed(2, [
            fx.chance(0.4, [fx.cash(20000)]),
            fx.chance(0.6, [fx.res('confianceEntraineur', -5)]),
          ]),
        ],
      }),
    ],
  }),

  dilemma({
    id: 'rare_soiree_mediatisee',
    title: 'Soirée VIP filmée en secret',
    body: 'Tu es invité à une soirée VIP où des influenceurs filment en continu. L’organisateur te glisse qu’une marque veut un contrat « spontané » capté sur le vif.',
    category: 'lifestyle',
    tags: ['rare', 'soiree', 'media'],
    rarity: 'rare',
    weight: 14,
    unique: true,
    ageMin: 20,
    ageMax: 32,
    choices: [
      choice({
        id: 'participer_filme',
        label: 'Participer et improviser une séquence pour la marque',
        stance: 'financial',
        riskPreview: 'Exposition maximale, image incontrôlable.',
        immediate: [fx.res('popularite', 8), fx.res('fatigue', 5)],
        delayed: [
          fx.delayed(1, [
            fx.chance(0.5, [fx.cash(18000)]),
            fx.chance(0.5, [fx.res('discipline', -8), fx.rel('coach', -5)]),
          ]),
        ],
      }),
      choice({
        id: 'quitter_tot',
        label: 'Quitter dès que tu comprends le piège médiatique',
        stance: 'prudent',
        riskPreview: 'Tu protèges ton image, tu brûles des contacts.',
        immediate: [fx.rel('sponsors', -4), fx.res('discipline', 4)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'rare_choix_medical_agressif',
    title: 'Injection avant match crucial',
    body: 'Un médecin non affilié au club te propose une injection pour jouer un match décisif alors que tu peines à marcher normalement. Le staff officiel n’est pas informé.',
    category: 'injury',
    tags: ['rare', 'medical', 'risque'],
    rarity: 'legendary',
    weight: 6,
    unique: true,
    ageMin: 22,
    ageMax: 38,
    choices: [
      choice({
        id: 'refuser_injection',
        label: 'Refuser et suivre uniquement le staff du club',
        stance: 'ethical',
        riskPreview: 'Tu manques peut-être le match, tu protèges ton corps.',
        immediate: [fx.res('sante', 5), fx.rel('coach', 2)],
        hidden: [fx.hidden('professionnalisme', 3)],
      }),
      choice({
        id: 'accepter_injection',
        label: 'Accepter l’injection en secret',
        stance: 'high_risk',
        riskPreview: 'Tu joues, les conséquences peuvent être lourdes.',
        immediate: [fx.res('forme', 10), fx.flag('injection_secrete')],
        nextEventIds: ['chain_injury_gamble_01'],
        hidden: [fx.res('sante', -8)],
      }),
    ],
  }),

  dilemma({
    id: 'rare_scandale_fuite_doping',
    title: 'Fuite sur contrôle antidopage',
    body: 'Un journaliste te contacte en privé : il prétient détenir une info sur un contrôle antidopage interne au club. Il te demande un commentaire avant publication.',
    category: 'media',
    tags: ['rare', 'doping', 'fuite'],
    rarity: 'legendary',
    weight: 7,
    unique: true,
    ageMin: 20,
    ageMax: 40,
    choices: [
      choice({
        id: 'denoncer_club',
        label: 'Exiger une enquête transparente via ton avocat',
        stance: 'ethical',
        riskPreview: 'Tu assumes une crise majeure.',
        immediate: [fx.rel('media', 5), fx.res('reputationSportive', -5)],
        delayed: [fx.delayed(2, [fx.res('reputationSportive', 8)])],
      }),
      choice({
        id: 'garder_silence',
        label: 'Ne pas commenter et laisser le club gérer',
        stance: 'prudent',
        riskPreview: 'Tu évites le front, suspicion possible.',
        immediate: [fx.rel('coach', 3), fx.res('moral', -4)],
        hidden: [fx.hidden('resistancePression', -2)],
      }),
    ],
  }),

  dilemma({
    id: 'rare_proposition_fixing',
    title: 'Approche suspecte avant match',
    body: 'Un inconnu te contacte par message chiffré et évoque une « contribution » pour un match précis. Il insiste : personne ne le saura.',
    category: 'match',
    tags: ['rare', 'integrite', 'scandale'],
    rarity: 'legendary',
    weight: 5,
    unique: true,
    ageMin: 21,
    ageMax: 38,
    choices: [
      choice({
        id: 'signaler_autorites',
        label: 'Transmettre les messages aux autorités du sport',
        stance: 'ethical',
        riskPreview: 'Tu déclenches une enquête, tu es protégé.',
        immediate: [fx.flag('fixing_signale'), fx.hidden('professionnalisme', 4)],
        hidden: [fx.res('moral', 3)],
      }),
      choice({
        id: 'bloquer_ignorer',
        label: 'Bloquer le numéro sans en parler',
        stance: 'prudent',
        riskPreview: 'Discret, mais le réseau peut revenir.',
        immediate: [fx.res('moral', -3)],
        delayed: [
          fx.delayed(3, [
            fx.chance(0.2, [fx.cash(-20000), fx.res('discipline', -20)]),
          ]),
        ],
      }),
    ],
  }),

  dilemma({
    id: 'rare_documentaire_intime',
    title: 'Documentaire intime proposé',
    body: 'Une plateforme de streaming propose un documentaire suivant ta vie privée pendant six mois. L’accès à ta famille et ton appartement serait total.',
    category: 'media',
    tags: ['rare', 'documentaire', 'vie_privee'],
    rarity: 'rare',
    weight: 13,
    unique: true,
    ageMin: 22,
    ageMax: 35,
    prerequisites: [{ type: 'minResource', id: 'popularite', value: 75 }],
    choices: [
      choice({
        id: 'accepter_docu',
        label: 'Accepter avec contrôle éditorial limité',
        stance: 'financial',
        riskPreview: 'Fortune et exposition de ton intimité.',
        immediate: [fx.cash(80000), fx.res('popularite', 10)],
        delayed: [
          fx.delayed(2, [
            fx.chance(0.55, [fx.rel('family', -6)]),
            fx.chance(0.45, [fx.rel('fans', 8)]),
          ]),
        ],
      }),
      choice({
        id: 'refuser_docu',
        label: 'Refuser pour protéger ta sphère privée',
        stance: 'prudent',
        riskPreview: 'Tu gardes ta vie privée, tu passes à côté d’un contrat.',
        immediate: [fx.rel('family', 4), fx.res('bienEtre', 5)],
        hidden: [fx.hidden('resistancePression', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'rare_mecene_investisseur',
    title: 'Mécène prêt à acheter ton club',
    body: 'Un investisseur te confie qu’il envisage de racheter ton club si tu l’introduis au vestiaire et aux décideurs. Il promet un projet sportif ambitieux.',
    category: 'transfer',
    tags: ['rare', 'investisseur', 'politique'],
    rarity: 'rare',
    weight: 11,
    unique: true,
    ageMin: 24,
    ageMax: 38,
    prerequisites: [{ type: 'minResource', id: 'reputationSportive', value: 78 }],
    choices: [
      choice({
        id: 'faciliter_rencontre',
        label: 'Organiser une rencontre discrète avec le président',
        stance: 'ambitious',
        riskPreview: 'Tu deviens acteur politique du club.',
        immediate: [fx.flag('mecene_introduit')],
        delayed: [
          fx.delayed(2, [
            fx.chance(0.45, [fx.cash(30000), fx.res('reputationSportive', 5)]),
            fx.chance(0.55, [fx.res('confianceEntraineur', -8)]),
          ]),
        ],
      }),
      choice({
        id: 'refuser_intermediation',
        label: 'Refuser d’être intermédiaire et rester joueur',
        stance: 'ethical',
        riskPreview: 'Tu évites le conflit d’intérêts.',
        immediate: [fx.hidden('professionnalisme', 3), fx.rel('coach', 3)],
      }),
    ],
  }),

  dilemma({
    id: 'rare_hommage_legende_vivante',
    title: 'Comparaison avec une légende locale',
    body: 'La presse te compare ouvertement à une légende du club encore vivante. Elle te convie à un déjeuner privé pour « te donner un conseil » — ou te mettre à ta place.',
    category: 'narrative_chain',
    tags: ['rare', 'legacy', 'legende'],
    rarity: 'legendary',
    weight: 9,
    unique: true,
    ageMin: 23,
    ageMax: 36,
    prerequisites: [{ type: 'minResource', id: 'reputationSportive', value: 82 }],
    choices: [
      choice({
        id: 'accepter_dejeuner',
        label: 'Accepter le déjeuner et écouter ses conseils',
        stance: 'loyal',
        riskPreview: 'Tu entres dans une dynastie, pas sans pression.',
        immediate: [fx.rel('fans', 6), fx.res('popularite', 5)],
        nextEventIds: ['chain_legacy_01'],
        hidden: [fx.hidden('grandsMatchs', 2)],
      }),
      choice({
        id: 'decliner_comparaison',
        label: 'Décliner poliment et refuser la comparaison publique',
        stance: 'individualist',
        riskPreview: 'Tu te construis ton propre récit.',
        immediate: [fx.res('moral', 3), fx.rel('media', -2)],
        hidden: [fx.hidden('ambition', 2)],
      }),
    ],
  }),
]
