import type { DilemmaDefinition } from '../../game-engine/dilemmas'
import { choice, dilemma, fx } from './helpers'

export const roleSpecificDilemmas: DilemmaDefinition[] = [
  // ——— Gardiens (≥4) ———
  dilemma({
    id: 'gk_sortie_aerienne_doute',
    title: 'Sortie aérienne contestée',
    body: 'Sur un corner, tu hésites entre rester sur ta ligne ou venir boxe le ballon au premier poteau. L’entraîneur des gardiens t’a pourtant répété la consigne hier.',
    category: 'match',
    tags: ['gardien', 'aerien'],
    rarity: 'common',
    weight: 55,
    ageMin: 17,
    ageMax: 38,
    positions: ['gk'],
    choices: [
      choice({
        id: 'sortir_boxer',
        label: 'Sortir agressivement pour boxe le ballon',
        stance: 'ambitious',
        riskPreview: 'Tu imposes ta présence, collision possible.',
        immediate: [fx.stat('puissance', 1)],
        hidden: [
          fx.skillCheck('stat', 'placement', 58, [
            fx.res('reputationSportive', 5),
            fx.rel('teammates', 3),
          ], [fx.res('moral', -6), fx.res('confianceEntraineur', -3)]),
        ],
      }),
      choice({
        id: 'rester_ligne',
        label: 'Rester sur ta ligne et organiser la défense',
        stance: 'prudent',
        riskPreview: 'Décision sage ou timide selon le dénouement.',
        immediate: [fx.stat('tactique', 1), fx.res('discipline', 2)],
        delayed: [fx.delayed(1, [fx.res('confianceEntraineur', 2)])],
      }),
    ],
  }),

  dilemma({
    id: 'gk_relance_risquee',
    title: 'Relance courte sous pressing',
    body: 'L’adversaire presse ton défenseur central au moment de la relance. Tu peux lui renvoyer le ballon ou tenter une passe longue directe vers l’ailier.',
    category: 'match',
    tags: ['gardien', 'relance'],
    rarity: 'uncommon',
    weight: 48,
    ageMin: 18,
    ageMax: 36,
    positions: ['gk'],
    choices: [
      choice({
        id: 'passe_longue',
        label: 'Tenter la passe longue en first time',
        stance: 'high_risk',
        riskPreview: 'Tu lances le contre ou offres une occasion.',
        immediate: [fx.stat('passe', 2)],
        hidden: [
          fx.chance(0.45, [fx.res('reputationSportive', 6)]),
          fx.chance(0.55, [fx.res('moral', -5)]),
        ],
      }),
      choice({
        id: 'degagement_securite',
        label: 'Dégager en touche pour respirer',
        stance: 'prudent',
        riskPreview: 'Tu sécurises, tu cèdes le ballon.',
        immediate: [fx.res('discipline', 3), fx.rel('coach', 2)],
        hidden: [fx.hidden('constance', 1)],
      }),
    ],
  }),

  dilemma({
    id: 'gk_penalty_adversaire',
    title: 'Penalty adverse à arrêter',
    body: 'L’arbitre siffle un penalty contre ton équipe en fin de match. Le tireur est réputé pour regarder le gardien avant de frapper. Le banc te crie des consignes contradictoires.',
    category: 'match',
    tags: ['gardien', 'penalty'],
    rarity: 'uncommon',
    weight: 42,
    ageMin: 19,
    ageMax: 40,
    positions: ['gk'],
    choices: [
      choice({
        id: 'provocation_ligne',
        label: 'Reste sur ta ligne et provoque le tireur du regard',
        stance: 'ambitious',
        riskPreview: 'Mind games — double tranchant.',
        immediate: [fx.stat('sangFroid', 1)],
        hidden: [
          fx.skillCheck('stat', 'sangFroid', 62, [
            fx.res('reputationSportive', 8),
            fx.rel('teammates', 5),
          ], [fx.res('moral', -7)]),
        ],
      }),
      choice({
        id: 'plongeon_anticipe',
        label: 'Anticiper en plongeant tôt d’un côté',
        stance: 'high_risk',
        riskPreview: 'Héros ou victime en une seconde.',
        immediate: [],
        hidden: [
          fx.chance(0.35, [fx.res('popularite', 7)]),
          fx.chance(0.65, [fx.res('confianceEntraineur', -4)]),
        ],
      }),
    ],
  }),

  dilemma({
    id: 'gk_concentration_banc',
    title: 'Concurrence au poste',
    body: 'Le club recrute un gardien expérimenté en renfort. Il s’entraîne avec toi et pose des questions sur tes habitudes de pré-match.',
    category: 'training',
    tags: ['gardien', 'concurrence'],
    rarity: 'common',
    weight: 52,
    ageMin: 18,
    ageMax: 34,
    positions: ['gk'],
    choices: [
      choice({
        id: 'partager_conseils',
        label: 'Partager ouvertement tes routines',
        stance: 'loyal',
        riskPreview: 'Esprit d’équipe, avantage rival possible.',
        immediate: [fx.rel('teammates', 4), fx.res('cohesionVestiaire', 3)],
        hidden: [fx.hidden('loyaute', 2)],
      }),
      choice({
        id: 'garder_secrets',
        label: 'Rester vague sur tes préférences tactiques',
        stance: 'individualist',
        riskPreview: 'Tu protèges ta place, ambiance tendue.',
        immediate: [fx.res('moral', 3), fx.rel('teammates', -2)],
        delayed: [fx.delayed(1, [fx.res('confianceEntraineur', -2)])],
      }),
    ],
  }),

  dilemma({
    id: 'gk_communication_defense',
    title: 'Consigne ignorée en défense',
    body: 'Tu cries à ton défenseur central de reculer sur une balle en profondeur. Il n’écoute pas et l’adversaire part seul. Tu dois décider quoi faire après le coup.',
    category: 'teammates',
    tags: ['gardien', 'communication'],
    rarity: 'common',
    weight: 50,
    ageMin: 17,
    ageMax: 38,
    positions: ['gk'],
    choices: [
      choice({
        id: 'confronter_vestiaire',
        label: 'Lui rappeler fermement ses responsabilités au vestiaire',
        stance: 'ambitious',
        riskPreview: 'Autorité affirmée, friction possible.',
        immediate: [fx.stat('leadership', 2), fx.rel('teammates', -2)],
        hidden: [fx.res('cohesionVestiaire', -3)],
      }),
      choice({
        id: 'laisser_passer',
        label: 'Laisser passer et en parler calmement plus tard',
        stance: 'prudent',
        riskPreview: 'Tu évites l’explosion, le problème persiste.',
        immediate: [fx.rel('teammates', 2), fx.res('discipline', 1)],
        delayed: [fx.delayed(2, [fx.res('confianceEntraineur', 2)])],
      }),
    ],
  }),

  // ——— Remplaçants / banc (≥3) ———
  dilemma({
    id: 'bench_patient_attente',
    title: 'Saison sur le banc',
    body: 'Tu n’as joué que quelques bribes cette saison. Un coéquipier te propose de demander un prêt en conférence de presse « par accident » pour forcer la main du club.',
    category: 'teammates',
    tags: ['banc', 'temps_jeu'],
    rarity: 'common',
    weight: 58,
    ageMin: 17,
    ageMax: 30,
    prerequisites: [{ type: 'maxMinutesLastSeason', value: 600 }],
    choices: [
      choice({
        id: 'refuser_manipulation',
        label: 'Refuser cette tactique et parler au coach en privé',
        stance: 'prudent',
        riskPreview: 'Approche directe, réponse incertaine.',
        immediate: [fx.rel('coach', 2)],
        delayed: [
          fx.delayed(1, [
            fx.skillCheck('hidden', 'professionnalisme', 55, [
              fx.res('confianceEntraineur', 5),
            ], [fx.res('moral', -5)]),
          ]),
        ],
      }),
      choice({
        id: 'laisser_rumeur',
        label: 'Laisser filtrer l’idée sans la confirmer',
        stance: 'individualist',
        riskPreview: 'Pression sur le club, réputation entachée.',
        immediate: [fx.flag('rumeur_pret_banc')],
        delayed: [
          fx.delayed(1, [
            fx.chance(0.4, [fx.res('reputationSportive', 3)]),
            fx.chance(0.6, [fx.rel('coach', -6)]),
          ]),
        ],
      }),
    ],
  }),

  dilemma({
    id: 'bench_entrainement_extra',
    title: 'Entraînement après le groupe',
    body: 'Comme tu joues peu, le préparateur te propose des séances supplémentaires après l’équipe. Les titulaires regardent avec un mélange d’admiration et de moquerie.',
    category: 'training',
    tags: ['banc', 'effort'],
    rarity: 'common',
    weight: 62,
    ageMin: 16,
    ageMax: 28,
    prerequisites: [{ type: 'maxMinutesLastSeason', value: 600 }],
    choices: [
      choice({
        id: 'doubler_seances',
        label: 'Accepter toutes les séances proposées',
        stance: 'ambitious',
        riskPreview: 'Tu progresses, tu t’épuises peut-être.',
        immediate: [fx.res('fatigue', 8), fx.stat('technique', 2)],
        delayed: [fx.delayed(2, [fx.res('forme', 5), fx.res('confianceEntraineur', 4)])],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
      choice({
        id: 'limiter_charge',
        label: 'N’en prendre qu’une par semaine pour rester frais',
        stance: 'prudent',
        riskPreview: 'Rythme soutenable, progression lente.',
        immediate: [fx.res('fatigue', 3), fx.stat('technique', 1)],
      }),
    ],
  }),

  dilemma({
    id: 'bench_substitution_decisive',
    title: 'Entrée en jeu décisive',
    body: 'Tu entres à la 85e minute pour ton premier vrai temps de jeu depuis des semaines. Le score est nul et l’entraîneur te dit simplement : « Fais la différence. »',
    category: 'match',
    tags: ['banc', 'substitution'],
    rarity: 'uncommon',
    weight: 45,
    ageMin: 17,
    ageMax: 32,
    prerequisites: [{ type: 'maxMinutesLastSeason', value: 600 }],
    choices: [
      choice({
        id: 'jouer_simple',
        label: 'Jouer simple, tenir le ballon et sécuriser',
        stance: 'prudent',
        riskPreview: 'Peu de risque, peu de gloire.',
        immediate: [fx.res('confianceEntraineur', 3), fx.stat('controle', 1)],
      }),
      choice({
        id: 'tenter_tout',
        label: 'Tenter le geste décisif dès ta première touche',
        stance: 'high_risk',
        riskPreview: 'Tu peux devenir héros ou bouc émissaire.',
        immediate: [fx.res('moral', 4)],
        hidden: [
          fx.skillCheck('stat', 'finition', 52, [
            fx.res('reputationSportive', 7),
            fx.res('confianceEntraineur', 6),
          ], [fx.res('moral', -8)]),
        ],
      }),
    ],
  }),

  dilemma({
    id: 'bench_agent_pression_pret',
    title: 'Agent exige un prêt',
    body: 'Ton agent menace d’aller en parler à la presse si tu n’obtiens pas plus de minutes. Tu es clairement derrière dans la hiérarchie du poste.',
    category: 'agent',
    tags: ['banc', 'agent'],
    rarity: 'uncommon',
    weight: 40,
    ageMin: 18,
    ageMax: 29,
    prerequisites: [
      { type: 'maxMinutesLastSeason', value: 600 },
      { type: 'hasFlag', key: 'rumeur_pret_banc' },
    ],
    exclusions: [{ type: 'minMinutesLastSeason', value: 900 }],
    choices: [
      choice({
        id: 'calmer_agent',
        label: 'Demander à ton agent de temporiser encore une saison',
        stance: 'loyal',
        riskPreview: 'Tu restes, la frustration grandit.',
        immediate: [fx.rel('coach', 3), fx.res('moral', -4)],
        hidden: [fx.hidden('loyaute', 2)],
      }),
      choice({
        id: 'exiger_pret',
        label: 'Exiger officiellement un prêt à la trêve',
        stance: 'ambitious',
        riskPreview: 'Tu forces une issue, le club peut se fermer.',
        immediate: [fx.rel('coach', -5), fx.flag('demande_pret_officielle')],
        delayed: [fx.delayed(2, [fx.res('reputationSportive', 4)])],
      }),
    ],
  }),

  // ——— Stars (≥3) ———
  dilemma({
    id: 'star_poids_epaules',
    title: 'Attentes démesurées',
    body: 'Ta réputation dépasse celle de plusieurs cadres. Le président te demande personnellement de « porter le projet » lors d’un dîner privé avec des investisseurs.',
    category: 'media',
    tags: ['star', 'pression'],
    rarity: 'uncommon',
    weight: 38,
    ageMin: 22,
    ageMax: 38,
    prerequisites: [{ type: 'minResource', id: 'reputationSportive', value: 75 }],
    choices: [
      choice({
        id: 'accepter_role',
        label: 'Accepter ce rôle de figure emblématique',
        stance: 'ambitious',
        riskPreview: 'Visibilité maximale, responsabilité accrue.',
        immediate: [fx.res('popularite', 6), fx.res('reputationSportive', 3)],
        delayed: [fx.delayed(2, [fx.debt('star_porteur', 'Promesse de porter le projet', 4)])],
        hidden: [fx.hidden('resistancePression', -1)],
      }),
      choice({
        id: 'partager_gloire',
        label: 'Insister sur le caractère collectif du projet',
        stance: 'loyal',
        riskPreview: 'Tu dilues ta starification, le staff apprécie.',
        immediate: [fx.res('cohesionVestiaire', 5), fx.rel('teammates', 4)],
        hidden: [fx.hidden('loyaute', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'star_marque_personnelle',
    title: 'Lancement de marque personnelle',
    body: 'Une agence te propose de lancer ta propre marque de vêtements avant la reprise. Le calendrier promotionnel chevauche la pré-saison.',
    category: 'sponsors',
    tags: ['star', 'marque'],
    rarity: 'uncommon',
    weight: 35,
    ageMin: 21,
    ageMax: 36,
    prerequisites: [{ type: 'minResource', id: 'popularite', value: 78 }],
    choices: [
      choice({
        id: 'lancer_marque',
        label: 'Lancer la marque avec une campagne agressive',
        stance: 'financial',
        riskPreview: 'Revenus et fatigue médiatique.',
        immediate: [fx.cash(25000), fx.res('fatigue', 6)],
        delayed: [fx.delayed(1, [fx.res('forme', -4), fx.res('popularite', 5)])],
      }),
      choice({
        id: 'reporter_lancement',
        label: 'Reporter le lancement après la pré-saison',
        stance: 'prudent',
        riskPreview: 'Tu privilégies le sport, l’agence déçue.',
        immediate: [fx.rel('sponsors', -3), fx.res('forme', 3)],
        hidden: [fx.hidden('professionnalisme', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'star_conflit_coequipier',
    title: 'Jalousie dans le vestiaire',
    body: 'Un coéquipier titulaire te reproche d’accaparer les interviews après les matchs. Il t’envoie un message vocal agressif la veille d’un match à enjeu.',
    category: 'teammates',
    tags: ['star', 'vestiaire'],
    rarity: 'common',
    weight: 42,
    ageMin: 20,
    ageMax: 37,
    prerequisites: [
      { type: 'minResource', id: 'reputationSportive', value: 72 },
      { type: 'minResource', id: 'popularite', value: 70 },
    ],
    choices: [
      choice({
        id: 'mediation',
        label: 'Proposer une médiation avec le capitaine',
        stance: 'ethical',
        riskPreview: 'Tu désamorces, tu montres de la maturité.',
        immediate: [fx.rel('teammates', 3), fx.res('cohesionVestiaire', 4)],
        hidden: [fx.stat('leadership', 2)],
      }),
      choice({
        id: 'repondre_dur',
        label: 'Répondre sèchement que tu gagnes tes interviews sur le terrain',
        stance: 'individualist',
        riskPreview: 'Tu affirmes ta place, la tension monte.',
        immediate: [fx.rel('teammates', -5), fx.res('moral', 3)],
        delayed: [fx.delayed(1, [fx.res('cohesionVestiaire', -6)])],
      }),
    ],
  }),

  dilemma({
    id: 'star_prix_individuel',
    title: 'Prix individuel vs titre collectif',
    body: 'Tu es nommé pour un trophée individuel national alors que ton équipe lutte pour le maintien. La cérémonie tombe la veille d’un match décisif.',
    category: 'media',
    tags: ['star', 'trophee'],
    rarity: 'uncommon',
    weight: 36,
    ageMin: 22,
    ageMax: 38,
    prerequisites: [{ type: 'minResource', id: 'reputationSportive', value: 80 }],
    choices: [
      choice({
        id: 'assister_gala',
        label: 'Assister à la cérémonie et revenir la nuit même',
        stance: 'ambitious',
        riskPreview: 'Gloire personnelle, jambes lourdes.',
        immediate: [fx.res('popularite', 8), fx.res('fatigue', 10)],
        delayed: [fx.delayed(1, [fx.res('forme', -5)])],
      }),
      choice({
        id: 'decliner_gala',
        label: 'Décliner l’invitation pour rester avec l’équipe',
        stance: 'loyal',
        riskPreview: 'Tu sacrifies une vitrine, tu gagnes le vestiaire.',
        immediate: [fx.rel('teammates', 6), fx.res('cohesionVestiaire', 5)],
        hidden: [fx.hidden('loyaute', 3)],
      }),
    ],
  }),

  // ——— Fin de carrière (≥3) ———
  dilemma({
    id: 'fin_carriere_proposition_staff',
    title: 'Proposition de rejoindre le staff',
    body: 'Avec l’âge qui avance, le club te propose un rôle dans l’encadrement des jeunes à partir de la saison prochaine. Tu sens encore que ton corps peut tenir un an de haut niveau.',
    category: 'career_end',
    tags: ['retraite', 'staff'],
    rarity: 'uncommon',
    weight: 32,
    ageMin: 34,
    ageMax: 40,
    careerStages: ['declin', 'fin_contrat', 'retraite'],
    choices: [
      choice({
        id: 'accepter_staff',
        label: 'Accepter la transition vers le staff',
        stance: 'prudent',
        riskPreview: 'Avenir sécurisé, carrière joueur raccourcie.',
        immediate: [fx.flag('transition_staff_acceptee'), fx.res('bienEtre', 5)],
        delayed: [fx.delayed(2, [fx.res('reputationSportive', 3)])],
      }),
      choice({
        id: 'prolonger_joueur',
        label: 'Demander une dernière extension comme joueur',
        stance: 'ambitious',
        riskPreview: 'Tu joues le tout pour le tout sportif.',
        immediate: [fx.res('moral', 4), fx.hidden('ambition', 2)],
        delayed: [
          fx.delayed(1, [
            fx.chance(0.45, [fx.res('forme', 5)]),
            fx.chance(0.55, [fx.res('sante', -8)]),
          ]),
        ],
      }),
    ],
  }),

  dilemma({
    id: 'fin_carriere_dernier_contrat',
    title: 'Dernier contrat à négocier',
    body: 'Un club modeste te propose un contrat d’un an avec un rôle de mentor. Un autre, plus riche, t’offre un salaire élevé mais sans garantie de temps de jeu.',
    category: 'career_end',
    tags: ['retraite', 'contrat'],
    rarity: 'uncommon',
    weight: 30,
    ageMin: 35,
    ageMax: 42,
    careerStages: ['declin', 'fin_contrat', 'retraite'],
    choices: [
      choice({
        id: 'club_modeste',
        label: 'Signer au club modeste avec rôle de mentor',
        stance: 'loyal',
        riskPreview: 'Legacy et transmission, salaire limité.',
        immediate: [fx.cash(5000), fx.hidden('loyaute', 3)],
        delayed: [fx.delayed(2, [fx.rel('teammates', 5)])],
      }),
      choice({
        id: 'club_riche',
        label: 'Choisir le salaire élevé sans garantie sportive',
        stance: 'financial',
        riskPreview: 'Trésorerie confortable, fin en douceur incertaine.',
        immediate: [fx.cash(40000), fx.res('financesPersonnelles', 10)],
        hidden: [fx.res('moral', -3), fx.hidden('professionnalisme', -1)],
      }),
    ],
  }),

  dilemma({
    id: 'fin_carriere_hommage_retraite',
    title: 'Match hommage ou retraite discrète',
    body: 'Le club veut organiser un match hommage pour ta carrière. Tu hésites : accepter la fête ou annoncer une retraite discrète pour éviter le spectacle.',
    category: 'career_end',
    tags: ['retraite', 'hommage'],
    rarity: 'uncommon',
    weight: 28,
    ageMin: 36,
    ageMax: 45,
    careerStages: ['retraite', 'fin_contrat'],
    choices: [
      choice({
        id: 'match_hommage',
        label: 'Accepter le match hommage devant le public',
        stance: 'emotional',
        riskPreview: 'Moment fort, pression émotionnelle énorme.',
        immediate: [fx.res('popularite', 10), fx.rel('fans', 8)],
        delayed: [fx.delayed(1, [fx.res('moral', 5)])],
        hidden: [fx.hidden('grandsMatchs', 2)],
      }),
      choice({
        id: 'retraite_discrete',
        label: 'Annoncer ta retraite par communiqué sobre',
        stance: 'prudent',
        riskPreview: 'Tu contrôles le récit, moins de célébration.',
        immediate: [fx.res('bienEtre', 4), fx.rel('media', -2)],
        hidden: [fx.hidden('resistancePression', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'fin_carriere_corps_limite',
    title: 'Corps au bout du rouleau',
    body: 'Les médecins te disent que chaque saison coûte désormais plusieurs mois de rééducation. Ta famille te demande d’arrêter ; tu envisages encore une dernière année.',
    category: 'injury',
    tags: ['retraite', 'sante'],
    rarity: 'common',
    weight: 34,
    ageMin: 33,
    ageMax: 44,
    careerStages: ['declin', 'retraite'],
    choices: [
      choice({
        id: 'arreter_maintenant',
        label: 'Écouter les médecins et annoncer l’arrêt',
        stance: 'prudent',
        riskPreview: 'Tu préserves ta santé long terme.',
        immediate: [fx.res('sante', 10), fx.rel('family', 6)],
        hidden: [fx.flag('retraite_sante')],
      }),
      choice({
        id: 'derniere_saison',
        label: 'Tenter une dernière saison avec protocole renforcé',
        stance: 'high_risk',
        riskPreview: 'Tu prolonges le rêve, la casse guette.',
        immediate: [fx.res('moral', 6), fx.res('sante', -6)],
        delayed: [
          fx.delayed(2, [
            fx.chance(0.35, [fx.res('reputationSportive', 5)]),
            fx.chance(0.65, [fx.res('sante', -12)]),
          ]),
        ],
      }),
    ],
  }),
]
