import { dilemma, choice, fx } from '../helpers'
import type { DilemmaDefinition } from '../../../game-engine/dilemmas'

/**
 * Dilemmes liés au pays de départ — phase 7.
 * 6 dilemmes, un par pays fictif : chacun ramène le joueur à
 * l’identité du territoire qui l’a formé.
 */
export const paysDilemmas: DilemmaDefinition[] = [
  dilemma({
    id: 'p7_pays_club_pecheurs',
    title: 'Le club des quais prend l’eau',
    body: 'L’appel vient de ton premier éducateur, la voix cassée par le vent des quais : le club de pêcheurs qui t’a formé va déposer le bilan. Les filets qui séchaient derrière le but, les mains gercées, la brume des matchs de huit heures — tout ça peut disparaître avant l’hiver. Il ne demande rien directement. Mais dans la Côte Brumeuse, on n’a jamais eu besoin de demander.',
    category: 'money',
    tags: ['pays', 'racines', 'argent'],
    rarity: 'uncommon',
    weight: 9,
    ageMin: 21,
    ageMax: 39,
    cooldownSeasons: 0,
    unique: true,
    prerequisites: [{ type: 'country', ids: ['cote-brumeuse'] }],
    choices: [
      choice({
        id: 'eponger',
        label: 'Éponger la dette, discrètement',
        stance: 'loyal',
        riskPreview: 'Le club sauvé, ton épargne sérieusement entamée.',
        immediate: [fx.cash(-45000), fx.resource('moral', 6)],
        delayed: [fx.delayed(1, [fx.relation('fans', 5)])],
        hidden: [fx.hidden('loyaute', 4)],
      }),
      choice({
        id: 'gala',
        label: 'Organiser un match de gala sur le port',
        stance: 'collective',
        riskPreview: 'Toute la côte mobilisée, ta trêve sacrifiée.',
        immediate: [
          fx.cash(-8000),
          fx.resource('fatigue', 5),
          fx.resource('popularite', 6),
          fx.relation('fans', 8),
        ],
        hidden: [fx.hidden('loyaute', 2)],
      }),
      choice({
        id: 'chemin',
        label: 'Envoyer tes vœux, garder ton argent',
        stance: 'financial',
        riskPreview: 'Tes finances intactes, un silence qui se remarquera.',
        immediate: [
          fx.resource('financesPersonnelles', 3),
          fx.resource('moral', -4),
          fx.relation('fans', -5),
        ],
        hidden: [fx.hidden('loyaute', -3)],
      }),
    ],
  }),

  dilemma({
    id: 'p7_pays_icone_lumen',
    title: 'Ton visage sur toute la baie',
    body: 'La Baie Lumen vit à la vitesse de ses écrans, et la métropole a choisi son prochain visage : le tien. Façades animées, tramways à ton effigie, campagne « enfant de la baie » sur toutes les plateformes. Le contrat est vertigineux, l’exposition aussi. Ici, une icône ne rate plus jamais un match tranquille : chaque contre-performance devient une affiche géante de trente mètres.',
    category: 'money',
    tags: ['pays', 'image', 'medias'],
    rarity: 'uncommon',
    weight: 9,
    ageMin: 20,
    ageMax: 36,
    cooldownSeasons: 0,
    unique: true,
    prerequisites: [{ type: 'country', ids: ['baie-lumen'] }],
    choices: [
      choice({
        id: 'icone',
        label: 'Devenir le visage de la baie',
        stance: 'media_savvy',
        riskPreview: 'Une notoriété immense, plus aucun match anonyme.',
        immediate: [
          fx.cash(50000),
          fx.resource('popularite', 10),
          fx.relation('sponsors', 8),
          fx.resource('cohesionVestiaire', -5),
        ],
        delayed: [fx.delayed(1, [fx.chance(0.35, [fx.resource('moral', -5)])])],
        hidden: [fx.hidden('ambition', 2)],
      }),
      choice({
        id: 'joueur',
        label: 'Refuser : le terrain d’abord, la ville ensuite',
        stance: 'professional',
        riskPreview: 'Ta bulle préservée, un chèque énorme envolé.',
        immediate: [
          fx.resource('confianceEntraineur', 4),
          fx.resource('cohesionVestiaire', 4),
          fx.resource('popularite', -3),
          fx.relation('sponsors', -5),
        ],
        hidden: [fx.hidden('professionnalisme', 3), fx.hidden('constance', 2)],
      }),
    ],
  }),

  dilemma({
    id: 'p7_pays_altitude_ete',
    title: 'L’été des cimes',
    body: 'Sur les Hauts Plateaux, les anciens le répètent : les grandes saisons se gagnent l’été, en altitude. Cabanes de pierre, souffle court, courses au lever du jour, aucun réseau pour te distraire. Ton préparateur personnel appelle ça du folklore et te propose un programme moderne, capteurs et salle climatisée. Là-haut, pourtant, quelque chose t’a toujours rendu plus dur au mal.',
    category: 'training',
    tags: ['pays', 'preparation', 'racines'],
    rarity: 'common',
    weight: 12,
    ageMin: 18,
    ageMax: 37,
    cooldownSeasons: 3,
    prerequisites: [{ type: 'country', ids: ['hauts-plateaux'] }],
    choices: [
      choice({
        id: 'monter',
        label: 'Monter aux cabanes, comme les anciens',
        stance: 'resilient',
        riskPreview: 'Un mental forgé là-haut, un monde qui t’oublie en bas.',
        immediate: [
          fx.stat('endurance', 2),
          fx.resource('sante', 4),
          fx.resource('bienEtre', 4),
          fx.relation('sponsors', -3),
          fx.resource('popularite', -2),
        ],
        hidden: [fx.hidden('constance', 3)],
      }),
      choice({
        id: 'moderne',
        label: 'Rester en bas : data, capteurs, climatisation',
        stance: 'professional',
        riskPreview: 'Une préparation calibrée, une tradition qui se perd.',
        immediate: [
          fx.stat('vitesse', 1),
          fx.resource('forme', 4),
          fx.cash(-6000),
          fx.resource('bienEtre', -2),
        ],
        hidden: [fx.hidden('professionnalisme', 2), fx.hidden('adaptabilite', 1)],
      }),
    ],
  }),

  dilemma({
    id: 'p7_pays_ferry_supporters',
    title: 'Six heures de mer pour te voir',
    body: 'Tu l’apprends par hasard, dans un article local : les supporters de l’Archipel embarquent avant l’aube sur le vieux ferry, six heures de houle à l’aller, autant au retour, pour chacun de tes matchs sur le continent. Certains font la traversée depuis tes débuts. Personne ne t’a rien demandé — la fierté insulaire ne demande pas. Mais maintenant que tu sais, tu ne peux plus faire comme si.',
    category: 'fans',
    tags: ['pays', 'supporters', 'racines'],
    rarity: 'uncommon',
    weight: 10,
    ageMin: 19,
    ageMax: 39,
    cooldownSeasons: 0,
    unique: true,
    prerequisites: [{ type: 'country', ids: ['archipel-sel'] }],
    choices: [
      choice({
        id: 'affreter',
        label: 'Payer leurs traversées de toute la saison',
        stance: 'loyal',
        riskPreview: 'Un geste immense, une facture à la hauteur.',
        immediate: [
          fx.cash(-30000),
          fx.relation('fans', 12),
          fx.resource('popularite', 5),
        ],
        hidden: [fx.hidden('loyaute', 3)],
      }),
      choice({
        id: 'embarquer',
        label: 'Monter à bord avec eux, un aller sans caméras',
        stance: 'collective',
        riskPreview: 'Six heures de houle dans les jambes avant le match.',
        immediate: [
          fx.relation('fans', 8),
          fx.resource('bienEtre', 3),
          fx.resource('fatigue', 5),
          fx.resource('forme', -2),
        ],
        hidden: [fx.hidden('loyaute', 2)],
      }),
      choice({
        id: 'message',
        label: 'Un message vidéo depuis le vestiaire',
        stance: 'media_savvy',
        riskPreview: 'Un geste propre et sans frais, vite oublié.',
        immediate: [
          fx.relation('fans', 3),
          fx.resource('popularite', 2),
          fx.resource('moral', -2),
        ],
        hidden: [fx.hidden('loyaute', -1)],
      }),
    ],
  }),

  dilemma({
    id: 'p7_pays_terrain_quartier',
    title: 'Le quartier réclame son terrain',
    body: 'Une association de ton quartier d’enfance t’écrit : entre les tours de la Capitale Miroir, le terrain où tu as tout appris n’est plus qu’un rectangle de bitume aux cages sans filets. Ils veulent construire un vrai city couvert et rêvent de ton nom sur le grillage — et de ton argent dans le budget. La ville, toujours prompte à briller, promet déjà une inauguration.',
    category: 'money',
    tags: ['pays', 'racines', 'quartier'],
    rarity: 'uncommon',
    weight: 8,
    ageMin: 23,
    ageMax: 39,
    cooldownSeasons: 0,
    unique: true,
    prerequisites: [{ type: 'country', ids: ['capitale-miroir'] }],
    choices: [
      choice({
        id: 'financer',
        label: 'Financer le terrain de bout en bout',
        stance: 'ethical',
        riskPreview: 'Un legs en dur, des attentes qui ne s’arrêteront plus.',
        immediate: [
          fx.cash(-70000),
          fx.relation('fans', 8),
          fx.resource('popularite', 7),
          fx.resource('moral', 5),
        ],
        delayed: [fx.delayed(1, [fx.chance(0.45, [fx.resource('moral', -4)])])],
        hidden: [fx.hidden('loyaute', 3)],
      }),
      choice({
        id: 'nom',
        label: 'Prêter ton nom, pas ton compte en banque',
        stance: 'prudent',
        riskPreview: 'Un soutien sans risque, un quartier qui compte les gestes.',
        immediate: [
          fx.resource('popularite', 3),
          fx.chance(0.4, [
            fx.relation('fans', -5),
            fx.resource('popularite', -3),
          ]),
        ],
        hidden: [fx.hidden('loyaute', -2)],
      }),
    ],
  }),

  dilemma({
    id: 'p7_pays_brassard_cite',
    title: 'Le brassard de la cité ouvrière',
    body: 'La vieille usine de la Vallée Cendre s’arrête pour de bon : trois générations y ont travaillé, la moitié des tribunes y a laissé son dos. La ville doute d’elle-même pour la première fois. Le capo du virage t’a tendu un brassard cousu main, frappé du marteau de la Forge : le porter samedi, devant les caméras, pour dire que la cité tient debout.',
    category: 'fans',
    tags: ['pays', 'racines', 'symbole'],
    rarity: 'uncommon',
    weight: 9,
    ageMin: 20,
    ageMax: 39,
    cooldownSeasons: 0,
    unique: true,
    prerequisites: [{ type: 'country', ids: ['vallee-cendre'] }],
    choices: [
      choice({
        id: 'porter',
        label: 'Porter le brassard devant tout le stade',
        stance: 'collective',
        riskPreview: 'Une ville derrière toi, des sponsors qui toussent.',
        immediate: [
          fx.relation('fans', 12),
          fx.resource('moral', 5),
          fx.relation('sponsors', -5),
        ],
        delayed: [fx.delayed(1, [fx.chance(0.3, [fx.relation('media', -4)])])],
        hidden: [fx.hidden('loyaute', 3), fx.hidden('resistancePression', 2)],
      }),
      choice({
        id: 'footballeur',
        label: 'Compatir, mais laisser le sport hors de ça',
        stance: 'professional',
        riskPreview: 'Aucune vague, un virage qui s’en souviendra.',
        immediate: [
          fx.relation('sponsors', 3),
          fx.resource('discipline', 3),
          fx.relation('fans', -8),
          fx.resource('moral', -4),
        ],
        hidden: [fx.hidden('professionnalisme', 2), fx.hidden('loyaute', -2)],
      }),
    ],
  }),
]
